-- NAME: SILVER_DMI_PMT_DAILY
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: MARCH 17, 2026

{{
   config(
            materialized='incremental',
            incremental_strategy='append',
            tags=["dmi_standard"]
        )
}}


WITH cte_silver_dmi_pmt AS (
	SELECT
		 LOAN_NUMBER
		,INVESTOR_NUMBER
		,CATEGORY_CODE
		,PMT_TRANSACTION_DATE
		,PMT_TRANSACTION_CODE
		,PMT_PRINCIPAL_AMOUNT
		,PMT_INTEREST_AMOUNT
		,PMT_ESCROW_AMOUNT
		,PMT_TOTAL_AMOUNT
		,PMT_FEE_AMOUNT
		,PMT_FEE_CODE
		,PMT_SUSPENSE_AMOUNT
		,PMT_A_H_INSURANCE_AMOUNT
		,PMT_LIFE_INSURANCE_AMOUNT
		,PMT_RESTRICTED_ESC_AMOUNT
		,PMT_REPLACEMENT_RES
		,PMT_MISC_AMOUNT
		,PMT_HUD_AMOUNT
		,PMT_EFFECTIVE_DATE
		,PMT_BATCH_NUMBER
		,MSP_LAST_RUN_DATE
		,FILE_NAME_DMI
		,DATE_OF_DATA
		,YEARMONTH
	FROM {{ ref('silver_dmi_pmt')}}
		{% if is_incremental() %}
			WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
		{% endif %}
)
SELECT *, GETUTCDATE() AS LOADED_AT FROM cte_silver_dmi_pmt