-- NAME: SILVER_CUSTOMER_Q2
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          tags=["q2_standard"]
        )
}}

WITH bronze_data AS (
    SELECT
		CUSTOMER_ID
		,GROUP_ID
		,GROUP_NAME
		,CUSTOMER_NAME
		,TAX_ID
		,IS_COMPANY
		,IS_TREASURY
		,PRIMARY_CIF
		,SERVICE_CHARGE_PLAN_ID
		,PLAN_NAME
		,CHARGE_ACCOUNT
		,CREATE_DATE
		,STREET_ADDRESS1
		,STREET_ADDRESS2
		,CITY
		,[STATE]
		,POSTAL_CODE
		,PROVINCE
		,IS_INTERNATIONAL
		,ISO_CODE_A3
		,CUSTOMER_DELETED_DATE
		,YEARMONTH
		,GETUTCDATE() LOADED_AT
    FROM {{ ref('bronze_q2_customer') }}
	WHERE CONVERT(date, LOADED_AT) = CONVERT(date, GETUTCDATE())
)

SELECT * FROM bronze_data