-- NAME: SILVER_NICE_REFERENCE_ACTIVITY_SERVICE_TYPE
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: MONTHLY
-- LOAD TYPE: FULL LOAD
-- TYPE: SOURCE
-- DATE: December 23, 2025

{{
   config(
          tags=["Monthly"]
        )
}}

WITH cte_data AS (
  SELECT
      ACTIVITY_SERVICE_TYPE_CD,
      TENANT_CD,
      ACTIVITY_SERVICE_TYPE_DESC,
      CUSTOM_BOOLEAN_01,
      CUSTOM_MEDIUM_STRING_01,
      CUSTOM_SMALL_STRING_01,
      CUSTOM_SMALL_STRING_02,
      CUSTOM_SMALL_STRING_03,
      APP_TRANS_TYPE_CD
  FROM
    {{ ref('bronze_nice_reference_activity_service_type') }}
)

select *, GETUTCDATE() as LOADED_AT FROM cte_data