-- NAME: SILVER_DMI_NON_CASH
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: MARCH 17, 2026

{{
   config(
		  tags=["dmi_standard"]
        )
}}


WITH cte_dmi_non_cash AS (
	SELECT
		 LOAN_NUMBER
		,INVESTOR_NUMBER
		,CATEGORY_CODE
		,NC_TRANSACTION_CODE
		,CONVERT(DATE,NC_TRANSACTION_DATE)								AS NC_TRANSACTION_DATE
		,CONVERT(DECIMAL(12,2),REPLACE(NC_AMOUNT, ',', ''))				AS NC_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(NC_PRINCIPAL_AMOUNT, ',', ''))	AS NC_PRINCIPAL_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(NC_INTEREST_AMOUNT, ',', ''))	AS NC_INTEREST_AMOUNT
		,CONVERT(DATE,MSP_LAST_RUN_DATE) AS MSP_LAST_RUN_DATE
		,FILE_NAME_DMI
	    ,COALESCE(
		    TRY_CONVERT(
		        DATE,
		        CONCAT(
		            '20',
		            SUBSTRING(FILE_NAME_DMI, 13, 2), -- YY
		            '-',
		            SUBSTRING(FILE_NAME_DMI, 9, 2),  -- MM
		            '-',
		            SUBSTRING(FILE_NAME_DMI, 11, 2)  -- DD
		        )
		    ),
		    CONVERT(DATE, NC_TRANSACTION_DATE)
		) AS DATE_OF_DATA
	FROM {{ ref('bronze_dmi_non_cash')}}
	WHERE
	    CONVERT(DATE,LOADED_AT) = (SELECT MAX(CONVERT(DATE,LOADED_AT)) FROM {{ ref('bronze_dmi_non_cash')}})
)

SELECT *,CONVERT(VARCHAR(6), DATE_OF_DATA, 112) AS YEARMONTH, GETUTCDATE() AS LOADED_AT FROM cte_dmi_non_cash