-- NAME: SILVER_REFERENCETABLE_ACCF
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: July 01, 2024

{{
   config(
		  tags=["pershing_standard"]
        )
}}

WITH bronze_data AS (
    SELECT
        TRANSCODE
        ,RECORDIND
        ,RECORDSEQUENCEID
        ,ACCTNUMBER
        ,BROKERDEALERNUMBER
        ,INVESTMENTPRONUMBER
        ,ACCOUNTSHORTNAME
        ,TRANSACTIONTYPE
        ,AUTOTITLEDACCT
        ,ACCTTYPECODE
        ,REGISTRATIONTYPE
        ,NUMBERACCTTITLELINES
        ,ACCTREGISLINE1
        ,ACCTREGISLINE2
        ,ACCTREGISLINE3
        ,ACCTREGISLINE4
        ,ACCTREGISLINE5
        ,ACCTREGISLINE6
        ,USTENANCYINDICATOR
        ,MARRIEDINDICATOR
        ,TENANCYSTATE
        ,JOINTTENANCYCLAUSE
        ,AGREEMENTEXEDATE
        ,NUMBEROFTENANTS
        ,DATEACCTOPENED
        ,DATEACCTINFOUPDATED
        ,ACCTSTATUSINDICATOR
        ,PENDINGCLOSEDDATE
        ,DATEACCOUNTCLOSED
        ,ACCTREACTIVATEDDATE
        ,DATEACCOUNTREOPENED
        ,PROCEEDS
        ,TRANSINSTRUC
        ,INCOMEINSTRUC
        ,NUMBCONFIRMS
        ,NUMBSTATEMENTS
        ,INVESOBJTRANSCODE
        ,COMMENTS
        ,EMPLOYERSHORTNAME
        ,EMPLOYERCUSIP
        ,EMPLOYERSYMBOL
        ,MARPRIVREVOKED
        ,STATEREVIEWDATE
        ,MARPAPERSFILE
        ,OPTPAPERSFILE
        ,GOODFAITHMARGIN
        ,INVESTPRODISCRGRANTED
        ,INVESTADVDISCRGRANTED
        ,THIRDPARTYDISCGRANTED
        ,THIRDPARTYNAME
        ,RISKFACTORCODE
        ,INVESTOBJCODE
        ,OPTIONEQUITIES
        ,OPTIONINDEX
        ,OPTIONDEBT
        ,OPTIONCURRENCY
        ,OPTIONLEVEL1
        ,OPTIONLEVEL2
        ,OPTIONLEVEL3
        ,OPTIONLEVEL4
        ,OPTIONCALLLIMITS
        ,OPTIONPUTLIMITS
        ,OPTIONLIMITSPUTSCALLS
        ,NONUSDOLLARTRADING
        ,NONCUSTOMERINDICATOR
        ,THIRDPARTYFEEINDICATOR
        ,THIRDPARTYFEEAPPRDATE
        ,INTERMEDIARYACCTIND
        ,COMMISSIONSCHEDULE
        ,GROUPINDEX
        ,MONEYMANAGERID
        ,MONEYMANAGEROBJID
        ,DTCIDCONFIRMNUMBER
        ,CAPSMASTERMNEMONIC
        ,EMPLOYEEID
        ,PRIMEBROKERFREEFUNDIND
        ,FEEBASEDACCTIND
        ,BILLINGTYPE
        ,FEEBASEDTERMDATE
        ,PLANNAME
        ,SELFDIRECTED
        ,PLANTYPE
        ,PLANNUMBER
        ,EMPLOYEERELAIND
        ,COMMISSPERCDISC
        ,BLOCKMUTFUNDFEES
        ,NAMEINVESTPRO
        ,DATEINVESTPRO
        ,NAMEPRINCIPALSIGNED
        ,DATEPRINCIPALSIGNED
        ,POLITEXPOSEDPERSON
        ,PRIVATEBANKACCTIND
        ,FOREIGNBANKACCTIND
        ,INITIALSOURCEFUNDS
        ,USAPATACTEXEMPTREASON
        ,PRIMARYCOUNTRYCTZ
        ,COUNTRYRESIDENCE
        ,BIRTHDATE
        ,AGEBASEDFUNDROLLEXEMPTIND
        ,MONEYFUNDREFORMRETAIL
        ,TRUSTEDCONTACTSTATUS
        ,FULFILLMENTMETHOD
        ,CREDITINTERESTIND
        ,AMAIND
        ,DATEOFDATA
        ,CONVERT(INT, CONVERT(nvarchar(6), LOADED_AT, 112)) AS YEARMONTH
        ,GETUTCDATE() LOADED_AT
    FROM {{ ref('bronze_pers_accf') }}
    WHERE CONVERT(date, LOADED_AT) = CONVERT(date, GETUTCDATE())
)
SELECT * FROM bronze_data