-- NAME: SILVER_DMI_E006_DATA_X09
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: MARCH 17, 2026

{{
   config(
		  tags=["dmi_standard"]
        )
}}


WITH cte_silver_dmi_pmt AS (
	SELECT
		 LOAN_NUMBER
		,INVESTOR_NUMBER
		,CATEGORY_CODE
		,CONVERT(DATE,PMT_TRANSACTION_DATE) AS PMT_TRANSACTION_DATE
		,PMT_TRANSACTION_CODE
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_PRINCIPAL_AMOUNT, ',', ''))		AS PMT_PRINCIPAL_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_INTEREST_AMOUNT, ',', ''))		AS PMT_INTEREST_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_ESCROW_AMOUNT, ',', ''))			AS PMT_ESCROW_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_TOTAL_AMOUNT, ',', ''))			AS PMT_TOTAL_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_FEE_AMOUNT, ',', ''))			AS PMT_FEE_AMOUNT
		,PMT_FEE_CODE
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_SUSPENSE_AMOUNT, ',', ''))		AS PMT_SUSPENSE_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_A_H_INSURANCE_AMOUNT, ',', ''))	AS PMT_A_H_INSURANCE_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_LIFE_INSURANCE_AMOUNT, ',', ''))	AS PMT_LIFE_INSURANCE_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_RESTRICTED_ESC_AMOUNT, ',', ''))	AS PMT_RESTRICTED_ESC_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_REPLACEMENT_RES, ',', ''))		AS PMT_REPLACEMENT_RES
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_MISC_AMOUNT, ',', ''))			AS PMT_MISC_AMOUNT
		,CONVERT(DECIMAL(12,2),REPLACE(PMT_HUD_AMOUNT, ',', ''))			AS PMT_HUD_AMOUNT
		,CONVERT(DATE,PMT_EFFECTIVE_DATE)									AS PMT_EFFECTIVE_DATE
		,PMT_BATCH_NUMBER
		,CONVERT(DATE,MSP_LAST_RUN_DATE)									AS MSP_LAST_RUN_DATE
		,FILE_NAME_DMI
		,COALESCE(
		    TRY_CONVERT(
		        DATE,
		        CONCAT(
		            '20',
		            SUBSTRING(FILE_NAME_DMI, 9, 2), -- YY
		            '-',
		            SUBSTRING(FILE_NAME_DMI, 5, 2), -- MM
		            '-',
		            SUBSTRING(FILE_NAME_DMI, 7, 2)  -- DD
		        )
		    ),
		    CONVERT(DATE,PMT_TRANSACTION_DATE)
		) AS DATE_OF_DATA
	FROM {{ ref('bronze_dmi_pmt')}}
	WHERE
	    CONVERT(DATE,LOADED_AT) = (SELECT MAX(CONVERT(DATE,LOADED_AT)) FROM {{ ref('bronze_dmi_pmt')}})
)

SELECT *,CONVERT(VARCHAR(6), DATE_OF_DATA, 112) AS YEARMONTH, GETUTCDATE() AS LOADED_AT FROM cte_silver_dmi_pmt