-- NAME: SILVER_NICE_REFERENCE_ACCOUNT_CLASSIFICATION
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: MONTHLY
-- LOAD TYPE: FULL LOAD
-- TYPE: SOURCE
-- DATE: December 23, 2025

{{
   config(
          tags=["Monthly"]
        )
}}

WITH cte_data AS (
  SELECT
      ACCOUNT_CLASSIFICATION_CD,
      TENANT_CD,
      ACCOUNT_CLASSIFICATION_DESC,
      SHORT_NAME,
      [DEFINITION],
      ACCOUNT_CLASSIFICATION_DV,
      CUSTOM_BOOLEAN_01,
      CUSTOM_MEDIUM_STRING_01,
      CUSTOM_SMALL_STRING_01,
      CUSTOM_SMALL_STRING_02,
      CUSTOM_SMALL_STRING_03
  FROM
    {{ ref('bronze_nice_reference_account_classification') }}
)

select *, GETUTCDATE() as LOADED_AT FROM cte_data