-- NAME: SILVER_INTRAFI_ACCOUNT_TRIAL_BALANCE_DAILY
-- CATEGORY: MODEL
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: April 1, 2026

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["promontory_standard"]
        )
}}

WITH
bronze_data AS (
    SELECT
        INSTITUTION_TRANSACTION_ACCOUNT_NO,
        ICS_ACCOUNT_ID,
        SHADOW_ACCOUNT_NO,
        ACCOUNT_TITLE,
        PRIMARY_CUSTOMER_TAX_ID,
        INTERNAL_CUSTOMER_ID,
        PRINCIPAL_BALANCE,
        ACCRUED_INTEREST,
        DAILY_ACCRUAL,
        INTEREST_PAID_TODAY,
        INTEREST_PAID_MTD,
        ICS_DEPOSIT_OPTION,
        PROGRAM_NAME,
        RATE_DESCRIPTION,
        CURRENT_PROGRAM_INTEREST_RATE,
        OWS_RATE,
        RATE_APPLIED_TODAY,
        PROGRAM_WITHDRAWALS_MTD,
        TOTAL_PROGRAM_WITHDRAWAL_VIOLATIONS,
        AVERAGE_DAILY_BALANCE_MTD,
        AVERAGE_DAILY_BALANCE_YTD,
        AVERAGE_RECIPROCAL_DAILY_BALANCE_MTD,
        AVERAGE_RECIPROCAL_DAILY_BALANCE_YTD,
        AVERAGE_OWS_DAILY_BALANCE_MTD,
        AVERAGE_OWS_DAILY_BALANCE_YTD,
        NUMBER_OF_DAYS_AS_A_RECIPROCAL_ACCOUNT_MTD,
        NUMBER_OF_DAYS_AS_A_OWS_ACCOUNT_MTD,
        INTEREST_PAID_YTD,
        INTEREST_PAID_LAST_YEAR,
        BRANCH_ID__NAME,
        INSTITUTION_SALES_CONTACT,
        DATE_ICS_ACCOUNT_OPENED,
        DATE_LAST_TRANSACTION,
        ACCOUNT_STATUS,
        ACCOUNT_TYPE,
        MTD_FEE_INCOME,
        YTD_FEE_INCOME,
        MTD_FEE_EXPENSE,
        YTD_FEE_EXPENSE,
        OWNERSHIP_RIGHT_AND_CAPACITY_CODES,
        LIQUIDITY_COVERAGE_RATIO_LCR_CATEGORY,
        MAIL_CUSTOMER_STATEMENTS_ON_BEHALF_OF_YOUR_INSTITUTION,
        ICS_SAVINGS_CUSTOM_FIELD_,
        DATE_OF_DATA
    FROM {{ ref('bronze_intrafi_account_trial_balance') }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT bd.*, GETUTCDATE() AS LOADED_AT  
FROM bronze_data bd