-- NAME: SILVER_NICE_REFERENCE_BSA_ADDITIONAL_CUSTOMER_DATA
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: MONTHLY
-- LOAD TYPE: FULL LOAD
-- TYPE: SOURCE
-- DATE: February 20, 2025

{{
   config(
          tags=["Monthly"]
        )
}}

SELECT
  CIFNO,
  IS_PEP,
  PEP_TARGET_TYPE_CD,
  IS_CORRESPONDENT_BANK,
  PEP_STATUS_CD,
  PEP_POSITION_CD,
  NO_OF_SAR,
  NO_OF_SUBPOENA,
  IS_PSP,
  IS_NGO,
  IS_TPPP,
  IS_CIB,
  IS_POATM,
  LAST_REVIEW_DATE,
  INITIAL_RISK_LEVEL,
  CREATED_AT,
  CREATED_BY,
  UPDATED_AT,
  UPDATED_BY,
	GETUTCDATE() AS LOADED_AT
FROM
  {{ ref('bronze_nice_reference_bsa_additional_customer_data') }}