-- NAME: SILVER_CUSTOMER_USER_PII_Q2
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: SILVER
-- FREQUENCY: DAILY
-- LOAD TYPE: FULL LOAD
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          tags=["q2_standard"]
        )
}}

WITH bronze_data AS (
    SELECT
    	USER_ID
		,PRIMARY_CIF
		,LAST_NAME
		,FIRST_NAME
		,MIDDLE_NAME
		,SALUTATION
		,SUFFIX
		,SOCIAL_SECURITY_NUMBER
		,EMAIL_ADDRESS
		,STREET_ADDRESS_1
		,STREET_ADDRESS_2
		,CITY
		,[STATE]
		,POSTAL_CODE
		,PROVINCE
		,IS_INTERNATIONAL
		,ISO_CODE_A3
		,YEARMONTH
		,GETUTCDATE() LOADED_AT
    FROM {{ ref('bronze_q2_user_pii') }}
	WHERE CONVERT(date, LOADED_AT) = CONVERT(date, GETUTCDATE())
)

SELECT * FROM bronze_data