-- Databricks SQL for source: dmi
-- Generated from sqlserver/brz-dmi.sql

CREATE CATALOG IF NOT EXISTS dmi;
USE CATALOG dmi;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."DMI_BACMAST"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_bacmast (
    `LOAN` STRING,
    `OLDLOANNO` STRING,
    `BILLNAME` STRING,
    `BANK` STRING,
    `AGGR` STRING,
    `NEXTDUE` STRING,
    `FIRSTPB` STRING,
    `ORGMTGAMT` STRING,
    `LOANDATE` DATE,
    `MATDATE` DATE,
    `CASE` STRING,
    `WHEN` STRING,
    `THEN` STRING,
    `ELSE` STRING,
    `ANNUALINT` STRING,
    `LOANTERM` STRING,
    `REMTERM` STRING,
    `PRODLINECD` STRING,
    `ARMIND` STRING,
    `ARMINDESC` STRING,
    `ORGPROPVAL` STRING,
    `PROPVAL` STRING,
    `PROPERTYST` STRING,
    `PROPERTYCT` STRING,
    `PROPSTATE` STRING,
    `PROPZIP` STRING,
    `SSNCODE` STRING,
    `PTFNMACODE` STRING,
    `PTFNMADESC` STRING,
    `INVESTLOAN` STRING,
    `OCCCODE` STRING,
    `OCCUDESC` STRING,
    `LNPURPCODE` STRING,
    `LNPURPDESC` STRING,
    `HITYPE` STRING,
    `HITYPEDESC` STRING,
    `LOTYPE` STRING,
    `LOTYPEDESC` STRING,
    `FIRSTDUE` STRING,
    `FIRSTPI` STRING,
    `FSTSERFEE` DECIMAL(38,10),
    `FORECLSCOD` STRING,
    `FORECLSDES` STRING,
    `ORGLTV` DECIMAL(38,10),
    `INTPDTHRU` STRING,
    `ESCROWBAL` DECIMAL(38,10),
    `ESCROWADV` DECIMAL(38,10),
    `PLGCODE` STRING,
    `PLGDESC` STRING,
    `PMNTPERD` STRING,
    `BADCHKTBLE` STRING,
    `TIMESDLQ` STRING,
    `TOTPMNT` STRING,
    `NOOFUNIT` STRING,
    `INTFLAG` STRING,
    `INTFLAGDES` STRING,
    `CAPLNFLAG` STRING,
    `CAPLNFDESC` STRING,
    `MTGRLNAME` STRING,
    `MTGRFNAME` STRING,
    `MTGRHAZPAY` STRING,
    `TIPMNT` STRING,
    `GUARFEE` DECIMAL(38,10),
    `RECFLAG` STRING,
    `RECFLAGDES` STRING,
    `POOLNUM` STRING,
    `DLQPMNTCNT` STRING,
    `IOEFLAG` STRING,
    `IOEFLAGDES` STRING,
    `MANCODE` STRING,
    `BBCODE` STRING,
    `BRNCHOFF` STRING,
    `ACRLSTAT` STRING,
    `PREPMNTIND` STRING,
    `FHLBBPP` STRING,
    `FSTORGCOST` DECIMAL(38,10),
    `FSTORIGFEE` DECIMAL(38,10),
    `FSTUNAMORT` STRING,
    `ARMIREFFDT` STRING,
    `ARMORGIR` STRING,
    `ARMMARGIN` STRING,
    `ARMPIEFFDT` STRING,
    `ARMCHGPRD` STRING,
    `ARMPICHGPR` STRING,
    `ARMIRMAXCL` STRING,
    `ARMIRMAXFL` STRING,
    `ARMIMAXINC` STRING,
    `ARMIMAXDEC` STRING,
    `AIRMAXLINC` STRING,
    `AIRMAXLDEC` STRING,
    `APIMAXPCTI` STRING,
    `APIMAXPCTD` STRING,
    `APIMAXLIFE` STRING,
    `APIPCTMINC` STRING,
    `APIPCTMDEC` STRING,
    `AORGPIAMT` STRING,
    `ARMINDEX` STRING,
    `ARMIRRATE` DECIMAL(38,10),
    `AOIRCHGDT` STRING,
    `AIRRNDTP` STRING,
    `AIRRNDDESC` STRING,
    `AIRRNDFACT` STRING,
    `ARMPLANID` STRING,
    `ARMPLANDES` STRING,
    `ARMINDCO` STRING,
    `ARMINDDESC` STRING,
    `AILEADDAYS` STRING,
    `USR15POS1` STRING,
    `USR2POS1A` STRING,
    `USR2POS2A` STRING,
    `DFTIND` STRING,
    `BANKNAME` STRING,
    `LOT` STRING,
    `BLOCK` STRING,
    `SUBDIV` STRING,
    `COUNTYCODE` STRING,
    `COUNTYTAX` STRING,
    `HAZMONTHLY` STRING,
    `LASTANALDT` STRING,
    `ESCMINBALC` STRING,
    `LASTANALOS` STRING,
    `OVSHTCHGDT` STRING,
    `MORTSSNO` STRING,
    `COMORTSSNO` STRING,
    `SSNCERTDT` STRING,
    `SSNVERCODE` STRING,
    `SSNVERDATE` DATE,
    `SETUPDATE` DATE,
    `SUSPBAL` STRING,
    `RESTESCBAL` STRING,
    `CRQUALCODE` STRING,
    `INTONLYIND` STRING,
    `PAYFULLDT` STRING,
    `SERVSOLDDT` STRING,
    `COMTGLNAME` STRING,
    `COMTGFNAME` STRING,
    `FLOZPOS1` STRING,
    `MTGRDOB` STRING,
    `COMTGRDOB` STRING,
    `PROPUNITNO` STRING,
    `LTV` DECIMAL(38,10),
    `BILLADDR3` STRING,
    `BILLADDR4` STRING,
    `BILLCITY` STRING,
    `BILLSTATE` STRING,
    `BILLZIP` STRING,
    `ORIGSCORE` STRING,
    `BILLADDR2` STRING,
    `USR1POS3A` STRING,
    `CHGOFFBAL` STRING,
    `ACC_LATECA` STRING,
    `LATECF` STRING,
    `GRACEDAYS` STRING,
    `LCCODE` STRING,
    `PHONE` STRING,
    `PHONE2` STRING,
    `EMAILF` STRING,
    `PROCSC` STRING,
    `DAIND` STRING,
    `CSBORCBC` STRING,
    `CSBORCBST` STRING,
    `FIRSTFF1` STRING,
    `ASSUMDATE` DATE,
    `VACDATE` DATE,
    `LNMODDATE` DATE,
    `USR20POS1A` STRING,
    `RECOVERCAB` STRING,
    `NONRECCAB` STRING,
    `THIRDPRCB` STRING,
    `PENDPIAMT` STRING,
    `ADLCBN1` STRING,
    `ADLCSTN1` STRING,
    `ADLCBS` STRING,
    `ADLCBC` STRING,
    `ADLCBST` STRING,
    `ADLCBZC` STRING,
    `ADLCBPN` STRING,
    `LASTFPAYDT` STRING,
    `YTDINTAMT` STRING,
    `YTDPPAMT` STRING,
    `YTDTAXAMT` STRING,
    `YTDHAZAMT` STRING,
    `USR1PO4A` STRING,
    `DAYDELIQUE` STRING,
    `ENTERNONAC` STRING,
    `LEAVENONAC` STRING,
    `APPRAIDATE` DATE,
    `LNMOAPPDAT` STRING,
    `LNMOAPPAMT` STRING,
    `CHAROFFDAT` STRING,
    `DRROUTRNUM` STRING,
    `FIORCOSAMT` STRING,
    `FIORFEEAMT` DECIMAL(38,10),
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_bacmast IS 
'The table contains loan details and associated characteristics. It includes information such as loan amounts, terms, important dates, and borrower details. This data can be utilized for analyzing loan portfolios, tracking payment schedules, and understanding borrower behavior.';

TRUNCATE TABLE dmi.default.dmi_bacmast;

INSERT INTO dmi.default.dmi_bacmast (
    `LOAN`, `OLDLOANNO`, `BILLNAME`, `BANK`, `AGGR`, `NEXTDUE`,
    `FIRSTPB`, `ORGMTGAMT`, `LOANDATE`, `MATDATE`, `CASE`, `WHEN`,
    `THEN`, `ELSE`, `ANNUALINT`, `LOANTERM`, `REMTERM`, `PRODLINECD`,
    `ARMIND`, `ARMINDESC`, `ORGPROPVAL`, `PROPVAL`, `PROPERTYST`, `PROPERTYCT`,
    `PROPSTATE`, `PROPZIP`, `SSNCODE`, `PTFNMACODE`, `PTFNMADESC`, `INVESTLOAN`,
    `OCCCODE`, `OCCUDESC`, `LNPURPCODE`, `LNPURPDESC`, `HITYPE`, `HITYPEDESC`,
    `LOTYPE`, `LOTYPEDESC`, `FIRSTDUE`, `FIRSTPI`, `FSTSERFEE`, `FORECLSCOD`,
    `FORECLSDES`, `ORGLTV`, `INTPDTHRU`, `ESCROWBAL`, `ESCROWADV`, `PLGCODE`,
    `PLGDESC`, `PMNTPERD`, `BADCHKTBLE`, `TIMESDLQ`, `TOTPMNT`, `NOOFUNIT`,
    `INTFLAG`, `INTFLAGDES`, `CAPLNFLAG`, `CAPLNFDESC`, `MTGRLNAME`, `MTGRFNAME`,
    `MTGRHAZPAY`, `TIPMNT`, `GUARFEE`, `RECFLAG`, `RECFLAGDES`, `POOLNUM`,
    `DLQPMNTCNT`, `IOEFLAG`, `IOEFLAGDES`, `MANCODE`, `BBCODE`, `BRNCHOFF`,
    `ACRLSTAT`, `PREPMNTIND`, `FHLBBPP`, `FSTORGCOST`, `FSTORIGFEE`, `FSTUNAMORT`,
    `ARMIREFFDT`, `ARMORGIR`, `ARMMARGIN`, `ARMPIEFFDT`, `ARMCHGPRD`, `ARMPICHGPR`,
    `ARMIRMAXCL`, `ARMIRMAXFL`, `ARMIMAXINC`, `ARMIMAXDEC`, `AIRMAXLINC`, `AIRMAXLDEC`,
    `APIMAXPCTI`, `APIMAXPCTD`, `APIMAXLIFE`, `APIPCTMINC`, `APIPCTMDEC`, `AORGPIAMT`,
    `ARMINDEX`, `ARMIRRATE`, `AOIRCHGDT`, `AIRRNDTP`, `AIRRNDDESC`, `AIRRNDFACT`,
    `ARMPLANID`, `ARMPLANDES`, `ARMINDCO`, `ARMINDDESC`, `AILEADDAYS`, `USR15POS1`,
    `USR2POS1A`, `USR2POS2A`, `DFTIND`, `BANKNAME`, `LOT`, `BLOCK`,
    `SUBDIV`, `COUNTYCODE`, `COUNTYTAX`, `HAZMONTHLY`, `LASTANALDT`, `ESCMINBALC`,
    `LASTANALOS`, `OVSHTCHGDT`, `MORTSSNO`, `COMORTSSNO`, `SSNCERTDT`, `SSNVERCODE`,
    `SSNVERDATE`, `SETUPDATE`, `SUSPBAL`, `RESTESCBAL`, `CRQUALCODE`, `INTONLYIND`,
    `PAYFULLDT`, `SERVSOLDDT`, `COMTGLNAME`, `COMTGFNAME`, `FLOZPOS1`, `MTGRDOB`,
    `COMTGRDOB`, `PROPUNITNO`, `LTV`, `BILLADDR3`, `BILLADDR4`, `BILLCITY`,
    `BILLSTATE`, `BILLZIP`, `ORIGSCORE`, `BILLADDR2`, `USR1POS3A`, `CHGOFFBAL`,
    `ACC_LATECA`, `LATECF`, `GRACEDAYS`, `LCCODE`, `PHONE`, `PHONE2`,
    `EMAILF`, `PROCSC`, `DAIND`, `CSBORCBC`, `CSBORCBST`, `FIRSTFF1`,
    `ASSUMDATE`, `VACDATE`, `LNMODDATE`, `USR20POS1A`, `RECOVERCAB`, `NONRECCAB`,
    `THIRDPRCB`, `PENDPIAMT`, `ADLCBN1`, `ADLCSTN1`, `ADLCBS`, `ADLCBC`,
    `ADLCBST`, `ADLCBZC`, `ADLCBPN`, `LASTFPAYDT`, `YTDINTAMT`, `YTDPPAMT`,
    `YTDTAXAMT`, `YTDHAZAMT`, `USR1PO4A`, `DAYDELIQUE`, `ENTERNONAC`, `LEAVENONAC`,
    `APPRAIDATE`, `LNMOAPPDAT`, `LNMOAPPAMT`, `CHAROFFDAT`, `DRROUTRNUM`, `FIORCOSAMT`,
    `FIORFEEAMT`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('LOAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOAN`,
    concat('OLDLOANNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `OLDLOANNO`,
    concat('BILLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLNAME`,
    concat('BANK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANK`,
    concat('AGGR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AGGR`,
    concat('NEXTDUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NEXTDUE`,
    concat('FIRSTPB_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTPB`,
    concat('ORGMTGAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGMTGAMT`,
    date_add(DATE '2026-01-01', idx - 1) AS `LOANDATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `MATDATE`,
    concat('CASE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CASE`,
    concat('WHEN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WHEN`,
    concat('THEN_', lpad(CAST(idx AS STRING), 2, '0')) AS `THEN`,
    concat('ELSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ELSE`,
    concat('ANNUALINT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ANNUALINT`,
    concat('LOANTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOANTERM`,
    concat('REMTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `REMTERM`,
    concat('PRODLINECD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODLINECD`,
    concat('ARMIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIND`,
    concat('ARMINDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDESC`,
    concat('ORGPROPVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGPROPVAL`,
    concat('PROPVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPVAL`,
    concat('PROPERTYST_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPERTYST`,
    concat('PROPERTYCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPERTYCT`,
    concat('PROPSTATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPSTATE`,
    concat('PROPZIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPZIP`,
    concat('SSNCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNCODE`,
    concat('PTFNMACODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTFNMACODE`,
    concat('PTFNMADESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTFNMADESC`,
    concat('INVESTLOAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `INVESTLOAN`,
    concat('OCCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OCCCODE`,
    concat('OCCUDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OCCUDESC`,
    concat('LNPURPCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNPURPCODE`,
    concat('LNPURPDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNPURPDESC`,
    concat('HITYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITYPE`,
    concat('HITYPEDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITYPEDESC`,
    concat('LOTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOTYPE`,
    concat('LOTYPEDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOTYPEDESC`,
    concat('FIRSTDUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTDUE`,
    concat('FIRSTPI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTPI`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FSTSERFEE`,
    concat('FORECLSCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `FORECLSCOD`,
    concat('FORECLSDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `FORECLSDES`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ORGLTV`,
    concat('INTPDTHRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `INTPDTHRU`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ESCROWBAL`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ESCROWADV`,
    concat('PLGCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLGCODE`,
    concat('PLGDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLGDESC`,
    concat('PMNTPERD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMNTPERD`,
    concat('BADCHKTBLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BADCHKTBLE`,
    concat('TIMESDLQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `TIMESDLQ`,
    concat('TOTPMNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `TOTPMNT`,
    concat('NOOFUNIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOOFUNIT`,
    concat('INTFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `INTFLAG`,
    concat('INTFLAGDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `INTFLAGDES`,
    concat('CAPLNFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAPLNFLAG`,
    concat('CAPLNFDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAPLNFDESC`,
    concat('MTGRLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRLNAME`,
    concat('MTGRFNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRFNAME`,
    concat('MTGRHAZPAY_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRHAZPAY`,
    concat('TIPMNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `TIPMNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `GUARFEE`,
    concat('RECFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECFLAG`,
    concat('RECFLAGDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECFLAGDES`,
    concat('POOLNUM_', lpad(CAST(idx AS STRING), 2, '0')) AS `POOLNUM`,
    concat('DLQPMNTCNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `DLQPMNTCNT`,
    concat('IOEFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `IOEFLAG`,
    concat('IOEFLAGDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `IOEFLAGDES`,
    concat('MANCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `MANCODE`,
    concat('BBCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBCODE`,
    concat('BRNCHOFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BRNCHOFF`,
    concat('ACRLSTAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRLSTAT`,
    concat('PREPMNTIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPMNTIND`,
    concat('FHLBBPP_', lpad(CAST(idx AS STRING), 2, '0')) AS `FHLBBPP`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FSTORGCOST`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FSTORIGFEE`,
    concat('FSTUNAMORT_', lpad(CAST(idx AS STRING), 2, '0')) AS `FSTUNAMORT`,
    concat('ARMIREFFDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIREFFDT`,
    concat('ARMORGIR_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMORGIR`,
    concat('ARMMARGIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMMARGIN`,
    concat('ARMPIEFFDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPIEFFDT`,
    concat('ARMCHGPRD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMCHGPRD`,
    concat('ARMPICHGPR_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPICHGPR`,
    concat('ARMIRMAXCL_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIRMAXCL`,
    concat('ARMIRMAXFL_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIRMAXFL`,
    concat('ARMIMAXINC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIMAXINC`,
    concat('ARMIMAXDEC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIMAXDEC`,
    concat('AIRMAXLINC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRMAXLINC`,
    concat('AIRMAXLDEC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRMAXLDEC`,
    concat('APIMAXPCTI_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXPCTI`,
    concat('APIMAXPCTD_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXPCTD`,
    concat('APIMAXLIFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXLIFE`,
    concat('APIPCTMINC_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIPCTMINC`,
    concat('APIPCTMDEC_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIPCTMDEC`,
    concat('AORGPIAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AORGPIAMT`,
    concat('ARMINDEX_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDEX`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ARMIRRATE`,
    concat('AOIRCHGDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AOIRCHGDT`,
    concat('AIRRNDTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDTP`,
    concat('AIRRNDDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDDESC`,
    concat('AIRRNDFACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDFACT`,
    concat('ARMPLANID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPLANID`,
    concat('ARMPLANDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPLANDES`,
    concat('ARMINDCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDCO`,
    concat('ARMINDDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDDESC`,
    concat('AILEADDAYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `AILEADDAYS`,
    concat('USR15POS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR15POS1`,
    concat('USR2POS1A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR2POS1A`,
    concat('USR2POS2A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR2POS2A`,
    concat('DFTIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `DFTIND`,
    concat('BANKNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANKNAME`,
    concat('LOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOT`,
    concat('BLOCK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BLOCK`,
    concat('SUBDIV_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUBDIV`,
    concat('COUNTYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `COUNTYCODE`,
    concat('COUNTYTAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `COUNTYTAX`,
    concat('HAZMONTHLY_', lpad(CAST(idx AS STRING), 2, '0')) AS `HAZMONTHLY`,
    concat('LASTANALDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LASTANALDT`,
    concat('ESCMINBALC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ESCMINBALC`,
    concat('LASTANALOS_', lpad(CAST(idx AS STRING), 2, '0')) AS `LASTANALOS`,
    concat('OVSHTCHGDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVSHTCHGDT`,
    concat('MORTSSNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `MORTSSNO`,
    concat('COMORTSSNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMORTSSNO`,
    concat('SSNCERTDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNCERTDT`,
    concat('SSNVERCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNVERCODE`,
    date_add(DATE '2026-01-01', idx - 1) AS `SSNVERDATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `SETUPDATE`,
    concat('SUSPBAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUSPBAL`,
    concat('RESTESCBAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `RESTESCBAL`,
    concat('CRQUALCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRQUALCODE`,
    concat('INTONLYIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `INTONLYIND`,
    concat('PAYFULLDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAYFULLDT`,
    concat('SERVSOLDDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `SERVSOLDDT`,
    concat('COMTGLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGLNAME`,
    concat('COMTGFNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGFNAME`,
    concat('FLOZPOS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `FLOZPOS1`,
    concat('MTGRDOB_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRDOB`,
    concat('COMTGRDOB_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGRDOB`,
    concat('PROPUNITNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPUNITNO`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LTV`,
    concat('BILLADDR3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR3`,
    concat('BILLADDR4_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR4`,
    concat('BILLCITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLCITY`,
    concat('BILLSTATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLSTATE`,
    concat('BILLZIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLZIP`,
    concat('ORIGSCORE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGSCORE`,
    concat('BILLADDR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR2`,
    concat('USR1POS3A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR1POS3A`,
    concat('CHGOFFBAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHGOFFBAL`,
    concat('ACC_LATECA_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACC_LATECA`,
    concat('LATECF_', lpad(CAST(idx AS STRING), 2, '0')) AS `LATECF`,
    concat('GRACEDAYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `GRACEDAYS`,
    concat('LCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LCCODE`,
    concat('PHONE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHONE`,
    concat('PHONE2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHONE2`,
    concat('EMAILF_', lpad(CAST(idx AS STRING), 2, '0')) AS `EMAILF`,
    concat('PROCSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROCSC`,
    concat('DAIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `DAIND`,
    concat('CSBORCBC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CSBORCBC`,
    concat('CSBORCBST_', lpad(CAST(idx AS STRING), 2, '0')) AS `CSBORCBST`,
    concat('FIRSTFF1_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTFF1`,
    date_add(DATE '2026-01-01', idx - 1) AS `ASSUMDATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `VACDATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `LNMODDATE`,
    concat('USR20POS1A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR20POS1A`,
    concat('RECOVERCAB_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECOVERCAB`,
    concat('NONRECCAB_', lpad(CAST(idx AS STRING), 2, '0')) AS `NONRECCAB`,
    concat('THIRDPRCB_', lpad(CAST(idx AS STRING), 2, '0')) AS `THIRDPRCB`,
    concat('PENDPIAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PENDPIAMT`,
    concat('ADLCBN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBN1`,
    concat('ADLCSTN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCSTN1`,
    concat('ADLCBS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBS`,
    concat('ADLCBC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBC`,
    concat('ADLCBST_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBST`,
    concat('ADLCBZC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBZC`,
    concat('ADLCBPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBPN`,
    concat('LASTFPAYDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LASTFPAYDT`,
    concat('YTDINTAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `YTDINTAMT`,
    concat('YTDPPAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `YTDPPAMT`,
    concat('YTDTAXAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `YTDTAXAMT`,
    concat('YTDHAZAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `YTDHAZAMT`,
    concat('USR1PO4A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR1PO4A`,
    concat('DAYDELIQUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DAYDELIQUE`,
    concat('ENTERNONAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ENTERNONAC`,
    concat('LEAVENONAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LEAVENONAC`,
    date_add(DATE '2026-01-01', idx - 1) AS `APPRAIDATE`,
    concat('LNMOAPPDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNMOAPPDAT`,
    concat('LNMOAPPAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNMOAPPAMT`,
    concat('CHAROFFDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHAROFFDAT`,
    concat('DRROUTRNUM_', lpad(CAST(idx AS STRING), 2, '0')) AS `DRROUTRNUM`,
    concat('FIORCOSAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIORCOSAMT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FIORFEEAMT`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_DISB"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_disb (
    `LOAN_NUMBER` BIGINT,
    `INVESTOR_NUMBER` BIGINT,
    `CATEGORY_CODE` STRING,
    `DSB_TRANSACTION_DATE` DATE,
    `DSB_TRANSACTION_CODE` STRING,
    `DSB_AMOUNT` DECIMAL(38,10),
    `MSP_LAST_RUN_DATE` DATE,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_disb IS 
'The table contains data related to disbursements associated with loans. Key attributes include loan numbers, investor numbers, transaction dates, and amounts. This can be utilized for tracking disbursement activities, analyzing funding patterns, and reconciling financial records.';

TRUNCATE TABLE dmi.default.dmi_disb;

INSERT INTO dmi.default.dmi_disb (
    `LOAN_NUMBER`, `INVESTOR_NUMBER`, `CATEGORY_CODE`, `DSB_TRANSACTION_DATE`, `DSB_TRANSACTION_CODE`, `DSB_AMOUNT`,
    `MSP_LAST_RUN_DATE`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    idx AS `LOAN_NUMBER`,
    idx AS `INVESTOR_NUMBER`,
    concat('CATEGORY_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CATEGORY_CODE`,
    date_add(DATE '2026-01-01', idx - 1) AS `DSB_TRANSACTION_DATE`,
    concat('DSB_TRANSACTION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DSB_TRANSACTION_CODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DSB_AMOUNT`,
    date_add(DATE '2026-01-01', idx - 1) AS `MSP_LAST_RUN_DATE`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_E006"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_e006 (
    `BatchCode` STRING,
    `SequenceNumber` BIGINT,
    `TransactionCode` STRING,
    `CLTNumber` BIGINT,
    `LoanNumber` BIGINT,
    `HITypeCode` STRING,
    `PrincipalAdjustment` DECIMAL(38,10),
    `InterestAdjustment` DECIMAL(38,10),
    `DiscountAdjustmentOrPercent` DECIMAL(38,10),
    `InterestDueAdjustment` DECIMAL(38,10),
    `TransactionTotal` DECIMAL(38,10),
    `DueDateAdjustment` STRING,
    `NXNumber` BIGINT,
    `NLOR` STRING,
    `CSCode` STRING,
    `DISCCode` STRING,
    `DISMCode` STRING,
    `ORGADJCode` STRING,
    `STPAcr` STRING,
    `ACSTCode` STRING,
    `SCCode` STRING,
    `ReasonCode` STRING,
    `CardCode` STRING,
    `PointsPaidByBorrower` DECIMAL(38,10),
    `RPTGYR_26_27` STRING,
    `AutoAdjSW1098` STRING,
    `DiscFlag` STRING,
    `PPBBFlag` STRING,
    `UpfrontMIP` STRING,
    `RPTGYR_40_41` STRING,
    `MI1098AdjSW` STRING,
    `Auto` STRING,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_e006 IS 
'The table contains records related to loan transactions, including details on adjustments, codes, and associated loan identifiers. Use cases include analyzing loan repayment patterns, evaluating adjustments made to loans, and tracking transaction details over time. This data can help in the assessment of financial performance and customer payment behavior.';

TRUNCATE TABLE dmi.default.dmi_e006;

INSERT INTO dmi.default.dmi_e006 (
    `BatchCode`, `SequenceNumber`, `TransactionCode`, `CLTNumber`, `LoanNumber`, `HITypeCode`,
    `PrincipalAdjustment`, `InterestAdjustment`, `DiscountAdjustmentOrPercent`, `InterestDueAdjustment`, `TransactionTotal`, `DueDateAdjustment`,
    `NXNumber`, `NLOR`, `CSCode`, `DISCCode`, `DISMCode`, `ORGADJCode`,
    `STPAcr`, `ACSTCode`, `SCCode`, `ReasonCode`, `CardCode`, `PointsPaidByBorrower`,
    `RPTGYR_26_27`, `AutoAdjSW1098`, `DiscFlag`, `PPBBFlag`, `UpfrontMIP`, `RPTGYR_40_41`,
    `MI1098AdjSW`, `Auto`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('BATCHCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BatchCode`,
    idx AS `SequenceNumber`,
    concat('TRANSACTIONCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TransactionCode`,
    idx AS `CLTNumber`,
    idx AS `LoanNumber`,
    concat('HITYPECODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITypeCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PrincipalAdjustment`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestAdjustment`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DiscountAdjustmentOrPercent`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestDueAdjustment`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TransactionTotal`,
    concat('DUEDATEADJUSTMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `DueDateAdjustment`,
    idx AS `NXNumber`,
    concat('NLOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `NLOR`,
    concat('CSCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CSCode`,
    concat('DISCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISCCode`,
    concat('DISMCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISMCode`,
    concat('ORGADJCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGADJCode`,
    concat('STPACR_', lpad(CAST(idx AS STRING), 2, '0')) AS `STPAcr`,
    concat('ACSTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACSTCode`,
    concat('SCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SCCode`,
    concat('REASONCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ReasonCode`,
    concat('CARDCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CardCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PointsPaidByBorrower`,
    concat('RPTGYR_26_27_', lpad(CAST(idx AS STRING), 2, '0')) AS `RPTGYR_26_27`,
    concat('AUTOADJSW1098_', lpad(CAST(idx AS STRING), 2, '0')) AS `AutoAdjSW1098`,
    concat('DISCFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `DiscFlag`,
    concat('PPBBFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPBBFlag`,
    concat('UPFRONTMIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `UpfrontMIP`,
    concat('RPTGYR_40_41_', lpad(CAST(idx AS STRING), 2, '0')) AS `RPTGYR_40_41`,
    concat('MI1098ADJSW_', lpad(CAST(idx AS STRING), 2, '0')) AS `MI1098AdjSW`,
    concat('AUTO_', lpad(CAST(idx AS STRING), 2, '0')) AS `Auto`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: static query dmi_gl_mapping
CREATE TABLE IF NOT EXISTS dmi.default.dmi_gl_mapping (
    `Investor_Type` STRING,
    `Investor_Name` STRING,
    `Perm_Inv` STRING,
    `Perm_Cat` STRING,
    `Recon_Method` STRING,
    `P_I_DDA_Number` BIGINT,
    `T_I_DDA_Number` BIGINT,
    `G_L_Corp_Code` STRING,
    `ABA_Number` BIGINT,
    `Principal_Payee` DECIMAL(38,10),
    `Principal_G_L_Acct_No` DECIMAL(38,10),
    `Principal_GL_Number` DECIMAL(38,10),
    `Principal_G_L_Cost_Center` DECIMAL(38,10),
    `Escrow_Replacement_Reserve_Payee` DECIMAL(38,10),
    `Escrow_Replacement_Reserve_G_L_Acct_No` DECIMAL(38,10),
    `Escrow_Replacement_Reserve_G_L_Cost_Center` DECIMAL(38,10),
    `Interest_Receivable_Payee` DECIMAL(38,10),
    `Interest_Receivable_G_L_Acct_No` DECIMAL(38,10),
    `Interest_Receivable_G_L_Cost_Center` DECIMAL(38,10),
    `Servicing_Fee_Payee` DECIMAL(38,10),
    `Servicing_Fee_G_L_Acct_No` DECIMAL(38,10),
    `Servicing_Fee_G_L_Cost_Center` DECIMAL(38,10),
    `Late_Charge_Payee` STRING,
    `Late_Charge_G_L_Acct_No` STRING,
    `Late_Charge_G_L_Cost_Center` DECIMAL(38,10),
    `Loans_in_Process_Payee` STRING,
    `Loans_in_Process_G_L_Acct_No` STRING,
    `Loans_in_Process_G_L_Cost_Center` DECIMAL(38,10),
    `Loans_in_Process_Payee_2` STRING,
    `Part_Conta_G_L_Acct_No` STRING,
    `Part_Conta_G_L_Cost_Center` DECIMAL(38,10),
    `Interest_Income_Payee` DECIMAL(38,10),
    `Interest_Income_G_L_Acct_No` DECIMAL(38,10),
    `Interest_Income_G_L_Cost_Center` DECIMAL(38,10),
    `Loans_Sold_Payee` STRING,
    `Loans_Sold_G_L_Acct_No` STRING,
    `Loans_Sold_G_L_Cost_Center` DECIMAL(38,10),
    `P_I_Adv_Payee` STRING,
    `Doc_Custod_Payee` STRING,
    `Penalty_Int_Penalty_Payee` DECIMAL(38,10),
    `Penalty_Int_Penalty_G_L_Acct_No` DECIMAL(38,10),
    `Penalty_Int_Penalty_G_L_Cost_Center` DECIMAL(38,10),
    `Penalty_Int_Penalty` DECIMAL(38,10),
    `Straightline_Disc_Unearned_Payee` STRING,
    `Straightline_Disc_Unearned_G_L_Acct_No` STRING,
    `Straightline_Disc_Unearned_G_L_Cost_Center` DECIMAL(38,10),
    `Straightline_Disc_Earned_Payee` STRING,
    `Straightline_Disc_Earned_G_L_Acct_No` STRING,
    `Straightline_Disc_Earned_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_1_Unearned_Fees_Payee` DECIMAL(38,10),
    `FASB_91_1_Unearned_Fees_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_1_Unearned_Fees_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_1_Earned_Fees_Payee` DECIMAL(38,10),
    `FASB_91_1_Earned_Fees_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_1_Earned_Fees_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_2_Unearned_Cost_Payee` DECIMAL(38,10),
    `FASB_91_2_Unearned_Cost_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_2_Unearned_Cost_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_2_Earned_Cost_Payee` DECIMAL(38,10),
    `FASB_91_2_Earned_Cost_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_2_Earned_Cost_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_3_Unearned_Cost_Payee` DECIMAL(38,10),
    `FASB_91_3_Unearned_Cost_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_3_Unearned_Cost_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_3_Earned_Cost_Payee` DECIMAL(38,10),
    `FASB_91_3_Earned_Cost_G_L_Acct_No` DECIMAL(38,10),
    `FASB_91_3_Earned_Cost_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_4_Unearned_Payee` STRING,
    `FASB_91_4_Unearned_G_L_Acct_No` STRING,
    `FASB_91_4_Unearned_G_L_Cost_Center` DECIMAL(38,10),
    `FASB_91_4_Earned_Payee` STRING,
    `FASB_91_4_Earned_G_L_Acct_No` STRING,
    `FASB_91_4_Earned_G_L_Cost_Center` DECIMAL(38,10),
    `Effective_Date` DATE,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_gl_mapping IS 
'This table captures mapping information related to various investor types and their associated financial details. It includes items such as investor names, general ledger account numbers, and cost centers for different types of financial transactions and payees. Colleagues can use this data to analyze financial mappings, perform reconciliations, and track financial obligations across multiple accounts.';

TRUNCATE TABLE dmi.default.dmi_gl_mapping;

INSERT INTO dmi.default.dmi_gl_mapping (
    `Investor_Type`, `Investor_Name`, `Perm_Inv`, `Perm_Cat`, `Recon_Method`, `P_I_DDA_Number`,
    `T_I_DDA_Number`, `G_L_Corp_Code`, `ABA_Number`, `Principal_Payee`, `Principal_G_L_Acct_No`, `Principal_GL_Number`,
    `Principal_G_L_Cost_Center`, `Escrow_Replacement_Reserve_Payee`, `Escrow_Replacement_Reserve_G_L_Acct_No`, `Escrow_Replacement_Reserve_G_L_Cost_Center`, `Interest_Receivable_Payee`, `Interest_Receivable_G_L_Acct_No`,
    `Interest_Receivable_G_L_Cost_Center`, `Servicing_Fee_Payee`, `Servicing_Fee_G_L_Acct_No`, `Servicing_Fee_G_L_Cost_Center`, `Late_Charge_Payee`, `Late_Charge_G_L_Acct_No`,
    `Late_Charge_G_L_Cost_Center`, `Loans_in_Process_Payee`, `Loans_in_Process_G_L_Acct_No`, `Loans_in_Process_G_L_Cost_Center`, `Loans_in_Process_Payee_2`, `Part_Conta_G_L_Acct_No`,
    `Part_Conta_G_L_Cost_Center`, `Interest_Income_Payee`, `Interest_Income_G_L_Acct_No`, `Interest_Income_G_L_Cost_Center`, `Loans_Sold_Payee`, `Loans_Sold_G_L_Acct_No`,
    `Loans_Sold_G_L_Cost_Center`, `P_I_Adv_Payee`, `Doc_Custod_Payee`, `Penalty_Int_Penalty_Payee`, `Penalty_Int_Penalty_G_L_Acct_No`, `Penalty_Int_Penalty_G_L_Cost_Center`,
    `Penalty_Int_Penalty`, `Straightline_Disc_Unearned_Payee`, `Straightline_Disc_Unearned_G_L_Acct_No`, `Straightline_Disc_Unearned_G_L_Cost_Center`, `Straightline_Disc_Earned_Payee`, `Straightline_Disc_Earned_G_L_Acct_No`,
    `Straightline_Disc_Earned_G_L_Cost_Center`, `FASB_91_1_Unearned_Fees_Payee`, `FASB_91_1_Unearned_Fees_G_L_Acct_No`, `FASB_91_1_Unearned_Fees_G_L_Cost_Center`, `FASB_91_1_Earned_Fees_Payee`, `FASB_91_1_Earned_Fees_G_L_Acct_No`,
    `FASB_91_1_Earned_Fees_G_L_Cost_Center`, `FASB_91_2_Unearned_Cost_Payee`, `FASB_91_2_Unearned_Cost_G_L_Acct_No`, `FASB_91_2_Unearned_Cost_G_L_Cost_Center`, `FASB_91_2_Earned_Cost_Payee`, `FASB_91_2_Earned_Cost_G_L_Acct_No`,
    `FASB_91_2_Earned_Cost_G_L_Cost_Center`, `FASB_91_3_Unearned_Cost_Payee`, `FASB_91_3_Unearned_Cost_G_L_Acct_No`, `FASB_91_3_Unearned_Cost_G_L_Cost_Center`, `FASB_91_3_Earned_Cost_Payee`, `FASB_91_3_Earned_Cost_G_L_Acct_No`,
    `FASB_91_3_Earned_Cost_G_L_Cost_Center`, `FASB_91_4_Unearned_Payee`, `FASB_91_4_Unearned_G_L_Acct_No`, `FASB_91_4_Unearned_G_L_Cost_Center`, `FASB_91_4_Earned_Payee`, `FASB_91_4_Earned_G_L_Acct_No`,
    `FASB_91_4_Earned_G_L_Cost_Center`, `Effective_Date`, `LOADED_AT`
)
SELECT
    concat('INVESTOR_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `Investor_Type`,
    concat('INVESTOR_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `Investor_Name`,
    concat('PERM_INV_', lpad(CAST(idx AS STRING), 2, '0')) AS `Perm_Inv`,
    concat('PERM_CAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `Perm_Cat`,
    concat('RECON_METHOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `Recon_Method`,
    idx AS `P_I_DDA_Number`,
    idx AS `T_I_DDA_Number`,
    concat('G_L_CORP_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `G_L_Corp_Code`,
    idx AS `ABA_Number`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Principal_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Principal_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Principal_GL_Number`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Principal_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Escrow_Replacement_Reserve_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Escrow_Replacement_Reserve_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Escrow_Replacement_Reserve_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Receivable_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Receivable_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Receivable_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Servicing_Fee_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Servicing_Fee_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Servicing_Fee_G_L_Cost_Center`,
    concat('LATE_CHARGE_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `Late_Charge_Payee`,
    concat('LATE_CHARGE_G_L_ACCT_NO_', lpad(CAST(idx AS STRING), 2, '0')) AS `Late_Charge_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Late_Charge_G_L_Cost_Center`,
    concat('LOANS_IN_PROCESS_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `Loans_in_Process_Payee`,
    concat('LOANS_IN_PROCESS_G_L_ACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `Loans_in_Process_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Loans_in_Process_G_L_Cost_Center`,
    concat('LOANS_IN_PROCESS_PAYEE_2_', lpad(CAST(idx AS STRING), 2, '0')) AS `Loans_in_Process_Payee_2`,
    concat('PART_CONTA_G_L_ACCT_NO_', lpad(CAST(idx AS STRING), 2, '0')) AS `Part_Conta_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Part_Conta_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Income_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Income_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Interest_Income_G_L_Cost_Center`,
    concat('LOANS_SOLD_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `Loans_Sold_Payee`,
    concat('LOANS_SOLD_G_L_ACCT_NO_', lpad(CAST(idx AS STRING), 2, '0')) AS `Loans_Sold_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Loans_Sold_G_L_Cost_Center`,
    concat('P_I_ADV_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P_I_Adv_Payee`,
    concat('DOC_CUSTOD_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `Doc_Custod_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Penalty_Int_Penalty_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Penalty_Int_Penalty_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Penalty_Int_Penalty_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Penalty_Int_Penalty`,
    concat('STRAIGHTLINE_DISC_UNEARN_', lpad(CAST(idx AS STRING), 2, '0')) AS `Straightline_Disc_Unearned_Payee`,
    concat('STRAIGHTLINE_DISC_UNEARN_', lpad(CAST(idx AS STRING), 2, '0')) AS `Straightline_Disc_Unearned_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Straightline_Disc_Unearned_G_L_Cost_Center`,
    concat('STRAIGHTLINE_DISC_EARNED_', lpad(CAST(idx AS STRING), 2, '0')) AS `Straightline_Disc_Earned_Payee`,
    concat('STRAIGHTLINE_DISC_EARNED_', lpad(CAST(idx AS STRING), 2, '0')) AS `Straightline_Disc_Earned_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Straightline_Disc_Earned_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Unearned_Fees_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Unearned_Fees_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Unearned_Fees_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Earned_Fees_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Earned_Fees_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_1_Earned_Fees_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Unearned_Cost_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Unearned_Cost_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Unearned_Cost_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Earned_Cost_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Earned_Cost_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_2_Earned_Cost_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Unearned_Cost_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Unearned_Cost_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Unearned_Cost_G_L_Cost_Center`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Earned_Cost_Payee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Earned_Cost_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_3_Earned_Cost_G_L_Cost_Center`,
    concat('FASB_91_4_UNEARNED_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FASB_91_4_Unearned_Payee`,
    concat('FASB_91_4_UNEARNED_G_L_A_', lpad(CAST(idx AS STRING), 2, '0')) AS `FASB_91_4_Unearned_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_4_Unearned_G_L_Cost_Center`,
    concat('FASB_91_4_EARNED_PAYEE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FASB_91_4_Earned_Payee`,
    concat('FASB_91_4_EARNED_G_L_ACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `FASB_91_4_Earned_G_L_Acct_No`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FASB_91_4_Earned_G_L_Cost_Center`,
    date_add(DATE '2026-01-01', idx - 1) AS `Effective_Date`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_NONCASH"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_noncash (
    `LOAN_NUMBER` BIGINT,
    `INVESTOR_NUMBER` BIGINT,
    `CATEGORY_CODE` STRING,
    `NC_TRANSACTION_CODE` STRING,
    `NC_TRANSACTION_DATE` DATE,
    `NC_AMOUNT` DECIMAL(38,10),
    `NC_PRINCIPAL_AMOUNT` DECIMAL(38,10),
    `NC_INTEREST_AMOUNT` DECIMAL(38,10),
    `MSP_LAST_RUN_DATE` DATE,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_noncash IS 
'The table captures non-cash transaction details related to loans and investments. It includes information such as loan numbers, investor identifiers, transaction categories, and amounts associated with principal and interest. This data can assist in analyzing non-cash transactions, monitoring financial activities related to loans, and understanding investment patterns over time.';

TRUNCATE TABLE dmi.default.dmi_noncash;

INSERT INTO dmi.default.dmi_noncash (
    `LOAN_NUMBER`, `INVESTOR_NUMBER`, `CATEGORY_CODE`, `NC_TRANSACTION_CODE`, `NC_TRANSACTION_DATE`, `NC_AMOUNT`,
    `NC_PRINCIPAL_AMOUNT`, `NC_INTEREST_AMOUNT`, `MSP_LAST_RUN_DATE`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    idx AS `LOAN_NUMBER`,
    idx AS `INVESTOR_NUMBER`,
    concat('CATEGORY_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CATEGORY_CODE`,
    concat('NC_TRANSACTION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NC_TRANSACTION_CODE`,
    date_add(DATE '2026-01-01', idx - 1) AS `NC_TRANSACTION_DATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NC_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NC_PRINCIPAL_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NC_INTEREST_AMOUNT`,
    date_add(DATE '2026-01-01', idx - 1) AS `MSP_LAST_RUN_DATE`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_P110"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_p110 (
    `LoanNumber` BIGINT,
    `BankCode` STRING,
    `LoanCategory` STRING,
    `LoanType` STRING,
    `InterestRate` DECIMAL(38,10),
    `ServiceRate` DECIMAL(38,10),
    `ManCode` STRING,
    `ShortName` STRING,
    `InvestorLoanNumber` BIGINT,
    `SubCode` STRING,
    `HITY` STRING,
    `InterestPaidToDate` DATE,
    `SegmentNumber` BIGINT,
    `EscrowBalance` DECIMAL(38,10),
    `SuspenseBalance` DECIMAL(38,10),
    `HUDBalance` DECIMAL(38,10),
    `PrincipalPaid` DECIMAL(38,10),
    `InterestPaid` DECIMAL(38,10),
    `ServiceFee` DECIMAL(38,10),
    `Penalty` DECIMAL(38,10),
    `PenaltySerFee` DECIMAL(38,10),
    `FHAPenalty` DECIMAL(38,10),
    `EscrowPaid` DECIMAL(38,10),
    `SuspensePaid` DECIMAL(38,10),
    `RestEscPaid` DECIMAL(38,10),
    `AdvanceBalance` DECIMAL(38,10),
    `RestEsc` STRING,
    `RepRsv` STRING,
    `PrinReductAmt` STRING,
    `DedCode` STRING,
    `PrinFBAmt` STRING,
    `P443FundingInterestRate` DECIMAL(38,10),
    `P443FundingServiceFee` DECIMAL(38,10),
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_p110 IS 
'The table contains information about loans, including various financial details associated with each loan. Use cases include analyzing loan performance, assessing interest and service fees, tracking payments made, and understanding the overall financial position of loans within different categories and types. Key data points include loan numbers, interest rates, fees, balances, and payment history.';

TRUNCATE TABLE dmi.default.dmi_p110;

INSERT INTO dmi.default.dmi_p110 (
    `LoanNumber`, `BankCode`, `LoanCategory`, `LoanType`, `InterestRate`, `ServiceRate`,
    `ManCode`, `ShortName`, `InvestorLoanNumber`, `SubCode`, `HITY`, `InterestPaidToDate`,
    `SegmentNumber`, `EscrowBalance`, `SuspenseBalance`, `HUDBalance`, `PrincipalPaid`, `InterestPaid`,
    `ServiceFee`, `Penalty`, `PenaltySerFee`, `FHAPenalty`, `EscrowPaid`, `SuspensePaid`,
    `RestEscPaid`, `AdvanceBalance`, `RestEsc`, `RepRsv`, `PrinReductAmt`, `DedCode`,
    `PrinFBAmt`, `P443FundingInterestRate`, `P443FundingServiceFee`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    idx AS `LoanNumber`,
    concat('BANKCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BankCode`,
    concat('LOANCATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `LoanCategory`,
    concat('LOANTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LoanType`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestRate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ServiceRate`,
    concat('MANCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ManCode`,
    concat('SHORTNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `ShortName`,
    idx AS `InvestorLoanNumber`,
    concat('SUBCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SubCode`,
    concat('HITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITY`,
    date_add(DATE '2026-01-01', idx - 1) AS `InterestPaidToDate`,
    idx AS `SegmentNumber`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EscrowBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SuspenseBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `HUDBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PrincipalPaid`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestPaid`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ServiceFee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Penalty`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PenaltySerFee`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FHAPenalty`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EscrowPaid`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SuspensePaid`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RestEscPaid`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AdvanceBalance`,
    concat('RESTESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `RestEsc`,
    concat('REPRSV_', lpad(CAST(idx AS STRING), 2, '0')) AS `RepRsv`,
    concat('PRINREDUCTAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PrinReductAmt`,
    concat('DEDCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DedCode`,
    concat('PRINFBAMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PrinFBAmt`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P443FundingInterestRate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P443FundingServiceFee`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_P132"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_p132 (
    `ReportID` STRING,
    `ReportDate` DATE,
    `LoanNumber` BIGINT,
    `InvestorCode` STRING,
    `CAT` STRING,
    `TRN` STRING,
    `DUE_DATE` DATE,
    `TP` STRING,
    `CLOSING` STRING,
    `AM_CD` STRING,
    `AM_CD_MO` STRING,
    `ORIGINAL_DISC` STRING,
    `DISC_BALANCE` DECIMAL(38,10),
    `DISC_DECREASE` STRING,
    `DISC_INCREASE` STRING,
    `DISC_PTS_FLG` STRING,
    `PTS_PD_BORR` STRING,
    `PTS_PD_BORR_YR` STRING,
    `PPBB_FLG` STRING,
    `DEDUCTIBLE_MI` STRING,
    `DEDUCTIBLE_MI_YR` STRING,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_p132 IS 
'The table contains data related to loan reports. It includes information such as report identifiers, loan numbers, investor codes, and various financial metrics related to discounts and balances. Possible use cases involve tracking loan performance, analyzing investor returns, and managing report deadlines. The data can be useful for financial analysis and reporting in related operations.';

TRUNCATE TABLE dmi.default.dmi_p132;

INSERT INTO dmi.default.dmi_p132 (
    `ReportID`, `ReportDate`, `LoanNumber`, `InvestorCode`, `CAT`, `TRN`,
    `DUE_DATE`, `TP`, `CLOSING`, `AM_CD`, `AM_CD_MO`, `ORIGINAL_DISC`,
    `DISC_BALANCE`, `DISC_DECREASE`, `DISC_INCREASE`, `DISC_PTS_FLG`, `PTS_PD_BORR`, `PTS_PD_BORR_YR`,
    `PPBB_FLG`, `DEDUCTIBLE_MI`, `DEDUCTIBLE_MI_YR`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('REPORTID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ReportID`,
    date_add(DATE '2026-01-01', idx - 1) AS `ReportDate`,
    idx AS `LoanNumber`,
    concat('INVESTORCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `InvestorCode`,
    concat('CAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAT`,
    concat('TRN_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRN`,
    date_add(DATE '2026-01-01', idx - 1) AS `DUE_DATE`,
    concat('TP_', lpad(CAST(idx AS STRING), 2, '0')) AS `TP`,
    concat('CLOSING_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLOSING`,
    concat('AM_CD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AM_CD`,
    concat('AM_CD_MO_', lpad(CAST(idx AS STRING), 2, '0')) AS `AM_CD_MO`,
    concat('ORIGINAL_DISC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGINAL_DISC`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DISC_BALANCE`,
    concat('DISC_DECREASE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISC_DECREASE`,
    concat('DISC_INCREASE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISC_INCREASE`,
    concat('DISC_PTS_FLG_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISC_PTS_FLG`,
    concat('PTS_PD_BORR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTS_PD_BORR`,
    concat('PTS_PD_BORR_YR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTS_PD_BORR_YR`,
    concat('PPBB_FLG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPBB_FLG`,
    concat('DEDUCTIBLE_MI_', lpad(CAST(idx AS STRING), 2, '0')) AS `DEDUCTIBLE_MI`,
    concat('DEDUCTIBLE_MI_YR_', lpad(CAST(idx AS STRING), 2, '0')) AS `DEDUCTIBLE_MI_YR`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_PMT"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_pmt (
    `LOAN_NUMBER` BIGINT,
    `INVESTOR_NUMBER` BIGINT,
    `CATEGORY_CODE` STRING,
    `PMT_TRANSACTION_DATE` DATE,
    `PMT_TRANSACTION_CODE` STRING,
    `PMT_PRINCIPAL_AMOUNT` DECIMAL(38,10),
    `PMT_INTEREST_AMOUNT` DECIMAL(38,10),
    `PMT_ESCROW_AMOUNT` DECIMAL(38,10),
    `PMT_TOTAL_AMOUNT` DECIMAL(38,10),
    `PMT_FEE_AMOUNT` DECIMAL(38,10),
    `PMT_FEE_CODE` DECIMAL(38,10),
    `PMT_SUSPENSE_AMOUNT` DECIMAL(38,10),
    `PMT_A_H_INSURANCE_AMOUNT` DECIMAL(38,10),
    `PMT_LIFE_INSURANCE_AMOUNT` DECIMAL(38,10),
    `PMT_RESTRICTED_ESC_AMOUNT` DECIMAL(38,10),
    `PMT_REPLACEMENT_RES` STRING,
    `PMT_MISC_AMOUNT` DECIMAL(38,10),
    `PMT_HUD_AMOUNT` DECIMAL(38,10),
    `PMT_EFFECTIVE_DATE` DATE,
    `PMT_BATCH_NUMBER` BIGINT,
    `MSP_LAST_RUN_DATE` DATE,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_pmt IS 
'This table contains information about payment transactions related to loans. It includes data such as loan numbers, investor numbers, transaction dates, and various amounts associated with the payments like principal, interest, fees, and escrow. Potential use cases for this table involve tracking payment histories, analyzing loan performance, and reporting on financial transactions related to loan servicing.';

TRUNCATE TABLE dmi.default.dmi_pmt;

INSERT INTO dmi.default.dmi_pmt (
    `LOAN_NUMBER`, `INVESTOR_NUMBER`, `CATEGORY_CODE`, `PMT_TRANSACTION_DATE`, `PMT_TRANSACTION_CODE`, `PMT_PRINCIPAL_AMOUNT`,
    `PMT_INTEREST_AMOUNT`, `PMT_ESCROW_AMOUNT`, `PMT_TOTAL_AMOUNT`, `PMT_FEE_AMOUNT`, `PMT_FEE_CODE`, `PMT_SUSPENSE_AMOUNT`,
    `PMT_A_H_INSURANCE_AMOUNT`, `PMT_LIFE_INSURANCE_AMOUNT`, `PMT_RESTRICTED_ESC_AMOUNT`, `PMT_REPLACEMENT_RES`, `PMT_MISC_AMOUNT`, `PMT_HUD_AMOUNT`,
    `PMT_EFFECTIVE_DATE`, `PMT_BATCH_NUMBER`, `MSP_LAST_RUN_DATE`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    idx AS `LOAN_NUMBER`,
    idx AS `INVESTOR_NUMBER`,
    concat('CATEGORY_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CATEGORY_CODE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PMT_TRANSACTION_DATE`,
    concat('PMT_TRANSACTION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMT_TRANSACTION_CODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_PRINCIPAL_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_INTEREST_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_ESCROW_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_TOTAL_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_FEE_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_FEE_CODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_SUSPENSE_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_A_H_INSURANCE_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_LIFE_INSURANCE_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_RESTRICTED_ESC_AMOUNT`,
    concat('PMT_REPLACEMENT_RES_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMT_REPLACEMENT_RES`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_MISC_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMT_HUD_AMOUNT`,
    date_add(DATE '2026-01-01', idx - 1) AS `PMT_EFFECTIVE_DATE`,
    idx AS `PMT_BATCH_NUMBER`,
    date_add(DATE '2026-01-01', idx - 1) AS `MSP_LAST_RUN_DATE`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_S2TT"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_s2tt (
    `AccrualEntityCode` STRING,
    `HeaderInvestorCode` STRING,
    `LoanNumber` BIGINT,
    `PSCode` STRING,
    `BeginningIRBalance` DECIMAL(38,10),
    `PeriodIncome` DECIMAL(38,10),
    `AccrualAdjust` STRING,
    `InterestCollected` DECIMAL(38,10),
    `EndIRBalance` DECIMAL(38,10),
    `AmortizedPrincipalBalance` DECIMAL(38,10),
    `InterestRate` DECIMAL(38,10),
    `DueOrEffectiveDate` DATE,
    `PandIConstant` STRING,
    `InvestorCode` STRING,
    `CategoryCode` STRING,
    `PCCode` STRING,
    `Percent__CS` DECIMAL(38,10),
    `PTCode` STRING,
    `ForecastedIncome` DECIMAL(38,10),
    `ForecastedIRBalance` DECIMAL(38,10),
    `FirstPrincipalBalance` DECIMAL(38,10),
    `IntlInd` STRING,
    `LoanTypeCode` STRING,
    `SLCode` STRING,
    `PtFq` STRING,
    `AI` STRING,
    `ARMPrimeRate` DECIMAL(38,10),
    `AFCode` STRING,
    `Delq` STRING,
    `SDCode` STRING,
    `ASDDifference` STRING,
    `ASDIR` STRING,
    `ExceptionCodes1` STRING,
    `ExceptionsCodesDateLine1` STRING,
    `NumberOfDays` STRING,
    `PerDiem` STRING,
    `Sum__CS` STRING,
    `ClientCode` STRING,
    `ExceptionCodes2` STRING,
    `ExceptionsCodesDateLine2` STRING,
    `NumberOfDays2` STRING,
    `PerDiem2` STRING,
    `Sum2` STRING,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_s2tt IS 
'The table contains data related to loan management and interest accrual. It records various financial metrics and details for each loan, including balances, interest rates, and income forecasts. Potential use cases include analyzing loan performance, tracking interest accruals, and forecasting income related to the loans. This data can aid in financial reporting and decision-making processes.';

TRUNCATE TABLE dmi.default.dmi_s2tt;

INSERT INTO dmi.default.dmi_s2tt (
    `AccrualEntityCode`, `HeaderInvestorCode`, `LoanNumber`, `PSCode`, `BeginningIRBalance`, `PeriodIncome`,
    `AccrualAdjust`, `InterestCollected`, `EndIRBalance`, `AmortizedPrincipalBalance`, `InterestRate`, `DueOrEffectiveDate`,
    `PandIConstant`, `InvestorCode`, `CategoryCode`, `PCCode`, `Percent__CS`, `PTCode`,
    `ForecastedIncome`, `ForecastedIRBalance`, `FirstPrincipalBalance`, `IntlInd`, `LoanTypeCode`, `SLCode`,
    `PtFq`, `AI`, `ARMPrimeRate`, `AFCode`, `Delq`, `SDCode`,
    `ASDDifference`, `ASDIR`, `ExceptionCodes1`, `ExceptionsCodesDateLine1`, `NumberOfDays`, `PerDiem`,
    `Sum__CS`, `ClientCode`, `ExceptionCodes2`, `ExceptionsCodesDateLine2`, `NumberOfDays2`, `PerDiem2`,
    `Sum2`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('ACCRUALENTITYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AccrualEntityCode`,
    concat('HEADERINVESTORCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `HeaderInvestorCode`,
    idx AS `LoanNumber`,
    concat('PSCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BeginningIRBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PeriodIncome`,
    concat('ACCRUALADJUST_', lpad(CAST(idx AS STRING), 2, '0')) AS `AccrualAdjust`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestCollected`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EndIRBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AmortizedPrincipalBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestRate`,
    date_add(DATE '2026-01-01', idx - 1) AS `DueOrEffectiveDate`,
    concat('PANDICONSTANT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PandIConstant`,
    concat('INVESTORCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `InvestorCode`,
    concat('CATEGORYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CategoryCode`,
    concat('PCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Percent__CS`,
    concat('PTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ForecastedIncome`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ForecastedIRBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FirstPrincipalBalance`,
    concat('INTLIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `IntlInd`,
    concat('LOANTYPECODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LoanTypeCode`,
    concat('SLCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SLCode`,
    concat('PTFQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `PtFq`,
    concat('AI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AI`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ARMPrimeRate`,
    concat('AFCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AFCode`,
    concat('DELQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `Delq`,
    concat('SDCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SDCode`,
    concat('ASDDIFFERENCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASDDifference`,
    concat('ASDIR_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASDIR`,
    concat('EXCEPTIONCODES1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionCodes1`,
    concat('EXCEPTIONSCODESDATELINE1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionsCodesDateLine1`,
    concat('NUMBEROFDAYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `NumberOfDays`,
    concat('PERDIEM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PerDiem`,
    concat('SUM__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `Sum__CS`,
    concat('CLIENTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ClientCode`,
    concat('EXCEPTIONCODES2_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionCodes2`,
    concat('EXCEPTIONSCODESDATELINE2_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionsCodesDateLine2`,
    concat('NUMBEROFDAYS2_', lpad(CAST(idx AS STRING), 2, '0')) AS `NumberOfDays2`,
    concat('PERDIEM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PerDiem2`,
    concat('SUM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `Sum2`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_S2TV"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_s2tv (
    `ExceptionDescription` STRING,
    `LoanNumber` BIGINT,
    `BeginningIRBalance` DECIMAL(38,10),
    `PeriodIncome` DECIMAL(38,10),
    `AccrualAdjust` STRING,
    `InterestCollected` DECIMAL(38,10),
    `EndIRBalance` DECIMAL(38,10),
    `FirstPrinBalance` DECIMAL(38,10),
    `InterestRate` DECIMAL(38,10),
    `DueEffDate` DATE,
    `PNIConstant` STRING,
    `AccrualEntityCode` STRING,
    `InvestorCode` STRING,
    `CategoryCode` STRING,
    `PartCode` STRING,
    `PostingType` STRING,
    `VariableBeforeAfter` STRING,
    `Date` DATE,
    `ExceptionCodes` STRING,
    `LoanType` STRING,
    `SLCode1` STRING,
    `PTFQCode` STRING,
    `AICode` STRING,
    `ArmPrmRt` STRING,
    `AFCode` STRING,
    `DelqCode` STRING,
    `SDCode` STRING,
    `PPDCode1` STRING,
    `ASDDiff` STRING,
    `ASDIR` STRING,
    `AmortPrinBalance` DECIMAL(38,10),
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_s2tv IS 
'The table contains financial data related to loans, including various metrics such as balances, income, interest rates, and associated codes for categorization. Possible use cases include tracking loan performance, analyzing interest accruals, and generating reports on loan status and exceptions. This data can assist in decision-making processes regarding loan management and financial analysis.';

TRUNCATE TABLE dmi.default.dmi_s2tv;

INSERT INTO dmi.default.dmi_s2tv (
    `ExceptionDescription`, `LoanNumber`, `BeginningIRBalance`, `PeriodIncome`, `AccrualAdjust`, `InterestCollected`,
    `EndIRBalance`, `FirstPrinBalance`, `InterestRate`, `DueEffDate`, `PNIConstant`, `AccrualEntityCode`,
    `InvestorCode`, `CategoryCode`, `PartCode`, `PostingType`, `VariableBeforeAfter`, `Date`,
    `ExceptionCodes`, `LoanType`, `SLCode1`, `PTFQCode`, `AICode`, `ArmPrmRt`,
    `AFCode`, `DelqCode`, `SDCode`, `PPDCode1`, `ASDDiff`, `ASDIR`,
    `AmortPrinBalance`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('EXCEPTIONDESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionDescription`,
    idx AS `LoanNumber`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BeginningIRBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PeriodIncome`,
    concat('ACCRUALADJUST_', lpad(CAST(idx AS STRING), 2, '0')) AS `AccrualAdjust`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestCollected`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EndIRBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FirstPrinBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestRate`,
    date_add(DATE '2026-01-01', idx - 1) AS `DueEffDate`,
    concat('PNICONSTANT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNIConstant`,
    concat('ACCRUALENTITYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AccrualEntityCode`,
    concat('INVESTORCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `InvestorCode`,
    concat('CATEGORYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CategoryCode`,
    concat('PARTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PartCode`,
    concat('POSTINGTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PostingType`,
    concat('VARIABLEBEFOREAFTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `VariableBeforeAfter`,
    date_add(DATE '2026-01-01', idx - 1) AS `Date`,
    concat('EXCEPTIONCODES_', lpad(CAST(idx AS STRING), 2, '0')) AS `ExceptionCodes`,
    concat('LOANTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LoanType`,
    concat('SLCODE1_', lpad(CAST(idx AS STRING), 2, '0')) AS `SLCode1`,
    concat('PTFQCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTFQCode`,
    concat('AICODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AICode`,
    concat('ARMPRMRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ArmPrmRt`,
    concat('AFCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AFCode`,
    concat('DELQCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `DelqCode`,
    concat('SDCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SDCode`,
    concat('PPDCODE1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDCode1`,
    concat('ASDDIFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASDDiff`,
    concat('ASDIR_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASDIR`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AmortPrinBalance`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_S5AZ"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_s5az (
    `Frequency` STRING,
    `RefinanceDescription` STRING,
    `LoanNumber` BIGINT,
    `InvestorCode2` STRING,
    `CategoryCode2` STRING,
    `HICode` STRING,
    `DueDate` DATE,
    `PrincipalBalance` DECIMAL(38,10),
    `InterestRate` DECIMAL(38,10),
    `Yield` DECIMAL(38,10),
    `FeeCost1` DECIMAL(38,10),
    `FeeCost2` DECIMAL(38,10),
    `FeeCost3` DECIMAL(38,10),
    `FeeCost4` DECIMAL(38,10),
    `FeeCost5` DECIMAL(38,10),
    `FeeCost6` DECIMAL(38,10),
    `FeeCost7` DECIMAL(38,10),
    `FeeCost8` DECIMAL(38,10),
    `Action` STRING,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_s5az IS 
'The table contains data related to loan refinancing and associated costs. It includes details such as loan number, principal balance, interest rates, fee costs, and refinancing descriptions. This data can be used to analyze refinancing patterns, calculate total costs associated with loans, and monitor due dates for payments.';

TRUNCATE TABLE dmi.default.dmi_s5az;

INSERT INTO dmi.default.dmi_s5az (
    `Frequency`, `RefinanceDescription`, `LoanNumber`, `InvestorCode2`, `CategoryCode2`, `HICode`,
    `DueDate`, `PrincipalBalance`, `InterestRate`, `Yield`, `FeeCost1`, `FeeCost2`,
    `FeeCost3`, `FeeCost4`, `FeeCost5`, `FeeCost6`, `FeeCost7`, `FeeCost8`,
    `Action`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('FREQUENCY_', lpad(CAST(idx AS STRING), 2, '0')) AS `Frequency`,
    concat('REFINANCEDESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `RefinanceDescription`,
    idx AS `LoanNumber`,
    concat('INVESTORCODE2_', lpad(CAST(idx AS STRING), 2, '0')) AS `InvestorCode2`,
    concat('CATEGORYCODE2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CategoryCode2`,
    concat('HICODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `HICode`,
    date_add(DATE '2026-01-01', idx - 1) AS `DueDate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PrincipalBalance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InterestRate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `Yield`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost1`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost2`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost3`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost4`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost5`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost6`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost7`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FeeCost8`,
    concat('ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `Action`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."DMI_T69W"
CREATE TABLE IF NOT EXISTS dmi.default.dmi_t69w (
    `CorpCode` STRING,
    `AccountNumber` BIGINT,
    `CostCenterCode` DECIMAL(38,10),
    `PayeeCode` STRING,
    `TypeOfFunds` STRING,
    `InvestorCode` STRING,
    `CategoryCode` STRING,
    `RptCode` STRING,
    `TrnCode` STRING,
    `CollectionsDebit` DECIMAL(38,10),
    `CollectionsCredit` DECIMAL(38,10),
    `InvestorDebit` DECIMAL(38,10),
    `InvestorCredit` DECIMAL(38,10),
    `CorporateDebit` DECIMAL(38,10),
    `CorporateCredit` DECIMAL(38,10),
    `TypeCode` STRING,
    `ClientCode` STRING,
    `ClientName` STRING,
    `ReportDate` DATE,
    `ReportNumber` BIGINT,
    `FILE_NAME_DMI` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_t69w IS 
'The table contains financial transaction data related to various accounts and clients. Key information includes transaction amounts for collections and investments, along with codes specifying the type of funds, payees, and clients. Use cases for this data may involve financial reporting, analyzing transaction trends, and reconciling accounts.';

TRUNCATE TABLE dmi.default.dmi_t69w;

INSERT INTO dmi.default.dmi_t69w (
    `CorpCode`, `AccountNumber`, `CostCenterCode`, `PayeeCode`, `TypeOfFunds`, `InvestorCode`,
    `CategoryCode`, `RptCode`, `TrnCode`, `CollectionsDebit`, `CollectionsCredit`, `InvestorDebit`,
    `InvestorCredit`, `CorporateDebit`, `CorporateCredit`, `TypeCode`, `ClientCode`, `ClientName`,
    `ReportDate`, `ReportNumber`, `FILE_NAME_DMI`, `LOADED_AT`
)
SELECT
    concat('CORPCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CorpCode`,
    idx AS `AccountNumber`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CostCenterCode`,
    concat('PAYEECODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PayeeCode`,
    concat('TYPEOFFUNDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `TypeOfFunds`,
    concat('INVESTORCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `InvestorCode`,
    concat('CATEGORYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CategoryCode`,
    concat('RPTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `RptCode`,
    concat('TRNCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TrnCode`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CollectionsDebit`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CollectionsCredit`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InvestorDebit`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `InvestorCredit`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CorporateDebit`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CorporateCredit`,
    concat('TYPECODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TypeCode`,
    concat('CLIENTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ClientCode`,
    concat('CLIENTNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `ClientName`,
    date_add(DATE '2026-01-01', idx - 1) AS `ReportDate`,
    idx AS `ReportNumber`,
    concat('FILE_NAME_DMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `FILE_NAME_DMI`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: static query dmi_transaction_codes_mapping
CREATE TABLE IF NOT EXISTS dmi.default.dmi_transaction_codes_mapping (
    `SHEET` STRING,
    `TRAN_CODE` STRING,
    `CATEGORY` STRING,
    `DESCRIPTION` STRING,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE dmi.default.dmi_transaction_codes_mapping IS 
'The table contains a mapping of transaction codes to their respective descriptions and categories. It includes information on the source sheet and the time the data was loaded. This data can be useful for understanding transaction classifications, integrating with other systems, and maintaining consistency in transaction coding across different processes';

TRUNCATE TABLE dmi.default.dmi_transaction_codes_mapping;

INSERT INTO dmi.default.dmi_transaction_codes_mapping (
    `SHEET`, `TRAN_CODE`, `CATEGORY`, `DESCRIPTION`, `LOADED_AT`
)
SELECT
    concat('SHEET_', lpad(CAST(idx AS STRING), 2, '0')) AS `SHEET`,
    concat('TRAN_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRAN_CODE`,
    concat('CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CATEGORY`,
    concat('DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `DESCRIPTION`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

SELECT 'dmi_bacmast' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_bacmast
UNION ALL
SELECT 'dmi_disb' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_disb
UNION ALL
SELECT 'dmi_e006' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_e006
UNION ALL
SELECT 'dmi_gl_mapping' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_gl_mapping
UNION ALL
SELECT 'dmi_noncash' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_noncash
UNION ALL
SELECT 'dmi_p110' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_p110
UNION ALL
SELECT 'dmi_p132' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_p132
UNION ALL
SELECT 'dmi_pmt' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_pmt
UNION ALL
SELECT 'dmi_s2tt' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_s2tt
UNION ALL
SELECT 'dmi_s2tv' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_s2tv
UNION ALL
SELECT 'dmi_s5az' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_s5az
UNION ALL
SELECT 'dmi_t69w' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_t69w
UNION ALL
SELECT 'dmi_transaction_codes_mapping' AS table_name, COUNT(*) AS record_count
FROM dmi.default.dmi_transaction_codes_mapping;
