-- Databricks SQL for source: manual
-- Generated from sqlserver/brz-manual.sql

CREATE CATALOG IF NOT EXISTS manual;
USE CATALOG manual;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."FILE_APEX_MONTHLY_ACCOUNTS"
CREATE TABLE IF NOT EXISTS manual.default.file_apex_monthly_accounts (
    `CLIENT_CODE` STRING,
    `CORRESPONDENT_CODE` STRING,
    `ACCOUNT_GROUP_CODE` STRING,
    `ACCOUNT_NUMBER` STRING,
    `BILLING_CALENDAR_MONTH` INT,
    `BILLING_CALENDAR_YEAR` INT,
    `BILLING_TRANSACTION_ID` INT,
    `BILLING_SECTION` STRING,
    `BILLING_CATEGORY` STRING,
    `BILLING_SUB_CATEGORY` STRING,
    `BILLING_NAME_RATE` STRING,
    `BILLING_RATE` DECIMAL(38,10),
    `PROCESS_START_DATE` DATE,
    `PROCESS_END_DATE` DATE,
    `FUNDED_START_DATE` DATE,
    `FUNDED_END_DATE` DATE,
    `AVG_MONTHLY_EQUITY` DECIMAL(38,10),
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_apex_monthly_accounts;

INSERT INTO manual.default.file_apex_monthly_accounts (
    `CLIENT_CODE`, `CORRESPONDENT_CODE`, `ACCOUNT_GROUP_CODE`, `ACCOUNT_NUMBER`, `BILLING_CALENDAR_MONTH`, `BILLING_CALENDAR_YEAR`,
    `BILLING_TRANSACTION_ID`, `BILLING_SECTION`, `BILLING_CATEGORY`, `BILLING_SUB_CATEGORY`, `BILLING_NAME_RATE`, `BILLING_RATE`,
    `PROCESS_START_DATE`, `PROCESS_END_DATE`, `FUNDED_START_DATE`, `FUNDED_END_DATE`, `AVG_MONTHLY_EQUITY`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('CLIENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLIENT_CODE`,
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORRESPONDENT_CODE`,
    concat('ACCOUNT_GROUP_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_GROUP_CODE`,
    concat('ACCOUNT_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NUMBER`,
    idx AS `BILLING_CALENDAR_MONTH`,
    idx AS `BILLING_CALENDAR_YEAR`,
    idx AS `BILLING_TRANSACTION_ID`,
    concat('BILLING_SECTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SECTION`,
    concat('BILLING_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_CATEGORY`,
    concat('BILLING_SUB_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SUB_CATEGORY`,
    concat('BILLING_NAME_RATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_NAME_RATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BILLING_RATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PROCESS_START_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PROCESS_END_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `FUNDED_START_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `FUNDED_END_DATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AVG_MONTHLY_EQUITY`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_APEX_MONTHLY_CREDIT"
CREATE TABLE IF NOT EXISTS manual.default.file_apex_monthly_credit (
    `CLIENT_CODE` STRING,
    `CORRESPONDENT_CODE` STRING,
    `ACCOUNT_GROUP_CODE` STRING,
    `ACCOUNT_NUMBER` STRING,
    `BILLING_CALENDAR_MONTH` INT,
    `BILLING_CALENDAR_YEAR` INT,
    `BILLING_TRANSACTION_ID` INT,
    `BILLING_SECTION` STRING,
    `BILLING_CATEGORY` STRING,
    `BILLING_SUB_CATEGORY` STRING,
    `BILLING_NAME_RATE` STRING,
    `RATE_PERCENT` DECIMAL(38,10),
    `CASH_SETTLE_BALANCE` DECIMAL(38,10),
    `BILLING_RATE` DECIMAL(38,10),
    `PROCESS_START_DATE` DATE,
    `PROCESS_END_DATE` DATE,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_apex_monthly_credit;

INSERT INTO manual.default.file_apex_monthly_credit (
    `CLIENT_CODE`, `CORRESPONDENT_CODE`, `ACCOUNT_GROUP_CODE`, `ACCOUNT_NUMBER`, `BILLING_CALENDAR_MONTH`, `BILLING_CALENDAR_YEAR`,
    `BILLING_TRANSACTION_ID`, `BILLING_SECTION`, `BILLING_CATEGORY`, `BILLING_SUB_CATEGORY`, `BILLING_NAME_RATE`, `RATE_PERCENT`,
    `CASH_SETTLE_BALANCE`, `BILLING_RATE`, `PROCESS_START_DATE`, `PROCESS_END_DATE`, `DATE_OF_DATA`, `YEARMONTH`,
    `LOADED_AT`
)
SELECT
    concat('CLIENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLIENT_CODE`,
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORRESPONDENT_CODE`,
    concat('ACCOUNT_GROUP_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_GROUP_CODE`,
    concat('ACCOUNT_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NUMBER`,
    idx AS `BILLING_CALENDAR_MONTH`,
    idx AS `BILLING_CALENDAR_YEAR`,
    idx AS `BILLING_TRANSACTION_ID`,
    concat('BILLING_SECTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SECTION`,
    concat('BILLING_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_CATEGORY`,
    concat('BILLING_SUB_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SUB_CATEGORY`,
    concat('BILLING_NAME_RATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_NAME_RATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RATE_PERCENT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CASH_SETTLE_BALANCE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BILLING_RATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PROCESS_START_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PROCESS_END_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_APEX_MONTHLY_EXECUTION"
CREATE TABLE IF NOT EXISTS manual.default.file_apex_monthly_execution (
    `BILLINGPERIOD` STRING,
    `CLEARINGACCOUNT` STRING,
    `INSTRUMENTTYPE` STRING,
    `CUSTOMER_VENUE` STRING,
    `APEXROUTE` STRING,
    `DESCRIPTION` STRING,
    `EXCH` STRING,
    `ORDERS` INT,
    `FILLS` INT,
    `NOTIONAL` DECIMAL(38,10),
    `QUANTITY` DECIMAL(38,10),
    `CUSTOMERPASSTHRUFEE` DECIMAL(38,10),
    `EXECUTION_FEE` DECIMAL(38,10),
    `CUSTOMER_PFOF` DECIMAL(38,10),
    `CUSTOMER_INDEX_SURCHARGE` DECIMAL(38,10),
    `CATHISTORICALFEE` DECIMAL(38,10),
    `CATONGOINGFEE` DECIMAL(38,10),
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_apex_monthly_execution;

INSERT INTO manual.default.file_apex_monthly_execution (
    `BILLINGPERIOD`, `CLEARINGACCOUNT`, `INSTRUMENTTYPE`, `CUSTOMER_VENUE`, `APEXROUTE`, `DESCRIPTION`,
    `EXCH`, `ORDERS`, `FILLS`, `NOTIONAL`, `QUANTITY`, `CUSTOMERPASSTHRUFEE`,
    `EXECUTION_FEE`, `CUSTOMER_PFOF`, `CUSTOMER_INDEX_SURCHARGE`, `CATHISTORICALFEE`, `CATONGOINGFEE`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('BILLINGPERIOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLINGPERIOD`,
    concat('CLEARINGACCOUNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLEARINGACCOUNT`,
    concat('INSTRUMENTTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSTRUMENTTYPE`,
    concat('CUSTOMER_VENUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSTOMER_VENUE`,
    concat('APEXROUTE_', lpad(CAST(idx AS STRING), 2, '0')) AS `APEXROUTE`,
    concat('DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `DESCRIPTION`,
    concat('EXCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXCH`,
    idx AS `ORDERS`,
    idx AS `FILLS`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NOTIONAL`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QUANTITY`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CUSTOMERPASSTHRUFEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EXECUTION_FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CUSTOMER_PFOF`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CUSTOMER_INDEX_SURCHARGE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CATHISTORICALFEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CATONGOINGFEE`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_APEX_MONTHLY_FDIC"
CREATE TABLE IF NOT EXISTS manual.default.file_apex_monthly_fdic (
    `CORRESPONDENT_CODE` STRING,
    `ACCOUNT_NUMBER` STRING,
    `ACCOUNT_ID` STRING,
    `FDIC_ASSET_SYMBOL` STRING,
    `BALANCE_DATE` DATE,
    `PRINCIPAL_BALANCE` DECIMAL(38,10),
    `ACCRUED_INTEREST` DECIMAL(38,10),
    `EFF` DECIMAL(38,10),
    `CORRESPONDENT_REBATE` DECIMAL(38,10),
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_apex_monthly_fdic;

INSERT INTO manual.default.file_apex_monthly_fdic (
    `CORRESPONDENT_CODE`, `ACCOUNT_NUMBER`, `ACCOUNT_ID`, `FDIC_ASSET_SYMBOL`, `BALANCE_DATE`, `PRINCIPAL_BALANCE`,
    `ACCRUED_INTEREST`, `EFF`, `CORRESPONDENT_REBATE`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORRESPONDENT_CODE`,
    concat('ACCOUNT_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NUMBER`,
    concat('ACCOUNT_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_ID`,
    concat('FDIC_ASSET_SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `FDIC_ASSET_SYMBOL`,
    date_add(DATE '2026-01-01', idx - 1) AS `BALANCE_DATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRINCIPAL_BALANCE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ACCRUED_INTEREST`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EFF`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CORRESPONDENT_REBATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_APEX_MONTHLY_TRADES"
CREATE TABLE IF NOT EXISTS manual.default.file_apex_monthly_trades (
    `CLIENT_CODE` STRING,
    `CORRESPONDENT_CODE` STRING,
    `ACCOUNT_GROUP_CODE` STRING,
    `ACCOUNT_NUMBER` STRING,
    `BILLING_CALENDAR_MONTH` INT,
    `BILLING_CALENDAR_YEAR` INT,
    `BILLING_TRANSACTION_ID` INT,
    `BILLING_SECTION` STRING,
    `BILLING_CATEGORY` STRING,
    `BILLING_SUB_CATEGORY` STRING,
    `BILLING_NAME_RATE` STRING,
    `BILLING_RATE` DECIMAL(38,10),
    `FUNDING_TYPE` STRING,
    `ACTIVITY_DATE` DATE,
    `PROCESS_DATE` DATE,
    `SETTLE_DATE` DATE,
    `ACTIVITY_ID` STRING,
    `SYMBOL` STRING,
    `CUSIP` STRING,
    `ACTIVITY_DESCRIPTION` STRING,
    `SIDE` STRING,
    `EXCHANGE` STRING,
    `ASSET_TYPE` STRING,
    `INSTRUMENT_TYPE` STRING,
    `INSTRUMENT_SUBTYPE` STRING,
    `REGION_CODE` STRING,
    `CURRENCY_CODE` STRING,
    `QUANTITY` DECIMAL(38,10),
    `PRICE` DECIMAL(38,10),
    `GROSS_AMOUNT` DECIMAL(38,10),
    `NET_AMOUNT` DECIMAL(38,10),
    `FEES` DECIMAL(38,10),
    `COMMISSION` DECIMAL(38,10),
    `MARKDOWN` DECIMAL(38,10),
    `MARKUP` DECIMAL(38,10),
    `BROKER` STRING,
    `ROUTE` STRING,
    `EXCHANGE_TYPE` STRING,
    `BROKER_CAPACITY` STRING,
    `ALGO` STRING,
    `EXTERNAL_ID` STRING,
    `CLIENT_ORDER_ID` STRING,
    `ORDER_ID` STRING,
    `EXECUTION_ID` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_apex_monthly_trades;

INSERT INTO manual.default.file_apex_monthly_trades (
    `CLIENT_CODE`, `CORRESPONDENT_CODE`, `ACCOUNT_GROUP_CODE`, `ACCOUNT_NUMBER`, `BILLING_CALENDAR_MONTH`, `BILLING_CALENDAR_YEAR`,
    `BILLING_TRANSACTION_ID`, `BILLING_SECTION`, `BILLING_CATEGORY`, `BILLING_SUB_CATEGORY`, `BILLING_NAME_RATE`, `BILLING_RATE`,
    `FUNDING_TYPE`, `ACTIVITY_DATE`, `PROCESS_DATE`, `SETTLE_DATE`, `ACTIVITY_ID`, `SYMBOL`,
    `CUSIP`, `ACTIVITY_DESCRIPTION`, `SIDE`, `EXCHANGE`, `ASSET_TYPE`, `INSTRUMENT_TYPE`,
    `INSTRUMENT_SUBTYPE`, `REGION_CODE`, `CURRENCY_CODE`, `QUANTITY`, `PRICE`, `GROSS_AMOUNT`,
    `NET_AMOUNT`, `FEES`, `COMMISSION`, `MARKDOWN`, `MARKUP`, `BROKER`,
    `ROUTE`, `EXCHANGE_TYPE`, `BROKER_CAPACITY`, `ALGO`, `EXTERNAL_ID`, `CLIENT_ORDER_ID`,
    `ORDER_ID`, `EXECUTION_ID`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('CLIENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLIENT_CODE`,
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORRESPONDENT_CODE`,
    concat('ACCOUNT_GROUP_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_GROUP_CODE`,
    concat('ACCOUNT_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NUMBER`,
    idx AS `BILLING_CALENDAR_MONTH`,
    idx AS `BILLING_CALENDAR_YEAR`,
    idx AS `BILLING_TRANSACTION_ID`,
    concat('BILLING_SECTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SECTION`,
    concat('BILLING_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_CATEGORY`,
    concat('BILLING_SUB_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_SUB_CATEGORY`,
    concat('BILLING_NAME_RATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLING_NAME_RATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BILLING_RATE`,
    concat('FUNDING_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FUNDING_TYPE`,
    date_add(DATE '2026-01-01', idx - 1) AS `ACTIVITY_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `PROCESS_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `SETTLE_DATE`,
    concat('ACTIVITY_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTIVITY_ID`,
    concat('SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `SYMBOL`,
    concat('CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSIP`,
    concat('ACTIVITY_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTIVITY_DESCRIPTION`,
    concat('SIDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SIDE`,
    concat('EXCHANGE_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXCHANGE`,
    concat('ASSET_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASSET_TYPE`,
    concat('INSTRUMENT_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSTRUMENT_TYPE`,
    concat('INSTRUMENT_SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSTRUMENT_SUBTYPE`,
    concat('REGION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `REGION_CODE`,
    concat('CURRENCY_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CURRENCY_CODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QUANTITY`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRICE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `GROSS_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NET_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FEES`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `COMMISSION`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MARKDOWN`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MARKUP`,
    concat('BROKER_', lpad(CAST(idx AS STRING), 2, '0')) AS `BROKER`,
    concat('ROUTE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ROUTE`,
    concat('EXCHANGE_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXCHANGE_TYPE`,
    concat('BROKER_CAPACITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BROKER_CAPACITY`,
    concat('ALGO_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALGO`,
    concat('EXTERNAL_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXTERNAL_ID`,
    concat('CLIENT_ORDER_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLIENT_ORDER_ID`,
    concat('ORDER_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORDER_ID`,
    concat('EXECUTION_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXECUTION_ID`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_BFLCRTRAN"
CREATE TABLE IF NOT EXISTS manual.default.file_bflcrtran (
    `TREFF6` STRING,
    `TRDAT6` STRING,
    `TRANCD` STRING,
    `DORC` STRING,
    `AMT` DECIMAL(38,10),
    `PFGLAC` STRING,
    `BATCH` STRING,
    `DDSD1` STRING,
    `DDSD2` STRING,
    `LCMACC` STRING,
    `CIFNO` STRING,
    `BRANCH` STRING,
    `GLCOST` STRING,
    `GLPROD` STRING,
    `GROUP` STRING,
    `TRACCT` STRING,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_bflcrtran;

INSERT INTO manual.default.file_bflcrtran (
    `TREFF6`, `TRDAT6`, `TRANCD`, `DORC`, `AMT`, `PFGLAC`,
    `BATCH`, `DDSD1`, `DDSD2`, `LCMACC`, `CIFNO`, `BRANCH`,
    `GLCOST`, `GLPROD`, `GROUP`, `TRACCT`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('TREFF6_', lpad(CAST(idx AS STRING), 2, '0')) AS `TREFF6`,
    concat('TRDAT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRDAT6`,
    concat('TRANCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRANCD`,
    concat('DORC_', lpad(CAST(idx AS STRING), 2, '0')) AS `DORC`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AMT`,
    concat('PFGLAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PFGLAC`,
    concat('BATCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `BATCH`,
    concat('DDSD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `DDSD1`,
    concat('DDSD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `DDSD2`,
    concat('LCMACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LCMACC`,
    concat('CIFNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `CIFNO`,
    concat('BRANCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `BRANCH`,
    concat('GLCOST_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLCOST`,
    concat('GLPROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPROD`,
    concat('GROUP_', lpad(CAST(idx AS STRING), 2, '0')) AS `GROUP`,
    concat('TRACCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRACCT`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_BIU_ACTIVITY"
CREATE TABLE IF NOT EXISTS manual.default.file_biu_activity (
    `ACCOUNT_NUMBER` STRING,
    `END_AUMS` DECIMAL(38,10),
    `MGMT_FEES` DECIMAL(38,10),
    `IB_FEES` DECIMAL(38,10),
    `NET_MGMT_FEE` DECIMAL(38,10),
    `SUB_ADVISOR_FEE` DECIMAL(38,10),
    `OUTSTANDING` DECIMAL(38,10),
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_biu_activity;

INSERT INTO manual.default.file_biu_activity (
    `ACCOUNT_NUMBER`, `END_AUMS`, `MGMT_FEES`, `IB_FEES`, `NET_MGMT_FEE`, `SUB_ADVISOR_FEE`,
    `OUTSTANDING`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('ACCOUNT_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NUMBER`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `END_AUMS`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MGMT_FEES`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `IB_FEES`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NET_MGMT_FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SUB_ADVISOR_FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `OUTSTANDING`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_FEDLINK_INC"
CREATE TABLE IF NOT EXISTS manual.default.file_fedlink_inc (
    `PAY_VIA` STRING,
    `TYPE` STRING,
    `TRACEKEY` STRING,
    `REF` STRING,
    `ACCOUNT` STRING,
    `NAME` STRING,
    `PRODCODE` STRING,
    `SUBTYPE` STRING,
    `LOADDATE` TIMESTAMP,
    `DATETIME` TIMESTAMP,
    `SENDERABA` STRING,
    `SENDERNAME` STRING,
    `RECEIVERABA` STRING,
    `RECEIVERNAME` STRING,
    `ORG` STRING,
    `ORGCDE` STRING,
    `ORGACC` STRING,
    `ORG1` STRING,
    `ORG2` STRING,
    `ORG3` STRING,
    `ORGCTRY` STRING,
    `OGB` STRING,
    `OGBCDE` STRING,
    `OGBACC` STRING,
    `OGB1` STRING,
    `OGB2` STRING,
    `OGB3` STRING,
    `OGBCTRY` STRING,
    `IBK` STRING,
    `IBKCDE` STRING,
    `IBKACC` STRING,
    `IBK1` STRING,
    `IBK2` STRING,
    `IBK3` STRING,
    `IBKCTRY` STRING,
    `BBK` STRING,
    `BBKCDE` STRING,
    `BBKACC` STRING,
    `BBK1` STRING,
    `BBK2` STRING,
    `BBK3` STRING,
    `BBKCTRY` STRING,
    `BNF` STRING,
    `BNFCDE` STRING,
    `BNFACC` STRING,
    `BNF1` STRING,
    `BNF2` STRING,
    `BNF3` STRING,
    `BNFCTRY` STRING,
    `OBI` STRING,
    `OBI1` STRING,
    `OBI2` STRING,
    `OBI3` STRING,
    `BBI` STRING,
    `BBI1` STRING,
    `BBI2` STRING,
    `BBI3` STRING,
    `BBI4` STRING,
    `BBI5` STRING,
    `INS` STRING,
    `INSCDE` STRING,
    `INSACC` STRING,
    `INS1` STRING,
    `INS2` STRING,
    `INS3` STRING,
    `INSCTRY` STRING,
    `VERBIAGE` STRING,
    `ORIGREF` STRING,
    `SENDERREF` STRING,
    `AMOUNT` DECIMAL(38,10),
    `FEE` DECIMAL(38,10),
    `DEDUCT_FEE` DECIMAL(38,10),
    `DEDUCT_FEE1` DECIMAL(38,10),
    `CHARGEBNF` STRING,
    `OFFICER` STRING,
    `CENTER` STRING,
    `FOREIGN` STRING,
    `BANKNUMBER` STRING,
    `COMMENT` STRING,
    `OFFSETACC` STRING,
    `PROCESSOR` STRING,
    `CURRCODE` STRING,
    `CURRAMOUNT` DECIMAL(38,10),
    `OMAD` STRING,
    `SOURCE` STRING,
    `ORGCENTER` STRING,
    `FXPROVIDER` STRING,
    `CRDCURRCODE` STRING,
    `CRDCURRAMT` DECIMAL(38,10),
    `FXRATE` DECIMAL(38,10),
    `FXCUSTRATE` DECIMAL(38,10),
    `FXVALDATE` STRING,
    `FXCONTRACT` STRING,
    `SOURCEPREP` STRING,
    `SOURCEAUTH1` STRING,
    `SOURCEAUTH2` STRING,
    `EXP_96` STRING,
    `EXP_97` STRING,
    `EXP_98` STRING,
    `EXP_99` STRING,
    `EXP_100` STRING,
    `EXP_101` STRING,
    `EXPDATE` DATE,
    `LOADTIME` STRING,
    `PREPARER` STRING,
    `PREPDATE` DATE,
    `PREPTIME` STRING,
    `AUTHOR1` STRING,
    `AUTHOR2` STRING,
    `AUTHDATE` DATE,
    `AUTHTIME` STRING,
    `COR` STRING,
    `CORCDE` STRING,
    `CORACC` STRING,
    `COR1` STRING,
    `COR2` STRING,
    `COR3` STRING,
    `CORCTRY` STRING,
    `MTMSG` STRING,
    `RFB` STRING,
    `PRODCODE1` STRING,
    `LOCALINSCD` STRING,
    `OFACAUTH` STRING,
    `OFACCOMM` STRING,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_fedlink_inc;

INSERT INTO manual.default.file_fedlink_inc (
    `PAY_VIA`, `TYPE`, `TRACEKEY`, `REF`, `ACCOUNT`, `NAME`,
    `PRODCODE`, `SUBTYPE`, `LOADDATE`, `DATETIME`, `SENDERABA`, `SENDERNAME`,
    `RECEIVERABA`, `RECEIVERNAME`, `ORG`, `ORGCDE`, `ORGACC`, `ORG1`,
    `ORG2`, `ORG3`, `ORGCTRY`, `OGB`, `OGBCDE`, `OGBACC`,
    `OGB1`, `OGB2`, `OGB3`, `OGBCTRY`, `IBK`, `IBKCDE`,
    `IBKACC`, `IBK1`, `IBK2`, `IBK3`, `IBKCTRY`, `BBK`,
    `BBKCDE`, `BBKACC`, `BBK1`, `BBK2`, `BBK3`, `BBKCTRY`,
    `BNF`, `BNFCDE`, `BNFACC`, `BNF1`, `BNF2`, `BNF3`,
    `BNFCTRY`, `OBI`, `OBI1`, `OBI2`, `OBI3`, `BBI`,
    `BBI1`, `BBI2`, `BBI3`, `BBI4`, `BBI5`, `INS`,
    `INSCDE`, `INSACC`, `INS1`, `INS2`, `INS3`, `INSCTRY`,
    `VERBIAGE`, `ORIGREF`, `SENDERREF`, `AMOUNT`, `FEE`, `DEDUCT_FEE`,
    `DEDUCT_FEE1`, `CHARGEBNF`, `OFFICER`, `CENTER`, `FOREIGN`, `BANKNUMBER`,
    `COMMENT`, `OFFSETACC`, `PROCESSOR`, `CURRCODE`, `CURRAMOUNT`, `OMAD`,
    `SOURCE`, `ORGCENTER`, `FXPROVIDER`, `CRDCURRCODE`, `CRDCURRAMT`, `FXRATE`,
    `FXCUSTRATE`, `FXVALDATE`, `FXCONTRACT`, `SOURCEPREP`, `SOURCEAUTH1`, `SOURCEAUTH2`,
    `EXP_96`, `EXP_97`, `EXP_98`, `EXP_99`, `EXP_100`, `EXP_101`,
    `EXPDATE`, `LOADTIME`, `PREPARER`, `PREPDATE`, `PREPTIME`, `AUTHOR1`,
    `AUTHOR2`, `AUTHDATE`, `AUTHTIME`, `COR`, `CORCDE`, `CORACC`,
    `COR1`, `COR2`, `COR3`, `CORCTRY`, `MTMSG`, `RFB`,
    `PRODCODE1`, `LOCALINSCD`, `OFACAUTH`, `OFACCOMM`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    'INCOMING' AS `PAY_VIA`,
    concat('TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TYPE`,
    concat('TRACEKEY_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRACEKEY`,
    concat('REF_', lpad(CAST(idx AS STRING), 2, '0')) AS `REF`,
    concat('ACCOUNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT`,
    concat('NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `NAME`,
    concat('PRODCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODCODE`,
    concat('SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUBTYPE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `LOADDATE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `DATETIME`,
    concat('SENDERABA_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERABA`,
    concat('SENDERNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERNAME`,
    concat('RECEIVERABA_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECEIVERABA`,
    concat('RECEIVERNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECEIVERNAME`,
    concat('ORG_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG`,
    concat('ORGCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCDE`,
    concat('ORGACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGACC`,
    concat('ORG1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG1`,
    concat('ORG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG2`,
    concat('ORG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG3`,
    concat('ORGCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCTRY`,
    concat('OGB_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB`,
    concat('OGBCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBCDE`,
    concat('OGBACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBACC`,
    concat('OGB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB1`,
    concat('OGB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB2`,
    concat('OGB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB3`,
    concat('OGBCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBCTRY`,
    concat('IBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK`,
    concat('IBKCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKCDE`,
    concat('IBKACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKACC`,
    concat('IBK1_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK1`,
    concat('IBK2_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK2`,
    concat('IBK3_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK3`,
    concat('IBKCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKCTRY`,
    concat('BBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK`,
    concat('BBKCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKCDE`,
    concat('BBKACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKACC`,
    concat('BBK1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK1`,
    concat('BBK2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK2`,
    concat('BBK3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK3`,
    concat('BBKCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKCTRY`,
    concat('BNF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF`,
    concat('BNFCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFCDE`,
    concat('BNFACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFACC`,
    concat('BNF1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF1`,
    concat('BNF2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF2`,
    concat('BNF3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF3`,
    concat('BNFCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFCTRY`,
    concat('OBI_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI`,
    concat('OBI1_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI1`,
    concat('OBI2_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI2`,
    concat('OBI3_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI3`,
    concat('BBI_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI`,
    concat('BBI1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI1`,
    concat('BBI2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI2`,
    concat('BBI3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI3`,
    concat('BBI4_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI4`,
    concat('BBI5_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI5`,
    concat('INS_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS`,
    concat('INSCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSCDE`,
    concat('INSACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSACC`,
    concat('INS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS1`,
    concat('INS2_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS2`,
    concat('INS3_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS3`,
    concat('INSCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSCTRY`,
    concat('VERBIAGE_', lpad(CAST(idx AS STRING), 2, '0')) AS `VERBIAGE`,
    concat('ORIGREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGREF`,
    concat('SENDERREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERREF`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DEDUCT_FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DEDUCT_FEE1`,
    concat('CHARGEBNF_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHARGEBNF`,
    concat('OFFICER_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFICER`,
    concat('CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CENTER`,
    concat('FOREIGN_', lpad(CAST(idx AS STRING), 2, '0')) AS `FOREIGN`,
    concat('BANKNUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANKNUMBER`,
    concat('COMMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMMENT`,
    concat('OFFSETACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFSETACC`,
    concat('PROCESSOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROCESSOR`,
    concat('CURRCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CURRCODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CURRAMOUNT`,
    concat('OMAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `OMAD`,
    concat('SOURCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCE`,
    concat('ORGCENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCENTER`,
    concat('FXPROVIDER_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXPROVIDER`,
    concat('CRDCURRCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRDCURRCODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CRDCURRAMT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FXRATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FXCUSTRATE`,
    concat('FXVALDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXVALDATE`,
    concat('FXCONTRACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXCONTRACT`,
    concat('SOURCEPREP_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEPREP`,
    concat('SOURCEAUTH1_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEAUTH1`,
    concat('SOURCEAUTH2_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEAUTH2`,
    concat('EXP_96_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_96`,
    concat('EXP_97_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_97`,
    concat('EXP_98_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_98`,
    concat('EXP_99_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_99`,
    concat('EXP_100_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_100`,
    concat('EXP_101_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_101`,
    date_add(DATE '2026-01-01', idx - 1) AS `EXPDATE`,
    concat('LOADTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOADTIME`,
    concat('PREPARER_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPARER`,
    date_add(DATE '2026-01-01', idx - 1) AS `PREPDATE`,
    concat('PREPTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPTIME`,
    concat('AUTHOR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHOR1`,
    concat('AUTHOR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHOR2`,
    date_add(DATE '2026-01-01', idx - 1) AS `AUTHDATE`,
    concat('AUTHTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHTIME`,
    concat('COR_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR`,
    concat('CORCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORCDE`,
    concat('CORACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORACC`,
    concat('COR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR1`,
    concat('COR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR2`,
    concat('COR3_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR3`,
    concat('CORCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORCTRY`,
    concat('MTMSG_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTMSG`,
    concat('RFB_', lpad(CAST(idx AS STRING), 2, '0')) AS `RFB`,
    concat('PRODCODE1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODCODE1`,
    concat('LOCALINSCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOCALINSCD`,
    concat('OFACAUTH_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFACAUTH`,
    concat('OFACCOMM_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFACCOMM`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_FEDLINK_OUT"
CREATE TABLE IF NOT EXISTS manual.default.file_fedlink_out (
    `PAY_VIA` STRING,
    `TYPE` STRING,
    `TRACEKEY` STRING,
    `REF` STRING,
    `ACCOUNT` STRING,
    `NAME` STRING,
    `PRODCODE` STRING,
    `SUBTYPE` STRING,
    `LOADDATE` TIMESTAMP,
    `DATETIME` TIMESTAMP,
    `SENDERABA` STRING,
    `SENDERNAME` STRING,
    `RECEIVERABA` STRING,
    `RECEIVERNAME` STRING,
    `ORG` STRING,
    `ORGCDE` STRING,
    `ORGACC` STRING,
    `ORG1` STRING,
    `ORG2` STRING,
    `ORG3` STRING,
    `ORGCTRY` STRING,
    `OGB` STRING,
    `OGBCDE` STRING,
    `OGBACC` STRING,
    `OGB1` STRING,
    `OGB2` STRING,
    `OGB3` STRING,
    `OGBCTRY` STRING,
    `IBK` STRING,
    `IBKCDE` STRING,
    `IBKACC` STRING,
    `IBK1` STRING,
    `IBK2` STRING,
    `IBK3` STRING,
    `IBKCTRY` STRING,
    `BBK` STRING,
    `BBKCDE` STRING,
    `BBKACC` STRING,
    `BBK1` STRING,
    `BBK2` STRING,
    `BBK3` STRING,
    `BBKCTRY` STRING,
    `BNF` STRING,
    `BNFCDE` STRING,
    `BNFACC` STRING,
    `BNF1` STRING,
    `BNF2` STRING,
    `BNF3` STRING,
    `BNFCTRY` STRING,
    `OBI` STRING,
    `OBI1` STRING,
    `OBI2` STRING,
    `OBI3` STRING,
    `BBI` STRING,
    `BBI1` STRING,
    `BBI2` STRING,
    `BBI3` STRING,
    `BBI4` STRING,
    `BBI5` STRING,
    `INS` STRING,
    `INSCDE` STRING,
    `INSACC` STRING,
    `INS1` STRING,
    `INS2` STRING,
    `INS3` STRING,
    `INSCTRY` STRING,
    `VERBIAGE` STRING,
    `ORIGREF` STRING,
    `SENDERREF` STRING,
    `AMOUNT` DECIMAL(38,10),
    `FEE` DECIMAL(38,10),
    `DEDUCT_FEE` DECIMAL(38,10),
    `DEDUCT_FEE1` DECIMAL(38,10),
    `CHARGEBNF` STRING,
    `OFFICER` STRING,
    `CENTER` STRING,
    `FOREIGN` STRING,
    `BANKNUMBER` STRING,
    `COMMENT` STRING,
    `OFFSETACC` STRING,
    `PROCESSOR` STRING,
    `CURRCODE` STRING,
    `CURRAMOUNT` DECIMAL(38,10),
    `OMAD` STRING,
    `SOURCE` STRING,
    `ORGCENTER` STRING,
    `FXPROVIDER` STRING,
    `CRDCURRCODE` STRING,
    `CRDCURRAMT` DECIMAL(38,10),
    `FXRATE` DECIMAL(38,10),
    `FXCUSTRATE` DECIMAL(38,10),
    `FXVALDATE` STRING,
    `FXCONTRACT` STRING,
    `SOURCEPREP` STRING,
    `SOURCEAUTH1` STRING,
    `SOURCEAUTH2` STRING,
    `EXP_96` STRING,
    `EXP_97` STRING,
    `EXP_98` STRING,
    `EXP_99` STRING,
    `EXP_100` STRING,
    `EXP_101` STRING,
    `EXPDATE` DATE,
    `LOADTIME` STRING,
    `PREPARER` STRING,
    `PREPDATE` DATE,
    `PREPTIME` STRING,
    `AUTHOR1` STRING,
    `AUTHOR2` STRING,
    `AUTHDATE` DATE,
    `AUTHTIME` STRING,
    `COR` STRING,
    `CORCDE` STRING,
    `CORACC` STRING,
    `COR1` STRING,
    `COR2` STRING,
    `COR3` STRING,
    `CORCTRY` STRING,
    `MTMSG` STRING,
    `RFB` STRING,
    `PRODCODE1` STRING,
    `LOCALINSCD` STRING,
    `OFACAUTH` STRING,
    `OFACCOMM` STRING,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_fedlink_out;

INSERT INTO manual.default.file_fedlink_out (
    `PAY_VIA`, `TYPE`, `TRACEKEY`, `REF`, `ACCOUNT`, `NAME`,
    `PRODCODE`, `SUBTYPE`, `LOADDATE`, `DATETIME`, `SENDERABA`, `SENDERNAME`,
    `RECEIVERABA`, `RECEIVERNAME`, `ORG`, `ORGCDE`, `ORGACC`, `ORG1`,
    `ORG2`, `ORG3`, `ORGCTRY`, `OGB`, `OGBCDE`, `OGBACC`,
    `OGB1`, `OGB2`, `OGB3`, `OGBCTRY`, `IBK`, `IBKCDE`,
    `IBKACC`, `IBK1`, `IBK2`, `IBK3`, `IBKCTRY`, `BBK`,
    `BBKCDE`, `BBKACC`, `BBK1`, `BBK2`, `BBK3`, `BBKCTRY`,
    `BNF`, `BNFCDE`, `BNFACC`, `BNF1`, `BNF2`, `BNF3`,
    `BNFCTRY`, `OBI`, `OBI1`, `OBI2`, `OBI3`, `BBI`,
    `BBI1`, `BBI2`, `BBI3`, `BBI4`, `BBI5`, `INS`,
    `INSCDE`, `INSACC`, `INS1`, `INS2`, `INS3`, `INSCTRY`,
    `VERBIAGE`, `ORIGREF`, `SENDERREF`, `AMOUNT`, `FEE`, `DEDUCT_FEE`,
    `DEDUCT_FEE1`, `CHARGEBNF`, `OFFICER`, `CENTER`, `FOREIGN`, `BANKNUMBER`,
    `COMMENT`, `OFFSETACC`, `PROCESSOR`, `CURRCODE`, `CURRAMOUNT`, `OMAD`,
    `SOURCE`, `ORGCENTER`, `FXPROVIDER`, `CRDCURRCODE`, `CRDCURRAMT`, `FXRATE`,
    `FXCUSTRATE`, `FXVALDATE`, `FXCONTRACT`, `SOURCEPREP`, `SOURCEAUTH1`, `SOURCEAUTH2`,
    `EXP_96`, `EXP_97`, `EXP_98`, `EXP_99`, `EXP_100`, `EXP_101`,
    `EXPDATE`, `LOADTIME`, `PREPARER`, `PREPDATE`, `PREPTIME`, `AUTHOR1`,
    `AUTHOR2`, `AUTHDATE`, `AUTHTIME`, `COR`, `CORCDE`, `CORACC`,
    `COR1`, `COR2`, `COR3`, `CORCTRY`, `MTMSG`, `RFB`,
    `PRODCODE1`, `LOCALINSCD`, `OFACAUTH`, `OFACCOMM`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    'OUTGOING' AS `PAY_VIA`,
    concat('TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TYPE`,
    concat('TRACEKEY_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRACEKEY`,
    concat('REF_', lpad(CAST(idx AS STRING), 2, '0')) AS `REF`,
    concat('ACCOUNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT`,
    concat('NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `NAME`,
    concat('PRODCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODCODE`,
    concat('SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUBTYPE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `LOADDATE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `DATETIME`,
    concat('SENDERABA_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERABA`,
    concat('SENDERNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERNAME`,
    concat('RECEIVERABA_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECEIVERABA`,
    concat('RECEIVERNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECEIVERNAME`,
    concat('ORG_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG`,
    concat('ORGCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCDE`,
    concat('ORGACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGACC`,
    concat('ORG1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG1`,
    concat('ORG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG2`,
    concat('ORG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORG3`,
    concat('ORGCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCTRY`,
    concat('OGB_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB`,
    concat('OGBCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBCDE`,
    concat('OGBACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBACC`,
    concat('OGB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB1`,
    concat('OGB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB2`,
    concat('OGB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGB3`,
    concat('OGBCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `OGBCTRY`,
    concat('IBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK`,
    concat('IBKCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKCDE`,
    concat('IBKACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKACC`,
    concat('IBK1_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK1`,
    concat('IBK2_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK2`,
    concat('IBK3_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBK3`,
    concat('IBKCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `IBKCTRY`,
    concat('BBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK`,
    concat('BBKCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKCDE`,
    concat('BBKACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKACC`,
    concat('BBK1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK1`,
    concat('BBK2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK2`,
    concat('BBK3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBK3`,
    concat('BBKCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBKCTRY`,
    concat('BNF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF`,
    concat('BNFCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFCDE`,
    concat('BNFACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFACC`,
    concat('BNF1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF1`,
    concat('BNF2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF2`,
    concat('BNF3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNF3`,
    concat('BNFCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BNFCTRY`,
    concat('OBI_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI`,
    concat('OBI1_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI1`,
    concat('OBI2_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI2`,
    concat('OBI3_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBI3`,
    concat('BBI_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI`,
    concat('BBI1_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI1`,
    concat('BBI2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI2`,
    concat('BBI3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI3`,
    concat('BBI4_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI4`,
    concat('BBI5_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBI5`,
    concat('INS_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS`,
    concat('INSCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSCDE`,
    concat('INSACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSACC`,
    concat('INS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS1`,
    concat('INS2_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS2`,
    concat('INS3_', lpad(CAST(idx AS STRING), 2, '0')) AS `INS3`,
    concat('INSCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSCTRY`,
    concat('VERBIAGE_', lpad(CAST(idx AS STRING), 2, '0')) AS `VERBIAGE`,
    concat('ORIGREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGREF`,
    concat('SENDERREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `SENDERREF`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DEDUCT_FEE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DEDUCT_FEE1`,
    concat('CHARGEBNF_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHARGEBNF`,
    concat('OFFICER_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFICER`,
    concat('CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CENTER`,
    concat('FOREIGN_', lpad(CAST(idx AS STRING), 2, '0')) AS `FOREIGN`,
    concat('BANKNUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANKNUMBER`,
    concat('COMMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMMENT`,
    concat('OFFSETACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFSETACC`,
    concat('PROCESSOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROCESSOR`,
    concat('CURRCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CURRCODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CURRAMOUNT`,
    concat('OMAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `OMAD`,
    concat('SOURCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCE`,
    concat('ORGCENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGCENTER`,
    concat('FXPROVIDER_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXPROVIDER`,
    concat('CRDCURRCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRDCURRCODE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CRDCURRAMT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FXRATE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FXCUSTRATE`,
    concat('FXVALDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXVALDATE`,
    concat('FXCONTRACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `FXCONTRACT`,
    concat('SOURCEPREP_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEPREP`,
    concat('SOURCEAUTH1_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEAUTH1`,
    concat('SOURCEAUTH2_', lpad(CAST(idx AS STRING), 2, '0')) AS `SOURCEAUTH2`,
    concat('EXP_96_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_96`,
    concat('EXP_97_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_97`,
    concat('EXP_98_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_98`,
    concat('EXP_99_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_99`,
    concat('EXP_100_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_100`,
    concat('EXP_101_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXP_101`,
    date_add(DATE '2026-01-01', idx - 1) AS `EXPDATE`,
    concat('LOADTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOADTIME`,
    concat('PREPARER_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPARER`,
    date_add(DATE '2026-01-01', idx - 1) AS `PREPDATE`,
    concat('PREPTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPTIME`,
    concat('AUTHOR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHOR1`,
    concat('AUTHOR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHOR2`,
    date_add(DATE '2026-01-01', idx - 1) AS `AUTHDATE`,
    concat('AUTHTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTHTIME`,
    concat('COR_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR`,
    concat('CORCDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORCDE`,
    concat('CORACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORACC`,
    concat('COR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR1`,
    concat('COR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR2`,
    concat('COR3_', lpad(CAST(idx AS STRING), 2, '0')) AS `COR3`,
    concat('CORCTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CORCTRY`,
    concat('MTMSG_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTMSG`,
    concat('RFB_', lpad(CAST(idx AS STRING), 2, '0')) AS `RFB`,
    concat('PRODCODE1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODCODE1`,
    concat('LOCALINSCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOCALINSCD`,
    concat('OFACAUTH_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFACAUTH`,
    concat('OFACCOMM_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFACCOMM`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_RDCI"
CREATE TABLE IF NOT EXISTS manual.default.file_rdci (
    `INSTRUMENT_ID` STRING,
    `ADJUSTED_AX_INTEREST` DECIMAL(38,10),
    `ADJUSTED_FTP_AMOUNT` DECIMAL(38,10),
    `NET_INTEREST_INCOME` DECIMAL(38,10),
    `NON_INTEREST_INCOME` DECIMAL(38,10),
    `TOTAL_REVENUE` DECIMAL(38,10),
    `TOTAL_NONINTEREST_EXPENSE` DECIMAL(38,10),
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_rdci;

INSERT INTO manual.default.file_rdci (
    `INSTRUMENT_ID`, `ADJUSTED_AX_INTEREST`, `ADJUSTED_FTP_AMOUNT`, `NET_INTEREST_INCOME`, `NON_INTEREST_INCOME`, `TOTAL_REVENUE`,
    `TOTAL_NONINTEREST_EXPENSE`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('INSTRUMENT_ID_', lpad(CAST(idx AS STRING), 2, '0')) AS `INSTRUMENT_ID`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ADJUSTED_AX_INTEREST`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ADJUSTED_FTP_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NET_INTEREST_INCOME`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NON_INTEREST_INCOME`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TOTAL_REVENUE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TOTAL_NONINTEREST_EXPENSE`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_TRAILER_FEES"
CREATE TABLE IF NOT EXISTS manual.default.file_trailer_fees (
    `PERSHING_ACCOUNT` STRING,
    `CUSIP` STRING,
    `ISIN` STRING,
    `AMOUNT` DECIMAL(38,10),
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_trailer_fees;

INSERT INTO manual.default.file_trailer_fees (
    `PERSHING_ACCOUNT`, `CUSIP`, `ISIN`, `AMOUNT`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('PERSHING_ACCOUNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PERSHING_ACCOUNT`,
    concat('CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSIP`,
    concat('ISIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ISIN`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AMOUNT`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."FILE_TRAILER_FEES_ACCRUALS"
CREATE TABLE IF NOT EXISTS manual.default.file_trailer_fees_accruals (
    `ACCOUNT_NO` STRING,
    `SHORT_NAME` STRING,
    `OFFICE` STRING,
    `IP` STRING,
    `SYMBOL` STRING,
    `CUSIP` STRING,
    `SEC_REGISTERED` STRING,
    `SECURITY_DESCRIPTION` STRING,
    `TRADE_DATE_QUANTITY` DECIMAL(38,10),
    `TRADE_DATE_MARKET_VALUE` DECIMAL(38,10),
    `PERCENTAGE_OF_GRAND_TOTAL_TRADE_DATE_MARKET_VALUE` DECIMAL(38,10),
    `TOTAL_SETTLEMENT_DATE_MARKET_VALUE` DECIMAL(38,10),
    `SETTLEMENT_DATE_QUANTITY` DECIMAL(38,10),
    `ACCOUNT_STATUS` STRING,
    `ACCRUED_AMOUNT` DECIMAL(38,10),
    `CLOSING_BALANCE` DECIMAL(38,10),
    `REFERENCE` STRING,
    `MANAGEMENT_FEES_PERCENTAGE` DECIMAL(38,10),
    `MANAGEMENT_FEES_AMOUNT` DECIMAL(38,10),
    `FUND_FAMILY_NAME` STRING,
    `COST_CENTER` STRING,
    `TEAM` STRING,
    `MONTH_YEAR` DATE,
    `YEARMONTH` INT,
    `GL_ACCOUNT` INT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE manual.default.file_trailer_fees_accruals;

INSERT INTO manual.default.file_trailer_fees_accruals (
    `ACCOUNT_NO`, `SHORT_NAME`, `OFFICE`, `IP`, `SYMBOL`, `CUSIP`,
    `SEC_REGISTERED`, `SECURITY_DESCRIPTION`, `TRADE_DATE_QUANTITY`, `TRADE_DATE_MARKET_VALUE`, `PERCENTAGE_OF_GRAND_TOTAL_TRADE_DATE_MARKET_VALUE`, `TOTAL_SETTLEMENT_DATE_MARKET_VALUE`,
    `SETTLEMENT_DATE_QUANTITY`, `ACCOUNT_STATUS`, `ACCRUED_AMOUNT`, `CLOSING_BALANCE`, `REFERENCE`, `MANAGEMENT_FEES_PERCENTAGE`,
    `MANAGEMENT_FEES_AMOUNT`, `FUND_FAMILY_NAME`, `COST_CENTER`, `TEAM`, `MONTH_YEAR`, `YEARMONTH`,
    `GL_ACCOUNT`, `LOADED_AT`
)
SELECT
    concat('ACCOUNT_NO_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_NO`,
    concat('SHORT_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `SHORT_NAME`,
    concat('OFFICE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFICE`,
    concat('IP_', lpad(CAST(idx AS STRING), 2, '0')) AS `IP`,
    concat('SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `SYMBOL`,
    concat('CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSIP`,
    concat('SEC_REGISTERED_', lpad(CAST(idx AS STRING), 2, '0')) AS `SEC_REGISTERED`,
    concat('SECURITY_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `SECURITY_DESCRIPTION`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TRADE_DATE_QUANTITY`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TRADE_DATE_MARKET_VALUE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PERCENTAGE_OF_GRAND_TOTAL_TRADE_DATE_MARKET_VALUE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TOTAL_SETTLEMENT_DATE_MARKET_VALUE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SETTLEMENT_DATE_QUANTITY`,
    concat('ACCOUNT_STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCOUNT_STATUS`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ACCRUED_AMOUNT`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CLOSING_BALANCE`,
    concat('REFERENCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `REFERENCE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MANAGEMENT_FEES_PERCENTAGE`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MANAGEMENT_FEES_AMOUNT`,
    concat('FUND_FAMILY_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `FUND_FAMILY_NAME`,
    concat('COST_CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `COST_CENTER`,
    concat('TEAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `TEAM`,
    date_add(DATE '2026-01-01', idx - 1) AS `MONTH_YEAR`,
    202601 AS `YEARMONTH`,
    idx AS `GL_ACCOUNT`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

SELECT 'file_apex_monthly_accounts' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_apex_monthly_accounts
UNION ALL
SELECT 'file_apex_monthly_credit' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_apex_monthly_credit
UNION ALL
SELECT 'file_apex_monthly_execution' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_apex_monthly_execution
UNION ALL
SELECT 'file_apex_monthly_fdic' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_apex_monthly_fdic
UNION ALL
SELECT 'file_apex_monthly_trades' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_apex_monthly_trades
UNION ALL
SELECT 'file_bflcrtran' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_bflcrtran
UNION ALL
SELECT 'file_biu_activity' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_biu_activity
UNION ALL
SELECT 'file_fedlink_inc' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_fedlink_inc
UNION ALL
SELECT 'file_fedlink_out' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_fedlink_out
UNION ALL
SELECT 'file_rdci' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_rdci
UNION ALL
SELECT 'file_trailer_fees' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_trailer_fees
UNION ALL
SELECT 'file_trailer_fees_accruals' AS table_name, COUNT(*) AS record_count
FROM manual.default.file_trailer_fees_accruals;
