-- NAME: BRONZE_PERS_ACCF
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

with landing_data as (
    SELECT
	    TRANSCODE
        ,RECORDIND
        ,RECORDSEQUENCEID
        ,ACCTNUMBER
        ,BROKERDEALERNUMBER
        ,INVESTMENTPRONUMBER
        ,ACCOUNTSHORTNAME
        ,TRANSACTIONTYPE
        ,AUTOTITLEDACCT
        ,ACCTTYPECODE
        ,REGISTRATIONTYPE
        ,NUMBERACCTTITLELINES
        ,ACCTREGISLINE1
        ,ACCTREGISLINE2
        ,ACCTREGISLINE3
        ,ACCTREGISLINE4
        ,ACCTREGISLINE5
        ,ACCTREGISLINE6
        ,USTENANCYINDICATOR
        ,MARRIEDINDICATOR
        ,TENANCYSTATE
        ,JOINTTENANCYCLAUSE
        ,AGREEMENTEXEDATE
        ,NUMBEROFTENANTS
        ,DATEACCTOPENED
        ,DATEACCTINFOUPDATED
        ,ACCTSTATUSINDICATOR
        ,PENDINGCLOSEDDATE
        ,DATEACCOUNTCLOSED
        ,ACCTREACTIVATEDDATE
        ,DATEACCOUNTREOPENED
        ,PROCEEDS
        ,TRANSINSTRUC
        ,INCOMEINSTRUC
        ,NUMBCONFIRMS
        ,NUMBSTATEMENTS
        ,INVESOBJTRANSCODE
        ,COMMENTS
        ,EMPLOYERSHORTNAME
        ,EMPLOYERCUSIP
        ,EMPLOYERSYMBOL
        ,MARPRIVREVOKED
        ,STATEREVIEWDATE
        ,MARPAPERSFILE
        ,OPTPAPERSFILE
        ,GOODFAITHMARGIN
        ,INVESTPRODISCRGRANTED
        ,INVESTADVDISCRGRANTED
        ,THIRDPARTYDISCGRANTED
        ,THIRDPARTYNAME
        ,RISKFACTORCODE
        ,INVESTOBJCODE
        ,OPTIONEQUITIES
        ,OPTIONINDEX
        ,OPTIONDEBT
        ,OPTIONCURRENCY
        ,OPTIONLEVEL1
        ,OPTIONLEVEL2
        ,OPTIONLEVEL3
        ,OPTIONLEVEL4
        ,OPTIONCALLLIMITS
        ,OPTIONPUTLIMITS
        ,OPTIONLIMITSPUTSCALLS
        ,NONUSDOLLARTRADING
        ,NONCUSTOMERINDICATOR
        ,THIRDPARTYFEEINDICATOR
        ,THIRDPARTYFEEAPPRDATE
        ,INTERMEDIARYACCTIND
        ,COMMISSIONSCHEDULE
        ,GROUPINDEX
        ,MONEYMANAGERID
        ,MONEYMANAGEROBJID
        ,DTCIDCONFIRMNUMBER
        ,CAPSMASTERMNEMONIC
        ,EMPLOYEEID
        ,PRIMEBROKERFREEFUNDIND
        ,FEEBASEDACCTIND
        ,BILLINGTYPE
        ,FEEBASEDTERMDATE
        ,PLANNAME
        ,SELFDIRECTED
        ,PLANTYPE
        ,PLANNUMBER
        ,EMPLOYEERELAIND
        ,COMMISSPERCDISC
        ,BLOCKMUTFUNDFEES
        ,NAMEINVESTPRO
        ,DATEINVESTPRO
        ,NAMEPRINCIPALSIGNED
        ,DATEPRINCIPALSIGNED
        ,POLITEXPOSEDPERSON
        ,PRIVATEBANKACCTIND
        ,FOREIGNBANKACCTIND
        ,INITIALSOURCEFUNDS
        ,USAPATACTEXEMPTREASON
        ,PRIMARYCOUNTRYCTZ
        ,COUNTRYRESIDENCE
        ,BIRTHDATE
        ,AGEBASEDFUNDROLLEXEMPTIND
        ,MONEYFUNDREFORMRETAIL
        ,TRUSTEDCONTACTSTATUS
        ,FULFILLMENTMETHOD
        ,CREDITINTERESTIND
        ,AMAIND
        ,DATEOFDATA
        ,CONVERT(INT, CONVERT(nvarchar(6), LOADED_AT, 112)) AS YEARMONTH
        ,LOADED_AT
    FROM
        {{ source("pershing", "PERS_ACCF") }}
),

bronze_data AS (
    SELECT
	    TRANSCODE
        ,RECORDIND
        ,RECORDSEQUENCEID
        ,ACCTNUMBER
        ,BROKERDEALERNUMBER
        ,INVESTMENTPRONUMBER
        ,ACCOUNTSHORTNAME
        ,TRANSACTIONTYPE
        ,AUTOTITLEDACCT
        ,ACCTTYPECODE
        ,REGISTRATIONTYPE
        ,NUMBERACCTTITLELINES
        ,ACCTREGISLINE1
        ,ACCTREGISLINE2
        ,ACCTREGISLINE3
        ,ACCTREGISLINE4
        ,ACCTREGISLINE5
        ,ACCTREGISLINE6
        ,USTENANCYINDICATOR
        ,MARRIEDINDICATOR
        ,TENANCYSTATE
        ,JOINTTENANCYCLAUSE
        ,AGREEMENTEXEDATE
        ,NUMBEROFTENANTS
        ,DATEACCTOPENED
        ,DATEACCTINFOUPDATED
        ,ACCTSTATUSINDICATOR
        ,PENDINGCLOSEDDATE
        ,DATEACCOUNTCLOSED
        ,ACCTREACTIVATEDDATE
        ,DATEACCOUNTREOPENED
        ,PROCEEDS
        ,TRANSINSTRUC
        ,INCOMEINSTRUC
        ,NUMBCONFIRMS
        ,NUMBSTATEMENTS
        ,INVESOBJTRANSCODE
        ,COMMENTS
        ,EMPLOYERSHORTNAME
        ,EMPLOYERCUSIP
        ,EMPLOYERSYMBOL
        ,MARPRIVREVOKED
        ,STATEREVIEWDATE
        ,MARPAPERSFILE
        ,OPTPAPERSFILE
        ,GOODFAITHMARGIN
        ,INVESTPRODISCRGRANTED
        ,INVESTADVDISCRGRANTED
        ,THIRDPARTYDISCGRANTED
        ,THIRDPARTYNAME
        ,RISKFACTORCODE
        ,INVESTOBJCODE
        ,OPTIONEQUITIES
        ,OPTIONINDEX
        ,OPTIONDEBT
        ,OPTIONCURRENCY
        ,OPTIONLEVEL1
        ,OPTIONLEVEL2
        ,OPTIONLEVEL3
        ,OPTIONLEVEL4
        ,OPTIONCALLLIMITS
        ,OPTIONPUTLIMITS
        ,OPTIONLIMITSPUTSCALLS
        ,NONUSDOLLARTRADING
        ,NONCUSTOMERINDICATOR
        ,THIRDPARTYFEEINDICATOR
        ,THIRDPARTYFEEAPPRDATE
        ,INTERMEDIARYACCTIND
        ,COMMISSIONSCHEDULE
        ,GROUPINDEX
        ,MONEYMANAGERID
        ,MONEYMANAGEROBJID
        ,DTCIDCONFIRMNUMBER
        ,CAPSMASTERMNEMONIC
        ,EMPLOYEEID
        ,PRIMEBROKERFREEFUNDIND
        ,FEEBASEDACCTIND
        ,BILLINGTYPE
        ,FEEBASEDTERMDATE
        ,PLANNAME
        ,SELFDIRECTED
        ,PLANTYPE
        ,PLANNUMBER
        ,EMPLOYEERELAIND
        ,COMMISSPERCDISC
        ,BLOCKMUTFUNDFEES
        ,NAMEINVESTPRO
        ,DATEINVESTPRO
        ,NAMEPRINCIPALSIGNED
        ,DATEPRINCIPALSIGNED
        ,POLITEXPOSEDPERSON
        ,PRIVATEBANKACCTIND
        ,FOREIGNBANKACCTIND
        ,INITIALSOURCEFUNDS
        ,USAPATACTEXEMPTREASON
        ,PRIMARYCOUNTRYCTZ
        ,COUNTRYRESIDENCE
        ,BIRTHDATE
        ,AGEBASEDFUNDROLLEXEMPTIND
        ,MONEYFUNDREFORMRETAIL
        ,TRUSTEDCONTACTSTATUS
        ,FULFILLMENTMETHOD
        ,CREDITINTERESTIND
        ,AMAIND
        ,DATEOFDATA
		,YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    {% if is_incremental() %}
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT * FROM bronze_data