-- NAME: BRONZE_PERSHING_ISRC_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: December 20, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
        TRANSACTION_CODE
        ,RECORD_SEQUENCE_IDENTIFIER
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,CHANGE_INDICATOR
        ,SOURCE_CODE
        ,SOURCE_CODE_DESCRIPTION_LINE_ONE
        ,SOURCE_CODE_DESCRIPTION_LINE_TWO
        ,SOURCE_CODE_DESCRIPTION_LINE_THREE
        ,TAX_STATUS
        ,USERID_OF_PERSON_WHO_LAST_ADDED_UPDATED_RECORD
        ,CASE
            WHEN DATE_ADDED = '00000000' THEN NULL
            WHEN DATE_ADDED IS NULL THEN NULL
            ELSE CONVERT(DATE, DATE_ADDED, 121)
        END AS DATE_ADDED
        ,CASE
            WHEN DATE_UPDATED = '00000000' THEN NULL
            WHEN DATE_UPDATED IS NULL THEN NULL
            ELSE CONVERT(DATE, DATE_UPDATED, 121)
        END AS DATE_UPDATED
        ,IRA_INCOME_ELEGIBLE
        ,RETAIL_INCOME_ELEGIBLE
        ,CUSTOMER_FIRM
        ,CREDIT_DEBIT
        ,STATEMENT_INDICATOR
        ,STATEMENT_ACTIVITY_SUMMARY_INDICATOR
        ,STATEMENT_ACTIVITY_SUMMARY_NUMBER
        ,STATEMENT_TRANSACTION_SUMMARY_INDICATOR
        ,STATEMENT_TRANSACTION_NUMBER
        ,STATEMENT_DISTRIBUTION_INDICATOR
        ,STATEMENT_DISTRIBUTION_NUMBER
        ,STATEMENT_DISTRIBUTION_TAXABLE_INDICATOR
        ,STATEMENT_DIVIDEND_INDICATOR
        ,STATEMENT_DIVIDEND_NUMBER
        ,STATEMENT_DIVIDEND_TAXABLE_INDICATOR
        ,PERSHING_DEPARTMENT
        ,PERSHING_GROUP_THAT_MANAGES_THE_SOURCE_CODE
        ,USERID_OF_PERSON_WHO_ADDED_CODE
        ,USERID_OF_PERSON_WHO_UPDATED_CODE
        ,PORTFOLIO_ELIGIBLE_INDICATOR
        ,REINVEST_INDICATOR
        ,DATE_OF_DATA
        ,YEARMONTH
        ,LOADED_AT
    FROM  {{ source("pershing", "PERSHING_ISRC_A") }}
),

bronze_data AS (
    SELECT
        TRANSACTION_CODE
        ,RECORD_SEQUENCE_IDENTIFIER
        ,RECORD_ID_SEQUENCE_NUMBER
        ,CHANGE_INDICATOR
        ,SOURCE_CODE
        ,SOURCE_CODE_DESCRIPTION_LINE_ONE
        ,SOURCE_CODE_DESCRIPTION_LINE_TWO
        ,SOURCE_CODE_DESCRIPTION_LINE_THREE
        ,TAX_STATUS
        ,USERID_OF_PERSON_WHO_LAST_ADDED_UPDATED_RECORD
        ,DATE_ADDED
        ,DATE_UPDATED
        ,IRA_INCOME_ELEGIBLE
        ,RETAIL_INCOME_ELEGIBLE
        ,CUSTOMER_FIRM
        ,CREDIT_DEBIT
        ,STATEMENT_INDICATOR
        ,STATEMENT_ACTIVITY_SUMMARY_INDICATOR
        ,STATEMENT_ACTIVITY_SUMMARY_NUMBER
        ,STATEMENT_TRANSACTION_SUMMARY_INDICATOR
        ,STATEMENT_TRANSACTION_NUMBER
        ,STATEMENT_DISTRIBUTION_INDICATOR
        ,STATEMENT_DISTRIBUTION_NUMBER
        ,STATEMENT_DISTRIBUTION_TAXABLE_INDICATOR
        ,STATEMENT_DIVIDEND_INDICATOR
        ,STATEMENT_DIVIDEND_NUMBER
        ,STATEMENT_DIVIDEND_TAXABLE_INDICATOR
        ,PERSHING_DEPARTMENT
        ,PERSHING_GROUP_THAT_MANAGES_THE_SOURCE_CODE
        ,USERID_OF_PERSON_WHO_ADDED_CODE
        ,USERID_OF_PERSON_WHO_UPDATED_CODE
        ,PORTFOLIO_ELIGIBLE_INDICATOR
        ,REINVEST_INDICATOR
        ,DATE_OF_DATA
        ,YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    {% if is_incremental() %}
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT * FROM bronze_data