-- NAME: BRONZE_PERSHING_GACT_REC_B
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: December 17, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT DISTINCT
        TRANSACTION_CODE
        ,RECORD_INDICATOR_VALUE
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,SECURITY_CURRENCY_OF_ISSUANCE
        ,TRADE_CURRENCY_CODE
        ,SETTLEMENT_CURRENCY_CODE
        ,CONVERT(DECIMAL(18,9), SETTLEMENT_USD_CURRENCY_FX_RATE) AS SETTLEMENT_USD_CURRENCY_FX_RATE
        ,SETTLEMENT_USD_MULTIPLY_DIVIDE_CODE
        ,CONVERT(DECIMAL(18,9), CROSS_CURRENCY_FX_RATE) AS CROSS_CURRENCY_FX_RATE
        ,CURRENCY_MULTIPLY_DIVIDE_CODE
        ,CONVERT(DECIMAL(18,2), ACCRUED_INTEREST_IN_SETTLEMENT_CURRENCY) AS ACCRUED_INTEREST_IN_SETTLEMENT_CURRENCY
        ,MARKET_CODE
        ,INTERNAL_REFERENCE_FOR_GLOSS
        ,INTRODUCING_BROKER_DEALER_IBD_VERSION
        ,CONVERT(DECIMAL(18,2), NET_AMOUNT_IN_SETTLEMENT_CURRENCY) AS NET_AMOUNT_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), PRINCIPAL_AMOUNT_IN_SETTLEMENT_CURRENCY) AS PRINCIPAL_AMOUNT_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), INTEREST_IN_SETTLEMENT_CURRENCY) AS INTEREST_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), COMISSION_IN_SETTLEMENT_CURRENCY) AS COMISSION_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), TAX_IN_SETTLEMENT_CURRENCY) AS TAX_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), TRANSACTION_FEE_IN_SETTLEMENT_CURRENCY) AS TRANSACTION_FEE_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), MISCELLANEOUS_FEE_IN_SETTLEMENT_CURRENCY) AS MISCELLANEOUS_FEE_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), OTHER_FEE_IN_SETTLEMENT_CURRENCY) AS OTHER_FEE_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), SALES_CREDIT_IN_SETTLEMENT_CURRENCY) AS SALES_CREDIT_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), SETTLEMENT_FEE_IN_SETTLEMENT_CURRENCY) AS SETTLEMENT_FEE_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), SERVICE_CHARGE_IN_SETTLEMENT_CURRENCY) AS SERVICE_CHARGE_IN_SETTLEMENT_CURRENCY
        ,CONVERT(DECIMAL(18,2), MARKUP_MARKDOWN_IN_SETTLEMENT_CURRENCY) AS MARKUP_MARKDOWN_IN_SETTLEMENT_CURRENCY
        ,GLOBAL_EXCHANGE
        ,CONVERT(INT, NUMBER_OF_DESCRIPTION_LINES) AS NUMBER_OF_DESCRIPTION_LINES
        ,CONVERT(INT, LAST_DESCRIPTION_LINE) AS LAST_DESCRIPTION_LINE
        ,DESCRIPTION_LINE_1
        ,DESCRIPTION_LINE_2
        ,DESCRIPTION_LINE_3
        ,DESCRIPTION_LINE_4
        ,DESCRIPTION_LINE_5
        ,DESCRIPTION_LINE_6
        ,DESCRIPTION_LINE_7
        ,DESCRIPTION_LINE_8
        ,DESCRIPTION_LINE_9
        ,DESCRIPTION_LINE_10
        ,DESCRIPTION_LINE_11
        ,DESCRIPTION_LINE_12
        ,SECURITY_CURRENCY_INDICATOR
        ,MARKET_MNEMONIC_CODE
        ,CONVERT(DECIMAL(18,9), CURRENCY_OF_ISSUANCE_USD_CURRENCY_FX_RATE) AS CURRENCY_OF_ISSUANCE_USD_CURRENCY_FX_RATE
        ,CURRENCY_OF_ISSUANCE_USD_MULTIPLY_DIVIDE_CODE
        ,ALTERNATE_SECURITY_ID_TYPE_1
        ,ALTERNATE_SECURITY_ID_1
        ,ALTERNATE_SECURITY_ID_TYPE_2
        ,ALTERNATE_SECURITY_ID_2
        ,INTERNATIONAL_NON_DOLLAR_SYMBOL
        ,CONFIRMATION_CODE_ONE
        ,CONFIRMATION_CODE_TWO
        ,CONFIRMATION_CODE_THREE
        ,CONFIRMATION_CODE_FOUR
        ,CONVERT(DECIMAL(18,9), PREVAILING_MARKET_PRICE_PMP) AS PREVAILING_MARKET_PRICE_PMP
        ,CONVERT(DECIMAL(18,2), TOTAL_AMOUNT_OF_MARK_UP_DOWN) AS TOTAL_AMOUNT_OF_MARK_UP_DOWN
        ,CONVERT(DECIMAL(9,5), PMP_PERCENT) AS PMP_PERCENT
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_GACT_B") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data