-- NAME: BRONZE_PERSHING_GCUS_REC_B
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
        TRANSACTION_CODE
        ,RECORD_INDICATOR_VALUE
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,CUSIP_NUMBER
        ,PORTFOLIO_CURRENCY
        ,UNDERLYING_CUSIP_NUMBER
        ,COUNTRY_CODE
        ,IP
        ,IBDNUMBER
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, FULLY_PAID_LENDING_QTY)) AS FULLY_PAID_LENDING_QTY
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, FULLY_PAID_LENDING_QTY_COLLAT_AMT)) AS FULLY_PAID_LENDING_QTY_COLLAT_AMT
        ,OPTION_ROOT_ID
        ,EXPIRATION_DATE
        ,CALL_PUT_INDICATOR
        ,CONVERT(DECIMAL(8, 3), CONVERT(FLOAT, STRIKE_PRICE_B)) AS STRIKE_PRICE_B
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRADE_DATE_REPO_QTY)) AS TRADE_DATE_REPO_QTY
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SETTLEMENT_DATE_REPO_QTY)) AS SETTLEMENT_DATE_REPO_QTY
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRADE_DATE_REVERSE_REPO_QTY)) AS TRADE_DATE_REVERSE_REPO_QTY
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SETTLEMENT_DATE_REVERSE_REPO_QTY)) AS SETTLEMENT_DATE_REVERSE_REPO_QTY
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, COLLAT_PLEDGE_QTY)) AS COLLAT_PLEDGE_QTY
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, CORP_EXEC_SERVICES_COLLAT_PLEDGE_QTY)) AS CORP_EXEC_SERVICES_COLLAT_PLEDGE_QTY
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, TRADE_DATE_REPO_LIQUIDATING_VALUE)) AS TRADE_DATE_REPO_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, SETTLEMENT_DATE_REPO_LIQUIDATING_VALUE)) AS SETTLEMENT_DATE_REPO_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, TRADE_DATE_REVERSE_REPO_LIQUIDATING_VALUE)) AS TRADE_DATE_REVERSE_REPO_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, SETTLEMENT_DATE_REVERSE_REPO_LIQUIDATING_VALUE)) AS SETTLEMENT_DATE_REVERSE_REPO_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, COLLAT_PLEDGE_LIQUIDATING_VALUE)) AS COLLAT_PLEDGE_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, CORP_EXEC_SERVICES_COLLAT_PLEDGE_LIQUIDATING_VALUE)) AS CORP_EXEC_SERVICES_COLLAT_PLEDGE_LIQUIDATING_VALUE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, TRADE_DATE_REPO_LOAN_AMOUNT)) AS TRADE_DATE_REPO_LOAN_AMOUNT
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, SETTLEMENT_DATE_REPO_LOAN_AMOUNT)) AS SETTLEMENT_DATE_REPO_LOAN_AMOUNT
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, TRADE_DATE_REVERSE_REPO_LOAN_AMOUNT)) AS TRADE_DATE_REVERSE_REPO_LOAN_AMOUNT
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, SETTLEMENT_DATE_REVERSE_REPO_LOAN_AMOUNT)) AS SETTLEMENT_DATE_REVERSE_REPO_LOAN_AMOUNT
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, ACCRUED_INTEREST_VALUE_FROM_LAST_PAYABLE)) AS ACCRUED_INTEREST_VALUE_FROM_LAST_PAYABLE
        ,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, DIVIDEND_or_COUPON_RATE)) AS DIVIDEND_or_COUPON_RATE
        ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, PENDING_SPLIT_QTY_LIQUIDATING_VALUE)) AS PENDING_SPLIT_QTY_LIQUIDATING_VALUE
        ,INTERNATIONAL_NON_DOLLAR_SYMBOL
        ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, PLEDGED_QTY_MEMO)) AS PLEDGED_QTY_MEMO
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
        ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_GCUS_B") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA > COALESCE((SELECT MAX(DATE_OF_DATA) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data