-- NAME: BRONZE_PERSHING_MFDS_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 12, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
    SELECT DISTINCT
        TRANSACTION_CODE
        ,RECORD_ID
        ,CONVERT(INT,RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,CUSIP_NUMBER
        ,FUND_FAMILY_CODE
        ,SECURITY_SYMBOL
        ,DIVIDEND_REINVEST_INDICATOR
        ,CAPITAL_GAIN_REINVEST_INDICATOR
        ,FUNDSERV_INDICATOR
        ,GRANDFATHER_INDICATOR
        ,LOAD_NO_LOAD_INDICATOR
        ,NETWORKING_INDICATOR
        ,NO_TRANSACTION_FEE_ELIGIBILITY_INDICATOR
        ,SHORT_SETTLEMENT_ELIGIBILITY_INDICATOR
        ,SYSTEMATIC_REINVESTMENT_SYSTEM_ELIGIBILITY_INDICATOR
        ,DIVIDEND_FREQUENCY
        ,CLOSED_TO_BUYS_INDICATOR
        ,CLOSED_TO_SELLS_INDICATOR
        ,NEW_INVESTMENT_CLOSED_INDICATOR
        ,SETTLE_PURCHASE_DAYS_NON_FUNDSERV
        ,SETTLE_REDEMPTION_DAYS_NON_FUNDSERV
        ,SETTLE_PURCHASE_DAYS_FUNDSERV
        ,SETTLE_REDEMPTION_DAYS_FUNDSERV
        ,CAST(STUFF(EXCHANGE_CUT_OFF_TIME, 3, 0, ':') AS TIME) AS EXCHANGE_CUT_OFF_TIME
        ,CAST(STUFF(PURCHASE_CUT_OFF_TIME, 3, 0, ':') AS TIME) AS PURCHASE_CUT_OFF_TIME
        ,CAST(STUFF(REDEMPTION_CUT_OFF_TIME, 3, 0, ':') AS TIME) AS REDEMPTION_CUT_OFF_TIME
        ,CONVERT(DECIMAL(20,8), LAST_PRICE) AS LAST_PRICE
        ,CASE
            WHEN LAST_PRICE_DATE = '00000000' THEN NULL
            WHEN LAST_PRICE_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, LAST_PRICE_DATE, 121)
        END AS LAST_PRICE_DATE
        ,FUND_FAMILY_NAME
        ,SHARE_CLASS
        ,MUTUAL_FUND_DESCRIPTION_LINE_1
        ,MUTUAL_FUND_DESCRIPTION_LINE_2
        ,MUTUAL_FUND_DESCRIPTION_LINE_3
        ,MUTUAL_FUND_DESCRIPTION_LINE_4
        ,MUTUAL_FUND_DESCRIPTION_LINE_5
        ,MUTUAL_FUND_DESCRIPTION_LINE_6
        ,EXCHANGE_ELIGIBLE_INDICATOR
        ,TRADE_STATUS
        ,CUSTOMER_COMMENTS
        ,OFFSHORE_INDICATOR
        ,OFFSHORE_PROCESSING_INDICATOR
        ,DEALER_AGREEMENT_REQUIRED_FOR_LOAD_TRADES
        ,DEALER_AGREEMENT_REQUIRED_FOR_NO_LOAD_TRADES
        ,DEALER_AGREEMENT_REQUIRED_FOR_LOAD_TRANSFERS
        ,DEALER_AGREEMENT_REQUIRED_FOR_NO_LOAD_TRANFERS
        ,AS_OF_INDICATOR
        ,CONVERT(INT, AS_OF_DAYS) AS AS_OF_DAYS
        ,POST_SETTLE_CANCEL_INDICATOR
        ,CONVERT(INT, POST_SETTLE_CANCEL_DAYS) AS POST_SETTLE_CANCEL_DAYS
        ,CONVERT(DECIMAL(14,2), POST_SETTLE_MAXIMUM_DOLLAR_AMOUNT) AS POST_SETTLE_MAXIMUM_DOLLAR_AMOUNT
        ,CONVERT(DECIMAL(20,2), MINIMUM_INITIAL_PURCHASE_AMOUNT) AS MINIMUM_INITIAL_PURCHASE_AMOUNT
        ,CONVERT(DECIMAL(20,2), MINIMUM_SUBSEQUENCE_PURCHASE_AMOUNT) AS MINIMUM_SUBSEQUENCE_PURCHASE_AMOUNT
        ,CONVERT(DECIMAL(20,2), MAXIMUM_INITIAL_PURCHASE_AMOUNT) AS MAXIMUM_INITIAL_PURCHASE_AMOUNT
        ,CONVERT(DECIMAL(20,2), MAXIMUM_SUBSEQUENCE_PURCHASE_AMOUNT) AS MAXIMUM_SUBSEQUENCE_PURCHASE_AMOUNT
        ,OMNIBUS_INDICATOR
        ,TENDER_INDICATOR
        ,FUNDVEST_200_ELIGIBLE
        ,SURCHARGE
        ,CURRENCY
        ,RETIREMENT_PLAN_NETWORK_RPN_ELIGIBLE_INDICATOR
        ,TRADING_RESTRICTED_BY_BOOKING_ENTITIES
        ,BNY_MELLON_BNYM
        ,PERSHING_LLC_PLLC
        ,PERSHING_AUSTRALIA_PSAL
        ,PERSHING_CANADA_PSCL
        ,PERSHING_LONDON_PSLL
        ,FUND_SHARE_CLASS
        ,_12B_1_INDICATOR
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_MFDS_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data