-- NAME: BRONZE_PERSHING_GTDE_REC_B
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: July 15, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
	    TRANSACTION_CODE
	    ,RECORD_INDICATOR_VALUE
	    ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
	    ,ACCOUNT_NUMBER
	    ,IBD_NUMBER
        ,CASE
            WHEN RTRIM(LTRIM(QUANTITY)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,5), QUANTITY)
        END AS QUANTITY
        ,CASE
            WHEN RTRIM(LTRIM(PRICE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,9), PRICE)
        END AS PRICE
        ,TRADE_CURRENCY
        ,BASIS_PRICE_INDICATOR
        ,CASE
            WHEN RTRIM(LTRIM(YIELD)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(18,9), YIELD)
        END AS YIELD
        ,CASE
            WHEN RTRIM(LTRIM(YIELD_TO_WORST)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(18,9), YIELD_TO_WORST)
        END AS YIELD_TO_WORST
        ,YIELD_TO_WORST_CODE
        ,CASE
            WHEN RTRIM(LTRIM(PERSHING_CHARGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), PERSHING_CHARGE)
        END AS PERSHING_CHARGE
        ,CASE
            WHEN RTRIM(LTRIM(TRANSACTION_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), TRANSACTION_FEE)
        END AS TRANSACTION_FEE
        ,CASE
            WHEN RTRIM(LTRIM(REBATE_AMOUNT)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), REBATE_AMOUNT)
        END AS REBATE_AMOUNT
        ,CASE
            WHEN RTRIM(LTRIM(NET_AMOUNT)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), NET_AMOUNT)
        END AS NET_AMOUNT
        ,SETTLEMENT_CURRENCY
        ,CASE
            WHEN RTRIM(LTRIM(SETTLEMENT_CURRENCY_EXCHANGE_RATE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,9), SETTLEMENT_CURRENCY_EXCHANGE_RATE)
        END AS SETTLEMENT_CURRENCY_EXCHANGE_RATE
        ,SETTLEMENT_CURRENCY_MULTIPLY_DIVIDE_CODE
        ,CASE
            WHEN RTRIM(LTRIM(ACCRUED_INTEREST)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), ACCRUED_INTEREST)
        END AS ACCRUED_INTEREST
        ,CASE
            WHEN RTRIM(LTRIM(SERVICE_CHARGE_FOR_IBD)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), SERVICE_CHARGE_FOR_IBD)
        END AS SERVICE_CHARGE_FOR_IBD
        ,CASE
            WHEN RTRIM(LTRIM(POSTAGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), POSTAGE)
        END AS POSTAGE
        ,COMMISSION_SALES_CREDIT_TYPE
        ,CASE
            WHEN RTRIM(LTRIM(COMMISSION)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), COMMISSION)
        END AS COMMISSION
        ,CASE
            WHEN RTRIM(LTRIM(COMMISSION_PERCENT_DISCOUNT)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(8,4), COMMISSION_PERCENT_DISCOUNT)
        END AS COMMISSION_PERCENT_DISCOUNT
        ,CASE
            WHEN RTRIM(LTRIM(SALES_CREDIT)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), SALES_CREDIT)
        END AS SALES_CREDIT
        ,CASE
            WHEN RTRIM(LTRIM(CDSC)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), CDSC)
        END AS CDSC
        ,CASE
            WHEN RTRIM(LTRIM(BASE_COMMISSION)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), BASE_COMMISSION)
        END AS BASE_COMMISSION
        ,CASE
            WHEN RTRIM(LTRIM(EQUITY_MARK_UP_MARK_DOWN)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), EQUITY_MARK_UP_MARK_DOWN)
        END AS EQUITY_MARK_UP_MARK_DOWN
        ,CASE
            WHEN RTRIM(LTRIM(PRINCIPAL)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), PRINCIPAL)
        END AS PRINCIPAL
        ,CASE
            WHEN RTRIM(LTRIM(EXECUTION_CHARGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), EXECUTION_CHARGE)
        END AS EXECUTION_CHARGE
        ,EXECUTION_ONLY_INDICATOR
        ,CASE
            WHEN RTRIM(LTRIM(SETTLEMENT_FEE_CUSTOMER)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), SETTLEMENT_FEE_CUSTOMER)
        END AS SETTLEMENT_FEE_CUSTOMER
        ,CLEARANCE_ONLY_INDICATOR
        ,CASE
            WHEN RTRIM(LTRIM(FGN_RECEIVE_DELIVER_CHARGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), FGN_RECEIVE_DELIVER_CHARGE)
        END AS FGN_RECEIVE_DELIVER_CHARGE
        ,CASE
            WHEN RTRIM(LTRIM(NTF_REDEMPTION_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), NTF_REDEMPTION_FEE)
        END AS NTF_REDEMPTION_FEE
        ,CASE
            WHEN RTRIM(LTRIM(NTF_REDEMPTION_ADD_ON_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), NTF_REDEMPTION_ADD_ON_FEE)
        END AS NTF_REDEMPTION_ADD_ON_FEE
        ,CASE
            WHEN RTRIM(LTRIM(MUTUAL_FUND_EXCHANGE_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), MUTUAL_FUND_EXCHANGE_FEE)
        END AS MUTUAL_FUND_EXCHANGE_FEE
        ,CASE
            WHEN RTRIM(LTRIM(SRS_FUND_EXCHANGE_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), SRS_FUND_EXCHANGE_FEE)
        END AS SRS_FUND_EXCHANGE_FEE
        ,CASE
            WHEN RTRIM(LTRIM(HANDLING_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), HANDLING_FEE)
        END AS HANDLING_FEE
        ,CASE
            WHEN RTRIM(LTRIM(STAMP_DUTY)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), STAMP_DUTY)
        END AS STAMP_DUTY
        ,CASE
            WHEN RTRIM(LTRIM(PRIME_BROKER_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), PRIME_BROKER_FEE)
        END AS PRIME_BROKER_FEE
        ,IBD_MISCELLANEOUS_CHARGE_LABEL
        ,CASE
            WHEN RTRIM(LTRIM(IBD_MISCELLANEOUS_CHARGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), IBD_MISCELLANEOUS_CHARGE)
        END AS IBD_MISCELLANEOUS_CHARGE
        ,STREETSIDE_MISCELLANEOUS_CHARGE_LABEL
        ,CASE
            WHEN RTRIM(LTRIM(STREETSIDE_MISCELLANEOUS_CHARGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), STREETSIDE_MISCELLANEOUS_CHARGE)
        END AS STREETSIDE_MISCELLANEOUS_CHARGE
        ,CASE
            WHEN RTRIM(LTRIM(TRANSACTION_LEVY)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), TRANSACTION_LEVY)
        END AS TRANSACTION_LEVY
        ,CASE
            WHEN RTRIM(LTRIM(TRANSFER_STAMP_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), TRANSFER_STAMP_FEE)
        END AS TRANSFER_STAMP_FEE
        ,CASE
            WHEN RTRIM(LTRIM(TRANSFER_TAX)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), TRANSFER_TAX)
        END AS TRANSFER_TAX
        ,CASE
            WHEN RTRIM(LTRIM(CUSTOMER_CONFIRM_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), CUSTOMER_CONFIRM_FEE)
        END AS CUSTOMER_CONFIRM_FEE
        ,CASE
            WHEN RTRIM(LTRIM(IBD_CONFIRM_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), IBD_CONFIRM_FEE)
        END AS IBD_CONFIRM_FEE
        ,CASE
            WHEN RTRIM(LTRIM(FOREIGN_FIN_TRANSACTION_TAX)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), FOREIGN_FIN_TRANSACTION_TAX)
        END AS FOREIGN_FIN_TRANSACTION_TAX
        ,CASE
            WHEN RTRIM(LTRIM(REPORTED_PRICE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,9), REPORTED_PRICE)
        END AS REPORTED_PRICE
        ,ADDITIONAL_TRAILER_LINE_ONE
        ,ADDITIONAL_TRAILER_LINE_TWO
        ,ADDITIONAL_TRAILER_LINE_THREE
        ,ADDITIONAL_TRAILER_LINE_FOUR
        ,ADDITIONAL_TRAILER_LINE_FIVE
        ,ADDITIONAL_TRAILER_LINE_SIX
        ,FREEFORM_LOT_INFORMATION_1
        ,FREEFORM_LOT_INFORMATION_2
        ,FREEFORM_LOT_INFORMATION_3
        ,CASE
            WHEN RTRIM(LTRIM(SEC)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), SEC)
        END AS SEC
        ,CASE
            WHEN RTRIM(LTRIM(OPTION_REGULATORY_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), OPTION_REGULATORY_FEE)
        END AS OPTION_REGULATORY_FEE
        ,ALTERNATE_SECURITY_ID_1_TYPE
        ,ALTERNATE_SECURITY_ID_1
        ,ALTERNATE_SECURITY_ID_2_TYPE
        ,ALTERNATE_SECURITY_ID_2
        ,CASE
            WHEN RTRIM(LTRIM(NET_AMOUNT_IN_USDE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), NET_AMOUNT_IN_USDE)
        END AS NET_AMOUNT_IN_USDE
        ,CASE
            WHEN RTRIM(LTRIM(INTERNATIONAL_FOREIGN_TRADING_FEE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(19,2), INTERNATIONAL_FOREIGN_TRADING_FEE)
        END AS INTERNATIONAL_FOREIGN_TRADING_FEE
        ,ATS_INDICATOR
        ,ATS_MPID
        ,CONVERT(INT, PERSHING_INTERNAL_VERSION_NUMBER) AS PERSHING_INTERNAL_VERSION_NUMBER
        ,PERSHING_INTERNAL_TRADE_REFERENCE_NUMBER
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
    	,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
    	,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
	    ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
	    ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_GTDE_B") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data