-- NAME: BRONZE_PERSHING_CAPT_REC_4
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 11, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
	SELECT DISTINCT
		INTRODUCING_BROKER_DEALER_IBD_NUMBER
		,RECORD_ID
		,CURRENCY_CODE
		,CASE
			WHEN RIGHT(CURRENCY_AMOUNT_OF_REVENUE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CURRENCY_AMOUNT_OF_REVENUE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(CURRENCY_AMOUNT_OF_REVENUE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CURRENCY_AMOUNT_OF_REVENUE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(20,3), CURRENCY_AMOUNT_OF_REVENUE)
		 END CURRENCY_AMOUNT_OF_REVENUE
		,CASE
			WHEN RIGHT(FOREIGN_EXCHANGE_RATE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(20,10),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FOREIGN_EXCHANGE_RATE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(FOREIGN_EXCHANGE_RATE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(20,10),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FOREIGN_EXCHANGE_RATE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(20,10), FOREIGN_EXCHANGE_RATE)
		 END FOREIGN_EXCHANGE_RATE
		,CURRENCY_MULTI_DIV_INDICATOR
		,CASE
			WHEN RIGHT(IBD_SETTLEMENT_FEE_USD,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(IBD_SETTLEMENT_FEE_USD,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(IBD_SETTLEMENT_FEE_USD,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(IBD_SETTLEMENT_FEE_USD,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(20,3), IBD_SETTLEMENT_FEE_USD)
		 END IBD_SETTLEMENT_FEE_USD
		,CASE
			WHEN RIGHT(CUSTOMER_SETTLEMENT_FEE_USD,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CUSTOMER_SETTLEMENT_FEE_USD,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(CUSTOMER_SETTLEMENT_FEE_USD,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(20,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CUSTOMER_SETTLEMENT_FEE_USD,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(20,3), CUSTOMER_SETTLEMENT_FEE_USD)
		 END CUSTOMER_SETTLEMENT_FEE_USD
		,GLOSS_REFERENCE_NUMBER
		,CASE
			WHEN RIGHT(CURRENCY_AMOUNT_OF_PERSHING_CHARGE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CURRENCY_AMOUNT_OF_PERSHING_CHARGE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(CURRENCY_AMOUNT_OF_PERSHING_CHARGE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CURRENCY_AMOUNT_OF_PERSHING_CHARGE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(14,2), CURRENCY_AMOUNT_OF_PERSHING_CHARGE)
		 END CURRENCY_AMOUNT_OF_PERSHING_CHARGE
		,RECORD_ID_SEQUENCE_NUMBER
		,DATE_OF_DATA
		,YEARMONTH
	FROM {{ source("pershing", "PERSHING_CAPT_4") }}
	{% if is_incremental() %}
		WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data