-- NAME: BRONZE_JH_DDAAMS
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: MONTHLY - 4TH BUSINESS DAY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



with landing_data as (
    SELECT
        AABR
        ,ACCTNO
        ,ACTYPE
        ,AGRPCD
        ,AASNAM
        ,AATYPE
        ,ACYCLE
        ,ACFREQ
        ,ACFRCD
        ,AOFFCR
        ,ADTLA6
        ,ADTLA7
        ,ADTNA6
        ,ADTNA7
        ,ALOSS
        ,ACGACT
        ,AGROUP
        ,AANAPLAN
        ,AASTATUS
        ,AFORM
        ,AREPT
        ,ACOVR
        ,ACOMP
        ,AAUSER
        ,AAGGDY
        ,AAGGAM
        ,AAGGCO
        ,AAGDYH
        ,AAGAMH
        ,AAGCOH
        ,ANODR
        ,ANOCR
        ,AONUS
        ,ATRNS1
        ,ATRNS2
        ,ATRNS3
        ,ATRNS4
        ,ATRNS5
        ,ASERCG
        ,AINTPD
        ,AODINT
        ,ASTOPS
        ,ASTMTR
        ,ASTMTS
        ,ASTMTT
        ,AINQ
        ,AABILN
        ,AADUED
        ,AAGGCOPOS
        ,AAGGCONEG
        ,AAGGDYPOS
        ,AAGGDYNEG
        ,AAGDYHPOS
        ,AAGDYHNEG
        ,AAGCOHPOS
        ,AAGCOHNEG
        ,P2AERATVAR
        ,P2AERATVCD
        ,P2AERATFLR
        ,P2AERATCEI
        ,P2ANRATVAR
        ,P2ANRATVCD
        ,P2ANRATFLR
        ,P2ANRATCEI
        ,ASTMTOPT
        ,ASTMTNT
        ,ASTMTPRFT
        ,ASTMTLOSS
        ,AACLSDT6
        ,AACLSDT7
        ,AACLSCHG
        ,AAWVEXPDT6
        ,AAWVEXPDT7
        ,AAPRCYEND
        ,AAPINTEXE
        ,AAEXETBL1
        ,AAEXETRT1
        ,AAEXETBL2
        ,AAEXETRT2
        ,AAEXETBL3
        ,AAEXETRT3
        ,AAEXETBL4
        ,AAEXETRT4
        ,AAEXETBL5
        ,AAEXETRT5
        ,AATSU3A1
        ,AATSU3A2
        ,AATSU3A3
        ,AATSU3A4
        ,AATSU3A5
        ,AATSUDT1
        ,AATSUDT2
        ,AATSUDT3
        ,AATSUDT4
        ,AATSUDT5
        ,AATSUAMT1
        ,AATSUAMT2
        ,AATSUAMT3
        ,AATSUAMT4
        ,AATSUAMT5
        ,AADSCAMT
        ,AADSCPRC
        ,AADSCEXP
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
            FROM dqp_landing.dbo.jh_ddpar1) AS AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6), DATEADD("m", -1, LOADED_AT), 112)) AS YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_DDAAMS"
),

bronze_data AS (
    SELECT
        CAST(NULLIF(AABR, '') AS INTEGER) AS AABR
        ,CAST(NULLIF(ACCTNO, '') AS BIGINT) AS ACCTNO
        ,CAST(NULLIF(ACTYPE, '') AS VARCHAR(1)) AS ACTYPE
        ,CAST(NULLIF(AGRPCD, '') AS VARCHAR(1)) AS AGRPCD
        ,CAST(NULLIF(AASNAM, '') AS VARCHAR(20)) AS AASNAM
        ,CAST(NULLIF(AATYPE, '') AS VARCHAR(2)) AS AATYPE
        ,CAST(NULLIF(ACYCLE, '') AS INTEGER) AS ACYCLE
        ,CAST(NULLIF(ACFREQ, '') AS INTEGER) AS ACFREQ
        ,CAST(NULLIF(ACFRCD, '') AS VARCHAR(1)) AS ACFRCD
        ,CAST(NULLIF(AOFFCR, '') AS VARCHAR(6)) AS AOFFCR
        ,CAST(NULLIF(ADTLA6, '') AS INTEGER) AS ADTLA6
        ,CAST(NULLIF(ADTLA7, '') AS INTEGER) AS ADTLA7
        ,CAST(NULLIF(ADTNA6, '') AS INTEGER) AS ADTNA6
        ,CAST(NULLIF(ADTNA7, '') AS INTEGER) AS ADTNA7
        ,CAST(NULLIF(ALOSS, '') AS VARCHAR(1)) AS ALOSS
        ,CAST(NULLIF(ACGACT, '') AS BIGINT) AS ACGACT
        ,CAST(NULLIF(AGROUP, '') AS BIGINT) AS AGROUP
        ,CAST(NULLIF(AANAPLAN, '') AS INTEGER) AS AANAPLAN
        ,CAST(NULLIF(AASTATUS, '') AS INTEGER) AS AASTATUS
        ,CAST(NULLIF(AFORM, '') AS VARCHAR(1)) AS AFORM
        ,CAST(NULLIF(AREPT, '') AS VARCHAR(1)) AS AREPT
        ,CAST(NULLIF(ACOVR, '') AS INTEGER) AS ACOVR
        ,CAST(NULLIF(ACOMP, '') AS NUMERIC(11,2)) AS ACOMP
        ,CAST(NULLIF(AAUSER, '') AS VARCHAR(3)) AS AAUSER
        ,CAST(NULLIF(AAGGDY, '') AS INTEGER) AS AAGGDY
        ,CAST(NULLIF(AAGGAM, '') AS NUMERIC(15,2)) AS AAGGAM
        ,CAST(NULLIF(AAGGCO, '') AS NUMERIC(15,2)) AS AAGGCO
        ,CAST(NULLIF(AAGDYH, '') AS INTEGER) AS AAGDYH
        ,CAST(NULLIF(AAGAMH, '') AS NUMERIC(15,2)) AS AAGAMH
        ,CAST(NULLIF(AAGCOH, '') AS NUMERIC(15,2)) AS AAGCOH
        ,CAST(NULLIF(ANODR, '') AS INTEGER) AS ANODR
        ,CAST(NULLIF(ANOCR, '') AS INTEGER) AS ANOCR
        ,CAST(NULLIF(AONUS, '') AS INTEGER) AS AONUS
        ,CAST(NULLIF(ATRNS1, '') AS INTEGER) AS ATRNS1
        ,CAST(NULLIF(ATRNS2, '') AS INTEGER) AS ATRNS2
        ,CAST(NULLIF(ATRNS3, '') AS INTEGER) AS ATRNS3
        ,CAST(NULLIF(ATRNS4, '') AS INTEGER) AS ATRNS4
        ,CAST(NULLIF(ATRNS5, '') AS INTEGER) AS ATRNS5
        ,CAST(NULLIF(ASERCG, '') AS NUMERIC(9,2)) AS ASERCG
        ,CAST(NULLIF(AINTPD, '') AS NUMERIC(13,2)) AS AINTPD
        ,CAST(NULLIF(AODINT, '') AS NUMERIC(13,5)) AS AODINT
        ,CAST(NULLIF(ASTOPS, '') AS INTEGER) AS ASTOPS
        ,CAST(NULLIF(ASTMTR, '') AS INTEGER) AS ASTMTR
        ,CAST(NULLIF(ASTMTS, '') AS INTEGER) AS ASTMTS
        ,CAST(NULLIF(ASTMTT, '') AS INTEGER) AS ASTMTT
        ,CAST(NULLIF(AINQ, '') AS INTEGER) AS AINQ
        ,CAST(NULLIF(AABILN, '') AS VARCHAR(1)) AS AABILN
        ,CAST(NULLIF(AADUED, '') AS INTEGER) AS AADUED
        ,CAST(NULLIF(AAGGCOPOS, '') AS NUMERIC(15,2)) AS AAGGCOPOS
        ,CAST(NULLIF(AAGGCONEG, '') AS NUMERIC(15,2)) AS AAGGCONEG
        ,CAST(NULLIF(AAGGDYPOS, '') AS INTEGER) AS AAGGDYPOS
        ,CAST(NULLIF(AAGGDYNEG, '') AS INTEGER) AS AAGGDYNEG
        ,CAST(NULLIF(AAGDYHPOS, '') AS INTEGER) AS AAGDYHPOS
        ,CAST(NULLIF(AAGDYHNEG, '') AS INTEGER) AS AAGDYHNEG
        ,CAST(NULLIF(AAGCOHPOS, '') AS NUMERIC(15,2)) AS AAGCOHPOS
        ,CAST(NULLIF(AAGCOHNEG, '') AS NUMERIC(15,2)) AS AAGCOHNEG
        ,CAST(CAST(NULLIF(P2AERATVAR, '') AS REAL) AS NUMERIC(9,8)) AS P2AERATVAR
        ,CAST(NULLIF(P2AERATVCD, '') AS VARCHAR(1)) AS P2AERATVCD
        ,CAST(CAST(NULLIF(P2AERATFLR, '') AS REAL) AS NUMERIC(9,8)) AS P2AERATFLR
        ,CAST(CAST(NULLIF(P2AERATCEI, '') AS REAL) AS NUMERIC(9,8)) AS P2AERATCEI
        ,CAST(CAST(NULLIF(P2ANRATVAR, '') AS REAL) AS NUMERIC(9,8)) AS P2ANRATVAR
        ,CAST(NULLIF(P2ANRATVCD, '') AS VARCHAR(1)) AS P2ANRATVCD
        ,CAST(CAST(NULLIF(P2ANRATFLR, '') AS REAL) AS NUMERIC(9,8)) AS P2ANRATFLR
        ,CAST(CAST(NULLIF(P2ANRATCEI, '') AS REAL) AS NUMERIC(9,8)) AS P2ANRATCEI
        ,CAST(NULLIF(ASTMTOPT, '') AS VARCHAR(1)) AS ASTMTOPT
        ,CAST(NULLIF(ASTMTNT, '') AS VARCHAR(1)) AS ASTMTNT
        ,CAST(NULLIF(ASTMTPRFT, '') AS VARCHAR(1)) AS ASTMTPRFT
        ,CAST(NULLIF(ASTMTLOSS, '') AS VARCHAR(1)) AS ASTMTLOSS
        ,CAST(NULLIF(AACLSDT6, '') AS INTEGER) AS AACLSDT6
        ,CAST(NULLIF(AACLSDT7, '') AS INTEGER) AS AACLSDT7
        ,CAST(NULLIF(AACLSCHG, '') AS VARCHAR(1)) AS AACLSCHG
        ,CAST(NULLIF(AAWVEXPDT6, '') AS INTEGER) AS AAWVEXPDT6
        ,CAST(NULLIF(AAWVEXPDT7, '') AS INTEGER) AS AAWVEXPDT7
        ,CAST(NULLIF(AAPRCYEND, '') AS VARCHAR(1)) AS AAPRCYEND
        ,CAST(NULLIF(AAPINTEXE, '') AS VARCHAR(1)) AS AAPINTEXE
        ,CAST(NULLIF(AAEXETBL1, '') AS NUMERIC(13,2)) AS AAEXETBL1
        ,CAST(NULLIF(AAEXETRT1, '') AS INTEGER) AS AAEXETRT1
        ,CAST(NULLIF(AAEXETBL2, '') AS NUMERIC(13,2)) AS AAEXETBL2
        ,CAST(NULLIF(AAEXETRT2, '') AS INTEGER) AS AAEXETRT2
        ,CAST(NULLIF(AAEXETBL3, '') AS NUMERIC(13,2)) AS AAEXETBL3
        ,CAST(NULLIF(AAEXETRT3, '') AS INTEGER) AS AAEXETRT3
        ,CAST(NULLIF(AAEXETBL4, '') AS NUMERIC(13,2)) AS AAEXETBL4
        ,CAST(NULLIF(AAEXETRT4, '') AS INTEGER) AS AAEXETRT4
        ,CAST(NULLIF(AAEXETBL5, '') AS NUMERIC(13,2)) AS AAEXETBL5
        ,CAST(NULLIF(AAEXETRT5, '') AS INTEGER) AS AAEXETRT5
        ,CAST(NULLIF(AATSU3A1, '') AS VARCHAR(3)) AS AATSU3A1
        ,CAST(NULLIF(AATSU3A2, '') AS VARCHAR(3)) AS AATSU3A2
        ,CAST(NULLIF(AATSU3A3, '') AS VARCHAR(3)) AS AATSU3A3
        ,CAST(NULLIF(AATSU3A4, '') AS VARCHAR(3)) AS AATSU3A4
        ,CAST(NULLIF(AATSU3A5, '') AS VARCHAR(3)) AS AATSU3A5
        ,CAST(NULLIF(AATSUDT1, '') AS VARCHAR(10)) AS AATSUDT1
        ,CAST(NULLIF(AATSUDT2, '') AS VARCHAR(10)) AS AATSUDT2
        ,CAST(NULLIF(AATSUDT3, '') AS VARCHAR(10)) AS AATSUDT3
        ,CAST(NULLIF(AATSUDT4, '') AS VARCHAR(10)) AS AATSUDT4
        ,CAST(NULLIF(AATSUDT5, '') AS VARCHAR(10)) AS AATSUDT5
        ,CAST(NULLIF(AATSUAMT1, '') AS NUMERIC(13,2)) AS AATSUAMT1
        ,CAST(NULLIF(AATSUAMT2, '') AS NUMERIC(13,2)) AS AATSUAMT2
        ,CAST(NULLIF(AATSUAMT3, '') AS NUMERIC(13,2)) AS AATSUAMT3
        ,CAST(NULLIF(AATSUAMT4, '') AS NUMERIC(13,2)) AS AATSUAMT4
        ,CAST(NULLIF(AATSUAMT5, '') AS NUMERIC(13,2)) AS AATSUAMT5
        ,CAST(NULLIF(AADSCAMT, '') AS NUMERIC(7,2)) AS AADSCAMT
        ,CAST(CAST(NULLIF(AADSCPRC, '') AS REAL) AS NUMERIC(9,8)) AS AADSCPRC
        ,CAST(NULLIF(AADSCEXP, '') AS VARCHAR(10)) AS AADSCEXP
        ,AsOfDate
        ,YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM "DQP_BRONZE"."dbo"."bronze_jh_ddaams"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data