-- NAME: BRONZE_JH_BFWTMAST
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



with landing_data as (
    SELECT
        WTTIMESTA
        ,WTXFRTYPE
        ,WTOMADREF
        ,WTBANK
        ,WTBATCH
        ,WTRTIME
        ,WTRDATE
        ,WTRDATJ
        ,WTOUREF
        ,WTBYORO
        ,WTBENEF
        ,WTDBANK
        ,WTDBRAN
        ,WTDGLNM
        ,WTDCOST
        ,WTDPROD
        ,WTDACCT
        ,WTDAMNT
        ,WTCBANK
        ,WTCBRAN
        ,WTCGLNM
        ,WTCCOST
        ,WTCPROD
        ,WTCACCT
        ,WTCAMNT
        ,WTDFBNK
        ,WTDFBRA
        ,WTDFGLN
        ,WTDFCOS
        ,WTDFPRO
        ,WTDFACC
        ,WTDFAMT
        ,WTCFBNK
        ,WTCFBRA
        ,WTCFGLN
        ,WTCFCOS
        ,WTCFPRO
        ,WTCFACC
        ,WTCFAMT
        ,WTDSCR1
        ,WTDSCR2
        ,WTDSCR3
        ,WTBYUSER
        ,WTRELBY
        ,WTCODE
        ,WTFMTVR
        ,WTTPRFL
        ,WTMESSD
        ,WTMESSS
        ,WTSTDMD
        ,WTSTTHM
        ,WTFEDAP
        ,WTACYMD
        ,WTOPDID
        ,WTOUTSE
        ,WTOUTMD
        ,WTOUTTM
        ,WTOUTAI
        ,WTERRCY
        ,WTERRCD
        ,WTERRDS
        ,WTOUFTV
        ,WTUSRRC
        ,WTOUTEN
        ,WTMESDU
        ,WTFEDFU
        ,WTFEDTT
        ,WTTRSBT
        ,WTPRDAT
        ,WTTERID
        ,WTINPSE
        ,WTAMOUN
        ,WTADYMD
        ,WTADJRE
        ,WTSABAN
        ,WTSENNA
        ,WTSEREF
        ,WTRABAA
        ,WTRENAM
        ,WTPDATE
        ,WTTERMI
        ,WTINPUS
        ,WTPRCOD
        ,WTCHGTY
        ,WTCURRE
        ,WTSNCHG
        ,WTCHAG2
        ,WTSCHG2
        ,WTCHAG3
        ,WTSCHG3
        ,WTCHAG4
        ,WTSCHG4
        ,WTINTCU
        ,WTINTAM
        ,WTEXRAT
        ,WTINCOD
        ,WTINFIC
        ,WTINFNA
        ,WTIFAD1
        ,WTIFAD2
        ,WTIFAD3
        ,WTBENFC
        ,WTBEFIC
        ,WTBEFNM
        ,WTBFAD1
        ,WTBFAD2
        ,WTBFAD3
        ,WTBENCD
        ,WTBENID
        ,WTBENNM
        ,WTBEAD1
        ,WTBEAD2
        ,WTBEAD3
        ,WTBENRE
        ,WTDRTYP
        ,WTDRAID
        ,WTDRAFI
        ,WTDRAD1
        ,WTDRAD2
        ,WTDRAD3
        ,WTORGTY
        ,WTORGID
        ,WTORGOI
        ,WTORAD1
        ,WTORAD2
        ,WTORAD3
        ,WTORGFT
        ,WTORGFI
        ,WTORGNM
        ,WTORGA1
        ,WTORGA2
        ,WTORGA3
        ,WTINTYP
        ,WTINIID
        ,WTININM
        ,WTINAD1
        ,WTINAD2
        ,WTINAD3
        ,WTCRABA
        ,WTORGB1
        ,WTORGB2
        ,WTORGB3
        ,WTORGB4
        ,WTRFIIN
        ,WTRFIAD
        ,WTDRACD
        ,WTDDRAI
        ,WTDDAIA
        ,WTIFIL1
        ,WTIFIAL
        ,WTINFCD
        ,WTINAL1
        ,WTINAL2
        ,WTBFIL1
        ,WTBFIAL
        ,WTBENPA
        ,WTBPAL1
        ,WTBPAL2
        ,WTBEIL1
        ,WTBEIAL
        ,WTPABNC
        ,WTPABN1
        ,WTPABN2
        ,WTBMPAY
        ,WTBMPL1
        ,WTPAYLM
        ,WTREIL1
        ,WTREIL2
        ,WTREIL3
        ,WTREIL4
        ,WTREIL5
        ,WTFRE01
        ,WTFRE02
        ,WTFRE03
        ,WTFRE04
        ,WTFRE05
        ,WTFRE06
        ,WTFRE07
        ,WTFRE08
        ,WTFRE09
        ,WTFRE10
        ,WTFRE11
        ,WTRANDJUL
        ,WTRANDATE
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
            FROM dqp_landing.dbo.jh_ddpar1) AS AsOfDate
        ,NULL AS YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_BFWTMAST"
),
-- The SQL order of execution will run the where command first, so we are
-- using the landing`s loaded_at on its run, this will capture new rows for us,
-- on otherhand the select clause is using a new loaded_at that will replace this
-- value with the loaded_at of this layer (bronze). Even if they have same names,
--they are different concepts.

bronze_data AS (
    SELECT
        --Could be interesting to convert those timestamps to YYYY-MM-DD HH:MM:SS
        --Could be interesting to convert those dates to YYYY-MM-DD
        CAST(NULLIF(WTTIMESTA, '') AS VARCHAR(14))AS WTTIMESTA
        ,CAST(NULLIF(WTXFRTYPE, '') AS VARCHAR(4)) AS WTXFRTYPE
        ,CAST(NULLIF(WTOMADREF, '') AS VARCHAR(22)) AS WTOMADREF
        ,CAST(NULLIF(WTBANK, '') AS INTEGER) AS WTBANK
        ,CAST(NULLIF(WTBATCH, '') AS INTEGER) AS WTBATCH
        ,CAST(NULLIF(WTRTIME, '') AS INTEGER) AS WTRTIME
        ,CAST(NULLIF(WTRDATE, '') AS INTEGER) AS WTRDATE
        ,CAST(NULLIF(WTRDATJ, '') AS INTEGER) AS WTRDATJ
        ,CAST(NULLIF(WTOUREF, '') AS VARCHAR(30)) AS WTOUREF
        ,CAST(NULLIF(WTBYORO, '') AS VARCHAR(35)) AS WTBYORO
        ,CAST(NULLIF(WTBENEF, '') AS VARCHAR(30)) AS WTBENEF
        ,CAST(NULLIF(WTDBANK, '') AS INTEGER) AS WTDBANK
        ,CAST(NULLIF(WTDBRAN, '') AS INTEGER) AS WTDBRAN
        ,CAST(NULLIF(WTDGLNM, '') AS INTEGER) AS WTDGLNM
        ,CAST(NULLIF(WTDCOST, '') AS INTEGER) AS WTDCOST
        ,CAST(NULLIF(WTDPROD, '') AS INTEGER) AS WTDPROD
        ,CAST(NULLIF(WTDACCT, '') AS BIGINT) AS WTDACCT
        ,CAST(NULLIF(WTDAMNT, '') AS NUMERIC(15,2)) AS WTDAMNT
        ,CAST(NULLIF(WTCBANK, '') AS INTEGER) AS WTCBANK
        ,CAST(NULLIF(WTCBRAN, '') AS INTEGER) AS WTCBRAN
        ,CAST(NULLIF(WTCGLNM, '') AS INTEGER) AS WTCGLNM
        ,CAST(NULLIF(WTCCOST, '') AS INTEGER) AS WTCCOST
        ,CAST(NULLIF(WTCPROD, '') AS INTEGER) AS WTCPROD
        ,CAST(NULLIF(WTCACCT, '') AS BIGINT) AS WTCACCT
        ,CAST(NULLIF(WTCAMNT, '') AS NUMERIC(15,2)) AS WTCAMNT
        ,CAST(NULLIF(WTDFBNK, '') AS INTEGER) AS WTDFBNK
        ,CAST(NULLIF(WTDFBRA, '') AS INTEGER) AS WTDFBRA
        ,CAST(NULLIF(WTDFGLN, '') AS INTEGER) AS WTDFGLN
        ,CAST(NULLIF(WTDFCOS, '') AS INTEGER) AS WTDFCOS
        ,CAST(NULLIF(WTDFPRO, '') AS INTEGER) AS WTDFPRO
        ,CAST(NULLIF(WTDFACC, '') AS BIGINT) AS WTDFACC
        ,CAST(NULLIF(WTDFAMT, '') AS NUMERIC(15,2)) AS WTDFAMT
        ,CAST(NULLIF(WTCFBNK, '') AS INTEGER) AS WTCFBNK
        ,CAST(NULLIF(WTCFBRA, '') AS INTEGER) AS WTCFBRA
        ,CAST(NULLIF(WTCFGLN, '') AS INTEGER) AS WTCFGLN
        ,CAST(NULLIF(WTCFCOS, '') AS INTEGER) AS WTCFCOS
        ,CAST(NULLIF(WTCFPRO, '') AS INTEGER) AS WTCFPRO
        ,CAST(NULLIF(WTCFACC, '') AS BIGINT) AS WTCFACC
        ,CAST(NULLIF(WTCFAMT, '') AS NUMERIC(15,2)) AS WTCFAMT
        ,CAST(NULLIF(WTDSCR1, '') AS VARCHAR(35)) AS WTDSCR1
        ,CAST(NULLIF(WTDSCR2, '') AS VARCHAR(35)) AS WTDSCR2
        ,CAST(NULLIF(WTDSCR3, '') AS VARCHAR(35)) AS WTDSCR3
        ,CAST(NULLIF(WTBYUSER, '') AS VARCHAR(10)) AS WTBYUSER
        ,CAST(NULLIF(WTRELBY, '') AS VARCHAR(10)) AS WTRELBY
        ,CAST(NULLIF(WTCODE, '') AS VARCHAR(3)) AS WTCODE
        ,CAST(NULLIF(WTFMTVR, '') AS INTEGER) AS WTFMTVR
        ,CAST(NULLIF(WTTPRFL, '') AS VARCHAR(1)) AS WTTPRFL
        ,CAST(NULLIF(WTMESSD, '') AS VARCHAR(1)) AS WTMESSD
        ,CAST(NULLIF(WTMESSS, '') AS VARCHAR(1)) AS WTMESSS
        ,CAST(NULLIF(WTSTDMD, '') AS INTEGER) AS WTSTDMD
        ,CAST(NULLIF(WTSTTHM, '') AS INTEGER) AS WTSTTHM
        ,CAST(NULLIF(WTFEDAP, '') AS VARCHAR(4)) AS WTFEDAP
        ,CAST(NULLIF(WTACYMD, '') AS INTEGER) AS WTACYMD
        ,CAST(NULLIF(WTOPDID, '') AS VARCHAR(8)) AS WTOPDID
        ,CAST(NULLIF(WTOUTSE, '') AS INTEGER) AS WTOUTSE
        ,CAST(NULLIF(WTOUTMD, '') AS INTEGER) AS WTOUTMD
        ,CAST(NULLIF(WTOUTTM, '') AS INTEGER) AS WTOUTTM
        ,CAST(NULLIF(WTOUTAI, '') AS VARCHAR(4)) AS WTOUTAI
        ,CAST(NULLIF(WTERRCY, '') AS VARCHAR(1)) AS WTERRCY
        ,CAST(NULLIF(WTERRCD, '') AS VARCHAR(3)) AS WTERRCD
        ,CAST(NULLIF(WTERRDS, '') AS VARCHAR(35)) AS WTERRDS
        ,CAST(NULLIF(WTOUFTV, '') AS INTEGER) AS WTOUFTV
        ,CAST(NULLIF(WTUSRRC, '') AS VARCHAR(8)) AS WTUSRRC
        ,CAST(NULLIF(WTOUTEN, '') AS VARCHAR(1)) AS WTOUTEN
        ,CAST(NULLIF(WTMESDU, '') AS VARCHAR(1)) AS WTMESDU
        ,CAST(NULLIF(WTFEDFU, '') AS VARCHAR(9)) AS WTFEDFU
        ,CAST(NULLIF(WTFEDTT, '') AS INTEGER) AS WTFEDTT
        ,CAST(NULLIF(WTTRSBT, '') AS INTEGER) AS WTTRSBT
        ,CAST(NULLIF(WTPRDAT, '') AS INTEGER) AS WTPRDAT
        ,CAST(NULLIF(WTTERID, '') AS VARCHAR(8)) AS WTTERID
        ,CAST(NULLIF(WTINPSE, '') AS INTEGER) AS WTINPSE
        ,CAST(NULLIF(WTAMOUN, '') AS NUMERIC(12,2)) AS WTAMOUN
        ,CAST(NULLIF(WTADYMD, '') AS INTEGER) AS WTADYMD
        ,CAST(NULLIF(WTADJRE, '') AS VARCHAR(2)) AS WTADJRE
        ,CAST(NULLIF(WTSABAN, '') AS INTEGER) WTSABAN
        ,CAST(NULLIF(WTSENNA, '') AS VARCHAR(18)) AS WTSENNA
        ,CAST(NULLIF(WTSEREF, '') AS VARCHAR(16)) AS WTSEREF
        ,CAST(NULLIF(WTRABAA, '') AS INTEGER) AS WTRABAA
        ,CAST(NULLIF(WTRENAM, '') AS VARCHAR(18)) AS WTRENAM
        ,CAST(NULLIF(WTPDATE, '') AS INTEGER) AS WTPDATE
        ,CAST(NULLIF(WTTERMI, '') AS VARCHAR(8)) AS WTTERMI
        ,CAST(NULLIF(WTINPUS, '') AS INTEGER) AS WTINPUS
        ,CAST(NULLIF(WTPRCOD, '') AS VARCHAR(3)) AS WTPRCOD
        ,CAST(NULLIF(WTCHGTY, '') AS VARCHAR(1)) AS WTCHGTY
        ,CAST(NULLIF(WTCURRE, '') AS VARCHAR(3)) AS WTCURRE
        ,CAST(NULLIF(WTSNCHG, '') AS NUMERIC(12,2)) AS WTSNCHG
        ,CAST(NULLIF(WTCHAG2, '') AS VARCHAR(3)) AS WTCHAG2
        ,CAST(NULLIF(WTSCHG2, '') AS NUMERIC(12,2)) AS WTSCHG2
        ,CAST(NULLIF(WTCHAG3, '') AS VARCHAR(3)) AS WTCHAG3
        ,CAST(NULLIF(WTSCHG3, '') AS NUMERIC(12,2)) AS WTSCHG3
        ,CAST(NULLIF(WTCHAG4, '') AS VARCHAR(3)) AS WTCHAG4
        ,CAST(NULLIF(WTSCHG4, '') AS NUMERIC(12,2)) AS WTSCHG4
        ,CAST(NULLIF(WTINTCU, '') AS VARCHAR(3)) AS WTINTCU
        ,CAST(NULLIF(WTINTAM, '') AS NUMERIC(15,2)) AS WTINTAM
        ,CAST(NULLIF(WTEXRAT, '') AS NUMERIC(12,6)) AS WTEXRAT
        ,CAST(NULLIF(WTINCOD, '') AS VARCHAR(1)) AS WTINCOD
        ,CAST(NULLIF(WTINFIC, '') AS VARCHAR(34)) AS WTINFIC
        ,CAST(NULLIF(WTINFNA, '') AS VARCHAR(35)) AS WTINFNA
        ,CAST(NULLIF(WTIFAD1, '') AS VARCHAR(35)) AS WTIFAD1
        ,CAST(NULLIF(WTIFAD2, '') AS VARCHAR(35)) AS WTIFAD2
        ,CAST(NULLIF(WTIFAD3, '') AS VARCHAR(35)) AS WTIFAD3
        ,CAST(NULLIF(WTBENFC, '') AS VARCHAR(1)) AS WTBENFC
        ,CAST(NULLIF(WTBEFIC, '') AS VARCHAR(34)) AS WTBEFIC
        ,CAST(NULLIF(WTBEFNM, '') AS VARCHAR(35)) AS WTBEFNM
        ,CAST(NULLIF(WTBFAD1, '') AS VARCHAR(35)) AS WTBFAD1
        ,CAST(NULLIF(WTBFAD2, '') AS VARCHAR(35)) AS WTBFAD2
        ,CAST(NULLIF(WTBFAD3, '') AS VARCHAR(35)) AS WTBFAD3
        ,CAST(NULLIF(WTBENCD, '') AS VARCHAR(1)) AS WTBENCD
        ,CAST(NULLIF(WTBENID, '') AS VARCHAR(34)) AS WTBENID
        ,CAST(NULLIF(WTBENNM, '') AS VARCHAR(35)) AS WTBENNM
        ,CAST(NULLIF(WTBEAD1, '') AS VARCHAR(35)) AS WTBEAD1
        ,CAST(NULLIF(WTBEAD2, '') AS VARCHAR(35)) AS WTBEAD2
        ,CAST(NULLIF(WTBEAD3, '') AS VARCHAR(35)) AS  WTBEAD3
        ,CAST(NULLIF(WTBENRE, '') AS VARCHAR(16)) AS  WTBENRE
        ,CAST(NULLIF(WTDRTYP, '') AS VARCHAR(1)) AS  WTDRTYP
        ,CAST(NULLIF(WTDRAID, '') AS VARCHAR(34)) AS  WTDRAID
        ,CAST(NULLIF(WTDRAFI, '') AS VARCHAR(35)) AS  WTDRAFI
        ,CAST(NULLIF(WTDRAD1, '') AS VARCHAR(35)) AS  WTDRAD1
        ,CAST(NULLIF(WTDRAD2, '') AS VARCHAR(35)) AS  WTDRAD2
        ,CAST(NULLIF(WTDRAD3, '') AS VARCHAR(35)) AS  WTDRAD3
        ,CAST(NULLIF(WTORGTY, '') AS VARCHAR(1)) AS  WTORGTY
        ,CAST(NULLIF(WTORGID, '') AS VARCHAR(34)) AS  WTORGID
        ,CAST(NULLIF(WTORGOI, '') AS VARCHAR(35)) AS  WTORGOI
        ,CAST(NULLIF(WTORAD1, '') AS VARCHAR(35)) AS  WTORAD1
        ,CAST(NULLIF(WTORAD2, '') AS VARCHAR(35)) AS  WTORAD2
        ,CAST(NULLIF(WTORAD3, '') AS VARCHAR(35)) AS  WTORAD3
        ,CAST(NULLIF(WTORGFT, '') AS VARCHAR(1)) AS  WTORGFT
        ,CAST(NULLIF(WTORGFI, '') AS VARCHAR(34)) AS  WTORGFI
        ,CAST(NULLIF(WTORGNM, '') AS VARCHAR(35)) AS  WTORGNM
        ,CAST(NULLIF(WTORGA1, '') AS VARCHAR(35)) AS  WTORGA1
        ,CAST(NULLIF(WTORGA2, '') AS VARCHAR(35)) AS  WTORGA2
        ,CAST(NULLIF(WTORGA3, '') AS VARCHAR(35)) AS  WTORGA3
        ,CAST(NULLIF(WTINTYP, '') AS VARCHAR(1)) AS  WTINTYP
        ,CAST(NULLIF(WTINIID, '') AS VARCHAR(34)) AS  WTINIID
        ,CAST(NULLIF(WTININM, '') AS VARCHAR(35)) AS  WTININM
        ,CAST(NULLIF(WTINAD1, '') AS VARCHAR(35)) AS  WTINAD1
        ,CAST(NULLIF(WTINAD2, '') AS VARCHAR(35)) AS  WTINAD2
        ,CAST(NULLIF(WTINAD3, '') AS VARCHAR(35)) AS  WTINAD3
        ,CAST(NULLIF(WTCRABA, '') AS INTEGER) AS WTCRABA
        ,CAST(NULLIF(WTORGB1, '') AS VARCHAR(35)) AS WTORGB1
        ,CAST(NULLIF(WTORGB2, '') AS VARCHAR(35)) AS WTORGB2
        ,CAST(NULLIF(WTORGB3, '') AS VARCHAR(35)) AS WTORGB3
        ,CAST(NULLIF(WTORGB4, '') AS VARCHAR(35)) AS WTORGB4
        ,CAST(NULLIF(WTRFIIN, '') AS VARCHAR(30)) AS WTRFIIN
        ,CAST(NULLIF(WTRFIAD, '') AS VARCHAR(33)) AS WTRFIAD
        ,CAST(NULLIF(WTDRACD, '') AS VARCHAR(3)) AS WTDRACD
        ,CAST(NULLIF(WTDDRAI, '') AS VARCHAR(26)) AS WTDDRAI
        ,CAST(NULLIF(WTDDAIA, '') AS VARCHAR(33)) AS WTDDAIA
        ,CAST(NULLIF(WTIFIL1, '') AS VARCHAR(30)) AS WTIFIL1
        ,CAST(NULLIF(WTIFIAL, '') AS VARCHAR(33)) AS WTIFIAL
        ,CAST(NULLIF(WTINFCD, '') AS VARCHAR(3)) AS WTINFCD
        ,CAST(NULLIF(WTINAL1, '') AS VARCHAR(26)) AS WTINAL1
        ,CAST(NULLIF(WTINAL2, '') AS VARCHAR(33)) AS WTINAL2
        ,CAST(NULLIF(WTBFIL1, '') AS VARCHAR(30)) AS WTBFIL1
        ,CAST(NULLIF(WTBFIAL, '') AS VARCHAR(33)) AS WTBFIAL
        ,CAST(NULLIF(WTBENPA, '') AS VARCHAR(3)) AS WTBENPA
        ,CAST(NULLIF(WTBPAL1, '') AS VARCHAR(26)) AS WTBPAL1
        ,CAST(NULLIF(WTBPAL2, '') AS VARCHAR(33)) AS WTBPAL2
        ,CAST(NULLIF(WTBEIL1, '') AS VARCHAR(30)) AS WTBEIL1
        ,CAST(NULLIF(WTBEIAL, '') AS VARCHAR(33)) AS WTBEIAL
        ,CAST(NULLIF(WTPABNC, '') AS VARCHAR(3)) AS WTPABNC
        ,CAST(NULLIF(WTPABN1, '') AS VARCHAR(26)) AS WTPABN1
        ,CAST(NULLIF(WTPABN2, '') AS VARCHAR(33)) AS WTPABN2
        ,CAST(NULLIF(WTBMPAY, '') AS VARCHAR(5)) AS WTBMPAY
        ,CAST(NULLIF(WTBMPL1, '') AS VARCHAR(30)) AS WTBMPL1
        ,CAST(NULLIF(WTPAYLM, '') AS VARCHAR(4)) AS WTPAYLM
        ,CAST(NULLIF(WTREIL1, '') AS VARCHAR(35)) AS WTREIL1
        ,CAST(NULLIF(WTREIL2, '') AS VARCHAR(35)) AS WTREIL2
        ,CAST(NULLIF(WTREIL3, '') AS VARCHAR(35)) AS WTREIL3
        ,CAST(NULLIF(WTREIL4, '') AS VARCHAR(35)) AS WTREIL4
        ,CAST(NULLIF(WTREIL5, '') AS VARCHAR(35)) AS WTREIL5
        ,CAST(NULLIF(WTFRE01, '') AS VARCHAR(35)) AS WTFRE01
        ,CAST(NULLIF(WTFRE02, '') AS VARCHAR(35)) AS WTFRE02
        ,CAST(NULLIF(WTFRE03, '') AS VARCHAR(35)) AS WTFRE03
        ,CAST(NULLIF(WTFRE04, '') AS VARCHAR(35)) AS WTFRE04
        ,CAST(NULLIF(WTFRE05, '') AS VARCHAR(35)) AS WTFRE05
        ,CAST(NULLIF(WTFRE06, '') AS VARCHAR(35)) AS WTFRE06
        ,CAST(NULLIF(WTFRE07, '') AS VARCHAR(35)) AS WTFRE07
        ,CAST(NULLIF(WTFRE08, '') AS VARCHAR(35)) AS WTFRE08
        ,CAST(NULLIF(WTFRE09, '') AS VARCHAR(35)) AS WTFRE09
        ,CAST(NULLIF(WTFRE10, '') AS VARCHAR(35)) AS WTFRE10
        ,CAST(NULLIF(WTFRE11, '') AS VARCHAR(35)) AS WTFRE11
        ,CAST(NULLIF(WTRANDJUL, '') AS VARCHAR(7)) AS WTRANDJUL
        ,CAST(NULLIF(WTRANDATE, '') AS VARCHAR(6)) AS WTRANDATE
        ,AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6),AsOfDate, 112)) AS YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM "DQP_BRONZE"."dbo"."bronze_jh_bfwtmast"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data