-- Databricks SQL for bronze catalog
-- Rebuilt from dbx/bronze.dbx.sql

CREATE CATALOG IF NOT EXISTS bronze;
USE CATALOG bronze;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- From bronze-sblc.dbx.sql
-- Source model: bronze_sblc_lcmaster
CREATE OR REPLACE TABLE bronze.default.bronze_sblc_lcmaster AS
-- NAME: BRONZE_SBLC_LCMASTER
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: November 27, 2025



WITH landing_data AS (
    SELECT
	 LCMBRN
	 ,LCMCCY
	 ,LCMGLN
	 ,LCMCCN
	 ,LCMPRC
	 ,LCMACN
	 ,LCMFCY
	 ,LCMSTS
	 ,LCMTYP
	 ,LCMORF
	 ,LCMRTY
	 ,LCMOFX
	 ,LCMCNF
	 ,LCMTRF
	 ,LCMTNR
	 ,LCMOFI
	 ,LCMGCD
	 ,LCMGRC
	 ,LCMOAM
	 ,LCMAMN
	 ,LCMCOM
	 ,LCMEXP
	 ,LCMMEB
	 ,LCMCFK
	 ,LCMODM
	 ,LCMODD
	 ,LCMODY
	 ,LCMOPJ
	 ,LCMLAM
	 ,LCMLAD
	 ,LCMLAY
	 ,LCMLAJ
	 ,LCMEXM
	 ,LCMEXD
	 ,LCMEXY
	 ,LCMEXJ
	 ,LCMCLM
	 ,LCMCLD
	 ,LCMCLY
	 ,LCMCLJ
	 ,LCMIB1
	 ,LCMIB2
	 ,LCMIB3
	 ,LCMIBA
	 ,LCMBN1
	 ,LCMBN2
	 ,LCMBN3
	 ,LCMACC
	 ,DATE_OF_DATA
	 ,NULL AS YEARMONTH
	 ,LOADED_AT
    FROM
        sblc.default.sblc_lcmaster
),

bronze_data AS (
    SELECT
        TRY_CAST(LCMBRN AS DECIMAL(3,0)) AS LCMBRN
        ,TRY_CAST(NULLIF(LCMCCY, '') AS STRING) AS LCMCCY
        ,TRY_CAST(LCMGLN AS DECIMAL(7,0)) AS LCMGLN
        ,TRY_CAST(LCMCCN AS DECIMAL(4,0)) AS LCMCCN
        ,TRY_CAST(LCMPRC AS DECIMAL(3,0)) AS LCMPRC
        ,TRY_CAST(LCMACN AS DECIMAL(16,0)) AS LCMACN
        ,TRY_CAST(NULLIF(LCMFCY, '') AS STRING) AS LCMFCY
        ,TRY_CAST(NULLIF(LCMSTS, '') AS STRING) AS LCMSTS
        ,TRY_CAST(NULLIF(LCMTYP, '') AS STRING) AS LCMTYP
        ,TRY_CAST(NULLIF(LCMORF, '') AS STRING) AS LCMORF
        ,TRY_CAST(NULLIF(LCMRTY, '') AS STRING) AS LCMRTY
        ,TRY_CAST(LCMOFX AS DECIMAL(17,6)) AS LCMOFX
        ,TRY_CAST(NULLIF(LCMCNF, '') AS STRING) AS LCMCNF
        ,TRY_CAST(NULLIF(LCMTRF, '') AS STRING) AS LCMTRF
        ,TRY_CAST(NULLIF(LCMTNR, '') AS STRING) AS LCMTNR
        ,TRY_CAST(NULLIF(LCMOFI, '') AS STRING) AS LCMOFI
        ,TRY_CAST(NULLIF(LCMGCD, '') AS STRING) AS LCMGCD
        ,TRY_CAST(NULLIF(LCMGRC, '') AS STRING) AS LCMGRC
        ,TRY_CAST(LCMOAM AS DECIMAL(17,2)) AS LCMOAM
        ,TRY_CAST(LCMAMN AS DECIMAL(17,2)) AS LCMAMN
        ,TRY_CAST(LCMCOM AS DECIMAL(17,2)) AS LCMCOM
        ,TRY_CAST(LCMEXP AS DECIMAL(17,2)) AS LCMEXP
        ,TRY_CAST(LCMMEB AS DECIMAL(17,2)) AS LCMMEB
        ,TRY_CAST(LCMCFK AS STRING) AS LCMCFK
        ,TRY_CAST(LCMODM AS DECIMAL(2,0)) AS LCMODM
        ,TRY_CAST(LCMODD AS DECIMAL(2,0)) AS LCMODD
        ,TRY_CAST(LCMODY AS DECIMAL(2,0)) AS LCMODY
        ,TRY_CAST(LCMOPJ AS DECIMAL(7,0)) AS LCMOPJ
        ,TRY_CAST(LCMLAM AS DECIMAL(2,0)) AS LCMLAM
        ,TRY_CAST(LCMLAD AS DECIMAL(2,0)) AS LCMLAD
        ,TRY_CAST(LCMLAY AS DECIMAL(2,0)) AS LCMLAY
        ,TRY_CAST(LCMLAJ AS DECIMAL(7,0)) AS LCMLAJ
        ,TRY_CAST(LCMEXM AS DECIMAL(2,0)) AS LCMEXM
        ,TRY_CAST(LCMEXD AS DECIMAL(2,0)) AS LCMEXD
        ,TRY_CAST(LCMEXY AS DECIMAL(2,0)) AS LCMEXY
        ,TRY_CAST(LCMEXJ AS DECIMAL(7,0)) AS LCMEXJ
        ,TRY_CAST(LCMCLM AS DECIMAL(2,0)) AS LCMCLM
        ,TRY_CAST(LCMCLD AS DECIMAL(2,0)) AS LCMCLD
        ,TRY_CAST(LCMCLY AS DECIMAL(2,0)) AS LCMCLY
        ,TRY_CAST(LCMCLJ AS DECIMAL(7,0)) AS LCMCLJ
        ,TRY_CAST(NULLIF(LCMIB1, '') AS STRING) AS LCMIB1
        ,TRY_CAST(NULLIF(LCMIB2, '') AS STRING) AS LCMIB2
        ,TRY_CAST(NULLIF(LCMIB3, '') AS STRING) AS LCMIB3
        ,TRY_CAST(LCMIBA AS DECIMAL(16,0)) AS LCMIBA
        ,TRY_CAST(NULLIF(LCMBN1, '') AS STRING) AS LCMBN1
        ,TRY_CAST(NULLIF(LCMBN2, '') AS STRING) AS LCMBN2
        ,TRY_CAST(NULLIF(LCMBN3, '') AS STRING) AS LCMBN3
        ,TRY_CAST(LCMACC AS DECIMAL(9,0)) AS LCMACC
        ,DATE_OF_DATA
        ,TRY_CAST(date_format(DATE_OF_DATA, 'yyyyMM') AS INT) AS YEARMONTH
        ,current_timestamp() AS LOADED_AT
    FROM landing_data
    
    
)





SELECT * FROM bronze_data;

-- From bronze-sblc.dbx.sql
-- Source model: bronze_sblc_lctranx
CREATE OR REPLACE TABLE bronze.default.bronze_sblc_lctranx AS
-- NAME: BRONZE_SBLC_LCTRANX
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: November 27, 2025



with landing_data as (
    SELECT
	    TRY_CAST(NULLIF(TRBR, '') AS INTEGER) AS TRBR
	    ,TRY_CAST(NULLIF(TRCOST, '') AS INTEGER) AS TRCOST
	    ,TRY_CAST(NULLIF(TRPROD, '') AS INTEGER) AS TRPROD
	    ,TRY_CAST(NULLIF(TRAGLN, '') AS INTEGER) AS TRAGLN
	    ,TRACCN
	    ,TRY_CAST(NULLIF(LCMACC, '') AS INTEGER) AS LCMACC
	    ,TRY_CAST(NULLIF(TRCODE, '') AS INTEGER) AS TRCODE
	    ,TRY_CAST(NULLIF(TRATYP, '') AS STRING) AS TRATYP
	    ,DESCRI
	    ,TRY_CAST(NULLIF(TRDORC, '') AS STRING) AS TRDORC
	    ,TRY_CAST(NULLIF(AMOUNT, '') AS DECIMAL(20,2)) AS AMOUNT
	    ,date_format(
            try_cast(STUFF(STUFF(NULLIF(TRIM(TREFF6), ''), 5, 0, '/'), 3, 0, '/') AS DATE),
            'dd-MM-yyyy') AS TREFF6
	    ,DDMUID
	    ,DATE_OF_DATA
	    ,TRY_CAST(date_format(DATE_OF_DATA, 'yyyyMM') AS INT) AS YEARMONTH
    FROM
        sblc.default.sblc_lctranx
    
    
)





SELECT *,current_timestamp() AS LOADED_AT FROM landing_data;

-- Row-count verification
