-- Databricks SQL for Pershing bronze model
-- Generated from sqlserver_brz_dbt/brz-pershing_gact_rec_b.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS bronze_pershing;
USE CATALOG bronze_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source model: BRONZE_PERSHING_GACT_REC_B
-- Source table: landing_pershing.default.pershing_gact_b
CREATE OR REPLACE TABLE bronze_pershing.default.bronze_pershing_gact_b AS
SELECT
    `TRANSACTION_CODE`,
    `RECORD_INDICATOR_VALUE`,
    `RECORD_ID_SEQUENCE_NUMBER`,
    `ACCOUNT_NUMBER`,
    substring(`ACCOUNT_NUMBER`, 1, 3) AS `ACCOUNT_NUMBER_OFFICE`,
    substring(`ACCOUNT_NUMBER`, 4, 6) AS `ACCOUNT_NUMBER_BASE`,
    CAST(NULL AS STRING) AS `ACCOUNT_NUMBER_TYPE`,
    `SECURITY_CURRENCY_OF_ISSUANCE`,
    `TRADE_CURRENCY_CODE`,
    `SETTLEMENT_CURRENCY_CODE`,
    `SETTLEMENT_USD_CURRENCY_FX_RATE`,
    `SETTLEMENT_USD_MULTIPLY_DIVIDE_CODE`,
    `CROSS_CURRENCY_FX_RATE`,
    `CURRENCY_MULTIPLY_DIVIDE_CODE`,
    `ACCRUED_INTEREST_IN_SETTLEMENT_CURRENCY`,
    `MARKET_CODE`,
    `INTERNAL_REFERENCE_FOR_GLOSS`,
    `INTRODUCING_BROKER_DEALER_IBD_VERSION`,
    `NET_AMOUNT_IN_SETTLEMENT_CURRENCY`,
    `PRINCIPAL_AMOUNT_IN_SETTLEMENT_CURRENCY`,
    `INTEREST_IN_SETTLEMENT_CURRENCY`,
    `COMISSION_IN_SETTLEMENT_CURRENCY`,
    `TAX_IN_SETTLEMENT_CURRENCY`,
    `TRANSACTION_FEE_IN_SETTLEMENT_CURRENCY`,
    `MISCELLANEOUS_FEE_IN_SETTLEMENT_CURRENCY`,
    `OTHER_FEE_IN_SETTLEMENT_CURRENCY`,
    `SALES_CREDIT_IN_SETTLEMENT_CURRENCY`,
    `SETTLEMENT_FEE_IN_SETTLEMENT_CURRENCY`,
    `SERVICE_CHARGE_IN_SETTLEMENT_CURRENCY`,
    `MARKUP_MARKDOWN_IN_SETTLEMENT_CURRENCY`,
    `GLOBAL_EXCHANGE`,
    `NUMBER_OF_DESCRIPTION_LINES`,
    `LAST_DESCRIPTION_LINE`,
    `DESCRIPTION_LINE_1`,
    `DESCRIPTION_LINE_2`,
    `DESCRIPTION_LINE_3`,
    `DESCRIPTION_LINE_4`,
    `DESCRIPTION_LINE_5`,
    `DESCRIPTION_LINE_6`,
    `DESCRIPTION_LINE_7`,
    `DESCRIPTION_LINE_8`,
    `DESCRIPTION_LINE_9`,
    `DESCRIPTION_LINE_10`,
    `DESCRIPTION_LINE_11`,
    `DESCRIPTION_LINE_12`,
    `SECURITY_CURRENCY_INDICATOR`,
    `MARKET_MNEMONIC_CODE`,
    `CURRENCY_OF_ISSUANCE_USD_CURRENCY_FX_RATE`,
    `CURRENCY_OF_ISSUANCE_USD_MULTIPLY_DIVIDE_CODE`,
    `ALTERNATE_SECURITY_ID_TYPE_1`,
    `ALTERNATE_SECURITY_ID_1`,
    `ALTERNATE_SECURITY_ID_TYPE_2`,
    `ALTERNATE_SECURITY_ID_2`,
    `INTERNATIONAL_NON_DOLLAR_SYMBOL`,
    `CONFIRMATION_CODE_ONE`,
    `CONFIRMATION_CODE_TWO`,
    `CONFIRMATION_CODE_THREE`,
    `CONFIRMATION_CODE_FOUR`,
    `PREVAILING_MARKET_PRICE_PMP`,
    `TOTAL_AMOUNT_OF_MARK_UP_DOWN`,
    `PMP_PERCENT`,
    `DATE_OF_DATA`,
    `YEARMONTH`,
    current_timestamp() AS `LOADED_AT`
FROM landing_pershing.default.pershing_gact_b;

COMMENT ON TABLE bronze_pershing.default.bronze_pershing_gact_b IS
'Bronze Pershing table bronze_pershing_gact_b contains transfer, ACATS, contra broker, status, and exception records sourced from landing_pershing.default.pershing_gact_b for warehouse parity, validation, reconciliation, and downstream reporting.';
