-- Databricks SQL for Pershing bronze model
-- Generated from sqlserver_brz_dbt/brz-pershing_mfds_rec_a.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS bronze_pershing;
USE CATALOG bronze_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source model: BRONZE_PERSHING_MFDS_REC_A
-- Source table: landing_pershing.default.pershing_mfds_a
CREATE OR REPLACE TABLE bronze_pershing.default.bronze_pershing_mfds_rec_a AS
SELECT
    `TRANSACTION_CODE`,
    `RECORD_ID`,
    `RECORD_ID_SEQUENCE_NUMBER`,
    `CUSIP_NUMBER`,
    `FUND_FAMILY_CODE`,
    `SECURITY_SYMBOL`,
    `DIVIDEND_REINVEST_INDICATOR`,
    `CAPITAL_GAIN_REINVEST_INDICATOR`,
    `FUNDSERV_INDICATOR`,
    `GRANDFATHER_INDICATOR`,
    `LOAD_NO_LOAD_INDICATOR`,
    `NETWORKING_INDICATOR`,
    `NO_TRANSACTION_FEE_ELIGIBILITY_INDICATOR`,
    `SHORT_SETTLEMENT_ELIGIBILITY_INDICATOR`,
    `SYSTEMATIC_REINVESTMENT_SYSTEM_ELIGIBILITY_INDICATOR`,
    `DIVIDEND_FREQUENCY`,
    `CLOSED_TO_BUYS_INDICATOR`,
    `CLOSED_TO_SELLS_INDICATOR`,
    `NEW_INVESTMENT_CLOSED_INDICATOR`,
    `SETTLE_PURCHASE_DAYS_NON_FUNDSERV`,
    `SETTLE_REDEMPTION_DAYS_NON_FUNDSERV`,
    `SETTLE_PURCHASE_DAYS_FUNDSERV`,
    `SETTLE_REDEMPTION_DAYS_FUNDSERV`,
    `EXCHANGE_CUT_OFF_TIME`,
    `PURCHASE_CUT_OFF_TIME`,
    `REDEMPTION_CUT_OFF_TIME`,
    `LAST_PRICE`,
    `LAST_PRICE_DATE`,
    `FUND_FAMILY_NAME`,
    `SHARE_CLASS`,
    `MUTUAL_FUND_DESCRIPTION_LINE_1`,
    `MUTUAL_FUND_DESCRIPTION_LINE_2`,
    `MUTUAL_FUND_DESCRIPTION_LINE_3`,
    `MUTUAL_FUND_DESCRIPTION_LINE_4`,
    `MUTUAL_FUND_DESCRIPTION_LINE_5`,
    `MUTUAL_FUND_DESCRIPTION_LINE_6`,
    `EXCHANGE_ELIGIBLE_INDICATOR`,
    `TRADE_STATUS`,
    `CUSTOMER_COMMENTS`,
    `OFFSHORE_INDICATOR`,
    `OFFSHORE_PROCESSING_INDICATOR`,
    `DEALER_AGREEMENT_REQUIRED_FOR_LOAD_TRADES`,
    `DEALER_AGREEMENT_REQUIRED_FOR_NO_LOAD_TRADES`,
    `DEALER_AGREEMENT_REQUIRED_FOR_LOAD_TRANSFERS`,
    `DEALER_AGREEMENT_REQUIRED_FOR_NO_LOAD_TRANFERS`,
    `AS_OF_INDICATOR`,
    `AS_OF_DAYS`,
    `POST_SETTLE_CANCEL_INDICATOR`,
    `POST_SETTLE_CANCEL_DAYS`,
    `POST_SETTLE_MAXIMUM_DOLLAR_AMOUNT`,
    `MINIMUM_INITIAL_PURCHASE_AMOUNT`,
    `MINIMUM_SUBSEQUENCE_PURCHASE_AMOUNT`,
    `MAXIMUM_INITIAL_PURCHASE_AMOUNT`,
    `MAXIMUM_SUBSEQUENCE_PURCHASE_AMOUNT`,
    `OMNIBUS_INDICATOR`,
    `TENDER_INDICATOR`,
    `FUNDVEST_200_ELIGIBLE`,
    `SURCHARGE`,
    `CURRENCY`,
    `RETIREMENT_PLAN_NETWORK_RPN_ELIGIBLE_INDICATOR`,
    `TRADING_RESTRICTED_BY_BOOKING_ENTITIES`,
    `BNY_MELLON_BNYM`,
    `PERSHING_LLC_PLLC`,
    `PERSHING_AUSTRALIA_PSAL`,
    `PERSHING_CANADA_PSCL`,
    `PERSHING_LONDON_PSLL`,
    `FUND_SHARE_CLASS`,
    `_12B_1_INDICATOR`,
    `DATE_OF_DATA`,
    `YEARMONTH`,
    current_timestamp() AS `LOADED_AT`
FROM landing_pershing.default.pershing_mfds_a;

COMMENT ON TABLE bronze_pershing.default.bronze_pershing_mfds_rec_a IS
'Bronze Pershing table bronze_pershing_mfds_rec_a contains security, fund, pricing, income, and product reference records sourced from landing_pershing.default.pershing_mfds_a for warehouse parity, validation, reconciliation, and downstream reporting.';
