-- Databricks SQL for source: jh_bfwtmast
-- Generated from sqlserver_brz/brz-jh_bfwtmast.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_BFWTMAST"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_bfwtmast (
    `WTTIMESTA` STRING,
    `WTXFRTYPE` STRING,
    `WTOMADREF` STRING,
    `WTBANK` STRING,
    `WTBATCH` STRING,
    `WTRTIME` STRING,
    `WTRDATE` STRING,
    `WTRDATJ` STRING,
    `WTOUREF` STRING,
    `WTBYORO` STRING,
    `WTBENEF` STRING,
    `WTDBANK` STRING,
    `WTDBRAN` STRING,
    `WTDGLNM` STRING,
    `WTDCOST` STRING,
    `WTDPROD` STRING,
    `WTDACCT` STRING,
    `WTDAMNT` DECIMAL(38,10),
    `WTCBANK` STRING,
    `WTCBRAN` STRING,
    `WTCGLNM` STRING,
    `WTCCOST` STRING,
    `WTCPROD` STRING,
    `WTCACCT` STRING,
    `WTCAMNT` DECIMAL(38,10),
    `WTDFBNK` STRING,
    `WTDFBRA` STRING,
    `WTDFGLN` STRING,
    `WTDFCOS` STRING,
    `WTDFPRO` STRING,
    `WTDFACC` STRING,
    `WTDFAMT` DECIMAL(38,10),
    `WTCFBNK` STRING,
    `WTCFBRA` STRING,
    `WTCFGLN` STRING,
    `WTCFCOS` STRING,
    `WTCFPRO` STRING,
    `WTCFACC` STRING,
    `WTCFAMT` DECIMAL(38,10),
    `WTDSCR1` STRING,
    `WTDSCR2` STRING,
    `WTDSCR3` STRING,
    `WTBYUSER` STRING,
    `WTRELBY` STRING,
    `WTCODE` STRING,
    `WTFMTVR` STRING,
    `WTTPRFL` STRING,
    `WTMESSD` STRING,
    `WTMESSS` STRING,
    `WTSTDMD` STRING,
    `WTSTTHM` STRING,
    `WTFEDAP` STRING,
    `WTACYMD` STRING,
    `WTOPDID` STRING,
    `WTOUTSE` STRING,
    `WTOUTMD` STRING,
    `WTOUTTM` STRING,
    `WTOUTAI` STRING,
    `WTERRCY` STRING,
    `WTERRCD` STRING,
    `WTERRDS` STRING,
    `WTOUFTV` STRING,
    `WTUSRRC` STRING,
    `WTOUTEN` STRING,
    `WTMESDU` STRING,
    `WTFEDFU` STRING,
    `WTFEDTT` STRING,
    `WTTRSBT` STRING,
    `WTPRDAT` STRING,
    `WTTERID` STRING,
    `WTINPSE` STRING,
    `WTAMOUN` STRING,
    `WTADYMD` STRING,
    `WTADJRE` STRING,
    `WTSABAN` STRING,
    `WTSENNA` STRING,
    `WTSEREF` STRING,
    `WTRABAA` STRING,
    `WTRENAM` STRING,
    `WTPDATE` STRING,
    `WTTERMI` STRING,
    `WTINPUS` STRING,
    `WTPRCOD` STRING,
    `WTCHGTY` DECIMAL(38,10),
    `WTCURRE` STRING,
    `WTSNCHG` DECIMAL(38,10),
    `WTCHAG2` STRING,
    `WTSCHG2` DECIMAL(38,10),
    `WTCHAG3` STRING,
    `WTSCHG3` DECIMAL(38,10),
    `WTCHAG4` STRING,
    `WTSCHG4` DECIMAL(38,10),
    `WTINTCU` STRING,
    `WTINTAM` DECIMAL(38,10),
    `WTEXRAT` DECIMAL(38,10),
    `WTINCOD` STRING,
    `WTINFIC` STRING,
    `WTINFNA` STRING,
    `WTIFAD1` STRING,
    `WTIFAD2` STRING,
    `WTIFAD3` STRING,
    `WTBENFC` STRING,
    `WTBEFIC` STRING,
    `WTBEFNM` STRING,
    `WTBFAD1` STRING,
    `WTBFAD2` STRING,
    `WTBFAD3` STRING,
    `WTBENCD` STRING,
    `WTBENID` STRING,
    `WTBENNM` STRING,
    `WTBEAD1` STRING,
    `WTBEAD2` STRING,
    `WTBEAD3` STRING,
    `WTBENRE` STRING,
    `WTDRTYP` STRING,
    `WTDRAID` STRING,
    `WTDRAFI` STRING,
    `WTDRAD1` STRING,
    `WTDRAD2` STRING,
    `WTDRAD3` STRING,
    `WTORGTY` STRING,
    `WTORGID` STRING,
    `WTORGOI` STRING,
    `WTORAD1` STRING,
    `WTORAD2` STRING,
    `WTORAD3` STRING,
    `WTORGFT` STRING,
    `WTORGFI` STRING,
    `WTORGNM` STRING,
    `WTORGA1` STRING,
    `WTORGA2` STRING,
    `WTORGA3` STRING,
    `WTINTYP` STRING,
    `WTINIID` STRING,
    `WTININM` STRING,
    `WTINAD1` STRING,
    `WTINAD2` STRING,
    `WTINAD3` STRING,
    `WTCRABA` STRING,
    `WTORGB1` STRING,
    `WTORGB2` STRING,
    `WTORGB3` STRING,
    `WTORGB4` STRING,
    `WTRFIIN` STRING,
    `WTRFIAD` STRING,
    `WTDRACD` STRING,
    `WTDDRAI` STRING,
    `WTDDAIA` STRING,
    `WTIFIL1` STRING,
    `WTIFIAL` STRING,
    `WTINFCD` STRING,
    `WTINAL1` STRING,
    `WTINAL2` STRING,
    `WTBFIL1` STRING,
    `WTBFIAL` STRING,
    `WTBENPA` STRING,
    `WTBPAL1` STRING,
    `WTBPAL2` STRING,
    `WTBEIL1` STRING,
    `WTBEIAL` STRING,
    `WTPABNC` STRING,
    `WTPABN1` STRING,
    `WTPABN2` STRING,
    `WTBMPAY` STRING,
    `WTBMPL1` STRING,
    `WTPAYLM` STRING,
    `WTREIL1` STRING,
    `WTREIL2` STRING,
    `WTREIL3` STRING,
    `WTREIL4` STRING,
    `WTREIL5` STRING,
    `WTFRE01` STRING,
    `WTFRE02` STRING,
    `WTFRE03` STRING,
    `WTFRE04` STRING,
    `WTFRE05` STRING,
    `WTFRE06` STRING,
    `WTFRE07` STRING,
    `WTFRE08` STRING,
    `WTFRE09` STRING,
    `WTFRE10` STRING,
    `WTFRE11` STRING,
    `WTRANDJUL` STRING,
    `WTRANDATE` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_bfwtmast IS
'The JH BFWTMAST landing table captures detailed wire transfer master records, including debit and credit accounts, amounts, banks, beneficiaries, originators, intermediary parties, Fed references, exception details, and transaction dates for wire operations reconciliation and downstream bronze processing.';

TRUNCATE TABLE landing_jh.default.jh_bfwtmast;

INSERT INTO landing_jh.default.jh_bfwtmast (
    `WTTIMESTA`, `WTXFRTYPE`, `WTOMADREF`, `WTBANK`, `WTBATCH`, `WTRTIME`,
    `WTRDATE`, `WTRDATJ`, `WTOUREF`, `WTBYORO`, `WTBENEF`, `WTDBANK`,
    `WTDBRAN`, `WTDGLNM`, `WTDCOST`, `WTDPROD`, `WTDACCT`, `WTDAMNT`,
    `WTCBANK`, `WTCBRAN`, `WTCGLNM`, `WTCCOST`, `WTCPROD`, `WTCACCT`,
    `WTCAMNT`, `WTDFBNK`, `WTDFBRA`, `WTDFGLN`, `WTDFCOS`, `WTDFPRO`,
    `WTDFACC`, `WTDFAMT`, `WTCFBNK`, `WTCFBRA`, `WTCFGLN`, `WTCFCOS`,
    `WTCFPRO`, `WTCFACC`, `WTCFAMT`, `WTDSCR1`, `WTDSCR2`, `WTDSCR3`,
    `WTBYUSER`, `WTRELBY`, `WTCODE`, `WTFMTVR`, `WTTPRFL`, `WTMESSD`,
    `WTMESSS`, `WTSTDMD`, `WTSTTHM`, `WTFEDAP`, `WTACYMD`, `WTOPDID`,
    `WTOUTSE`, `WTOUTMD`, `WTOUTTM`, `WTOUTAI`, `WTERRCY`, `WTERRCD`,
    `WTERRDS`, `WTOUFTV`, `WTUSRRC`, `WTOUTEN`, `WTMESDU`, `WTFEDFU`,
    `WTFEDTT`, `WTTRSBT`, `WTPRDAT`, `WTTERID`, `WTINPSE`, `WTAMOUN`,
    `WTADYMD`, `WTADJRE`, `WTSABAN`, `WTSENNA`, `WTSEREF`, `WTRABAA`,
    `WTRENAM`, `WTPDATE`, `WTTERMI`, `WTINPUS`, `WTPRCOD`, `WTCHGTY`,
    `WTCURRE`, `WTSNCHG`, `WTCHAG2`, `WTSCHG2`, `WTCHAG3`, `WTSCHG3`,
    `WTCHAG4`, `WTSCHG4`, `WTINTCU`, `WTINTAM`, `WTEXRAT`, `WTINCOD`,
    `WTINFIC`, `WTINFNA`, `WTIFAD1`, `WTIFAD2`, `WTIFAD3`, `WTBENFC`,
    `WTBEFIC`, `WTBEFNM`, `WTBFAD1`, `WTBFAD2`, `WTBFAD3`, `WTBENCD`,
    `WTBENID`, `WTBENNM`, `WTBEAD1`, `WTBEAD2`, `WTBEAD3`, `WTBENRE`,
    `WTDRTYP`, `WTDRAID`, `WTDRAFI`, `WTDRAD1`, `WTDRAD2`, `WTDRAD3`,
    `WTORGTY`, `WTORGID`, `WTORGOI`, `WTORAD1`, `WTORAD2`, `WTORAD3`,
    `WTORGFT`, `WTORGFI`, `WTORGNM`, `WTORGA1`, `WTORGA2`, `WTORGA3`,
    `WTINTYP`, `WTINIID`, `WTININM`, `WTINAD1`, `WTINAD2`, `WTINAD3`,
    `WTCRABA`, `WTORGB1`, `WTORGB2`, `WTORGB3`, `WTORGB4`, `WTRFIIN`,
    `WTRFIAD`, `WTDRACD`, `WTDDRAI`, `WTDDAIA`, `WTIFIL1`, `WTIFIAL`,
    `WTINFCD`, `WTINAL1`, `WTINAL2`, `WTBFIL1`, `WTBFIAL`, `WTBENPA`,
    `WTBPAL1`, `WTBPAL2`, `WTBEIL1`, `WTBEIAL`, `WTPABNC`, `WTPABN1`,
    `WTPABN2`, `WTBMPAY`, `WTBMPL1`, `WTPAYLM`, `WTREIL1`, `WTREIL2`,
    `WTREIL3`, `WTREIL4`, `WTREIL5`, `WTFRE01`, `WTFRE02`, `WTFRE03`,
    `WTFRE04`, `WTFRE05`, `WTFRE06`, `WTFRE07`, `WTFRE08`, `WTFRE09`,
    `WTFRE10`, `WTFRE11`, `WTRANDJUL`, `WTRANDATE`, `AsOfDate`, `YEARMONTH`,
    `LOADED_AT`
)
SELECT
    concat('WTTIMESTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTTIMESTA`,
    concat('WTXFRTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTXFRTYPE`,
    concat('WTOMADREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOMADREF`,
    concat('WTBANK_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBANK`,
    concat('WTBATCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBATCH`,
    concat('WTRTIME_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRTIME`,
    concat('WTRDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRDATE`,
    concat('WTRDATJ_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRDATJ`,
    concat('WTOUREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUREF`,
    concat('WTBYORO_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBYORO`,
    concat('WTBENEF_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENEF`,
    concat('WTDBANK_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDBANK`,
    concat('WTDBRAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDBRAN`,
    concat('WTDGLNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDGLNM`,
    concat('WTDCOST_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDCOST`,
    concat('WTDPROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDPROD`,
    concat('WTDACCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDACCT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTDAMNT`,
    concat('WTCBANK_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCBANK`,
    concat('WTCBRAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCBRAN`,
    concat('WTCGLNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCGLNM`,
    concat('WTCCOST_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCCOST`,
    concat('WTCPROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCPROD`,
    concat('WTCACCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCACCT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTCAMNT`,
    concat('WTDFBNK_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFBNK`,
    concat('WTDFBRA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFBRA`,
    concat('WTDFGLN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFGLN`,
    concat('WTDFCOS_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFCOS`,
    concat('WTDFPRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFPRO`,
    concat('WTDFACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDFACC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTDFAMT`,
    concat('WTCFBNK_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFBNK`,
    concat('WTCFBRA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFBRA`,
    concat('WTCFGLN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFGLN`,
    concat('WTCFCOS_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFCOS`,
    concat('WTCFPRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFPRO`,
    concat('WTCFACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCFACC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTCFAMT`,
    concat('WTDSCR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDSCR1`,
    concat('WTDSCR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDSCR2`,
    concat('WTDSCR3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDSCR3`,
    concat('WTBYUSER_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBYUSER`,
    concat('WTRELBY_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRELBY`,
    concat('WTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCODE`,
    concat('WTFMTVR_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFMTVR`,
    concat('WTTPRFL_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTTPRFL`,
    concat('WTMESSD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTMESSD`,
    concat('WTMESSS_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTMESSS`,
    concat('WTSTDMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTSTDMD`,
    concat('WTSTTHM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTSTTHM`,
    concat('WTFEDAP_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFEDAP`,
    concat('WTACYMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTACYMD`,
    concat('WTOPDID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOPDID`,
    concat('WTOUTSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUTSE`,
    concat('WTOUTMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUTMD`,
    concat('WTOUTTM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUTTM`,
    concat('WTOUTAI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUTAI`,
    concat('WTERRCY_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTERRCY`,
    concat('WTERRCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTERRCD`,
    concat('WTERRDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTERRDS`,
    concat('WTOUFTV_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUFTV`,
    concat('WTUSRRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTUSRRC`,
    concat('WTOUTEN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTOUTEN`,
    concat('WTMESDU_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTMESDU`,
    concat('WTFEDFU_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFEDFU`,
    concat('WTFEDTT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFEDTT`,
    concat('WTTRSBT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTTRSBT`,
    concat('WTPRDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPRDAT`,
    concat('WTTERID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTTERID`,
    concat('WTINPSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINPSE`,
    concat('WTAMOUN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTAMOUN`,
    concat('WTADYMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTADYMD`,
    concat('WTADJRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTADJRE`,
    concat('WTSABAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTSABAN`,
    concat('WTSENNA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTSENNA`,
    concat('WTSEREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTSEREF`,
    concat('WTRABAA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRABAA`,
    concat('WTRENAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRENAM`,
    concat('WTPDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPDATE`,
    concat('WTTERMI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTTERMI`,
    concat('WTINPUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINPUS`,
    concat('WTPRCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPRCOD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTCHGTY`,
    concat('WTCURRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCURRE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTSNCHG`,
    concat('WTCHAG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCHAG2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTSCHG2`,
    concat('WTCHAG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCHAG3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTSCHG3`,
    concat('WTCHAG4_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCHAG4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTSCHG4`,
    concat('WTINTCU_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINTCU`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTINTAM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WTEXRAT`,
    concat('WTINCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINCOD`,
    concat('WTINFIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINFIC`,
    concat('WTINFNA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINFNA`,
    concat('WTIFAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTIFAD1`,
    concat('WTIFAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTIFAD2`,
    concat('WTIFAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTIFAD3`,
    concat('WTBENFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENFC`,
    concat('WTBEFIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEFIC`,
    concat('WTBEFNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEFNM`,
    concat('WTBFAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBFAD1`,
    concat('WTBFAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBFAD2`,
    concat('WTBFAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBFAD3`,
    concat('WTBENCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENCD`,
    concat('WTBENID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENID`,
    concat('WTBENNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENNM`,
    concat('WTBEAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEAD1`,
    concat('WTBEAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEAD2`,
    concat('WTBEAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEAD3`,
    concat('WTBENRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENRE`,
    concat('WTDRTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRTYP`,
    concat('WTDRAID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRAID`,
    concat('WTDRAFI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRAFI`,
    concat('WTDRAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRAD1`,
    concat('WTDRAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRAD2`,
    concat('WTDRAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRAD3`,
    concat('WTORGTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGTY`,
    concat('WTORGID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGID`,
    concat('WTORGOI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGOI`,
    concat('WTORAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORAD1`,
    concat('WTORAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORAD2`,
    concat('WTORAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORAD3`,
    concat('WTORGFT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGFT`,
    concat('WTORGFI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGFI`,
    concat('WTORGNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGNM`,
    concat('WTORGA1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGA1`,
    concat('WTORGA2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGA2`,
    concat('WTORGA3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGA3`,
    concat('WTINTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINTYP`,
    concat('WTINIID_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINIID`,
    concat('WTININM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTININM`,
    concat('WTINAD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINAD1`,
    concat('WTINAD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINAD2`,
    concat('WTINAD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINAD3`,
    concat('WTCRABA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTCRABA`,
    concat('WTORGB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGB1`,
    concat('WTORGB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGB2`,
    concat('WTORGB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGB3`,
    concat('WTORGB4_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTORGB4`,
    concat('WTRFIIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRFIIN`,
    concat('WTRFIAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRFIAD`,
    concat('WTDRACD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDRACD`,
    concat('WTDDRAI_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDDRAI`,
    concat('WTDDAIA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTDDAIA`,
    concat('WTIFIL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTIFIL1`,
    concat('WTIFIAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTIFIAL`,
    concat('WTINFCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINFCD`,
    concat('WTINAL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINAL1`,
    concat('WTINAL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTINAL2`,
    concat('WTBFIL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBFIL1`,
    concat('WTBFIAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBFIAL`,
    concat('WTBENPA_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBENPA`,
    concat('WTBPAL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBPAL1`,
    concat('WTBPAL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBPAL2`,
    concat('WTBEIL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEIL1`,
    concat('WTBEIAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBEIAL`,
    concat('WTPABNC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPABNC`,
    concat('WTPABN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPABN1`,
    concat('WTPABN2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPABN2`,
    concat('WTBMPAY_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBMPAY`,
    concat('WTBMPL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTBMPL1`,
    concat('WTPAYLM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTPAYLM`,
    concat('WTREIL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTREIL1`,
    concat('WTREIL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTREIL2`,
    concat('WTREIL3_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTREIL3`,
    concat('WTREIL4_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTREIL4`,
    concat('WTREIL5_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTREIL5`,
    concat('WTFRE01_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE01`,
    concat('WTFRE02_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE02`,
    concat('WTFRE03_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE03`,
    concat('WTFRE04_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE04`,
    concat('WTFRE05_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE05`,
    concat('WTFRE06_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE06`,
    concat('WTFRE07_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE07`,
    concat('WTFRE08_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE08`,
    concat('WTFRE09_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE09`,
    concat('WTFRE10_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE10`,
    concat('WTFRE11_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTFRE11`,
    concat('WTRANDJUL_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRANDJUL`,
    concat('WTRANDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WTRANDATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_bfwtmast' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_bfwtmast;
