-- Databricks SQL for source: pershing
-- Generated from sqlserver_landing_dbt/landing-pershing_caps_rec_3.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS landing_pershing;
USE CATALOG landing_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHING_CAPS_3"
CREATE TABLE IF NOT EXISTS landing_pershing.default.pershing_caps_3 (
    `INTRODUCING_BROKER_DEALER_IBD_NUMBER` STRING,
    `RECORD_ID` STRING,
    `AS_OF_TRADE_INDICATOR` STRING,
    `DISTRIBUTION_INDICATOR` STRING,
    `EXPLODE_INDICATOR` STRING,
    `REVENUE_TYPE` STRING,
    `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER` STRING,
    `INVESTMENT_PROFESSIONAL_CAPS_REVENUE_CENTER` STRING,
    `INVESTMENT_PROFESSIONAL_CAPS_OFFICE_NUMBER` STRING,
    `INVESTMENT_PROFESSIONAL_SPLIT_PERCENT` DECIMAL(7,3),
    `TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP` DECIMAL(14,2),
    `PERSHING_CHARGE` DECIMAL(12,2),
    `LEGACY_FROM_INVESTMENT_PROFESSIONAL_NUMBER` STRING,
    `CAPS_REVENUE_CENTER_ASSOCIATED_WITH_IP` STRING,
    `CAPS_OFFICE_NUMBER_ASSOCIATED_WITH_IP` STRING,
    `TOTAL_ORDER_COMMISSION` DECIMAL(12,2),
    `SPREAD_STRADDLE_MUTUAL_FUND_VALUES` DECIMAL(38,10),
    `CORRECTION_CODE` STRING,
    `SECURITY_MODIFIER` STRING,
    `SECURITY_CALCULATION_CODE` STRING,
    `PRINCIPAL` DECIMAL(12,2),
    `CRD_NUMBER` STRING,
    `SOURCE_OF_INPUT` STRING,
    `SERVICE_CHARGE_OTHER_FEE` DECIMAL(12,2),
    `RECORD_ID_SEQUENCE_NUMBER` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_pershing.default.pershing_caps_3 IS
'Pershing landing table containing trade, position, security, amount, and settlement attributes sourced from SQL Server dbt bronze logic for validation, reconciliation, and downstream brokerage reporting.';

TRUNCATE TABLE landing_pershing.default.pershing_caps_3;

INSERT INTO landing_pershing.default.pershing_caps_3 (
    `INTRODUCING_BROKER_DEALER_IBD_NUMBER`, `RECORD_ID`, `AS_OF_TRADE_INDICATOR`, `DISTRIBUTION_INDICATOR`,
    `EXPLODE_INDICATOR`, `REVENUE_TYPE`, `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    `INVESTMENT_PROFESSIONAL_CAPS_REVENUE_CENTER`, `INVESTMENT_PROFESSIONAL_CAPS_OFFICE_NUMBER`,
    `INVESTMENT_PROFESSIONAL_SPLIT_PERCENT`, `TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP`, `PERSHING_CHARGE`,
    `LEGACY_FROM_INVESTMENT_PROFESSIONAL_NUMBER`, `CAPS_REVENUE_CENTER_ASSOCIATED_WITH_IP`,
    `CAPS_OFFICE_NUMBER_ASSOCIATED_WITH_IP`, `TOTAL_ORDER_COMMISSION`, `SPREAD_STRADDLE_MUTUAL_FUND_VALUES`,
    `CORRECTION_CODE`, `SECURITY_MODIFIER`, `SECURITY_CALCULATION_CODE`, `PRINCIPAL`, `CRD_NUMBER`, `SOURCE_OF_INPUT`,
    `SERVICE_CHARGE_OTHER_FEE`, `RECORD_ID_SEQUENCE_NUMBER`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('INTRODUCING_BROKER_DEALE_', format_string('%02d', idx)) AS `INTRODUCING_BROKER_DEALER_IBD_NUMBER`,
    concat('RECORD_ID_', format_string('%02d', idx)) AS `RECORD_ID`,
    concat('AS_OF_TRADE_INDICATOR_', format_string('%02d', idx)) AS `AS_OF_TRADE_INDICATOR`,
    concat('DISTRIBUTION_INDICATOR_', format_string('%02d', idx)) AS `DISTRIBUTION_INDICATOR`,
    concat('EXPLODE_INDICATOR_', format_string('%02d', idx)) AS `EXPLODE_INDICATOR`,
    concat('REVENUE_TYPE_', format_string('%02d', idx)) AS `REVENUE_TYPE`,
    concat('LEGACY_INVESTMENT_PROFES_', format_string('%02d', idx)) AS `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    concat('INVESTMENT_PROFESSIONAL__', format_string('%02d', idx)) AS `INVESTMENT_PROFESSIONAL_CAPS_REVENUE_CENTER`,
    concat('INVESTMENT_PROFESSIONAL__', format_string('%02d', idx)) AS `INVESTMENT_PROFESSIONAL_CAPS_OFFICE_NUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(7,3)) AS `INVESTMENT_PROFESSIONAL_SPLIT_PERCENT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(14,2)) AS `TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(12,2)) AS `PERSHING_CHARGE`,
    concat('LEGACY_FROM_INVESTMENT_P_', format_string('%02d', idx)) AS `LEGACY_FROM_INVESTMENT_PROFESSIONAL_NUMBER`,
    concat('CAPS_REVENUE_CENTER_ASSO_', format_string('%02d', idx)) AS `CAPS_REVENUE_CENTER_ASSOCIATED_WITH_IP`,
    concat('CAPS_OFFICE_NUMBER_ASSOC_', format_string('%02d', idx)) AS `CAPS_OFFICE_NUMBER_ASSOCIATED_WITH_IP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(12,2)) AS `TOTAL_ORDER_COMMISSION`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SPREAD_STRADDLE_MUTUAL_FUND_VALUES`,
    concat('CORRECTION_CODE_', format_string('%02d', idx)) AS `CORRECTION_CODE`,
    concat('SECURITY_MODIFIER_', format_string('%02d', idx)) AS `SECURITY_MODIFIER`,
    concat('SECURITY_CALCULATION_COD_', format_string('%02d', idx)) AS `SECURITY_CALCULATION_CODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(12,2)) AS `PRINCIPAL`,
    concat('CRD_NUMBER_', format_string('%02d', idx)) AS `CRD_NUMBER`,
    concat('SOURCE_OF_INPUT_', format_string('%02d', idx)) AS `SOURCE_OF_INPUT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(12,2)) AS `SERVICE_CHARGE_OTHER_FEE`,
    concat('RECORD_ID_SEQUENCE_NUMBE_', format_string('%02d', idx)) AS `RECORD_ID_SEQUENCE_NUMBER`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershing_caps_3' AS table_name, COUNT(*) AS record_count
FROM landing_pershing.default.pershing_caps_3;
