-- Databricks SQL for source: jh_cdpar2
-- Generated from sqlserver_brz/brz-jh_cdpar2.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_CDPAR2"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_cdpar2 (
    `P2BRNO` INT,
    `P2REGN` STRING,
    `P2XRFNBR` INT,
    `PTYPE` STRING,
    `PDESC` STRING,
    `PGROUP` STRING,
    `PGRPDS` STRING,
    `P2COST` STRING,
    `P2PROD` STRING,
    `P2IQNM` STRING,
    `PCTERM` STRING,
    `PCCODE` STRING,
    `PITERM` STRING,
    `PICODE` STRING,
    `PMETHD` STRING,
    `PYRCOD` STRING,
    `PEVENC` STRING,
    `PRATE` DECIMAL(38,10),
    `PRATEM` DECIMAL(38,10),
    `PRATE_CS` DECIMAL(38,10),
    `PBLRT2` STRING,
    `PRAT2_CS` STRING,
    `PBLRT3` STRING,
    `PRAT3_CS` STRING,
    `PBLRT4` STRING,
    `PRAT4_CS` STRING,
    `PBLRT5` STRING,
    `PRAT5_CS` STRING,
    `PBLRT6` STRING,
    `PRAT6_CS` STRING,
    `PBLRT7` STRING,
    `PRAT7_CS` STRING,
    `PBLRT8` STRING,
    `PRAT8_CS` STRING,
    `PBLRT9` STRING,
    `PRAT9_CS` STRING,
    `PBLRT0` STRING,
    `PRAT0_CS` STRING,
    `SPLTAC` STRING,
    `PRENEW` STRING,
    `PRNRT1` STRING,
    `PRNBL2` STRING,
    `PRNRT2` STRING,
    `PRNBL3` STRING,
    `PRNRT3` STRING,
    `PRNBL4` STRING,
    `PRNRT4` STRING,
    `PRNBL5` STRING,
    `PRNRT5` STRING,
    `PRNBL6` STRING,
    `PRNRT6` STRING,
    `PRNBL7` STRING,
    `PRNRT7` STRING,
    `PRNBL8` STRING,
    `PRNRT8` STRING,
    `PRNBL9` STRING,
    `PRNRT9` STRING,
    `PRNBL0` STRING,
    `PRNRT0` STRING,
    `PRNNOT` STRING,
    `PRNGRC` STRING,
    `PB4RNW` STRING,
    `PB4MAT` STRING,
    `P2ESCH` STRING,
    `PIRATY` STRING,
    `PIDISP` STRING,
    `PCOMCK` STRING,
    `PPENTY` DECIMAL(38,10),
    `PPEN59` DECIMAL(38,10),
    `PWHCOD` STRING,
    `PINCLU` STRING,
    `PHMAIL` STRING,
    `PMATCO` STRING,
    `PSTMTC` STRING,
    `PALMTY` STRING,
    `PPAPLE` STRING,
    `PPALAS` STRING,
    `PRATSC` STRING,
    `PALNXT` STRING,
    `PSTMPA` STRING,
    `PSIC1` STRING,
    `PSIC2` STRING,
    `PSIC3` STRING,
    `PSIC4` STRING,
    `PEXDAY` STRING,
    `PMLDRT` STRING,
    `PFLCOD` STRING,
    `P2STMD` STRING,
    `P2MNDW` STRING,
    `P2PAPY` STRING,
    `PVRAPY` STRING,
    `PV2APY` STRING,
    `PV3APY` STRING,
    `PV4APY` STRING,
    `PV5APY` STRING,
    `PV6APY` STRING,
    `PV7APY` STRING,
    `PV8APY` STRING,
    `PV9APY` STRING,
    `PV0APY` STRING,
    `PRNAPY` STRING,
    `PR2APY` STRING,
    `PR3APY` STRING,
    `PR4APY` STRING,
    `PR5APY` STRING,
    `PR6APY` STRING,
    `PR7APY` STRING,
    `PR8APY` STRING,
    `PR9APY` STRING,
    `PR0APY` STRING,
    `APYBAL` DECIMAL(38,10),
    `P2LEAD` STRING,
    `P2CLSA` STRING,
    `P2APYT` STRING,
    `P2APYC` STRING,
    `P2FNDA` STRING,
    `P2FNDT` STRING,
    `P2100K` STRING,
    `P2100T` STRING,
    `P2CALL` STRING,
    `P2OKAR` STRING,
    `P2OINS` STRING,
    `P2BIF` STRING,
    `P2SAIF` STRING,
    `P2FDIC` STRING,
    `P2DLYD` STRING,
    `P2RSCH` STRING,
    `P2DORMD` STRING,
    `P2DORR_CS` STRING,
    `P2DORRN` STRING,
    `P2RNAG` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_cdpar2 IS
'The JH CD parameter landing table captures certificate of deposit reference and configuration attributes for CD product validation, classification, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_cdpar2;

INSERT INTO landing_jh.default.jh_cdpar2 (
    `P2BRNO`, `P2REGN`, `P2XRFNBR`, `PTYPE`, `PDESC`, `PGROUP`,
    `PGRPDS`, `P2COST`, `P2PROD`, `P2IQNM`, `PCTERM`, `PCCODE`,
    `PITERM`, `PICODE`, `PMETHD`, `PYRCOD`, `PEVENC`, `PRATE`,
    `PRATEM`, `PRATE_CS`, `PBLRT2`, `PRAT2_CS`, `PBLRT3`, `PRAT3_CS`,
    `PBLRT4`, `PRAT4_CS`, `PBLRT5`, `PRAT5_CS`, `PBLRT6`, `PRAT6_CS`,
    `PBLRT7`, `PRAT7_CS`, `PBLRT8`, `PRAT8_CS`, `PBLRT9`, `PRAT9_CS`,
    `PBLRT0`, `PRAT0_CS`, `SPLTAC`, `PRENEW`, `PRNRT1`, `PRNBL2`,
    `PRNRT2`, `PRNBL3`, `PRNRT3`, `PRNBL4`, `PRNRT4`, `PRNBL5`,
    `PRNRT5`, `PRNBL6`, `PRNRT6`, `PRNBL7`, `PRNRT7`, `PRNBL8`,
    `PRNRT8`, `PRNBL9`, `PRNRT9`, `PRNBL0`, `PRNRT0`, `PRNNOT`,
    `PRNGRC`, `PB4RNW`, `PB4MAT`, `P2ESCH`, `PIRATY`, `PIDISP`,
    `PCOMCK`, `PPENTY`, `PPEN59`, `PWHCOD`, `PINCLU`, `PHMAIL`,
    `PMATCO`, `PSTMTC`, `PALMTY`, `PPAPLE`, `PPALAS`, `PRATSC`,
    `PALNXT`, `PSTMPA`, `PSIC1`, `PSIC2`, `PSIC3`, `PSIC4`,
    `PEXDAY`, `PMLDRT`, `PFLCOD`, `P2STMD`, `P2MNDW`, `P2PAPY`,
    `PVRAPY`, `PV2APY`, `PV3APY`, `PV4APY`, `PV5APY`, `PV6APY`,
    `PV7APY`, `PV8APY`, `PV9APY`, `PV0APY`, `PRNAPY`, `PR2APY`,
    `PR3APY`, `PR4APY`, `PR5APY`, `PR6APY`, `PR7APY`, `PR8APY`,
    `PR9APY`, `PR0APY`, `APYBAL`, `P2LEAD`, `P2CLSA`, `P2APYT`,
    `P2APYC`, `P2FNDA`, `P2FNDT`, `P2100K`, `P2100T`, `P2CALL`,
    `P2OKAR`, `P2OINS`, `P2BIF`, `P2SAIF`, `P2FDIC`, `P2DLYD`,
    `P2RSCH`, `P2DORMD`, `P2DORR_CS`, `P2DORRN`, `P2RNAG`, `AsOfDate`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `P2BRNO`,
    concat('P2REGN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2REGN`,
    idx AS `P2XRFNBR`,
    concat('PTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTYPE`,
    concat('PDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDESC`,
    concat('PGROUP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGROUP`,
    concat('PGRPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGRPDS`,
    concat('P2COST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2COST`,
    concat('P2PROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PROD`,
    concat('P2IQNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IQNM`,
    concat('PCTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCTERM`,
    concat('PCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCCODE`,
    concat('PITERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PITERM`,
    concat('PICODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PICODE`,
    concat('PMETHD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMETHD`,
    concat('PYRCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PYRCOD`,
    concat('PEVENC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PEVENC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRATE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRATEM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRATE_CS`,
    concat('PBLRT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT2`,
    concat('PRAT2_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT2_CS`,
    concat('PBLRT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT3`,
    concat('PRAT3_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT3_CS`,
    concat('PBLRT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT4`,
    concat('PRAT4_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT4_CS`,
    concat('PBLRT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT5`,
    concat('PRAT5_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT5_CS`,
    concat('PBLRT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT6`,
    concat('PRAT6_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT6_CS`,
    concat('PBLRT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT7`,
    concat('PRAT7_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT7_CS`,
    concat('PBLRT8_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT8`,
    concat('PRAT8_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT8_CS`,
    concat('PBLRT9_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT9`,
    concat('PRAT9_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT9_CS`,
    concat('PBLRT0_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLRT0`,
    concat('PRAT0_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRAT0_CS`,
    concat('SPLTAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `SPLTAC`,
    concat('PRENEW_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRENEW`,
    concat('PRNRT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT1`,
    concat('PRNBL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL2`,
    concat('PRNRT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT2`,
    concat('PRNBL3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL3`,
    concat('PRNRT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT3`,
    concat('PRNBL4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL4`,
    concat('PRNRT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT4`,
    concat('PRNBL5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL5`,
    concat('PRNRT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT5`,
    concat('PRNBL6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL6`,
    concat('PRNRT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT6`,
    concat('PRNBL7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL7`,
    concat('PRNRT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT7`,
    concat('PRNBL8_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL8`,
    concat('PRNRT8_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT8`,
    concat('PRNBL9_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL9`,
    concat('PRNRT9_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT9`,
    concat('PRNBL0_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNBL0`,
    concat('PRNRT0_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNRT0`,
    concat('PRNNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNNOT`,
    concat('PRNGRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNGRC`,
    concat('PB4RNW_', lpad(CAST(idx AS STRING), 2, '0')) AS `PB4RNW`,
    concat('PB4MAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PB4MAT`,
    concat('P2ESCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ESCH`,
    concat('PIRATY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIRATY`,
    concat('PIDISP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIDISP`,
    concat('PCOMCK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOMCK`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PPENTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PPEN59`,
    concat('PWHCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PWHCOD`,
    concat('PINCLU_', lpad(CAST(idx AS STRING), 2, '0')) AS `PINCLU`,
    concat('PHMAIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHMAIL`,
    concat('PMATCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMATCO`,
    concat('PSTMTC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTMTC`,
    concat('PALMTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALMTY`,
    concat('PPAPLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPAPLE`,
    concat('PPALAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPALAS`,
    concat('PRATSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRATSC`,
    concat('PALNXT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALNXT`,
    concat('PSTMPA_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTMPA`,
    concat('PSIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSIC1`,
    concat('PSIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSIC2`,
    concat('PSIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSIC3`,
    concat('PSIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSIC4`,
    concat('PEXDAY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PEXDAY`,
    concat('PMLDRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMLDRT`,
    concat('PFLCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PFLCOD`,
    concat('P2STMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMD`,
    concat('P2MNDW_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MNDW`,
    concat('P2PAPY_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PAPY`,
    concat('PVRAPY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PVRAPY`,
    concat('PV2APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV2APY`,
    concat('PV3APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV3APY`,
    concat('PV4APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV4APY`,
    concat('PV5APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV5APY`,
    concat('PV6APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV6APY`,
    concat('PV7APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV7APY`,
    concat('PV8APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV8APY`,
    concat('PV9APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV9APY`,
    concat('PV0APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PV0APY`,
    concat('PRNAPY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNAPY`,
    concat('PR2APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR2APY`,
    concat('PR3APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR3APY`,
    concat('PR4APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR4APY`,
    concat('PR5APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR5APY`,
    concat('PR6APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR6APY`,
    concat('PR7APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR7APY`,
    concat('PR8APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR8APY`,
    concat('PR9APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR9APY`,
    concat('PR0APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR0APY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `APYBAL`,
    concat('P2LEAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LEAD`,
    concat('P2CLSA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLSA`,
    concat('P2APYT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2APYT`,
    concat('P2APYC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2APYC`,
    concat('P2FNDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FNDA`,
    concat('P2FNDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FNDT`,
    concat('P2100K_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2100K`,
    concat('P2100T_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2100T`,
    concat('P2CALL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CALL`,
    concat('P2OKAR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OKAR`,
    concat('P2OINS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OINS`,
    concat('P2BIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2BIF`,
    concat('P2SAIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SAIF`,
    concat('P2FDIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FDIC`,
    concat('P2DLYD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DLYD`,
    concat('P2RSCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RSCH`,
    concat('P2DORMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DORMD`,
    concat('P2DORR_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DORR_CS`,
    concat('P2DORRN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DORRN`,
    concat('P2RNAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RNAG`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_cdpar2' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_cdpar2;
