-- NAME: BRONZE_PERSHING_GTDE_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: July 14, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
        TRANSACTION_CODE
        ,RECORD_INDICATOR_VALUE
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,IBD_NUMBER
        ,PERSHING_INTERNAL_ORDER_REFERENCE_NUMBER
        ,PERSHING_INTERNAL_TRADE_REFERENCE_NUMBER
        ,CONVERT(INT, PERSHING_INTERNAL_VERSION) AS PERSHING_INTERNAL_VERSION
        ,IBD_ID
        ,UNIQUE_ORDER_ID
        ,ALLOCATION_BLOCK_ID
        ,EXTERNAL_REFERENCE_NUMBER
        ,BLOCK_TRADE_ID
        ,PS_REFERENCE_NUMBER
        ,TRADE_AREA_ID
        ,CASE
            WHEN TRADE_DATE = '00000000' THEN NULL
            WHEN TRADE_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, TRADE_DATE , 121)
        END AS TRADE_DATE
        ,CONVERT(INT, EXECUTION_TIME) AS EXECUTION_TIME
        ,CASE
            WHEN SETTLEMENT_DATE = '00000000' THEN NULL
            WHEN SETTLEMENT_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, SETTLEMENT_DATE, 121)
        END AS SETTLEMENT_DATE
        ,CASE
            WHEN PROCESS_DATE = '00000000' THEN NULL
            WHEN PROCESS_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, PROCESS_DATE , 121)
        END AS PROCESS_DATE
        ,BUY_SELL_CODE
        ,CUSIP_NUMBER
        ,INTERNATIONAL_SECURITY_IDENTIFIER_TYPE
        ,INTERNATIONAL_SECURITY_IDENTIFIER_ENTERED_ON_TRANSACTION
        ,SECURITY_SYMBOL
        ,CASE
            WHEN RTRIM(LTRIM(ORDER_QUANTITY)) = '.'
                THEN NULL
            WHEN RTRIM(LTRIM(ORDER_QUANTITY)) LIKE '%E%'
                THEN CONVERT(DECIMAL(20,5), CONVERT(FLOAT, ORDER_QUANTITY))
            ELSE CONVERT(DECIMAL(20,5), ORDER_QUANTITY)
        END AS ORDER_QUANTITY
        ,CONVERT(BIGINT, PRICING_GROUP_QUANTITY) AS PRICING_GROUP_QUANTITY
        ,MARKET_CODE
        ,MARKET_MNEMONIC_CODE
        ,BLOTTER_CODE
        ,SETTLEMENT_LOCATION_CODE
        ,COUNTER_PARTY
        ,CANCEL_CODE
        ,CORRECTION_CODE
        ,OPEN_CLOSE_INDICATOR_FOR_OPTIONS
        ,TYPE_OF_ORDER
        ,DISCRETION_EXERCISED
        ,SOLICITED_INDICATOR
        ,FX_FORWARD
        ,USER_ID
        ,SOURCE_OF_INPUT
        ,NTF
        ,ORDER_TERMINAL_ID
        ,CONVERT(INT, ORDER_SEQUENCE_NUMBER) AS ORDER_SEQUENCE_NUMBER
        ,CAPACITY_CODE
        ,ACCOUNT_TYPE_INDICATOR
        ,RISKLESS_PRINCIPAL_INDICATOR
        ,TRACE_TREASURE_ISSUED_INDICATOR
        ,SHORT_TRADE
        ,SYNDICATE_INDICATOR
        ,ODD_LOT_CODE
        ,MUTUAL_FUND_VALUES
        ,SPREAD_STRADDLE_INDICATOR
        ,BATCH_CODE
        ,INVESTMENT_MANAGER_CODE
        ,DOLLAR_ROLL_INDICATOR
        ,HEDGED_TRANSACTION_INDICATOR
        ,OFFSET_ACCOUNT
        ,EXECUTING_BROKER
        ,MAJOR_BROKERAGE_BADGE_NUMBER
        ,CONTRA_BROKER
        ,MINOR_BROKERAGE_BADGE_NUMBER
        ,TRADER_INITIALS
        ,STEP_IN_OUT_INDICATOR
        ,EXECUTION_TERMINAL
        ,EXECUTION_SEQUENCE_NUMBER
        ,PRIME_BROKER_INDICATOR
        ,COUNTRY_OF_CITIZENSHIP
        ,COUNTRY_STATE_OF_RESIDENCE
        ,WITHHOLDING_CODE_TAX_EXEMPT_INDICATOR
        ,BASE_CURRENCY
        ,CASE
            WHEN RTRIM(LTRIM(BASE_CURRENCY_EXCHANGE_RATE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(20,9), BASE_CURRENCY_EXCHANGE_RATE)
        END AS BASE_CURRENCY_EXCHANGE_RATE
        ,BASE_CURRENCY_MULTIPLE_DIVIDE_CODE
        ,PRIMARY_EXECUTION_IP
        ,IP_2_OVERRIDE
        ,CASE
            WHEN RTRIM(LTRIM(IP_2_PERCENTAGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(20,9), IP_2_PERCENTAGE)
        END AS IP_2_PERCENTAGE
        ,IP_3_OVERRIDE
        ,CASE
            WHEN RTRIM(LTRIM(IP_3_PERCENTAGE)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(20,9), IP_3_PERCENTAGE)
        END AS IP_3_PERCENTAGE
        ,SECURITY_TYPE_CODE
        ,SECURITY_MODIFIER_CODE
        ,SECURITY_CALCULATION_CODE
        ,MINOR_PRODUCT_CODE
        ,ASSET_TYPE
        ,ASSET_SUBTYPE
        ,ASSET_SUB_SUBTYPE
        ,INTERNATIONAL_EXCHANGE_CODE
        ,UNDERLYING_CUSIP
        ,CASE
            WHEN RTRIM(LTRIM(STRIKE_PRICE_01)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(20,9), STRIKE_PRICE_01)
        END AS STRIKE_PRICE_01
        ,CASE
            WHEN RTRIM(LTRIM(POOL_FACTOR)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(17,12), POOL_FACTOR)
        END AS POOL_FACTOR
        ,NON_US_SECURITY_INDICATOR
        ,CNS_ELIGIBILITY
        ,DTC_ELIGIBILITY
        ,BUY_IN_TRADE_EXECUTION_INDICATOR
        ,CASE
            WHEN EX_DIVIDEND_DATE = '00000000' THEN NULL
            WHEN EX_DIVIDEND_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, EX_DIVIDEND_DATE , 121)
        END AS EX_DIVIDEND_DATE
        ,CASE
            WHEN RECORD_DATE = '00000000' THEN NULL
            WHEN RECORD_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, RECORD_DATE , 121)
        END AS RECORD_DATE
        ,CONVERT(INT, NUMBER_OF_DESCRIPTION_LINES) AS NUMBER_OF_DESCRIPTION_LINES
        ,DESCRIPTION_LINE_1
        ,DESCRIPTION_LINE_2
        ,DESCRIPTION_LINE_3
        ,DESCRIPTION_LINE_4
        ,DESCRIPTION_LINE_5
        ,DESCRIPTION_LINE_6
        ,LEGEND_CODE_1
        ,LEGEND_CODE_2
        ,LEGEND_CODE_ONE
        ,LEGEND_CODE_TWO
        ,LEGEND_CODE_THREE
        ,LEGEND_CODE_FOUR
        ,LEGEND_CODE_FIVE
        ,LEGEND_CODE_SIX
        ,TRAILER_LINE_ONE
        ,TRAILER_LINE_TWO
        ,TRAILER_LINE_THREE
        ,TRAILER_LINE_FOUR
        ,TRAILER_LINE_FIVE
        ,TRAILER_LINE_SIX
        ,TRAILER_LINE_SEVEN
        ,TRAILER_LINE_EIGHT
        ,TRAILER_LINE_NINE
        ,MIPS_COMMENT_1
        ,MIPS_COMMENT_2
        ,SOURCE_INITIAL_FUNDS_PURCHASE_ID
        ,MIPS_SOURCE_OF_FUNDS
        ,MIPS_COMMENT_3
        ,OPTION_ROOT_ID
        ,CASE WHEN EXPIRATION_DATE IS NOT NULL THEN CONVERT(DATE, CONCAT('20',EXPIRATION_DATE))
              ELSE EXPIRATION_DATE
        END AS EXPIRATION_DATE
        ,CALL_PUT_INDICATOR
        ,CASE
            WHEN RTRIM(LTRIM(STRIKE_PRICE_02)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(10,3), STRIKE_PRICE_02)
        END AS STRIKE_PRICE_02
        ,MBS_MPID
        ,BUNCHED_TRADE_INDICATOR
        ,CONFIRM_PRINT_INDICATOR
        ,INTERNATIONAL_NON_DOLLAR_SYMBOL
        ,CMTA_INDICATOR
        ,CMTA_BROKER_NUMBER
        ,CONFIRMATION_CODE_ONE
        ,CONFIRMATION_CODE_TWO
        ,CONFIRMATION_CODE_THREE
        ,CONFIRMATION_CODE_FOUR
        ,CASE
            WHEN RTRIM(LTRIM(PMP)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(20,9), PMP)
        END AS PMP
        ,CASE
            WHEN RTRIM(LTRIM(TOTAL_AMOUNT_OF_MARK)) = '.' THEN NULL
            WHEN TOTAL_AMOUNT_OF_MARK IS NULL THEN NULL
            ELSE CONVERT(DECIMAL(20,2), TOTAL_AMOUNT_OF_MARK)
        END AS TOTAL_AMOUNT_OF_MARK
        ,CASE
            WHEN RTRIM(LTRIM(PREVAILING_MARKET_PRICE_PERCENT)) = '.' THEN NULL
            ELSE CONVERT(DECIMAL(11,5), PREVAILING_MARKET_PRICE_PERCENT)
        END AS PREVAILING_MARKET_PRICE_PERCENT
        ,CASE
            WHEN EXPANDED_EXECUTION_TIME IS NULL THEN NULL
            ELSE CONVERT(BIGINT, EXPANDED_EXECUTION_TIME)
        END AS EXPANDED_EXECUTION_TIME
        ,ERROR_ACCOUNT_NUMBER
        ,TRADE_PROCESSING_TIME_STAMP
        ,SOURCE_OF_FUNDS
        ,M2I_INDICATOR
        ,M2I_CONFIRM_NUMBER
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
        ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_GTDE_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data