-- NAME: BRONZE_PERSHING_CAPS_REC_1
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 25, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
    SELECT DISTINCT
        INTRODUCING_BROKER_DEALER_IBD_NUMBER
        ,RECORD_ID
        ,CASE
            WHEN TRADE_DATE = '00000000' THEN NULL
            WHEN TRADE_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, TRADE_DATE, 121)
        END AS TRADE_DATE
        ,TRADE_REFERENCE_NUMBER
        ,PERSHING_OFFICE_NUMBER
        ,ACCOUNT_NUMBER
        ,ACCOUNT_NAME
        ,BUY_SELL_INDICATOR
        ,CANCEL_INDICATOR
        ,CAPS_SOURCE
        ,CASE
            WHEN RIGHT(TRADE_QUANTITY,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(14,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TRADE_QUANTITY,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(TRADE_QUANTITY,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(14,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TRADE_QUANTITY,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(14,4), TRADE_QUANTITY)
         END TRADE_QUANTITY
        ,CASE
            WHEN RIGHT(PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(14,7),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(14,7),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(14,7), PRICE)
         END PRICE
        ,PRODUCT_CODE
        ,CUSIP_NUMBER_OF_SECURITY_TRADED
        ,ACCOUNT_SHORT_NAME
        ,ORDER_TYPE
        ,CASE
            WHEN RIGHT(MISCELLANEOUS_FEE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MISCELLANEOUS_FEE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(MISCELLANEOUS_FEE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(MISCELLANEOUS_FEE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(14,2), MISCELLANEOUS_FEE)
         END MISCELLANEOUS_FEE
        ,RECORD_ID_SEQUENCE_NUMBER
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_CAPS_1") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data