-- NAME: BRONZE_PERSHING_CAPS_REC_3
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 25, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
    SELECT DISTINCT
        INTRODUCING_BROKER_DEALER_IBD_NUMBER
        ,RECORD_ID
        ,AS_OF_TRADE_INDICATOR
        ,DISTRIBUTION_INDICATOR
        ,EXPLODE_INDICATOR
        ,REVENUE_TYPE
        ,LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER
        ,INVESTMENT_PROFESSIONAL_CAPS_REVENUE_CENTER
        ,INVESTMENT_PROFESSIONAL_CAPS_OFFICE_NUMBER
        ,CASE
            WHEN RIGHT(INVESTMENT_PROFESSIONAL_SPLIT_PERCENT,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(7,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INVESTMENT_PROFESSIONAL_SPLIT_PERCENT,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(INVESTMENT_PROFESSIONAL_SPLIT_PERCENT,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(7,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(INVESTMENT_PROFESSIONAL_SPLIT_PERCENT,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(7,3), INVESTMENT_PROFESSIONAL_SPLIT_PERCENT)
         END INVESTMENT_PROFESSIONAL_SPLIT_PERCENT
        ,CASE
            WHEN RIGHT(TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(14,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(14,2), TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP)
         END TOTAL_AMOUNT_OF_REVENUE_GENERATED_AND_CREDITED_TO_IP
        ,CASE
            WHEN RIGHT(PERSHING_CHARGE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PERSHING_CHARGE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(PERSHING_CHARGE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PERSHING_CHARGE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(12,2), PERSHING_CHARGE)
         END PERSHING_CHARGE
        ,LEGACY_FROM_INVESTMENT_PROFESSIONAL_NUMBER
        ,CAPS_REVENUE_CENTER_ASSOCIATED_WITH_IP
        ,CAPS_OFFICE_NUMBER_ASSOCIATED_WITH_IP
        ,CASE
            WHEN RIGHT(TOTAL_ORDER_COMMISSION,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TOTAL_ORDER_COMMISSION,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(TOTAL_ORDER_COMMISSION,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(TOTAL_ORDER_COMMISSION,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(12,2), TOTAL_ORDER_COMMISSION)
         END TOTAL_ORDER_COMMISSION
        ,SPREAD_STRADDLE_MUTUAL_FUND_VALUES
        ,CORRECTION_CODE
        ,SECURITY_MODIFIER
        ,SECURITY_CALCULATION_CODE
        ,CASE
            WHEN RIGHT(PRINCIPAL,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PRINCIPAL,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(PRINCIPAL,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PRINCIPAL,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(12,2), PRINCIPAL)
         END PRINCIPAL
        ,CRD_NUMBER
        ,SOURCE_OF_INPUT
        ,CASE
            WHEN RIGHT(SERVICE_CHARGE_OTHER_FEE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SERVICE_CHARGE_OTHER_FEE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(SERVICE_CHARGE_OTHER_FEE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(12,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(SERVICE_CHARGE_OTHER_FEE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
            ELSE CONVERT(DECIMAL(12,2), SERVICE_CHARGE_OTHER_FEE)
         END SERVICE_CHARGE_OTHER_FEE
        ,RECORD_ID_SEQUENCE_NUMBER
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_CAPS_3") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data