-- NAME: BRONZE_PERSHING_ISCA_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: January 06, 2026

{{
   config(
	      materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT DISTINCT
	    RECORD_INDICATOR_VALUE,
	    CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER,
        CUSIP_NUMBER,
        SECURITY_TYPE,
        SECURITY_MODIFIER,
        SECURITY_CALCULATION_CODE,
        PRIMARY_EXCHANGE,
        CASE
            WHEN RIGHT(COUPON_RATE_OR_INDICATED_DIVIDEND,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(COUPON_RATE_OR_INDICATED_DIVIDEND,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(COUPON_RATE_OR_INDICATED_DIVIDEND,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(COUPON_RATE_OR_INDICATED_DIVIDEND,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
	    END COUPON_RATE_OR_INDICATED_DIVIDEND,
        CONVERT(INT, MATURITY_OPTION_EXPIRE_DATE) MATURITY_OPTION_EXPIRE_DATE,
        UNDERLYING_SECURITY_CUSIP,
        CASE
            WHEN RIGHT(FIRST_CALL_PRICE_OR_STRIKE_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(11,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FIRST_CALL_PRICE_OR_STRIKE_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(FIRST_CALL_PRICE_OR_STRIKE_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(11,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FIRST_CALL_PRICE_OR_STRIKE_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END FIRST_CALL_PRICE_OR_STRIKE_PRICE,
        CASE
            WHEN RIGHT(FIRST_PAR_CALL_PRICE_OR_UNITS,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(11,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FIRST_PAR_CALL_PRICE_OR_UNITS,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(FIRST_PAR_CALL_PRICE_OR_UNITS,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(11,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(FIRST_PAR_CALL_PRICE_OR_UNITS,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END FIRST_PAR_CALL_PRICE_OR_UNITS,
        PRIMARY_SYMBOL,
        INTEREST_FREQUENCY,
        BOND_CLASS,
        FIRST_COUPON_DAY,
        CALL_INDICATOR,
        PUT_INDICATOR,
        CONVERT(INT, NEXT_PAR_CALL_DATE) NEXT_PAR_CALL_DATE,
        CONVERT(INT, PREREFUNDED_DATE) PREREFUNDED_DATE,
        CONVERT(INT, NEXT_PREMIUM_CALL_DATE) NEXT_PREMIUM_CALL_DATE,
        CONVERT(INT, DATED_DATE_OR_EX_DIVIDEND_DATE) DATED_DATE_OR_EX_DIVIDEND_DATE,
        CONVERT(INT, FIRST_COUPON_OR_PAYABLE_DATE) FIRST_COUPON_OR_PAYABLE_DATE,
        FEDERAL_MARGINABLE_INDICATOR,
        CNS_ELIGIBLE_CODE,
        DTCC_ELIGIBLE_CODE,
        NSCC_ELIGIBLE_CODE,
        FOREIGN_SECURITY,
        SECOND_COUPON_DAY,
        DIVIDEND_INTEREST_PAYMENT_METHOD,
        MINOR_PRODUCT_CODE,
	    CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA,
	    YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_ISCA_A") }}
    {% if is_incremental() %}
		WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data