-- NAME: BRONZE_PERSHING_CKFF_REC_D
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 12, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
	SELECT DISTINCT
		TRANSACTION_CODE
		,RECORD_TYPE
		,RECORD_ID_SEQUENCE_NUMBER
		,ACCOUNT_NUMBER
		,CONVERT(DECIMAL(18,2), TRANSACTION_AMOUNT) AS TRANSACTION_AMOUNT
		,LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_1
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_2
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_3
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_4
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_5
		,ULTIMATE_BENEFICIARY_INFORMATION_LINE_6
		,BANK_NAME
		,ORD_INST_INFO_1_OR_DESC_TRAN_ADD_INFO_1
		,ORD_INST_INFO_2_OR_ABA_NUMBER_ADD_INFO_2
		,ORD_INST_INFO_3_OR_DDA_NUMBER_ADD_INFO_3
		,ORD_INST_INFO_4_OR_ADD_INFO_4
		,ORD_INST_INFO_5_OR_ADD_INFO_5
		,ORD_INST_INFO_6_OR_ADD_INFO_6
		,ORD_INST_INFO_7_OR_ADD_INFO_7
		,ORD_INST_INFO_8_OR_ADD_INFO_8
		,ORD_INST_INFO_9_OR_ADD_INFO_9
		,INCOMING_WIRE_INDICATOR
		,TRANSACTION_IDENTIFIER
		,EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER
		,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
		,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
		,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
		,DATE_OF_DATA
		,YEARMONTH
	FROM {{ source("pershing", "PERSHING_CKFF_D") }}
	{% if is_incremental() %}
		WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data