-- NAME: BRONZE_PERSHING_ACCT_REC_B
-- CATEGORY: MODEL
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: April 10, 2026

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
	SELECT 
		TRANSACTION_CODE,
		RECORD_INDICATOR_VALUE,
		CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER,
		ACCOUNT_NUMBER,
		INTRODUCING_BROKER_DEALER_IBD_NUMBER,
		INVESTMENT_PROFESSIONAL_IP_NUMBER,
		ACCOUNT_SHORT_NAME,
        TAX_ID_TYPE,
        TAX_ID_NUMBER,
        DATE_TAX_ID_APPLIED_FOR,
        W_8_W_9_INDICATOR,
		CASE
			WHEN W8_W_9_DATE_SIGNED = '00000000' THEN NULL
			WHEN W8_W_9_DATE_SIGNED IS NULL THEN NULL
			ELSE CONVERT(DATE,W8_W_9_DATE_SIGNED , 121)
		END AS W8_W_9_DATE_SIGNED,
		CASE
			WHEN W_8_W_9_EFFECTIVE_RECEIVED_DATE = '00000000' THEN NULL
			WHEN W_8_W_9_EFFECTIVE_RECEIVED_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE,W_8_W_9_EFFECTIVE_RECEIVED_DATE , 121)
		END AS W_8_W_9_EFFECTIVE_RECEIVED_DATE,
        W_8_W_9_DOCUMENT_TYPE,
        TAX_STATUS,
        B_NOTICE_REASON_CODE,
        FIRST_B_NOTICE_STATUS,
		CASE
			WHEN DATE_FIRST_B_NOTICE_STATUS_ISSUED_ENFORCED = '00000000' THEN NULL
			WHEN DATE_FIRST_B_NOTICE_STATUS_ISSUED_ENFORCED IS NULL THEN NULL
			ELSE CONVERT(DATE,DATE_FIRST_B_NOTICE_STATUS_ISSUED_ENFORCED, 121)
		END AS DATE_FIRST_B_NOTICE_STATUS_ISSUED_ENFORCED,
		CASE
			WHEN DATE_FIRST_B_NOTICE_STATUS_SATISFIED = '00000000' THEN NULL
			WHEN DATE_FIRST_B_NOTICE_STATUS_SATISFIED IS NULL THEN NULL
			ELSE CONVERT(DATE,DATE_FIRST_B_NOTICE_STATUS_SATISFIED, 121)
		END AS DATE_FIRST_B_NOTICE_STATUS_SATISFIED,
        SECOND_B_NOTICE_STATUS,
		CASE
			WHEN DATE_SECOND_B_NOTICE_STATUS_ISSUED_ENFORCED = '00000000' THEN NULL
			WHEN DATE_SECOND_B_NOTICE_STATUS_ISSUED_ENFORCED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_SECOND_B_NOTICE_STATUS_ISSUED_ENFORCED, 121)
		END AS DATE_SECOND_B_NOTICE_STATUS_ISSUED_ENFORCED,
		CASE
			WHEN DATE_SECOND_B_NOTICE_STATUS_SATISFIED = '00000000' THEN NULL
			WHEN DATE_SECOND_B_NOTICE_STATUS_SATISFIED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_SECOND_B_NOTICE_STATUS_SATISFIED, 121)
		END AS DATE_SECOND_B_NOTICE_STATUS_SATISFIED,
        C_NOTICE_STATUS,
		CASE
			WHEN DATE_C_NOTICE_STATUS_ISSUED_ENFORCED = '00000000' THEN NULL
			WHEN DATE_C_NOTICE_STATUS_ISSUED_ENFORCED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_C_NOTICE_STATUS_ISSUED_ENFORCED, 121)
		END AS DATE_C_NOTICE_STATUS_ISSUED_ENFORCED,
		CASE
			WHEN DATE_C_NOTICE_STATUS_SATISFIED = '00000000' THEN NULL
			WHEN DATE_C_NOTICE_STATUS_SATISFIED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_C_NOTICE_STATUS_SATISFIED, 121)
		END AS DATE_C_NOTICE_STATUS_SATISFIED,
        OLD_ACCOUNT_NUMBER,
		CASE
			WHEN ORIGINAL_ACCOUNT_OPEN_DATE = '00000000' THEN NULL
			WHEN ORIGINAL_ACCOUNT_OPEN_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, ORIGINAL_ACCOUNT_OPEN_DATE, 121)
		END AS ORIGINAL_ACCOUNT_OPEN_DATE,
        UNIDENTIFIED_LARGE_TRADER_ID,
        LARGE_TRADER_TYPE_CODE,
		CASE
			WHEN LARGE_TRADER_TYPE_LAST_CHANGE_DATE = '00000000' THEN NULL
			WHEN LARGE_TRADER_TYPE_LAST_CHANGE_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, LARGE_TRADER_TYPE_LAST_CHANGE_DATE, 121)
		END AS LARGE_TRADER_TYPE_LAST_CHANGE_DATE,
        INITIAL_SOURCE_OF_FUNDS,
		CASE
			WHEN ACCOUNT_FUNDING_DATE = '00000000' THEN NULL
			WHEN ACCOUNT_FUNDING_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, ACCOUNT_FUNDING_DATE, 121)
		END AS ACCOUNT_FUNDING_DATE,
        REGULATORY_BLOCK_INDICATOR,
        STATEMENT_CURRENCY_CODE,
        FUTURE_STATEMENT_CURRENCY_CODE,
		CASE
			WHEN FUTURE_STATEMENT_CURRENCY_CODE_DATE = '00000000' THEN NULL
			WHEN FUTURE_STATEMENT_CURRENCY_CODE_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, FUTURE_STATEMENT_CURRENCY_CODE_DATE, 121)
		END AS FUTURE_STATEMENT_CURRENCY_CODE_DATE,
        ACCOUNT_LEVEL_ROUTING_CODE,
        SELF_DIRECTED_INDICATOR,
        DIGITAL_ADVICE_INDICATOR,
        PROHIBITED_TRANSACTON_EXEMPTION_PTE_86_128_ACCOUNT_INDICATOR,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_1,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_2,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_3,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_4,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_5,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_6,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_7,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_8,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_9,
        LEGACY_FIRST_INVESTMENT_PROFESSIONAL_IP_NUMBER_10,
        ALERT_IM_ACRONYM,
        ALERT_IM_ACCESS_CODE,
        BROKER_ACRONYM,
        CROSS_REFERENCED_INDICATOR,
        BNY_TRUST_INDICATOR,
        SOURCE_OF_ASSETS_AT_ACCOUNT_OPENING,
        COMMISSION_DISCOUNT_CODE,
        EXTERNAL_ACCOUNT_NUMBER,
        CONFIRMATION_SUPPRESSION_INDICATOR,
		CASE
			WHEN DATE_LAST_BOOKS_RECORDS_MAILING_SENT_TO = '000000' THEN NULL
			WHEN DATE_LAST_BOOKS_RECORDS_MAILING_SENT_TO IS NULL THEN NULL
			ELSE DATE_LAST_BOOKS_RECORDS_MAILING_SENT_TO
		END AS DATE_LAST_BOOKS_RECORDS_MAILING_SENT_TO,
		CASE
			WHEN DATE_LAST_BOOKS_AND_RECORDS_MAILING_SENT_TO_CUSTOMER_OUTSIDE_PERSHING_SYSTEM = '000000' THEN NULL
			WHEN DATE_LAST_BOOKS_AND_RECORDS_MAILING_SENT_TO_CUSTOMER_OUTSIDE_PERSHING_SYSTEM IS NULL THEN NULL
			ELSE DATE_LAST_BOOKS_AND_RECORDS_MAILING_SENT_TO_CUSTOMER_OUTSIDE_PERSHING_SYSTEM
		END AS DATE_LAST_BOOKS_AND_RECORDS_MAILING_SENT_TO_CUSTOMER_OUTSIDE_PERSHING_SYSTEM,
        FULLY_PAID_LENDING_AGREEMENT_INDICATOR,
		CASE
			WHEN FULLY_PAID_LENDING_AGREEMENT_DATE = '00000000' THEN NULL
			WHEN FULLY_PAID_LENDING_AGREEMENT_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, FULLY_PAID_LENDING_AGREEMENT_DATE, 121)
		END AS FULLY_PAID_LENDING_AGREEMENT_DATE,
        CUSTODIAN_ACCOUNT_TYPE,
        MARKETS_IN_FINANCIAL_INSTRUMENTS_DIRECTIVE_MIFID_CUSTOMER_CATEGORIZATION,
        CASH_MANAGEMENT_TRANSACTION_CODE,
        SWEEP_STATUS_INDICATOR,
		CASE
			WHEN DATE_SWEEP_ACTIVATED = '00000000' THEN NULL
			WHEN DATE_SWEEP_ACTIVATED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_SWEEP_ACTIVATED, 121)
		END AS DATE_SWEEP_ACTIVATED,
		CASE
			WHEN DATE_SWEEP_DETAILS_CHANGED = '00000000' THEN NULL
			WHEN DATE_SWEEP_DETAILS_CHANGED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_SWEEP_DETAILS_CHANGED, 121)
		END AS DATE_SWEEP_DETAILS_CHANGED,
        COVER_MARGIN_DEBIT_INDICATOR,
        FIRST_FUND_SWEEP_ACCOUNT_ID,
		CONVERT(
			DECIMAL(18,9),
        	LEFT(FIRST_FUND_SWEEP_ACCOUNT_PERCENT, 9) + '.' + RIGHT(FIRST_FUND_SWEEP_ACCOUNT_PERCENT, 9)
    	) AS FIRST_FUND_SWEEP_ACCOUNT_PERCENT,
        FIRST_FUND_SWEEP_ACCOUNT_REDEMPTION_PRIORITY,
        SECOND_FUND_SWEEP_ACCOUNT_ID,
		CONVERT(
			DECIMAL(18,9),
        	LEFT(SECOND_FUND_SWEEP_ACCOUNT_PERCENT, 9) + '.' + RIGHT(SECOND_FUND_SWEEP_ACCOUNT_PERCENT, 9)
    	) AS SECOND_FUND_SWEEP_ACCOUNT_PERCENT,
        SECOND_FUND_SWEEP_ACCOUNT_REDEMPTION_PRIORITY,
        TYPE_OF_BANK_ACCOUNT,
        BANKLINK_ABA_NUMBER,
        BANKLINK_DDA_NUMBER,
        FUND_BANK_INDICATOR,
        W_9_CORPORATION_TAX_CLASSIFICATION_CODE,
        COMBINED_MARGIN_ACCOUNT_INDICATOR,
        PLEDGE_COLLATERAL_ACCOUNT_INDICATOR,
        FINRA_INSTITUTIONAL_ACCOUNT_CODE,
        PROPOSED_ACCOUNT_REFERENCE_ID,
        ADVISOR_MODEL_ID,
        FIRM_MODEL_STYLE_ID,
        THIRD_PARTY_LENDER_INDICATOR,
        RESERVED_FOR_FUTURE_THIRD_PARTY_LENDER_GROWTH,
        DVP_RESTRICTION_CODE,
		CASE
			WHEN DVP_RESTRICTION_EXPIRATION_DATE = '00000000' THEN NULL
			WHEN DVP_RESTRICTION_EXPIRATION_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, DVP_RESTRICTION_EXPIRATION_DATE, 121)
		END AS DVP_RESTRICTION_EXPIRATION_DATE,
        ESCHEATMENT_WITHHOLDING_INDICATOR,
        SOURCE_OF_ORIGINATION,
        SOURCE_OF_PERSONA,
        CLIENT_ON_BOARDING_METHOD,
        TAX_FILING_CODE,
        NON_PURPOSE_COLLATERAL_ACCOUNT_INDICATOR,
		SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE,
		SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE,
		NULL AS ACCOUNT_NUMBER_TYPE,
		DATE_OF_DATA,
		YEARMONTH
	FROM  
        {{ source("pershing", "PERSHING_ACCT_B") }}
    {% if is_incremental() %}
    WHERE 
        DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data