-- NAME: BRONZE_PERSHING_ISCA_REC_B
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT DISTINCT
        RECORD_INDICATOR_VALUE
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,CUSIP_NUMBER
        ,NOT_USED
        ,ETF_INDICATOR
        ,CASE
            WHEN RIGHT(BID_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(BID_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(BID_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(BID_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END BID_PRICE
        ,CASE
            WHEN RIGHT(ASK_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ASK_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(ASK_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(ASK_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END ASK_PRICE
        ,CASE
            WHEN RIGHT(PREVIOUS_DAY_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PREVIOUS_DAY_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(PREVIOUS_DAY_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(PREVIOUS_DAY_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END PREVIOUS_DAY_PRICE
        ,CASE
            WHEN RIGHT(LATEST_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LATEST_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(LATEST_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(LATEST_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END LATEST_PRICE
        ,CASE
            WHEN RIGHT(END_OF_MONTH_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(END_OF_MONTH_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
            WHEN RIGHT(END_OF_MONTH_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(END_OF_MONTH_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
        END END_OF_MONTH_PRICE
        ,CONVERT(INT, ROUND_LOT_QUANTITY) AS ROUND_LOT_QUANTITY
        ,DIVIDEND_REINVESTMENT_ELIGIBILITY_INDICATOR
        ,CONVERT(INT, PREVIOUS_PRICE_DATE) AS PREVIOUS_PRICE_DATE
        ,CONVERT(INT, LATEST_PRICE_DATE) AS LATEST_PRICE_DATE
        ,CONVERT(INT, END_OF_MONTH_PRICE_DATE) AS END_OF_MONTH_PRICE_DATE
        ,CONVERT(INT, RECORD_DATE) AS RECORD_DATE
        ,FUNDVEST_INDICATOR
        ,COUNTRY_CODE
        ,STANDARD_AND_POORS_RATING
        ,MOODYS_RATING
        ,BOND_SUB_CLASS
        ,RESTRICTION_INDICATOR
        ,TRACE_INDICATOR
        ,NEW_INTEREST_CALCULATION_CODE
        ,SIC_CODE
        ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
        ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_ISCA_B") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA > COALESCE((SELECT MAX(DATE_OF_DATA) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data