-- NAME: BRONZE_PERSHING_ACA2_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
        CONVERT(VARCHAR(2),TRANSACTION_CODE)                            AS TRANSACTION_CODE
        ,CONVERT(VARCHAR(1),RECORD_INDICATOR_TRANSFER_TYPE)             AS RECORD_INDICATOR_TRANSFER_TYPE
        ,CONVERT(VARCHAR(8),RECORD_ID_SEQUENCE_NUMBER)                  AS RECORD_ID_SEQUENCE_NUMBER
        ,CONVERT(VARCHAR(9),ACCOUNT_NUMBER)                             AS ACCOUNT_NUMBER
        ,CONVERT(VARCHAR(4),INVESTMENT_PROFESSIONAL)                    AS INVESTMENT_PROFESSIONAL
        ,CONVERT(VARCHAR(1),RECORD_TYPE)                                AS RECORD_TYPE
        ,CONVERT(VARCHAR(3),TRANSFER_TYPE)                              AS TRANSFER_TYPE
        ,CONVERT(VARCHAR(3),TRANSFER_STATUS)                            AS TRANSFER_STATUS
        ,CONVERT(varchar(50),NUMBER_OF_DAYS_IN_PERSHING_STATUS)         AS NUMBER_OF_DAYS_IN_PERSHING_STATUS
        ,trim(CONVERT(varchar(4),CONTRA_BROKER_NUMBER))                 AS CONTRA_BROKER_NUMBER
        ,CONVERT(varchar(35),CONTRA_BROKER_NAME)                        AS CONTRA_BROKER_NAME
        ,convert(varchar(35),CONTRA_ACCOUNT_NUMBER)                     AS CONTRA_ACCOUNT_NUMBER
        ,CONVERT(VARCHAR(2),RETIREMENT_ACCOUNT_CLASS_INDICATOR)         AS RETIREMENT_ACCOUNT_CLASS_INDICATOR
        ,CONVERT(INT,REQUEST_CREATION_DATE)                             AS REQUEST_CREATION_DATE
        ,CONVERT(VARCHAR(8),REQUEST_CREATION_USER_ID)                   AS REQUEST_CREATION_USER_ID
        ,CONVERT(INT,LAST_UPDATE_DATE)                                  AS LAST_UPDATE_DATE
        ,CONVERT(VARCHAR(8),LAST_UPDATE_USER_ID)                        AS LAST_UPDATE_USER_ID
        ,CONVERT(DECIMAL(16,2), CAST(TOTAL_MARKET_VALUE_OF_TRANSFER AS FLOAT)) AS TOTAL_MARKET_VALUE_OF_TRANSFER
        ,CONVERT(VARCHAR(1),TOTAL_MARKET_VALUE_SIGN)                    AS TOTAL_MARKET_VALUE_SIGN
        ,CONVERT(VARCHAR(3),SOURCE_CODE)                                AS SOURCE_CODE
        ,CONVERT(DECIMAL(16,2),SPECIAL_MEMORANDUM_ACCOUNT)              AS SPECIAL_MEMORANDUM_ACCOUNT
        ,CONVERT(VARCHAR(1),SPECIAL_MEMORANDUM_ACCOUNT_SIGN)            AS SPECIAL_MEMORANDUM_ACCOUNT_SIGN
        ,CONVERT(VARCHAR(40),CUSTOMER_NAME)                             AS CUSTOMER_NAME
        ,CONVERT(VARCHAR(9),PRIMARY_TAX_IDENTIFICATION_NUMBER)          AS PRIMARY_TAX_IDENTIFICATION_NUMBER
        ,CONVERT(VARCHAR(2),NSCC_ACCOUNT_TYPE)                          AS NSCC_ACCOUNT_TYPE
        ,CONVERT(VARCHAR(3),NSCC_STATUS)                                AS NSCC_STATUS
        ,CONVERT(VARCHAR(50),NUMBER_OF_DAYS_IN_NSCC_STATUS)             AS NUMBER_OF_DAYS_IN_NSCC_STATUS
        ,CONVERT(VARCHAR(14),NSCC_CONTROL_NUMBER)                       AS NSCC_CONTROL_NUMBER
        ,CONVERT(VARCHAR(10),REASON_CODE_FOR_REJECT)                    AS REASON_CODE_FOR_REJECT
        ,CONVERT(VARCHAR(250),REASON_COMMENTS)                          AS REASON_COMMENTS
        ,CONVERT(VARCHAR(20),REQUEST_ID)                                AS REQUEST_ID
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3)                                AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6)                                AS ACCOUNT_NUMBER_BASE
        ,NULL                                                           AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
        ,LOADED_AT
    FROM
        {{ source("pershing", "PERSHING_ACA2_A") }}
),

bronze_data AS (
    SELECT
        TRANSACTION_CODE
        ,RECORD_INDICATOR_TRANSFER_TYPE
        ,RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,INVESTMENT_PROFESSIONAL
        ,RECORD_TYPE
        ,TRANSFER_TYPE
        ,TRANSFER_STATUS
        ,NUMBER_OF_DAYS_IN_PERSHING_STATUS
        ,CONTRA_BROKER_NUMBER
        ,CONTRA_BROKER_NAME
        ,CONTRA_ACCOUNT_NUMBER
        ,RETIREMENT_ACCOUNT_CLASS_INDICATOR
        ,REQUEST_CREATION_DATE
        ,REQUEST_CREATION_USER_ID
        ,LAST_UPDATE_DATE
        ,LAST_UPDATE_USER_ID
        ,TOTAL_MARKET_VALUE_OF_TRANSFER
        ,TOTAL_MARKET_VALUE_SIGN
        ,SOURCE_CODE
        ,SPECIAL_MEMORANDUM_ACCOUNT
        ,SPECIAL_MEMORANDUM_ACCOUNT_SIGN
        ,CUSTOMER_NAME
        ,PRIMARY_TAX_IDENTIFICATION_NUMBER
        ,NSCC_ACCOUNT_TYPE
        ,NSCC_STATUS
        ,NUMBER_OF_DAYS_IN_NSCC_STATUS
        ,NSCC_CONTROL_NUMBER
        ,REASON_CODE_FOR_REJECT
        ,REASON_COMMENTS
        ,REQUEST_ID
        ,ACCOUNT_NUMBER_OFFICE
        ,ACCOUNT_NUMBER_BASE
        ,ACCOUNT_NUMBER_TYPE
        ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
        ,YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT * FROM bronze_data