-- NAME: BRONZE_PERSHING_CKFF_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 12, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
    SELECT DISTINCT
        TRANSACTION_CODE
        ,RECORD_TYPE
        ,RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,CONVERT(DECIMAL(18,2), TRANSACTION_AMOUNT) AS TRANSACTION_AMOUNT
        ,LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER
        ,EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER
        ,INTERMEDIARY_DESCRIPTION_LINE_1
        ,INTERMEDIARY_DESCRIPTION_LINE_2
        ,ACCOUNT_WITH_INSTITUTION
        ,BENEFICIARY_CUSTOMER_1
        ,BENEFICIARY_CUSTOMER_2
        ,BENEFICIARY_CUSTOMER_3
        ,BENEFICIARY_CUSTOMER_4
        ,OUTGOING_WIRES_ADD_INFO1_OR_DESC_TRANSACT
        ,OUTGOING_WIRES_ADD_INFO2_OR_ABA_NUMBER
        ,OUTGOING_WIRES_ADD_INFO3_OR_DDA_NUMBER
        ,OUTGOING_WIRES_ACH_ADD_INFO4
        ,OUTGOING_WIRES_ACH_ADD_INFO5
        ,OUTGOING_WIRES_ACH_ADD_INFO6
        ,OUTGOING_WIRES_ACH_ADD_INFO7
        ,OUTGOING_WIRES_ACH_ADD_INFO8
        ,OUTGOING_WIRES_ACH_ADD_INFO9
        ,DUPLICATE_RECORD_INDICATOR
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_CKFF_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data