-- NAME: BRONZE_PERSHING_GCUS_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT
	    TRANSACTION_CODE
	    ,RECORD_INDICATOR_VALUE
	    ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
	    ,ACCOUNT_NUMBER
	    ,CUSIP_NUMBER
	    ,PORTFOLIO_CURRENCY
	    ,UNDERLYING_CUSIP_NUMBER
	    ,COUNTRY_CODE_SEC_ISSUANCE
	    ,IP
	    ,IBDNUMBER
	    ,CURRENCY_SECURITY_IND
	    ,ISSUE_CURRENCY
	    ,DATE_STAMP_TRADE_DATE
	    ,DATE_STAMP_SETTLEMENT_DATE
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SAFEKEEPING_QTY_MEMO)) AS SAFEKEEPING_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRANSFER_QTY_MEMO)) AS TRANSFER_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, PENDING_TRANSFER_QTY)) AS PENDING_TRANSFER_QTY
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, LEGAL_TRANSFER_QTY)) AS LEGAL_TRANSFER_QTY
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRADE_DATE_QTY)) AS TRADE_DATE_QTY
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SETTLEMENT_DATE_QTY)) AS SETTLEMENT_DATE_QTY
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SEG_QTY_MEMO)) AS SEG_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TENDERED_REORG_QTY_MEMO)) AS TENDERED_REORG_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, PENDING_PAPERS_MEMO)) AS PENDING_PAPERS_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, SHORT_AGAINST_THE_BOX_QTY_MEMO)) AS SHORT_AGAINST_THE_BOX_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, NETWORKED_QTY_MEMO)) AS NETWORKED_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, PENDING_SPLIT_QTY_MEMO)) AS PENDING_SPLIT_QTY_MEMO
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, QTY_COVERING_OPTIONS_OR_COVERED_QTY)) AS QTY_COVERING_OPTIONS_OR_COVERED_QTY
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRADE_DATE_QTY_BOUGHT)) AS TRADE_DATE_QTY_BOUGHT
	    ,CONVERT(DECIMAL(18, 5), CONVERT(FLOAT, TRADE_DATE_QTY_SOLD)) AS TRADE_DATE_QTY_SOLD
	    ,CONVERT(DECIMAL(18, 2), CONVERT(FLOAT, FED_REG_T_REQUIREMENT)) AS FED_REG_T_REQUIREMENT
	    ,CONVERT(DECIMAL(18, 2), CONVERT(FLOAT, HOUSE_PERSHING_MARGIN_REQUIREMENT)) AS HOUSE_PERSHING_MARGIN_REQUIREMENT
	    ,CONVERT(DECIMAL(18, 2), CONVERT(FLOAT, EXCHANGE_NYSE_REQUIREMENT)) AS EXCHANGE_NYSE_REQUIREMENT
	    ,CONVERT(DECIMAL(18, 2), CONVERT(FLOAT, EQUITY_REQUIREMENT)) AS EQUITY_REQUIREMENT
	    ,SECURITY_SYMBOL
	    ,SECURITY_TYPE
	    ,SECURITY_MOD
	    ,SECURITY_CALC
	    ,MINOR_PRODUCT_CODE
	    ,NETWORK_ELIGIBILITY_INDICATOR
	    ,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, STRIKE_PRICE_A)) AS STRIKE_PRICE_A
	    ,EXPIRATION_MATURITY_DATE
	    ,CONVERT(DECIMAL(18,5), CONVERT(FLOAT, CONTRACT_SIZE)) AS CONTRACT_SIZE
	    ,CONVERT(DECIMAL(18,9), CONVERT(FLOAT, CONVERSION_RATIO)) AS CONVERSION_RATIO
	    ,ACCOUNT_SHORT_NAME
	    ,STATE_CODE
	    ,COUNTRY_CODE_ACCT_LVL_CITIZENSHIP
	    ,CONVERT(INT, NUMBER_OF_SECURITY_DESC_LINES) AS NUMBER_OF_SECURITY_DESC_LINES
	    ,SECURITY_DESC_LINE_1
	    ,SECURITY_DESC_LINE_2
	    ,SECURITY_DESC_LINE_3
	    ,SECURITY_DESC_LINE_4
	    ,SECURITY_DESC_LINE_5
	    ,SECURITY_DESC_LINE_6
	    ,DIVIDEND_OPTION
	    ,LONG_TERM_CAPITAL_GAINS_OPTION
	    ,SHORT_TERM_CAPITAL_GAINS_OPTION
	    ,FIRM_TRADING_INDICATOR
	    ,POSITION_CURRENCY
	    ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, TRADE_DATE_LIQUIDATING_VALUE)) AS TRADE_DATE_LIQUIDATING_VALUE
	    ,CONVERT(DECIMAL(10, 8), CONVERT(FLOAT, POOL_FACTOR)) AS POOL_FACTOR
	    ,CONVERT(DECIMAL(18, 10), CONVERT(FLOAT, EXCHANGE_RATE)) AS EXCHANGE_RATE
	    ,CONVERT(DECIMAL(18, 3), CONVERT(FLOAT, SETTLEMENT_DATE_LIQUIDATING_VALUE)) AS SETTLEMENT_DATE_LIQUIDATING_VALUE
	    ,ALTERNATE_SECURITY_ID_TYPE
	    ,ALTERNATE_SECURITY_ID
		,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
    	,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
    	,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
	    ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
	    ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_GCUS_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA > COALESCE((SELECT MAX(DATE_OF_DATA) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data