-- NAME: BRONZE_PERSHING_CAPT_REC_5
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 11, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
	SELECT DISTINCT
		INTRODUCING_BROKER_DEALER_IBD_NUMBER
		,RECORD_ID
		,OPTION_ROOT_ID
		,EXPIRATION_DATE
		,CALL_PUT_INDICATOR
		,CASE
			WHEN RIGHT(STRIKE_PRICE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(STRIKE_PRICE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(STRIKE_PRICE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,3),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(STRIKE_PRICE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(10,3), STRIKE_PRICE)
		 END STRIKE_PRICE
		,MASTER_CLIENT_NAME
		,PERSHING_INTERNAL_ORDER_REFERENCE_NUMBER
		,EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER
		,EXPANDED_FROM_INVESTMENT_PROFESSIONAL_NUMBER
		,RECORD_ID_SEQUENCE_NUMBER
		,DATE_OF_DATA
		,YEARMONTH
	FROM {{ source("pershing", "PERSHING_CAPT_5") }}
	{% if is_incremental() %}
		WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data