-- NAME: BRONZE_PERSHING_ISCA_REC_J
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT DISTINCT
	    RECORD_INDICATOR_VALUE
	    ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
	    ,CUSIP_NUMBER
	    ,NOT_USED_1
		,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, LATEST_PRICE)) AS LATEST_PRICE
		,CONVERT(INT, LATEST_PRICE_DATE) AS LATEST_PRICE_DATE
		,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, FACTORED_MARKET_VALUE_MULTIPLIER)) AS FACTORED_MARKET_VALUE_MULTIPLIER
		,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, CURRENT_YIELD)) AS CURRENT_YIELD
		,CONVERT(DECIMAL(18, 9), CONVERT(FLOAT, YIELD)) AS YIELD
		,PRICE_SOURCE
		,COUNTRY_OF_ORIGIN
		,RESTRICTED_SECURITY_CODE
		,INTERNATIONAL_NON_DOLLAR_SYMBOL
		,INTERNATIONAL_EXCHANGE
		,VARIABLE_RATE_CATEGORY_CODE
		,INTEREST_RATE_COMPLETION_INDICATOR
		,NOT_USED_2
	    ,CONVERT(DATE, DATE_OF_DATA) AS DATE_OF_DATA
	    ,YEARMONTH
    FROM
        {{ source("pershing", "PERSHING_ISCA_J") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA > COALESCE((SELECT MAX(DATE_OF_DATA) FROM {{ this }}),'1970-01-01 00:00:00.000')
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data