-- NAME: BRONZE_PERSHING_GACT_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: December 17, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
    SELECT DISTINCT
        TRANSACTION_CODE
        ,RECORD_INDICATOR_VALUE
        ,CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,CUSIP_NUMBER
        ,UNDERLYING_CUSIP
        ,SECURITY_SYMBOL
        ,LEGACY_INVESTMENT_PROFESSIONAL_IP_OF_RECORD
        ,LEGACY_EXECUTING_INVESTMENT_PROFESSIONAL_IP
        ,TRANSACTION_TYPE
        ,BUY_SELL_CODE
        ,OPEN_CLOSE_INDICATOR
        ,PAR_KEY_CODE
        ,SOURCE_CODE
        ,CONVERT(INT, MAXX_KEY_CODE) AS MAXX_KEY_CODE
        ,CASE
            WHEN PROCESS_DATE = '00000000' THEN NULL
            WHEN PROCESS_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, PROCESS_DATE, 121)
        END AS PROCESS_DATE
        ,CASE
            WHEN TRADE_DATE = '00000000' THEN NULL
            WHEN TRADE_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, TRADE_DATE, 121)
        END AS TRADE_DATE
        ,CASE
            WHEN SETTLEMENT_ENTRY_DATE = '00000000' THEN NULL
            WHEN SETTLEMENT_ENTRY_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, SETTLEMENT_ENTRY_DATE, 121)
        END AS SETTLEMENT_ENTRY_DATE
        ,SOURCE_OF_INPUT
        ,REFERENCE_NUMBER
        ,BATCH_CODE
        ,SAME_DAY_SETTLEMENT
        ,CONTRA_ACCOUNT
        ,MARKET_CODE
        ,BLOTTER_CODE
        ,CANCEL_CODE
        ,CORRECTION_CODE
        ,MARKET_LIMIT_INDICATOR
        ,LEGEND_CODE_1
        ,LEGEND_CODE_2
        ,CONVERT(DECIMAL(18,5), QUANTITY) AS QUANTITY
        ,CONVERT(DECIMAL(18,9), PRICE_IN_SETTLEMENT_CURRENCY) AS PRICE_IN_SETTLEMENT_CURRENCY
        ,CURRENCY_INDICATOR_FOR_PRICE
        ,CONVERT(DECIMAL(18,3), NET_AMOUNT_OF_TRANSACTION_USD_USDE) AS NET_AMOUNT_OF_TRANSACTION_USD_USDE
        ,CONVERT(DECIMAL(18,3), PRINCIPAL_USD_USDE) AS PRINCIPAL_USD_USDE
        ,CONVERT(DECIMAL(18,2), INTEREST_USD_USDE) AS INTEREST_USD_USDE
        ,CONVERT(DECIMAL(18,2), COMMISSION_USD_USDE) AS COMMISSION_USD_USDE
        ,CONVERT(DECIMAL(18,2), TAX_USD_USDE) AS TAX_USD_USDE
        ,CONVERT(DECIMAL(18,2), TRANSACTION_USD_USDE) AS TRANSACTION_USD_USDE
        ,CONVERT(DECIMAL(18,2), MISC_FEE_USD_USDE) AS MISC_FEE_USD_USDE
        ,CONVERT(DECIMAL(18,2), OTHER_FEE_USD_USDE) AS OTHER_FEE_USD_USDE
        ,CONVERT(DECIMAL(18,2), TEFRA_WITHHOLDING_AMOUNT_USD) AS TEFRA_WITHHOLDING_AMOUNT_USD
        ,CONVERT(DECIMAL(18,2), PERSHING_CHARGE_USD) AS PERSHING_CHARGE_USD
        ,CONVERT(DECIMAL(18,2), BROKERAGE_CHARGE_USD) AS BROKERAGE_CHARGE_USD
        ,CONVERT(DECIMAL(18,2), SALES_CREDIT_USD_USDE) AS SALES_CREDIT_USD_USDE
        ,CONVERT(DECIMAL(18,2), SETTLEMENT_FEE_USD_USDE) AS SETTLEMENT_FEE_USD_USDE
        ,CONVERT(DECIMAL(18,2), SERVICE_CHARGE_USD_USDE) AS SERVICE_CHARGE_USD_USDE
        ,CONVERT(DECIMAL(18,2), MARKUP_MARKDOWN_AMOUNT_USD_USDE) AS MARKUP_MARKDOWN_AMOUNT_USD_USDE
        ,CASE
            WHEN DIVIDEND_PAYABLE_DATE = '00000000' THEN NULL
            WHEN DIVIDEND_PAYABLE_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, DIVIDEND_PAYABLE_DATE, 121)
        END AS DIVIDEND_PAYABLE_DATE
        ,CASE
            WHEN DIVIDEND_RECORD_DATE = '00000000' THEN NULL
            WHEN DIVIDEND_RECORD_DATE IS NULL THEN NULL
            ELSE CONVERT(DATE, DIVIDEND_RECORD_DATE, 121)
        END AS DIVIDEND_RECORD_DATE
        ,CONVERT(INT, DIVIDEND_TYPE) AS DIVIDEND_TYPE
        ,CONVERT(DECIMAL(18,5), SHARES_OF_RECORD_QUANTITY_FOR_DIVIDENDS) AS SHARES_OF_RECORD_QUANTITY_FOR_DIVIDENDS
        ,CONVERT(DECIMAL(18,5), ORDER_SIZE_QUANTITY) AS ORDER_SIZE_QUANTITY
        ,CONVERT(DECIMAL(18,9), POOL_FACTOR) AS POOL_FACTOR
        ,PARSED_CUSTOMER_ACCOUNT_NUMBER_ASSOC_FIRM_ACCOUNT
        ,IBD_NUMBER
        ,SECURITY_TYPE_CODE
        ,SECURITY_MODIFIER_CODE
        ,SECURITY_CALCULATION_CODE
        ,MINOR_PRODUCT_CODE
        ,FOREIGN_PRODUCT_INDICATOR
        ,WITH_DUE_BILL_INDICATOR
        ,TAXABLE_MUNICIPAL_BOND_INDICATOR
        ,OMNIBUS_INDICATOR
        ,EXTERNAL_ORDER_ID
        ,CONVERT(DECIMAL(18,2), MARKET_VALUE_OF_TRANSACTION) AS MARKET_VALUE_OF_TRANSACTION
        ,LEGACY_INVESTMENT_PROFESSIONAL_IP_GMAR_FIRM_ACCOUNT
        ,CONVERT(DECIMAL(18,9), REPORTED_PRICE) AS REPORTED_PRICE
        ,CONVERT(DECIMAL(18,2), PREVIOUS_DAY_MARKET_VALUE_TRANSACTION) AS PREVIOUS_DAY_MARKET_VALUE_TRANSACTION
        ,CONVERT(DECIMAL(18,9), PRICE_IN_USDE) AS PRICE_IN_USDE
        ,OPTION_ROOT_ID
        ,EXPIRATION_DATE
        ,PUT_CALL_CODE
        ,CONVERT(DECIMAL(8,3), STRIKE_PRICE) AS STRIKE_PRICE
        ,REPO_IDENTIFIER
        ,TAXABLE
        ,QUALIFIED
        ,EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER_OF_RECORD
        ,EXPANDED_EXECUTING_INVESTMENT_IP
        ,EXPANDED_INVESTMENT_PROFESSIONAL_IP_GMAR_FIRM_ACCOUNT
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_GACT_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data