-- NAME: BRONZE_PERSHING_ACCF_REC_A
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: December 17, 2024

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS (
	SELECT DISTINCT
		-- GENERIC TYPE (PART I)
		TRANSACTION_CODE,
		RECORD_INDICATOR_VALUE,
		CONVERT(INT, RECORD_ID_SEQUENCE_NUMBER) AS RECORD_ID_SEQUENCE_NUMBER,
		ACCOUNT_NUMBER,
		INTRODUCING_BROKER_DEALER_IBD_NUMBER,
		INVESTMENT_PROFESSIONAL_IP_NUMBER,
		ACCOUNT_SHORT_NAME,
		TRANSACTION_TYPE,
		AUTO_TITLED_OR_USER_TITLED_ACCOUNT,
		ACCOUNT_TYPE_CODE,
		REGISTRATION_TYPE,
		CONVERT(INT, NUMBER_OF_ACCOUNT_TITLE_LINES_IN_REGISTRATION_LINES) AS NUMBER_OF_ACCOUNT_TITLE_LINES_IN_REGISTRATION_LINES,
		ACCOUNT_REGISTRATION_LINE_1,
		ACCOUNT_REGISTRATION_LINE_2,
		ACCOUNT_REGISTRATION_LINE_3,
		ACCOUNT_REGISTRATION_LINE_4,
		ACCOUNT_REGISTRATION_LINE_5,
		ACCOUNT_REGISTRATION_LINE_6,

		-- REG TYPE IN ('JNTN','NPLJ','TODI','TODJ'), OTHER REGS WILL BE NULLIFIED
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODJ') THEN US_TENANCY_INDICATOR
			ELSE NULL
		END AS US_TENANCY_INDICATOR,
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODJ') THEN MARRIED_INDICATOR
			ELSE NULL
		END AS MARRIED_INDICATOR,
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODJ') THEN TENANCY_STATE
			ELSE NULL
		END AS TENANCY_STATE,
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODJ') THEN JOINT_TENANCY_CLAUSE
			ELSE NULL
		END AS JOINT_TENANCY_CLAUSE,
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODI','TODJ') THEN
				CASE
					WHEN AGREEMENT_EXECUTION_DATE = '00000000' THEN NULL
					ELSE CONVERT(DATE, AGREEMENT_EXECUTION_DATE, 121)
				END
			ELSE NULL
		END AS AGREEMENT_EXECUTION_DATE,
		CASE
			WHEN REGISTRATION_TYPE IN ('JNTN','NPLJ','TODI','TODJ') THEN CONVERT(INT, NUMBER_OF_TENANTS)
			ELSE NULL
		END AS NUMBER_OF_TENANTS,

		-- CUSTODIAN REG TYPE IN ('CUST','529C'), OTHER REGS WILL BE NULLIFIED
		CASE
			WHEN REGISTRATION_TYPE IN ('CUST','529C') THEN STATE_GIFT_GIVEN
			ELSE NULL
		END AS STATE_GIFT_GIVEN,
		CASE
			WHEN REGISTRATION_TYPE IN ('CUST','529C') THEN
				CASE
					WHEN DATE_GIFT_GIVEN = '00000000' THEN NULL
					ELSE CONVERT(DATE, DATE_GIFT_GIVEN, 121)
				END
			ELSE NULL
		END AS DATE_GIFT_GIVEN,
		CASE
			WHEN REGISTRATION_TYPE IN ('CUST','529C') THEN CONVERT(INT, AGE_TO_TERMINATE)
			ELSE NULL
		END AS AGE_TO_TERMINATE,
		CASE
			WHEN REGISTRATION_TYPE IN ('CUST','529C') THEN
				CASE
					WHEN MINORS_BIRTHDATE = '00000000' THEN NULL
					ELSE CONVERT(DATE, MINORS_BIRTHDATE, 121)
				END
			ELSE NULL
		END AS MINORS_BIRTHDATE,
		CASE
			WHEN REGISTRATION_TYPE IN ('CUST','529C') THEN MANNER_OF_GIFT
			ELSE NULL
		END AS MANNER_OF_GIFT,

		-- NEEDS TO BE CONFIRMED WITH PROPER SOURCES, THERE IS NO CLEAR INDICATION ON DOCS
		-- TRUST ACCOUNT REG TYPE IN ('NPLT','TRST','529T','DLJC','DLJI','DLJP','DLJQ','DLJS','RETE','RETI','RETN','RETP','RETQ','RETR','RETS'), OTHER REGS WILL BE NULLIFIED
		CASE
			WHEN REGISTRATION_TYPE IN ('NPLT','TRST','529T','DLJC','DLJI','DLJP','DLJQ','DLJS','RETE','RETI','RETN','RETP','RETQ','RETR','RETS') THEN TYPE_OF_TRUST
			ELSE NULL
		END AS TYPE_OF_TRUST,
		CASE
			WHEN REGISTRATION_TYPE IN ('NPLT','TRST','529T','DLJC','DLJI','DLJP','DLJQ','DLJS','RETE','RETI','RETN','RETP','RETQ','RETR','RETS') THEN
				CASE
					WHEN DATE_TRUST_ESTABLISHED = '00000000' THEN NULL
					ELSE CONVERT(DATE, DATE_TRUST_ESTABLISHED, 121)
				END
			ELSE NULL
		END AS DATE_TRUST_ESTABLISHED,
		CASE
			WHEN REGISTRATION_TYPE IN ('NPLT','TRST','529T','DLJC','DLJI','DLJP','DLJQ','DLJS','RETE','RETI','RETN','RETP','RETQ','RETR','RETS') THEN
				CASE
					WHEN AMENDED_DATE = '00000000' THEN NULL
					ELSE CONVERT(DATE, AMENDED_DATE, 121)
				END
			ELSE NULL
		END AS AMENDED_DATE,
		CASE
			WHEN REGISTRATION_TYPE IN ('NPLT','TRST','529T','DLJC','DLJI','DLJP','DLJQ','DLJS','RETE','RETI','RETN','RETP','RETQ','RETR','RETS') THEN TRUSTEE_INDEPENDENT_ACTION
			ELSE NULL
		END AS TRUSTEE_INDEPENDENT_ACTION,

		-- CPPS ACCOUNT REG TYPE IN ('CPPS'), OTHER REGS WILL BE NULLIFIED
		CASE
			WHEN REGISTRATION_TYPE = 'CPPS' THEN
				CASE
					WHEN PLAN_ESTABLISHED_DATE = '00000000' THEN NULL
					ELSE CONVERT(DATE, PLAN_ESTABLISHED_DATE, 121)
				END
			ELSE NULL
		END AS PLAN_ESTABLISHED_DATE,
		CASE
			WHEN REGISTRATION_TYPE = 'CPPS' THEN
				CASE
					WHEN PLAN_AMENDMENT_DATE = '00000000' THEN NULL
					ELSE CONVERT(DATE, PLAN_AMENDMENT_DATE, 121)
				END
			ELSE NULL
		END AS PLAN_AMENDMENT_DATE,

		-- GENERIC TYPE (PART II)
		CASE
			WHEN DATE_ACCOUNT_OPENED = '00000000' THEN NULL
			WHEN DATE_ACCOUNT_OPENED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_ACCOUNT_OPENED, 121)
		END AS DATE_ACCOUNT_OPENED,
		CASE
			WHEN DATE_ACCOUNT_INFORMATION_UPDATED = '00000000' THEN NULL
			WHEN DATE_ACCOUNT_INFORMATION_UPDATED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_ACCOUNT_INFORMATION_UPDATED, 121)
		END AS DATE_ACCOUNT_INFORMATION_UPDATED,
		ACCOUNT_STATUS_INDICATOR,
		--
		CASE
			WHEN PENDING_CLOSED_DATE = '00000000' THEN NULL
			WHEN PENDING_CLOSED_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, PENDING_CLOSED_DATE, 121)
		END AS PENDING_CLOSED_DATE,
		CASE
			WHEN DATE_ACCOUNT_CLOSED = '00000000' THEN NULL
			WHEN DATE_ACCOUNT_CLOSED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_ACCOUNT_CLOSED, 121)
		END AS DATE_ACCOUNT_CLOSED,
		CASE
			WHEN CLOSING_NOTICE_DATE = '00000000' THEN NULL
			WHEN CLOSING_NOTICE_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, CLOSING_NOTICE_DATE, 121)
		END AS CLOSING_NOTICE_DATE,
		CASE
			WHEN ACCOUNT_REACTIVATED_DATE = '00000000' THEN NULL
			WHEN ACCOUNT_REACTIVATED_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, ACCOUNT_REACTIVATED_DATE, 121)
		END AS ACCOUNT_REACTIVATED_DATE,
		CASE
			WHEN DATE_ACCOUNT_REOPENED = '00000000' THEN NULL
			WHEN DATE_ACCOUNT_REOPENED IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_ACCOUNT_REOPENED, 121)
		END AS DATE_ACCOUNT_REOPENED,
		PROCEEDS,
		TRANSFER_INSTRUCTIONS,
		INCOME_INSTRUCTIONS,
		CONVERT(INT, NUMBER_OF_CONFIRMS_FOR_THIS_ACCOUNT) AS NUMBER_OF_CONFIRMS_FOR_THIS_ACCOUNT,
		CONVERT(INT, NUMBER_OF_STATEMENTS_FOR_THIS_ACCOUNT) AS NUMBER_OF_STATEMENTS_FOR_THIS_ACCOUNT,
		INVESTMENT_OBJECTIVE_TRANSACTION_CODE,
		COMMENTS,
		EMPLOYER_SHORTNAME,
		EMPLOYERS_CUSIP,
		EMPLOYERS_SYMBOL,
		MARGIN_PRIVILEGES_REVOKED,
		CASE
			WHEN STATEMENT_REVIEW_DATE = '00000000' THEN NULL
			WHEN STATEMENT_REVIEW_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, STATEMENT_REVIEW_DATE, 121)
		END AS STATEMENT_REVIEW_DATE,
		MARGIN_PAPERS_ON_FILE,
		OPTION_PAPERS_ON_FILE,
		GOOD_FAITH_MARGIN,
		INVESTMENT_PROFESSIONAL_DISCRETION_GRANTED,
		INVESTMENT_ADVISOR_DISCRETION_GRANTED,
		THIRD_PARTY_DISCRETION_GRANTED,
		THIRD_PARTY_NAME,
		RISK_FACTOR_CODE,
		INVESTMENT_OBJECTIVE_CODE,
		OPTION_EQUITIES,
		OPTION_INDEX,
		OPTION_DEBT,
		OPTION_CURRENCY,
		OPTION_LEVEL_1,
		OPTION_LEVEL_2,
		OPTION_LEVEL_3,
		OPTION_LEVEL_4,
		CONVERT(DECIMAL(10,0), OPTION_CALL_LIMITS) AS OPTION_CALL_LIMITS,
		CONVERT(DECIMAL(10,0), OPTION_PUT_LIMITS) AS OPTION_PUT_LIMITS,
		CONVERT(DECIMAL(10,0), OPTION_TOTAL_LIMITS_OF_PUTS_AND_CALLS) AS OPTION_TOTAL_LIMITS_OF_PUTS_AND_CALLS,
		NON_US_DOLLAR_TRADING,
		NON_CUSTOMER_INDICATOR,
		THIRD_PARTY_FEE_INDICATOR,
		CASE
			WHEN THIRD_PARTY_FEE_APPROVAL_DATE = '00000000' THEN NULL
			WHEN THIRD_PARTY_FEE_APPROVAL_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, THIRD_PARTY_FEE_APPROVAL_DATE, 121)
		END AS THIRD_PARTY_FEE_APPROVAL_DATE,
		INTERMEDIARY_ACCOUNT_INDICATOR,
		COMMISSION_SCHEDULE,
		GROUP_INDEX,
		MONEY_MANAGER_ID,
		MONEY_MANAGER_OBJECTIVE,
		DTC_ID_CONFIRM_NUMBER_FOR_NON_COD_ACCOUNT,
		CAPS_MASTER_MNEMONIC,
		EMPLOYEE_ID,
		PRIME_BROKER_FREE_FUND_INDICATOR,
		FEE_BASED_ACCOUNT_INDICATOR,
		CASE
			WHEN FEE_BASED_TERMINATION_DATE = '00000000' THEN NULL
			WHEN FEE_BASED_TERMINATION_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, FEE_BASED_TERMINATION_DATE, 121)
		END AS FEE_BASED_TERMINATION_DATE,
		PLAN_NAME,
		SELFDIRECTED_401_k_ACCOUNT_TYPE,
		PLAN_TYPE,
		PLAN_NUMBER,
		EMPLOYEE_RELATIVE_INDICATOR,
		CONVERT(
			DECIMAL(18,9),
        	LEFT(COMMISSION_PERCENT_DISCOUNT, 9) + '.' + RIGHT(COMMISSION_PERCENT_DISCOUNT, 9)
    	) AS COMMISSION_PERCENT_DISCOUNT,
		BLOCK_MUTUAL_FUND_FEES,
		NAME_OF_INVESTMENT_PROFESSIONAL_WHO_SIGNED_NEW_ACCOUNT_FORM,
		CASE
			WHEN DATE_INVESTMENT_PROFESSIONAL_SIGNED_NEW_ACCOUNT_FORM = '00000000' THEN NULL
			WHEN DATE_INVESTMENT_PROFESSIONAL_SIGNED_NEW_ACCOUNT_FORM IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_INVESTMENT_PROFESSIONAL_SIGNED_NEW_ACCOUNT_FORM, 121)
		END AS DATE_INVESTMENT_PROFESSIONAL_SIGNED_NEW_ACCOUNT_FORM,
		NAME_OF_PRINCIPAL_WHO_SIGNED_NEW_ACCOUNT_FORM,
		CASE
			WHEN DATE_PRINCIPAL_SIGNED_NEW_ACCOUNT_FORM = '00000000' THEN NULL
			WHEN DATE_PRINCIPAL_SIGNED_NEW_ACCOUNT_FORM IS NULL THEN NULL
			ELSE CONVERT(DATE, DATE_PRINCIPAL_SIGNED_NEW_ACCOUNT_FORM, 121)
		END AS DATE_PRINCIPAL_SIGNED_NEW_ACCOUNT_FORM,
		POLITICALLY_EXPOSED_PERSON_INDICATOR,
		PRIVATE_BANKING_ACCOUNT_INDICATOR,
		FOREIGN_BANK_ACCOUNT_INDICATOR,
		INITIAL_SOURCE_OF_FUNDS,
		USA_PATRIOT_ACT_EXEMPT_REASON,
		PRIMARY_COUNTRY_OF_CITIZENSHIP,
		COUNTRY_OF_RESIDENCE,
		CASE
			WHEN BIRTH_DATE = '00000000' THEN NULL
			WHEN BIRTH_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, BIRTH_DATE, 121)
		END AS BIRTH_DATE,
		AGEBASED_FUND_ROLL_EXEMPT_INDICATOR,
		MONEY_FUND_REFORM_RETAIL,
		TRUSTED_CONTACT_STATUS,
		REGULATORY_ACCOUNT_TYPE_CATEGORY,
		ACCOUNT_MANAGED_BY_TRUST_COMPANY_INDICATOR,
		VOTING_AUTHORITY,
		Internal_Use_IMS_Prime_Broker_Code,
		Internal_Use_Payout_Code,
		Internal_Use_Trader_Number,
		Internal_Use_Product_Code,
		CUSTOMER_TYPE,
		Internal_Use_Account_Plan_Type,
		Internal_Use_Promotion_Type,
		Internal_Use_Investment_Objective_1,
		Internal_Use_Investment_Objective_2,
		Internal_Use_Investment_Objective_3,
		FULFILLMENT_METHOD,
		CREDIT_INTEREST_INDICATOR,
		AMA_INDICATOR,
		SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE,
		SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE,
		NULL AS ACCOUNT_NUMBER_TYPE,
		DATE_OF_DATA,
		YEARMONTH
	FROM  {{ source("pershing", "PERSHING_ACCF_A") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data