-- NAME: BRONZE_PERSHING_CAPT_REC_2
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 10, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
		  tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
	SELECT DISTINCT
		INTRODUCING_BROKER_DEALER_IBD_NUMBER
		,RECORD_ID
		,MARKET_CODE
		,BLOTTER_CODE
		,SECURITY_TYPE
		,STOCK_SYMBOL
		,SECURITY_DESCRIPTION
		,CASE
			WHEN RIGHT(CENTS_PER_SHARE,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(10,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CENTS_PER_SHARE,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(CENTS_PER_SHARE,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(10,4),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(CENTS_PER_SHARE,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(10,4), CENTS_PER_SHARE)
		 END CENTS_PER_SHARE
		,CASE
			WHEN RIGHT(DISCOUNT_PERCENT,1) IN ('{','A','B','C','D','E','F','G','H','I') THEN CONVERT(DECIMAL(8,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(DISCOUNT_PERCENT,'{',0),'A',1),'B',2),'C', 3),'D',4),'E', 5),'F',6),'G',7),'H',8),'I',9))
			WHEN RIGHT(DISCOUNT_PERCENT,1) IN ('}','J','K','L','M','N','O','P','Q','R') THEN CONVERT(DECIMAL(8,2),REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(DISCOUNT_PERCENT,'}',0),'J',1),'K',2),'L', 3),'M',4),'N', 5),'O',6),'P',7),'Q',8),'R',9)) * -1
			ELSE CONVERT(DECIMAL(8,2), DISCOUNT_PERCENT)
		 END DISCOUNT_PERCENT
		,PAYCODE
		,MASTER_CLIENT_MNEMONIC
		,INSTITUTIONAL_RETAIL_INDICATOR
		,STATE_CODE
		,COMISSION_INDICATOR
		,FIRM_TRADING_ACCOUNT
		,CASE
			WHEN POSTED_DATE = '00000000' THEN NULL
			WHEN POSTED_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, POSTED_DATE, 121)
		END AS POSTED_DATE
		,CASE
			WHEN SETTLEMENT_DATE = '00000000' THEN NULL
			WHEN SETTLEMENT_DATE IS NULL THEN NULL
			ELSE CONVERT(DATE, SETTLEMENT_DATE, 121)
		END AS SETTLEMENT_DATE
		,RECYCLE_INDICATOR
		,RECORD_ID_SEQUENCE_NUMBER
		,DATE_OF_DATA
		,YEARMONTH
	FROM {{ source("pershing", "PERSHING_CAPT_2") }}
	{% if is_incremental() %}
		WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data