-- Databricks SQL for source: jh_acsret
-- Generated from sqlserver_brz/brz-jh_acsret.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_ACSRET"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_acsret (
    `ACRTYP` STRING,
    `AC1TYP` STRING,
    `AC1PCD` STRING,
    `AC1RP1` STRING,
    `AC1RPI` STRING,
    `AC1RPC` STRING,
    `AC1SP1` STRING,
    `AC1SPI` STRING,
    `AC1SPC` STRING,
    `AC1DT` STRING,
    `AC1TIM` STRING,
    `AC1MOD` STRING,
    `AC1REC` STRING,
    `AC1BLK` STRING,
    `AC1FC` STRING,
    `AC1DES` STRING,
    `AC1ORG` STRING,
    `AC1REF` STRING,
    `AC5CLA` STRING,
    `AC5COM` STRING,
    `AC5CDD` STRING,
    `AC5CID` STRING,
    `AC5SEC` STRING,
    `AC5CED` STRING,
    `AC5CDT` STRING,
    `AC5EED` STRING,
    `AC5SET` STRING,
    `AC5OSI` STRING,
    `AC5ODF` STRING,
    `AC5BAT` STRING,
    `AC5IATIND` STRING,
    `AC5IATFEI` STRING,
    `AC5IATFERI` STRING,
    `AC5IATFER` STRING,
    `AC5IATDCC` STRING,
    `AC5IATOCCD` STRING,
    `AC5IATDCCD` STRING,
    `AC5BRFEI` STRING,
    `AC5BRFERI` STRING,
    `AC5BRFER` STRING,
    `AC5BRDCC` STRING,
    `AC5BROCC` STRING,
    `AC5BRDCRC` STRING,
    `AC6TYP` STRING,
    `AC6TC` STRING,
    `AC6RTR` STRING,
    `AC6RCK` STRING,
    `AC6ACT` STRING,
    `AC6AMT` DECIMAL(38,10),
    `AC6IIN` STRING,
    `AC6CKN` STRING,
    `AC6CTY` STRING,
    `AC6STA` STRING,
    `AC6INM` STRING,
    `AC6IINCIE` STRING,
    `AC6INMCIE` STRING,
    `AC6DD` STRING,
    `AC6ARI` STRING,
    `AC6TRC` STRING,
    `AC6BRRCVCO` STRING,
    `AC6CED` STRING,
    `AC6DFN` STRING,
    `AC6CAN` STRING,
    `AC6CTT` STRING,
    `AC6NIP` STRING,
    `AC6RCN` STRING,
    `AC6FIL` STRING,
    `AC6INOADDN` STRING,
    `AC6IACCTNO` STRING,
    `AC6IGOOSI1` STRING,
    `AC6IGOOSI2` STRING,
    `AC7TYP` STRING,
    `AC7ATC` STRING,
    `AC7RET` STRING,
    `AC7OTN` STRING,
    `AC7DOD` STRING,
    `AC7TR` STRING,
    `AC7AI` STRING,
    `AC7TRC` STRING,
    `AC7IOEPAMT` DECIMAL(38,10),
    `AC7IRTNADD` STRING,
    `AC7ICORDTA` STRING,
    `AC7BRTRTYP` STRING,
    `AC7BRFRNID` STRING,
    `AC7BRFRNAM` STRING,
    `AC7BRFRNTR` STRING,
    `AC7BRFRNAC` STRING,
    `AC7BRRTID` STRING,
    `AC7BRRTAM` STRING,
    `AC7BRRTFAM` STRING,
    `AC7BRRTADN` STRING,
    `AC7BRRTTRC` STRING,
    `AC7TD` STRING,
    `AC7NIC` STRING,
    `AC7TIC` STRING,
    `AC7TSN` STRING,
    `AC7TDT` STRING,
    `AC7TTA` STRING,
    `AC7LOC` STRING,
    `AC7CIT` STRING,
    `AC7STA` STRING,
    `AC7PTC` STRING,
    `AC7RDC` STRING,
    `AC7RN` STRING,
    `AC7RID` STRING,
    `AC7DDA` STRING,
    `AC7TDA` STRING,
    `AC7ADJ` DECIMAL(38,10),
    `AC7NET` DECIMAL(38,10),
    `AC7AVI` STRING,
    `AC7SAN` STRING,
    `AC7FL2` STRING,
    `AC7ASN` STRING,
    `AC7DSN` STRING,
    `AC7F79` STRING,
    `AC7SSN` STRING,
    `AC7F80` STRING,
    `AC7SAS` STRING,
    `AC8EAC` STRING,
    `AC8HSH` STRING,
    `AC8DRA` DECIMAL(38,10),
    `AC8CRA` DECIMAL(38,10),
    `AC8CID` STRING,
    `AC8OTR` STRING,
    `AC8BAT` STRING,
    `AC9BAT` STRING,
    `AC9EAC` STRING,
    `AC9DRA` DECIMAL(38,10),
    `AC9CRA` DECIMAL(38,10),
    `AC8DRAADV` STRING,
    `AC8CRAADV` STRING,
    `AC8OPDADV` STRING,
    `AC9DRAADV` STRING,
    `AC9CRAADV` STRING,
    `AC9FILADV` STRING,
    `ACONUS` STRING,
    `ACONUSCRC` STRING,
    `ACONUSCRT` STRING,
    `ACONUSDRC` STRING,
    `ACONUSDRT` STRING,
    `ACNOTUSCRC` STRING,
    `ACNOTUSCRT` STRING,
    `ACNOTUSDRC` STRING,
    `ACNOTUSDRT` STRING,
    `ACRSKVIOL` STRING,
    `ACSUSPEND` STRING,
    `ACACCT` STRING,
    `ACATYP` STRING,
    `ACOSCD` STRING,
    `ACOSAT` STRING,
    `ACOBR` STRING,
    `ACMEMO` STRING,
    `ACEXDT` STRING,
    `ACFILK` STRING,
    `ACBATN` STRING,
    `ACSEQN` STRING,
    `ACORGFILK` STRING,
    `ACORGBATN` STRING,
    `ACORGSEQN` STRING,
    `ACENTB` STRING,
    `ACDEN7` STRING,
    `ACDEN6` STRING,
    `ACTENT` STRING,
    `ACENTV` STRING,
    `ACUPLDUID` STRING,
    `ACUPLDWID` STRING,
    `ACUSPNDUID` STRING,
    `ACUSPNDWID` STRING,
    `ACSPNDUID` STRING,
    `ACSPNDWID` STRING,
    `ACRETURNED` STRING,
    `ACRTNDTTM` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_acsret IS
'The JH ACSRET landing table captures ACH return, routing, account, batch, risk, suspension, and return-status attributes from Jack Henry for landing-layer validation, reconciliation, and downstream bronze processing.';

TRUNCATE TABLE landing_jh.default.jh_acsret;

INSERT INTO landing_jh.default.jh_acsret (
    `ACRTYP`, `AC1TYP`, `AC1PCD`, `AC1RP1`, `AC1RPI`, `AC1RPC`,
    `AC1SP1`, `AC1SPI`, `AC1SPC`, `AC1DT`, `AC1TIM`, `AC1MOD`,
    `AC1REC`, `AC1BLK`, `AC1FC`, `AC1DES`, `AC1ORG`, `AC1REF`,
    `AC5CLA`, `AC5COM`, `AC5CDD`, `AC5CID`, `AC5SEC`, `AC5CED`,
    `AC5CDT`, `AC5EED`, `AC5SET`, `AC5OSI`, `AC5ODF`, `AC5BAT`,
    `AC5IATIND`, `AC5IATFEI`, `AC5IATFERI`, `AC5IATFER`, `AC5IATDCC`, `AC5IATOCCD`,
    `AC5IATDCCD`, `AC5BRFEI`, `AC5BRFERI`, `AC5BRFER`, `AC5BRDCC`, `AC5BROCC`,
    `AC5BRDCRC`, `AC6TYP`, `AC6TC`, `AC6RTR`, `AC6RCK`, `AC6ACT`,
    `AC6AMT`, `AC6IIN`, `AC6CKN`, `AC6CTY`, `AC6STA`, `AC6INM`,
    `AC6IINCIE`, `AC6INMCIE`, `AC6DD`, `AC6ARI`, `AC6TRC`, `AC6BRRCVCO`,
    `AC6CED`, `AC6DFN`, `AC6CAN`, `AC6CTT`, `AC6NIP`, `AC6RCN`,
    `AC6FIL`, `AC6INOADDN`, `AC6IACCTNO`, `AC6IGOOSI1`, `AC6IGOOSI2`, `AC7TYP`,
    `AC7ATC`, `AC7RET`, `AC7OTN`, `AC7DOD`, `AC7TR`, `AC7AI`,
    `AC7TRC`, `AC7IOEPAMT`, `AC7IRTNADD`, `AC7ICORDTA`, `AC7BRTRTYP`, `AC7BRFRNID`,
    `AC7BRFRNAM`, `AC7BRFRNTR`, `AC7BRFRNAC`, `AC7BRRTID`, `AC7BRRTAM`, `AC7BRRTFAM`,
    `AC7BRRTADN`, `AC7BRRTTRC`, `AC7TD`, `AC7NIC`, `AC7TIC`, `AC7TSN`,
    `AC7TDT`, `AC7TTA`, `AC7LOC`, `AC7CIT`, `AC7STA`, `AC7PTC`,
    `AC7RDC`, `AC7RN`, `AC7RID`, `AC7DDA`, `AC7TDA`, `AC7ADJ`,
    `AC7NET`, `AC7AVI`, `AC7SAN`, `AC7FL2`, `AC7ASN`, `AC7DSN`,
    `AC7F79`, `AC7SSN`, `AC7F80`, `AC7SAS`, `AC8EAC`, `AC8HSH`,
    `AC8DRA`, `AC8CRA`, `AC8CID`, `AC8OTR`, `AC8BAT`, `AC9BAT`,
    `AC9EAC`, `AC9DRA`, `AC9CRA`, `AC8DRAADV`, `AC8CRAADV`, `AC8OPDADV`,
    `AC9DRAADV`, `AC9CRAADV`, `AC9FILADV`, `ACONUS`, `ACONUSCRC`, `ACONUSCRT`,
    `ACONUSDRC`, `ACONUSDRT`, `ACNOTUSCRC`, `ACNOTUSCRT`, `ACNOTUSDRC`, `ACNOTUSDRT`,
    `ACRSKVIOL`, `ACSUSPEND`, `ACACCT`, `ACATYP`, `ACOSCD`, `ACOSAT`,
    `ACOBR`, `ACMEMO`, `ACEXDT`, `ACFILK`, `ACBATN`, `ACSEQN`,
    `ACORGFILK`, `ACORGBATN`, `ACORGSEQN`, `ACENTB`, `ACDEN7`, `ACDEN6`,
    `ACTENT`, `ACENTV`, `ACUPLDUID`, `ACUPLDWID`, `ACUSPNDUID`, `ACUSPNDWID`,
    `ACSPNDUID`, `ACSPNDWID`, `ACRETURNED`, `ACRTNDTTM`, `AsOfDate`, `YEARMONTH`,
    `LOADED_AT`
)
SELECT
    concat('ACRTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRTYP`,
    concat('AC1TYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1TYP`,
    concat('AC1PCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1PCD`,
    concat('AC1RP1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1RP1`,
    concat('AC1RPI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1RPI`,
    concat('AC1RPC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1RPC`,
    concat('AC1SP1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1SP1`,
    concat('AC1SPI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1SPI`,
    concat('AC1SPC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1SPC`,
    concat('AC1DT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1DT`,
    concat('AC1TIM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1TIM`,
    concat('AC1MOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1MOD`,
    concat('AC1REC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1REC`,
    concat('AC1BLK_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1BLK`,
    concat('AC1FC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1FC`,
    concat('AC1DES_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1DES`,
    concat('AC1ORG_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1ORG`,
    concat('AC1REF_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC1REF`,
    concat('AC5CLA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5CLA`,
    concat('AC5COM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5COM`,
    concat('AC5CDD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5CDD`,
    concat('AC5CID_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5CID`,
    concat('AC5SEC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5SEC`,
    concat('AC5CED_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5CED`,
    concat('AC5CDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5CDT`,
    concat('AC5EED_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5EED`,
    concat('AC5SET_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5SET`,
    concat('AC5OSI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5OSI`,
    concat('AC5ODF_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5ODF`,
    concat('AC5BAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BAT`,
    concat('AC5IATIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATIND`,
    concat('AC5IATFEI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATFEI`,
    concat('AC5IATFERI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATFERI`,
    concat('AC5IATFER_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATFER`,
    concat('AC5IATDCC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATDCC`,
    concat('AC5IATOCCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATOCCD`,
    concat('AC5IATDCCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5IATDCCD`,
    concat('AC5BRFEI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BRFEI`,
    concat('AC5BRFERI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BRFERI`,
    concat('AC5BRFER_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BRFER`,
    concat('AC5BRDCC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BRDCC`,
    concat('AC5BROCC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BROCC`,
    concat('AC5BRDCRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC5BRDCRC`,
    concat('AC6TYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6TYP`,
    concat('AC6TC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6TC`,
    concat('AC6RTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6RTR`,
    concat('AC6RCK_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6RCK`,
    concat('AC6ACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6ACT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC6AMT`,
    concat('AC6IIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6IIN`,
    concat('AC6CKN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6CKN`,
    concat('AC6CTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6CTY`,
    concat('AC6STA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6STA`,
    concat('AC6INM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6INM`,
    concat('AC6IINCIE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6IINCIE`,
    concat('AC6INMCIE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6INMCIE`,
    concat('AC6DD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6DD`,
    concat('AC6ARI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6ARI`,
    concat('AC6TRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6TRC`,
    concat('AC6BRRCVCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6BRRCVCO`,
    concat('AC6CED_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6CED`,
    concat('AC6DFN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6DFN`,
    concat('AC6CAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6CAN`,
    concat('AC6CTT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6CTT`,
    concat('AC6NIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6NIP`,
    concat('AC6RCN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6RCN`,
    concat('AC6FIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6FIL`,
    concat('AC6INOADDN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6INOADDN`,
    concat('AC6IACCTNO_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6IACCTNO`,
    concat('AC6IGOOSI1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6IGOOSI1`,
    concat('AC6IGOOSI2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC6IGOOSI2`,
    concat('AC7TYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TYP`,
    concat('AC7ATC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7ATC`,
    concat('AC7RET_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7RET`,
    concat('AC7OTN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7OTN`,
    concat('AC7DOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7DOD`,
    concat('AC7TR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TR`,
    concat('AC7AI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7AI`,
    concat('AC7TRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TRC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC7IOEPAMT`,
    concat('AC7IRTNADD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7IRTNADD`,
    concat('AC7ICORDTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7ICORDTA`,
    concat('AC7BRTRTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRTRTYP`,
    concat('AC7BRFRNID_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRFRNID`,
    concat('AC7BRFRNAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRFRNAM`,
    concat('AC7BRFRNTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRFRNTR`,
    concat('AC7BRFRNAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRFRNAC`,
    concat('AC7BRRTID_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRRTID`,
    concat('AC7BRRTAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRRTAM`,
    concat('AC7BRRTFAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRRTFAM`,
    concat('AC7BRRTADN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRRTADN`,
    concat('AC7BRRTTRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7BRRTTRC`,
    concat('AC7TD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TD`,
    concat('AC7NIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7NIC`,
    concat('AC7TIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TIC`,
    concat('AC7TSN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TSN`,
    concat('AC7TDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TDT`,
    concat('AC7TTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TTA`,
    concat('AC7LOC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7LOC`,
    concat('AC7CIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7CIT`,
    concat('AC7STA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7STA`,
    concat('AC7PTC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7PTC`,
    concat('AC7RDC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7RDC`,
    concat('AC7RN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7RN`,
    concat('AC7RID_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7RID`,
    concat('AC7DDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7DDA`,
    concat('AC7TDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7TDA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC7ADJ`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC7NET`,
    concat('AC7AVI_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7AVI`,
    concat('AC7SAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7SAN`,
    concat('AC7FL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7FL2`,
    concat('AC7ASN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7ASN`,
    concat('AC7DSN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7DSN`,
    concat('AC7F79_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7F79`,
    concat('AC7SSN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7SSN`,
    concat('AC7F80_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7F80`,
    concat('AC7SAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC7SAS`,
    concat('AC8EAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8EAC`,
    concat('AC8HSH_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8HSH`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC8DRA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC8CRA`,
    concat('AC8CID_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8CID`,
    concat('AC8OTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8OTR`,
    concat('AC8BAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8BAT`,
    concat('AC9BAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC9BAT`,
    concat('AC9EAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC9EAC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC9DRA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AC9CRA`,
    concat('AC8DRAADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8DRAADV`,
    concat('AC8CRAADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8CRAADV`,
    concat('AC8OPDADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC8OPDADV`,
    concat('AC9DRAADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC9DRAADV`,
    concat('AC9CRAADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC9CRAADV`,
    concat('AC9FILADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `AC9FILADV`,
    concat('ACONUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACONUS`,
    concat('ACONUSCRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACONUSCRC`,
    concat('ACONUSCRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACONUSCRT`,
    concat('ACONUSDRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACONUSDRC`,
    concat('ACONUSDRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACONUSDRT`,
    concat('ACNOTUSCRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACNOTUSCRC`,
    concat('ACNOTUSCRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACNOTUSCRT`,
    concat('ACNOTUSDRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACNOTUSDRC`,
    concat('ACNOTUSDRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACNOTUSDRT`,
    concat('ACRSKVIOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRSKVIOL`,
    concat('ACSUSPEND_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACSUSPEND`,
    concat('ACACCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACACCT`,
    concat('ACATYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACATYP`,
    concat('ACOSCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACOSCD`,
    concat('ACOSAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACOSAT`,
    concat('ACOBR_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACOBR`,
    concat('ACMEMO_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACMEMO`,
    concat('ACEXDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACEXDT`,
    concat('ACFILK_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACFILK`,
    concat('ACBATN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACBATN`,
    concat('ACSEQN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACSEQN`,
    concat('ACORGFILK_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACORGFILK`,
    concat('ACORGBATN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACORGBATN`,
    concat('ACORGSEQN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACORGSEQN`,
    concat('ACENTB_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACENTB`,
    concat('ACDEN7_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACDEN7`,
    concat('ACDEN6_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACDEN6`,
    concat('ACTENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTENT`,
    concat('ACENTV_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACENTV`,
    concat('ACUPLDUID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACUPLDUID`,
    concat('ACUPLDWID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACUPLDWID`,
    concat('ACUSPNDUID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACUSPNDUID`,
    concat('ACUSPNDWID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACUSPNDWID`,
    concat('ACSPNDUID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACSPNDUID`,
    concat('ACSPNDWID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACSPNDWID`,
    concat('ACRETURNED_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRETURNED`,
    concat('ACRTNDTTM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRTNDTTM`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_acsret' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_acsret;
