-- Databricks SQL for source: invoice
-- Generated from sqlserver/brz-invoice.sql

CREATE CATALOG IF NOT EXISTS landing;
USE CATALOG landing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."FILE_INVOICE_REQUESTS"
CREATE TABLE IF NOT EXISTS landing.default.file_invoice_requests (
    `INVOICE_NAME` STRING,
    `EMPLOYEE_NAME` STRING,
    `VENDOR_NAME` STRING,
    `INVOICE_RECEIVED` DATE,
    `ORIGIN_SOURCE` STRING,
    `APPROVAL_STATUS` STRING,
    `PAYMENT_STATUS` STRING,
    `REQUEST_TOTAL` DECIMAL(38,10),
    `REQUEST_KEY` STRING,
    `CHECK_NUMBER` STRING,
    `CREATE_DATE` DATE,
    `DESCRIPTION` STRING,
    `INVOICE_AMOUNT` DECIMAL(38,10),
    `INVOICE_DATE` DATE,
    `PAYMENT_AMOUNT` DECIMAL(38,10),
    `PAYMENT_DUE_DATE` DATE,
    `INVOICE_NUMBER` STRING,
    `PAYMENT_STATUS_DATE` DATE,
    `CUSTOM_01_COST_CENTER` STRING,
    `CUSTOM_02_ENTITY` STRING,
    `CUSTOM_7_COST_CENTER` STRING,
    `CUSTOM_6_ENTITY` STRING,
    `PAYMENT_METHOD_TYPE` STRING,
    `CLOSED_DATE` DATE,
    `SEND_DATE` DATE,
    `FUNDING_DATE` DATE,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` BIGINT,
    `LOADED_AT` TIMESTAMP
);

TRUNCATE TABLE landing.default.file_invoice_requests;

INSERT INTO landing.default.file_invoice_requests (
    `INVOICE_NAME`, `EMPLOYEE_NAME`, `VENDOR_NAME`, `INVOICE_RECEIVED`, `ORIGIN_SOURCE`, `APPROVAL_STATUS`,
    `PAYMENT_STATUS`, `REQUEST_TOTAL`, `REQUEST_KEY`, `CHECK_NUMBER`, `CREATE_DATE`, `DESCRIPTION`,
    `INVOICE_AMOUNT`, `INVOICE_DATE`, `PAYMENT_AMOUNT`, `PAYMENT_DUE_DATE`, `INVOICE_NUMBER`, `PAYMENT_STATUS_DATE`,
    `CUSTOM_01_COST_CENTER`, `CUSTOM_02_ENTITY`, `CUSTOM_7_COST_CENTER`, `CUSTOM_6_ENTITY`, `PAYMENT_METHOD_TYPE`, `CLOSED_DATE`,
    `SEND_DATE`, `FUNDING_DATE`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('INVOICE_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `INVOICE_NAME`,
    concat('EMPLOYEE_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `EMPLOYEE_NAME`,
    concat('VENDOR_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `VENDOR_NAME`,
    date_add(DATE '2026-01-01', idx - 1) AS `INVOICE_RECEIVED`,
    concat('ORIGIN_SOURCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGIN_SOURCE`,
    concat('APPROVAL_STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `APPROVAL_STATUS`,
    concat('PAYMENT_STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAYMENT_STATUS`,
    CAST(idx * 1000.25 AS DECIMAL(38,10)) AS `REQUEST_TOTAL`,
    concat('REQUEST_KEY_', lpad(CAST(idx AS STRING), 2, '0')) AS `REQUEST_KEY`,
    concat('CHECK_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHECK_NUMBER`,
    date_add(DATE '2026-01-01', idx - 1) AS `CREATE_DATE`,
    concat('DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `DESCRIPTION`,
    CAST(idx * 1000.25 AS DECIMAL(38,10)) AS `INVOICE_AMOUNT`,
    date_add(DATE '2026-01-01', idx - 1) AS `INVOICE_DATE`,
    CAST(idx * 1000.25 AS DECIMAL(38,10)) AS `PAYMENT_AMOUNT`,
    date_add(DATE '2026-01-01', idx - 1) AS `PAYMENT_DUE_DATE`,
    concat('INVOICE_NUMBER_', lpad(CAST(idx AS STRING), 2, '0')) AS `INVOICE_NUMBER`,
    date_add(DATE '2026-01-01', idx - 1) AS `PAYMENT_STATUS_DATE`,
    concat('CUSTOM_01_COST_CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSTOM_01_COST_CENTER`,
    concat('CUSTOM_02_ENTITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSTOM_02_ENTITY`,
    concat('CUSTOM_7_COST_CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSTOM_7_COST_CENTER`,
    concat('CUSTOM_6_ENTITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CUSTOM_6_ENTITY`,
    concat('PAYMENT_METHOD_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAYMENT_METHOD_TYPE`,
    date_add(DATE '2026-01-01', idx - 1) AS `CLOSED_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `SEND_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `FUNDING_DATE`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

SELECT 'file_invoice_requests' AS table_name, COUNT(*) AS record_count
FROM landing.default.file_invoice_requests;
