-- Databricks SQL for source: pershing
-- Generated from sqlserver_dbt/landing-pershing_isrc_rec_a.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS landing_pershing;
USE CATALOG landing_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHING_ISRC_A"
CREATE TABLE IF NOT EXISTS landing_pershing.default.pershing_isrc_a (
    `TRANSACTION_CODE` STRING,
    `RECORD_SEQUENCE_IDENTIFIER` STRING,
    `RECORD_ID_SEQUENCE_NUMBER` INT,
    `CHANGE_INDICATOR` STRING,
    `SOURCE_CODE` STRING,
    `SOURCE_CODE_DESCRIPTION_LINE_ONE` STRING,
    `SOURCE_CODE_DESCRIPTION_LINE_TWO` STRING,
    `SOURCE_CODE_DESCRIPTION_LINE_THREE` STRING,
    `TAX_STATUS` STRING,
    `USERID_OF_PERSON_WHO_LAST_ADDED_UPDATED_RECORD` DATE,
    `DATE_ADDED` DATE,
    `DATE_UPDATED` DATE,
    `IRA_INCOME_ELEGIBLE` STRING,
    `RETAIL_INCOME_ELEGIBLE` STRING,
    `CUSTOMER_FIRM` STRING,
    `CREDIT_DEBIT` DECIMAL(38,10),
    `STATEMENT_INDICATOR` STRING,
    `STATEMENT_ACTIVITY_SUMMARY_INDICATOR` STRING,
    `STATEMENT_ACTIVITY_SUMMARY_NUMBER` STRING,
    `STATEMENT_TRANSACTION_SUMMARY_INDICATOR` STRING,
    `STATEMENT_TRANSACTION_NUMBER` STRING,
    `STATEMENT_DISTRIBUTION_INDICATOR` STRING,
    `STATEMENT_DISTRIBUTION_NUMBER` STRING,
    `STATEMENT_DISTRIBUTION_TAXABLE_INDICATOR` STRING,
    `STATEMENT_DIVIDEND_INDICATOR` STRING,
    `STATEMENT_DIVIDEND_NUMBER` STRING,
    `STATEMENT_DIVIDEND_TAXABLE_INDICATOR` STRING,
    `PERSHING_DEPARTMENT` STRING,
    `PERSHING_GROUP_THAT_MANAGES_THE_SOURCE_CODE` STRING,
    `USERID_OF_PERSON_WHO_ADDED_CODE` STRING,
    `USERID_OF_PERSON_WHO_UPDATED_CODE` DATE,
    `PORTFOLIO_ELIGIBLE_INDICATOR` STRING,
    `REINVEST_INDICATOR` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_pershing.default.pershing_isrc_a IS
'Pershing landing table containing cash, fund, income, security activity, and transaction attributes sourced from SQL Server dbt bronze logic for validation, reconciliation, and downstream brokerage reporting.';

TRUNCATE TABLE landing_pershing.default.pershing_isrc_a;

INSERT INTO landing_pershing.default.pershing_isrc_a (
    `TRANSACTION_CODE`, `RECORD_SEQUENCE_IDENTIFIER`, `RECORD_ID_SEQUENCE_NUMBER`, `CHANGE_INDICATOR`, `SOURCE_CODE`,
    `SOURCE_CODE_DESCRIPTION_LINE_ONE`, `SOURCE_CODE_DESCRIPTION_LINE_TWO`, `SOURCE_CODE_DESCRIPTION_LINE_THREE`,
    `TAX_STATUS`, `USERID_OF_PERSON_WHO_LAST_ADDED_UPDATED_RECORD`, `DATE_ADDED`, `DATE_UPDATED`, `IRA_INCOME_ELEGIBLE`,
    `RETAIL_INCOME_ELEGIBLE`, `CUSTOMER_FIRM`, `CREDIT_DEBIT`, `STATEMENT_INDICATOR`,
    `STATEMENT_ACTIVITY_SUMMARY_INDICATOR`, `STATEMENT_ACTIVITY_SUMMARY_NUMBER`,
    `STATEMENT_TRANSACTION_SUMMARY_INDICATOR`, `STATEMENT_TRANSACTION_NUMBER`, `STATEMENT_DISTRIBUTION_INDICATOR`,
    `STATEMENT_DISTRIBUTION_NUMBER`, `STATEMENT_DISTRIBUTION_TAXABLE_INDICATOR`, `STATEMENT_DIVIDEND_INDICATOR`,
    `STATEMENT_DIVIDEND_NUMBER`, `STATEMENT_DIVIDEND_TAXABLE_INDICATOR`, `PERSHING_DEPARTMENT`,
    `PERSHING_GROUP_THAT_MANAGES_THE_SOURCE_CODE`, `USERID_OF_PERSON_WHO_ADDED_CODE`,
    `USERID_OF_PERSON_WHO_UPDATED_CODE`, `PORTFOLIO_ELIGIBLE_INDICATOR`, `REINVEST_INDICATOR`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('TRANSACTION_CODE_', format_string('%02d', idx)) AS `TRANSACTION_CODE`,
    concat('RECORD_SEQUENCE_IDENTIFI_', format_string('%02d', idx)) AS `RECORD_SEQUENCE_IDENTIFIER`,
    idx AS `RECORD_ID_SEQUENCE_NUMBER`,
    concat('CHANGE_INDICATOR_', format_string('%02d', idx)) AS `CHANGE_INDICATOR`,
    concat('SOURCE_CODE_', format_string('%02d', idx)) AS `SOURCE_CODE`,
    concat('SOURCE_CODE_DESCRIPTION__', format_string('%02d', idx)) AS `SOURCE_CODE_DESCRIPTION_LINE_ONE`,
    concat('SOURCE_CODE_DESCRIPTION__', format_string('%02d', idx)) AS `SOURCE_CODE_DESCRIPTION_LINE_TWO`,
    concat('SOURCE_CODE_DESCRIPTION__', format_string('%02d', idx)) AS `SOURCE_CODE_DESCRIPTION_LINE_THREE`,
    concat('TAX_STATUS_', format_string('%02d', idx)) AS `TAX_STATUS`,
    date_add(DATE '2026-01-01', idx - 1) AS `USERID_OF_PERSON_WHO_LAST_ADDED_UPDATED_RECORD`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_ADDED`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_UPDATED`,
    concat('IRA_INCOME_ELEGIBLE_', format_string('%02d', idx)) AS `IRA_INCOME_ELEGIBLE`,
    concat('RETAIL_INCOME_ELEGIBLE_', format_string('%02d', idx)) AS `RETAIL_INCOME_ELEGIBLE`,
    concat('CUSTOMER_FIRM_', format_string('%02d', idx)) AS `CUSTOMER_FIRM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CREDIT_DEBIT`,
    concat('STATEMENT_INDICATOR_', format_string('%02d', idx)) AS `STATEMENT_INDICATOR`,
    concat('STATEMENT_ACTIVITY_SUMMA_', format_string('%02d', idx)) AS `STATEMENT_ACTIVITY_SUMMARY_INDICATOR`,
    concat('STATEMENT_ACTIVITY_SUMMA_', format_string('%02d', idx)) AS `STATEMENT_ACTIVITY_SUMMARY_NUMBER`,
    concat('STATEMENT_TRANSACTION_SU_', format_string('%02d', idx)) AS `STATEMENT_TRANSACTION_SUMMARY_INDICATOR`,
    concat('STATEMENT_TRANSACTION_NU_', format_string('%02d', idx)) AS `STATEMENT_TRANSACTION_NUMBER`,
    concat('STATEMENT_DISTRIBUTION_I_', format_string('%02d', idx)) AS `STATEMENT_DISTRIBUTION_INDICATOR`,
    concat('STATEMENT_DISTRIBUTION_N_', format_string('%02d', idx)) AS `STATEMENT_DISTRIBUTION_NUMBER`,
    concat('STATEMENT_DISTRIBUTION_T_', format_string('%02d', idx)) AS `STATEMENT_DISTRIBUTION_TAXABLE_INDICATOR`,
    concat('STATEMENT_DIVIDEND_INDIC_', format_string('%02d', idx)) AS `STATEMENT_DIVIDEND_INDICATOR`,
    concat('STATEMENT_DIVIDEND_NUMBE_', format_string('%02d', idx)) AS `STATEMENT_DIVIDEND_NUMBER`,
    concat('STATEMENT_DIVIDEND_TAXAB_', format_string('%02d', idx)) AS `STATEMENT_DIVIDEND_TAXABLE_INDICATOR`,
    concat('PERSHING_DEPARTMENT_', format_string('%02d', idx)) AS `PERSHING_DEPARTMENT`,
    concat('PERSHING_GROUP_THAT_MANA_', format_string('%02d', idx)) AS `PERSHING_GROUP_THAT_MANAGES_THE_SOURCE_CODE`,
    concat('USERID_OF_PERSON_WHO_ADD_', format_string('%02d', idx)) AS `USERID_OF_PERSON_WHO_ADDED_CODE`,
    date_add(DATE '2026-01-01', idx - 1) AS `USERID_OF_PERSON_WHO_UPDATED_CODE`,
    concat('PORTFOLIO_ELIGIBLE_INDIC_', format_string('%02d', idx)) AS `PORTFOLIO_ELIGIBLE_INDICATOR`,
    concat('REINVEST_INDICATOR_', format_string('%02d', idx)) AS `REINVEST_INDICATOR`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershing_isrc_a' AS table_name, COUNT(*) AS record_count
FROM landing_pershing.default.pershing_isrc_a;
