-- Databricks SQL for source: pershing
-- Generated from sqlserver_dbt/landing-pershing_ckff_rec_d.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS landing_pershing;
USE CATALOG landing_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHING_CKFF_D"
CREATE TABLE IF NOT EXISTS landing_pershing.default.pershing_ckff_d (
    `TRANSACTION_CODE` STRING,
    `RECORD_TYPE` STRING,
    `RECORD_ID_SEQUENCE_NUMBER` STRING,
    `ACCOUNT_NUMBER` STRING,
    `TRANSACTION_AMOUNT` DECIMAL(18,2),
    `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_1` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_2` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_3` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_4` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_5` STRING,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_6` STRING,
    `BANK_NAME` STRING,
    `ORD_INST_INFO_1_OR_DESC_TRAN_ADD_INFO_1` STRING,
    `ORD_INST_INFO_2_OR_ABA_NUMBER_ADD_INFO_2` STRING,
    `ORD_INST_INFO_3_OR_DDA_NUMBER_ADD_INFO_3` STRING,
    `ORD_INST_INFO_4_OR_ADD_INFO_4` STRING,
    `ORD_INST_INFO_5_OR_ADD_INFO_5` STRING,
    `ORD_INST_INFO_6_OR_ADD_INFO_6` STRING,
    `ORD_INST_INFO_7_OR_ADD_INFO_7` STRING,
    `ORD_INST_INFO_8_OR_ADD_INFO_8` STRING,
    `ORD_INST_INFO_9_OR_ADD_INFO_9` STRING,
    `INCOMING_WIRE_INDICATOR` STRING,
    `TRANSACTION_IDENTIFIER` STRING,
    `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_pershing.default.pershing_ckff_d IS
'Pershing landing table containing cash, fund, income, security activity, and transaction attributes sourced from SQL Server dbt bronze logic for validation, reconciliation, and downstream brokerage reporting.';

TRUNCATE TABLE landing_pershing.default.pershing_ckff_d;

INSERT INTO landing_pershing.default.pershing_ckff_d (
    `TRANSACTION_CODE`, `RECORD_TYPE`, `RECORD_ID_SEQUENCE_NUMBER`, `ACCOUNT_NUMBER`, `TRANSACTION_AMOUNT`,
    `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`, `ULTIMATE_BENEFICIARY_INFORMATION_LINE_1`,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_2`, `ULTIMATE_BENEFICIARY_INFORMATION_LINE_3`,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_4`, `ULTIMATE_BENEFICIARY_INFORMATION_LINE_5`,
    `ULTIMATE_BENEFICIARY_INFORMATION_LINE_6`, `BANK_NAME`, `ORD_INST_INFO_1_OR_DESC_TRAN_ADD_INFO_1`,
    `ORD_INST_INFO_2_OR_ABA_NUMBER_ADD_INFO_2`, `ORD_INST_INFO_3_OR_DDA_NUMBER_ADD_INFO_3`,
    `ORD_INST_INFO_4_OR_ADD_INFO_4`, `ORD_INST_INFO_5_OR_ADD_INFO_5`, `ORD_INST_INFO_6_OR_ADD_INFO_6`,
    `ORD_INST_INFO_7_OR_ADD_INFO_7`, `ORD_INST_INFO_8_OR_ADD_INFO_8`, `ORD_INST_INFO_9_OR_ADD_INFO_9`,
    `INCOMING_WIRE_INDICATOR`, `TRANSACTION_IDENTIFIER`, `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('TRANSACTION_CODE_', format_string('%02d', idx)) AS `TRANSACTION_CODE`,
    concat('RECORD_TYPE_', format_string('%02d', idx)) AS `RECORD_TYPE`,
    concat('RECORD_ID_SEQUENCE_NUMBE_', format_string('%02d', idx)) AS `RECORD_ID_SEQUENCE_NUMBER`,
    concat('ACCOUNT_NUMBER_', format_string('%02d', idx)) AS `ACCOUNT_NUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,2)) AS `TRANSACTION_AMOUNT`,
    concat('LEGACY_INVESTMENT_PROFES_', format_string('%02d', idx)) AS `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_1`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_2`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_3`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_4`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_5`,
    concat('ULTIMATE_BENEFICIARY_INF_', format_string('%02d', idx)) AS `ULTIMATE_BENEFICIARY_INFORMATION_LINE_6`,
    concat('BANK_NAME_', format_string('%02d', idx)) AS `BANK_NAME`,
    concat('ORD_INST_INFO_1_OR_DESC__', format_string('%02d', idx)) AS `ORD_INST_INFO_1_OR_DESC_TRAN_ADD_INFO_1`,
    concat('ORD_INST_INFO_2_OR_ABA_N_', format_string('%02d', idx)) AS `ORD_INST_INFO_2_OR_ABA_NUMBER_ADD_INFO_2`,
    concat('ORD_INST_INFO_3_OR_DDA_N_', format_string('%02d', idx)) AS `ORD_INST_INFO_3_OR_DDA_NUMBER_ADD_INFO_3`,
    concat('ORD_INST_INFO_4_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_4_OR_ADD_INFO_4`,
    concat('ORD_INST_INFO_5_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_5_OR_ADD_INFO_5`,
    concat('ORD_INST_INFO_6_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_6_OR_ADD_INFO_6`,
    concat('ORD_INST_INFO_7_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_7_OR_ADD_INFO_7`,
    concat('ORD_INST_INFO_8_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_8_OR_ADD_INFO_8`,
    concat('ORD_INST_INFO_9_OR_ADD_I_', format_string('%02d', idx)) AS `ORD_INST_INFO_9_OR_ADD_INFO_9`,
    concat('INCOMING_WIRE_INDICATOR_', format_string('%02d', idx)) AS `INCOMING_WIRE_INDICATOR`,
    concat('TRANSACTION_IDENTIFIER_', format_string('%02d', idx)) AS `TRANSACTION_IDENTIFIER`,
    concat('EXPANDED_INVESTMENT_PROF_', format_string('%02d', idx)) AS `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershing_ckff_d' AS table_name, COUNT(*) AS record_count
FROM landing_pershing.default.pershing_ckff_d;
