-- Databricks SQL for source: jh_cdmasteom
-- Generated from sqlserver/brz-jh_cdmasteom.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_CDMASTEOM"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_cdmasteom (
    `ACCTNO` INT,
    `ACTYPE` INT,
    `SNAME` STRING,
    `CIFNO` INT,
    `TYPE__CS` STRING,
    `ARGPRDCOD` STRING,
    `BR` STRING,
    `GROUP__CS` STRING,
    `GLCOST` INT,
    `GLPROD` INT,
    `ALTADD` STRING,
    `ADDNAM` STRING,
    `ALTNAM` STRING,
    `OFFCR` STRING,
    `STATUS__CS` STRING,
    `CLASS` STRING,
    `CDNUM` INT,
    `ORGBAL` DECIMAL(38,10),
    `CBAL` DECIMAL(38,10),
    `HOLD` DECIMAL(38,10),
    `HLDESC` STRING,
    `STMPAS` STRING,
    `AMTLIN` DECIMAL(38,10),
    `ACCINT` DECIMAL(38,10),
    `ANTINT` DECIMAL(38,10),
    `DAYINT` DECIMAL(38,10),
    `YTDINT` DECIMAL(38,10),
    `PREYTD` DECIMAL(38,10),
    `PREPEN` DECIMAL(38,10),
    `PREFWH` STRING,
    `PRESWH` STRING,
    `TTDINT` DECIMAL(38,10),
    `LTDINT` DECIMAL(38,10),
    `INTPEN` DECIMAL(38,10),
    `PRVPAY` DECIMAL(38,10),
    `PRVBAL` DECIMAL(38,10),
    `YTDCON` DECIMAL(38,10),
    `PENAMT` DECIMAL(38,10),
    `BEGACC` STRING,
    `BEG12M` STRING,
    `YESBAL` DECIMAL(38,10),
    `YESACC` STRING,
    `TODACR` STRING,
    `TODIDR` STRING,
    `TODICR` STRING,
    `INTDRP` DECIMAL(38,10),
    `INTBCK` DECIMAL(38,10),
    `INTPDT` DECIMAL(38,10),
    `STMBAL` DECIMAL(38,10),
    `COLECT` STRING,
    `DEPTRM` STRING,
    `WDTRM` STRING,
    `PENBAL` DECIMAL(38,10),
    `LSTDEP` STRING,
    `QTDWDA` DECIMAL(38,10),
    `MTDWDA` DECIMAL(38,10),
    `MTDEXP` DECIMAL(38,10),
    `QTDEXP` DECIMAL(38,10),
    `YTDEXP` DECIMAL(38,10),
    `CDMTDWAIVE` DECIMAL(38,10),
    `CDQTDWAIVE` DECIMAL(38,10),
    `CDYTDWAIVE` DECIMAL(38,10),
    `CDLTDWAIVE` DECIMAL(38,10),
    `AGGBAL` DECIMAL(38,10),
    `AGGACC` STRING,
    `AGGDAY` STRING,
    `ISSDT6` STRING,
    `RENDT6` STRING,
    `LPDAT6` STRING,
    `NPDAT6` STRING,
    `MATDT6` STRING,
    `ORGDM6` STRING,
    `RDMDT6` STRING,
    `LMDAT6` STRING,
    `REVDT6` STRING,
    `STMDT6` STRING,
    `ENTRD6` STRING,
    `ACTVD6` STRING,
    `LDEPD6` STRING,
    `CONTD6` STRING,
    `CNVDT6` STRING,
    `DAYMO` STRING,
    `ISSDT` STRING,
    `RENDT` STRING,
    `LPDAT` STRING,
    `NPDAT` STRING,
    `MATDT` STRING,
    `ORGDMT` STRING,
    `RDMDT` STRING,
    `LMDAT` STRING,
    `REVDT` STRING,
    `STMDT` STRING,
    `ENTRDT` STRING,
    `ACTVDT` STRING,
    `LDEPDT` STRING,
    `CONTDT` STRING,
    `CNVDT7` STRING,
    `CDTERM` STRING,
    `CDTCOD` STRING,
    `ORGTRM` STRING,
    `ORGTCD` STRING,
    `INTERM` DECIMAL(38,10),
    `ITCODE` STRING,
    `RENEW` STRING,
    `DISP` STRING,
    `COMCHK` STRING,
    `METHOD` STRING,
    `YRBASE` STRING,
    `EVENCD` STRING,
    `EVNCHG` DECIMAL(38,10),
    `DACT` STRING,
    `DACTYP` STRING,
    `CKPCIF` STRING,
    `PRVTRM` STRING,
    `PRVTCD` STRING,
    `PRVMT6` STRING,
    `PRVMT7` STRING,
    `RATE` DECIMAL(38,10),
    `VARY` STRING,
    `VARYCD` STRING,
    `FLOOR` STRING,
    `CEIL` STRING,
    `REVTRM` STRING,
    `RTCODE` STRING,
    `RATE__CS` DECIMAL(38,10),
    `RATSCH` STRING,
    `WHCODE` STRING,
    `WALTAC` STRING,
    `WALTTP` STRING,
    `WALTRT` STRING,
    `WHMTD` DECIMAL(38,10),
    `WHQTD` DECIMAL(38,10),
    `WHYTD` DECIMAL(38,10),
    `STATE__CS` STRING,
    `CRASTA` STRING,
    `COUNTY` STRING,
    `WHSCOD` STRING,
    `WALTSR` STRING,
    `WHSMTD` DECIMAL(38,10),
    `WHSQTD` DECIMAL(38,10),
    `WHSYTD` DECIMAL(38,10),
    `OVRNYN` STRING,
    `OVRNRT` STRING,
    `OVRNR` STRING,
    `WDATE6` STRING,
    `WDATE7` STRING,
    `CDAGGD` STRING,
    `CDAGGB` STRING,
    `CDINTE` DECIMAL(38,10),
    `CALREPT` STRING,
    `CDSIC1` STRING,
    `CDSIC2` STRING,
    `CDSIC3` STRING,
    `CDSIC4` STRING,
    `CDUSER` STRING,
    `MESSAG` STRING,
    `INCLUD` STRING,
    `HMAIL` STRING,
    `CHKCOD` STRING,
    `CHDCOD` STRING,
    `IRACOD` STRING,
    `BLOCK__CS` STRING,
    `PENTYP` DECIMAL(38,10),
    `OIDFLG` STRING,
    `MATCOD` STRING,
    `STMTCD` STRING,
    `ALMTYP` STRING,
    `PLAN__CS` STRING,
    `DISSEQ` STRING,
    `ORGSRC` STRING,
    `SMSA` STRING,
    `CRALOC` STRING,
    `ZIPCOD` STRING,
    `INDCOD` STRING,
    `CENSUS` STRING,
    `PAPLES` STRING,
    `PALAST` STRING,
    `ALNXTI` STRING,
    `MLTDRT` DECIMAL(38,10),
    `FLCODE` STRING,
    `SECURE` STRING,
    `CDREGP` STRING,
    `CDPIC1` STRING,
    `CDPIC2` STRING,
    `CDPDT1` STRING,
    `CDPD61` STRING,
    `CDPDT2` STRING,
    `CDPD62` STRING,
    `CDPAM1` STRING,
    `CDPAM2` STRING,
    `QTDNEW` DECIMAL(38,10),
    `MTDNEW` DECIMAL(38,10),
    `QTDWD` DECIMAL(38,10),
    `MTDWD` DECIMAL(38,10),
    `BIFMBR` STRING,
    `SAIFMB` STRING,
    `FDICMB` STRING,
    `CDCLOSEDRS` STRING,
    `RNTYPE` STRING,
    `OKFLAG` STRING,
    `OKBIFA` STRING,
    `OKBIF6` STRING,
    `OKBIF7` STRING,
    `OKSAIF` STRING,
    `OKSAI6` STRING,
    `OKSAI7` STRING,
    `OKSOLD` STRING,
    `OKSLD6` STRING,
    `OKSLD7` STRING,
    `OKFDIC` STRING,
    `OVRDLY` STRING,
    `OVRDYS` STRING,
    `SALESAC` STRING,
    `DORDT6` STRING,
    `DORDT7` STRING,
    `DORDYS` STRING,
    `CDLANG` STRING,
    `CDJHA1` STRING,
    `CDJHA2` STRING,
    `CDJHA3` STRING,
    `CDJHA4` STRING,
    `CDJHA11` STRING,
    `CDJHA12` STRING,
    `CDJHA13` STRING,
    `CDJHA14` STRING,
    `CDJHA61` STRING,
    `CDJHA71` STRING,
    `CDJHA62` STRING,
    `CDJHA72` STRING,
    `REGAGG` STRING,
    `WDGTRM` STRING,
    `WDPTRM` STRING,
    `MTDAGD` DECIMAL(38,10),
    `MTDINTACC` DECIMAL(38,10),
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_cdmasteom IS
'The JH CDMAST landing table captures certificate of deposit master account attributes, including account identity, customer, status, balance, interest, maturity, renewal, rate, withholding, and cycle fields for CD account validation, reconciliation, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_cdmasteom;

INSERT INTO landing_jh.default.jh_cdmasteom (
    `ACCTNO`, `ACTYPE`, `SNAME`, `CIFNO`, `TYPE__CS`, `ARGPRDCOD`,
    `BR`, `GROUP__CS`, `GLCOST`, `GLPROD`, `ALTADD`, `ADDNAM`,
    `ALTNAM`, `OFFCR`, `STATUS__CS`, `CLASS`, `CDNUM`, `ORGBAL`,
    `CBAL`, `HOLD`, `HLDESC`, `STMPAS`, `AMTLIN`, `ACCINT`,
    `ANTINT`, `DAYINT`, `YTDINT`, `PREYTD`, `PREPEN`, `PREFWH`,
    `PRESWH`, `TTDINT`, `LTDINT`, `INTPEN`, `PRVPAY`, `PRVBAL`,
    `YTDCON`, `PENAMT`, `BEGACC`, `BEG12M`, `YESBAL`, `YESACC`,
    `TODACR`, `TODIDR`, `TODICR`, `INTDRP`, `INTBCK`, `INTPDT`,
    `STMBAL`, `COLECT`, `DEPTRM`, `WDTRM`, `PENBAL`, `LSTDEP`,
    `QTDWDA`, `MTDWDA`, `MTDEXP`, `QTDEXP`, `YTDEXP`, `CDMTDWAIVE`,
    `CDQTDWAIVE`, `CDYTDWAIVE`, `CDLTDWAIVE`, `AGGBAL`, `AGGACC`, `AGGDAY`,
    `ISSDT6`, `RENDT6`, `LPDAT6`, `NPDAT6`, `MATDT6`, `ORGDM6`,
    `RDMDT6`, `LMDAT6`, `REVDT6`, `STMDT6`, `ENTRD6`, `ACTVD6`,
    `LDEPD6`, `CONTD6`, `CNVDT6`, `DAYMO`, `ISSDT`, `RENDT`,
    `LPDAT`, `NPDAT`, `MATDT`, `ORGDMT`, `RDMDT`, `LMDAT`,
    `REVDT`, `STMDT`, `ENTRDT`, `ACTVDT`, `LDEPDT`, `CONTDT`,
    `CNVDT7`, `CDTERM`, `CDTCOD`, `ORGTRM`, `ORGTCD`, `INTERM`,
    `ITCODE`, `RENEW`, `DISP`, `COMCHK`, `METHOD`, `YRBASE`,
    `EVENCD`, `EVNCHG`, `DACT`, `DACTYP`, `CKPCIF`, `PRVTRM`,
    `PRVTCD`, `PRVMT6`, `PRVMT7`, `RATE`, `VARY`, `VARYCD`,
    `FLOOR`, `CEIL`, `REVTRM`, `RTCODE`, `RATE__CS`, `RATSCH`,
    `WHCODE`, `WALTAC`, `WALTTP`, `WALTRT`, `WHMTD`, `WHQTD`,
    `WHYTD`, `STATE__CS`, `CRASTA`, `COUNTY`, `WHSCOD`, `WALTSR`,
    `WHSMTD`, `WHSQTD`, `WHSYTD`, `OVRNYN`, `OVRNRT`, `OVRNR`,
    `WDATE6`, `WDATE7`, `CDAGGD`, `CDAGGB`, `CDINTE`, `CALREPT`,
    `CDSIC1`, `CDSIC2`, `CDSIC3`, `CDSIC4`, `CDUSER`, `MESSAG`,
    `INCLUD`, `HMAIL`, `CHKCOD`, `CHDCOD`, `IRACOD`, `BLOCK__CS`,
    `PENTYP`, `OIDFLG`, `MATCOD`, `STMTCD`, `ALMTYP`, `PLAN__CS`,
    `DISSEQ`, `ORGSRC`, `SMSA`, `CRALOC`, `ZIPCOD`, `INDCOD`,
    `CENSUS`, `PAPLES`, `PALAST`, `ALNXTI`, `MLTDRT`, `FLCODE`,
    `SECURE`, `CDREGP`, `CDPIC1`, `CDPIC2`, `CDPDT1`, `CDPD61`,
    `CDPDT2`, `CDPD62`, `CDPAM1`, `CDPAM2`, `QTDNEW`, `MTDNEW`,
    `QTDWD`, `MTDWD`, `BIFMBR`, `SAIFMB`, `FDICMB`, `CDCLOSEDRS`,
    `RNTYPE`, `OKFLAG`, `OKBIFA`, `OKBIF6`, `OKBIF7`, `OKSAIF`,
    `OKSAI6`, `OKSAI7`, `OKSOLD`, `OKSLD6`, `OKSLD7`, `OKFDIC`,
    `OVRDLY`, `OVRDYS`, `SALESAC`, `DORDT6`, `DORDT7`, `DORDYS`,
    `CDLANG`, `CDJHA1`, `CDJHA2`, `CDJHA3`, `CDJHA4`, `CDJHA11`,
    `CDJHA12`, `CDJHA13`, `CDJHA14`, `CDJHA61`, `CDJHA71`, `CDJHA62`,
    `CDJHA72`, `REGAGG`, `WDGTRM`, `WDPTRM`, `MTDAGD`, `MTDINTACC`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `ACCTNO`,
    idx AS `ACTYPE`,
    concat('SNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `SNAME`,
    idx AS `CIFNO`,
    concat('TYPE__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `TYPE__CS`,
    concat('ARGPRDCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARGPRDCOD`,
    concat('BR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BR`,
    concat('GROUP__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `GROUP__CS`,
    idx AS `GLCOST`,
    idx AS `GLPROD`,
    concat('ALTADD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALTADD`,
    concat('ADDNAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADDNAM`,
    concat('ALTNAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALTNAM`,
    concat('OFFCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFCR`,
    concat('STATUS__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `STATUS__CS`,
    concat('CLASS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLASS`,
    idx AS `CDNUM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ORGBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `HOLD`,
    concat('HLDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `HLDESC`,
    concat('STMPAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `STMPAS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AMTLIN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ACCINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ANTINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DAYINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PREYTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PREPEN`,
    concat('PREFWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREFWH`,
    concat('PRESWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRESWH`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TTDINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LTDINT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTPEN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRVPAY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRVBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDCON`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PENAMT`,
    concat('BEGACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGACC`,
    concat('BEG12M_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEG12M`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YESBAL`,
    concat('YESACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `YESACC`,
    concat('TODACR_', lpad(CAST(idx AS STRING), 2, '0')) AS `TODACR`,
    concat('TODIDR_', lpad(CAST(idx AS STRING), 2, '0')) AS `TODIDR`,
    concat('TODICR_', lpad(CAST(idx AS STRING), 2, '0')) AS `TODICR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTDRP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTBCK`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTPDT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `STMBAL`,
    concat('COLECT_', lpad(CAST(idx AS STRING), 2, '0')) AS `COLECT`,
    concat('DEPTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `DEPTRM`,
    concat('WDTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WDTRM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PENBAL`,
    concat('LSTDEP_', lpad(CAST(idx AS STRING), 2, '0')) AS `LSTDEP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDWDA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDWDA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDEXP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDEXP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDEXP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CDMTDWAIVE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CDQTDWAIVE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CDYTDWAIVE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CDLTDWAIVE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AGGBAL`,
    concat('AGGACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AGGACC`,
    concat('AGGDAY_', lpad(CAST(idx AS STRING), 2, '0')) AS `AGGDAY`,
    concat('ISSDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `ISSDT6`,
    concat('RENDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `RENDT6`,
    concat('LPDAT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `LPDAT6`,
    concat('NPDAT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `NPDAT6`,
    concat('MATDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `MATDT6`,
    concat('ORGDM6_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGDM6`,
    concat('RDMDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `RDMDT6`,
    concat('LMDAT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMDAT6`,
    concat('REVDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `REVDT6`,
    concat('STMDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `STMDT6`,
    concat('ENTRD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `ENTRD6`,
    concat('ACTVD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTVD6`,
    concat('LDEPD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `LDEPD6`,
    concat('CONTD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CONTD6`,
    concat('CNVDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CNVDT6`,
    concat('DAYMO_', lpad(CAST(idx AS STRING), 2, '0')) AS `DAYMO`,
    concat('ISSDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ISSDT`,
    concat('RENDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `RENDT`,
    concat('LPDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LPDAT`,
    concat('NPDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `NPDAT`,
    concat('MATDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `MATDT`,
    concat('ORGDMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGDMT`,
    concat('RDMDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `RDMDT`,
    concat('LMDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMDAT`,
    concat('REVDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `REVDT`,
    concat('STMDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `STMDT`,
    concat('ENTRDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ENTRDT`,
    concat('ACTVDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTVDT`,
    concat('LDEPDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LDEPDT`,
    concat('CONTDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CONTDT`,
    concat('CNVDT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CNVDT7`,
    concat('CDTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDTERM`,
    concat('CDTCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDTCOD`,
    concat('ORGTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGTRM`,
    concat('ORGTCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGTCD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTERM`,
    concat('ITCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ITCODE`,
    concat('RENEW_', lpad(CAST(idx AS STRING), 2, '0')) AS `RENEW`,
    concat('DISP_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISP`,
    concat('COMCHK_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMCHK`,
    concat('METHOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `METHOD`,
    concat('YRBASE_', lpad(CAST(idx AS STRING), 2, '0')) AS `YRBASE`,
    concat('EVENCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `EVENCD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EVNCHG`,
    concat('DACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `DACT`,
    concat('DACTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `DACTYP`,
    concat('CKPCIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `CKPCIF`,
    concat('PRVTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRVTRM`,
    concat('PRVTCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRVTCD`,
    concat('PRVMT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRVMT6`,
    concat('PRVMT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRVMT7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RATE`,
    concat('VARY_', lpad(CAST(idx AS STRING), 2, '0')) AS `VARY`,
    concat('VARYCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `VARYCD`,
    concat('FLOOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `FLOOR`,
    concat('CEIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CEIL`,
    concat('REVTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `REVTRM`,
    concat('RTCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `RTCODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RATE__CS`,
    concat('RATSCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `RATSCH`,
    concat('WHCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `WHCODE`,
    concat('WALTAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `WALTAC`,
    concat('WALTTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `WALTTP`,
    concat('WALTRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `WALTRT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHMTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHQTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHYTD`,
    concat('STATE__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `STATE__CS`,
    concat('CRASTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRASTA`,
    concat('COUNTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `COUNTY`,
    concat('WHSCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `WHSCOD`,
    concat('WALTSR_', lpad(CAST(idx AS STRING), 2, '0')) AS `WALTSR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHSMTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHSQTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHSYTD`,
    concat('OVRNYN_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVRNYN`,
    concat('OVRNRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVRNRT`,
    concat('OVRNR_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVRNR`,
    concat('WDATE6_', lpad(CAST(idx AS STRING), 2, '0')) AS `WDATE6`,
    concat('WDATE7_', lpad(CAST(idx AS STRING), 2, '0')) AS `WDATE7`,
    concat('CDAGGD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDAGGD`,
    concat('CDAGGB_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDAGGB`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CDINTE`,
    concat('CALREPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CALREPT`,
    concat('CDSIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDSIC1`,
    concat('CDSIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDSIC2`,
    concat('CDSIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDSIC3`,
    concat('CDSIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDSIC4`,
    concat('CDUSER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDUSER`,
    concat('MESSAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `MESSAG`,
    concat('INCLUD_', lpad(CAST(idx AS STRING), 2, '0')) AS `INCLUD`,
    concat('HMAIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `HMAIL`,
    concat('CHKCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHKCOD`,
    concat('CHDCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHDCOD`,
    concat('IRACOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `IRACOD`,
    concat('BLOCK__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `BLOCK__CS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PENTYP`,
    concat('OIDFLG_', lpad(CAST(idx AS STRING), 2, '0')) AS `OIDFLG`,
    concat('MATCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `MATCOD`,
    concat('STMTCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `STMTCD`,
    concat('ALMTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALMTYP`,
    concat('PLAN__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLAN__CS`,
    concat('DISSEQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `DISSEQ`,
    concat('ORGSRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGSRC`,
    concat('SMSA_', lpad(CAST(idx AS STRING), 2, '0')) AS `SMSA`,
    concat('CRALOC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRALOC`,
    concat('ZIPCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ZIPCOD`,
    concat('INDCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `INDCOD`,
    concat('CENSUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CENSUS`,
    concat('PAPLES_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAPLES`,
    concat('PALAST_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALAST`,
    concat('ALNXTI_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALNXTI`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MLTDRT`,
    concat('FLCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FLCODE`,
    concat('SECURE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SECURE`,
    concat('CDREGP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDREGP`,
    concat('CDPIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPIC1`,
    concat('CDPIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPIC2`,
    concat('CDPDT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPDT1`,
    concat('CDPD61_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPD61`,
    concat('CDPDT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPDT2`,
    concat('CDPD62_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPD62`,
    concat('CDPAM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPAM1`,
    concat('CDPAM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDPAM2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDNEW`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDNEW`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDWD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDWD`,
    concat('BIFMBR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BIFMBR`,
    concat('SAIFMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `SAIFMB`,
    concat('FDICMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `FDICMB`,
    concat('CDCLOSEDRS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDCLOSEDRS`,
    concat('RNTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `RNTYPE`,
    concat('OKFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKFLAG`,
    concat('OKBIFA_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKBIFA`,
    concat('OKBIF6_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKBIF6`,
    concat('OKBIF7_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKBIF7`,
    concat('OKSAIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSAIF`,
    concat('OKSAI6_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSAI6`,
    concat('OKSAI7_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSAI7`,
    concat('OKSOLD_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSOLD`,
    concat('OKSLD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSLD6`,
    concat('OKSLD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKSLD7`,
    concat('OKFDIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OKFDIC`,
    concat('OVRDLY_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVRDLY`,
    concat('OVRDYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `OVRDYS`,
    concat('SALESAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `SALESAC`,
    concat('DORDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DORDT6`,
    concat('DORDT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DORDT7`,
    concat('DORDYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `DORDYS`,
    concat('CDLANG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDLANG`,
    concat('CDJHA1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA1`,
    concat('CDJHA2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA2`,
    concat('CDJHA3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA3`,
    concat('CDJHA4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA4`,
    concat('CDJHA11_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA11`,
    concat('CDJHA12_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA12`,
    concat('CDJHA13_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA13`,
    concat('CDJHA14_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA14`,
    concat('CDJHA61_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA61`,
    concat('CDJHA71_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA71`,
    concat('CDJHA62_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA62`,
    concat('CDJHA72_', lpad(CAST(idx AS STRING), 2, '0')) AS `CDJHA72`,
    concat('REGAGG_', lpad(CAST(idx AS STRING), 2, '0')) AS `REGAGG`,
    concat('WDGTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WDGTRM`,
    concat('WDPTRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `WDPTRM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDAGD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDINTACC`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_cdmasteom' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_cdmasteom;
