-- Databricks SQL for source: pershing
-- Generated from sqlserver_dbt/landing-pershing_gcus_rec_b.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS landing_pershing;
USE CATALOG landing_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHING_GCUS_B"
CREATE TABLE IF NOT EXISTS landing_pershing.default.pershing_gcus_b (
    `TRANSACTION_CODE` STRING,
    `RECORD_INDICATOR_VALUE` DECIMAL(38,10),
    `RECORD_ID_SEQUENCE_NUMBER` INT,
    `ACCOUNT_NUMBER` STRING,
    `CUSIP_NUMBER` STRING,
    `PORTFOLIO_CURRENCY` STRING,
    `UNDERLYING_CUSIP_NUMBER` STRING,
    `COUNTRY_CODE` STRING,
    `IP` STRING,
    `IBDNUMBER` STRING,
    `FULLY_PAID_LENDING_QTY` DECIMAL(18,5),
    `FULLY_PAID_LENDING_QTY_COLLAT_AMT` DECIMAL(18,3),
    `OPTION_ROOT_ID` STRING,
    `EXPIRATION_DATE` DATE,
    `CALL_PUT_INDICATOR` STRING,
    `STRIKE_PRICE_B` DECIMAL(8,3),
    `TRADE_DATE_REPO_QTY` DECIMAL(18,5),
    `SETTLEMENT_DATE_REPO_QTY` DECIMAL(18,5),
    `TRADE_DATE_REVERSE_REPO_QTY` DECIMAL(18,5),
    `SETTLEMENT_DATE_REVERSE_REPO_QTY` DECIMAL(18,5),
    `COLLAT_PLEDGE_QTY` DECIMAL(18,5),
    `CORP_EXEC_SERVICES_COLLAT_PLEDGE_QTY` DECIMAL(18,5),
    `TRADE_DATE_REPO_LIQUIDATING_VALUE` DECIMAL(18,3),
    `SETTLEMENT_DATE_REPO_LIQUIDATING_VALUE` DECIMAL(18,3),
    `TRADE_DATE_REVERSE_REPO_LIQUIDATING_VALUE` DECIMAL(18,3),
    `SETTLEMENT_DATE_REVERSE_REPO_LIQUIDATING_VALUE` DECIMAL(18,3),
    `COLLAT_PLEDGE_LIQUIDATING_VALUE` DECIMAL(18,3),
    `CORP_EXEC_SERVICES_COLLAT_PLEDGE_LIQUIDATING_VALUE` DECIMAL(18,3),
    `TRADE_DATE_REPO_LOAN_AMOUNT` DECIMAL(18,3),
    `SETTLEMENT_DATE_REPO_LOAN_AMOUNT` DECIMAL(18,3),
    `TRADE_DATE_REVERSE_REPO_LOAN_AMOUNT` DECIMAL(18,3),
    `SETTLEMENT_DATE_REVERSE_REPO_LOAN_AMOUNT` DECIMAL(18,3),
    `ACCRUED_INTEREST_VALUE_FROM_LAST_PAYABLE` DECIMAL(18,3),
    `DIVIDEND_or_COUPON_RATE` DECIMAL(18,9),
    `PENDING_SPLIT_QTY_LIQUIDATING_VALUE` DECIMAL(18,3),
    `INTERNATIONAL_NON_DOLLAR_SYMBOL` DECIMAL(38,10),
    `PLEDGED_QTY_MEMO` DECIMAL(18,5),
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_pershing.default.pershing_gcus_b IS
'Pershing landing table containing customer, address, tax, and contact attributes sourced from SQL Server dbt bronze logic for validation, reconciliation, and downstream brokerage reporting.';

TRUNCATE TABLE landing_pershing.default.pershing_gcus_b;

INSERT INTO landing_pershing.default.pershing_gcus_b (
    `TRANSACTION_CODE`, `RECORD_INDICATOR_VALUE`, `RECORD_ID_SEQUENCE_NUMBER`, `ACCOUNT_NUMBER`, `CUSIP_NUMBER`,
    `PORTFOLIO_CURRENCY`, `UNDERLYING_CUSIP_NUMBER`, `COUNTRY_CODE`, `IP`, `IBDNUMBER`, `FULLY_PAID_LENDING_QTY`,
    `FULLY_PAID_LENDING_QTY_COLLAT_AMT`, `OPTION_ROOT_ID`, `EXPIRATION_DATE`, `CALL_PUT_INDICATOR`, `STRIKE_PRICE_B`,
    `TRADE_DATE_REPO_QTY`, `SETTLEMENT_DATE_REPO_QTY`, `TRADE_DATE_REVERSE_REPO_QTY`,
    `SETTLEMENT_DATE_REVERSE_REPO_QTY`, `COLLAT_PLEDGE_QTY`, `CORP_EXEC_SERVICES_COLLAT_PLEDGE_QTY`,
    `TRADE_DATE_REPO_LIQUIDATING_VALUE`, `SETTLEMENT_DATE_REPO_LIQUIDATING_VALUE`,
    `TRADE_DATE_REVERSE_REPO_LIQUIDATING_VALUE`, `SETTLEMENT_DATE_REVERSE_REPO_LIQUIDATING_VALUE`,
    `COLLAT_PLEDGE_LIQUIDATING_VALUE`, `CORP_EXEC_SERVICES_COLLAT_PLEDGE_LIQUIDATING_VALUE`,
    `TRADE_DATE_REPO_LOAN_AMOUNT`, `SETTLEMENT_DATE_REPO_LOAN_AMOUNT`, `TRADE_DATE_REVERSE_REPO_LOAN_AMOUNT`,
    `SETTLEMENT_DATE_REVERSE_REPO_LOAN_AMOUNT`, `ACCRUED_INTEREST_VALUE_FROM_LAST_PAYABLE`, `DIVIDEND_or_COUPON_RATE`,
    `PENDING_SPLIT_QTY_LIQUIDATING_VALUE`, `INTERNATIONAL_NON_DOLLAR_SYMBOL`, `PLEDGED_QTY_MEMO`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('TRANSACTION_CODE_', format_string('%02d', idx)) AS `TRANSACTION_CODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RECORD_INDICATOR_VALUE`,
    idx AS `RECORD_ID_SEQUENCE_NUMBER`,
    concat('ACCOUNT_NUMBER_', format_string('%02d', idx)) AS `ACCOUNT_NUMBER`,
    concat('CUSIP_NUMBER_', format_string('%02d', idx)) AS `CUSIP_NUMBER`,
    concat('PORTFOLIO_CURRENCY_', format_string('%02d', idx)) AS `PORTFOLIO_CURRENCY`,
    concat('UNDERLYING_CUSIP_NUMBER_', format_string('%02d', idx)) AS `UNDERLYING_CUSIP_NUMBER`,
    concat('COUNTRY_CODE_', format_string('%02d', idx)) AS `COUNTRY_CODE`,
    concat('IP_', format_string('%02d', idx)) AS `IP`,
    concat('IBDNUMBER_', format_string('%02d', idx)) AS `IBDNUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `FULLY_PAID_LENDING_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `FULLY_PAID_LENDING_QTY_COLLAT_AMT`,
    concat('OPTION_ROOT_ID_', format_string('%02d', idx)) AS `OPTION_ROOT_ID`,
    date_add(DATE '2026-01-01', idx - 1) AS `EXPIRATION_DATE`,
    concat('CALL_PUT_INDICATOR_', format_string('%02d', idx)) AS `CALL_PUT_INDICATOR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(8,3)) AS `STRIKE_PRICE_B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `TRADE_DATE_REPO_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `SETTLEMENT_DATE_REPO_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `TRADE_DATE_REVERSE_REPO_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `SETTLEMENT_DATE_REVERSE_REPO_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `COLLAT_PLEDGE_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `CORP_EXEC_SERVICES_COLLAT_PLEDGE_QTY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `TRADE_DATE_REPO_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `SETTLEMENT_DATE_REPO_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `TRADE_DATE_REVERSE_REPO_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `SETTLEMENT_DATE_REVERSE_REPO_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `COLLAT_PLEDGE_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `CORP_EXEC_SERVICES_COLLAT_PLEDGE_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `TRADE_DATE_REPO_LOAN_AMOUNT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `SETTLEMENT_DATE_REPO_LOAN_AMOUNT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `TRADE_DATE_REVERSE_REPO_LOAN_AMOUNT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `SETTLEMENT_DATE_REVERSE_REPO_LOAN_AMOUNT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `ACCRUED_INTEREST_VALUE_FROM_LAST_PAYABLE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,9)) AS `DIVIDEND_or_COUPON_RATE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,3)) AS `PENDING_SPLIT_QTY_LIQUIDATING_VALUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTERNATIONAL_NON_DOLLAR_SYMBOL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,5)) AS `PLEDGED_QTY_MEMO`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershing_gcus_b' AS table_name, COUNT(*) AS record_count
FROM landing_pershing.default.pershing_gcus_b;
