-- Databricks SQL for source: jh_lnpar2
-- Generated from sqlserver_brz/brz-jh_lnpar2.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_LNPAR2"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_lnpar2 (
    `PTYPE` STRING,
    `PTYDSC` STRING,
    `PLNGRP` STRING,
    `PGRDSC` STRING,
    `P2COST` STRING,
    `P2PROD` STRING,
    `P2IQNM` STRING,
    `PIBASE` STRING,
    `PDEPTC` STRING,
    `P1098C` STRING,
    `PCRREP` STRING,
    `PCRTYP` STRING,
    `PBKDYS` STRING,
    `P2HECONV` STRING,
    `P2OVMCHK$` STRING,
    `P2MCHKFP` STRING,
    `P2MNCKAVL` STRING,
    `P2CNVTYP` STRING,
    `P2CLSHELC` STRING,
    `P2REAMCNV` STRING,
    `PMINRT` STRING,
    `PMAXRT` STRING,
    `PINCLU` STRING,
    `PFREQ` STRING,
    `PFCODE` STRING,
    `PSMDY1` STRING,
    `PSMDY2` STRING,
    `PPMTCD` STRING,
    `PLATCD` STRING,
    `P2IGLC` STRING,
    `PPDNOT` STRING,
    `PPDNLC` STRING,
    `PCDNOT` STRING,
    `PCPN` STRING,
    `PMINCG` STRING,
    `PCLASS` STRING,
    `PPRCPM` STRING,
    `P1STPD` STRING,
    `P2NDPD` STRING,
    `P3RDPD` STRING,
    `P4THPD` STRING,
    `P5THPD` STRING,
    `P6THPD` STRING,
    `P7THPD` STRING,
    `P8THPD` STRING,
    `P9THPD` STRING,
    `P1STPDS` STRING,
    `P2NDPDS` STRING,
    `P3RDPDS` STRING,
    `P4THPDS` STRING,
    `P5THPDS` STRING,
    `P6THPDS` STRING,
    `P7THPDS` STRING,
    `P8THPDS` STRING,
    `P9THPDS` STRING,
    `PPDRPT` STRING,
    `PMAXLC` STRING,
    `PMNNEW` STRING,
    `PRHSNW` STRING,
    `PRHSPD` STRING,
    `PRHSPO` STRING,
    `PDHSDY` STRING,
    `PBLNDY` STRING,
    `POTOL` STRING,
    `PMTBOA` STRING,
    `RETPDB` STRING,
    `PRDTBK` STRING,
    `PRLDBK` STRING,
    `PRMEBK` STRING,
    `PRMTBK` STRING,
    `PMNRBK` STRING,
    `PRCNOT` STRING,
    `PRCNTR` STRING,
    `PBLLBR` STRING,
    `PRBEXF` STRING,
    `PPRRTC` STRING,
    `PRTCDY` STRING,
    `PRTCMX` STRING,
    `PRTCDF` STRING,
    `PDCBTR` STRING,
    `PMIAMR` STRING,
    `PCALRE` STRING,
    `PALTSC` STRING,
    `PHMAIL` STRING,
    `PTITLE` STRING,
    `PCLSZR` STRING,
    `PSTATU` STRING,
    `PREAMO` STRING,
    `PESCRO` STRING,
    `PPARTI` STRING,
    `PHASAR` STRING,
    `PALMTY` STRING,
    `PALWBD` STRING,
    `PDOCTR` STRING,
    `PPPPCD` STRING,
    `PUSESP` STRING,
    `PPDMTH` STRING,
    `PIOEPI` STRING,
    `PIOENB` STRING,
    `PNEGAM` STRING,
    `PNEGIN` STRING,
    `PADDCP` STRING,
    `PSUBPS` STRING,
    `P2STMD` STRING,
    `P2CPLT` STRING,
    `P2CPIC` STRING,
    `P2NAST` STRING,
    `P2NADY` STRING,
    `P2NAAC` STRING,
    `P2NAPO` STRING,
    `P2RADV` STRING,
    `P2RPMT` STRING,
    `P2MATN` STRING,
    `P2MATD` STRING,
    `P2ARMC` STRING,
    `P2UCSH` STRING,
    `P2EAD6` STRING,
    `P2EAD7` STRING,
    `P2ESCO` STRING,
    `P2INTO` DECIMAL(38,10),
    `P2LTCO` STRING,
    `P2OTHO` STRING,
    `P2PRNO` INT,
    `P2INSO` STRING,
    `P2SALA` STRING,
    `P2FFOL` STRING,
    `PAFTFC` STRING,
    `PRJADV` STRING,
    `PCLRBL` STRING,
    `P2TRUE` STRING,
    `P2DIFP` STRING,
    `P2DBIT` STRING,
    `P2DIFD` STRING,
    `P2ZERO` STRING,
    `P2PSST` STRING,
    `P2STMT` STRING,
    `P2STMR` STRING,
    `P2STMP` STRING,
    `P2PMNT` STRING,
    `P2FREZ` STRING,
    `P2FRZG` STRING,
    `P2TAKP` STRING,
    `P2INCR` STRING,
    `P2MNAV` STRING,
    `P2MNDD` STRING,
    `P2MRAT` STRING,
    `P2MCHK` STRING,
    `P2RAT1` STRING,
    `P2NEGB` STRING,
    `P2AVAL` STRING,
    `P2DAVL` STRING,
    `P2RDUM` STRING,
    `P2PREF` STRING,
    `P2BLAD` STRING,
    `P2CLRQ` STRING,
    `P2CLRS` STRING,
    `P2STML` STRING,
    `P2PPMS` STRING,
    `P2P1PM` STRING,
    `P2POLT` STRING,
    `P2UPAR` STRING,
    `P2RTOL` STRING,
    `P2CCOL` STRING,
    `P2NEGP` STRING,
    `P2NSFE` STRING,
    `PDSLOP` STRING,
    `PDSLT1` STRING,
    `PDSLT2` STRING,
    `PDSLT3` STRING,
    `PDSLT4` STRING,
    `PDSLT5` STRING,
    `PDSLM1` STRING,
    `PDSLM2` STRING,
    `PDSLM3` STRING,
    `PDSLM4` STRING,
    `PDSLM5` STRING,
    `PDSGOP` STRING,
    `PDSGT1` STRING,
    `PDSGT2` STRING,
    `PDSGT3` STRING,
    `PDSGT4` STRING,
    `PDSGT5` STRING,
    `PDSGM1` STRING,
    `PDSGM2` STRING,
    `PDSGM3` STRING,
    `PDSGM4` STRING,
    `PDSGM5` STRING,
    `PDDLOP` STRING,
    `PDDLT1` STRING,
    `PDDLT2` STRING,
    `PDDLT3` STRING,
    `PDDLT4` STRING,
    `PDDLT5` STRING,
    `PDDLM1` STRING,
    `PDDLM2` STRING,
    `PDDLM3` STRING,
    `PDDLM4` STRING,
    `PDDLM5` STRING,
    `PDDGOP` STRING,
    `PDDGT1` STRING,
    `PDDGT2` STRING,
    `PDDGT3` STRING,
    `PDDGT4` STRING,
    `PDDGT5` STRING,
    `PDDGM1` STRING,
    `PDDGM2` STRING,
    `PDDGM3` STRING,
    `PDDGM4` STRING,
    `PDDGM5` STRING,
    `PDOVRD` STRING,
    `PDOVRP` STRING,
    `PDRNDO` STRING,
    `PDUPDN` STRING,
    `PDASTM` STRING,
    `PDCHGT` DECIMAL(38,10),
    `PDINIT` STRING,
    `P2SHORT` STRING,
    `P2USEUP` STRING,
    `P2UNPAY` DECIMAL(38,10),
    `P2MADV` STRING,
    `PCRDTL` STRING,
    `PPPSBA` STRING,
    `PPPINQ` STRING,
    `P2FLOR` STRING,
    `P2CEIL` STRING,
    `P2REAM` STRING,
    `P2OLFE` STRING,
    `P2OTNB` STRING,
    `P2CINDX_CS` STRING,
    `P2CVVARI` STRING,
    `P2CVVARC` STRING,
    `P2CONSTR` STRING,
    `P2RGRISK` STRING,
    `P2TEASER` STRING,
    `PTSLTV` STRING,
    `P2ATMCRD` STRING,
    `P2CLZLC1` STRING,
    `P2CLZLC2` STRING,
    `P2CLZLC3` STRING,
    `P2CLZLC4` STRING,
    `P2CLZLC5` STRING,
    `P2CLZLC6` STRING,
    `P2HMDA` STRING,
    `P2RTCR` STRING,
    `P2MNCBL` STRING,
    `P2PRTMB` STRING,
    `P2INTF` DECIMAL(38,10),
    `P2STEPR` STRING,
    `P2USEIB3` STRING,
    `P2APPDLNS` STRING,
    `P2NBRPDPMT` STRING,
    `P2APPPDLNS` STRING,
    `P2NPDAPPLT` STRING,
    `P2NPDPPLTR` STRING,
    `P2PSTEXCRT` STRING,
    `P2ODIBAS` STRING,
    `P2DLPMT` STRING,
    `P2RSHTPC6` STRING,
    `P2SCRACOD` STRING,
    `P2MPLOC` STRING,
    `P2MPPSEQ` STRING,
    `P2XRFNBR` INT,
    `P2PTYPE` STRING,
    `P2TAKEACR` STRING,
    `P2TIER` STRING,
    `P2LR2B` STRING,
    `P2LRT2` STRING,
    `P2LR3B` STRING,
    `P2LRT3` STRING,
    `P2LR4B` STRING,
    `P2LRT4` STRING,
    `P2LR5B` STRING,
    `P2LRT5` STRING,
    `P2LR6B` STRING,
    `P2LRT6` STRING,
    `P2LR7B` STRING,
    `P2LRT7` STRING,
    `P2LR8B` STRING,
    `P2LRT8` STRING,
    `P2LR9B` STRING,
    `P2LRT9` STRING,
    `P2LR10B` STRING,
    `P2LRT10` STRING,
    `P2LSPL` STRING,
    `P2CAPR` STRING,
    `PLNOFF2LC` STRING,
    `PLNBR_2LC_CS` STRING,
    `PLNCAL2LC` STRING,
    `PLNCOL2LC` STRING,
    `PLNREG2LC` STRING,
    `PLNTAX2LC` DECIMAL(38,10),
    `P2ODPHOLD` DECIMAL(38,10),
    `P2NETP` STRING,
    `P2LCRL` STRING,
    `P2ACCDORB` STRING,
    `P2RQRGZ` STRING,
    `P2RZOERE` STRING,
    `P2RZOELN` STRING,
    `P2FLD1` STRING,
    `P2FLD2` STRING,
    `P2FLD3` STRING,
    `P2FLD4` STRING,
    `P2AMT1` DECIMAL(38,10),
    `P2AMT2` DECIMAL(38,10),
    `P2AMT3` DECIMAL(38,10),
    `P2PCT1` STRING,
    `P2PCT2` STRING,
    `P2NPST` STRING,
    `P2ATOBIL1` STRING,
    `P2ATOBIL2` STRING,
    `P2AUTOBIL` STRING,
    `P2ESCPD_CS` STRING,
    `P2SETTLEFF` STRING,
    `P2RZCERE` STRING,
    `P2PRIDWE` STRING,
    `P2ARMNTC` STRING,
    `P2INARMD` STRING,
    `P2SEIN` STRING,
    `P2DPDEIN` STRING,
    `P2SIAPLX` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_lnpar2 IS
'The JH_LNPAR2 landing table captures Jack Henry loan account, transaction, position, payment, collateral, rate, date, and balance attributes for loan validation, reconciliation, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_lnpar2;

INSERT INTO landing_jh.default.jh_lnpar2 (
    `PTYPE`, `PTYDSC`, `PLNGRP`, `PGRDSC`, `P2COST`, `P2PROD`,
    `P2IQNM`, `PIBASE`, `PDEPTC`, `P1098C`, `PCRREP`, `PCRTYP`,
    `PBKDYS`, `P2HECONV`, `P2OVMCHK$`, `P2MCHKFP`, `P2MNCKAVL`, `P2CNVTYP`,
    `P2CLSHELC`, `P2REAMCNV`, `PMINRT`, `PMAXRT`, `PINCLU`, `PFREQ`,
    `PFCODE`, `PSMDY1`, `PSMDY2`, `PPMTCD`, `PLATCD`, `P2IGLC`,
    `PPDNOT`, `PPDNLC`, `PCDNOT`, `PCPN`, `PMINCG`, `PCLASS`,
    `PPRCPM`, `P1STPD`, `P2NDPD`, `P3RDPD`, `P4THPD`, `P5THPD`,
    `P6THPD`, `P7THPD`, `P8THPD`, `P9THPD`, `P1STPDS`, `P2NDPDS`,
    `P3RDPDS`, `P4THPDS`, `P5THPDS`, `P6THPDS`, `P7THPDS`, `P8THPDS`,
    `P9THPDS`, `PPDRPT`, `PMAXLC`, `PMNNEW`, `PRHSNW`, `PRHSPD`,
    `PRHSPO`, `PDHSDY`, `PBLNDY`, `POTOL`, `PMTBOA`, `RETPDB`,
    `PRDTBK`, `PRLDBK`, `PRMEBK`, `PRMTBK`, `PMNRBK`, `PRCNOT`,
    `PRCNTR`, `PBLLBR`, `PRBEXF`, `PPRRTC`, `PRTCDY`, `PRTCMX`,
    `PRTCDF`, `PDCBTR`, `PMIAMR`, `PCALRE`, `PALTSC`, `PHMAIL`,
    `PTITLE`, `PCLSZR`, `PSTATU`, `PREAMO`, `PESCRO`, `PPARTI`,
    `PHASAR`, `PALMTY`, `PALWBD`, `PDOCTR`, `PPPPCD`, `PUSESP`,
    `PPDMTH`, `PIOEPI`, `PIOENB`, `PNEGAM`, `PNEGIN`, `PADDCP`,
    `PSUBPS`, `P2STMD`, `P2CPLT`, `P2CPIC`, `P2NAST`, `P2NADY`,
    `P2NAAC`, `P2NAPO`, `P2RADV`, `P2RPMT`, `P2MATN`, `P2MATD`,
    `P2ARMC`, `P2UCSH`, `P2EAD6`, `P2EAD7`, `P2ESCO`, `P2INTO`,
    `P2LTCO`, `P2OTHO`, `P2PRNO`, `P2INSO`, `P2SALA`, `P2FFOL`,
    `PAFTFC`, `PRJADV`, `PCLRBL`, `P2TRUE`, `P2DIFP`, `P2DBIT`,
    `P2DIFD`, `P2ZERO`, `P2PSST`, `P2STMT`, `P2STMR`, `P2STMP`,
    `P2PMNT`, `P2FREZ`, `P2FRZG`, `P2TAKP`, `P2INCR`, `P2MNAV`,
    `P2MNDD`, `P2MRAT`, `P2MCHK`, `P2RAT1`, `P2NEGB`, `P2AVAL`,
    `P2DAVL`, `P2RDUM`, `P2PREF`, `P2BLAD`, `P2CLRQ`, `P2CLRS`,
    `P2STML`, `P2PPMS`, `P2P1PM`, `P2POLT`, `P2UPAR`, `P2RTOL`,
    `P2CCOL`, `P2NEGP`, `P2NSFE`, `PDSLOP`, `PDSLT1`, `PDSLT2`,
    `PDSLT3`, `PDSLT4`, `PDSLT5`, `PDSLM1`, `PDSLM2`, `PDSLM3`,
    `PDSLM4`, `PDSLM5`, `PDSGOP`, `PDSGT1`, `PDSGT2`, `PDSGT3`,
    `PDSGT4`, `PDSGT5`, `PDSGM1`, `PDSGM2`, `PDSGM3`, `PDSGM4`,
    `PDSGM5`, `PDDLOP`, `PDDLT1`, `PDDLT2`, `PDDLT3`, `PDDLT4`,
    `PDDLT5`, `PDDLM1`, `PDDLM2`, `PDDLM3`, `PDDLM4`, `PDDLM5`,
    `PDDGOP`, `PDDGT1`, `PDDGT2`, `PDDGT3`, `PDDGT4`, `PDDGT5`,
    `PDDGM1`, `PDDGM2`, `PDDGM3`, `PDDGM4`, `PDDGM5`, `PDOVRD`,
    `PDOVRP`, `PDRNDO`, `PDUPDN`, `PDASTM`, `PDCHGT`, `PDINIT`,
    `P2SHORT`, `P2USEUP`, `P2UNPAY`, `P2MADV`, `PCRDTL`, `PPPSBA`,
    `PPPINQ`, `P2FLOR`, `P2CEIL`, `P2REAM`, `P2OLFE`, `P2OTNB`,
    `P2CINDX_CS`, `P2CVVARI`, `P2CVVARC`, `P2CONSTR`, `P2RGRISK`, `P2TEASER`,
    `PTSLTV`, `P2ATMCRD`, `P2CLZLC1`, `P2CLZLC2`, `P2CLZLC3`, `P2CLZLC4`,
    `P2CLZLC5`, `P2CLZLC6`, `P2HMDA`, `P2RTCR`, `P2MNCBL`, `P2PRTMB`,
    `P2INTF`, `P2STEPR`, `P2USEIB3`, `P2APPDLNS`, `P2NBRPDPMT`, `P2APPPDLNS`,
    `P2NPDAPPLT`, `P2NPDPPLTR`, `P2PSTEXCRT`, `P2ODIBAS`, `P2DLPMT`, `P2RSHTPC6`,
    `P2SCRACOD`, `P2MPLOC`, `P2MPPSEQ`, `P2XRFNBR`, `P2PTYPE`, `P2TAKEACR`,
    `P2TIER`, `P2LR2B`, `P2LRT2`, `P2LR3B`, `P2LRT3`, `P2LR4B`,
    `P2LRT4`, `P2LR5B`, `P2LRT5`, `P2LR6B`, `P2LRT6`, `P2LR7B`,
    `P2LRT7`, `P2LR8B`, `P2LRT8`, `P2LR9B`, `P2LRT9`, `P2LR10B`,
    `P2LRT10`, `P2LSPL`, `P2CAPR`, `PLNOFF2LC`, `PLNBR_2LC_CS`, `PLNCAL2LC`,
    `PLNCOL2LC`, `PLNREG2LC`, `PLNTAX2LC`, `P2ODPHOLD`, `P2NETP`, `P2LCRL`,
    `P2ACCDORB`, `P2RQRGZ`, `P2RZOERE`, `P2RZOELN`, `P2FLD1`, `P2FLD2`,
    `P2FLD3`, `P2FLD4`, `P2AMT1`, `P2AMT2`, `P2AMT3`, `P2PCT1`,
    `P2PCT2`, `P2NPST`, `P2ATOBIL1`, `P2ATOBIL2`, `P2AUTOBIL`, `P2ESCPD_CS`,
    `P2SETTLEFF`, `P2RZCERE`, `P2PRIDWE`, `P2ARMNTC`, `P2INARMD`, `P2SEIN`,
    `P2DPDEIN`, `P2SIAPLX`, `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('PTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTYPE`,
    concat('PTYDSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTYDSC`,
    concat('PLNGRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNGRP`,
    concat('PGRDSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGRDSC`,
    concat('P2COST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2COST`,
    concat('P2PROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PROD`,
    concat('P2IQNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IQNM`,
    concat('PIBASE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIBASE`,
    concat('PDEPTC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDEPTC`,
    concat('P1098C_', lpad(CAST(idx AS STRING), 2, '0')) AS `P1098C`,
    concat('PCRREP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRREP`,
    concat('PCRTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRTYP`,
    concat('PBKDYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBKDYS`,
    concat('P2HECONV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2HECONV`,
    concat('P2OVMCHK__', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OVMCHK$`,
    concat('P2MCHKFP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MCHKFP`,
    concat('P2MNCKAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MNCKAVL`,
    concat('P2CNVTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CNVTYP`,
    concat('P2CLSHELC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLSHELC`,
    concat('P2REAMCNV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2REAMCNV`,
    concat('PMINRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMINRT`,
    concat('PMAXRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMAXRT`,
    concat('PINCLU_', lpad(CAST(idx AS STRING), 2, '0')) AS `PINCLU`,
    concat('PFREQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `PFREQ`,
    concat('PFCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PFCODE`,
    concat('PSMDY1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSMDY1`,
    concat('PSMDY2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSMDY2`,
    concat('PPMTCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPMTCD`,
    concat('PLATCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLATCD`,
    concat('P2IGLC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IGLC`,
    concat('PPDNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDNOT`,
    concat('PPDNLC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDNLC`,
    concat('PCDNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCDNOT`,
    concat('PCPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCPN`,
    concat('PMINCG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMINCG`,
    concat('PCLASS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCLASS`,
    concat('PPRCPM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPRCPM`,
    concat('P1STPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P1STPD`,
    concat('P2NDPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NDPD`,
    concat('P3RDPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P3RDPD`,
    concat('P4THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P4THPD`,
    concat('P5THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P5THPD`,
    concat('P6THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P6THPD`,
    concat('P7THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P7THPD`,
    concat('P8THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P8THPD`,
    concat('P9THPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P9THPD`,
    concat('P1STPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P1STPDS`,
    concat('P2NDPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NDPDS`,
    concat('P3RDPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P3RDPDS`,
    concat('P4THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P4THPDS`,
    concat('P5THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P5THPDS`,
    concat('P6THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P6THPDS`,
    concat('P7THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P7THPDS`,
    concat('P8THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P8THPDS`,
    concat('P9THPDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P9THPDS`,
    concat('PPDRPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDRPT`,
    concat('PMAXLC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMAXLC`,
    concat('PMNNEW_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMNNEW`,
    concat('PRHSNW_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRHSNW`,
    concat('PRHSPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRHSPD`,
    concat('PRHSPO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRHSPO`,
    concat('PDHSDY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDHSDY`,
    concat('PBLNDY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLNDY`,
    concat('POTOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `POTOL`,
    concat('PMTBOA_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMTBOA`,
    concat('RETPDB_', lpad(CAST(idx AS STRING), 2, '0')) AS `RETPDB`,
    concat('PRDTBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRDTBK`,
    concat('PRLDBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRLDBK`,
    concat('PRMEBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRMEBK`,
    concat('PRMTBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRMTBK`,
    concat('PMNRBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMNRBK`,
    concat('PRCNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRCNOT`,
    concat('PRCNTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRCNTR`,
    concat('PBLLBR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBLLBR`,
    concat('PRBEXF_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRBEXF`,
    concat('PPRRTC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPRRTC`,
    concat('PRTCDY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTCDY`,
    concat('PRTCMX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTCMX`,
    concat('PRTCDF_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTCDF`,
    concat('PDCBTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDCBTR`,
    concat('PMIAMR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMIAMR`,
    concat('PCALRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCALRE`,
    concat('PALTSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALTSC`,
    concat('PHMAIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHMAIL`,
    concat('PTITLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTITLE`,
    concat('PCLSZR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCLSZR`,
    concat('PSTATU_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTATU`,
    concat('PREAMO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREAMO`,
    concat('PESCRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PESCRO`,
    concat('PPARTI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPARTI`,
    concat('PHASAR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHASAR`,
    concat('PALMTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALMTY`,
    concat('PALWBD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALWBD`,
    concat('PDOCTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDOCTR`,
    concat('PPPPCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPPPCD`,
    concat('PUSESP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PUSESP`,
    concat('PPDMTH_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDMTH`,
    concat('PIOEPI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIOEPI`,
    concat('PIOENB_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIOENB`,
    concat('PNEGAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNEGAM`,
    concat('PNEGIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNEGIN`,
    concat('PADDCP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADDCP`,
    concat('PSUBPS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSUBPS`,
    concat('P2STMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMD`,
    concat('P2CPLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CPLT`,
    concat('P2CPIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CPIC`,
    concat('P2NAST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NAST`,
    concat('P2NADY_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NADY`,
    concat('P2NAAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NAAC`,
    concat('P2NAPO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NAPO`,
    concat('P2RADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RADV`,
    concat('P2RPMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RPMT`,
    concat('P2MATN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MATN`,
    concat('P2MATD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MATD`,
    concat('P2ARMC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ARMC`,
    concat('P2UCSH_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2UCSH`,
    concat('P2EAD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EAD6`,
    concat('P2EAD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EAD7`,
    concat('P2ESCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ESCO`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2INTO`,
    concat('P2LTCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LTCO`,
    concat('P2OTHO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OTHO`,
    idx AS `P2PRNO`,
    concat('P2INSO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2INSO`,
    concat('P2SALA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SALA`,
    concat('P2FFOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FFOL`,
    concat('PAFTFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAFTFC`,
    concat('PRJADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRJADV`,
    concat('PCLRBL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCLRBL`,
    concat('P2TRUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TRUE`,
    concat('P2DIFP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DIFP`,
    concat('P2DBIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DBIT`,
    concat('P2DIFD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DIFD`,
    concat('P2ZERO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ZERO`,
    concat('P2PSST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSST`,
    concat('P2STMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMT`,
    concat('P2STMR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMR`,
    concat('P2STMP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMP`,
    concat('P2PMNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PMNT`,
    concat('P2FREZ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FREZ`,
    concat('P2FRZG_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FRZG`,
    concat('P2TAKP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TAKP`,
    concat('P2INCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2INCR`,
    concat('P2MNAV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MNAV`,
    concat('P2MNDD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MNDD`,
    concat('P2MRAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MRAT`,
    concat('P2MCHK_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MCHK`,
    concat('P2RAT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RAT1`,
    concat('P2NEGB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NEGB`,
    concat('P2AVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AVAL`,
    concat('P2DAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DAVL`,
    concat('P2RDUM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RDUM`,
    concat('P2PREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PREF`,
    concat('P2BLAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2BLAD`,
    concat('P2CLRQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLRQ`,
    concat('P2CLRS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLRS`,
    concat('P2STML_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STML`,
    concat('P2PPMS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PPMS`,
    concat('P2P1PM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2P1PM`,
    concat('P2POLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2POLT`,
    concat('P2UPAR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2UPAR`,
    concat('P2RTOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RTOL`,
    concat('P2CCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CCOL`,
    concat('P2NEGP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NEGP`,
    concat('P2NSFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NSFE`,
    concat('PDSLOP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLOP`,
    concat('PDSLT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLT1`,
    concat('PDSLT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLT2`,
    concat('PDSLT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLT3`,
    concat('PDSLT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLT4`,
    concat('PDSLT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLT5`,
    concat('PDSLM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLM1`,
    concat('PDSLM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLM2`,
    concat('PDSLM3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLM3`,
    concat('PDSLM4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLM4`,
    concat('PDSLM5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSLM5`,
    concat('PDSGOP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGOP`,
    concat('PDSGT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGT1`,
    concat('PDSGT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGT2`,
    concat('PDSGT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGT3`,
    concat('PDSGT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGT4`,
    concat('PDSGT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGT5`,
    concat('PDSGM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGM1`,
    concat('PDSGM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGM2`,
    concat('PDSGM3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGM3`,
    concat('PDSGM4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGM4`,
    concat('PDSGM5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSGM5`,
    concat('PDDLOP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLOP`,
    concat('PDDLT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLT1`,
    concat('PDDLT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLT2`,
    concat('PDDLT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLT3`,
    concat('PDDLT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLT4`,
    concat('PDDLT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLT5`,
    concat('PDDLM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLM1`,
    concat('PDDLM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLM2`,
    concat('PDDLM3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLM3`,
    concat('PDDLM4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLM4`,
    concat('PDDLM5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDLM5`,
    concat('PDDGOP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGOP`,
    concat('PDDGT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGT1`,
    concat('PDDGT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGT2`,
    concat('PDDGT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGT3`,
    concat('PDDGT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGT4`,
    concat('PDDGT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGT5`,
    concat('PDDGM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGM1`,
    concat('PDDGM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGM2`,
    concat('PDDGM3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGM3`,
    concat('PDDGM4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGM4`,
    concat('PDDGM5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDDGM5`,
    concat('PDOVRD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDOVRD`,
    concat('PDOVRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDOVRP`,
    concat('PDRNDO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDRNDO`,
    concat('PDUPDN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDUPDN`,
    concat('PDASTM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDASTM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PDCHGT`,
    concat('PDINIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDINIT`,
    concat('P2SHORT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SHORT`,
    concat('P2USEUP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2USEUP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2UNPAY`,
    concat('P2MADV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MADV`,
    concat('PCRDTL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRDTL`,
    concat('PPPSBA_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPPSBA`,
    concat('PPPINQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPPINQ`,
    concat('P2FLOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FLOR`,
    concat('P2CEIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CEIL`,
    concat('P2REAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2REAM`,
    concat('P2OLFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OLFE`,
    concat('P2OTNB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OTNB`,
    concat('P2CINDX_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CINDX_CS`,
    concat('P2CVVARI_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CVVARI`,
    concat('P2CVVARC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CVVARC`,
    concat('P2CONSTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CONSTR`,
    concat('P2RGRISK_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RGRISK`,
    concat('P2TEASER_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TEASER`,
    concat('PTSLTV_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTSLTV`,
    concat('P2ATMCRD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATMCRD`,
    concat('P2CLZLC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC1`,
    concat('P2CLZLC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC2`,
    concat('P2CLZLC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC3`,
    concat('P2CLZLC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC4`,
    concat('P2CLZLC5_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC5`,
    concat('P2CLZLC6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZLC6`,
    concat('P2HMDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2HMDA`,
    concat('P2RTCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RTCR`,
    concat('P2MNCBL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MNCBL`,
    concat('P2PRTMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PRTMB`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2INTF`,
    concat('P2STEPR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STEPR`,
    concat('P2USEIB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2USEIB3`,
    concat('P2APPDLNS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2APPDLNS`,
    concat('P2NBRPDPMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NBRPDPMT`,
    concat('P2APPPDLNS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2APPPDLNS`,
    concat('P2NPDAPPLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NPDAPPLT`,
    concat('P2NPDPPLTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NPDPPLTR`,
    concat('P2PSTEXCRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSTEXCRT`,
    concat('P2ODIBAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODIBAS`,
    concat('P2DLPMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DLPMT`,
    concat('P2RSHTPC6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RSHTPC6`,
    concat('P2SCRACOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SCRACOD`,
    concat('P2MPLOC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MPLOC`,
    concat('P2MPPSEQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MPPSEQ`,
    idx AS `P2XRFNBR`,
    concat('P2PTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PTYPE`,
    concat('P2TAKEACR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TAKEACR`,
    concat('P2TIER_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TIER`,
    concat('P2LR2B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR2B`,
    concat('P2LRT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT2`,
    concat('P2LR3B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR3B`,
    concat('P2LRT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT3`,
    concat('P2LR4B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR4B`,
    concat('P2LRT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT4`,
    concat('P2LR5B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR5B`,
    concat('P2LRT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT5`,
    concat('P2LR6B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR6B`,
    concat('P2LRT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT6`,
    concat('P2LR7B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR7B`,
    concat('P2LRT7_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT7`,
    concat('P2LR8B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR8B`,
    concat('P2LRT8_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT8`,
    concat('P2LR9B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR9B`,
    concat('P2LRT9_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT9`,
    concat('P2LR10B_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LR10B`,
    concat('P2LRT10_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LRT10`,
    concat('P2LSPL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LSPL`,
    concat('P2CAPR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CAPR`,
    concat('PLNOFF2LC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNOFF2LC`,
    concat('PLNBR_2LC_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNBR_2LC_CS`,
    concat('PLNCAL2LC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNCAL2LC`,
    concat('PLNCOL2LC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNCOL2LC`,
    concat('PLNREG2LC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLNREG2LC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PLNTAX2LC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2ODPHOLD`,
    concat('P2NETP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NETP`,
    concat('P2LCRL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCRL`,
    concat('P2ACCDORB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ACCDORB`,
    concat('P2RQRGZ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RQRGZ`,
    concat('P2RZOERE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RZOERE`,
    concat('P2RZOELN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RZOELN`,
    concat('P2FLD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FLD1`,
    concat('P2FLD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FLD2`,
    concat('P2FLD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FLD3`,
    concat('P2FLD4_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2FLD4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2AMT1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2AMT2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2AMT3`,
    concat('P2PCT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PCT1`,
    concat('P2PCT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PCT2`,
    concat('P2NPST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NPST`,
    concat('P2ATOBIL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATOBIL1`,
    concat('P2ATOBIL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATOBIL2`,
    concat('P2AUTOBIL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AUTOBIL`,
    concat('P2ESCPD_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ESCPD_CS`,
    concat('P2SETTLEFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SETTLEFF`,
    concat('P2RZCERE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RZCERE`,
    concat('P2PRIDWE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PRIDWE`,
    concat('P2ARMNTC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ARMNTC`,
    concat('P2INARMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2INARMD`,
    concat('P2SEIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SEIN`,
    concat('P2DPDEIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DPDEIN`,
    concat('P2SIAPLX_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SIAPLX`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_lnpar2' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_lnpar2;
