-- Databricks SQL for source: jh_ddpar2
-- Generated from sqlserver/brz-jh_ddpar2.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_DDPAR2"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_ddpar2 (
    `P2BRNO` INT,
    `P2REGN` STRING,
    `SCCODE` STRING,
    `PRSTMT` STRING,
    `PRTDOR` STRING,
    `CHGDOR` DECIMAL(38,10),
    `PRTNAC` STRING,
    `PRSEFT` STRING,
    `PSC1ST` STRING,
    `PIOTA` STRING,
    `ALTRT_CS` STRING,
    `PGRCOD` STRING,
    `PGRDES` STRING,
    `P2COST` STRING,
    `P2PROD` STRING,
    `P2IQNM` STRING,
    `P2HIST` STRING,
    `PSCNEG` STRING,
    `PSCZRO` STRING,
    `TRKEDR` STRING,
    `P2PSTM` STRING,
    `P2AORC` STRING,
    `ACCODE` STRING,
    `LEDCOL` STRING,
    `ACMETH` STRING,
    `YEARCD` STRING,
    `RESACC` STRING,
    `LGITEM` STRING,
    `DDADOR` STRING,
    `DDAESC` STRING,
    `DDACLO` STRING,
    `RETNDA` STRING,
    `RETCOB` STRING,
    `PSTREV` STRING,
    `PSTBAL` DECIMAL(38,10),
    `PSTSTP` STRING,
    `PSTSTPAC` STRING,
    `ACHAUT` STRING,
    `ACHAUTRSN` STRING,
    `NODFLT` STRING,
    `ROLFLT` STRING,
    `LIPNUM` INT,
    `FINLXC` STRING,
    `EXDACT` STRING,
    `EXDNUM` INT,
    `EXDCHG` DECIMAL(38,10),
    `EX3ACT` STRING,
    `EX3NUM` INT,
    `EX3CHG` DECIMAL(38,10),
    `EX6ACT` STRING,
    `EX6NUM` INT,
    `EX6CHG` DECIMAL(38,10),
    `EXSTMT` STRING,
    `EXWAIV` STRING,
    `ODPPIN` STRING,
    `PRTREL` STRING,
    `PSTPCG` STRING,
    `DORCHG` DECIMAL(38,10),
    `PDORTP` STRING,
    `PDORBL` STRING,
    `FORM` STRING,
    `AFTNSF` STRING,
    `PRIRT_CS` STRING,
    `BALRT2` DECIMAL(38,10),
    `INTRT2` DECIMAL(38,10),
    `BALRT3` DECIMAL(38,10),
    `INTRT3` DECIMAL(38,10),
    `BALRT4` DECIMAL(38,10),
    `INTRT4` DECIMAL(38,10),
    `BALRT5` DECIMAL(38,10),
    `INTRT5` DECIMAL(38,10),
    `BALRT6` DECIMAL(38,10),
    `INTRT6` DECIMAL(38,10),
    `BALRT7` DECIMAL(38,10),
    `INTRT7` DECIMAL(38,10),
    `BALRT8` DECIMAL(38,10),
    `INTRT8` DECIMAL(38,10),
    `BALRT9` DECIMAL(38,10),
    `INTRT9` DECIMAL(38,10),
    `BALRT0` DECIMAL(38,10),
    `INTRT0` DECIMAL(38,10),
    `SPLTAC` STRING,
    `PCHG0` DECIMAL(38,10),
    `PCHG1` DECIMAL(38,10),
    `PCOD1A` STRING,
    `PBAL1A` DECIMAL(38,10),
    `PCOD1B` STRING,
    `PBAL1B` DECIMAL(38,10),
    `PCHG2` DECIMAL(38,10),
    `PCOD2A` STRING,
    `PBAL2A` DECIMAL(38,10),
    `PCOD2B` STRING,
    `PBAL2B` DECIMAL(38,10),
    `PCHG3` DECIMAL(38,10),
    `PCOD3A` STRING,
    `PBAL3A` DECIMAL(38,10),
    `PCOD3B` STRING,
    `PBAL3B` DECIMAL(38,10),
    `PCHG4` DECIMAL(38,10),
    `PCOD4A` STRING,
    `PBAL4A` DECIMAL(38,10),
    `PCOD4B` STRING,
    `PBAL4B` DECIMAL(38,10),
    `PCHG5` DECIMAL(38,10),
    `PCOD5A` STRING,
    `PBAL5A` DECIMAL(38,10),
    `PCOD5B` STRING,
    `PBAL5B` DECIMAL(38,10),
    `PCHG6` DECIMAL(38,10),
    `PCOD6A` STRING,
    `PBAL6A` DECIMAL(38,10),
    `PCOD6B` STRING,
    `PBAL6B` DECIMAL(38,10),
    `PCHG7` DECIMAL(38,10),
    `PCOD7A` STRING,
    `PBAL7A` DECIMAL(38,10),
    `PCOD7B` STRING,
    `PBAL7B` DECIMAL(38,10),
    `PCHG8` DECIMAL(38,10),
    `PCOD8A` STRING,
    `PBAL8A` DECIMAL(38,10),
    `PCOD8B` STRING,
    `PBAL8B` DECIMAL(38,10),
    `PCHG9` DECIMAL(38,10),
    `PCOD9A` STRING,
    `PBAL9A` DECIMAL(38,10),
    `PCOD9B` STRING,
    `PBAL9B` DECIMAL(38,10),
    `PCHG10` DECIMAL(38,10),
    `PCD10A` STRING,
    `PBL10A` STRING,
    `PCD10B` STRING,
    `PBL10B` STRING,
    `PDRCHG` DECIMAL(38,10),
    `PNODR` STRING,
    `PDCOD1` STRING,
    `PDBAL1` DECIMAL(38,10),
    `PDCOD2` STRING,
    `PDBAL2` DECIMAL(38,10),
    `PCRCHG` DECIMAL(38,10),
    `PNOCR` STRING,
    `PCCOD1` STRING,
    `PCBAL1` DECIMAL(38,10),
    `PCCOD2` STRING,
    `PCBAL2` DECIMAL(38,10),
    `PITMCG` STRING,
    `PNOITM` STRING,
    `PICOD1` STRING,
    `PIBAL1` DECIMAL(38,10),
    `PICOD2` STRING,
    `PIBAL2` DECIMAL(38,10),
    `PTRCHG` DECIMAL(38,10),
    `PNOTR` STRING,
    `PTCOD1` STRING,
    `PTBAL1` DECIMAL(38,10),
    `PTCOD2` STRING,
    `PTBAL2` DECIMAL(38,10),
    `P2LCLITCHG` DECIMAL(38,10),
    `P2LCLITEXC` STRING,
    `P2LCLITBL1` STRING,
    `P2LCLBLBL0` STRING,
    `P2LCLITBL2` STRING,
    `P2LCLBLBL2` STRING,
    `PONCHG` DECIMAL(38,10),
    `PNOON` STRING,
    `POCOD1` STRING,
    `POBAL1` DECIMAL(38,10),
    `POCOD2` STRING,
    `POBAL2` DECIMAL(38,10),
    `PWDCHG` DECIMAL(38,10),
    `PNOWD` STRING,
    `PDPCHG` DECIMAL(38,10),
    `PNODP` STRING,
    `PATMOC` STRING,
    `PATMOD` STRING,
    `PATMOT` STRING,
    `PATMOI` STRING,
    `PATWOC` STRING,
    `PATWOD` STRING,
    `PATWOT` STRING,
    `PATWOI` STRING,
    `PATMFC` STRING,
    `PATMFD` STRING,
    `PATMFT` STRING,
    `PATMFI` STRING,
    `PATWFC` STRING,
    `PATWFD` STRING,
    `PATWFT` STRING,
    `PATWFI` STRING,
    `P2ATMO` STRING,
    `P2ATMM` STRING,
    `P2ATST` STRING,
    `PCGPCT` STRING,
    `PCGCOD` STRING,
    `PODRT_CS` STRING,
    `PODCOD` STRING,
    `PODBAL` DECIMAL(38,10),
    `RELD11` STRING,
    `RELD12` STRING,
    `RELD13` STRING,
    `RELD14` STRING,
    `RELD15` STRING,
    `RELD21` STRING,
    `RELD22` STRING,
    `RELD23` STRING,
    `RELD24` STRING,
    `RELD25` STRING,
    `RELD31` STRING,
    `RELD32` STRING,
    `RELD33` STRING,
    `RELD34` STRING,
    `RELD35` STRING,
    `RELS11` STRING,
    `RELS12` STRING,
    `RELS13` STRING,
    `RELS14` STRING,
    `RELS15` STRING,
    `RELS21` STRING,
    `RELS22` STRING,
    `RELS23` STRING,
    `RELS24` STRING,
    `RELS25` STRING,
    `RELS31` STRING,
    `RELS32` STRING,
    `RELS33` STRING,
    `RELS34` STRING,
    `RELS35` STRING,
    `RELC11` STRING,
    `RELC12` STRING,
    `RELC13` STRING,
    `RELC14` STRING,
    `RELC15` STRING,
    `RELC21` STRING,
    `RELC22` STRING,
    `RELC23` STRING,
    `RELC24` STRING,
    `RELC25` STRING,
    `RELC31` STRING,
    `RELC32` STRING,
    `RELC33` STRING,
    `RELC34` STRING,
    `RELC35` STRING,
    `RELL11` STRING,
    `RELL12` STRING,
    `RELL13` STRING,
    `RELL14` STRING,
    `RELL15` STRING,
    `RELL21` STRING,
    `RELL22` STRING,
    `RELL23` STRING,
    `RELL24` STRING,
    `RELL25` STRING,
    `RELL31` STRING,
    `RELL32` STRING,
    `RELL33` STRING,
    `RELL34` STRING,
    `RELL35` STRING,
    `RELO11` STRING,
    `RELO12` STRING,
    `RELO13` STRING,
    `RELO14` STRING,
    `RELO15` STRING,
    `RELO21` STRING,
    `RELO22` STRING,
    `RELO23` STRING,
    `RELO24` STRING,
    `RELO25` STRING,
    `RELO31` STRING,
    `RELO32` STRING,
    `RELO33` STRING,
    `RELO34` STRING,
    `RELO35` STRING,
    `RELB11` STRING,
    `RELB12` STRING,
    `RELB13` STRING,
    `RELB14` STRING,
    `RELB15` STRING,
    `RELB21` STRING,
    `RELB22` STRING,
    `RELB23` STRING,
    `RELB24` STRING,
    `RELB25` STRING,
    `RELN31` STRING,
    `RELN32` STRING,
    `RELN33` STRING,
    `RELN34` STRING,
    `RELN35` STRING,
    `RELT11` STRING,
    `RELT12` STRING,
    `RELT21` STRING,
    `RELT22` STRING,
    `RELT31` STRING,
    `RELT32` STRING,
    `RELTAO` STRING,
    `RELWAV` STRING,
    `RELAMT` DECIMAL(38,10),
    `RELPCT` STRING,
    `RELR01` STRING,
    `RELR02` STRING,
    `RELR03` STRING,
    `RELR04` STRING,
    `RELR05` STRING,
    `RELR06` STRING,
    `RELR07` STRING,
    `RELR08` STRING,
    `RELR09` STRING,
    `RELR10` STRING,
    `RELR11` STRING,
    `RELR12` STRING,
    `RELR13` STRING,
    `RELR14` STRING,
    `RELR15` STRING,
    `RELR16` STRING,
    `RELR17` STRING,
    `RELR18` STRING,
    `RELR19` STRING,
    `RELR20` STRING,
    `RELR21` STRING,
    `RELR22` STRING,
    `RELR23` STRING,
    `RELR24` STRING,
    `RELR25` STRING,
    `RELR26` STRING,
    `ALWXMS` STRING,
    `PCRSC` STRING,
    `PCRBAL` DECIMAL(38,10),
    `PCRMIN` STRING,
    `PCRCOD` STRING,
    `PCRRES` STRING,
    `PCRRT_CS` STRING,
    `PCRCD1` STRING,
    `PCRMN1` STRING,
    `PCRRS1` STRING,
    `PALCOD` STRING,
    `PALBAL` DECIMAL(38,10),
    `PACOD1` STRING,
    `PABAL1` DECIMAL(38,10),
    `PACOD3` STRING,
    `PABAL3` DECIMAL(38,10),
    `PABAL2` DECIMAL(38,10),
    `PMINSC` STRING,
    `PWAVSC` STRING,
    `PWAIV1` STRING,
    `PWAIV2` STRING,
    `PSCDES` STRING,
    `DELET` STRING,
    `PCAVAL` STRING,
    `PHAVAL` STRING,
    `PIAVAL` STRING,
    `PCAVOD` STRING,
    `PTAVAL` STRING,
    `PUCAVL` STRING,
    `PUDAVL` STRING,
    `PMCLED` STRING,
    `PMCCOL` STRING,
    `PMCAVL` STRING,
    `PMCMAX` STRING,
    `PMCMIN` STRING,
    `PMDLED` STRING,
    `PMDCOL` STRING,
    `PMDAVL` STRING,
    `PMDMAX` STRING,
    `PMDMIN` STRING,
    `PACLED` STRING,
    `PACCOL` STRING,
    `PACAVL` STRING,
    `PACMAX` STRING,
    `PACMIN` STRING,
    `PADLED` STRING,
    `PADCOL` STRING,
    `PADAVL` STRING,
    `PADMAX` STRING,
    `PADMIN` STRING,
    `PTCLED` STRING,
    `PTCCOL` STRING,
    `PTCAVL` STRING,
    `PTCMAX` STRING,
    `PTCMIN` STRING,
    `PTDLED` STRING,
    `PTDCOL` STRING,
    `PTDAVL` STRING,
    `PTDMAX` STRING,
    `PTDMIN` STRING,
    `PPCLED` STRING,
    `PPCCOL` STRING,
    `PPCAVL` STRING,
    `PPCMAX` STRING,
    `PPCMIN` STRING,
    `PPDLED` STRING,
    `PPDCOL` STRING,
    `PPDAVL` STRING,
    `PPDMAX` STRING,
    `PPDMIN` STRING,
    `PRTLED` STRING,
    `PRTCOL` STRING,
    `PRTAVL` STRING,
    `PRTMAX` STRING,
    `PRTMIN` STRING,
    `PRELED` STRING,
    `PRECOL` STRING,
    `PREAVL` STRING,
    `PREMAX` STRING,
    `PREMIN` STRING,
    `PNEWDA` STRING,
    `PNEWFL` STRING,
    `PACTYP` STRING,
    `PSCTYP` STRING,
    `PODLMT` STRING,
    `PODCHG` DECIMAL(38,10),
    `PODFEE` DECIMAL(38,10),
    `PODFMX` STRING,
    `PODFPC` STRING,
    `PODFDY` STRING,
    `PODFBL` STRING,
    `PSGCOD` STRING,
    `PCHKGT` STRING,
    `PATMCR` STRING,
    `PCOMBI` STRING,
    `PMALHL` STRING,
    `PLSTPS` STRING,
    `PAUTNS` STRING,
    `PNSFMX` STRING,
    `PODIMX` STRING,
    `PPCHEC` STRING,
    `PTRUNC` STRING,
    `PPVAR1` STRING,
    `PXMASP` STRING,
    `PDSIC1` STRING,
    `PDSIC2` STRING,
    `PDSIC3` STRING,
    `PDSIC4` STRING,
    `HISEXP` STRING,
    `PRTCKP` STRING,
    `PRTNEB` STRING,
    `PSWINC` STRING,
    `PSWCHG` DECIMAL(38,10),
    `PSWPRT` STRING,
    `ACHPNC` STRING,
    `P2STMD` STRING,
    `P2PREF` STRING,
    `P2CKAD` STRING,
    `P2TORE` STRING,
    `P2EXHS` STRING,
    `P2CMIC` STRING,
    `PRNAPY` STRING,
    `PR2APY` STRING,
    `PR3APY` STRING,
    `PR4APY` STRING,
    `PR5APY` STRING,
    `PR6APY` STRING,
    `PR7APY` STRING,
    `PR8APY` STRING,
    `PR9APY` STRING,
    `PR0APY` STRING,
    `APYBAL` DECIMAL(38,10),
    `P2TTD1` STRING,
    `P2TTD2` STRING,
    `P2TTFE` STRING,
    `P2TTRC` STRING,
    `P2IPPG` STRING,
    `P2IFBK` STRING,
    `P2ICKO` STRING,
    `P2ICRS` STRING,
    `P2CLZR` STRING,
    `P2PRNTRATE` DECIMAL(38,10),
    `P2LOWBALNC` DECIMAL(38,10),
    `P2LOWTOLRN` STRING,
    `P2EARLYFEE` DECIMAL(38,10),
    `P2EARLYDYS` STRING,
    `P2PRNTADND` STRING,
    `P2ADNDCNT` INT,
    `P2CALL` STRING,
    `P2RS_TIME_CS` STRING,
    `P2RS_ITEM_CS` STRING,
    `P2CYCCHG$` DECIMAL(38,10),
    `P2CYCAAIT_CS` STRING,
    `P2CYCFREE` STRING,
    `P2STMCHG$` DECIMAL(38,10),
    `P2STMAAIT_CS` STRING,
    `P2STMFREE` STRING,
    `P2STCYRSFQ` STRING,
    `P2STCYCGFQ` STRING,
    `P2WAIVERET` STRING,
    `P2SWEEPNOT` STRING,
    `P2PYINTEOM` DECIMAL(38,10),
    `P2ODNOTDY1` STRING,
    `P2ODNOTDY2` STRING,
    `P2ODNOTDY3` STRING,
    `P2ODNOTDY4` STRING,
    `P2ODNOTDY5` STRING,
    `P2ODNOTDY6` STRING,
    `P2STCYC` STRING,
    `P2SCCYC` STRING,
    `P2INTCYC` DECIMAL(38,10),
    `P2PRTINTR` DECIMAL(38,10),
    `P2USESFRM` STRING,
    `P2ALLREDE` STRING,
    `P2NOREDEP` STRING,
    `P2SNDREDP` STRING,
    `PUCFMX` STRING,
    `P2DEFOFFWV` STRING,
    `P2OFFREQWV` STRING,
    `P2ODRGRPT` STRING,
    `P2SWLDCL` STRING,
    `P2SWFLOAT` STRING,
    `P2SWTYPE` STRING,
    `P2SWPAYOF` DECIMAL(38,10),
    `P2SWLIMT` STRING,
    `P2SETUPFAM` STRING,
    `P2SETUPFCT` STRING,
    `P2MTHLYFAM` STRING,
    `P2MTHLYFCT` STRING,
    `P2EXCPTFAM` STRING,
    `P2EXCPTFCT` STRING,
    `P2SWAPEG` STRING,
    `P2AVLTAB` STRING,
    `P2HSA` STRING,
    `P2STPNOT` STRING,
    `P2SWUTGB` STRING,
    `P2PORCACT` STRING,
    `P2ODDAY` STRING,
    `P2INQAVLTB` STRING,
    `P2_ACR_CS` STRING,
    `P2R_ACR` STRING,
    `P2R_ACR_CS` STRING,
    `P2_ADR_CS` STRING,
    `P2R_ADR` STRING,
    `P2R_ADR_CS` STRING,
    `P2ACPPSETA` STRING,
    `P2ACPPMTHA` STRING,
    `P2ACPPEXCA` STRING,
    `P2JHA1` STRING,
    `P2JHA2` STRING,
    `P2JHA3` STRING,
    `P2JHA4` STRING,
    `P2JHA5` STRING,
    `P2JHA6` STRING,
    `P2JHA7` STRING,
    `P2JHA8` STRING,
    `P2ODDAYCN` STRING,
    `P2XRFNBR` INT,
    `P2PSCOD` STRING,
    `P2PSFEEAMT` DECIMAL(38,10),
    `P2PSFEITEM` STRING,
    `P2PSFECODE` STRING,
    `P2IMGACTFE` STRING,
    `P2RWDSFLG` STRING,
    `PCGBAL` DECIMAL(38,10),
    `PRTPRCY` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_ddpar2 IS
'The JH demand deposit parameter landing table captures DDA product, transaction, service charge, and account reference attributes for validation, classification, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_ddpar2;

INSERT INTO landing_jh.default.jh_ddpar2 (
    `P2BRNO`, `P2REGN`, `SCCODE`, `PRSTMT`, `PRTDOR`, `CHGDOR`,
    `PRTNAC`, `PRSEFT`, `PSC1ST`, `PIOTA`, `ALTRT_CS`, `PGRCOD`,
    `PGRDES`, `P2COST`, `P2PROD`, `P2IQNM`, `P2HIST`, `PSCNEG`,
    `PSCZRO`, `TRKEDR`, `P2PSTM`, `P2AORC`, `ACCODE`, `LEDCOL`,
    `ACMETH`, `YEARCD`, `RESACC`, `LGITEM`, `DDADOR`, `DDAESC`,
    `DDACLO`, `RETNDA`, `RETCOB`, `PSTREV`, `PSTBAL`, `PSTSTP`,
    `PSTSTPAC`, `ACHAUT`, `ACHAUTRSN`, `NODFLT`, `ROLFLT`, `LIPNUM`,
    `FINLXC`, `EXDACT`, `EXDNUM`, `EXDCHG`, `EX3ACT`, `EX3NUM`,
    `EX3CHG`, `EX6ACT`, `EX6NUM`, `EX6CHG`, `EXSTMT`, `EXWAIV`,
    `ODPPIN`, `PRTREL`, `PSTPCG`, `DORCHG`, `PDORTP`, `PDORBL`,
    `FORM`, `AFTNSF`, `PRIRT_CS`, `BALRT2`, `INTRT2`, `BALRT3`,
    `INTRT3`, `BALRT4`, `INTRT4`, `BALRT5`, `INTRT5`, `BALRT6`,
    `INTRT6`, `BALRT7`, `INTRT7`, `BALRT8`, `INTRT8`, `BALRT9`,
    `INTRT9`, `BALRT0`, `INTRT0`, `SPLTAC`, `PCHG0`, `PCHG1`,
    `PCOD1A`, `PBAL1A`, `PCOD1B`, `PBAL1B`, `PCHG2`, `PCOD2A`,
    `PBAL2A`, `PCOD2B`, `PBAL2B`, `PCHG3`, `PCOD3A`, `PBAL3A`,
    `PCOD3B`, `PBAL3B`, `PCHG4`, `PCOD4A`, `PBAL4A`, `PCOD4B`,
    `PBAL4B`, `PCHG5`, `PCOD5A`, `PBAL5A`, `PCOD5B`, `PBAL5B`,
    `PCHG6`, `PCOD6A`, `PBAL6A`, `PCOD6B`, `PBAL6B`, `PCHG7`,
    `PCOD7A`, `PBAL7A`, `PCOD7B`, `PBAL7B`, `PCHG8`, `PCOD8A`,
    `PBAL8A`, `PCOD8B`, `PBAL8B`, `PCHG9`, `PCOD9A`, `PBAL9A`,
    `PCOD9B`, `PBAL9B`, `PCHG10`, `PCD10A`, `PBL10A`, `PCD10B`,
    `PBL10B`, `PDRCHG`, `PNODR`, `PDCOD1`, `PDBAL1`, `PDCOD2`,
    `PDBAL2`, `PCRCHG`, `PNOCR`, `PCCOD1`, `PCBAL1`, `PCCOD2`,
    `PCBAL2`, `PITMCG`, `PNOITM`, `PICOD1`, `PIBAL1`, `PICOD2`,
    `PIBAL2`, `PTRCHG`, `PNOTR`, `PTCOD1`, `PTBAL1`, `PTCOD2`,
    `PTBAL2`, `P2LCLITCHG`, `P2LCLITEXC`, `P2LCLITBL1`, `P2LCLBLBL0`, `P2LCLITBL2`,
    `P2LCLBLBL2`, `PONCHG`, `PNOON`, `POCOD1`, `POBAL1`, `POCOD2`,
    `POBAL2`, `PWDCHG`, `PNOWD`, `PDPCHG`, `PNODP`, `PATMOC`,
    `PATMOD`, `PATMOT`, `PATMOI`, `PATWOC`, `PATWOD`, `PATWOT`,
    `PATWOI`, `PATMFC`, `PATMFD`, `PATMFT`, `PATMFI`, `PATWFC`,
    `PATWFD`, `PATWFT`, `PATWFI`, `P2ATMO`, `P2ATMM`, `P2ATST`,
    `PCGPCT`, `PCGCOD`, `PODRT_CS`, `PODCOD`, `PODBAL`, `RELD11`,
    `RELD12`, `RELD13`, `RELD14`, `RELD15`, `RELD21`, `RELD22`,
    `RELD23`, `RELD24`, `RELD25`, `RELD31`, `RELD32`, `RELD33`,
    `RELD34`, `RELD35`, `RELS11`, `RELS12`, `RELS13`, `RELS14`,
    `RELS15`, `RELS21`, `RELS22`, `RELS23`, `RELS24`, `RELS25`,
    `RELS31`, `RELS32`, `RELS33`, `RELS34`, `RELS35`, `RELC11`,
    `RELC12`, `RELC13`, `RELC14`, `RELC15`, `RELC21`, `RELC22`,
    `RELC23`, `RELC24`, `RELC25`, `RELC31`, `RELC32`, `RELC33`,
    `RELC34`, `RELC35`, `RELL11`, `RELL12`, `RELL13`, `RELL14`,
    `RELL15`, `RELL21`, `RELL22`, `RELL23`, `RELL24`, `RELL25`,
    `RELL31`, `RELL32`, `RELL33`, `RELL34`, `RELL35`, `RELO11`,
    `RELO12`, `RELO13`, `RELO14`, `RELO15`, `RELO21`, `RELO22`,
    `RELO23`, `RELO24`, `RELO25`, `RELO31`, `RELO32`, `RELO33`,
    `RELO34`, `RELO35`, `RELB11`, `RELB12`, `RELB13`, `RELB14`,
    `RELB15`, `RELB21`, `RELB22`, `RELB23`, `RELB24`, `RELB25`,
    `RELN31`, `RELN32`, `RELN33`, `RELN34`, `RELN35`, `RELT11`,
    `RELT12`, `RELT21`, `RELT22`, `RELT31`, `RELT32`, `RELTAO`,
    `RELWAV`, `RELAMT`, `RELPCT`, `RELR01`, `RELR02`, `RELR03`,
    `RELR04`, `RELR05`, `RELR06`, `RELR07`, `RELR08`, `RELR09`,
    `RELR10`, `RELR11`, `RELR12`, `RELR13`, `RELR14`, `RELR15`,
    `RELR16`, `RELR17`, `RELR18`, `RELR19`, `RELR20`, `RELR21`,
    `RELR22`, `RELR23`, `RELR24`, `RELR25`, `RELR26`, `ALWXMS`,
    `PCRSC`, `PCRBAL`, `PCRMIN`, `PCRCOD`, `PCRRES`, `PCRRT_CS`,
    `PCRCD1`, `PCRMN1`, `PCRRS1`, `PALCOD`, `PALBAL`, `PACOD1`,
    `PABAL1`, `PACOD3`, `PABAL3`, `PABAL2`, `PMINSC`, `PWAVSC`,
    `PWAIV1`, `PWAIV2`, `PSCDES`, `DELET`, `PCAVAL`, `PHAVAL`,
    `PIAVAL`, `PCAVOD`, `PTAVAL`, `PUCAVL`, `PUDAVL`, `PMCLED`,
    `PMCCOL`, `PMCAVL`, `PMCMAX`, `PMCMIN`, `PMDLED`, `PMDCOL`,
    `PMDAVL`, `PMDMAX`, `PMDMIN`, `PACLED`, `PACCOL`, `PACAVL`,
    `PACMAX`, `PACMIN`, `PADLED`, `PADCOL`, `PADAVL`, `PADMAX`,
    `PADMIN`, `PTCLED`, `PTCCOL`, `PTCAVL`, `PTCMAX`, `PTCMIN`,
    `PTDLED`, `PTDCOL`, `PTDAVL`, `PTDMAX`, `PTDMIN`, `PPCLED`,
    `PPCCOL`, `PPCAVL`, `PPCMAX`, `PPCMIN`, `PPDLED`, `PPDCOL`,
    `PPDAVL`, `PPDMAX`, `PPDMIN`, `PRTLED`, `PRTCOL`, `PRTAVL`,
    `PRTMAX`, `PRTMIN`, `PRELED`, `PRECOL`, `PREAVL`, `PREMAX`,
    `PREMIN`, `PNEWDA`, `PNEWFL`, `PACTYP`, `PSCTYP`, `PODLMT`,
    `PODCHG`, `PODFEE`, `PODFMX`, `PODFPC`, `PODFDY`, `PODFBL`,
    `PSGCOD`, `PCHKGT`, `PATMCR`, `PCOMBI`, `PMALHL`, `PLSTPS`,
    `PAUTNS`, `PNSFMX`, `PODIMX`, `PPCHEC`, `PTRUNC`, `PPVAR1`,
    `PXMASP`, `PDSIC1`, `PDSIC2`, `PDSIC3`, `PDSIC4`, `HISEXP`,
    `PRTCKP`, `PRTNEB`, `PSWINC`, `PSWCHG`, `PSWPRT`, `ACHPNC`,
    `P2STMD`, `P2PREF`, `P2CKAD`, `P2TORE`, `P2EXHS`, `P2CMIC`,
    `PRNAPY`, `PR2APY`, `PR3APY`, `PR4APY`, `PR5APY`, `PR6APY`,
    `PR7APY`, `PR8APY`, `PR9APY`, `PR0APY`, `APYBAL`, `P2TTD1`,
    `P2TTD2`, `P2TTFE`, `P2TTRC`, `P2IPPG`, `P2IFBK`, `P2ICKO`,
    `P2ICRS`, `P2CLZR`, `P2PRNTRATE`, `P2LOWBALNC`, `P2LOWTOLRN`, `P2EARLYFEE`,
    `P2EARLYDYS`, `P2PRNTADND`, `P2ADNDCNT`, `P2CALL`, `P2RS_TIME_CS`, `P2RS_ITEM_CS`,
    `P2CYCCHG$`, `P2CYCAAIT_CS`, `P2CYCFREE`, `P2STMCHG$`, `P2STMAAIT_CS`, `P2STMFREE`,
    `P2STCYRSFQ`, `P2STCYCGFQ`, `P2WAIVERET`, `P2SWEEPNOT`, `P2PYINTEOM`, `P2ODNOTDY1`,
    `P2ODNOTDY2`, `P2ODNOTDY3`, `P2ODNOTDY4`, `P2ODNOTDY5`, `P2ODNOTDY6`, `P2STCYC`,
    `P2SCCYC`, `P2INTCYC`, `P2PRTINTR`, `P2USESFRM`, `P2ALLREDE`, `P2NOREDEP`,
    `P2SNDREDP`, `PUCFMX`, `P2DEFOFFWV`, `P2OFFREQWV`, `P2ODRGRPT`, `P2SWLDCL`,
    `P2SWFLOAT`, `P2SWTYPE`, `P2SWPAYOF`, `P2SWLIMT`, `P2SETUPFAM`, `P2SETUPFCT`,
    `P2MTHLYFAM`, `P2MTHLYFCT`, `P2EXCPTFAM`, `P2EXCPTFCT`, `P2SWAPEG`, `P2AVLTAB`,
    `P2HSA`, `P2STPNOT`, `P2SWUTGB`, `P2PORCACT`, `P2ODDAY`, `P2INQAVLTB`,
    `P2_ACR_CS`, `P2R_ACR`, `P2R_ACR_CS`, `P2_ADR_CS`, `P2R_ADR`, `P2R_ADR_CS`,
    `P2ACPPSETA`, `P2ACPPMTHA`, `P2ACPPEXCA`, `P2JHA1`, `P2JHA2`, `P2JHA3`,
    `P2JHA4`, `P2JHA5`, `P2JHA6`, `P2JHA7`, `P2JHA8`, `P2ODDAYCN`,
    `P2XRFNBR`, `P2PSCOD`, `P2PSFEEAMT`, `P2PSFEITEM`, `P2PSFECODE`, `P2IMGACTFE`,
    `P2RWDSFLG`, `PCGBAL`, `PRTPRCY`, `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `P2BRNO`,
    concat('P2REGN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2REGN`,
    concat('SCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SCCODE`,
    concat('PRSTMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRSTMT`,
    concat('PRTDOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTDOR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHGDOR`,
    concat('PRTNAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTNAC`,
    concat('PRSEFT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRSEFT`,
    concat('PSC1ST_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSC1ST`,
    concat('PIOTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIOTA`,
    concat('ALTRT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALTRT_CS`,
    concat('PGRCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGRCOD`,
    concat('PGRDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGRDES`,
    concat('P2COST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2COST`,
    concat('P2PROD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PROD`,
    concat('P2IQNM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IQNM`,
    concat('P2HIST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2HIST`,
    concat('PSCNEG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSCNEG`,
    concat('PSCZRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSCZRO`,
    concat('TRKEDR_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRKEDR`,
    concat('P2PSTM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSTM`,
    concat('P2AORC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AORC`,
    concat('ACCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCODE`,
    concat('LEDCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `LEDCOL`,
    concat('ACMETH_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACMETH`,
    concat('YEARCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `YEARCD`,
    concat('RESACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `RESACC`,
    concat('LGITEM_', lpad(CAST(idx AS STRING), 2, '0')) AS `LGITEM`,
    concat('DDADOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `DDADOR`,
    concat('DDAESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `DDAESC`,
    concat('DDACLO_', lpad(CAST(idx AS STRING), 2, '0')) AS `DDACLO`,
    concat('RETNDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `RETNDA`,
    concat('RETCOB_', lpad(CAST(idx AS STRING), 2, '0')) AS `RETCOB`,
    concat('PSTREV_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTREV`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSTBAL`,
    concat('PSTSTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTSTP`,
    concat('PSTSTPAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTSTPAC`,
    concat('ACHAUT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACHAUT`,
    concat('ACHAUTRSN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACHAUTRSN`,
    concat('NODFLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `NODFLT`,
    concat('ROLFLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ROLFLT`,
    idx AS `LIPNUM`,
    concat('FINLXC_', lpad(CAST(idx AS STRING), 2, '0')) AS `FINLXC`,
    concat('EXDACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXDACT`,
    idx AS `EXDNUM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EXDCHG`,
    concat('EX3ACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `EX3ACT`,
    idx AS `EX3NUM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EX3CHG`,
    concat('EX6ACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `EX6ACT`,
    idx AS `EX6NUM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `EX6CHG`,
    concat('EXSTMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXSTMT`,
    concat('EXWAIV_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXWAIV`,
    concat('ODPPIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ODPPIN`,
    concat('PRTREL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTREL`,
    concat('PSTPCG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTPCG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DORCHG`,
    concat('PDORTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDORTP`,
    concat('PDORBL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDORBL`,
    concat('FORM_', lpad(CAST(idx AS STRING), 2, '0')) AS `FORM`,
    concat('AFTNSF_', lpad(CAST(idx AS STRING), 2, '0')) AS `AFTNSF`,
    concat('PRIRT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRIRT_CS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALRT0`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTRT0`,
    concat('SPLTAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `SPLTAC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG0`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG1`,
    concat('PCOD1A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD1A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL1A`,
    concat('PCOD1B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD1B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL1B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG2`,
    concat('PCOD2A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD2A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL2A`,
    concat('PCOD2B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD2B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL2B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG3`,
    concat('PCOD3A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD3A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL3A`,
    concat('PCOD3B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD3B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL3B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG4`,
    concat('PCOD4A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD4A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL4A`,
    concat('PCOD4B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD4B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL4B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG5`,
    concat('PCOD5A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD5A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL5A`,
    concat('PCOD5B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD5B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL5B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG6`,
    concat('PCOD6A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD6A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL6A`,
    concat('PCOD6B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD6B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL6B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG7`,
    concat('PCOD7A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD7A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL7A`,
    concat('PCOD7B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD7B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL7B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG8`,
    concat('PCOD8A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD8A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL8A`,
    concat('PCOD8B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD8B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL8B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG9`,
    concat('PCOD9A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD9A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL9A`,
    concat('PCOD9B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOD9B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PBAL9B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCHG10`,
    concat('PCD10A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCD10A`,
    concat('PBL10A_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBL10A`,
    concat('PCD10B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCD10B`,
    concat('PBL10B_', lpad(CAST(idx AS STRING), 2, '0')) AS `PBL10B`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PDRCHG`,
    concat('PNODR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNODR`,
    concat('PDCOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDCOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PDBAL1`,
    concat('PDCOD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDCOD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PDBAL2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCRCHG`,
    concat('PNOCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNOCR`,
    concat('PCCOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCCOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCBAL1`,
    concat('PCCOD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCCOD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCBAL2`,
    concat('PITMCG_', lpad(CAST(idx AS STRING), 2, '0')) AS `PITMCG`,
    concat('PNOITM_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNOITM`,
    concat('PICOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PICOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PIBAL1`,
    concat('PICOD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PICOD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PIBAL2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PTRCHG`,
    concat('PNOTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNOTR`,
    concat('PTCOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PTBAL1`,
    concat('PTCOD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCOD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PTBAL2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2LCLITCHG`,
    concat('P2LCLITEXC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCLITEXC`,
    concat('P2LCLITBL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCLITBL1`,
    concat('P2LCLBLBL0_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCLBLBL0`,
    concat('P2LCLITBL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCLITBL2`,
    concat('P2LCLBLBL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LCLBLBL2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PONCHG`,
    concat('PNOON_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNOON`,
    concat('POCOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `POCOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `POBAL1`,
    concat('POCOD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `POCOD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `POBAL2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PWDCHG`,
    concat('PNOWD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNOWD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PDPCHG`,
    concat('PNODP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNODP`,
    concat('PATMOC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMOC`,
    concat('PATMOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMOD`,
    concat('PATMOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMOT`,
    concat('PATMOI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMOI`,
    concat('PATWOC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWOC`,
    concat('PATWOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWOD`,
    concat('PATWOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWOT`,
    concat('PATWOI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWOI`,
    concat('PATMFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMFC`,
    concat('PATMFD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMFD`,
    concat('PATMFT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMFT`,
    concat('PATMFI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMFI`,
    concat('PATWFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWFC`,
    concat('PATWFD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWFD`,
    concat('PATWFT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWFT`,
    concat('PATWFI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATWFI`,
    concat('P2ATMO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATMO`,
    concat('P2ATMM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATMM`,
    concat('P2ATST_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ATST`,
    concat('PCGPCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCGPCT`,
    concat('PCGCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCGCOD`,
    concat('PODRT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODRT_CS`,
    concat('PODCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODCOD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PODBAL`,
    concat('RELD11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD11`,
    concat('RELD12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD12`,
    concat('RELD13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD13`,
    concat('RELD14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD14`,
    concat('RELD15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD15`,
    concat('RELD21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD21`,
    concat('RELD22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD22`,
    concat('RELD23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD23`,
    concat('RELD24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD24`,
    concat('RELD25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD25`,
    concat('RELD31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD31`,
    concat('RELD32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD32`,
    concat('RELD33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD33`,
    concat('RELD34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD34`,
    concat('RELD35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELD35`,
    concat('RELS11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS11`,
    concat('RELS12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS12`,
    concat('RELS13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS13`,
    concat('RELS14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS14`,
    concat('RELS15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS15`,
    concat('RELS21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS21`,
    concat('RELS22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS22`,
    concat('RELS23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS23`,
    concat('RELS24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS24`,
    concat('RELS25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS25`,
    concat('RELS31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS31`,
    concat('RELS32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS32`,
    concat('RELS33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS33`,
    concat('RELS34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS34`,
    concat('RELS35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELS35`,
    concat('RELC11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC11`,
    concat('RELC12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC12`,
    concat('RELC13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC13`,
    concat('RELC14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC14`,
    concat('RELC15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC15`,
    concat('RELC21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC21`,
    concat('RELC22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC22`,
    concat('RELC23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC23`,
    concat('RELC24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC24`,
    concat('RELC25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC25`,
    concat('RELC31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC31`,
    concat('RELC32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC32`,
    concat('RELC33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC33`,
    concat('RELC34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC34`,
    concat('RELC35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELC35`,
    concat('RELL11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL11`,
    concat('RELL12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL12`,
    concat('RELL13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL13`,
    concat('RELL14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL14`,
    concat('RELL15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL15`,
    concat('RELL21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL21`,
    concat('RELL22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL22`,
    concat('RELL23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL23`,
    concat('RELL24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL24`,
    concat('RELL25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL25`,
    concat('RELL31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL31`,
    concat('RELL32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL32`,
    concat('RELL33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL33`,
    concat('RELL34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL34`,
    concat('RELL35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELL35`,
    concat('RELO11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO11`,
    concat('RELO12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO12`,
    concat('RELO13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO13`,
    concat('RELO14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO14`,
    concat('RELO15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO15`,
    concat('RELO21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO21`,
    concat('RELO22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO22`,
    concat('RELO23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO23`,
    concat('RELO24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO24`,
    concat('RELO25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO25`,
    concat('RELO31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO31`,
    concat('RELO32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO32`,
    concat('RELO33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO33`,
    concat('RELO34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO34`,
    concat('RELO35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELO35`,
    concat('RELB11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB11`,
    concat('RELB12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB12`,
    concat('RELB13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB13`,
    concat('RELB14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB14`,
    concat('RELB15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB15`,
    concat('RELB21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB21`,
    concat('RELB22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB22`,
    concat('RELB23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB23`,
    concat('RELB24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB24`,
    concat('RELB25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELB25`,
    concat('RELN31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELN31`,
    concat('RELN32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELN32`,
    concat('RELN33_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELN33`,
    concat('RELN34_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELN34`,
    concat('RELN35_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELN35`,
    concat('RELT11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT11`,
    concat('RELT12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT12`,
    concat('RELT21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT21`,
    concat('RELT22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT22`,
    concat('RELT31_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT31`,
    concat('RELT32_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELT32`,
    concat('RELTAO_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELTAO`,
    concat('RELWAV_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELWAV`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `RELAMT`,
    concat('RELPCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELPCT`,
    concat('RELR01_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR01`,
    concat('RELR02_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR02`,
    concat('RELR03_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR03`,
    concat('RELR04_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR04`,
    concat('RELR05_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR05`,
    concat('RELR06_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR06`,
    concat('RELR07_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR07`,
    concat('RELR08_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR08`,
    concat('RELR09_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR09`,
    concat('RELR10_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR10`,
    concat('RELR11_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR11`,
    concat('RELR12_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR12`,
    concat('RELR13_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR13`,
    concat('RELR14_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR14`,
    concat('RELR15_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR15`,
    concat('RELR16_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR16`,
    concat('RELR17_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR17`,
    concat('RELR18_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR18`,
    concat('RELR19_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR19`,
    concat('RELR20_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR20`,
    concat('RELR21_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR21`,
    concat('RELR22_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR22`,
    concat('RELR23_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR23`,
    concat('RELR24_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR24`,
    concat('RELR25_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR25`,
    concat('RELR26_', lpad(CAST(idx AS STRING), 2, '0')) AS `RELR26`,
    concat('ALWXMS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALWXMS`,
    concat('PCRSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRSC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCRBAL`,
    concat('PCRMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRMIN`,
    concat('PCRCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRCOD`,
    concat('PCRRES_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRRES`,
    concat('PCRRT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRRT_CS`,
    concat('PCRCD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRCD1`,
    concat('PCRMN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRMN1`,
    concat('PCRRS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCRRS1`,
    concat('PALCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PALCOD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PALBAL`,
    concat('PACOD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACOD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PABAL1`,
    concat('PACOD3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACOD3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PABAL3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PABAL2`,
    concat('PMINSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMINSC`,
    concat('PWAVSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PWAVSC`,
    concat('PWAIV1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PWAIV1`,
    concat('PWAIV2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PWAIV2`,
    concat('PSCDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSCDES`,
    concat('DELET_', lpad(CAST(idx AS STRING), 2, '0')) AS `DELET`,
    concat('PCAVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCAVAL`,
    concat('PHAVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHAVAL`,
    concat('PIAVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PIAVAL`,
    concat('PCAVOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCAVOD`,
    concat('PTAVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTAVAL`,
    concat('PUCAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PUCAVL`,
    concat('PUDAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PUDAVL`,
    concat('PMCLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMCLED`,
    concat('PMCCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMCCOL`,
    concat('PMCAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMCAVL`,
    concat('PMCMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMCMAX`,
    concat('PMCMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMCMIN`,
    concat('PMDLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMDLED`,
    concat('PMDCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMDCOL`,
    concat('PMDAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMDAVL`,
    concat('PMDMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMDMAX`,
    concat('PMDMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMDMIN`,
    concat('PACLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACLED`,
    concat('PACCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACCOL`,
    concat('PACAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACAVL`,
    concat('PACMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACMAX`,
    concat('PACMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACMIN`,
    concat('PADLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADLED`,
    concat('PADCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADCOL`,
    concat('PADAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADAVL`,
    concat('PADMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADMAX`,
    concat('PADMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PADMIN`,
    concat('PTCLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCLED`,
    concat('PTCCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCCOL`,
    concat('PTCAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCAVL`,
    concat('PTCMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCMAX`,
    concat('PTCMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTCMIN`,
    concat('PTDLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTDLED`,
    concat('PTDCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTDCOL`,
    concat('PTDAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTDAVL`,
    concat('PTDMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTDMAX`,
    concat('PTDMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTDMIN`,
    concat('PPCLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCLED`,
    concat('PPCCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCCOL`,
    concat('PPCAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCAVL`,
    concat('PPCMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCMAX`,
    concat('PPCMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCMIN`,
    concat('PPDLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDLED`,
    concat('PPDCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDCOL`,
    concat('PPDAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDAVL`,
    concat('PPDMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDMAX`,
    concat('PPDMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPDMIN`,
    concat('PRTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTLED`,
    concat('PRTCOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTCOL`,
    concat('PRTAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTAVL`,
    concat('PRTMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTMAX`,
    concat('PRTMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTMIN`,
    concat('PRELED_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRELED`,
    concat('PRECOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRECOL`,
    concat('PREAVL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREAVL`,
    concat('PREMAX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREMAX`,
    concat('PREMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREMIN`,
    concat('PNEWDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNEWDA`,
    concat('PNEWFL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNEWFL`,
    concat('PACTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PACTYP`,
    concat('PSCTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSCTYP`,
    concat('PODLMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODLMT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PODCHG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PODFEE`,
    concat('PODFMX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODFMX`,
    concat('PODFPC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODFPC`,
    concat('PODFDY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODFDY`,
    concat('PODFBL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODFBL`,
    concat('PSGCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSGCOD`,
    concat('PCHKGT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCHKGT`,
    concat('PATMCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `PATMCR`,
    concat('PCOMBI_', lpad(CAST(idx AS STRING), 2, '0')) AS `PCOMBI`,
    concat('PMALHL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMALHL`,
    concat('PLSTPS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLSTPS`,
    concat('PAUTNS_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAUTNS`,
    concat('PNSFMX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PNSFMX`,
    concat('PODIMX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PODIMX`,
    concat('PPCHEC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPCHEC`,
    concat('PTRUNC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTRUNC`,
    concat('PPVAR1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PPVAR1`,
    concat('PXMASP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PXMASP`,
    concat('PDSIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSIC1`,
    concat('PDSIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSIC2`,
    concat('PDSIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSIC3`,
    concat('PDSIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PDSIC4`,
    concat('HISEXP_', lpad(CAST(idx AS STRING), 2, '0')) AS `HISEXP`,
    concat('PRTCKP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTCKP`,
    concat('PRTNEB_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTNEB`,
    concat('PSWINC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSWINC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSWCHG`,
    concat('PSWPRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSWPRT`,
    concat('ACHPNC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACHPNC`,
    concat('P2STMD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMD`,
    concat('P2PREF_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PREF`,
    concat('P2CKAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CKAD`,
    concat('P2TORE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TORE`,
    concat('P2EXHS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EXHS`,
    concat('P2CMIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CMIC`,
    concat('PRNAPY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRNAPY`,
    concat('PR2APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR2APY`,
    concat('PR3APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR3APY`,
    concat('PR4APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR4APY`,
    concat('PR5APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR5APY`,
    concat('PR6APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR6APY`,
    concat('PR7APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR7APY`,
    concat('PR8APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR8APY`,
    concat('PR9APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR9APY`,
    concat('PR0APY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PR0APY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `APYBAL`,
    concat('P2TTD1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TTD1`,
    concat('P2TTD2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TTD2`,
    concat('P2TTFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TTFE`,
    concat('P2TTRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2TTRC`,
    concat('P2IPPG_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IPPG`,
    concat('P2IFBK_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IFBK`,
    concat('P2ICKO_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ICKO`,
    concat('P2ICRS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ICRS`,
    concat('P2CLZR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CLZR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2PRNTRATE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2LOWBALNC`,
    concat('P2LOWTOLRN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2LOWTOLRN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2EARLYFEE`,
    concat('P2EARLYDYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EARLYDYS`,
    concat('P2PRNTADND_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PRNTADND`,
    idx AS `P2ADNDCNT`,
    concat('P2CALL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CALL`,
    concat('P2RS_TIME_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RS_TIME_CS`,
    concat('P2RS_ITEM_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RS_ITEM_CS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2CYCCHG$`,
    concat('P2CYCAAIT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CYCAAIT_CS`,
    concat('P2CYCFREE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2CYCFREE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2STMCHG$`,
    concat('P2STMAAIT_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMAAIT_CS`,
    concat('P2STMFREE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STMFREE`,
    concat('P2STCYRSFQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STCYRSFQ`,
    concat('P2STCYCGFQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STCYCGFQ`,
    concat('P2WAIVERET_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2WAIVERET`,
    concat('P2SWEEPNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWEEPNOT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2PYINTEOM`,
    concat('P2ODNOTDY1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY1`,
    concat('P2ODNOTDY2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY2`,
    concat('P2ODNOTDY3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY3`,
    concat('P2ODNOTDY4_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY4`,
    concat('P2ODNOTDY5_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY5`,
    concat('P2ODNOTDY6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODNOTDY6`,
    concat('P2STCYC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STCYC`,
    concat('P2SCCYC_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SCCYC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2INTCYC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2PRTINTR`,
    concat('P2USESFRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2USESFRM`,
    concat('P2ALLREDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ALLREDE`,
    concat('P2NOREDEP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2NOREDEP`,
    concat('P2SNDREDP_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SNDREDP`,
    concat('PUCFMX_', lpad(CAST(idx AS STRING), 2, '0')) AS `PUCFMX`,
    concat('P2DEFOFFWV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2DEFOFFWV`,
    concat('P2OFFREQWV_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2OFFREQWV`,
    concat('P2ODRGRPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODRGRPT`,
    concat('P2SWLDCL_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWLDCL`,
    concat('P2SWFLOAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWFLOAT`,
    concat('P2SWTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWTYPE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2SWPAYOF`,
    concat('P2SWLIMT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWLIMT`,
    concat('P2SETUPFAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SETUPFAM`,
    concat('P2SETUPFCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SETUPFCT`,
    concat('P2MTHLYFAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MTHLYFAM`,
    concat('P2MTHLYFCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2MTHLYFCT`,
    concat('P2EXCPTFAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EXCPTFAM`,
    concat('P2EXCPTFCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2EXCPTFCT`,
    concat('P2SWAPEG_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWAPEG`,
    concat('P2AVLTAB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AVLTAB`,
    concat('P2HSA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2HSA`,
    concat('P2STPNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2STPNOT`,
    concat('P2SWUTGB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2SWUTGB`,
    concat('P2PORCACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PORCACT`,
    concat('P2ODDAY_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODDAY`,
    concat('P2INQAVLTB_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2INQAVLTB`,
    concat('P2_ACR_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2_ACR_CS`,
    concat('P2R_ACR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2R_ACR`,
    concat('P2R_ACR_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2R_ACR_CS`,
    concat('P2_ADR_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2_ADR_CS`,
    concat('P2R_ADR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2R_ADR`,
    concat('P2R_ADR_CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2R_ADR_CS`,
    concat('P2ACPPSETA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ACPPSETA`,
    concat('P2ACPPMTHA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ACPPMTHA`,
    concat('P2ACPPEXCA_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ACPPEXCA`,
    concat('P2JHA1_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA1`,
    concat('P2JHA2_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA2`,
    concat('P2JHA3_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA3`,
    concat('P2JHA4_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA4`,
    concat('P2JHA5_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA5`,
    concat('P2JHA6_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA6`,
    concat('P2JHA7_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA7`,
    concat('P2JHA8_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2JHA8`,
    concat('P2ODDAYCN_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ODDAYCN`,
    idx AS `P2XRFNBR`,
    concat('P2PSCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSCOD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `P2PSFEEAMT`,
    concat('P2PSFEITEM_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSFEITEM`,
    concat('P2PSFECODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2PSFECODE`,
    concat('P2IMGACTFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2IMGACTFE`,
    concat('P2RWDSFLG_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2RWDSFLG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PCGBAL`,
    concat('PRTPRCY_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRTPRCY`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_ddpar2' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_ddpar2;
