-- Databricks SQL for source: pershingdataprod
-- Generated from sqlserver_desc/landing-pershingdataprod_caps_hist-desc.txt

CREATE CATALOG IF NOT EXISTS landing;
USE CATALOG landing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHINGDATAPROD_CAPS_HIST"
CREATE TABLE IF NOT EXISTS landing.default.pershingdataprod_caps_hist (
    `id` INT,
    `IBD_1` STRING,
    `RECORD_ID_1` STRING,
    `TRADE_DATE` STRING,
    `TRADE_REFERENCE_NUMBER` STRING,
    `PERSHING_OFFICE_NUMBER` STRING,
    `ACCOUNT_NUMBER` STRING,
    `ACCOUNT_NAME` STRING,
    `BUY_SELL_INDICATOR` STRING,
    `CANCEL_INDICATOR` STRING,
    `CAPS_SOURCE` STRING,
    `TRADE_QUANTITY` DECIMAL(38,10),
    `PRICE` DECIMAL(38,10),
    `PRODUCT_CODE` STRING,
    `CUSIP_NUMBER_OF_SECURITY_TRADED` STRING,
    `ACCOUNT_SHORT_NAME` STRING,
    `ORDER_TYPE` STRING,
    `MISCELLANEOUS_FEE` DECIMAL(38,10),
    `NOT_USED_1` STRING,
    `IBD_2` STRING,
    `RECORD_ID_2` STRING,
    `MARKET_CODE` STRING,
    `BLOTTER_CODE` STRING,
    `SECURITY_TYPE` STRING,
    `STOCK_SYMBOL` STRING,
    `SECURITY_DESCRIPTION` STRING,
    `CENTS_PER_SHARE` DECIMAL(38,10),
    `DISCOUNT_PERCENT` DECIMAL(38,10),
    `PAYCODE` STRING,
    `MASTER_CLIENT_MNEMONIC` STRING,
    `INSTITUTIONAL_RETAIL_INDICATOR` STRING,
    `STATE_CODE` STRING,
    `COMMISSION_INDICATOR` STRING,
    `FIRM_TRADING_ACCOUNT` STRING,
    `POSTED_DATE` STRING,
    `SETTLEMENT_DATE` STRING,
    `NOT_USED_2` STRING,
    `RECYCLE_INDICATOR` STRING,
    `IBD_3` STRING,
    `RECORD_ID_3` STRING,
    `AS_OF_TRADE_INDICATOR` STRING,
    `DISTRIBUTION_INDICATOR` STRING,
    `EXPLODE_INDICATOR` STRING,
    `REVENUE_TYPE` STRING,
    `IP` STRING,
    `IP_CAPS_REVENUE_CENTER` STRING,
    `IP_CAPS_OFFICE_NUMBER` STRING,
    `IP_SPLIT_PERCENT` DECIMAL(38,10),
    `TOTAL_AMT_OF_REV_GEN_BY_TR_AND_CRED_TO_IP` DECIMAL(38,10),
    `PERSHING_CHARGE` DECIMAL(38,10),
    `FROM_IP_NUMBER` STRING,
    `CAPS_REV_CENTER_ASSOC_W_THE_FROM_IP` STRING,
    `CAPS_OFFICE_NO_ASSOC_W_THE_FROM_IP` STRING,
    `TOTAL_ORDER_COMMISSION` DECIMAL(38,10),
    `SPREAD_STRADDLE` STRING,
    `CORRECTION_CODE` STRING,
    `SECURITY_MODIFIER` STRING,
    `SECURITY_CALCULATION_CODE` STRING,
    `PRINCIPAL` DECIMAL(38,10),
    `CRD_NUMBER` STRING,
    `SOURCE_OF_INPUT` STRING,
    `FOR_PERS_INT_USE_ONLY_3` STRING,
    `SERVICE_CHARGE_OTHER_FEE` DECIMAL(38,10),
    `IBD_4` STRING,
    `RECORD_ID_4` STRING,
    `CURRENCY_CODE` STRING,
    `CURRENCY_AMOUNT_OF_REVENUE` DECIMAL(38,10),
    `FOREIGN_EXCHANGE_RATE` DECIMAL(38,10),
    `CURRENCY_MULTI_DIV_INDICATOR` STRING,
    `IBD_SETTLEMENT_FEE` DECIMAL(38,10),
    `CUSTOMER_SETTLEMENT_FEE` DECIMAL(38,10),
    `GLOSS_REFERENCE_NUMBER` STRING,
    `CURRENCY_AMOUNT_OF_PERSHING_CHARGE` DECIMAL(38,10),
    `NOT_USED_4` STRING,
    `IBD_5` STRING,
    `RECORD_ID_5` STRING,
    `OPTION_ROOT_ID` STRING,
    `EXPIRATION_DATE` STRING,
    `CALL_PUT_INDICATOR` STRING,
    `STRIKE_PRICE` DECIMAL(38,10),
    `MASTER_CLIENT_NAME` STRING,
    `FOR_PERS_INT_USE_ONLY_5` STRING,
    `PERS_INT_ORDER_REF_NO` STRING,
    `NOT_USED_5` STRING,
    `AS_OF_DATE` DATE,
    `IMPORTED_DATE` TIMESTAMP,
    `LOADED_AT` TIMESTAMP,
    `YEARMONTH` INT
);
COMMENT ON TABLE landing.default.pershingdataprod_caps_hist IS
'The table contains Pershing CAPS historical trade and commission activity, including trade references, account identifiers, security details, quantities, prices, revenue amounts, fees, currency values, and settlement attributes. It supports landing-layer validation for trading activity, revenue allocation, commission review, and downstream Pershing reporting.';

TRUNCATE TABLE landing.default.pershingdataprod_caps_hist;

INSERT INTO landing.default.pershingdataprod_caps_hist (
    `id`, `IBD_1`, `RECORD_ID_1`, `TRADE_DATE`, `TRADE_REFERENCE_NUMBER`, `PERSHING_OFFICE_NUMBER`,
    `ACCOUNT_NUMBER`, `ACCOUNT_NAME`, `BUY_SELL_INDICATOR`, `CANCEL_INDICATOR`, `CAPS_SOURCE`, `TRADE_QUANTITY`,
    `PRICE`, `PRODUCT_CODE`, `CUSIP_NUMBER_OF_SECURITY_TRADED`, `ACCOUNT_SHORT_NAME`, `ORDER_TYPE`, `MISCELLANEOUS_FEE`,
    `NOT_USED_1`, `IBD_2`, `RECORD_ID_2`, `MARKET_CODE`, `BLOTTER_CODE`, `SECURITY_TYPE`,
    `STOCK_SYMBOL`, `SECURITY_DESCRIPTION`, `CENTS_PER_SHARE`, `DISCOUNT_PERCENT`, `PAYCODE`, `MASTER_CLIENT_MNEMONIC`,
    `INSTITUTIONAL_RETAIL_INDICATOR`, `STATE_CODE`, `COMMISSION_INDICATOR`, `FIRM_TRADING_ACCOUNT`, `POSTED_DATE`, `SETTLEMENT_DATE`,
    `NOT_USED_2`, `RECYCLE_INDICATOR`, `IBD_3`, `RECORD_ID_3`, `AS_OF_TRADE_INDICATOR`, `DISTRIBUTION_INDICATOR`,
    `EXPLODE_INDICATOR`, `REVENUE_TYPE`, `IP`, `IP_CAPS_REVENUE_CENTER`, `IP_CAPS_OFFICE_NUMBER`, `IP_SPLIT_PERCENT`,
    `TOTAL_AMT_OF_REV_GEN_BY_TR_AND_CRED_TO_IP`, `PERSHING_CHARGE`, `FROM_IP_NUMBER`, `CAPS_REV_CENTER_ASSOC_W_THE_FROM_IP`, `CAPS_OFFICE_NO_ASSOC_W_THE_FROM_IP`, `TOTAL_ORDER_COMMISSION`,
    `SPREAD_STRADDLE`, `CORRECTION_CODE`, `SECURITY_MODIFIER`, `SECURITY_CALCULATION_CODE`, `PRINCIPAL`, `CRD_NUMBER`,
    `SOURCE_OF_INPUT`, `FOR_PERS_INT_USE_ONLY_3`, `SERVICE_CHARGE_OTHER_FEE`, `IBD_4`, `RECORD_ID_4`, `CURRENCY_CODE`,
    `CURRENCY_AMOUNT_OF_REVENUE`, `FOREIGN_EXCHANGE_RATE`, `CURRENCY_MULTI_DIV_INDICATOR`, `IBD_SETTLEMENT_FEE`, `CUSTOMER_SETTLEMENT_FEE`, `GLOSS_REFERENCE_NUMBER`,
    `CURRENCY_AMOUNT_OF_PERSHING_CHARGE`, `NOT_USED_4`, `IBD_5`, `RECORD_ID_5`, `OPTION_ROOT_ID`, `EXPIRATION_DATE`,
    `CALL_PUT_INDICATOR`, `STRIKE_PRICE`, `MASTER_CLIENT_NAME`, `FOR_PERS_INT_USE_ONLY_5`, `PERS_INT_ORDER_REF_NO`, `NOT_USED_5`,
    `AS_OF_DATE`, `IMPORTED_DATE`, `LOADED_AT`, `YEARMONTH`
)
SELECT
    idx AS `id`,
    concat('IBD_1_', format_string('%02d', idx)) AS `IBD_1`,
    concat('RECORD_ID_1_', format_string('%02d', idx)) AS `RECORD_ID_1`,
    concat('TRADE_DATE_', format_string('%02d', idx)) AS `TRADE_DATE`,
    concat('TRADE_REFERENCE_NUMBER_', format_string('%02d', idx)) AS `TRADE_REFERENCE_NUMBER`,
    concat('PERSHING_OFFICE_NUMBER_', format_string('%02d', idx)) AS `PERSHING_OFFICE_NUMBER`,
    concat('ACCOUNT_NUMBER_', format_string('%02d', idx)) AS `ACCOUNT_NUMBER`,
    concat('ACCOUNT_NAME_', format_string('%02d', idx)) AS `ACCOUNT_NAME`,
    concat('BUY_SELL_INDICATOR_', format_string('%02d', idx)) AS `BUY_SELL_INDICATOR`,
    concat('CANCEL_INDICATOR_', format_string('%02d', idx)) AS `CANCEL_INDICATOR`,
    concat('CAPS_SOURCE_', format_string('%02d', idx)) AS `CAPS_SOURCE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TRADE_QUANTITY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRICE`,
    concat('PRODUCT_CODE_', format_string('%02d', idx)) AS `PRODUCT_CODE`,
    concat('CUSIP_NUMBER_OF_SECURITY_', format_string('%02d', idx)) AS `CUSIP_NUMBER_OF_SECURITY_TRADED`,
    concat('ACCOUNT_SHORT_NAME_', format_string('%02d', idx)) AS `ACCOUNT_SHORT_NAME`,
    concat('ORDER_TYPE_', format_string('%02d', idx)) AS `ORDER_TYPE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MISCELLANEOUS_FEE`,
    concat('NOT_USED_1_', format_string('%02d', idx)) AS `NOT_USED_1`,
    concat('IBD_2_', format_string('%02d', idx)) AS `IBD_2`,
    concat('RECORD_ID_2_', format_string('%02d', idx)) AS `RECORD_ID_2`,
    concat('MARKET_CODE_', format_string('%02d', idx)) AS `MARKET_CODE`,
    concat('BLOTTER_CODE_', format_string('%02d', idx)) AS `BLOTTER_CODE`,
    concat('SECURITY_TYPE_', format_string('%02d', idx)) AS `SECURITY_TYPE`,
    concat('STOCK_SYMBOL_', format_string('%02d', idx)) AS `STOCK_SYMBOL`,
    concat('SECURITY_DESCRIPTION_', format_string('%02d', idx)) AS `SECURITY_DESCRIPTION`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CENTS_PER_SHARE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `DISCOUNT_PERCENT`,
    concat('PAYCODE_', format_string('%02d', idx)) AS `PAYCODE`,
    concat('MASTER_CLIENT_MNEMONIC_', format_string('%02d', idx)) AS `MASTER_CLIENT_MNEMONIC`,
    concat('INSTITUTIONAL_RETAIL_IND_', format_string('%02d', idx)) AS `INSTITUTIONAL_RETAIL_INDICATOR`,
    concat('STATE_CODE_', format_string('%02d', idx)) AS `STATE_CODE`,
    concat('COMMISSION_INDICATOR_', format_string('%02d', idx)) AS `COMMISSION_INDICATOR`,
    concat('FIRM_TRADING_ACCOUNT_', format_string('%02d', idx)) AS `FIRM_TRADING_ACCOUNT`,
    concat('POSTED_DATE_', format_string('%02d', idx)) AS `POSTED_DATE`,
    concat('SETTLEMENT_DATE_', format_string('%02d', idx)) AS `SETTLEMENT_DATE`,
    concat('NOT_USED_2_', format_string('%02d', idx)) AS `NOT_USED_2`,
    concat('RECYCLE_INDICATOR_', format_string('%02d', idx)) AS `RECYCLE_INDICATOR`,
    concat('IBD_3_', format_string('%02d', idx)) AS `IBD_3`,
    concat('RECORD_ID_3_', format_string('%02d', idx)) AS `RECORD_ID_3`,
    concat('AS_OF_TRADE_INDICATOR_', format_string('%02d', idx)) AS `AS_OF_TRADE_INDICATOR`,
    concat('DISTRIBUTION_INDICATOR_', format_string('%02d', idx)) AS `DISTRIBUTION_INDICATOR`,
    concat('EXPLODE_INDICATOR_', format_string('%02d', idx)) AS `EXPLODE_INDICATOR`,
    concat('REVENUE_TYPE_', format_string('%02d', idx)) AS `REVENUE_TYPE`,
    concat('IP_', format_string('%02d', idx)) AS `IP`,
    concat('IP_CAPS_REVENUE_CENTER_', format_string('%02d', idx)) AS `IP_CAPS_REVENUE_CENTER`,
    concat('IP_CAPS_OFFICE_NUMBER_', format_string('%02d', idx)) AS `IP_CAPS_OFFICE_NUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `IP_SPLIT_PERCENT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TOTAL_AMT_OF_REV_GEN_BY_TR_AND_CRED_TO_IP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PERSHING_CHARGE`,
    concat('FROM_IP_NUMBER_', format_string('%02d', idx)) AS `FROM_IP_NUMBER`,
    concat('CAPS_REV_CENTER_ASSOC_W__', format_string('%02d', idx)) AS `CAPS_REV_CENTER_ASSOC_W_THE_FROM_IP`,
    concat('CAPS_OFFICE_NO_ASSOC_W_T_', format_string('%02d', idx)) AS `CAPS_OFFICE_NO_ASSOC_W_THE_FROM_IP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TOTAL_ORDER_COMMISSION`,
    concat('SPREAD_STRADDLE_', format_string('%02d', idx)) AS `SPREAD_STRADDLE`,
    concat('CORRECTION_CODE_', format_string('%02d', idx)) AS `CORRECTION_CODE`,
    concat('SECURITY_MODIFIER_', format_string('%02d', idx)) AS `SECURITY_MODIFIER`,
    concat('SECURITY_CALCULATION_COD_', format_string('%02d', idx)) AS `SECURITY_CALCULATION_CODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PRINCIPAL`,
    concat('CRD_NUMBER_', format_string('%02d', idx)) AS `CRD_NUMBER`,
    concat('SOURCE_OF_INPUT_', format_string('%02d', idx)) AS `SOURCE_OF_INPUT`,
    concat('FOR_PERS_INT_USE_ONLY_3_', format_string('%02d', idx)) AS `FOR_PERS_INT_USE_ONLY_3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SERVICE_CHARGE_OTHER_FEE`,
    concat('IBD_4_', format_string('%02d', idx)) AS `IBD_4`,
    concat('RECORD_ID_4_', format_string('%02d', idx)) AS `RECORD_ID_4`,
    concat('CURRENCY_CODE_', format_string('%02d', idx)) AS `CURRENCY_CODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CURRENCY_AMOUNT_OF_REVENUE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FOREIGN_EXCHANGE_RATE`,
    concat('CURRENCY_MULTI_DIV_INDIC_', format_string('%02d', idx)) AS `CURRENCY_MULTI_DIV_INDICATOR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `IBD_SETTLEMENT_FEE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CUSTOMER_SETTLEMENT_FEE`,
    concat('GLOSS_REFERENCE_NUMBER_', format_string('%02d', idx)) AS `GLOSS_REFERENCE_NUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CURRENCY_AMOUNT_OF_PERSHING_CHARGE`,
    concat('NOT_USED_4_', format_string('%02d', idx)) AS `NOT_USED_4`,
    concat('IBD_5_', format_string('%02d', idx)) AS `IBD_5`,
    concat('RECORD_ID_5_', format_string('%02d', idx)) AS `RECORD_ID_5`,
    concat('OPTION_ROOT_ID_', format_string('%02d', idx)) AS `OPTION_ROOT_ID`,
    concat('EXPIRATION_DATE_', format_string('%02d', idx)) AS `EXPIRATION_DATE`,
    concat('CALL_PUT_INDICATOR_', format_string('%02d', idx)) AS `CALL_PUT_INDICATOR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `STRIKE_PRICE`,
    concat('MASTER_CLIENT_NAME_', format_string('%02d', idx)) AS `MASTER_CLIENT_NAME`,
    concat('FOR_PERS_INT_USE_ONLY_5_', format_string('%02d', idx)) AS `FOR_PERS_INT_USE_ONLY_5`,
    concat('PERS_INT_ORDER_REF_NO_', format_string('%02d', idx)) AS `PERS_INT_ORDER_REF_NO`,
    concat('NOT_USED_5_', format_string('%02d', idx)) AS `NOT_USED_5`,
    date_add(DATE '2026-01-01', idx - 1) AS `AS_OF_DATE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `IMPORTED_DATE`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`,
    202601 AS `YEARMONTH`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershingdataprod_caps_hist' AS table_name, COUNT(*) AS record_count
FROM landing.default.pershingdataprod_caps_hist;
