-- Databricks SQL for source: pershing
-- Generated from sqlserver_landing_dbt/landing-pershing_ckff_rec_a.dbt.ms.sql

CREATE CATALOG IF NOT EXISTS landing_pershing;
USE CATALOG landing_pershing;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."PERSHING_CKFF_A"
CREATE TABLE IF NOT EXISTS landing_pershing.default.pershing_ckff_a (
    `TRANSACTION_CODE` STRING,
    `RECORD_TYPE` STRING,
    `RECORD_ID_SEQUENCE_NUMBER` STRING,
    `ACCOUNT_NUMBER` STRING,
    `TRANSACTION_AMOUNT` DECIMAL(18,2),
    `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER` STRING,
    `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER` STRING,
    `INTERMEDIARY_DESCRIPTION_LINE_1` STRING,
    `INTERMEDIARY_DESCRIPTION_LINE_2` STRING,
    `ACCOUNT_WITH_INSTITUTION` STRING,
    `BENEFICIARY_CUSTOMER_1` STRING,
    `BENEFICIARY_CUSTOMER_2` STRING,
    `BENEFICIARY_CUSTOMER_3` STRING,
    `BENEFICIARY_CUSTOMER_4` STRING,
    `OUTGOING_WIRES_ADD_INFO1_OR_DESC_TRANSACT` STRING,
    `OUTGOING_WIRES_ADD_INFO2_OR_ABA_NUMBER` STRING,
    `OUTGOING_WIRES_ADD_INFO3_OR_DDA_NUMBER` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO4` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO5` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO6` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO7` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO8` STRING,
    `OUTGOING_WIRES_ACH_ADD_INFO9` STRING,
    `DUPLICATE_RECORD_INDICATOR` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_pershing.default.pershing_ckff_a IS
'Pershing landing table containing cash, fund, income, security activity, and transaction attributes sourced from SQL Server dbt bronze logic for validation, reconciliation, and downstream brokerage reporting.';

TRUNCATE TABLE landing_pershing.default.pershing_ckff_a;

INSERT INTO landing_pershing.default.pershing_ckff_a (
    `TRANSACTION_CODE`, `RECORD_TYPE`, `RECORD_ID_SEQUENCE_NUMBER`, `ACCOUNT_NUMBER`, `TRANSACTION_AMOUNT`,
    `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`, `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    `INTERMEDIARY_DESCRIPTION_LINE_1`, `INTERMEDIARY_DESCRIPTION_LINE_2`, `ACCOUNT_WITH_INSTITUTION`,
    `BENEFICIARY_CUSTOMER_1`, `BENEFICIARY_CUSTOMER_2`, `BENEFICIARY_CUSTOMER_3`, `BENEFICIARY_CUSTOMER_4`,
    `OUTGOING_WIRES_ADD_INFO1_OR_DESC_TRANSACT`, `OUTGOING_WIRES_ADD_INFO2_OR_ABA_NUMBER`,
    `OUTGOING_WIRES_ADD_INFO3_OR_DDA_NUMBER`, `OUTGOING_WIRES_ACH_ADD_INFO4`, `OUTGOING_WIRES_ACH_ADD_INFO5`,
    `OUTGOING_WIRES_ACH_ADD_INFO6`, `OUTGOING_WIRES_ACH_ADD_INFO7`, `OUTGOING_WIRES_ACH_ADD_INFO8`,
    `OUTGOING_WIRES_ACH_ADD_INFO9`, `DUPLICATE_RECORD_INDICATOR`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('TRANSACTION_CODE_', format_string('%02d', idx)) AS `TRANSACTION_CODE`,
    concat('RECORD_TYPE_', format_string('%02d', idx)) AS `RECORD_TYPE`,
    concat('RECORD_ID_SEQUENCE_NUMBE_', format_string('%02d', idx)) AS `RECORD_ID_SEQUENCE_NUMBER`,
    concat('ACCOUNT_NUMBER_', format_string('%02d', idx)) AS `ACCOUNT_NUMBER`,
    TRY_CAST(idx * 100.25 AS DECIMAL(18,2)) AS `TRANSACTION_AMOUNT`,
    concat('LEGACY_INVESTMENT_PROFES_', format_string('%02d', idx)) AS `LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    concat('EXPANDED_INVESTMENT_PROF_', format_string('%02d', idx)) AS `EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER`,
    concat('INTERMEDIARY_DESCRIPTION_', format_string('%02d', idx)) AS `INTERMEDIARY_DESCRIPTION_LINE_1`,
    concat('INTERMEDIARY_DESCRIPTION_', format_string('%02d', idx)) AS `INTERMEDIARY_DESCRIPTION_LINE_2`,
    concat('ACCOUNT_WITH_INSTITUTION_', format_string('%02d', idx)) AS `ACCOUNT_WITH_INSTITUTION`,
    concat('BENEFICIARY_CUSTOMER_1_', format_string('%02d', idx)) AS `BENEFICIARY_CUSTOMER_1`,
    concat('BENEFICIARY_CUSTOMER_2_', format_string('%02d', idx)) AS `BENEFICIARY_CUSTOMER_2`,
    concat('BENEFICIARY_CUSTOMER_3_', format_string('%02d', idx)) AS `BENEFICIARY_CUSTOMER_3`,
    concat('BENEFICIARY_CUSTOMER_4_', format_string('%02d', idx)) AS `BENEFICIARY_CUSTOMER_4`,
    concat('OUTGOING_WIRES_ADD_INFO1_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ADD_INFO1_OR_DESC_TRANSACT`,
    concat('OUTGOING_WIRES_ADD_INFO2_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ADD_INFO2_OR_ABA_NUMBER`,
    concat('OUTGOING_WIRES_ADD_INFO3_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ADD_INFO3_OR_DDA_NUMBER`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO4`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO5`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO6`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO7`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO8`,
    concat('OUTGOING_WIRES_ACH_ADD_I_', format_string('%02d', idx)) AS `OUTGOING_WIRES_ACH_ADD_INFO9`,
    concat('DUPLICATE_RECORD_INDICAT_', format_string('%02d', idx)) AS `DUPLICATE_RECORD_INDICATOR`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'pershing_ckff_a' AS table_name, COUNT(*) AS record_count
FROM landing_pershing.default.pershing_ckff_a;
