-- Databricks SQL for source: jh_glmast
-- Generated from sqlserver_brz/brz-jh_glmast.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_GLMAST"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_glmast (
    `BANKNO` INT,
    `BRANCH` INT,
    `ACCTNO` INT,
    `CONACC` STRING,
    `CENTER` STRING,
    `PRDCOD` STRING,
    `STATUS` STRING,
    `POST` STRING,
    `TITLE` STRING,
    `ACTYPE` INT,
    `REPTYP` STRING,
    `ACTSEQ` STRING,
    `LEVEL` STRING,
    `OFFICR` STRING,
    `BALCOD` DECIMAL(38,10),
    `PSTFRQ` STRING,
    `TRNTYP` STRING,
    `MANDES` STRING,
    `MANOFF` STRING,
    `RISK` STRING,
    `CALRP1` STRING,
    `CALRP2` STRING,
    `CALRP3` STRING,
    `CALRP4` STRING,
    `COND1` STRING,
    `COND2` STRING,
    `COND3` STRING,
    `COND4` STRING,
    `COND5` STRING,
    `COND6` STRING,
    `COND7` STRING,
    `COND8` STRING,
    `COND9` STRING,
    `GLSIC1` STRING,
    `GLSIC2` STRING,
    `GLSIC3` STRING,
    `GLSIC4` STRING,
    `DATCV7` STRING,
    `DATCV6` STRING,
    `DLA7` STRING,
    `DLA6` STRING,
    `DATOP7` STRING,
    `DATOP6` STRING,
    `DATEN7` STRING,
    `DATEN6` STRING,
    `DLM7` STRING,
    `DLM6` STRING,
    `CURBAL` DECIMAL(38,10),
    `NETCHG` DECIMAL(38,10),
    `YESBAL` DECIMAL(38,10),
    `BEGCYR` STRING,
    `BEGLYR` STRING,
    `BEGPYR` STRING,
    `MTDBAL` DECIMAL(38,10),
    `QTDBAL` DECIMAL(38,10),
    `YTDBAL` DECIMAL(38,10),
    `MTDAVG` DECIMAL(38,10),
    `QTDAVG` DECIMAL(38,10),
    `YTDAVG` DECIMAL(38,10),
    `YTDAVL` DECIMAL(38,10),
    `YTDAVP` DECIMAL(38,10),
    `MAGBAL` DECIMAL(38,10),
    `QAGBAL` DECIMAL(38,10),
    `YAGBAL` DECIMAL(38,10),
    `GLPIC1` STRING,
    `GLPIC2` STRING,
    `GLPD71` STRING,
    `GLPD61` STRING,
    `GLPD72` STRING,
    `GLPD62` STRING,
    `GLPAM1` STRING,
    `GLPAM2` STRING,
    `GLPAM3` STRING,
    `GLPAM4` STRING,
    `CMEB1` STRING,
    `CMEB2` STRING,
    `CMEB3` STRING,
    `CMEB4` STRING,
    `CMEB5` STRING,
    `CMEB6` STRING,
    `CMEB7` STRING,
    `CMEB8` STRING,
    `CMEB9` STRING,
    `CMEB10` STRING,
    `CMEB11` STRING,
    `CMEB12` STRING,
    `LMEB1` STRING,
    `LMEB2` STRING,
    `LMEB3` STRING,
    `LMEB4` STRING,
    `LMEB5` STRING,
    `LMEB6` STRING,
    `LMEB7` STRING,
    `LMEB8` STRING,
    `LMEB9` STRING,
    `LMEB10` STRING,
    `LMEB11` STRING,
    `LMEB12` STRING,
    `PMEB1` STRING,
    `PMEB2` STRING,
    `PMEB3` STRING,
    `PMEB4` STRING,
    `PMEB5` STRING,
    `PMEB6` STRING,
    `PMEB7` STRING,
    `PMEB8` STRING,
    `PMEB9` STRING,
    `PMEB10` STRING,
    `PMEB11` STRING,
    `PMEB12` STRING,
    `CMTD1` DECIMAL(38,10),
    `CMTD2` DECIMAL(38,10),
    `CMTD3` DECIMAL(38,10),
    `CMTD4` DECIMAL(38,10),
    `CMTD5` DECIMAL(38,10),
    `CMTD6` DECIMAL(38,10),
    `CMTD7` DECIMAL(38,10),
    `CMTD8` DECIMAL(38,10),
    `CMTD9` DECIMAL(38,10),
    `CMTD10` DECIMAL(38,10),
    `CMTD11` DECIMAL(38,10),
    `CMTD12` DECIMAL(38,10),
    `LMTD1` DECIMAL(38,10),
    `LMTD2` DECIMAL(38,10),
    `LMTD3` DECIMAL(38,10),
    `LMTD4` DECIMAL(38,10),
    `LMTD5` DECIMAL(38,10),
    `LMTD6` DECIMAL(38,10),
    `LMTD7` DECIMAL(38,10),
    `LMTD8` DECIMAL(38,10),
    `LMTD9` DECIMAL(38,10),
    `LMTD10` DECIMAL(38,10),
    `LMTD11` DECIMAL(38,10),
    `LMTD12` DECIMAL(38,10),
    `PMTD1` DECIMAL(38,10),
    `PMTD2` DECIMAL(38,10),
    `PMTD3` DECIMAL(38,10),
    `PMTD4` DECIMAL(38,10),
    `PMTD5` DECIMAL(38,10),
    `PMTD6` DECIMAL(38,10),
    `PMTD7` DECIMAL(38,10),
    `PMTD8` DECIMAL(38,10),
    `PMTD9` DECIMAL(38,10),
    `PMTD10` DECIMAL(38,10),
    `PMTD11` DECIMAL(38,10),
    `PMTD12` DECIMAL(38,10),
    `CAGG1` STRING,
    `CAGG2` STRING,
    `CAGG3` STRING,
    `CAGG4` STRING,
    `CAGG5` STRING,
    `CAGG6` STRING,
    `CAGG7` STRING,
    `CAGG8` STRING,
    `CAGG9` STRING,
    `CAGG10` STRING,
    `CAGG11` STRING,
    `CAGG12` STRING,
    `LAGG1` STRING,
    `LAGG2` STRING,
    `LAGG3` STRING,
    `LAGG4` STRING,
    `LAGG5` STRING,
    `LAGG6` STRING,
    `LAGG7` STRING,
    `LAGG8` STRING,
    `LAGG9` STRING,
    `LAGG10` STRING,
    `LAGG11` STRING,
    `LAGG12` STRING,
    `PAGG1` STRING,
    `PAGG2` STRING,
    `PAGG3` STRING,
    `PAGG4` STRING,
    `PAGG5` STRING,
    `PAGG6` STRING,
    `PAGG7` STRING,
    `PAGG8` STRING,
    `PAGG9` STRING,
    `PAGG10` STRING,
    `PAGG11` STRING,
    `PAGG12` STRING,
    `CAVG1` DECIMAL(38,10),
    `CAVG2` DECIMAL(38,10),
    `CAVG3` DECIMAL(38,10),
    `CAVG4` DECIMAL(38,10),
    `CAVG5` DECIMAL(38,10),
    `CAVG6` DECIMAL(38,10),
    `CAVG7` DECIMAL(38,10),
    `CAVG8` DECIMAL(38,10),
    `CAVG9` DECIMAL(38,10),
    `CAVG10` DECIMAL(38,10),
    `CAVG11` DECIMAL(38,10),
    `CAVG12` DECIMAL(38,10),
    `LAVG1` DECIMAL(38,10),
    `LAVG2` DECIMAL(38,10),
    `LAVG3` DECIMAL(38,10),
    `LAVG4` DECIMAL(38,10),
    `LAVG5` DECIMAL(38,10),
    `LAVG6` DECIMAL(38,10),
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_glmast IS
'The JH_GLMAST landing table captures Jack Henry general ledger account, transaction, posting, balance, effective date, and reference attributes for ledger validation, reconciliation, and downstream reporting.';

TRUNCATE TABLE landing_jh.default.jh_glmast;

INSERT INTO landing_jh.default.jh_glmast (
    `BANKNO`, `BRANCH`, `ACCTNO`, `CONACC`, `CENTER`, `PRDCOD`,
    `STATUS`, `POST`, `TITLE`, `ACTYPE`, `REPTYP`, `ACTSEQ`,
    `LEVEL`, `OFFICR`, `BALCOD`, `PSTFRQ`, `TRNTYP`, `MANDES`,
    `MANOFF`, `RISK`, `CALRP1`, `CALRP2`, `CALRP3`, `CALRP4`,
    `COND1`, `COND2`, `COND3`, `COND4`, `COND5`, `COND6`,
    `COND7`, `COND8`, `COND9`, `GLSIC1`, `GLSIC2`, `GLSIC3`,
    `GLSIC4`, `DATCV7`, `DATCV6`, `DLA7`, `DLA6`, `DATOP7`,
    `DATOP6`, `DATEN7`, `DATEN6`, `DLM7`, `DLM6`, `CURBAL`,
    `NETCHG`, `YESBAL`, `BEGCYR`, `BEGLYR`, `BEGPYR`, `MTDBAL`,
    `QTDBAL`, `YTDBAL`, `MTDAVG`, `QTDAVG`, `YTDAVG`, `YTDAVL`,
    `YTDAVP`, `MAGBAL`, `QAGBAL`, `YAGBAL`, `GLPIC1`, `GLPIC2`,
    `GLPD71`, `GLPD61`, `GLPD72`, `GLPD62`, `GLPAM1`, `GLPAM2`,
    `GLPAM3`, `GLPAM4`, `CMEB1`, `CMEB2`, `CMEB3`, `CMEB4`,
    `CMEB5`, `CMEB6`, `CMEB7`, `CMEB8`, `CMEB9`, `CMEB10`,
    `CMEB11`, `CMEB12`, `LMEB1`, `LMEB2`, `LMEB3`, `LMEB4`,
    `LMEB5`, `LMEB6`, `LMEB7`, `LMEB8`, `LMEB9`, `LMEB10`,
    `LMEB11`, `LMEB12`, `PMEB1`, `PMEB2`, `PMEB3`, `PMEB4`,
    `PMEB5`, `PMEB6`, `PMEB7`, `PMEB8`, `PMEB9`, `PMEB10`,
    `PMEB11`, `PMEB12`, `CMTD1`, `CMTD2`, `CMTD3`, `CMTD4`,
    `CMTD5`, `CMTD6`, `CMTD7`, `CMTD8`, `CMTD9`, `CMTD10`,
    `CMTD11`, `CMTD12`, `LMTD1`, `LMTD2`, `LMTD3`, `LMTD4`,
    `LMTD5`, `LMTD6`, `LMTD7`, `LMTD8`, `LMTD9`, `LMTD10`,
    `LMTD11`, `LMTD12`, `PMTD1`, `PMTD2`, `PMTD3`, `PMTD4`,
    `PMTD5`, `PMTD6`, `PMTD7`, `PMTD8`, `PMTD9`, `PMTD10`,
    `PMTD11`, `PMTD12`, `CAGG1`, `CAGG2`, `CAGG3`, `CAGG4`,
    `CAGG5`, `CAGG6`, `CAGG7`, `CAGG8`, `CAGG9`, `CAGG10`,
    `CAGG11`, `CAGG12`, `LAGG1`, `LAGG2`, `LAGG3`, `LAGG4`,
    `LAGG5`, `LAGG6`, `LAGG7`, `LAGG8`, `LAGG9`, `LAGG10`,
    `LAGG11`, `LAGG12`, `PAGG1`, `PAGG2`, `PAGG3`, `PAGG4`,
    `PAGG5`, `PAGG6`, `PAGG7`, `PAGG8`, `PAGG9`, `PAGG10`,
    `PAGG11`, `PAGG12`, `CAVG1`, `CAVG2`, `CAVG3`, `CAVG4`,
    `CAVG5`, `CAVG6`, `CAVG7`, `CAVG8`, `CAVG9`, `CAVG10`,
    `CAVG11`, `CAVG12`, `LAVG1`, `LAVG2`, `LAVG3`, `LAVG4`,
    `LAVG5`, `LAVG6`, `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `BANKNO`,
    idx AS `BRANCH`,
    idx AS `ACCTNO`,
    concat('CONACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CONACC`,
    concat('CENTER_', lpad(CAST(idx AS STRING), 2, '0')) AS `CENTER`,
    concat('PRDCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRDCOD`,
    concat('STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `STATUS`,
    concat('POST_', lpad(CAST(idx AS STRING), 2, '0')) AS `POST`,
    concat('TITLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `TITLE`,
    idx AS `ACTYPE`,
    concat('REPTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `REPTYP`,
    concat('ACTSEQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTSEQ`,
    concat('LEVEL_', lpad(CAST(idx AS STRING), 2, '0')) AS `LEVEL`,
    concat('OFFICR_', lpad(CAST(idx AS STRING), 2, '0')) AS `OFFICR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BALCOD`,
    concat('PSTFRQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `PSTFRQ`,
    concat('TRNTYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `TRNTYP`,
    concat('MANDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `MANDES`,
    concat('MANOFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `MANOFF`,
    concat('RISK_', lpad(CAST(idx AS STRING), 2, '0')) AS `RISK`,
    concat('CALRP1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CALRP1`,
    concat('CALRP2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CALRP2`,
    concat('CALRP3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CALRP3`,
    concat('CALRP4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CALRP4`,
    concat('COND1_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND1`,
    concat('COND2_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND2`,
    concat('COND3_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND3`,
    concat('COND4_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND4`,
    concat('COND5_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND5`,
    concat('COND6_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND6`,
    concat('COND7_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND7`,
    concat('COND8_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND8`,
    concat('COND9_', lpad(CAST(idx AS STRING), 2, '0')) AS `COND9`,
    concat('GLSIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLSIC1`,
    concat('GLSIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLSIC2`,
    concat('GLSIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLSIC3`,
    concat('GLSIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLSIC4`,
    concat('DATCV7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATCV7`,
    concat('DATCV6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATCV6`,
    concat('DLA7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DLA7`,
    concat('DLA6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DLA6`,
    concat('DATOP7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATOP7`,
    concat('DATOP6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATOP6`,
    concat('DATEN7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATEN7`,
    concat('DATEN6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DATEN6`,
    concat('DLM7_', lpad(CAST(idx AS STRING), 2, '0')) AS `DLM7`,
    concat('DLM6_', lpad(CAST(idx AS STRING), 2, '0')) AS `DLM6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CURBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `NETCHG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YESBAL`,
    concat('BEGCYR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGCYR`,
    concat('BEGLYR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGLYR`,
    concat('BEGPYR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGPYR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTDAVG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QTDAVG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDAVG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDAVL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDAVP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MAGBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `QAGBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YAGBAL`,
    concat('GLPIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPIC1`,
    concat('GLPIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPIC2`,
    concat('GLPD71_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPD71`,
    concat('GLPD61_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPD61`,
    concat('GLPD72_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPD72`,
    concat('GLPD62_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPD62`,
    concat('GLPAM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPAM1`,
    concat('GLPAM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPAM2`,
    concat('GLPAM3_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPAM3`,
    concat('GLPAM4_', lpad(CAST(idx AS STRING), 2, '0')) AS `GLPAM4`,
    concat('CMEB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB1`,
    concat('CMEB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB2`,
    concat('CMEB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB3`,
    concat('CMEB4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB4`,
    concat('CMEB5_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB5`,
    concat('CMEB6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB6`,
    concat('CMEB7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB7`,
    concat('CMEB8_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB8`,
    concat('CMEB9_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB9`,
    concat('CMEB10_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB10`,
    concat('CMEB11_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB11`,
    concat('CMEB12_', lpad(CAST(idx AS STRING), 2, '0')) AS `CMEB12`,
    concat('LMEB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB1`,
    concat('LMEB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB2`,
    concat('LMEB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB3`,
    concat('LMEB4_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB4`,
    concat('LMEB5_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB5`,
    concat('LMEB6_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB6`,
    concat('LMEB7_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB7`,
    concat('LMEB8_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB8`,
    concat('LMEB9_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB9`,
    concat('LMEB10_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB10`,
    concat('LMEB11_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB11`,
    concat('LMEB12_', lpad(CAST(idx AS STRING), 2, '0')) AS `LMEB12`,
    concat('PMEB1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB1`,
    concat('PMEB2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB2`,
    concat('PMEB3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB3`,
    concat('PMEB4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB4`,
    concat('PMEB5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB5`,
    concat('PMEB6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB6`,
    concat('PMEB7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB7`,
    concat('PMEB8_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB8`,
    concat('PMEB9_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB9`,
    concat('PMEB10_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB10`,
    concat('PMEB11_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB11`,
    concat('PMEB12_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMEB12`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD10`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD11`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CMTD12`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD10`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD11`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LMTD12`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD10`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD11`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PMTD12`,
    concat('CAGG1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG1`,
    concat('CAGG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG2`,
    concat('CAGG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG3`,
    concat('CAGG4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG4`,
    concat('CAGG5_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG5`,
    concat('CAGG6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG6`,
    concat('CAGG7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG7`,
    concat('CAGG8_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG8`,
    concat('CAGG9_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG9`,
    concat('CAGG10_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG10`,
    concat('CAGG11_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG11`,
    concat('CAGG12_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAGG12`,
    concat('LAGG1_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG1`,
    concat('LAGG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG2`,
    concat('LAGG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG3`,
    concat('LAGG4_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG4`,
    concat('LAGG5_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG5`,
    concat('LAGG6_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG6`,
    concat('LAGG7_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG7`,
    concat('LAGG8_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG8`,
    concat('LAGG9_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG9`,
    concat('LAGG10_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG10`,
    concat('LAGG11_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG11`,
    concat('LAGG12_', lpad(CAST(idx AS STRING), 2, '0')) AS `LAGG12`,
    concat('PAGG1_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG1`,
    concat('PAGG2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG2`,
    concat('PAGG3_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG3`,
    concat('PAGG4_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG4`,
    concat('PAGG5_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG5`,
    concat('PAGG6_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG6`,
    concat('PAGG7_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG7`,
    concat('PAGG8_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG8`,
    concat('PAGG9_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG9`,
    concat('PAGG10_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG10`,
    concat('PAGG11_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG11`,
    concat('PAGG12_', lpad(CAST(idx AS STRING), 2, '0')) AS `PAGG12`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG7`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG8`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG10`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG11`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CAVG12`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LAVG6`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_glmast' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_glmast;
