-- Databricks SQL for source: jh_dmilay
-- Generated from sqlserver/brz-jh_dmilay.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_DMILAY"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_dmilay (
    `LOANNO` INT,
    `OLDLOANNO` INT,
    `BILLNAME` STRING,
    `BANK` STRING,
    `AGGR` STRING,
    `NEXTDUE` STRING,
    `FIRSTPRINB` STRING,
    `ORGMTGAM` STRING,
    `LOANDATE` STRING,
    `MATDATE` STRING,
    `ANNUALIN` STRING,
    `LOANTERM` STRING,
    `REMTERM` STRING,
    `PRODLINECD` STRING,
    `ARMIND` STRING,
    `ARMINDESC` STRING,
    `ORGPROPVAL` STRING,
    `PROPVAL` STRING,
    `PROPERTYST` STRING,
    `PROPERTYCT` STRING,
    `PROPSTATE` STRING,
    `PROPZIP` STRING,
    `SSNCODE` STRING,
    `PTFNMACODE` STRING,
    `PTFNMADESC` STRING,
    `INVESTLOAN` STRING,
    `OCCCODE` STRING,
    `OCCUDESC` STRING,
    `LNPURPCODE` STRING,
    `LNPURPDESC` STRING,
    `HITYPE` STRING,
    `HITYPEDESC` STRING,
    `LOTYPE` STRING,
    `LOTYPEDESC` STRING,
    `FIRSTDUE` STRING,
    `FIRSTP` STRING,
    `FSTSERFE` STRING,
    `FORECLSCOD` STRING,
    `FORECLSDES` STRING,
    `ORGLT` STRING,
    `INTPDTHRU` DECIMAL(38,10),
    `ESCROWBA` STRING,
    `ESCROWAD` STRING,
    `PLGCODE` STRING,
    `PLGDESC` STRING,
    `PMNTPERD` STRING,
    `BADCHKTBLE` STRING,
    `TIMESDLQ` STRING,
    `TOTPMN` STRING,
    `NOOFUNIT` STRING,
    `INTFLAG` DECIMAL(38,10),
    `INTFLAGDES` DECIMAL(38,10),
    `CAPLNFLAG` STRING,
    `CAPLNFDESC` STRING,
    `MTGRLNAME` STRING,
    `MTGRFNAME` STRING,
    `MTGRHAZPAY` DECIMAL(38,10),
    `TIPMN` STRING,
    `GUARFE` STRING,
    `RECFLAG` STRING,
    `RECFLAGDES` STRING,
    `POOLNUM` INT,
    `DLQPMNTCNT` INT,
    `IOEFLAG` STRING,
    `IOEFLAGDES` STRING,
    `MANCODE` STRING,
    `BBCODE` STRING,
    `BRNCHOFF` STRING,
    `ACRLSTAT` STRING,
    `PREPMNTIND` STRING,
    `FHLBBPP` STRING,
    `FSTORGCOS` STRING,
    `FSTORIGFE` STRING,
    `FSTUNAMOR` STRING,
    `ARMIREFFDT` STRING,
    `ARMORGI` STRING,
    `ARMMARGI` STRING,
    `ARMPIEFFDT` STRING,
    `ARMCHGPRD` DECIMAL(38,10),
    `ARMPICHGPR` DECIMAL(38,10),
    `ARMIRMAXC` STRING,
    `ARMIRMAXF` STRING,
    `ARMIMAXIN` STRING,
    `ARMIMAXDE` STRING,
    `AIRMAXLIN` STRING,
    `AIRMAXLDE` STRING,
    `APIMAXPCT` STRING,
    `APIMAXPCD` STRING,
    `APIMAXLIF` STRING,
    `APIPCTMIN` STRING,
    `APIPCTMDE` STRING,
    `AORGPIAM` STRING,
    `ARMINDE` STRING,
    `ARMIRRAT` STRING,
    `AOIRCHGDT` DECIMAL(38,10),
    `AIRRNDTP` STRING,
    `AIRRNDDESC` STRING,
    `AIRRNDFAC` STRING,
    `ARMPLANID` STRING,
    `ARMPLANDES` STRING,
    `ARMINDCO` STRING,
    `ARMINDDESC` STRING,
    `AILEADDAYS` STRING,
    `USR15POS1` STRING,
    `USR2POS1A` STRING,
    `USR2POS2A` STRING,
    `DFTIND` STRING,
    `BANKNAME` STRING,
    `LOT` STRING,
    `BLOCK` STRING,
    `SUBDIV` STRING,
    `COUNTYCODE` STRING,
    `COUNTYTA` STRING,
    `HAZMONTHL` STRING,
    `LASTANALDT` STRING,
    `ESCMINBAL` DECIMAL(38,10),
    `LASTANALO` STRING,
    `OVSHTCHGDT` DECIMAL(38,10),
    `MORTSSNO` INT,
    `COMORTSSNO` INT,
    `SSNCERTDT` STRING,
    `SSNVERCODE` STRING,
    `SSNVERDATE` STRING,
    `SETUPDATE` STRING,
    `SUSPBA` STRING,
    `RESTESCBA` STRING,
    `CRQUALCODE` STRING,
    `INTONLYIND` DECIMAL(38,10),
    `PAYFULLDT` DECIMAL(38,10),
    `SERVSOLDDT` STRING,
    `COMTGLNAME` STRING,
    `COMTGFNAME` STRING,
    `FLOZPOS1` STRING,
    `MTGRDOB` STRING,
    `COMTGRDOB` STRING,
    `PROPUNITNO` INT,
    `LTVN` STRING,
    `BILLADDR3` STRING,
    `BILLADDR4` STRING,
    `BILLCITY` STRING,
    `BILLSTATE` STRING,
    `BILLZIP` STRING,
    `ORIGSCORE` STRING,
    `BILLADDR2` STRING,
    `USR1POS3A` STRING,
    `CHGOFFBALN` DECIMAL(38,10),
    `ACCLATECAN` STRING,
    `LATECFN` STRING,
    `GRACEDAYS` STRING,
    `LCCODE` STRING,
    `PHONE` STRING,
    `PHONE2` STRING,
    `EMAILF` STRING,
    `PROCSC` STRING,
    `DAIND` STRING,
    `CSBORCBC` STRING,
    `CSBORCBST` STRING,
    `FIRSTFF1N` STRING,
    `ASSUMDATE` STRING,
    `VACDATE` STRING,
    `LNMODDATE` STRING,
    `USR20POS1A` STRING,
    `RECOVECABN` STRING,
    `NONRECCABN` STRING,
    `THIRDPRCBN` STRING,
    `PENDPIAMTN` DECIMAL(38,10),
    `ADLCBN1` STRING,
    `ADLCSTN1` STRING,
    `ADLCBS` STRING,
    `ADLCBC` STRING,
    `ADLCBST` STRING,
    `ADLCBZC` STRING,
    `ADLCBPN` STRING,
    `LASTFPAYDT` DECIMAL(38,10),
    `YTDINTAMTN` DECIMAL(38,10),
    `YTDPPAMTN` DECIMAL(38,10),
    `YTDTAXAMTN` DECIMAL(38,10),
    `YTDHAZAMTN` DECIMAL(38,10),
    `USR1PO4A` STRING,
    `DAYDELIQU` STRING,
    `ENTERNONAC` STRING,
    `LEAVENONAC` STRING,
    `APPRAIDATE` STRING,
    `LNMOAPPDAT` STRING,
    `LNMOAPPAM` STRING,
    `CHAROFFDAT` STRING,
    `DRROUTRNU` STRING,
    `FIORCOSAM` STRING,
    `FIORFEEAM` DECIMAL(38,10),
    `NextDueDate` STRING,
    `OriginalLoanDate` STRING,
    `MaturityDate` STRING,
    `FirstDueDate` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_dmilay IS
'The JH DMILAY landing table captures DMI layout and loan-related interface attributes from Jack Henry for source validation, reconciliation, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_dmilay;

INSERT INTO landing_jh.default.jh_dmilay (
    `LOANNO`, `OLDLOANNO`, `BILLNAME`, `BANK`, `AGGR`, `NEXTDUE`,
    `FIRSTPRINB`, `ORGMTGAM`, `LOANDATE`, `MATDATE`, `ANNUALIN`, `LOANTERM`,
    `REMTERM`, `PRODLINECD`, `ARMIND`, `ARMINDESC`, `ORGPROPVAL`, `PROPVAL`,
    `PROPERTYST`, `PROPERTYCT`, `PROPSTATE`, `PROPZIP`, `SSNCODE`, `PTFNMACODE`,
    `PTFNMADESC`, `INVESTLOAN`, `OCCCODE`, `OCCUDESC`, `LNPURPCODE`, `LNPURPDESC`,
    `HITYPE`, `HITYPEDESC`, `LOTYPE`, `LOTYPEDESC`, `FIRSTDUE`, `FIRSTP`,
    `FSTSERFE`, `FORECLSCOD`, `FORECLSDES`, `ORGLT`, `INTPDTHRU`, `ESCROWBA`,
    `ESCROWAD`, `PLGCODE`, `PLGDESC`, `PMNTPERD`, `BADCHKTBLE`, `TIMESDLQ`,
    `TOTPMN`, `NOOFUNIT`, `INTFLAG`, `INTFLAGDES`, `CAPLNFLAG`, `CAPLNFDESC`,
    `MTGRLNAME`, `MTGRFNAME`, `MTGRHAZPAY`, `TIPMN`, `GUARFE`, `RECFLAG`,
    `RECFLAGDES`, `POOLNUM`, `DLQPMNTCNT`, `IOEFLAG`, `IOEFLAGDES`, `MANCODE`,
    `BBCODE`, `BRNCHOFF`, `ACRLSTAT`, `PREPMNTIND`, `FHLBBPP`, `FSTORGCOS`,
    `FSTORIGFE`, `FSTUNAMOR`, `ARMIREFFDT`, `ARMORGI`, `ARMMARGI`, `ARMPIEFFDT`,
    `ARMCHGPRD`, `ARMPICHGPR`, `ARMIRMAXC`, `ARMIRMAXF`, `ARMIMAXIN`, `ARMIMAXDE`,
    `AIRMAXLIN`, `AIRMAXLDE`, `APIMAXPCT`, `APIMAXPCD`, `APIMAXLIF`, `APIPCTMIN`,
    `APIPCTMDE`, `AORGPIAM`, `ARMINDE`, `ARMIRRAT`, `AOIRCHGDT`, `AIRRNDTP`,
    `AIRRNDDESC`, `AIRRNDFAC`, `ARMPLANID`, `ARMPLANDES`, `ARMINDCO`, `ARMINDDESC`,
    `AILEADDAYS`, `USR15POS1`, `USR2POS1A`, `USR2POS2A`, `DFTIND`, `BANKNAME`,
    `LOT`, `BLOCK`, `SUBDIV`, `COUNTYCODE`, `COUNTYTA`, `HAZMONTHL`,
    `LASTANALDT`, `ESCMINBAL`, `LASTANALO`, `OVSHTCHGDT`, `MORTSSNO`, `COMORTSSNO`,
    `SSNCERTDT`, `SSNVERCODE`, `SSNVERDATE`, `SETUPDATE`, `SUSPBA`, `RESTESCBA`,
    `CRQUALCODE`, `INTONLYIND`, `PAYFULLDT`, `SERVSOLDDT`, `COMTGLNAME`, `COMTGFNAME`,
    `FLOZPOS1`, `MTGRDOB`, `COMTGRDOB`, `PROPUNITNO`, `LTVN`, `BILLADDR3`,
    `BILLADDR4`, `BILLCITY`, `BILLSTATE`, `BILLZIP`, `ORIGSCORE`, `BILLADDR2`,
    `USR1POS3A`, `CHGOFFBALN`, `ACCLATECAN`, `LATECFN`, `GRACEDAYS`, `LCCODE`,
    `PHONE`, `PHONE2`, `EMAILF`, `PROCSC`, `DAIND`, `CSBORCBC`,
    `CSBORCBST`, `FIRSTFF1N`, `ASSUMDATE`, `VACDATE`, `LNMODDATE`, `USR20POS1A`,
    `RECOVECABN`, `NONRECCABN`, `THIRDPRCBN`, `PENDPIAMTN`, `ADLCBN1`, `ADLCSTN1`,
    `ADLCBS`, `ADLCBC`, `ADLCBST`, `ADLCBZC`, `ADLCBPN`, `LASTFPAYDT`,
    `YTDINTAMTN`, `YTDPPAMTN`, `YTDTAXAMTN`, `YTDHAZAMTN`, `USR1PO4A`, `DAYDELIQU`,
    `ENTERNONAC`, `LEAVENONAC`, `APPRAIDATE`, `LNMOAPPDAT`, `LNMOAPPAM`, `CHAROFFDAT`,
    `DRROUTRNU`, `FIORCOSAM`, `FIORFEEAM`, `NextDueDate`, `OriginalLoanDate`, `MaturityDate`,
    `FirstDueDate`, `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `LOANNO`,
    idx AS `OLDLOANNO`,
    concat('BILLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLNAME`,
    concat('BANK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANK`,
    concat('AGGR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AGGR`,
    concat('NEXTDUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NEXTDUE`,
    concat('FIRSTPRINB_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTPRINB`,
    concat('ORGMTGAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGMTGAM`,
    concat('LOANDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOANDATE`,
    concat('MATDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `MATDATE`,
    concat('ANNUALIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ANNUALIN`,
    concat('LOANTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOANTERM`,
    concat('REMTERM_', lpad(CAST(idx AS STRING), 2, '0')) AS `REMTERM`,
    concat('PRODLINECD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PRODLINECD`,
    concat('ARMIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIND`,
    concat('ARMINDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDESC`,
    concat('ORGPROPVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGPROPVAL`,
    concat('PROPVAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPVAL`,
    concat('PROPERTYST_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPERTYST`,
    concat('PROPERTYCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPERTYCT`,
    concat('PROPSTATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPSTATE`,
    concat('PROPZIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROPZIP`,
    concat('SSNCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNCODE`,
    concat('PTFNMACODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTFNMACODE`,
    concat('PTFNMADESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PTFNMADESC`,
    concat('INVESTLOAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `INVESTLOAN`,
    concat('OCCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OCCCODE`,
    concat('OCCUDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OCCUDESC`,
    concat('LNPURPCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNPURPCODE`,
    concat('LNPURPDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNPURPDESC`,
    concat('HITYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITYPE`,
    concat('HITYPEDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `HITYPEDESC`,
    concat('LOTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOTYPE`,
    concat('LOTYPEDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOTYPEDESC`,
    concat('FIRSTDUE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTDUE`,
    concat('FIRSTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTP`,
    concat('FSTSERFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FSTSERFE`,
    concat('FORECLSCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `FORECLSCOD`,
    concat('FORECLSDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `FORECLSDES`,
    concat('ORGLT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORGLT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTPDTHRU`,
    concat('ESCROWBA_', lpad(CAST(idx AS STRING), 2, '0')) AS `ESCROWBA`,
    concat('ESCROWAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ESCROWAD`,
    concat('PLGCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLGCODE`,
    concat('PLGDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PLGDESC`,
    concat('PMNTPERD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PMNTPERD`,
    concat('BADCHKTBLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BADCHKTBLE`,
    concat('TIMESDLQ_', lpad(CAST(idx AS STRING), 2, '0')) AS `TIMESDLQ`,
    concat('TOTPMN_', lpad(CAST(idx AS STRING), 2, '0')) AS `TOTPMN`,
    concat('NOOFUNIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOOFUNIT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTFLAG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTFLAGDES`,
    concat('CAPLNFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAPLNFLAG`,
    concat('CAPLNFDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CAPLNFDESC`,
    concat('MTGRLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRLNAME`,
    concat('MTGRFNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRFNAME`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `MTGRHAZPAY`,
    concat('TIPMN_', lpad(CAST(idx AS STRING), 2, '0')) AS `TIPMN`,
    concat('GUARFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `GUARFE`,
    concat('RECFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECFLAG`,
    concat('RECFLAGDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECFLAGDES`,
    idx AS `POOLNUM`,
    idx AS `DLQPMNTCNT`,
    concat('IOEFLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `IOEFLAG`,
    concat('IOEFLAGDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `IOEFLAGDES`,
    concat('MANCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `MANCODE`,
    concat('BBCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BBCODE`,
    concat('BRNCHOFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BRNCHOFF`,
    concat('ACRLSTAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACRLSTAT`,
    concat('PREPMNTIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `PREPMNTIND`,
    concat('FHLBBPP_', lpad(CAST(idx AS STRING), 2, '0')) AS `FHLBBPP`,
    concat('FSTORGCOS_', lpad(CAST(idx AS STRING), 2, '0')) AS `FSTORGCOS`,
    concat('FSTORIGFE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FSTORIGFE`,
    concat('FSTUNAMOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `FSTUNAMOR`,
    concat('ARMIREFFDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIREFFDT`,
    concat('ARMORGI_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMORGI`,
    concat('ARMMARGI_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMMARGI`,
    concat('ARMPIEFFDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPIEFFDT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ARMCHGPRD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ARMPICHGPR`,
    concat('ARMIRMAXC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIRMAXC`,
    concat('ARMIRMAXF_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIRMAXF`,
    concat('ARMIMAXIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIMAXIN`,
    concat('ARMIMAXDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIMAXDE`,
    concat('AIRMAXLIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRMAXLIN`,
    concat('AIRMAXLDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRMAXLDE`,
    concat('APIMAXPCT_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXPCT`,
    concat('APIMAXPCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXPCD`,
    concat('APIMAXLIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIMAXLIF`,
    concat('APIPCTMIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIPCTMIN`,
    concat('APIPCTMDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `APIPCTMDE`,
    concat('AORGPIAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AORGPIAM`,
    concat('ARMINDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDE`,
    concat('ARMIRRAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMIRRAT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `AOIRCHGDT`,
    concat('AIRRNDTP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDTP`,
    concat('AIRRNDDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDDESC`,
    concat('AIRRNDFAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AIRRNDFAC`,
    concat('ARMPLANID_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPLANID`,
    concat('ARMPLANDES_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMPLANDES`,
    concat('ARMINDCO_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDCO`,
    concat('ARMINDDESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ARMINDDESC`,
    concat('AILEADDAYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `AILEADDAYS`,
    concat('USR15POS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR15POS1`,
    concat('USR2POS1A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR2POS1A`,
    concat('USR2POS2A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR2POS2A`,
    concat('DFTIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `DFTIND`,
    concat('BANKNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `BANKNAME`,
    concat('LOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LOT`,
    concat('BLOCK_', lpad(CAST(idx AS STRING), 2, '0')) AS `BLOCK`,
    concat('SUBDIV_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUBDIV`,
    concat('COUNTYCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `COUNTYCODE`,
    concat('COUNTYTA_', lpad(CAST(idx AS STRING), 2, '0')) AS `COUNTYTA`,
    concat('HAZMONTHL_', lpad(CAST(idx AS STRING), 2, '0')) AS `HAZMONTHL`,
    concat('LASTANALDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LASTANALDT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ESCMINBAL`,
    concat('LASTANALO_', lpad(CAST(idx AS STRING), 2, '0')) AS `LASTANALO`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `OVSHTCHGDT`,
    idx AS `MORTSSNO`,
    idx AS `COMORTSSNO`,
    concat('SSNCERTDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNCERTDT`,
    concat('SSNVERCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNVERCODE`,
    concat('SSNVERDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SSNVERDATE`,
    concat('SETUPDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SETUPDATE`,
    concat('SUSPBA_', lpad(CAST(idx AS STRING), 2, '0')) AS `SUSPBA`,
    concat('RESTESCBA_', lpad(CAST(idx AS STRING), 2, '0')) AS `RESTESCBA`,
    concat('CRQUALCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `CRQUALCODE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTONLYIND`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PAYFULLDT`,
    concat('SERVSOLDDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `SERVSOLDDT`,
    concat('COMTGLNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGLNAME`,
    concat('COMTGFNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGFNAME`,
    concat('FLOZPOS1_', lpad(CAST(idx AS STRING), 2, '0')) AS `FLOZPOS1`,
    concat('MTGRDOB_', lpad(CAST(idx AS STRING), 2, '0')) AS `MTGRDOB`,
    concat('COMTGRDOB_', lpad(CAST(idx AS STRING), 2, '0')) AS `COMTGRDOB`,
    idx AS `PROPUNITNO`,
    concat('LTVN_', lpad(CAST(idx AS STRING), 2, '0')) AS `LTVN`,
    concat('BILLADDR3_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR3`,
    concat('BILLADDR4_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR4`,
    concat('BILLCITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLCITY`,
    concat('BILLSTATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLSTATE`,
    concat('BILLZIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLZIP`,
    concat('ORIGSCORE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ORIGSCORE`,
    concat('BILLADDR2_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILLADDR2`,
    concat('USR1POS3A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR1POS3A`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHGOFFBALN`,
    concat('ACCLATECAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCLATECAN`,
    concat('LATECFN_', lpad(CAST(idx AS STRING), 2, '0')) AS `LATECFN`,
    concat('GRACEDAYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `GRACEDAYS`,
    concat('LCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LCCODE`,
    concat('PHONE_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHONE`,
    concat('PHONE2_', lpad(CAST(idx AS STRING), 2, '0')) AS `PHONE2`,
    concat('EMAILF_', lpad(CAST(idx AS STRING), 2, '0')) AS `EMAILF`,
    concat('PROCSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `PROCSC`,
    concat('DAIND_', lpad(CAST(idx AS STRING), 2, '0')) AS `DAIND`,
    concat('CSBORCBC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CSBORCBC`,
    concat('CSBORCBST_', lpad(CAST(idx AS STRING), 2, '0')) AS `CSBORCBST`,
    concat('FIRSTFF1N_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIRSTFF1N`,
    concat('ASSUMDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASSUMDATE`,
    concat('VACDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `VACDATE`,
    concat('LNMODDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNMODDATE`,
    concat('USR20POS1A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR20POS1A`,
    concat('RECOVECABN_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECOVECABN`,
    concat('NONRECCABN_', lpad(CAST(idx AS STRING), 2, '0')) AS `NONRECCABN`,
    concat('THIRDPRCBN_', lpad(CAST(idx AS STRING), 2, '0')) AS `THIRDPRCBN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PENDPIAMTN`,
    concat('ADLCBN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBN1`,
    concat('ADLCSTN1_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCSTN1`,
    concat('ADLCBS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBS`,
    concat('ADLCBC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBC`,
    concat('ADLCBST_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBST`,
    concat('ADLCBZC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBZC`,
    concat('ADLCBPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ADLCBPN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `LASTFPAYDT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDINTAMTN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDPPAMTN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDTAXAMTN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDHAZAMTN`,
    concat('USR1PO4A_', lpad(CAST(idx AS STRING), 2, '0')) AS `USR1PO4A`,
    concat('DAYDELIQU_', lpad(CAST(idx AS STRING), 2, '0')) AS `DAYDELIQU`,
    concat('ENTERNONAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `ENTERNONAC`,
    concat('LEAVENONAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `LEAVENONAC`,
    concat('APPRAIDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `APPRAIDATE`,
    concat('LNMOAPPDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNMOAPPDAT`,
    concat('LNMOAPPAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `LNMOAPPAM`,
    concat('CHAROFFDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CHAROFFDAT`,
    concat('DRROUTRNU_', lpad(CAST(idx AS STRING), 2, '0')) AS `DRROUTRNU`,
    concat('FIORCOSAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `FIORCOSAM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `FIORFEEAM`,
    concat('NEXTDUEDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NextDueDate`,
    concat('ORIGINALLOANDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OriginalLoanDate`,
    concat('MATURITYDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `MaturityDate`,
    concat('FIRSTDUEDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `FirstDueDate`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_dmilay' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_dmilay;
