-- Databricks SQL for source: jh_cfmast
-- Generated from sqlserver/brz-jh_cfmast.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_CFMAST"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_cfmast (
    `CFRECI` STRING,
    `CFRETN` STRING,
    `CFBNKN` STRING,
    `CFBRNN` STRING,
    `CFCIF__CS` STRING,
    `CFSNME` STRING,
    `CFSEQ__CS` STRING,
    `CFSNPH` STRING,
    `CFSNP2` STRING,
    `CFINQC` STRING,
    `CFOFFR` STRING,
    `CFEMPL` STRING,
    `CFINSC` STRING,
    `CFVIPC` STRING,
    `CFDEAD` STRING,
    `CFBADA` STRING,
    `CFHLDM` STRING,
    `CFPROA` STRING,
    `CFFORN` STRING,
    `CFSIC1` STRING,
    `CFSIC2` STRING,
    `CFSIC3` STRING,
    `CFSIC4` STRING,
    `CFSIC5` STRING,
    `CFSIC6` STRING,
    `CFSIC7` STRING,
    `CFSIC8` STRING,
    `CFNA1` STRING,
    `CFNA2` STRING,
    `CFNA3` STRING,
    `CFNA4` STRING,
    `CFCITY` STRING,
    `CFSTAT` STRING,
    `CFCRAS` STRING,
    `CFCNTY` STRING,
    `CFZIP` STRING,
    `CFZIPD` STRING,
    `CFNAME` STRING,
    `CFFNA` STRING,
    `CFFNAL` STRING,
    `CFMNA` STRING,
    `CFMNAL` STRING,
    `CFMNIN` STRING,
    `CFLNA` STRING,
    `CFLNAL` STRING,
    `CFSFX` STRING,
    `CFSFXL` STRING,
    `CFNAMC` STRING,
    `CFEXTTL` STRING,
    `CFORGD` STRING,
    `CFORG6` STRING,
    `CFDLM` STRING,
    `CFDLM6` STRING,
    `CFHPHO` STRING,
    `CFBPHO` STRING,
    `CFFSDT` STRING,
    `CFFSD6` STRING,
    `CFSSNO` INT,
    `CFSSCD` STRING,
    `CFSSFX` STRING,
    `CFBIRD` STRING,
    `CFBIR6` STRING,
    `CFSEX` STRING,
    `CFCLAS` STRING,
    `CFINDI` STRING,
    `CFINCL` STRING,
    `CFSMSA` STRING,
    `CFCRAL` STRING,
    `CFCENS` STRING,
    `CFBUST` STRING,
    `CFNAICS` STRING,
    `CFSCLA` STRING,
    `CFGRUP` STRING,
    `CFCCYC` STRING,
    `CFTINS` STRING,
    `CFTND6` STRING,
    `CFTNDT` STRING,
    `CFWHCD` STRING,
    `CFWHPR` STRING,
    `CFWHDT` STRING,
    `CFWHD6` STRING,
    `CFBNOT` STRING,
    `CFBND6` STRING,
    `CFBNDT` STRING,
    `CFAFLG` STRING,
    `CFADT6` STRING,
    `CFADAT` STRING,
    `CFDDE6` STRING,
    `CFDDEA` STRING,
    `CFUIC1` STRING,
    `CFUIC2` STRING,
    `CFUIC3` STRING,
    `CFUIC4` STRING,
    `CFUIC5` STRING,
    `CFUIC6` STRING,
    `CFUIC7` STRING,
    `CFUIC8` STRING,
    `CFPIC1` STRING,
    `CFPIC2` STRING,
    `CFPDT1` STRING,
    `CFPD61` STRING,
    `CFPDT2` STRING,
    `CFPD62` STRING,
    `CFPAM1` STRING,
    `CFPAM2` STRING,
    `CFGRP__CS` STRING,
    `CFCFSD` STRING,
    `CFCFS6` STRING,
    `CFLTDT` DECIMAL(38,10),
    `CFLTD6` DECIMAL(38,10),
    `CFWRTH` STRING,
    `CFWVCD` STRING,
    `CFWVDT` STRING,
    `CFWVD6` STRING,
    `CFTXRT` STRING,
    `CFTXR6` STRING,
    `CFTXET` STRING,
    `CFTXE6` STRING,
    `CFIRSA` STRING,
    `CFIRSC` STRING,
    `CFIRSS` STRING,
    `CFIRSZ` STRING,
    `CFIRSD` STRING,
    `CFIRSF` STRING,
    `CFCASS` STRING,
    `CFLEAS` STRING,
    `CFFAX1` STRING,
    `CFFAX2` STRING,
    `CFCEL1` STRING,
    `CFCEL2` STRING,
    `CFEML1` STRING,
    `CFEML2` STRING,
    `CFREGP` STRING,
    `CFRPD6` STRING,
    `CFRPD7` STRING,
    `CFNOCALL` STRING,
    `CFNCLEX6` STRING,
    `CFNCLEX7` STRING,
    `CFRSKRT` STRING,
    `CFRSKD6` STRING,
    `CFRSKD7` STRING,
    `CFRSKBY` STRING,
    `CFOCPCD` STRING,
    `CFAFLOPT` STRING,
    `CFAFLEXD6` STRING,
    `CFAFLEXD7` STRING,
    `CFAFLECD6` STRING,
    `CFAFLECD7` STRING,
    `CFAFLEXCD` STRING,
    `SALESCF` STRING,
    `CFBPHX` STRING,
    `CFLANG` STRING,
    `CFFORC` STRING,
    `CFIRSFC` STRING,
    `CFAEDT6` STRING,
    `CFAEDAT` STRING,
    `W8STAT` STRING,
    `W8TYPE` STRING,
    `W8LLDT6` STRING,
    `W8LLDAT` STRING,
    `W8STS` STRING,
    `CFDTO6` STRING,
    `CFDTO7` STRING,
    `CFPFA1` STRING,
    `CFPFA2` STRING,
    `CFPFCY` STRING,
    `CFPFST` STRING,
    `CFPFZC` STRING,
    `CFPFDP` STRING,
    `CFDLAC6` STRING,
    `CFDLAC7` STRING,
    `CFPFFD` STRING,
    `CFPFFC` STRING,
    `CFPFFR` STRING,
    `CFTINMATCH` STRING,
    `CFSSNO_FLAG` STRING,
    `OriginalCustomerDate` STRING,
    `DateOfBirth` STRING,
    `LastAlienCertificationDate` STRING,
    `AlienCertificationExpirationDate` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_cfmast IS
'The JH CFMAST landing table captures customer master profile attributes, including CIF identifiers, names, addresses, officer, demographic, tax, compliance, contact, and status fields for customer validation and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_cfmast;

INSERT INTO landing_jh.default.jh_cfmast (
    `CFRECI`, `CFRETN`, `CFBNKN`, `CFBRNN`, `CFCIF__CS`, `CFSNME`,
    `CFSEQ__CS`, `CFSNPH`, `CFSNP2`, `CFINQC`, `CFOFFR`, `CFEMPL`,
    `CFINSC`, `CFVIPC`, `CFDEAD`, `CFBADA`, `CFHLDM`, `CFPROA`,
    `CFFORN`, `CFSIC1`, `CFSIC2`, `CFSIC3`, `CFSIC4`, `CFSIC5`,
    `CFSIC6`, `CFSIC7`, `CFSIC8`, `CFNA1`, `CFNA2`, `CFNA3`,
    `CFNA4`, `CFCITY`, `CFSTAT`, `CFCRAS`, `CFCNTY`, `CFZIP`,
    `CFZIPD`, `CFNAME`, `CFFNA`, `CFFNAL`, `CFMNA`, `CFMNAL`,
    `CFMNIN`, `CFLNA`, `CFLNAL`, `CFSFX`, `CFSFXL`, `CFNAMC`,
    `CFEXTTL`, `CFORGD`, `CFORG6`, `CFDLM`, `CFDLM6`, `CFHPHO`,
    `CFBPHO`, `CFFSDT`, `CFFSD6`, `CFSSNO`, `CFSSCD`, `CFSSFX`,
    `CFBIRD`, `CFBIR6`, `CFSEX`, `CFCLAS`, `CFINDI`, `CFINCL`,
    `CFSMSA`, `CFCRAL`, `CFCENS`, `CFBUST`, `CFNAICS`, `CFSCLA`,
    `CFGRUP`, `CFCCYC`, `CFTINS`, `CFTND6`, `CFTNDT`, `CFWHCD`,
    `CFWHPR`, `CFWHDT`, `CFWHD6`, `CFBNOT`, `CFBND6`, `CFBNDT`,
    `CFAFLG`, `CFADT6`, `CFADAT`, `CFDDE6`, `CFDDEA`, `CFUIC1`,
    `CFUIC2`, `CFUIC3`, `CFUIC4`, `CFUIC5`, `CFUIC6`, `CFUIC7`,
    `CFUIC8`, `CFPIC1`, `CFPIC2`, `CFPDT1`, `CFPD61`, `CFPDT2`,
    `CFPD62`, `CFPAM1`, `CFPAM2`, `CFGRP__CS`, `CFCFSD`, `CFCFS6`,
    `CFLTDT`, `CFLTD6`, `CFWRTH`, `CFWVCD`, `CFWVDT`, `CFWVD6`,
    `CFTXRT`, `CFTXR6`, `CFTXET`, `CFTXE6`, `CFIRSA`, `CFIRSC`,
    `CFIRSS`, `CFIRSZ`, `CFIRSD`, `CFIRSF`, `CFCASS`, `CFLEAS`,
    `CFFAX1`, `CFFAX2`, `CFCEL1`, `CFCEL2`, `CFEML1`, `CFEML2`,
    `CFREGP`, `CFRPD6`, `CFRPD7`, `CFNOCALL`, `CFNCLEX6`, `CFNCLEX7`,
    `CFRSKRT`, `CFRSKD6`, `CFRSKD7`, `CFRSKBY`, `CFOCPCD`, `CFAFLOPT`,
    `CFAFLEXD6`, `CFAFLEXD7`, `CFAFLECD6`, `CFAFLECD7`, `CFAFLEXCD`, `SALESCF`,
    `CFBPHX`, `CFLANG`, `CFFORC`, `CFIRSFC`, `CFAEDT6`, `CFAEDAT`,
    `W8STAT`, `W8TYPE`, `W8LLDT6`, `W8LLDAT`, `W8STS`, `CFDTO6`,
    `CFDTO7`, `CFPFA1`, `CFPFA2`, `CFPFCY`, `CFPFST`, `CFPFZC`,
    `CFPFDP`, `CFDLAC6`, `CFDLAC7`, `CFPFFD`, `CFPFFC`, `CFPFFR`,
    `CFTINMATCH`, `CFSSNO_FLAG`, `OriginalCustomerDate`, `DateOfBirth`, `LastAlienCertificationDate`, `AlienCertificationExpirationDate`,
    `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('CFRECI_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRECI`,
    concat('CFRETN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRETN`,
    concat('CFBNKN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBNKN`,
    concat('CFBRNN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBRNN`,
    concat('CFCIF__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCIF__CS`,
    concat('CFSNME_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSNME`,
    concat('CFSEQ__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSEQ__CS`,
    concat('CFSNPH_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSNPH`,
    concat('CFSNP2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSNP2`,
    concat('CFINQC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFINQC`,
    concat('CFOFFR_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFOFFR`,
    concat('CFEMPL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFEMPL`,
    concat('CFINSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFINSC`,
    concat('CFVIPC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFVIPC`,
    concat('CFDEAD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDEAD`,
    concat('CFBADA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBADA`,
    concat('CFHLDM_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFHLDM`,
    concat('CFPROA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPROA`,
    concat('CFFORN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFORN`,
    concat('CFSIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC1`,
    concat('CFSIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC2`,
    concat('CFSIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC3`,
    concat('CFSIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC4`,
    concat('CFSIC5_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC5`,
    concat('CFSIC6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC6`,
    concat('CFSIC7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC7`,
    concat('CFSIC8_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSIC8`,
    concat('CFNA1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNA1`,
    concat('CFNA2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNA2`,
    concat('CFNA3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNA3`,
    concat('CFNA4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNA4`,
    concat('CFCITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCITY`,
    concat('CFSTAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSTAT`,
    concat('CFCRAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCRAS`,
    concat('CFCNTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCNTY`,
    concat('CFZIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFZIP`,
    concat('CFZIPD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFZIPD`,
    concat('CFNAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNAME`,
    concat('CFFNA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFNA`,
    concat('CFFNAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFNAL`,
    concat('CFMNA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFMNA`,
    concat('CFMNAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFMNAL`,
    concat('CFMNIN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFMNIN`,
    concat('CFLNA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFLNA`,
    concat('CFLNAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFLNAL`,
    concat('CFSFX_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSFX`,
    concat('CFSFXL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSFXL`,
    concat('CFNAMC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNAMC`,
    concat('CFEXTTL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFEXTTL`,
    concat('CFORGD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFORGD`,
    concat('CFORG6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFORG6`,
    concat('CFDLM_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDLM`,
    concat('CFDLM6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDLM6`,
    concat('CFHPHO_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFHPHO`,
    concat('CFBPHO_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBPHO`,
    concat('CFFSDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFSDT`,
    concat('CFFSD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFSD6`,
    idx AS `CFSSNO`,
    concat('CFSSCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSSCD`,
    concat('CFSSFX_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSSFX`,
    concat('CFBIRD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBIRD`,
    concat('CFBIR6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBIR6`,
    concat('CFSEX_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSEX`,
    concat('CFCLAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCLAS`,
    concat('CFINDI_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFINDI`,
    concat('CFINCL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFINCL`,
    concat('CFSMSA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSMSA`,
    concat('CFCRAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCRAL`,
    concat('CFCENS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCENS`,
    concat('CFBUST_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBUST`,
    concat('CFNAICS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNAICS`,
    concat('CFSCLA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSCLA`,
    concat('CFGRUP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFGRUP`,
    concat('CFCCYC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCCYC`,
    concat('CFTINS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTINS`,
    concat('CFTND6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTND6`,
    concat('CFTNDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTNDT`,
    concat('CFWHCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWHCD`,
    concat('CFWHPR_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWHPR`,
    concat('CFWHDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWHDT`,
    concat('CFWHD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWHD6`,
    concat('CFBNOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBNOT`,
    concat('CFBND6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBND6`,
    concat('CFBNDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBNDT`,
    concat('CFAFLG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLG`,
    concat('CFADT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFADT6`,
    concat('CFADAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFADAT`,
    concat('CFDDE6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDDE6`,
    concat('CFDDEA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDDEA`,
    concat('CFUIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC1`,
    concat('CFUIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC2`,
    concat('CFUIC3_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC3`,
    concat('CFUIC4_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC4`,
    concat('CFUIC5_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC5`,
    concat('CFUIC6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC6`,
    concat('CFUIC7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC7`,
    concat('CFUIC8_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFUIC8`,
    concat('CFPIC1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPIC1`,
    concat('CFPIC2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPIC2`,
    concat('CFPDT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPDT1`,
    concat('CFPD61_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPD61`,
    concat('CFPDT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPDT2`,
    concat('CFPD62_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPD62`,
    concat('CFPAM1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPAM1`,
    concat('CFPAM2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPAM2`,
    concat('CFGRP__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFGRP__CS`,
    concat('CFCFSD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCFSD`,
    concat('CFCFS6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCFS6`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CFLTDT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CFLTD6`,
    concat('CFWRTH_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWRTH`,
    concat('CFWVCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWVCD`,
    concat('CFWVDT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWVDT`,
    concat('CFWVD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFWVD6`,
    concat('CFTXRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTXRT`,
    concat('CFTXR6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTXR6`,
    concat('CFTXET_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTXET`,
    concat('CFTXE6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTXE6`,
    concat('CFIRSA_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSA`,
    concat('CFIRSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSC`,
    concat('CFIRSS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSS`,
    concat('CFIRSZ_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSZ`,
    concat('CFIRSD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSD`,
    concat('CFIRSF_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSF`,
    concat('CFCASS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCASS`,
    concat('CFLEAS_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFLEAS`,
    concat('CFFAX1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFAX1`,
    concat('CFFAX2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFAX2`,
    concat('CFCEL1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCEL1`,
    concat('CFCEL2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFCEL2`,
    concat('CFEML1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFEML1`,
    concat('CFEML2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFEML2`,
    concat('CFREGP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFREGP`,
    concat('CFRPD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRPD6`,
    concat('CFRPD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRPD7`,
    concat('CFNOCALL_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNOCALL`,
    concat('CFNCLEX6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNCLEX6`,
    concat('CFNCLEX7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFNCLEX7`,
    concat('CFRSKRT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRSKRT`,
    concat('CFRSKD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRSKD6`,
    concat('CFRSKD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRSKD7`,
    concat('CFRSKBY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFRSKBY`,
    concat('CFOCPCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFOCPCD`,
    concat('CFAFLOPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLOPT`,
    concat('CFAFLEXD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLEXD6`,
    concat('CFAFLEXD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLEXD7`,
    concat('CFAFLECD6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLECD6`,
    concat('CFAFLECD7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLECD7`,
    concat('CFAFLEXCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAFLEXCD`,
    concat('SALESCF_', lpad(CAST(idx AS STRING), 2, '0')) AS `SALESCF`,
    concat('CFBPHX_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFBPHX`,
    concat('CFLANG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFLANG`,
    concat('CFFORC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFFORC`,
    concat('CFIRSFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFIRSFC`,
    concat('CFAEDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAEDT6`,
    concat('CFAEDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFAEDAT`,
    concat('W8STAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `W8STAT`,
    concat('W8TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `W8TYPE`,
    concat('W8LLDT6_', lpad(CAST(idx AS STRING), 2, '0')) AS `W8LLDT6`,
    concat('W8LLDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `W8LLDAT`,
    concat('W8STS_', lpad(CAST(idx AS STRING), 2, '0')) AS `W8STS`,
    concat('CFDTO6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDTO6`,
    concat('CFDTO7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDTO7`,
    concat('CFPFA1_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFA1`,
    concat('CFPFA2_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFA2`,
    concat('CFPFCY_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFCY`,
    concat('CFPFST_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFST`,
    concat('CFPFZC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFZC`,
    concat('CFPFDP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFDP`,
    concat('CFDLAC6_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDLAC6`,
    concat('CFDLAC7_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFDLAC7`,
    concat('CFPFFD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFFD`,
    concat('CFPFFC_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFFC`,
    concat('CFPFFR_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFPFFR`,
    concat('CFTINMATCH_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFTINMATCH`,
    concat('CFSSNO_FLAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CFSSNO_FLAG`,
    concat('ORIGINALCUSTOMERDATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `OriginalCustomerDate`,
    concat('DATEOFBIRTH_', lpad(CAST(idx AS STRING), 2, '0')) AS `DateOfBirth`,
    concat('LASTALIENCERTIFICATIONDA_', lpad(CAST(idx AS STRING), 2, '0')) AS `LastAlienCertificationDate`,
    concat('ALIENCERTIFICATIONEXPIRA_', lpad(CAST(idx AS STRING), 2, '0')) AS `AlienCertificationExpirationDate`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_cfmast' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_cfmast;
