-- Databricks SQL for source: apex
-- Generated from sqlserver/brz-apex.sql

CREATE CATALOG IF NOT EXISTS apex;
USE CATALOG apex;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."APEX_daily_accounts"
CREATE TABLE IF NOT EXISTS apex.default.apex_daily_accounts (
    `account_id` BIGINT,
    `account_group_code` STRING,
    `correspondent_code` STRING,
    `ownership_type` STRING,
    `registration_type` STRING,
    `funding_type` STRING,
    `status` STRING,
    `fdid` BIGINT,
    `cat_account_holder_type` STRING,
    `title` STRING,
    `created_time` TIMESTAMP,
    `opened_time` TIMESTAMP,
    `is_pattern_day_trader` STRING,
    `accepts_issuer_direct_communication` STRING,
    `primary_registered_rep_id` BIGINT,
    `investment_profile_investment_profile_id` BIGINT,
    `investment_profile_account_goals_investment_objective` STRING,
    `investment_profile_account_goals_risk_tolerance` STRING,
    `investment_profile_account_goals_liquidity_needs` STRING,
    `investment_profile_account_goals_time_horizon` STRING,
    `investment_profile_customer_profile_investment_experience` STRING,
    `investment_profile_customer_profile_annual_income_range_usd` STRING,
    `investment_profile_customer_profile_liquid_net_worth_range_usd` DECIMAL(38,10),
    `investment_profile_customer_profile_total_net_worth_range_usd` DECIMAL(38,10),
    `investment_profile_customer_profile_federal_tax_bracket` STRING,
    `dividend_reinvestment_plan` STRING,
    `business_unit` STRING,
    `external_account_id` BIGINT,
    `margin_group_id` BIGINT,
    `tax_profile_cost_basis_lot_disposal_method` STRING,
    `tax_profile_wash_sale_eligible` STRING,
    `tax_profile_section_475_election` STRING,
    `finra_coa_code` STRING,
    `reserve_class` STRING,
    `account_number` BIGINT,
    `close_time` TIMESTAMP,
    `agreements` STRING,
    `enrollments` STRING,
    `active_restrictions` STRING,
    `interested_parties` DECIMAL(38,10),
    `registered_representatives` STRING,
    `parties` STRING,
    `entitlements` STRING,
    `_key` STRING,
    `trusted_contacts` STRING,
    `correspondents_record_correspondent_id` BIGINT,
    `correspondents_record_trading_mpid` BIGINT,
    `correspondents_record_correspondent_code` STRING,
    `correspondents_record_client_id` BIGINT,
    `correspondents_record_client_code` STRING,
    `correspondents_record_account_group_code` STRING,
    `correspondents_record_account_group_id` BIGINT,
    `correspondents_record_branch_office` STRING,
    `identifiers` STRING,
    `replacing_fdid` BIGINT,
    `fdid_end_reason` STRING,
    `last_modified_by` STRING,
    `last_modified_time` TIMESTAMP,
    `mutual_fund_external_facilitation_account` STRING,
    `snapshot_timestamp` TIMESTAMP,
    `source_file` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_daily_accounts IS 
'The table contains daily records of accounts along with their various attributes. It includes details such as account types, registration, and investment profiles, which can be useful for analyzing account activity and client demographics. Possible use cases include assessing account statuses, understanding ownership types, and analyzing investment profiles based on different financial goals and risk tolerances.';

TRUNCATE TABLE apex.default.apex_daily_accounts;

INSERT INTO apex.default.apex_daily_accounts (
    `account_id`, `account_group_code`, `correspondent_code`, `ownership_type`, `registration_type`, `funding_type`,
    `status`, `fdid`, `cat_account_holder_type`, `title`, `created_time`, `opened_time`,
    `is_pattern_day_trader`, `accepts_issuer_direct_communication`, `primary_registered_rep_id`, `investment_profile_investment_profile_id`, `investment_profile_account_goals_investment_objective`, `investment_profile_account_goals_risk_tolerance`,
    `investment_profile_account_goals_liquidity_needs`, `investment_profile_account_goals_time_horizon`, `investment_profile_customer_profile_investment_experience`, `investment_profile_customer_profile_annual_income_range_usd`, `investment_profile_customer_profile_liquid_net_worth_range_usd`, `investment_profile_customer_profile_total_net_worth_range_usd`,
    `investment_profile_customer_profile_federal_tax_bracket`, `dividend_reinvestment_plan`, `business_unit`, `external_account_id`, `margin_group_id`, `tax_profile_cost_basis_lot_disposal_method`,
    `tax_profile_wash_sale_eligible`, `tax_profile_section_475_election`, `finra_coa_code`, `reserve_class`, `account_number`, `close_time`,
    `agreements`, `enrollments`, `active_restrictions`, `interested_parties`, `registered_representatives`, `parties`,
    `entitlements`, `_key`, `trusted_contacts`, `correspondents_record_correspondent_id`, `correspondents_record_trading_mpid`, `correspondents_record_correspondent_code`,
    `correspondents_record_client_id`, `correspondents_record_client_code`, `correspondents_record_account_group_code`, `correspondents_record_account_group_id`, `correspondents_record_branch_office`, `identifiers`,
    `replacing_fdid`, `fdid_end_reason`, `last_modified_by`, `last_modified_time`, `mutual_fund_external_facilitation_account`, `snapshot_timestamp`,
    `source_file`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `account_id`,
    concat('ACCOUNT_GROUP_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_group_code`,
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondent_code`,
    concat('OWNERSHIP_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ownership_type`,
    concat('REGISTRATION_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `registration_type`,
    concat('FUNDING_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `funding_type`,
    concat('STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `status`,
    idx AS `fdid`,
    concat('CAT_ACCOUNT_HOLDER_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `cat_account_holder_type`,
    concat('TITLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `title`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `created_time`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `opened_time`,
    concat('IS_PATTERN_DAY_TRADER_', lpad(CAST(idx AS STRING), 2, '0')) AS `is_pattern_day_trader`,
    concat('ACCEPTS_ISSUER_DIRECT_CO_', lpad(CAST(idx AS STRING), 2, '0')) AS `accepts_issuer_direct_communication`,
    idx AS `primary_registered_rep_id`,
    idx AS `investment_profile_investment_profile_id`,
    concat('INVESTMENT_PROFILE_ACCOU_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_account_goals_investment_objective`,
    concat('INVESTMENT_PROFILE_ACCOU_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_account_goals_risk_tolerance`,
    concat('INVESTMENT_PROFILE_ACCOU_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_account_goals_liquidity_needs`,
    concat('INVESTMENT_PROFILE_ACCOU_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_account_goals_time_horizon`,
    concat('INVESTMENT_PROFILE_CUSTO_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_customer_profile_investment_experience`,
    concat('INVESTMENT_PROFILE_CUSTO_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_customer_profile_annual_income_range_usd`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `investment_profile_customer_profile_liquid_net_worth_range_usd`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `investment_profile_customer_profile_total_net_worth_range_usd`,
    concat('INVESTMENT_PROFILE_CUSTO_', lpad(CAST(idx AS STRING), 2, '0')) AS `investment_profile_customer_profile_federal_tax_bracket`,
    concat('DIVIDEND_REINVESTMENT_PL_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_reinvestment_plan`,
    concat('BUSINESS_UNIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `business_unit`,
    idx AS `external_account_id`,
    idx AS `margin_group_id`,
    concat('TAX_PROFILE_COST_BASIS_L_', lpad(CAST(idx AS STRING), 2, '0')) AS `tax_profile_cost_basis_lot_disposal_method`,
    concat('TAX_PROFILE_WASH_SALE_EL_', lpad(CAST(idx AS STRING), 2, '0')) AS `tax_profile_wash_sale_eligible`,
    concat('TAX_PROFILE_SECTION_475__', lpad(CAST(idx AS STRING), 2, '0')) AS `tax_profile_section_475_election`,
    concat('FINRA_COA_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `finra_coa_code`,
    concat('RESERVE_CLASS_', lpad(CAST(idx AS STRING), 2, '0')) AS `reserve_class`,
    idx AS `account_number`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `close_time`,
    concat('AGREEMENTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `agreements`,
    concat('ENROLLMENTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `enrollments`,
    concat('ACTIVE_RESTRICTIONS_', lpad(CAST(idx AS STRING), 2, '0')) AS `active_restrictions`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interested_parties`,
    concat('REGISTERED_REPRESENTATIV_', lpad(CAST(idx AS STRING), 2, '0')) AS `registered_representatives`,
    concat('PARTIES_', lpad(CAST(idx AS STRING), 2, '0')) AS `parties`,
    concat('ENTITLEMENTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `entitlements`,
    concat('_KEY_', lpad(CAST(idx AS STRING), 2, '0')) AS `_key`,
    concat('TRUSTED_CONTACTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `trusted_contacts`,
    idx AS `correspondents_record_correspondent_id`,
    idx AS `correspondents_record_trading_mpid`,
    concat('CORRESPONDENTS_RECORD_CO_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondents_record_correspondent_code`,
    idx AS `correspondents_record_client_id`,
    concat('CORRESPONDENTS_RECORD_CL_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondents_record_client_code`,
    concat('CORRESPONDENTS_RECORD_AC_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondents_record_account_group_code`,
    idx AS `correspondents_record_account_group_id`,
    concat('CORRESPONDENTS_RECORD_BR_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondents_record_branch_office`,
    concat('IDENTIFIERS_', lpad(CAST(idx AS STRING), 2, '0')) AS `identifiers`,
    idx AS `replacing_fdid`,
    concat('FDID_END_REASON_', lpad(CAST(idx AS STRING), 2, '0')) AS `fdid_end_reason`,
    concat('LAST_MODIFIED_BY_', lpad(CAST(idx AS STRING), 2, '0')) AS `last_modified_by`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `last_modified_time`,
    concat('MUTUAL_FUND_EXTERNAL_FAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `mutual_fund_external_facilitation_account`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `snapshot_timestamp`,
    concat('SOURCE_FILE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_file`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."APEX_daily_activities"
CREATE TABLE IF NOT EXISTS apex.default.apex_daily_activities (
    `account_id` BIGINT,
    `activity_id` BIGINT,
    `type` STRING,
    `sub_type` STRING,
    `symbol` STRING,
    `asset_type` STRING,
    `region_code` STRING,
    `asset_id` BIGINT,
    `side` STRING,
    `quantity` DECIMAL(38,10),
    `currency_code` DECIMAL(38,10),
    `currency_asset_id` DECIMAL(38,10),
    `price` DECIMAL(38,10),
    `gross_amount` DECIMAL(38,10),
    `net_amount` DECIMAL(38,10),
    `activity_date` DATE,
    `activity_time` TIMESTAMP,
    `process_date` DATE,
    `settle_date` DATE,
    `state` STRING,
    `activity_description` STRING,
    `asset_description` STRING,
    `asset_version` STRING,
    `trade_symbol_description` STRING,
    `trade_additional_instructions` STRING,
    `trade_special_instructions` STRING,
    `trade_client_order_id` BIGINT,
    `trade_exchange` STRING,
    `trade_broker_capacity` STRING,
    `trade_route` STRING,
    `trade_algo` STRING,
    `trade_broker` STRING,
    `trade_execution_id` BIGINT,
    `trade_markup` DECIMAL(38,10),
    `trade_markdown` DECIMAL(38,10),
    `trade_execution_only` STRING,
    `trade_when_issued` STRING,
    `trade_when_distributed` STRING,
    `trade_is_writeoff` STRING,
    `trade_client_memos` STRING,
    `trade_order_id` BIGINT,
    `trade_alternate_order_id` BIGINT,
    `trade_external_id` BIGINT,
    `trade_source_account_id` BIGINT,
    `trade_booking_api_trade_id` BIGINT,
    `trade_booking_api_trade_allocation_id` BIGINT,
    `trade_gateway_client_order_id` BIGINT,
    `trade_internal_error` STRING,
    `trade_prevailing_market_price` DECIMAL(38,10),
    `trade_price_adjustment_type` DECIMAL(38,10),
    `trade_price_adjustment_amount` DECIMAL(38,10),
    `trade_price_adjustment_percent` DECIMAL(38,10),
    `trade_yield_records` STRING,
    `reverse_stock_split_symbol_description` STRING,
    `reverse_stock_split_factor_numerator` STRING,
    `reverse_stock_split_factor_denominator` STRING,
    `reverse_stock_split_quantity` DECIMAL(38,10),
    `reverse_stock_split_new_cusip` STRING,
    `reverse_stock_split_cash_rate` DECIMAL(38,10),
    `reverse_stock_split_old_cusip` STRING,
    `reverse_stock_split_action` STRING,
    `reverse_stock_split_effective_date` DATE,
    `reverse_stock_split_corporate_action_id` DECIMAL(38,10),
    `reverse_stock_split_target_symbol_description` STRING,
    `reverse_stock_split_target_cusip` STRING,
    `reverse_stock_split_target_asset_id` BIGINT,
    `reverse_stock_split_disbursed_symbol_description` STRING,
    `reverse_stock_split_disbursed_cusip` STRING,
    `reverse_stock_split_disbursed_asset_id` BIGINT,
    `cash_dividend_symbol_description` STRING,
    `cash_dividend_cash_rate` DECIMAL(38,10),
    `cash_dividend_settled` STRING,
    `cash_dividend_record_date` DATE,
    `cash_dividend_payment_date` DATE,
    `cash_dividend_tefra_withholding` STRING,
    `cash_dividend_foreign_withholding` STRING,
    `cash_dividend_nra_withholding` STRING,
    `cash_dividend_qualified` STRING,
    `cash_dividend_long_term_gain` STRING,
    `cash_dividend_free` STRING,
    `cash_dividend_fpsl` STRING,
    `cash_dividend_is_substitute_payment` DECIMAL(38,10),
    `cash_dividend_subtype` STRING,
    `cash_dividend_quantity` DECIMAL(38,10),
    `cash_dividend_corporate_action_id` DECIMAL(38,10),
    `cash_dividend_target_symbol_description` STRING,
    `cash_dividend_target_cusip` STRING,
    `cash_dividend_target_asset_id` BIGINT,
    `cash_dividend_disbursed_symbol_description` STRING,
    `cash_dividend_disbursed_cusip` STRING,
    `cash_dividend_disbursed_asset_id` BIGINT,
    `cash_dividend_reinvested` STRING,
    `stock_dividend_rate` DECIMAL(38,10),
    `stock_dividend_quantity` DECIMAL(38,10),
    `stock_dividend_record_date` DATE,
    `stock_dividend_pay_date` DATE,
    `stock_dividend_corporate_action_id` DECIMAL(38,10),
    `stock_dividend_target_symbol_description` STRING,
    `stock_dividend_target_cusip` STRING,
    `stock_dividend_target_asset_id` BIGINT,
    `stock_dividend_disbursed_symbol_description` STRING,
    `stock_dividend_disbursed_cusip` STRING,
    `stock_dividend_disbursed_asset_id` BIGINT,
    `withdrawal_deposit_transfer_originating_institution` STRING,
    `withdrawal_deposit_transfer_destination_institution` STRING,
    `withdrawal_deposit_transfer_additional_instructions` STRING,
    `stock_split_factor_numerator` STRING,
    `stock_split_factor_denominator` STRING,
    `stock_split_quantity` DECIMAL(38,10),
    `stock_split_record_date` DATE,
    `stock_split_pay_date` DATE,
    `stock_split_corporate_action_id` DECIMAL(38,10),
    `stock_split_target_symbol_description` STRING,
    `stock_split_target_cusip` STRING,
    `stock_split_target_asset_id` BIGINT,
    `stock_split_disbursed_symbol_description` STRING,
    `stock_split_disbursed_cusip` STRING,
    `stock_split_disbursed_asset_id` BIGINT,
    `name_change_old_symbol_description` STRING,
    `name_change_quantity` DECIMAL(38,10),
    `name_change_old_cusip` STRING,
    `name_change_new_cusip` STRING,
    `name_change_action` STRING,
    `name_change_effective_date` DATE,
    `name_change_corporate_action_id` DECIMAL(38,10),
    `name_change_target_symbol_description` STRING,
    `name_change_target_cusip` STRING,
    `name_change_target_asset_id` BIGINT,
    `name_change_disbursed_symbol_description` STRING,
    `name_change_disbursed_cusip` STRING,
    `name_change_disbursed_asset_id` BIGINT,
    `capital_gains_quantity` DECIMAL(38,10),
    `capital_gains_record_date` DATE,
    `capital_gains_payment_date` DATE,
    `capital_gains_long_term_gain` STRING,
    `capital_gains_corporate_action_id` DECIMAL(38,10),
    `capital_gains_target_symbol_description` STRING,
    `capital_gains_target_cusip` STRING,
    `capital_gains_target_asset_id` BIGINT,
    `capital_gains_disbursed_symbol_description` STRING,
    `capital_gains_disbursed_cusip` STRING,
    `capital_gains_disbursed_asset_id` BIGINT,
    `capital_gains_reinvested` STRING,
    `spinoff_old_symbol_description` STRING,
    `spinoff_new_symbol_description` STRING,
    `spinoff_quantity` DECIMAL(38,10),
    `spinoff_record_date` DATE,
    `spinoff_pay_date` DATE,
    `spinoff_corporate_action_id` DECIMAL(38,10),
    `spinoff_target_symbol_description` STRING,
    `spinoff_target_cusip` STRING,
    `spinoff_target_asset_id` BIGINT,
    `spinoff_disbursed_symbol_description` STRING,
    `spinoff_disbursed_cusip` STRING,
    `spinoff_disbursed_asset_id` BIGINT,
    `interest_payment_symbol_description` DECIMAL(38,10),
    `interest_payment_cash_rate` DECIMAL(38,10),
    `interest_payment_settled` DECIMAL(38,10),
    `interest_payment_record_date` DATE,
    `interest_payment_payment_date` DATE,
    `interest_payment_corporate_action_id` DECIMAL(38,10),
    `interest_payment_target_symbol_description` DECIMAL(38,10),
    `interest_payment_target_cusip` DECIMAL(38,10),
    `interest_payment_target_asset_id` DECIMAL(38,10),
    `interest_payment_disbursed_symbol_description` DECIMAL(38,10),
    `interest_payment_disbursed_cusip` DECIMAL(38,10),
    `interest_payment_disbursed_asset_id` DECIMAL(38,10),
    `liquidation_symbol_description` STRING,
    `liquidation_cash_rate` DECIMAL(38,10),
    `liquidation_quantity` DECIMAL(38,10),
    `liquidation_settled` STRING,
    `liquidation_action` STRING,
    `liquidation_subtype` STRING,
    `liquidation_record_date` DATE,
    `liquidation_payment_date` DATE,
    `liquidation_effective_date` DATE,
    `liquidation_corporate_action_id` DECIMAL(38,10),
    `liquidation_target_symbol_description` STRING,
    `liquidation_target_cusip` STRING,
    `liquidation_target_asset_id` BIGINT,
    `liquidation_disbursed_symbol_description` STRING,
    `liquidation_disbursed_cusip` STRING,
    `liquidation_disbursed_asset_id` BIGINT,
    `dividend_symbol_description` STRING,
    `dividend_cash_rate` DECIMAL(38,10),
    `dividend_settled` STRING,
    `dividend_record_date` DATE,
    `dividend_subtype` STRING,
    `dividend_corporate_action_id` DECIMAL(38,10),
    `dividend_target_symbol_description` STRING,
    `dividend_target_cusip` STRING,
    `dividend_target_asset_id` BIGINT,
    `dividend_disbursed_symbol_description` STRING,
    `dividend_disbursed_cusip` STRING,
    `dividend_disbursed_asset_id` BIGINT,
    `sale_of_rights_symbol_description` STRING,
    `sale_of_rights_cash_rate` DECIMAL(38,10),
    `sale_of_rights_settled` STRING,
    `sale_of_rights_record_date` DATE,
    `sale_of_rights_payment_date` DATE,
    `sale_of_rights_corporate_action_id` DECIMAL(38,10),
    `sale_of_rights_target_symbol_description` STRING,
    `sale_of_rights_target_cusip` STRING,
    `sale_of_rights_target_asset_id` BIGINT,
    `sale_of_rights_disbursed_symbol_description` STRING,
    `sale_of_rights_disbursed_cusip` STRING,
    `sale_of_rights_disbursed_asset_id` BIGINT,
    `redemption_full_symbol_description` STRING,
    `redemption_full_cash_rate` DECIMAL(38,10),
    `redemption_full_quantity` DECIMAL(38,10),
    `redemption_full_action` STRING,
    `redemption_full_subtype` STRING,
    `redemption_full_payment_date` DATE,
    `redemption_full_corporate_action_id` DECIMAL(38,10),
    `redemption_full_target_symbol_description` STRING,
    `redemption_full_target_cusip` STRING,
    `redemption_full_target_asset_id` BIGINT,
    `redemption_full_disbursed_symbol_description` STRING,
    `redemption_full_disbursed_cusip` STRING,
    `redemption_full_disbursed_asset_id` BIGINT,
    `rights_distribution_new_symbol_description` STRING,
    `rights_distribution_settled` STRING,
    `rights_distribution_record_date` DATE,
    `rights_distribution_payment_date` DATE,
    `rights_distribution_corporate_action_id` DECIMAL(38,10),
    `rights_distribution_target_symbol_description` STRING,
    `rights_distribution_target_cusip` STRING,
    `rights_distribution_target_asset_id` BIGINT,
    `rights_distribution_disbursed_symbol_description` STRING,
    `rights_distribution_disbursed_cusip` STRING,
    `rights_distribution_disbursed_asset_id` BIGINT,
    `deposit_contribution_type` STRING,
    `deposit_contribution_year` STRING,
    `deposit_conversion` STRING,
    `deposit_futures_settlement` STRING,
    `deposit_micro` STRING,
    `deposit_retirement_type` STRING,
    `deposit_type` STRING,
    `deposit_originating_institution` STRING,
    `deposit_destination_institution` STRING,
    `deposit_additional_instructions` STRING,
    `deposit_fed_reference_number` BIGINT,
    `deposit_originating_account_number` BIGINT,
    `withdrawal_conversion` STRING,
    `withdrawal_distribution_type` STRING,
    `withdrawal_distribution_year` STRING,
    `withdrawal_closing_account` STRING,
    `withdrawal_futures_settlement` STRING,
    `withdrawal_micro` STRING,
    `withdrawal_periodic` STRING,
    `withdrawal_retirement_type` STRING,
    `withdrawal_taxable` STRING,
    `withdrawal_type` STRING,
    `withdrawal_advance` STRING,
    `withdrawal_originating_institution` STRING,
    `withdrawal_destination_institution` STRING,
    `withdrawal_additional_instructions` STRING,
    `withdrawal_fed_reference_number` BIGINT,
    `withdrawal_destination_account_number` BIGINT,
    `worthless_symbol_description` STRING,
    `worthless_effective_date` DATE,
    `worthless_payment_date` DATE,
    `worthless_corporate_action_id` DECIMAL(38,10),
    `worthless_target_symbol_description` STRING,
    `worthless_target_cusip` STRING,
    `worthless_target_asset_id` BIGINT,
    `worthless_disbursed_symbol_description` STRING,
    `worthless_disbursed_cusip` STRING,
    `worthless_disbursed_asset_id` BIGINT,
    `transfer_first_party` STRING,
    `transfer_originating_institution` STRING,
    `transfer_destination_institution` STRING,
    `transfer_additional_instructions` STRING,
    `transfer_client_brokerage` STRING,
    `transfer_transfer_type` STRING,
    `rounding_adjustment_rounding_reason` STRING,
    `fees` DECIMAL(38,10),
    `withholdings` STRING,
    `commissions` STRING,
    `accrued_interests` DECIMAL(38,10),
    `merger_symbol_description` STRING,
    `merger_quantity` DECIMAL(38,10),
    `merger_old_cusip` STRING,
    `merger_new_cusip` STRING,
    `merger_cash_rate` DECIMAL(38,10),
    `merger_stock_rate` DECIMAL(38,10),
    `merger_type` STRING,
    `merger_action` STRING,
    `merger_effective_date` DATE,
    `merger_corporate_action_id` DECIMAL(38,10),
    `merger_target_symbol_description` STRING,
    `merger_target_cusip` STRING,
    `merger_target_asset_id` BIGINT,
    `merger_disbursed_symbol_description` STRING,
    `merger_disbursed_cusip` STRING,
    `merger_disbursed_asset_id` BIGINT,
    `credit_credit_type` STRING,
    `credit_taxable` STRING,
    `credit_additional_instructions` STRING,
    `fpsl_action` STRING,
    `account_transfer_action` STRING,
    `account_transfer_acats_control_number` BIGINT,
    `account_transfer_institution` STRING,
    `account_transfer_additional_instructions` STRING,
    `account_transfer_acats_asset_sequence_number` BIGINT,
    `account_transfer_contra_party_id` BIGINT,
    `account_transfer_contra_party_account_number` BIGINT,
    `account_transfer_method` STRING,
    `tender_offer_symbol_description` STRING,
    `tender_offer_target_cusip` STRING,
    `tender_offer_cash_rate` DECIMAL(38,10),
    `tender_offer_corporate_action_id` DECIMAL(38,10),
    `tender_offer_target_symbol_description` STRING,
    `tender_offer_corporate_action_general_information_target_cusip` DECIMAL(38,10),
    `tender_offer_target_asset_id` BIGINT,
    `tender_offer_disbursed_symbol_description` STRING,
    `tender_offer_disbursed_cusip` STRING,
    `tender_offer_disbursed_asset_id` BIGINT,
    `unit_split_symbol_description` STRING,
    `unit_split_stock_rate` DECIMAL(38,10),
    `unit_split_corporate_action_id` DECIMAL(38,10),
    `unit_split_target_symbol_description` STRING,
    `unit_split_target_cusip` STRING,
    `unit_split_target_asset_id` BIGINT,
    `unit_split_disbursed_symbol_description` STRING,
    `unit_split_disbursed_cusip` STRING,
    `unit_split_disbursed_asset_id` BIGINT,
    `exchange_symbol_description` STRING,
    `exchange_old_cusip` STRING,
    `exchange_new_cusip` STRING,
    `exchange_cash_rate` DECIMAL(38,10),
    `exchange_stock_rate` DECIMAL(38,10),
    `exchange_type` STRING,
    `exchange_corporate_action_id` DECIMAL(38,10),
    `exchange_target_symbol_description` STRING,
    `exchange_target_cusip` STRING,
    `exchange_target_asset_id` BIGINT,
    `exchange_disbursed_symbol_description` STRING,
    `exchange_disbursed_cusip` STRING,
    `exchange_disbursed_asset_id` BIGINT,
    `conversion_symbol_description` STRING,
    `conversion_old_cusip` STRING,
    `conversion_new_cusip` STRING,
    `conversion_cash_rate` DECIMAL(38,10),
    `conversion_stock_rate` DECIMAL(38,10),
    `conversion_type` STRING,
    `conversion_corporate_action_id` DECIMAL(38,10),
    `conversion_target_symbol_description` STRING,
    `conversion_target_cusip` STRING,
    `conversion_target_asset_id` BIGINT,
    `conversion_disbursed_symbol_description` STRING,
    `conversion_disbursed_cusip` STRING,
    `conversion_disbursed_asset_id` BIGINT,
    `account_memo` STRING,
    `warrant_exercise_symbol_description` STRING,
    `warrant_exercise_corporate_action_id` DECIMAL(38,10),
    `warrant_exercise_target_symbol_description` STRING,
    `warrant_exercise_target_cusip` STRING,
    `warrant_exercise_target_asset_id` BIGINT,
    `warrant_exercise_disbursed_symbol_description` STRING,
    `warrant_exercise_disbursed_cusip` STRING,
    `warrant_exercise_disbursed_asset_id` BIGINT,
    `rights_subscription_symbol_description` STRING,
    `rights_subscription_corporate_action_id` DECIMAL(38,10),
    `rights_subscription_target_symbol_description` STRING,
    `rights_subscription_target_cusip` STRING,
    `rights_subscription_target_asset_id` BIGINT,
    `rights_subscription_disbursed_symbol_description` STRING,
    `rights_subscription_disbursed_cusip` STRING,
    `rights_subscription_disbursed_asset_id` BIGINT,
    `maturity_cash_rate` DECIMAL(38,10),
    `maturity_quantity` DECIMAL(38,10),
    `maturity_payment_date` DATE,
    `maturity_corporate_action_id` DECIMAL(38,10),
    `maturity_target_symbol_description` STRING,
    `maturity_target_cusip` STRING,
    `maturity_target_asset_id` BIGINT,
    `maturity_disbursed_symbol_description` STRING,
    `maturity_disbursed_cusip` STRING,
    `maturity_disbursed_asset_id` BIGINT,
    `drip_action` STRING,
    `fee_additional_instructions` DECIMAL(38,10),
    `sweep_action` STRING,
    `sweep_type` STRING,
    `sweep_eod_redemption` STRING,
    `subtype_category` STRING,
    `source_application` STRING,
    `source_application_id` BIGINT,
    `generation` STRING,
    `client_id` BIGINT,
    `suppress_downstream` STRING,
    `rounded_offset` STRING,
    `suppress_documents` STRING,
    `creation_time` TIMESTAMP,
    `initiating_user_id` BIGINT,
    `previous_activity_id` BIGINT,
    `previous_process_date` DATE,
    `_key` STRING,
    `_ingested_at` STRING,
    `kafka_metadata_topic` STRING,
    `kafka_metadata_partition` STRING,
    `kafka_metadata_offset` STRING,
    `proto_metadata_type_name` STRING,
    `proto_metadata_schema_id` BIGINT,
    `snapshot_timestamp` TIMESTAMP,
    `correspondent_id` BIGINT,
    `source_file` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_daily_activities IS 
'The table captures daily activities related to accounts and assets. It includes data on various activity types such as trades, dividends, and stock splits. This information can be useful for tracking account transactions, analyzing asset performance, and understanding corporate actions. Possible use cases include generating reports on trading activities, assessing dividend distributions, and handling corporate actions like stock splits.';

TRUNCATE TABLE apex.default.apex_daily_activities;

INSERT INTO apex.default.apex_daily_activities (
    `account_id`, `activity_id`, `type`, `sub_type`, `symbol`, `asset_type`,
    `region_code`, `asset_id`, `side`, `quantity`, `currency_code`, `currency_asset_id`,
    `price`, `gross_amount`, `net_amount`, `activity_date`, `activity_time`, `process_date`,
    `settle_date`, `state`, `activity_description`, `asset_description`, `asset_version`, `trade_symbol_description`,
    `trade_additional_instructions`, `trade_special_instructions`, `trade_client_order_id`, `trade_exchange`, `trade_broker_capacity`, `trade_route`,
    `trade_algo`, `trade_broker`, `trade_execution_id`, `trade_markup`, `trade_markdown`, `trade_execution_only`,
    `trade_when_issued`, `trade_when_distributed`, `trade_is_writeoff`, `trade_client_memos`, `trade_order_id`, `trade_alternate_order_id`,
    `trade_external_id`, `trade_source_account_id`, `trade_booking_api_trade_id`, `trade_booking_api_trade_allocation_id`, `trade_gateway_client_order_id`, `trade_internal_error`,
    `trade_prevailing_market_price`, `trade_price_adjustment_type`, `trade_price_adjustment_amount`, `trade_price_adjustment_percent`, `trade_yield_records`, `reverse_stock_split_symbol_description`,
    `reverse_stock_split_factor_numerator`, `reverse_stock_split_factor_denominator`, `reverse_stock_split_quantity`, `reverse_stock_split_new_cusip`, `reverse_stock_split_cash_rate`, `reverse_stock_split_old_cusip`,
    `reverse_stock_split_action`, `reverse_stock_split_effective_date`, `reverse_stock_split_corporate_action_id`, `reverse_stock_split_target_symbol_description`, `reverse_stock_split_target_cusip`, `reverse_stock_split_target_asset_id`,
    `reverse_stock_split_disbursed_symbol_description`, `reverse_stock_split_disbursed_cusip`, `reverse_stock_split_disbursed_asset_id`, `cash_dividend_symbol_description`, `cash_dividend_cash_rate`, `cash_dividend_settled`,
    `cash_dividend_record_date`, `cash_dividend_payment_date`, `cash_dividend_tefra_withholding`, `cash_dividend_foreign_withholding`, `cash_dividend_nra_withholding`, `cash_dividend_qualified`,
    `cash_dividend_long_term_gain`, `cash_dividend_free`, `cash_dividend_fpsl`, `cash_dividend_is_substitute_payment`, `cash_dividend_subtype`, `cash_dividend_quantity`,
    `cash_dividend_corporate_action_id`, `cash_dividend_target_symbol_description`, `cash_dividend_target_cusip`, `cash_dividend_target_asset_id`, `cash_dividend_disbursed_symbol_description`, `cash_dividend_disbursed_cusip`,
    `cash_dividend_disbursed_asset_id`, `cash_dividend_reinvested`, `stock_dividend_rate`, `stock_dividend_quantity`, `stock_dividend_record_date`, `stock_dividend_pay_date`,
    `stock_dividend_corporate_action_id`, `stock_dividend_target_symbol_description`, `stock_dividend_target_cusip`, `stock_dividend_target_asset_id`, `stock_dividend_disbursed_symbol_description`, `stock_dividend_disbursed_cusip`,
    `stock_dividend_disbursed_asset_id`, `withdrawal_deposit_transfer_originating_institution`, `withdrawal_deposit_transfer_destination_institution`, `withdrawal_deposit_transfer_additional_instructions`, `stock_split_factor_numerator`, `stock_split_factor_denominator`,
    `stock_split_quantity`, `stock_split_record_date`, `stock_split_pay_date`, `stock_split_corporate_action_id`, `stock_split_target_symbol_description`, `stock_split_target_cusip`,
    `stock_split_target_asset_id`, `stock_split_disbursed_symbol_description`, `stock_split_disbursed_cusip`, `stock_split_disbursed_asset_id`, `name_change_old_symbol_description`, `name_change_quantity`,
    `name_change_old_cusip`, `name_change_new_cusip`, `name_change_action`, `name_change_effective_date`, `name_change_corporate_action_id`, `name_change_target_symbol_description`,
    `name_change_target_cusip`, `name_change_target_asset_id`, `name_change_disbursed_symbol_description`, `name_change_disbursed_cusip`, `name_change_disbursed_asset_id`, `capital_gains_quantity`,
    `capital_gains_record_date`, `capital_gains_payment_date`, `capital_gains_long_term_gain`, `capital_gains_corporate_action_id`, `capital_gains_target_symbol_description`, `capital_gains_target_cusip`,
    `capital_gains_target_asset_id`, `capital_gains_disbursed_symbol_description`, `capital_gains_disbursed_cusip`, `capital_gains_disbursed_asset_id`, `capital_gains_reinvested`, `spinoff_old_symbol_description`,
    `spinoff_new_symbol_description`, `spinoff_quantity`, `spinoff_record_date`, `spinoff_pay_date`, `spinoff_corporate_action_id`, `spinoff_target_symbol_description`,
    `spinoff_target_cusip`, `spinoff_target_asset_id`, `spinoff_disbursed_symbol_description`, `spinoff_disbursed_cusip`, `spinoff_disbursed_asset_id`, `interest_payment_symbol_description`,
    `interest_payment_cash_rate`, `interest_payment_settled`, `interest_payment_record_date`, `interest_payment_payment_date`, `interest_payment_corporate_action_id`, `interest_payment_target_symbol_description`,
    `interest_payment_target_cusip`, `interest_payment_target_asset_id`, `interest_payment_disbursed_symbol_description`, `interest_payment_disbursed_cusip`, `interest_payment_disbursed_asset_id`, `liquidation_symbol_description`,
    `liquidation_cash_rate`, `liquidation_quantity`, `liquidation_settled`, `liquidation_action`, `liquidation_subtype`, `liquidation_record_date`,
    `liquidation_payment_date`, `liquidation_effective_date`, `liquidation_corporate_action_id`, `liquidation_target_symbol_description`, `liquidation_target_cusip`, `liquidation_target_asset_id`,
    `liquidation_disbursed_symbol_description`, `liquidation_disbursed_cusip`, `liquidation_disbursed_asset_id`, `dividend_symbol_description`, `dividend_cash_rate`, `dividend_settled`,
    `dividend_record_date`, `dividend_subtype`, `dividend_corporate_action_id`, `dividend_target_symbol_description`, `dividend_target_cusip`, `dividend_target_asset_id`,
    `dividend_disbursed_symbol_description`, `dividend_disbursed_cusip`, `dividend_disbursed_asset_id`, `sale_of_rights_symbol_description`, `sale_of_rights_cash_rate`, `sale_of_rights_settled`,
    `sale_of_rights_record_date`, `sale_of_rights_payment_date`, `sale_of_rights_corporate_action_id`, `sale_of_rights_target_symbol_description`, `sale_of_rights_target_cusip`, `sale_of_rights_target_asset_id`,
    `sale_of_rights_disbursed_symbol_description`, `sale_of_rights_disbursed_cusip`, `sale_of_rights_disbursed_asset_id`, `redemption_full_symbol_description`, `redemption_full_cash_rate`, `redemption_full_quantity`,
    `redemption_full_action`, `redemption_full_subtype`, `redemption_full_payment_date`, `redemption_full_corporate_action_id`, `redemption_full_target_symbol_description`, `redemption_full_target_cusip`,
    `redemption_full_target_asset_id`, `redemption_full_disbursed_symbol_description`, `redemption_full_disbursed_cusip`, `redemption_full_disbursed_asset_id`, `rights_distribution_new_symbol_description`, `rights_distribution_settled`,
    `rights_distribution_record_date`, `rights_distribution_payment_date`, `rights_distribution_corporate_action_id`, `rights_distribution_target_symbol_description`, `rights_distribution_target_cusip`, `rights_distribution_target_asset_id`,
    `rights_distribution_disbursed_symbol_description`, `rights_distribution_disbursed_cusip`, `rights_distribution_disbursed_asset_id`, `deposit_contribution_type`, `deposit_contribution_year`, `deposit_conversion`,
    `deposit_futures_settlement`, `deposit_micro`, `deposit_retirement_type`, `deposit_type`, `deposit_originating_institution`, `deposit_destination_institution`,
    `deposit_additional_instructions`, `deposit_fed_reference_number`, `deposit_originating_account_number`, `withdrawal_conversion`, `withdrawal_distribution_type`, `withdrawal_distribution_year`,
    `withdrawal_closing_account`, `withdrawal_futures_settlement`, `withdrawal_micro`, `withdrawal_periodic`, `withdrawal_retirement_type`, `withdrawal_taxable`,
    `withdrawal_type`, `withdrawal_advance`, `withdrawal_originating_institution`, `withdrawal_destination_institution`, `withdrawal_additional_instructions`, `withdrawal_fed_reference_number`,
    `withdrawal_destination_account_number`, `worthless_symbol_description`, `worthless_effective_date`, `worthless_payment_date`, `worthless_corporate_action_id`, `worthless_target_symbol_description`,
    `worthless_target_cusip`, `worthless_target_asset_id`, `worthless_disbursed_symbol_description`, `worthless_disbursed_cusip`, `worthless_disbursed_asset_id`, `transfer_first_party`,
    `transfer_originating_institution`, `transfer_destination_institution`, `transfer_additional_instructions`, `transfer_client_brokerage`, `transfer_transfer_type`, `rounding_adjustment_rounding_reason`,
    `fees`, `withholdings`, `commissions`, `accrued_interests`, `merger_symbol_description`, `merger_quantity`,
    `merger_old_cusip`, `merger_new_cusip`, `merger_cash_rate`, `merger_stock_rate`, `merger_type`, `merger_action`,
    `merger_effective_date`, `merger_corporate_action_id`, `merger_target_symbol_description`, `merger_target_cusip`, `merger_target_asset_id`, `merger_disbursed_symbol_description`,
    `merger_disbursed_cusip`, `merger_disbursed_asset_id`, `credit_credit_type`, `credit_taxable`, `credit_additional_instructions`, `fpsl_action`,
    `account_transfer_action`, `account_transfer_acats_control_number`, `account_transfer_institution`, `account_transfer_additional_instructions`, `account_transfer_acats_asset_sequence_number`, `account_transfer_contra_party_id`,
    `account_transfer_contra_party_account_number`, `account_transfer_method`, `tender_offer_symbol_description`, `tender_offer_target_cusip`, `tender_offer_cash_rate`, `tender_offer_corporate_action_id`,
    `tender_offer_target_symbol_description`, `tender_offer_corporate_action_general_information_target_cusip`, `tender_offer_target_asset_id`, `tender_offer_disbursed_symbol_description`, `tender_offer_disbursed_cusip`, `tender_offer_disbursed_asset_id`,
    `unit_split_symbol_description`, `unit_split_stock_rate`, `unit_split_corporate_action_id`, `unit_split_target_symbol_description`, `unit_split_target_cusip`, `unit_split_target_asset_id`,
    `unit_split_disbursed_symbol_description`, `unit_split_disbursed_cusip`, `unit_split_disbursed_asset_id`, `exchange_symbol_description`, `exchange_old_cusip`, `exchange_new_cusip`,
    `exchange_cash_rate`, `exchange_stock_rate`, `exchange_type`, `exchange_corporate_action_id`, `exchange_target_symbol_description`, `exchange_target_cusip`,
    `exchange_target_asset_id`, `exchange_disbursed_symbol_description`, `exchange_disbursed_cusip`, `exchange_disbursed_asset_id`, `conversion_symbol_description`, `conversion_old_cusip`,
    `conversion_new_cusip`, `conversion_cash_rate`, `conversion_stock_rate`, `conversion_type`, `conversion_corporate_action_id`, `conversion_target_symbol_description`,
    `conversion_target_cusip`, `conversion_target_asset_id`, `conversion_disbursed_symbol_description`, `conversion_disbursed_cusip`, `conversion_disbursed_asset_id`, `account_memo`,
    `warrant_exercise_symbol_description`, `warrant_exercise_corporate_action_id`, `warrant_exercise_target_symbol_description`, `warrant_exercise_target_cusip`, `warrant_exercise_target_asset_id`, `warrant_exercise_disbursed_symbol_description`,
    `warrant_exercise_disbursed_cusip`, `warrant_exercise_disbursed_asset_id`, `rights_subscription_symbol_description`, `rights_subscription_corporate_action_id`, `rights_subscription_target_symbol_description`, `rights_subscription_target_cusip`,
    `rights_subscription_target_asset_id`, `rights_subscription_disbursed_symbol_description`, `rights_subscription_disbursed_cusip`, `rights_subscription_disbursed_asset_id`, `maturity_cash_rate`, `maturity_quantity`,
    `maturity_payment_date`, `maturity_corporate_action_id`, `maturity_target_symbol_description`, `maturity_target_cusip`, `maturity_target_asset_id`, `maturity_disbursed_symbol_description`,
    `maturity_disbursed_cusip`, `maturity_disbursed_asset_id`, `drip_action`, `fee_additional_instructions`, `sweep_action`, `sweep_type`,
    `sweep_eod_redemption`, `subtype_category`, `source_application`, `source_application_id`, `generation`, `client_id`,
    `suppress_downstream`, `rounded_offset`, `suppress_documents`, `creation_time`, `initiating_user_id`, `previous_activity_id`,
    `previous_process_date`, `_key`, `_ingested_at`, `kafka_metadata_topic`, `kafka_metadata_partition`, `kafka_metadata_offset`,
    `proto_metadata_type_name`, `proto_metadata_schema_id`, `snapshot_timestamp`, `correspondent_id`, `source_file`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `account_id`,
    idx AS `activity_id`,
    concat('TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `type`,
    concat('SUB_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `sub_type`,
    concat('SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `symbol`,
    concat('ASSET_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `asset_type`,
    concat('REGION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `region_code`,
    idx AS `asset_id`,
    concat('SIDE_', lpad(CAST(idx AS STRING), 2, '0')) AS `side`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `quantity`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `currency_code`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `currency_asset_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `price`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `gross_amount`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `net_amount`,
    date_add(DATE '2026-01-01', idx - 1) AS `activity_date`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `activity_time`,
    date_add(DATE '2026-01-01', idx - 1) AS `process_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `settle_date`,
    concat('STATE_', lpad(CAST(idx AS STRING), 2, '0')) AS `state`,
    concat('ACTIVITY_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `activity_description`,
    concat('ASSET_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `asset_description`,
    concat('ASSET_VERSION_', lpad(CAST(idx AS STRING), 2, '0')) AS `asset_version`,
    concat('TRADE_SYMBOL_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_symbol_description`,
    concat('TRADE_ADDITIONAL_INSTRUC_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_additional_instructions`,
    concat('TRADE_SPECIAL_INSTRUCTIO_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_special_instructions`,
    idx AS `trade_client_order_id`,
    concat('TRADE_EXCHANGE_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_exchange`,
    concat('TRADE_BROKER_CAPACITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_broker_capacity`,
    concat('TRADE_ROUTE_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_route`,
    concat('TRADE_ALGO_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_algo`,
    concat('TRADE_BROKER_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_broker`,
    idx AS `trade_execution_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_markup`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_markdown`,
    concat('TRADE_EXECUTION_ONLY_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_execution_only`,
    concat('TRADE_WHEN_ISSUED_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_when_issued`,
    concat('TRADE_WHEN_DISTRIBUTED_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_when_distributed`,
    concat('TRADE_IS_WRITEOFF_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_is_writeoff`,
    concat('TRADE_CLIENT_MEMOS_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_client_memos`,
    idx AS `trade_order_id`,
    idx AS `trade_alternate_order_id`,
    idx AS `trade_external_id`,
    idx AS `trade_source_account_id`,
    idx AS `trade_booking_api_trade_id`,
    idx AS `trade_booking_api_trade_allocation_id`,
    idx AS `trade_gateway_client_order_id`,
    concat('TRADE_INTERNAL_ERROR_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_internal_error`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_prevailing_market_price`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_price_adjustment_type`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_price_adjustment_amount`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_price_adjustment_percent`,
    concat('TRADE_YIELD_RECORDS_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_yield_records`,
    concat('REVERSE_STOCK_SPLIT_SYMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_symbol_description`,
    concat('REVERSE_STOCK_SPLIT_FACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_factor_numerator`,
    concat('REVERSE_STOCK_SPLIT_FACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_factor_denominator`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `reverse_stock_split_quantity`,
    concat('REVERSE_STOCK_SPLIT_NEW__', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_new_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `reverse_stock_split_cash_rate`,
    concat('REVERSE_STOCK_SPLIT_OLD__', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_old_cusip`,
    concat('REVERSE_STOCK_SPLIT_ACTI_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_action`,
    date_add(DATE '2026-01-01', idx - 1) AS `reverse_stock_split_effective_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `reverse_stock_split_corporate_action_id`,
    concat('REVERSE_STOCK_SPLIT_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_target_symbol_description`,
    concat('REVERSE_STOCK_SPLIT_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_target_cusip`,
    idx AS `reverse_stock_split_target_asset_id`,
    concat('REVERSE_STOCK_SPLIT_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_disbursed_symbol_description`,
    concat('REVERSE_STOCK_SPLIT_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `reverse_stock_split_disbursed_cusip`,
    idx AS `reverse_stock_split_disbursed_asset_id`,
    concat('CASH_DIVIDEND_SYMBOL_DES_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_dividend_cash_rate`,
    concat('CASH_DIVIDEND_SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `cash_dividend_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `cash_dividend_payment_date`,
    concat('CASH_DIVIDEND_TEFRA_WITH_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_tefra_withholding`,
    concat('CASH_DIVIDEND_FOREIGN_WI_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_foreign_withholding`,
    concat('CASH_DIVIDEND_NRA_WITHHO_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_nra_withholding`,
    concat('CASH_DIVIDEND_QUALIFIED_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_qualified`,
    concat('CASH_DIVIDEND_LONG_TERM__', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_long_term_gain`,
    concat('CASH_DIVIDEND_FREE_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_free`,
    concat('CASH_DIVIDEND_FPSL_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_fpsl`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_dividend_is_substitute_payment`,
    concat('CASH_DIVIDEND_SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_subtype`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_dividend_quantity`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_dividend_corporate_action_id`,
    concat('CASH_DIVIDEND_TARGET_SYM_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_target_symbol_description`,
    concat('CASH_DIVIDEND_TARGET_CUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_target_cusip`,
    idx AS `cash_dividend_target_asset_id`,
    concat('CASH_DIVIDEND_DISBURSED__', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_disbursed_symbol_description`,
    concat('CASH_DIVIDEND_DISBURSED__', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_disbursed_cusip`,
    idx AS `cash_dividend_disbursed_asset_id`,
    concat('CASH_DIVIDEND_REINVESTED_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_dividend_reinvested`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `stock_dividend_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `stock_dividend_quantity`,
    date_add(DATE '2026-01-01', idx - 1) AS `stock_dividend_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `stock_dividend_pay_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `stock_dividend_corporate_action_id`,
    concat('STOCK_DIVIDEND_TARGET_SY_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_dividend_target_symbol_description`,
    concat('STOCK_DIVIDEND_TARGET_CU_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_dividend_target_cusip`,
    idx AS `stock_dividend_target_asset_id`,
    concat('STOCK_DIVIDEND_DISBURSED_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_dividend_disbursed_symbol_description`,
    concat('STOCK_DIVIDEND_DISBURSED_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_dividend_disbursed_cusip`,
    idx AS `stock_dividend_disbursed_asset_id`,
    concat('WITHDRAWAL_DEPOSIT_TRANS_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_deposit_transfer_originating_institution`,
    concat('WITHDRAWAL_DEPOSIT_TRANS_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_deposit_transfer_destination_institution`,
    concat('WITHDRAWAL_DEPOSIT_TRANS_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_deposit_transfer_additional_instructions`,
    concat('STOCK_SPLIT_FACTOR_NUMER_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_factor_numerator`,
    concat('STOCK_SPLIT_FACTOR_DENOM_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_factor_denominator`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `stock_split_quantity`,
    date_add(DATE '2026-01-01', idx - 1) AS `stock_split_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `stock_split_pay_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `stock_split_corporate_action_id`,
    concat('STOCK_SPLIT_TARGET_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_target_symbol_description`,
    concat('STOCK_SPLIT_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_target_cusip`,
    idx AS `stock_split_target_asset_id`,
    concat('STOCK_SPLIT_DISBURSED_SY_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_disbursed_symbol_description`,
    concat('STOCK_SPLIT_DISBURSED_CU_', lpad(CAST(idx AS STRING), 2, '0')) AS `stock_split_disbursed_cusip`,
    idx AS `stock_split_disbursed_asset_id`,
    concat('NAME_CHANGE_OLD_SYMBOL_D_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_old_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `name_change_quantity`,
    concat('NAME_CHANGE_OLD_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_old_cusip`,
    concat('NAME_CHANGE_NEW_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_new_cusip`,
    concat('NAME_CHANGE_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_action`,
    date_add(DATE '2026-01-01', idx - 1) AS `name_change_effective_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `name_change_corporate_action_id`,
    concat('NAME_CHANGE_TARGET_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_target_symbol_description`,
    concat('NAME_CHANGE_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_target_cusip`,
    idx AS `name_change_target_asset_id`,
    concat('NAME_CHANGE_DISBURSED_SY_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_disbursed_symbol_description`,
    concat('NAME_CHANGE_DISBURSED_CU_', lpad(CAST(idx AS STRING), 2, '0')) AS `name_change_disbursed_cusip`,
    idx AS `name_change_disbursed_asset_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `capital_gains_quantity`,
    date_add(DATE '2026-01-01', idx - 1) AS `capital_gains_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `capital_gains_payment_date`,
    concat('CAPITAL_GAINS_LONG_TERM__', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_long_term_gain`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `capital_gains_corporate_action_id`,
    concat('CAPITAL_GAINS_TARGET_SYM_', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_target_symbol_description`,
    concat('CAPITAL_GAINS_TARGET_CUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_target_cusip`,
    idx AS `capital_gains_target_asset_id`,
    concat('CAPITAL_GAINS_DISBURSED__', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_disbursed_symbol_description`,
    concat('CAPITAL_GAINS_DISBURSED__', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_disbursed_cusip`,
    idx AS `capital_gains_disbursed_asset_id`,
    concat('CAPITAL_GAINS_REINVESTED_', lpad(CAST(idx AS STRING), 2, '0')) AS `capital_gains_reinvested`,
    concat('SPINOFF_OLD_SYMBOL_DESCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_old_symbol_description`,
    concat('SPINOFF_NEW_SYMBOL_DESCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_new_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `spinoff_quantity`,
    date_add(DATE '2026-01-01', idx - 1) AS `spinoff_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `spinoff_pay_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `spinoff_corporate_action_id`,
    concat('SPINOFF_TARGET_SYMBOL_DE_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_target_symbol_description`,
    concat('SPINOFF_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_target_cusip`,
    idx AS `spinoff_target_asset_id`,
    concat('SPINOFF_DISBURSED_SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_disbursed_symbol_description`,
    concat('SPINOFF_DISBURSED_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `spinoff_disbursed_cusip`,
    idx AS `spinoff_disbursed_asset_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `interest_payment_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `interest_payment_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_corporate_action_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_target_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_target_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_target_asset_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_disbursed_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_disbursed_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `interest_payment_disbursed_asset_id`,
    concat('LIQUIDATION_SYMBOL_DESCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `liquidation_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `liquidation_quantity`,
    concat('LIQUIDATION_SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_settled`,
    concat('LIQUIDATION_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_action`,
    concat('LIQUIDATION_SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_subtype`,
    date_add(DATE '2026-01-01', idx - 1) AS `liquidation_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `liquidation_payment_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `liquidation_effective_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `liquidation_corporate_action_id`,
    concat('LIQUIDATION_TARGET_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_target_symbol_description`,
    concat('LIQUIDATION_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_target_cusip`,
    idx AS `liquidation_target_asset_id`,
    concat('LIQUIDATION_DISBURSED_SY_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_disbursed_symbol_description`,
    concat('LIQUIDATION_DISBURSED_CU_', lpad(CAST(idx AS STRING), 2, '0')) AS `liquidation_disbursed_cusip`,
    idx AS `liquidation_disbursed_asset_id`,
    concat('DIVIDEND_SYMBOL_DESCRIPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `dividend_cash_rate`,
    concat('DIVIDEND_SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `dividend_record_date`,
    concat('DIVIDEND_SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_subtype`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `dividend_corporate_action_id`,
    concat('DIVIDEND_TARGET_SYMBOL_D_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_target_symbol_description`,
    concat('DIVIDEND_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_target_cusip`,
    idx AS `dividend_target_asset_id`,
    concat('DIVIDEND_DISBURSED_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_disbursed_symbol_description`,
    concat('DIVIDEND_DISBURSED_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `dividend_disbursed_cusip`,
    idx AS `dividend_disbursed_asset_id`,
    concat('SALE_OF_RIGHTS_SYMBOL_DE_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `sale_of_rights_cash_rate`,
    concat('SALE_OF_RIGHTS_SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `sale_of_rights_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `sale_of_rights_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `sale_of_rights_corporate_action_id`,
    concat('SALE_OF_RIGHTS_TARGET_SY_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_target_symbol_description`,
    concat('SALE_OF_RIGHTS_TARGET_CU_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_target_cusip`,
    idx AS `sale_of_rights_target_asset_id`,
    concat('SALE_OF_RIGHTS_DISBURSED_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_disbursed_symbol_description`,
    concat('SALE_OF_RIGHTS_DISBURSED_', lpad(CAST(idx AS STRING), 2, '0')) AS `sale_of_rights_disbursed_cusip`,
    idx AS `sale_of_rights_disbursed_asset_id`,
    concat('REDEMPTION_FULL_SYMBOL_D_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `redemption_full_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `redemption_full_quantity`,
    concat('REDEMPTION_FULL_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_action`,
    concat('REDEMPTION_FULL_SUBTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_subtype`,
    date_add(DATE '2026-01-01', idx - 1) AS `redemption_full_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `redemption_full_corporate_action_id`,
    concat('REDEMPTION_FULL_TARGET_S_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_target_symbol_description`,
    concat('REDEMPTION_FULL_TARGET_C_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_target_cusip`,
    idx AS `redemption_full_target_asset_id`,
    concat('REDEMPTION_FULL_DISBURSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_disbursed_symbol_description`,
    concat('REDEMPTION_FULL_DISBURSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `redemption_full_disbursed_cusip`,
    idx AS `redemption_full_disbursed_asset_id`,
    concat('RIGHTS_DISTRIBUTION_NEW__', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_new_symbol_description`,
    concat('RIGHTS_DISTRIBUTION_SETT_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `rights_distribution_record_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `rights_distribution_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `rights_distribution_corporate_action_id`,
    concat('RIGHTS_DISTRIBUTION_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_target_symbol_description`,
    concat('RIGHTS_DISTRIBUTION_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_target_cusip`,
    idx AS `rights_distribution_target_asset_id`,
    concat('RIGHTS_DISTRIBUTION_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_disbursed_symbol_description`,
    concat('RIGHTS_DISTRIBUTION_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_distribution_disbursed_cusip`,
    idx AS `rights_distribution_disbursed_asset_id`,
    concat('DEPOSIT_CONTRIBUTION_TYP_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_contribution_type`,
    concat('DEPOSIT_CONTRIBUTION_YEA_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_contribution_year`,
    concat('DEPOSIT_CONVERSION_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_conversion`,
    concat('DEPOSIT_FUTURES_SETTLEME_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_futures_settlement`,
    concat('DEPOSIT_MICRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_micro`,
    concat('DEPOSIT_RETIREMENT_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_retirement_type`,
    concat('DEPOSIT_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_type`,
    concat('DEPOSIT_ORIGINATING_INST_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_originating_institution`,
    concat('DEPOSIT_DESTINATION_INST_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_destination_institution`,
    concat('DEPOSIT_ADDITIONAL_INSTR_', lpad(CAST(idx AS STRING), 2, '0')) AS `deposit_additional_instructions`,
    idx AS `deposit_fed_reference_number`,
    idx AS `deposit_originating_account_number`,
    concat('WITHDRAWAL_CONVERSION_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_conversion`,
    concat('WITHDRAWAL_DISTRIBUTION__', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_distribution_type`,
    concat('WITHDRAWAL_DISTRIBUTION__', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_distribution_year`,
    concat('WITHDRAWAL_CLOSING_ACCOU_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_closing_account`,
    concat('WITHDRAWAL_FUTURES_SETTL_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_futures_settlement`,
    concat('WITHDRAWAL_MICRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_micro`,
    concat('WITHDRAWAL_PERIODIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_periodic`,
    concat('WITHDRAWAL_RETIREMENT_TY_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_retirement_type`,
    concat('WITHDRAWAL_TAXABLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_taxable`,
    concat('WITHDRAWAL_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_type`,
    concat('WITHDRAWAL_ADVANCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_advance`,
    concat('WITHDRAWAL_ORIGINATING_I_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_originating_institution`,
    concat('WITHDRAWAL_DESTINATION_I_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_destination_institution`,
    concat('WITHDRAWAL_ADDITIONAL_IN_', lpad(CAST(idx AS STRING), 2, '0')) AS `withdrawal_additional_instructions`,
    idx AS `withdrawal_fed_reference_number`,
    idx AS `withdrawal_destination_account_number`,
    concat('WORTHLESS_SYMBOL_DESCRIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `worthless_symbol_description`,
    date_add(DATE '2026-01-01', idx - 1) AS `worthless_effective_date`,
    date_add(DATE '2026-01-01', idx - 1) AS `worthless_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `worthless_corporate_action_id`,
    concat('WORTHLESS_TARGET_SYMBOL__', lpad(CAST(idx AS STRING), 2, '0')) AS `worthless_target_symbol_description`,
    concat('WORTHLESS_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `worthless_target_cusip`,
    idx AS `worthless_target_asset_id`,
    concat('WORTHLESS_DISBURSED_SYMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `worthless_disbursed_symbol_description`,
    concat('WORTHLESS_DISBURSED_CUSI_', lpad(CAST(idx AS STRING), 2, '0')) AS `worthless_disbursed_cusip`,
    idx AS `worthless_disbursed_asset_id`,
    concat('TRANSFER_FIRST_PARTY_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_first_party`,
    concat('TRANSFER_ORIGINATING_INS_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_originating_institution`,
    concat('TRANSFER_DESTINATION_INS_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_destination_institution`,
    concat('TRANSFER_ADDITIONAL_INST_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_additional_instructions`,
    concat('TRANSFER_CLIENT_BROKERAG_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_client_brokerage`,
    concat('TRANSFER_TRANSFER_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `transfer_transfer_type`,
    concat('ROUNDING_ADJUSTMENT_ROUN_', lpad(CAST(idx AS STRING), 2, '0')) AS `rounding_adjustment_rounding_reason`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `fees`,
    concat('WITHHOLDINGS_', lpad(CAST(idx AS STRING), 2, '0')) AS `withholdings`,
    concat('COMMISSIONS_', lpad(CAST(idx AS STRING), 2, '0')) AS `commissions`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `accrued_interests`,
    concat('MERGER_SYMBOL_DESCRIPTIO_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `merger_quantity`,
    concat('MERGER_OLD_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_old_cusip`,
    concat('MERGER_NEW_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_new_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `merger_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `merger_stock_rate`,
    concat('MERGER_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_type`,
    concat('MERGER_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_action`,
    date_add(DATE '2026-01-01', idx - 1) AS `merger_effective_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `merger_corporate_action_id`,
    concat('MERGER_TARGET_SYMBOL_DES_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_target_symbol_description`,
    concat('MERGER_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_target_cusip`,
    idx AS `merger_target_asset_id`,
    concat('MERGER_DISBURSED_SYMBOL__', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_disbursed_symbol_description`,
    concat('MERGER_DISBURSED_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `merger_disbursed_cusip`,
    idx AS `merger_disbursed_asset_id`,
    concat('CREDIT_CREDIT_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `credit_credit_type`,
    concat('CREDIT_TAXABLE_', lpad(CAST(idx AS STRING), 2, '0')) AS `credit_taxable`,
    concat('CREDIT_ADDITIONAL_INSTRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `credit_additional_instructions`,
    concat('FPSL_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `fpsl_action`,
    concat('ACCOUNT_TRANSFER_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_transfer_action`,
    idx AS `account_transfer_acats_control_number`,
    concat('ACCOUNT_TRANSFER_INSTITU_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_transfer_institution`,
    concat('ACCOUNT_TRANSFER_ADDITIO_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_transfer_additional_instructions`,
    idx AS `account_transfer_acats_asset_sequence_number`,
    idx AS `account_transfer_contra_party_id`,
    idx AS `account_transfer_contra_party_account_number`,
    concat('ACCOUNT_TRANSFER_METHOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_transfer_method`,
    concat('TENDER_OFFER_SYMBOL_DESC_', lpad(CAST(idx AS STRING), 2, '0')) AS `tender_offer_symbol_description`,
    concat('TENDER_OFFER_TARGET_CUSI_', lpad(CAST(idx AS STRING), 2, '0')) AS `tender_offer_target_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `tender_offer_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `tender_offer_corporate_action_id`,
    concat('TENDER_OFFER_TARGET_SYMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `tender_offer_target_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `tender_offer_corporate_action_general_information_target_cusip`,
    idx AS `tender_offer_target_asset_id`,
    concat('TENDER_OFFER_DISBURSED_S_', lpad(CAST(idx AS STRING), 2, '0')) AS `tender_offer_disbursed_symbol_description`,
    concat('TENDER_OFFER_DISBURSED_C_', lpad(CAST(idx AS STRING), 2, '0')) AS `tender_offer_disbursed_cusip`,
    idx AS `tender_offer_disbursed_asset_id`,
    concat('UNIT_SPLIT_SYMBOL_DESCRI_', lpad(CAST(idx AS STRING), 2, '0')) AS `unit_split_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `unit_split_stock_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `unit_split_corporate_action_id`,
    concat('UNIT_SPLIT_TARGET_SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `unit_split_target_symbol_description`,
    concat('UNIT_SPLIT_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `unit_split_target_cusip`,
    idx AS `unit_split_target_asset_id`,
    concat('UNIT_SPLIT_DISBURSED_SYM_', lpad(CAST(idx AS STRING), 2, '0')) AS `unit_split_disbursed_symbol_description`,
    concat('UNIT_SPLIT_DISBURSED_CUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `unit_split_disbursed_cusip`,
    idx AS `unit_split_disbursed_asset_id`,
    concat('EXCHANGE_SYMBOL_DESCRIPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_symbol_description`,
    concat('EXCHANGE_OLD_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_old_cusip`,
    concat('EXCHANGE_NEW_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_new_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `exchange_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `exchange_stock_rate`,
    concat('EXCHANGE_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_type`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `exchange_corporate_action_id`,
    concat('EXCHANGE_TARGET_SYMBOL_D_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_target_symbol_description`,
    concat('EXCHANGE_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_target_cusip`,
    idx AS `exchange_target_asset_id`,
    concat('EXCHANGE_DISBURSED_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_disbursed_symbol_description`,
    concat('EXCHANGE_DISBURSED_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `exchange_disbursed_cusip`,
    idx AS `exchange_disbursed_asset_id`,
    concat('CONVERSION_SYMBOL_DESCRI_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_symbol_description`,
    concat('CONVERSION_OLD_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_old_cusip`,
    concat('CONVERSION_NEW_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_new_cusip`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `conversion_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `conversion_stock_rate`,
    concat('CONVERSION_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_type`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `conversion_corporate_action_id`,
    concat('CONVERSION_TARGET_SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_target_symbol_description`,
    concat('CONVERSION_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_target_cusip`,
    idx AS `conversion_target_asset_id`,
    concat('CONVERSION_DISBURSED_SYM_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_disbursed_symbol_description`,
    concat('CONVERSION_DISBURSED_CUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `conversion_disbursed_cusip`,
    idx AS `conversion_disbursed_asset_id`,
    concat('ACCOUNT_MEMO_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_memo`,
    concat('WARRANT_EXERCISE_SYMBOL__', lpad(CAST(idx AS STRING), 2, '0')) AS `warrant_exercise_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `warrant_exercise_corporate_action_id`,
    concat('WARRANT_EXERCISE_TARGET__', lpad(CAST(idx AS STRING), 2, '0')) AS `warrant_exercise_target_symbol_description`,
    concat('WARRANT_EXERCISE_TARGET__', lpad(CAST(idx AS STRING), 2, '0')) AS `warrant_exercise_target_cusip`,
    idx AS `warrant_exercise_target_asset_id`,
    concat('WARRANT_EXERCISE_DISBURS_', lpad(CAST(idx AS STRING), 2, '0')) AS `warrant_exercise_disbursed_symbol_description`,
    concat('WARRANT_EXERCISE_DISBURS_', lpad(CAST(idx AS STRING), 2, '0')) AS `warrant_exercise_disbursed_cusip`,
    idx AS `warrant_exercise_disbursed_asset_id`,
    concat('RIGHTS_SUBSCRIPTION_SYMB_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_subscription_symbol_description`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `rights_subscription_corporate_action_id`,
    concat('RIGHTS_SUBSCRIPTION_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_subscription_target_symbol_description`,
    concat('RIGHTS_SUBSCRIPTION_TARG_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_subscription_target_cusip`,
    idx AS `rights_subscription_target_asset_id`,
    concat('RIGHTS_SUBSCRIPTION_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_subscription_disbursed_symbol_description`,
    concat('RIGHTS_SUBSCRIPTION_DISB_', lpad(CAST(idx AS STRING), 2, '0')) AS `rights_subscription_disbursed_cusip`,
    idx AS `rights_subscription_disbursed_asset_id`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `maturity_cash_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `maturity_quantity`,
    date_add(DATE '2026-01-01', idx - 1) AS `maturity_payment_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `maturity_corporate_action_id`,
    concat('MATURITY_TARGET_SYMBOL_D_', lpad(CAST(idx AS STRING), 2, '0')) AS `maturity_target_symbol_description`,
    concat('MATURITY_TARGET_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `maturity_target_cusip`,
    idx AS `maturity_target_asset_id`,
    concat('MATURITY_DISBURSED_SYMBO_', lpad(CAST(idx AS STRING), 2, '0')) AS `maturity_disbursed_symbol_description`,
    concat('MATURITY_DISBURSED_CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `maturity_disbursed_cusip`,
    idx AS `maturity_disbursed_asset_id`,
    concat('DRIP_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `drip_action`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `fee_additional_instructions`,
    concat('SWEEP_ACTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `sweep_action`,
    concat('SWEEP_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `sweep_type`,
    concat('SWEEP_EOD_REDEMPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `sweep_eod_redemption`,
    concat('SUBTYPE_CATEGORY_', lpad(CAST(idx AS STRING), 2, '0')) AS `subtype_category`,
    concat('SOURCE_APPLICATION_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_application`,
    idx AS `source_application_id`,
    concat('GENERATION_', lpad(CAST(idx AS STRING), 2, '0')) AS `generation`,
    idx AS `client_id`,
    concat('SUPPRESS_DOWNSTREAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `suppress_downstream`,
    concat('ROUNDED_OFFSET_', lpad(CAST(idx AS STRING), 2, '0')) AS `rounded_offset`,
    concat('SUPPRESS_DOCUMENTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `suppress_documents`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `creation_time`,
    idx AS `initiating_user_id`,
    idx AS `previous_activity_id`,
    date_add(DATE '2026-01-01', idx - 1) AS `previous_process_date`,
    concat('_KEY_', lpad(CAST(idx AS STRING), 2, '0')) AS `_key`,
    concat('_INGESTED_AT_', lpad(CAST(idx AS STRING), 2, '0')) AS `_ingested_at`,
    concat('KAFKA_METADATA_TOPIC_', lpad(CAST(idx AS STRING), 2, '0')) AS `kafka_metadata_topic`,
    concat('KAFKA_METADATA_PARTITION_', lpad(CAST(idx AS STRING), 2, '0')) AS `kafka_metadata_partition`,
    concat('KAFKA_METADATA_OFFSET_', lpad(CAST(idx AS STRING), 2, '0')) AS `kafka_metadata_offset`,
    concat('PROTO_METADATA_TYPE_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `proto_metadata_type_name`,
    idx AS `proto_metadata_schema_id`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `snapshot_timestamp`,
    idx AS `correspondent_id`,
    concat('SOURCE_FILE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_file`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."APEX_daily_overnight_balances"
CREATE TABLE IF NOT EXISTS apex.default.apex_daily_overnight_balances (
    `account_id` BIGINT,
    `firm` STRING,
    `process_date` DATE,
    `currency_code` DECIMAL(38,10),
    `total_equity` STRING,
    `margin_equity` STRING,
    `margin_requirement` STRING,
    `margin_excess_equity` STRING,
    `cash_equity` STRING,
    `cash_requirement` STRING,
    `cash_excess_equity` STRING,
    `margin_requirement_with_concentration` STRING,
    `margin_excess_equity_with_concentration` STRING,
    `overnight_buying_power_calculated` STRING,
    `overnight_buying_power_issued` STRING,
    `day_trade_buying_power_issued` STRING,
    `regt_buying_power_calculated` STRING,
    `regt_buying_power_issued` STRING,
    `overnight_factor_calculated` STRING,
    `overnight_factor_issued` STRING,
    `day_trade_factor_calculated` STRING,
    `day_trade_factor_issued` STRING,
    `margin_equity_percent` DECIMAL(38,10),
    `position_market_value` DECIMAL(38,10),
    `long_equity_market_value` DECIMAL(38,10),
    `short_equity_market_value` DECIMAL(38,10),
    `long_option_market_value` DECIMAL(38,10),
    `short_option_market_value` DECIMAL(38,10),
    `total_trade_balance` DECIMAL(38,10),
    `total_settle_balance` DECIMAL(38,10),
    `cash_trade_balance` DECIMAL(38,10),
    `margin_trade_balance` DECIMAL(38,10),
    `short_trade_balance` DECIMAL(38,10),
    `money_market_trade_balance` DECIMAL(38,10),
    `cash_settle_balance` DECIMAL(38,10),
    `margin_settle_balance` DECIMAL(38,10),
    `short_settle_balance` DECIMAL(38,10),
    `money_market_settle_balance` DECIMAL(38,10),
    `free_cash` STRING,
    `sma` STRING,
    `available_to_withdraw` STRING,
    `future_balance` DECIMAL(38,10),
    `future_equity` STRING,
    `future_requirement` STRING,
    `options_requirement` STRING,
    `non_options_requirement` STRING,
    `last_update_time` TIMESTAMP,
    `non_options_requirement_not_concentrated` DECIMAL(38,10),
    `type1_unavailable_cash_proceeds` STRING,
    `type2_unavailable_cash_proceeds` STRING,
    `net_balance` DECIMAL(38,10),
    `sma_committed` STRING,
    `high_water_mark` STRING,
    `margin_requirement_nyse` STRING,
    `margin_excess_equity_nyse` STRING,
    `settled_cash_available_to_withdraw` STRING,
    `snapshot_timestamp` TIMESTAMP,
    `correspondent_id` BIGINT,
    `source_file` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_daily_overnight_balances IS 
'The table contains daily overnight balance data for accounts, covering various equity and cash metrics. Use cases include monitoring account balances, margin requirements, and buying power analysis. It can help in understanding the financial health and liquidity of accounts over time.';

TRUNCATE TABLE apex.default.apex_daily_overnight_balances;

INSERT INTO apex.default.apex_daily_overnight_balances (
    `account_id`, `firm`, `process_date`, `currency_code`, `total_equity`, `margin_equity`,
    `margin_requirement`, `margin_excess_equity`, `cash_equity`, `cash_requirement`, `cash_excess_equity`, `margin_requirement_with_concentration`,
    `margin_excess_equity_with_concentration`, `overnight_buying_power_calculated`, `overnight_buying_power_issued`, `day_trade_buying_power_issued`, `regt_buying_power_calculated`, `regt_buying_power_issued`,
    `overnight_factor_calculated`, `overnight_factor_issued`, `day_trade_factor_calculated`, `day_trade_factor_issued`, `margin_equity_percent`, `position_market_value`,
    `long_equity_market_value`, `short_equity_market_value`, `long_option_market_value`, `short_option_market_value`, `total_trade_balance`, `total_settle_balance`,
    `cash_trade_balance`, `margin_trade_balance`, `short_trade_balance`, `money_market_trade_balance`, `cash_settle_balance`, `margin_settle_balance`,
    `short_settle_balance`, `money_market_settle_balance`, `free_cash`, `sma`, `available_to_withdraw`, `future_balance`,
    `future_equity`, `future_requirement`, `options_requirement`, `non_options_requirement`, `last_update_time`, `non_options_requirement_not_concentrated`,
    `type1_unavailable_cash_proceeds`, `type2_unavailable_cash_proceeds`, `net_balance`, `sma_committed`, `high_water_mark`, `margin_requirement_nyse`,
    `margin_excess_equity_nyse`, `settled_cash_available_to_withdraw`, `snapshot_timestamp`, `correspondent_id`, `source_file`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `account_id`,
    concat('FIRM_', lpad(CAST(idx AS STRING), 2, '0')) AS `firm`,
    date_add(DATE '2026-01-01', idx - 1) AS `process_date`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `currency_code`,
    concat('TOTAL_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `total_equity`,
    concat('MARGIN_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_equity`,
    concat('MARGIN_REQUIREMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_requirement`,
    concat('MARGIN_EXCESS_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_excess_equity`,
    concat('CASH_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_equity`,
    concat('CASH_REQUIREMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_requirement`,
    concat('CASH_EXCESS_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `cash_excess_equity`,
    concat('MARGIN_REQUIREMENT_WITH__', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_requirement_with_concentration`,
    concat('MARGIN_EXCESS_EQUITY_WIT_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_excess_equity_with_concentration`,
    concat('OVERNIGHT_BUYING_POWER_C_', lpad(CAST(idx AS STRING), 2, '0')) AS `overnight_buying_power_calculated`,
    concat('OVERNIGHT_BUYING_POWER_I_', lpad(CAST(idx AS STRING), 2, '0')) AS `overnight_buying_power_issued`,
    concat('DAY_TRADE_BUYING_POWER_I_', lpad(CAST(idx AS STRING), 2, '0')) AS `day_trade_buying_power_issued`,
    concat('REGT_BUYING_POWER_CALCUL_', lpad(CAST(idx AS STRING), 2, '0')) AS `regt_buying_power_calculated`,
    concat('REGT_BUYING_POWER_ISSUED_', lpad(CAST(idx AS STRING), 2, '0')) AS `regt_buying_power_issued`,
    concat('OVERNIGHT_FACTOR_CALCULA_', lpad(CAST(idx AS STRING), 2, '0')) AS `overnight_factor_calculated`,
    concat('OVERNIGHT_FACTOR_ISSUED_', lpad(CAST(idx AS STRING), 2, '0')) AS `overnight_factor_issued`,
    concat('DAY_TRADE_FACTOR_CALCULA_', lpad(CAST(idx AS STRING), 2, '0')) AS `day_trade_factor_calculated`,
    concat('DAY_TRADE_FACTOR_ISSUED_', lpad(CAST(idx AS STRING), 2, '0')) AS `day_trade_factor_issued`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `margin_equity_percent`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `position_market_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `long_equity_market_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `short_equity_market_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `long_option_market_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `short_option_market_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `total_trade_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `total_settle_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_trade_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `margin_trade_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `short_trade_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `money_market_trade_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `cash_settle_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `margin_settle_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `short_settle_balance`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `money_market_settle_balance`,
    concat('FREE_CASH_', lpad(CAST(idx AS STRING), 2, '0')) AS `free_cash`,
    concat('SMA_', lpad(CAST(idx AS STRING), 2, '0')) AS `sma`,
    concat('AVAILABLE_TO_WITHDRAW_', lpad(CAST(idx AS STRING), 2, '0')) AS `available_to_withdraw`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `future_balance`,
    concat('FUTURE_EQUITY_', lpad(CAST(idx AS STRING), 2, '0')) AS `future_equity`,
    concat('FUTURE_REQUIREMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `future_requirement`,
    concat('OPTIONS_REQUIREMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `options_requirement`,
    concat('NON_OPTIONS_REQUIREMENT_', lpad(CAST(idx AS STRING), 2, '0')) AS `non_options_requirement`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `last_update_time`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `non_options_requirement_not_concentrated`,
    concat('TYPE1_UNAVAILABLE_CASH_P_', lpad(CAST(idx AS STRING), 2, '0')) AS `type1_unavailable_cash_proceeds`,
    concat('TYPE2_UNAVAILABLE_CASH_P_', lpad(CAST(idx AS STRING), 2, '0')) AS `type2_unavailable_cash_proceeds`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `net_balance`,
    concat('SMA_COMMITTED_', lpad(CAST(idx AS STRING), 2, '0')) AS `sma_committed`,
    concat('HIGH_WATER_MARK_', lpad(CAST(idx AS STRING), 2, '0')) AS `high_water_mark`,
    concat('MARGIN_REQUIREMENT_NYSE_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_requirement_nyse`,
    concat('MARGIN_EXCESS_EQUITY_NYS_', lpad(CAST(idx AS STRING), 2, '0')) AS `margin_excess_equity_nyse`,
    concat('SETTLED_CASH_AVAILABLE_T_', lpad(CAST(idx AS STRING), 2, '0')) AS `settled_cash_available_to_withdraw`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `snapshot_timestamp`,
    idx AS `correspondent_id`,
    concat('SOURCE_FILE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_file`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."APEX_daily_positions"
CREATE TABLE IF NOT EXISTS apex.default.apex_daily_positions (
    `account_id` BIGINT,
    `asset_id` BIGINT,
    `date` DATE,
    `trade` STRING,
    `settled` STRING,
    `last_adjusted_date` DATE,
    `adjusted_trade` STRING,
    `adjusted_settled` STRING,
    `free` STRING,
    `fpsl` STRING,
    `pending_outgoing_acat` STRING,
    `unrestricted` STRING,
    `pending_drip` STRING,
    `pending_withdrawal` STRING,
    `snapshot_timestamp` TIMESTAMP,
    `correspondent_id` BIGINT,
    `source_file` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_daily_positions IS 
'The table contains daily position data for different accounts related to asset management. It includes information on trades, settlements, and various adjustments that may impact asset positions. Potential use cases include tracking asset performance over time, analyzing trends in trading activity, and reconciling account positions to ensure accuracy. The data can also assist in understanding the status of pending transactions.';

TRUNCATE TABLE apex.default.apex_daily_positions;

INSERT INTO apex.default.apex_daily_positions (
    `account_id`, `asset_id`, `date`, `trade`, `settled`, `last_adjusted_date`,
    `adjusted_trade`, `adjusted_settled`, `free`, `fpsl`, `pending_outgoing_acat`, `unrestricted`,
    `pending_drip`, `pending_withdrawal`, `snapshot_timestamp`, `correspondent_id`, `source_file`, `DATE_OF_DATA`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `account_id`,
    idx AS `asset_id`,
    date_add(DATE '2026-01-01', idx - 1) AS `date`,
    concat('TRADE_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade`,
    concat('SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `settled`,
    date_add(DATE '2026-01-01', idx - 1) AS `last_adjusted_date`,
    concat('ADJUSTED_TRADE_', lpad(CAST(idx AS STRING), 2, '0')) AS `adjusted_trade`,
    concat('ADJUSTED_SETTLED_', lpad(CAST(idx AS STRING), 2, '0')) AS `adjusted_settled`,
    concat('FREE_', lpad(CAST(idx AS STRING), 2, '0')) AS `free`,
    concat('FPSL_', lpad(CAST(idx AS STRING), 2, '0')) AS `fpsl`,
    concat('PENDING_OUTGOING_ACAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `pending_outgoing_acat`,
    concat('UNRESTRICTED_', lpad(CAST(idx AS STRING), 2, '0')) AS `unrestricted`,
    concat('PENDING_DRIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `pending_drip`,
    concat('PENDING_WITHDRAWAL_', lpad(CAST(idx AS STRING), 2, '0')) AS `pending_withdrawal`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `snapshot_timestamp`,
    idx AS `correspondent_id`,
    concat('SOURCE_FILE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_file`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."APEX_daily_stock_record"
CREATE TABLE IF NOT EXISTS apex.default.apex_daily_stock_record (
    `Id` BIGINT,
    `business_date` DATE,
    `branch_id` BIGINT,
    `account_id` BIGINT,
    `account_type` STRING,
    `account_class` STRING,
    `account_class_type` STRING,
    `account_name` STRING,
    `account_group_id` BIGINT,
    `asset_id` BIGINT,
    `asset_type` STRING,
    `asset_country` STRING,
    `cusip` STRING,
    `symbol` STRING,
    `symbol_description` STRING,
    `trade_position` STRING,
    `settled_position` STRING,
    `closing_price` DECIMAL(38,10),
    `closing_price_date` DATE,
    `factor` STRING,
    `trade_position_value` DECIMAL(38,10),
    `settled_position_value` DECIMAL(38,10),
    `contract_price` DECIMAL(38,10),
    `currency_code` DECIMAL(38,10),
    `currency_rate` DECIMAL(38,10),
    `trade_position_value_usd` DECIMAL(38,10),
    `settled_position_value_usd` DECIMAL(38,10),
    `ref_id` BIGINT,
    `source` STRING,
    `created_date` DATE,
    `allocation_code` STRING,
    `correspondent_code` STRING,
    `trading_mpid` BIGINT,
    `account_number` BIGINT,
    `correspondent_id` BIGINT,
    `fpsl_position` STRING,
    `snapshot_timestamp` TIMESTAMP,
    `source_file` STRING,
    `DATE_OF_DATA` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_daily_stock_record IS 
'The table contains daily stock records, including details about various accounts, assets, and their financial metrics. It tracks information such as account types, asset prices, currency values, and trade positions for each business date. This data can be utilized for analyzing stock performance, assessing account health, and making informed financial decisions related to investments.';

TRUNCATE TABLE apex.default.apex_daily_stock_record;

INSERT INTO apex.default.apex_daily_stock_record (
    `Id`, `business_date`, `branch_id`, `account_id`, `account_type`, `account_class`,
    `account_class_type`, `account_name`, `account_group_id`, `asset_id`, `asset_type`, `asset_country`,
    `cusip`, `symbol`, `symbol_description`, `trade_position`, `settled_position`, `closing_price`,
    `closing_price_date`, `factor`, `trade_position_value`, `settled_position_value`, `contract_price`, `currency_code`,
    `currency_rate`, `trade_position_value_usd`, `settled_position_value_usd`, `ref_id`, `source`, `created_date`,
    `allocation_code`, `correspondent_code`, `trading_mpid`, `account_number`, `correspondent_id`, `fpsl_position`,
    `snapshot_timestamp`, `source_file`, `DATE_OF_DATA`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `Id`,
    date_add(DATE '2026-01-01', idx - 1) AS `business_date`,
    idx AS `branch_id`,
    idx AS `account_id`,
    concat('ACCOUNT_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_type`,
    concat('ACCOUNT_CLASS_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_class`,
    concat('ACCOUNT_CLASS_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_class_type`,
    concat('ACCOUNT_NAME_', lpad(CAST(idx AS STRING), 2, '0')) AS `account_name`,
    idx AS `account_group_id`,
    idx AS `asset_id`,
    concat('ASSET_TYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `asset_type`,
    concat('ASSET_COUNTRY_', lpad(CAST(idx AS STRING), 2, '0')) AS `asset_country`,
    concat('CUSIP_', lpad(CAST(idx AS STRING), 2, '0')) AS `cusip`,
    concat('SYMBOL_', lpad(CAST(idx AS STRING), 2, '0')) AS `symbol`,
    concat('SYMBOL_DESCRIPTION_', lpad(CAST(idx AS STRING), 2, '0')) AS `symbol_description`,
    concat('TRADE_POSITION_', lpad(CAST(idx AS STRING), 2, '0')) AS `trade_position`,
    concat('SETTLED_POSITION_', lpad(CAST(idx AS STRING), 2, '0')) AS `settled_position`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `closing_price`,
    date_add(DATE '2026-01-01', idx - 1) AS `closing_price_date`,
    concat('FACTOR_', lpad(CAST(idx AS STRING), 2, '0')) AS `factor`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_position_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `settled_position_value`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `contract_price`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `currency_code`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `currency_rate`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `trade_position_value_usd`,
    CAST(idx * 100.25 AS DECIMAL(38,10)) AS `settled_position_value_usd`,
    idx AS `ref_id`,
    concat('SOURCE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source`,
    date_add(DATE '2026-01-01', idx - 1) AS `created_date`,
    concat('ALLOCATION_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `allocation_code`,
    concat('CORRESPONDENT_CODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `correspondent_code`,
    idx AS `trading_mpid`,
    idx AS `account_number`,
    idx AS `correspondent_id`,
    concat('FPSL_POSITION_', lpad(CAST(idx AS STRING), 2, '0')) AS `fpsl_position`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 09:00:00') AS `snapshot_timestamp`,
    concat('SOURCE_FILE_', lpad(CAST(idx AS STRING), 2, '0')) AS `source_file`,
    date_add(DATE '2026-01-01', idx - 1) AS `DATE_OF_DATA`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Source: "DQP_LANDING"."dbo"."APEX_onboarding_status"
CREATE TABLE IF NOT EXISTS apex.default.apex_onboarding_status (
    `id` BIGINT,
    `cif` STRING,
    `partnerUserId` BIGINT,
    `status` STRING,
    `partnerAccountId` BIGINT,
    `createdAt` STRING,
    `updatedAt` STRING,
    `partnerFileUploadId` BIGINT,
    `failureReason` STRING,
    `failures` STRING,
    `brokerAccountId` BIGINT,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE apex.default.apex_onboarding_status IS 
'The table contains information related to the onboarding status of partners in the system. It tracks various aspects such as the current status of onboarding, timestamps for when records were created and updated, and any failure reasons that may arise during the process. This data can be useful for monitoring the progress of partner onboarding, identifying bottlenecks, and analyzing patterns in onboarding success or failure.';

TRUNCATE TABLE apex.default.apex_onboarding_status;

INSERT INTO apex.default.apex_onboarding_status (
    `id`, `cif`, `partnerUserId`, `status`, `partnerAccountId`, `createdAt`,
    `updatedAt`, `partnerFileUploadId`, `failureReason`, `failures`, `brokerAccountId`, `AsOfDate`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `id`,
    concat('CIF_', lpad(CAST(idx AS STRING), 2, '0')) AS `cif`,
    idx AS `partnerUserId`,
    concat('STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `status`,
    idx AS `partnerAccountId`,
    concat('CREATEDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `createdAt`,
    concat('UPDATEDAT_', lpad(CAST(idx AS STRING), 2, '0')) AS `updatedAt`,
    idx AS `partnerFileUploadId`,
    concat('FAILUREREASON_', lpad(CAST(idx AS STRING), 2, '0')) AS `failureReason`,
    concat('FAILURES_', lpad(CAST(idx AS STRING), 2, '0')) AS `failures`,
    idx AS `brokerAccountId`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

SELECT 'apex_daily_accounts' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_daily_accounts
UNION ALL
SELECT 'apex_daily_activities' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_daily_activities
UNION ALL
SELECT 'apex_daily_overnight_balances' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_daily_overnight_balances
UNION ALL
SELECT 'apex_daily_positions' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_daily_positions
UNION ALL
SELECT 'apex_daily_stock_record' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_daily_stock_record
UNION ALL
SELECT 'apex_onboarding_status' AS table_name, COUNT(*) AS record_count
FROM apex.default.apex_onboarding_status;
