-- Databricks SQL for source: jh_ddpost
-- Generated from sqlserver_brz/brz-jh_ddpost.ms.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_DDPOST"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_ddpost (
    `RECID2` STRING,
    `PGRCOD` STRING,
    `BRANCH` INT,
    `ACCTNO` INT,
    `ACTYPE` INT,
    `GLCOST` INT,
    `GLPROD` INT,
    `YBAL` DECIMAL(38,10),
    `CBAL` DECIMAL(38,10),
    `NEWACT` STRING,
    `ACTIVE` STRING,
    `SCCODE` STRING,
    `STATUS` STRING,
    `NSFN` STRING,
    `NSF` STRING,
    `ODN` STRING,
    `OD` STRING,
    `SWEEPN` STRING,
    `SWEEP` STRING,
    `STOPN` STRING,
    `STOP` STRING,
    `ATMN` STRING,
    `ATM` STRING,
    `EAAN` STRING,
    `EAA` STRING,
    `CHGRN` DECIMAL(38,10),
    `CHGR` DECIMAL(38,10),
    `BCKDN` STRING,
    `BCKD` STRING,
    `BCKCN` STRING,
    `BCKC` STRING,
    `CFEEN` DECIMAL(38,10),
    `CFEE` DECIMAL(38,10),
    `EXCGN` STRING,
    `EXCG` STRING,
    `CHG1N` DECIMAL(38,10),
    `CHG1` DECIMAL(38,10),
    `CHG2N` DECIMAL(38,10),
    `CHG2` DECIMAL(38,10),
    `CHG3N` DECIMAL(38,10),
    `CHG3` DECIMAL(38,10),
    `CHG4N` DECIMAL(38,10),
    `CHG4` DECIMAL(38,10),
    `CHG5N` DECIMAL(38,10),
    `CHG5` DECIMAL(38,10),
    `TELN` STRING,
    `TEL` STRING,
    `BEGACC` STRING,
    `TODACR` STRING,
    `ACCR92` STRING,
    `BEGYTD` DECIMAL(38,10),
    `CKAMT` DECIMAL(38,10),
    `INTPD` DECIMAL(38,10),
    `INTDEP` DECIMAL(38,10),
    `INTTRO` DECIMAL(38,10),
    `INTTRI` DECIMAL(38,10),
    `YTDINT` DECIMAL(38,10),
    `DD500N` STRING,
    `DD500` STRING,
    `DD501N` STRING,
    `DD501` STRING,
    `DD502N` STRING,
    `DD502` STRING,
    `DD503N` STRING,
    `DD503` STRING,
    `DD998N` STRING,
    `DD998` STRING,
    `DD999N` STRING,
    `DD999` STRING,
    `NOBCRP` STRING,
    `AMBCRP` STRING,
    `NOBCRU` STRING,
    `AMBCRU` STRING,
    `NOBDRP` STRING,
    `AMBDRP` STRING,
    `NOBDRU` STRING,
    `AMBDRU` STRING,
    `NOCCRP` STRING,
    `AMCCRP` STRING,
    `CLSCKN` STRING,
    `CLSCK` STRING,
    `CLSDPN` STRING,
    `CLSDP` STRING,
    `CLSOTN` STRING,
    `CLSOT` STRING,
    `CLSCDN` STRING,
    `CLSCD` STRING,
    `NOICRP` STRING,
    `AMICRP` STRING,
    `NOICRU` STRING,
    `AMICRU` STRING,
    `NOIDRP` STRING,
    `AMIDRP` STRING,
    `NOIDRU` STRING,
    `AMIDRU` STRING,
    `NOYCRP` STRING,
    `AMYCRP` STRING,
    `NOYCRU` STRING,
    `AMYCRU` STRING,
    `NOYDRP` STRING,
    `AMYDRP` STRING,
    `NOYDRU` STRING,
    `AMYDRU` STRING,
    `NOWCRP` STRING,
    `AMWCRP` STRING,
    `NOWCRU` STRING,
    `AMWCRU` STRING,
    `NOWDRP` STRING,
    `AMWDRP` STRING,
    `NOWDRU` STRING,
    `AMWDRU` STRING,
    `NOSCRP` STRING,
    `AMSCRP` STRING,
    `NOSCRU` STRING,
    `AMSCRU` STRING,
    `NOSDRP` STRING,
    `AMSDRP` STRING,
    `NOSDRU` STRING,
    `AMSDRU` STRING,
    `NOCCRU` STRING,
    `AMCCRU` STRING,
    `NOCDRU` STRING,
    `AMCDRU` STRING,
    `NOGCRP` STRING,
    `AMGCRP` STRING,
    `NOGDRP` STRING,
    `AMGDRP` STRING,
    `AMSCRE` STRING,
    `NOSCRE` STRING,
    `AMSDRE` STRING,
    `NOSDRE` STRING,
    `INDROP` STRING,
    `INBACK` STRING,
    `SERCHG` DECIMAL(38,10),
    `WAVCHG` DECIMAL(38,10),
    `SAVCHG` DECIMAL(38,10),
    `FEDWH` STRING,
    `STAWH` STRING,
    `BEGFWH` STRING,
    `BEGSWH` STRING,
    `WHYTD` DECIMAL(38,10),
    `WHSYTD` DECIMAL(38,10),
    `TAX` DECIMAL(38,10),
    `TAXCD` DECIMAL(38,10),
    `AUTP__CS` STRING,
    `ODPAMT` DECIMAL(38,10),
    `OBEGAC` STRING,
    `OTODAC` STRING,
    `OACCR9` STRING,
    `OINTPD` DECIMAL(38,10),
    `OINDRO` STRING,
    `CODCG` STRING,
    `BILCHGSN` DECIMAL(38,10),
    `BILCHGS` DECIMAL(38,10),
    `BILPMTSN` STRING,
    `BILPMTS` STRING,
    `BILWAIVN` STRING,
    `BILWAIV` STRING,
    `BILREVRN` STRING,
    `BILREVR` STRING,
    `PSCYCCHGN` DECIMAL(38,10),
    `PSCYCCHG` DECIMAL(38,10),
    `PSSTMCHGN` DECIMAL(38,10),
    `PSSTMCHG` DECIMAL(38,10),
    `DD045` STRING,
    `DD045N` STRING,
    `DD197` STRING,
    `DD197N` STRING,
    `DD198` STRING,
    `DD198N` STRING,
    `DD199` STRING,
    `DD199N` STRING,
    `DD093` STRING,
    `DD093N` STRING,
    `DD083` STRING,
    `DD083N` STRING,
    `DD094` STRING,
    `DD094N` STRING,
    `DD095` STRING,
    `DD095N` STRING,
    `DD096` STRING,
    `DD096N` STRING,
    `DD097` STRING,
    `DD097N` STRING,
    `DD103` STRING,
    `DD103N` STRING,
    `DD104` STRING,
    `DD104N` STRING,
    `DD105` STRING,
    `DD105N` STRING,
    `DD106` STRING,
    `DD106N` STRING,
    `DD107` STRING,
    `DD107N` STRING,
    `DD108` STRING,
    `DD108N` STRING,
    `DD109` STRING,
    `DD109N` STRING,
    `DD110` STRING,
    `DD110N` STRING,
    `DD111` STRING,
    `DD111N` STRING,
    `DD112` STRING,
    `DD112N` STRING,
    `DD113` STRING,
    `DD113N` STRING,
    `DD114` STRING,
    `DD114N` STRING,
    `DD115` STRING,
    `DD115N` STRING,
    `DD116` STRING,
    `DD116N` STRING,
    `DD117` STRING,
    `DD117N` STRING,
    `DD118` STRING,
    `DD118N` STRING,
    `DD119` STRING,
    `DD119N` STRING,
    `DD120` STRING,
    `DD120N` STRING,
    `DD121` STRING,
    `DD121N` STRING,
    `DD122` STRING,
    `DD122N` STRING,
    `DD123` STRING,
    `DD123N` STRING,
    `DD124` STRING,
    `DD124N` STRING,
    `DD125` STRING,
    `DD125N` STRING,
    `DD126` STRING,
    `DD126N` STRING,
    `DD127` STRING,
    `DD127N` STRING,
    `DD128` STRING,
    `DD128N` STRING,
    `DD129` STRING,
    `DD129N` STRING,
    `DD130` STRING,
    `DD130N` STRING,
    `DD131` STRING,
    `DD131N` STRING,
    `DD132` STRING,
    `DD132N` STRING,
    `DD133` STRING,
    `DD133N` STRING,
    `DD134` STRING,
    `DD134N` STRING,
    `DD135` STRING,
    `DD135N` STRING,
    `DD136` STRING,
    `DD136N` STRING,
    `DD137` STRING,
    `DD137N` STRING,
    `DD138` STRING,
    `DD138N` STRING,
    `DD139` STRING,
    `DD139N` STRING,
    `DD140` STRING,
    `DD140N` STRING,
    `DD141` STRING,
    `DD141N` STRING,
    `DD142` STRING,
    `DD142N` STRING,
    `DD143` STRING,
    `DD143N` STRING,
    `DD144` STRING,
    `DD144N` STRING,
    `DD145` STRING,
    `DD145N` STRING,
    `DD146` STRING,
    `DD146N` STRING,
    `DD147` STRING,
    `DD147N` STRING,
    `DD148` STRING,
    `DD148N` STRING,
    `DD149` STRING,
    `DD149N` STRING,
    `DD150` STRING,
    `DD150N` STRING,
    `DD151` STRING,
    `DD151N` STRING,
    `DD152` STRING,
    `DD152N` STRING,
    `DD153` STRING,
    `DD153N` STRING,
    `DD154` STRING,
    `DD154N` STRING,
    `DD160` STRING,
    `DD160N` STRING,
    `DD161` STRING,
    `DD161N` STRING,
    `DD162` STRING,
    `DD162N` STRING,
    `DD163` STRING,
    `DD163N` STRING,
    `DD164` STRING,
    `DD164N` STRING,
    `DD165` STRING,
    `DD165N` STRING,
    `DD166` STRING,
    `DD166N` STRING,
    `DD167` STRING,
    `DD167N` STRING,
    `DD168` STRING,
    `DD168N` STRING,
    `DD169` STRING,
    `DD169N` STRING,
    `DD170` STRING,
    `DD170N` STRING,
    `DD171` STRING,
    `DD171N` STRING,
    `DD172` STRING,
    `DD172N` STRING,
    `DD173` STRING,
    `DD173N` STRING,
    `DD174` STRING,
    `DD174N` STRING,
    `DD175` STRING,
    `DD175N` STRING,
    `DD176` STRING,
    `DD176N` STRING,
    `DD177` STRING,
    `DD177N` STRING,
    `DD178` STRING,
    `DD178N` STRING,
    `DD179` STRING,
    `DD179N` STRING,
    `BEGCOBAL` DECIMAL(38,10),
    `BEGCONSF` STRING,
    `BEGCOSC` STRING,
    `BEGCOOD` STRING,
    `BEGCOUCF` STRING,
    `DD266` STRING,
    `DD266N` STRING,
    `DD267` STRING,
    `DD267N` STRING,
    `DD268` STRING,
    `DD268N` STRING,
    `DD269` STRING,
    `DD269N` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_ddpost IS
'The JH DDPOST landing table captures demand deposit posting activity, including account identifiers, transaction codes, amounts, effective dates, and posting metadata for reconciliation and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_ddpost;

INSERT INTO landing_jh.default.jh_ddpost (
    `RECID2`, `PGRCOD`, `BRANCH`, `ACCTNO`, `ACTYPE`, `GLCOST`,
    `GLPROD`, `YBAL`, `CBAL`, `NEWACT`, `ACTIVE`, `SCCODE`,
    `STATUS`, `NSFN`, `NSF`, `ODN`, `OD`, `SWEEPN`,
    `SWEEP`, `STOPN`, `STOP`, `ATMN`, `ATM`, `EAAN`,
    `EAA`, `CHGRN`, `CHGR`, `BCKDN`, `BCKD`, `BCKCN`,
    `BCKC`, `CFEEN`, `CFEE`, `EXCGN`, `EXCG`, `CHG1N`,
    `CHG1`, `CHG2N`, `CHG2`, `CHG3N`, `CHG3`, `CHG4N`,
    `CHG4`, `CHG5N`, `CHG5`, `TELN`, `TEL`, `BEGACC`,
    `TODACR`, `ACCR92`, `BEGYTD`, `CKAMT`, `INTPD`, `INTDEP`,
    `INTTRO`, `INTTRI`, `YTDINT`, `DD500N`, `DD500`, `DD501N`,
    `DD501`, `DD502N`, `DD502`, `DD503N`, `DD503`, `DD998N`,
    `DD998`, `DD999N`, `DD999`, `NOBCRP`, `AMBCRP`, `NOBCRU`,
    `AMBCRU`, `NOBDRP`, `AMBDRP`, `NOBDRU`, `AMBDRU`, `NOCCRP`,
    `AMCCRP`, `CLSCKN`, `CLSCK`, `CLSDPN`, `CLSDP`, `CLSOTN`,
    `CLSOT`, `CLSCDN`, `CLSCD`, `NOICRP`, `AMICRP`, `NOICRU`,
    `AMICRU`, `NOIDRP`, `AMIDRP`, `NOIDRU`, `AMIDRU`, `NOYCRP`,
    `AMYCRP`, `NOYCRU`, `AMYCRU`, `NOYDRP`, `AMYDRP`, `NOYDRU`,
    `AMYDRU`, `NOWCRP`, `AMWCRP`, `NOWCRU`, `AMWCRU`, `NOWDRP`,
    `AMWDRP`, `NOWDRU`, `AMWDRU`, `NOSCRP`, `AMSCRP`, `NOSCRU`,
    `AMSCRU`, `NOSDRP`, `AMSDRP`, `NOSDRU`, `AMSDRU`, `NOCCRU`,
    `AMCCRU`, `NOCDRU`, `AMCDRU`, `NOGCRP`, `AMGCRP`, `NOGDRP`,
    `AMGDRP`, `AMSCRE`, `NOSCRE`, `AMSDRE`, `NOSDRE`, `INDROP`,
    `INBACK`, `SERCHG`, `WAVCHG`, `SAVCHG`, `FEDWH`, `STAWH`,
    `BEGFWH`, `BEGSWH`, `WHYTD`, `WHSYTD`, `TAX`, `TAXCD`,
    `AUTP__CS`, `ODPAMT`, `OBEGAC`, `OTODAC`, `OACCR9`, `OINTPD`,
    `OINDRO`, `CODCG`, `BILCHGSN`, `BILCHGS`, `BILPMTSN`, `BILPMTS`,
    `BILWAIVN`, `BILWAIV`, `BILREVRN`, `BILREVR`, `PSCYCCHGN`, `PSCYCCHG`,
    `PSSTMCHGN`, `PSSTMCHG`, `DD045`, `DD045N`, `DD197`, `DD197N`,
    `DD198`, `DD198N`, `DD199`, `DD199N`, `DD093`, `DD093N`,
    `DD083`, `DD083N`, `DD094`, `DD094N`, `DD095`, `DD095N`,
    `DD096`, `DD096N`, `DD097`, `DD097N`, `DD103`, `DD103N`,
    `DD104`, `DD104N`, `DD105`, `DD105N`, `DD106`, `DD106N`,
    `DD107`, `DD107N`, `DD108`, `DD108N`, `DD109`, `DD109N`,
    `DD110`, `DD110N`, `DD111`, `DD111N`, `DD112`, `DD112N`,
    `DD113`, `DD113N`, `DD114`, `DD114N`, `DD115`, `DD115N`,
    `DD116`, `DD116N`, `DD117`, `DD117N`, `DD118`, `DD118N`,
    `DD119`, `DD119N`, `DD120`, `DD120N`, `DD121`, `DD121N`,
    `DD122`, `DD122N`, `DD123`, `DD123N`, `DD124`, `DD124N`,
    `DD125`, `DD125N`, `DD126`, `DD126N`, `DD127`, `DD127N`,
    `DD128`, `DD128N`, `DD129`, `DD129N`, `DD130`, `DD130N`,
    `DD131`, `DD131N`, `DD132`, `DD132N`, `DD133`, `DD133N`,
    `DD134`, `DD134N`, `DD135`, `DD135N`, `DD136`, `DD136N`,
    `DD137`, `DD137N`, `DD138`, `DD138N`, `DD139`, `DD139N`,
    `DD140`, `DD140N`, `DD141`, `DD141N`, `DD142`, `DD142N`,
    `DD143`, `DD143N`, `DD144`, `DD144N`, `DD145`, `DD145N`,
    `DD146`, `DD146N`, `DD147`, `DD147N`, `DD148`, `DD148N`,
    `DD149`, `DD149N`, `DD150`, `DD150N`, `DD151`, `DD151N`,
    `DD152`, `DD152N`, `DD153`, `DD153N`, `DD154`, `DD154N`,
    `DD160`, `DD160N`, `DD161`, `DD161N`, `DD162`, `DD162N`,
    `DD163`, `DD163N`, `DD164`, `DD164N`, `DD165`, `DD165N`,
    `DD166`, `DD166N`, `DD167`, `DD167N`, `DD168`, `DD168N`,
    `DD169`, `DD169N`, `DD170`, `DD170N`, `DD171`, `DD171N`,
    `DD172`, `DD172N`, `DD173`, `DD173N`, `DD174`, `DD174N`,
    `DD175`, `DD175N`, `DD176`, `DD176N`, `DD177`, `DD177N`,
    `DD178`, `DD178N`, `DD179`, `DD179N`, `BEGCOBAL`, `BEGCONSF`,
    `BEGCOSC`, `BEGCOOD`, `BEGCOUCF`, `DD266`, `DD266N`, `DD267`,
    `DD267N`, `DD268`, `DD268N`, `DD269`, `DD269N`, `AsOfDate`,
    `YEARMONTH`, `LOADED_AT`
)
SELECT
    concat('RECID2_', lpad(CAST(idx AS STRING), 2, '0')) AS `RECID2`,
    concat('PGRCOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `PGRCOD`,
    idx AS `BRANCH`,
    idx AS `ACCTNO`,
    idx AS `ACTYPE`,
    idx AS `GLCOST`,
    idx AS `GLPROD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YBAL`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CBAL`,
    concat('NEWACT_', lpad(CAST(idx AS STRING), 2, '0')) AS `NEWACT`,
    concat('ACTIVE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTIVE`,
    concat('SCCODE_', lpad(CAST(idx AS STRING), 2, '0')) AS `SCCODE`,
    concat('STATUS_', lpad(CAST(idx AS STRING), 2, '0')) AS `STATUS`,
    concat('NSFN_', lpad(CAST(idx AS STRING), 2, '0')) AS `NSFN`,
    concat('NSF_', lpad(CAST(idx AS STRING), 2, '0')) AS `NSF`,
    concat('ODN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ODN`,
    concat('OD_', lpad(CAST(idx AS STRING), 2, '0')) AS `OD`,
    concat('SWEEPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `SWEEPN`,
    concat('SWEEP_', lpad(CAST(idx AS STRING), 2, '0')) AS `SWEEP`,
    concat('STOPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `STOPN`,
    concat('STOP_', lpad(CAST(idx AS STRING), 2, '0')) AS `STOP`,
    concat('ATMN_', lpad(CAST(idx AS STRING), 2, '0')) AS `ATMN`,
    concat('ATM_', lpad(CAST(idx AS STRING), 2, '0')) AS `ATM`,
    concat('EAAN_', lpad(CAST(idx AS STRING), 2, '0')) AS `EAAN`,
    concat('EAA_', lpad(CAST(idx AS STRING), 2, '0')) AS `EAA`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHGRN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHGR`,
    concat('BCKDN_', lpad(CAST(idx AS STRING), 2, '0')) AS `BCKDN`,
    concat('BCKD_', lpad(CAST(idx AS STRING), 2, '0')) AS `BCKD`,
    concat('BCKCN_', lpad(CAST(idx AS STRING), 2, '0')) AS `BCKCN`,
    concat('BCKC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BCKC`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CFEEN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CFEE`,
    concat('EXCGN_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXCGN`,
    concat('EXCG_', lpad(CAST(idx AS STRING), 2, '0')) AS `EXCG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG1N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG2N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG3N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG4N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG5N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CHG5`,
    concat('TELN_', lpad(CAST(idx AS STRING), 2, '0')) AS `TELN`,
    concat('TEL_', lpad(CAST(idx AS STRING), 2, '0')) AS `TEL`,
    concat('BEGACC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGACC`,
    concat('TODACR_', lpad(CAST(idx AS STRING), 2, '0')) AS `TODACR`,
    concat('ACCR92_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACCR92`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BEGYTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `CKAMT`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTPD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTDEP`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTTRO`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `INTTRI`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `YTDINT`,
    concat('DD500N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD500N`,
    concat('DD500_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD500`,
    concat('DD501N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD501N`,
    concat('DD501_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD501`,
    concat('DD502N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD502N`,
    concat('DD502_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD502`,
    concat('DD503N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD503N`,
    concat('DD503_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD503`,
    concat('DD998N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD998N`,
    concat('DD998_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD998`,
    concat('DD999N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD999N`,
    concat('DD999_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD999`,
    concat('NOBCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOBCRP`,
    concat('AMBCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMBCRP`,
    concat('NOBCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOBCRU`,
    concat('AMBCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMBCRU`,
    concat('NOBDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOBDRP`,
    concat('AMBDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMBDRP`,
    concat('NOBDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOBDRU`,
    concat('AMBDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMBDRU`,
    concat('NOCCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOCCRP`,
    concat('AMCCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMCCRP`,
    concat('CLSCKN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSCKN`,
    concat('CLSCK_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSCK`,
    concat('CLSDPN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSDPN`,
    concat('CLSDP_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSDP`,
    concat('CLSOTN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSOTN`,
    concat('CLSOT_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSOT`,
    concat('CLSCDN_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSCDN`,
    concat('CLSCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `CLSCD`,
    concat('NOICRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOICRP`,
    concat('AMICRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMICRP`,
    concat('NOICRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOICRU`,
    concat('AMICRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMICRU`,
    concat('NOIDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOIDRP`,
    concat('AMIDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMIDRP`,
    concat('NOIDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOIDRU`,
    concat('AMIDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMIDRU`,
    concat('NOYCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOYCRP`,
    concat('AMYCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMYCRP`,
    concat('NOYCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOYCRU`,
    concat('AMYCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMYCRU`,
    concat('NOYDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOYDRP`,
    concat('AMYDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMYDRP`,
    concat('NOYDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOYDRU`,
    concat('AMYDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMYDRU`,
    concat('NOWCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOWCRP`,
    concat('AMWCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMWCRP`,
    concat('NOWCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOWCRU`,
    concat('AMWCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMWCRU`,
    concat('NOWDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOWDRP`,
    concat('AMWDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMWDRP`,
    concat('NOWDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOWDRU`,
    concat('AMWDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMWDRU`,
    concat('NOSCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSCRP`,
    concat('AMSCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSCRP`,
    concat('NOSCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSCRU`,
    concat('AMSCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSCRU`,
    concat('NOSDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSDRP`,
    concat('AMSDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSDRP`,
    concat('NOSDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSDRU`,
    concat('AMSDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSDRU`,
    concat('NOCCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOCCRU`,
    concat('AMCCRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMCCRU`,
    concat('NOCDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOCDRU`,
    concat('AMCDRU_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMCDRU`,
    concat('NOGCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOGCRP`,
    concat('AMGCRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMGCRP`,
    concat('NOGDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOGDRP`,
    concat('AMGDRP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMGDRP`,
    concat('AMSCRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSCRE`,
    concat('NOSCRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSCRE`,
    concat('AMSDRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AMSDRE`,
    concat('NOSDRE_', lpad(CAST(idx AS STRING), 2, '0')) AS `NOSDRE`,
    concat('INDROP_', lpad(CAST(idx AS STRING), 2, '0')) AS `INDROP`,
    concat('INBACK_', lpad(CAST(idx AS STRING), 2, '0')) AS `INBACK`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SERCHG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WAVCHG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `SAVCHG`,
    concat('FEDWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `FEDWH`,
    concat('STAWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `STAWH`,
    concat('BEGFWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGFWH`,
    concat('BEGSWH_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGSWH`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHYTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `WHSYTD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TAX`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `TAXCD`,
    concat('AUTP__CS_', lpad(CAST(idx AS STRING), 2, '0')) AS `AUTP__CS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `ODPAMT`,
    concat('OBEGAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OBEGAC`,
    concat('OTODAC_', lpad(CAST(idx AS STRING), 2, '0')) AS `OTODAC`,
    concat('OACCR9_', lpad(CAST(idx AS STRING), 2, '0')) AS `OACCR9`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `OINTPD`,
    concat('OINDRO_', lpad(CAST(idx AS STRING), 2, '0')) AS `OINDRO`,
    concat('CODCG_', lpad(CAST(idx AS STRING), 2, '0')) AS `CODCG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BILCHGSN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BILCHGS`,
    concat('BILPMTSN_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILPMTSN`,
    concat('BILPMTS_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILPMTS`,
    concat('BILWAIVN_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILWAIVN`,
    concat('BILWAIV_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILWAIV`,
    concat('BILREVRN_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILREVRN`,
    concat('BILREVR_', lpad(CAST(idx AS STRING), 2, '0')) AS `BILREVR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSCYCCHGN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSCYCCHG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSSTMCHGN`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `PSSTMCHG`,
    concat('DD045_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD045`,
    concat('DD045N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD045N`,
    concat('DD197_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD197`,
    concat('DD197N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD197N`,
    concat('DD198_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD198`,
    concat('DD198N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD198N`,
    concat('DD199_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD199`,
    concat('DD199N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD199N`,
    concat('DD093_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD093`,
    concat('DD093N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD093N`,
    concat('DD083_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD083`,
    concat('DD083N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD083N`,
    concat('DD094_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD094`,
    concat('DD094N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD094N`,
    concat('DD095_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD095`,
    concat('DD095N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD095N`,
    concat('DD096_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD096`,
    concat('DD096N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD096N`,
    concat('DD097_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD097`,
    concat('DD097N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD097N`,
    concat('DD103_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD103`,
    concat('DD103N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD103N`,
    concat('DD104_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD104`,
    concat('DD104N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD104N`,
    concat('DD105_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD105`,
    concat('DD105N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD105N`,
    concat('DD106_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD106`,
    concat('DD106N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD106N`,
    concat('DD107_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD107`,
    concat('DD107N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD107N`,
    concat('DD108_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD108`,
    concat('DD108N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD108N`,
    concat('DD109_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD109`,
    concat('DD109N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD109N`,
    concat('DD110_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD110`,
    concat('DD110N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD110N`,
    concat('DD111_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD111`,
    concat('DD111N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD111N`,
    concat('DD112_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD112`,
    concat('DD112N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD112N`,
    concat('DD113_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD113`,
    concat('DD113N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD113N`,
    concat('DD114_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD114`,
    concat('DD114N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD114N`,
    concat('DD115_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD115`,
    concat('DD115N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD115N`,
    concat('DD116_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD116`,
    concat('DD116N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD116N`,
    concat('DD117_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD117`,
    concat('DD117N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD117N`,
    concat('DD118_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD118`,
    concat('DD118N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD118N`,
    concat('DD119_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD119`,
    concat('DD119N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD119N`,
    concat('DD120_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD120`,
    concat('DD120N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD120N`,
    concat('DD121_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD121`,
    concat('DD121N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD121N`,
    concat('DD122_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD122`,
    concat('DD122N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD122N`,
    concat('DD123_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD123`,
    concat('DD123N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD123N`,
    concat('DD124_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD124`,
    concat('DD124N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD124N`,
    concat('DD125_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD125`,
    concat('DD125N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD125N`,
    concat('DD126_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD126`,
    concat('DD126N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD126N`,
    concat('DD127_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD127`,
    concat('DD127N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD127N`,
    concat('DD128_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD128`,
    concat('DD128N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD128N`,
    concat('DD129_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD129`,
    concat('DD129N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD129N`,
    concat('DD130_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD130`,
    concat('DD130N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD130N`,
    concat('DD131_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD131`,
    concat('DD131N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD131N`,
    concat('DD132_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD132`,
    concat('DD132N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD132N`,
    concat('DD133_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD133`,
    concat('DD133N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD133N`,
    concat('DD134_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD134`,
    concat('DD134N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD134N`,
    concat('DD135_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD135`,
    concat('DD135N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD135N`,
    concat('DD136_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD136`,
    concat('DD136N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD136N`,
    concat('DD137_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD137`,
    concat('DD137N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD137N`,
    concat('DD138_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD138`,
    concat('DD138N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD138N`,
    concat('DD139_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD139`,
    concat('DD139N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD139N`,
    concat('DD140_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD140`,
    concat('DD140N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD140N`,
    concat('DD141_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD141`,
    concat('DD141N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD141N`,
    concat('DD142_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD142`,
    concat('DD142N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD142N`,
    concat('DD143_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD143`,
    concat('DD143N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD143N`,
    concat('DD144_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD144`,
    concat('DD144N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD144N`,
    concat('DD145_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD145`,
    concat('DD145N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD145N`,
    concat('DD146_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD146`,
    concat('DD146N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD146N`,
    concat('DD147_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD147`,
    concat('DD147N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD147N`,
    concat('DD148_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD148`,
    concat('DD148N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD148N`,
    concat('DD149_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD149`,
    concat('DD149N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD149N`,
    concat('DD150_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD150`,
    concat('DD150N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD150N`,
    concat('DD151_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD151`,
    concat('DD151N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD151N`,
    concat('DD152_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD152`,
    concat('DD152N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD152N`,
    concat('DD153_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD153`,
    concat('DD153N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD153N`,
    concat('DD154_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD154`,
    concat('DD154N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD154N`,
    concat('DD160_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD160`,
    concat('DD160N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD160N`,
    concat('DD161_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD161`,
    concat('DD161N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD161N`,
    concat('DD162_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD162`,
    concat('DD162N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD162N`,
    concat('DD163_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD163`,
    concat('DD163N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD163N`,
    concat('DD164_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD164`,
    concat('DD164N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD164N`,
    concat('DD165_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD165`,
    concat('DD165N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD165N`,
    concat('DD166_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD166`,
    concat('DD166N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD166N`,
    concat('DD167_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD167`,
    concat('DD167N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD167N`,
    concat('DD168_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD168`,
    concat('DD168N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD168N`,
    concat('DD169_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD169`,
    concat('DD169N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD169N`,
    concat('DD170_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD170`,
    concat('DD170N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD170N`,
    concat('DD171_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD171`,
    concat('DD171N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD171N`,
    concat('DD172_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD172`,
    concat('DD172N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD172N`,
    concat('DD173_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD173`,
    concat('DD173N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD173N`,
    concat('DD174_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD174`,
    concat('DD174N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD174N`,
    concat('DD175_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD175`,
    concat('DD175N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD175N`,
    concat('DD176_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD176`,
    concat('DD176N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD176N`,
    concat('DD177_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD177`,
    concat('DD177N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD177N`,
    concat('DD178_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD178`,
    concat('DD178N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD178N`,
    concat('DD179_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD179`,
    concat('DD179N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD179N`,
    TRY_CAST(idx * 100.25 AS DECIMAL(38,10)) AS `BEGCOBAL`,
    concat('BEGCONSF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGCONSF`,
    concat('BEGCOSC_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGCOSC`,
    concat('BEGCOOD_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGCOOD`,
    concat('BEGCOUCF_', lpad(CAST(idx AS STRING), 2, '0')) AS `BEGCOUCF`,
    concat('DD266_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD266`,
    concat('DD266N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD266N`,
    concat('DD267_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD267`,
    concat('DD267N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD267N`,
    concat('DD268_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD268`,
    concat('DD268N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD268N`,
    concat('DD269_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD269`,
    concat('DD269N_', lpad(CAST(idx AS STRING), 2, '0')) AS `DD269N`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_ddpost' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_ddpost;
