-- Databricks SQL for source: jh_ddaams
-- Generated from sqlserver/brz-jh_ddaams.sql

CREATE CATALOG IF NOT EXISTS landing_jh;
USE CATALOG landing_jh;

CREATE SCHEMA IF NOT EXISTS default;
USE SCHEMA default;

-- Source: "DQP_LANDING"."dbo"."JH_DDAAMS"
CREATE TABLE IF NOT EXISTS landing_jh.default.jh_ddaams (
    `AABR` INT,
    `ACCTNO` BIGINT,
    `ACTYPE` STRING,
    `AGRPCD` STRING,
    `AASNAM` STRING,
    `AATYPE` STRING,
    `ACYCLE` INT,
    `ACFREQ` INT,
    `ACFRCD` STRING,
    `AOFFCR` STRING,
    `ADTLA6` INT,
    `ADTLA7` INT,
    `ADTNA6` INT,
    `ADTNA7` INT,
    `ALOSS` STRING,
    `ACGACT` BIGINT,
    `AGROUP` BIGINT,
    `AANAPLAN` INT,
    `AASTATUS` INT,
    `AFORM` STRING,
    `AREPT` STRING,
    `ACOVR` INT,
    `ACOMP` DECIMAL(11,2),
    `AAUSER` STRING,
    `AAGGDY` INT,
    `AAGGAM` DECIMAL(15,2),
    `AAGGCO` DECIMAL(15,2),
    `AAGDYH` INT,
    `AAGAMH` DECIMAL(15,2),
    `AAGCOH` DECIMAL(15,2),
    `ANODR` INT,
    `ANOCR` INT,
    `AONUS` INT,
    `ATRNS1` INT,
    `ATRNS2` INT,
    `ATRNS3` INT,
    `ATRNS4` INT,
    `ATRNS5` INT,
    `ASERCG` DECIMAL(9,2),
    `AINTPD` DECIMAL(13,2),
    `AODINT` DECIMAL(13,5),
    `ASTOPS` INT,
    `ASTMTR` INT,
    `ASTMTS` INT,
    `ASTMTT` INT,
    `AINQ` INT,
    `AABILN` STRING,
    `AADUED` INT,
    `AAGGCOPOS` DECIMAL(15,2),
    `AAGGCONEG` DECIMAL(15,2),
    `AAGGDYPOS` INT,
    `AAGGDYNEG` INT,
    `AAGDYHPOS` INT,
    `AAGDYHNEG` INT,
    `AAGCOHPOS` DECIMAL(15,2),
    `AAGCOHNEG` DECIMAL(15,2),
    `P2AERATVAR` STRING,
    `P2AERATVCD` STRING,
    `P2AERATFLR` STRING,
    `P2AERATCEI` STRING,
    `P2ANRATVAR` STRING,
    `P2ANRATVCD` STRING,
    `P2ANRATFLR` STRING,
    `P2ANRATCEI` STRING,
    `ASTMTOPT` STRING,
    `ASTMTNT` STRING,
    `ASTMTPRFT` STRING,
    `ASTMTLOSS` STRING,
    `AACLSDT6` INT,
    `AACLSDT7` INT,
    `AACLSCHG` STRING,
    `AAWVEXPDT6` INT,
    `AAWVEXPDT7` INT,
    `AAPRCYEND` STRING,
    `AAPINTEXE` STRING,
    `AAEXETBL1` DECIMAL(13,2),
    `AAEXETRT1` INT,
    `AAEXETBL2` DECIMAL(13,2),
    `AAEXETRT2` INT,
    `AAEXETBL3` DECIMAL(13,2),
    `AAEXETRT3` INT,
    `AAEXETBL4` DECIMAL(13,2),
    `AAEXETRT4` INT,
    `AAEXETBL5` DECIMAL(13,2),
    `AAEXETRT5` INT,
    `AATSU3A1` STRING,
    `AATSU3A2` STRING,
    `AATSU3A3` STRING,
    `AATSU3A4` STRING,
    `AATSU3A5` STRING,
    `AATSUDT1` STRING,
    `AATSUDT2` STRING,
    `AATSUDT3` STRING,
    `AATSUDT4` STRING,
    `AATSUDT5` STRING,
    `AATSUAMT1` DECIMAL(13,2),
    `AATSUAMT2` DECIMAL(13,2),
    `AATSUAMT3` DECIMAL(13,2),
    `AATSUAMT4` DECIMAL(13,2),
    `AATSUAMT5` DECIMAL(13,2),
    `AADSCAMT` DECIMAL(7,2),
    `AADSCPRC` STRING,
    `AADSCEXP` STRING,
    `AsOfDate` DATE,
    `YEARMONTH` INT,
    `LOADED_AT` TIMESTAMP
);
COMMENT ON TABLE landing_jh.default.jh_ddaams IS
'The JH DDAAMS landing table captures demand deposit account analysis and service charge attributes from Jack Henry for account analysis validation, fee review, and downstream processing.';

TRUNCATE TABLE landing_jh.default.jh_ddaams;

INSERT INTO landing_jh.default.jh_ddaams (
    `AABR`, `ACCTNO`, `ACTYPE`, `AGRPCD`, `AASNAM`, `AATYPE`,
    `ACYCLE`, `ACFREQ`, `ACFRCD`, `AOFFCR`, `ADTLA6`, `ADTLA7`,
    `ADTNA6`, `ADTNA7`, `ALOSS`, `ACGACT`, `AGROUP`, `AANAPLAN`,
    `AASTATUS`, `AFORM`, `AREPT`, `ACOVR`, `ACOMP`, `AAUSER`,
    `AAGGDY`, `AAGGAM`, `AAGGCO`, `AAGDYH`, `AAGAMH`, `AAGCOH`,
    `ANODR`, `ANOCR`, `AONUS`, `ATRNS1`, `ATRNS2`, `ATRNS3`,
    `ATRNS4`, `ATRNS5`, `ASERCG`, `AINTPD`, `AODINT`, `ASTOPS`,
    `ASTMTR`, `ASTMTS`, `ASTMTT`, `AINQ`, `AABILN`, `AADUED`,
    `AAGGCOPOS`, `AAGGCONEG`, `AAGGDYPOS`, `AAGGDYNEG`, `AAGDYHPOS`, `AAGDYHNEG`,
    `AAGCOHPOS`, `AAGCOHNEG`, `P2AERATVAR`, `P2AERATVCD`, `P2AERATFLR`, `P2AERATCEI`,
    `P2ANRATVAR`, `P2ANRATVCD`, `P2ANRATFLR`, `P2ANRATCEI`, `ASTMTOPT`, `ASTMTNT`,
    `ASTMTPRFT`, `ASTMTLOSS`, `AACLSDT6`, `AACLSDT7`, `AACLSCHG`, `AAWVEXPDT6`,
    `AAWVEXPDT7`, `AAPRCYEND`, `AAPINTEXE`, `AAEXETBL1`, `AAEXETRT1`, `AAEXETBL2`,
    `AAEXETRT2`, `AAEXETBL3`, `AAEXETRT3`, `AAEXETBL4`, `AAEXETRT4`, `AAEXETBL5`,
    `AAEXETRT5`, `AATSU3A1`, `AATSU3A2`, `AATSU3A3`, `AATSU3A4`, `AATSU3A5`,
    `AATSUDT1`, `AATSUDT2`, `AATSUDT3`, `AATSUDT4`, `AATSUDT5`, `AATSUAMT1`,
    `AATSUAMT2`, `AATSUAMT3`, `AATSUAMT4`, `AATSUAMT5`, `AADSCAMT`, `AADSCPRC`,
    `AADSCEXP`, `AsOfDate`, `YEARMONTH`, `LOADED_AT`
)
SELECT
    idx AS `AABR`,
    idx AS `ACCTNO`,
    concat('ACTYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACTYPE`,
    concat('AGRPCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `AGRPCD`,
    concat('AASNAM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AASNAM`,
    concat('AATYPE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATYPE`,
    idx AS `ACYCLE`,
    idx AS `ACFREQ`,
    concat('ACFRCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `ACFRCD`,
    concat('AOFFCR_', lpad(CAST(idx AS STRING), 2, '0')) AS `AOFFCR`,
    idx AS `ADTLA6`,
    idx AS `ADTLA7`,
    idx AS `ADTNA6`,
    idx AS `ADTNA7`,
    concat('ALOSS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ALOSS`,
    idx AS `ACGACT`,
    idx AS `AGROUP`,
    idx AS `AANAPLAN`,
    idx AS `AASTATUS`,
    concat('AFORM_', lpad(CAST(idx AS STRING), 2, '0')) AS `AFORM`,
    concat('AREPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `AREPT`,
    idx AS `ACOVR`,
    TRY_CAST(idx * 100.25 AS DECIMAL(11,2)) AS `ACOMP`,
    concat('AAUSER_', lpad(CAST(idx AS STRING), 2, '0')) AS `AAUSER`,
    idx AS `AAGGDY`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGGAM`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGGCO`,
    idx AS `AAGDYH`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGAMH`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGCOH`,
    idx AS `ANODR`,
    idx AS `ANOCR`,
    idx AS `AONUS`,
    idx AS `ATRNS1`,
    idx AS `ATRNS2`,
    idx AS `ATRNS3`,
    idx AS `ATRNS4`,
    idx AS `ATRNS5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(9,2)) AS `ASERCG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AINTPD`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,5)) AS `AODINT`,
    idx AS `ASTOPS`,
    idx AS `ASTMTR`,
    idx AS `ASTMTS`,
    idx AS `ASTMTT`,
    idx AS `AINQ`,
    concat('AABILN_', lpad(CAST(idx AS STRING), 2, '0')) AS `AABILN`,
    idx AS `AADUED`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGGCOPOS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGGCONEG`,
    idx AS `AAGGDYPOS`,
    idx AS `AAGGDYNEG`,
    idx AS `AAGDYHPOS`,
    idx AS `AAGDYHNEG`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGCOHPOS`,
    TRY_CAST(idx * 100.25 AS DECIMAL(15,2)) AS `AAGCOHNEG`,
    concat('P2AERATVAR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AERATVAR`,
    concat('P2AERATVCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AERATVCD`,
    concat('P2AERATFLR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AERATFLR`,
    concat('P2AERATCEI_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2AERATCEI`,
    concat('P2ANRATVAR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ANRATVAR`,
    concat('P2ANRATVCD_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ANRATVCD`,
    concat('P2ANRATFLR_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ANRATFLR`,
    concat('P2ANRATCEI_', lpad(CAST(idx AS STRING), 2, '0')) AS `P2ANRATCEI`,
    concat('ASTMTOPT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASTMTOPT`,
    concat('ASTMTNT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASTMTNT`,
    concat('ASTMTPRFT_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASTMTPRFT`,
    concat('ASTMTLOSS_', lpad(CAST(idx AS STRING), 2, '0')) AS `ASTMTLOSS`,
    idx AS `AACLSDT6`,
    idx AS `AACLSDT7`,
    concat('AACLSCHG_', lpad(CAST(idx AS STRING), 2, '0')) AS `AACLSCHG`,
    idx AS `AAWVEXPDT6`,
    idx AS `AAWVEXPDT7`,
    concat('AAPRCYEND_', lpad(CAST(idx AS STRING), 2, '0')) AS `AAPRCYEND`,
    concat('AAPINTEXE_', lpad(CAST(idx AS STRING), 2, '0')) AS `AAPINTEXE`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AAEXETBL1`,
    idx AS `AAEXETRT1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AAEXETBL2`,
    idx AS `AAEXETRT2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AAEXETBL3`,
    idx AS `AAEXETRT3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AAEXETBL4`,
    idx AS `AAEXETRT4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AAEXETBL5`,
    idx AS `AAEXETRT5`,
    concat('AATSU3A1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSU3A1`,
    concat('AATSU3A2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSU3A2`,
    concat('AATSU3A3_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSU3A3`,
    concat('AATSU3A4_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSU3A4`,
    concat('AATSU3A5_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSU3A5`,
    concat('AATSUDT1_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSUDT1`,
    concat('AATSUDT2_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSUDT2`,
    concat('AATSUDT3_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSUDT3`,
    concat('AATSUDT4_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSUDT4`,
    concat('AATSUDT5_', lpad(CAST(idx AS STRING), 2, '0')) AS `AATSUDT5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AATSUAMT1`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AATSUAMT2`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AATSUAMT3`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AATSUAMT4`,
    TRY_CAST(idx * 100.25 AS DECIMAL(13,2)) AS `AATSUAMT5`,
    TRY_CAST(idx * 100.25 AS DECIMAL(7,2)) AS `AADSCAMT`,
    concat('AADSCPRC_', lpad(CAST(idx AS STRING), 2, '0')) AS `AADSCPRC`,
    concat('AADSCEXP_', lpad(CAST(idx AS STRING), 2, '0')) AS `AADSCEXP`,
    date_add(DATE '2026-01-01', idx - 1) AS `AsOfDate`,
    202601 AS `YEARMONTH`,
    timestampadd(DAY, idx - 1, TIMESTAMP '2026-01-01 12:00:00') AS `LOADED_AT`
FROM VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10) AS seed(idx);

-- Row-count verification
SELECT 'jh_ddaams' AS table_name, COUNT(*) AS record_count
FROM landing_jh.default.jh_ddaams;
