-- NAME: BRONZE_JH_DMILAY
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



WITH landing_data AS (
    SELECT
        LOANNO
        ,OLDLOANNO
        ,BILLNAME
        ,BANK
        ,AGGR
        ,NEXTDUE
        ,FIRSTPRINB
        ,ORGMTGAM
        ,LOANDATE
        ,MATDATE
        ,ANNUALIN
        ,LOANTERM
        ,REMTERM
        ,PRODLINECD
        ,ARMIND
        ,ARMINDESC
        ,ORGPROPVAL
        ,PROPVAL
        ,PROPERTYST
        ,PROPERTYCT
        ,PROPSTATE
        ,PROPZIP
        ,SSNCODE
        ,PTFNMACODE
        ,PTFNMADESC
        ,INVESTLOAN
        ,OCCCODE
        ,OCCUDESC
        ,LNPURPCODE
        ,LNPURPDESC
        ,HITYPE
        ,HITYPEDESC
        ,LOTYPE
        ,LOTYPEDESC
        ,FIRSTDUE
        ,FIRSTP
        ,FSTSERFE
        ,FORECLSCOD
        ,FORECLSDES
        ,ORGLT
        ,INTPDTHRU
        ,ESCROWBA
        ,ESCROWAD
        ,PLGCODE
        ,PLGDESC
        ,PMNTPERD
        ,BADCHKTBLE
        ,TIMESDLQ
        ,TOTPMN
        ,NOOFUNIT
        ,INTFLAG
        ,INTFLAGDES
        ,CAPLNFLAG
        ,CAPLNFDESC
        ,MTGRLNAME
        ,MTGRFNAME
        ,MTGRHAZPAY
        ,TIPMN
        ,GUARFE
        ,RECFLAG
        ,RECFLAGDES
        ,POOLNUM
        ,DLQPMNTCNT
        ,IOEFLAG
        ,IOEFLAGDES
        ,MANCODE
        ,BBCODE
        ,BRNCHOFF
        ,ACRLSTAT
        ,PREPMNTIND
        ,FHLBBPP
        ,FSTORGCOS
        ,FSTORIGFE
        ,FSTUNAMOR
        ,ARMIREFFDT
        ,ARMORGI
        ,ARMMARGI
        ,ARMPIEFFDT
        ,ARMCHGPRD
        ,ARMPICHGPR
        ,ARMIRMAXC
        ,ARMIRMAXF
        ,ARMIMAXIN
        ,ARMIMAXDE
        ,AIRMAXLIN
        ,AIRMAXLDE
        ,APIMAXPCT
        ,APIMAXPCD
        ,APIMAXLIF
        ,APIPCTMIN
        ,APIPCTMDE
        ,AORGPIAM
        ,ARMINDE
        ,ARMIRRAT
        ,AOIRCHGDT
        ,AIRRNDTP
        ,AIRRNDDESC
        ,AIRRNDFAC
        ,ARMPLANID
        ,ARMPLANDES
        ,ARMINDCO
        ,ARMINDDESC
        ,AILEADDAYS
        ,USR15POS1
        ,USR2POS1A
        ,USR2POS2A
        ,DFTIND
        ,BANKNAME
        ,LOT
        ,[BLOCK]
        ,SUBDIV
        ,COUNTYCODE
        ,COUNTYTA
        ,HAZMONTHL
        ,LASTANALDT
        ,ESCMINBAL
        ,LASTANALO
        ,OVSHTCHGDT
        ,MORTSSNO
        ,COMORTSSNO
        ,SSNCERTDT
        ,SSNVERCODE
        ,SSNVERDATE
        ,SETUPDATE
        ,SUSPBA
        ,RESTESCBA
        ,CRQUALCODE
        ,INTONLYIND
        ,PAYFULLDT
        ,SERVSOLDDT
        ,COMTGLNAME
        ,COMTGFNAME
        ,FLOZPOS1
        ,MTGRDOB
        ,COMTGRDOB
        ,PROPUNITNO
        ,LTVN
        ,BILLADDR3
        ,BILLADDR4
        ,BILLCITY
        ,BILLSTATE
        ,BILLZIP
        ,ORIGSCORE
        ,BILLADDR2
        ,USR1POS3A
        ,CHGOFFBALN
        ,ACCLATECAN
        ,LATECFN
        ,GRACEDAYS
        ,LCCODE
        ,PHONE
        ,PHONE2
        ,EMAILF
        ,PROCSC
        ,DAIND
        ,CSBORCBC
        ,CSBORCBST
        ,FIRSTFF1N
        ,ASSUMDATE
        ,VACDATE
        ,LNMODDATE
        ,USR20POS1A
        ,RECOVECABN
        ,NONRECCABN
        ,THIRDPRCBN
        ,PENDPIAMTN
        ,ADLCBN1
        ,ADLCSTN1
        ,ADLCBS
        ,ADLCBC
        ,ADLCBST
        ,ADLCBZC
        ,ADLCBPN
        ,LASTFPAYDT
        ,YTDINTAMTN
        ,YTDPPAMTN
        ,YTDTAXAMTN
        ,YTDHAZAMTN
        ,USR1PO4A
        ,DAYDELIQU
        ,ENTERNONAC
        ,LEAVENONAC
        ,APPRAIDATE
        ,LNMOAPPDAT
        ,LNMOAPPAM
        ,CHAROFFDAT
        ,DRROUTRNU
        ,FIORCOSAM
        ,FIORFEEAM
        ,CONVERT(DATETIME, NEXTDUE) AS NextDueDate
        ,CONVERT(DATETIME, LOANDATE) AS OriginalLoanDate
        ,CONVERT(DATETIME, MATDATE) AS MaturityDate
        ,CONVERT(DATETIME, FIRSTDUE) AS FirstDueDate
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
	        FROM dqp_landing.dbo.jh_ddpar1) as AsOfDate
        ,NULL as YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_DMILAY"
),

bronze_data AS (
    SELECT
        LOANNO
        ,OLDLOANNO
        ,BILLNAME
        ,BANK
        ,AGGR
        ,NEXTDUE
        ,FIRSTPRINB
        ,ORGMTGAM
        ,LOANDATE
        ,MATDATE
        ,ANNUALIN
        ,LOANTERM
        ,REMTERM
        ,PRODLINECD
        ,ARMIND
        ,ARMINDESC
        ,ORGPROPVAL
        ,PROPVAL
        ,PROPERTYST
        ,PROPERTYCT
        ,PROPSTATE
        ,PROPZIP
        ,SSNCODE
        ,PTFNMACODE
        ,PTFNMADESC
        ,INVESTLOAN
        ,OCCCODE
        ,OCCUDESC
        ,LNPURPCODE
        ,LNPURPDESC
        ,HITYPE
        ,HITYPEDESC
        ,LOTYPE
        ,LOTYPEDESC
        ,FIRSTDUE
        ,FIRSTP
        ,FSTSERFE
        ,FORECLSCOD
        ,FORECLSDES
        ,ORGLT
        ,INTPDTHRU
        ,ESCROWBA
        ,ESCROWAD
        ,PLGCODE
        ,PLGDESC
        ,PMNTPERD
        ,BADCHKTBLE
        ,TIMESDLQ
        ,TOTPMN
        ,NOOFUNIT
        ,INTFLAG
        ,INTFLAGDES
        ,CAPLNFLAG
        ,CAPLNFDESC
        ,MTGRLNAME
        ,MTGRFNAME
        ,MTGRHAZPAY
        ,TIPMN
        ,GUARFE
        ,RECFLAG
        ,RECFLAGDES
        ,POOLNUM
        ,DLQPMNTCNT
        ,IOEFLAG
        ,IOEFLAGDES
        ,MANCODE
        ,BBCODE
        ,BRNCHOFF
        ,ACRLSTAT
        ,PREPMNTIND
        ,FHLBBPP
        ,FSTORGCOS
        ,FSTORIGFE
        ,FSTUNAMOR
        ,ARMIREFFDT
        ,ARMORGI
        ,ARMMARGI
        ,ARMPIEFFDT
        ,ARMCHGPRD
        ,ARMPICHGPR
        ,ARMIRMAXC
        ,ARMIRMAXF
        ,ARMIMAXIN
        ,ARMIMAXDE
        ,AIRMAXLIN
        ,AIRMAXLDE
        ,APIMAXPCT
        ,APIMAXPCD
        ,APIMAXLIF
        ,APIPCTMIN
        ,APIPCTMDE
        ,AORGPIAM
        ,ARMINDE
        ,ARMIRRAT
        ,AOIRCHGDT
        ,AIRRNDTP
        ,AIRRNDDESC
        ,AIRRNDFAC
        ,ARMPLANID
        ,ARMPLANDES
        ,ARMINDCO
        ,ARMINDDESC
        ,AILEADDAYS
        ,USR15POS1
        ,USR2POS1A
        ,USR2POS2A
        ,DFTIND
        ,BANKNAME
        ,LOT
        ,[BLOCK]
        ,SUBDIV
        ,COUNTYCODE
        ,COUNTYTA
        ,HAZMONTHL
        ,LASTANALDT
        ,ESCMINBAL
        ,LASTANALO
        ,OVSHTCHGDT
        ,MORTSSNO
        ,COMORTSSNO
        ,SSNCERTDT
        ,SSNVERCODE
        ,SSNVERDATE
        ,SETUPDATE
        ,SUSPBA
        ,RESTESCBA
        ,CRQUALCODE
        ,INTONLYIND
        ,PAYFULLDT
        ,SERVSOLDDT
        ,COMTGLNAME
        ,COMTGFNAME
        ,FLOZPOS1
        ,MTGRDOB
        ,COMTGRDOB
        ,PROPUNITNO
        ,LTVN
        ,BILLADDR3
        ,BILLADDR4
        ,BILLCITY
        ,BILLSTATE
        ,BILLZIP
        ,ORIGSCORE
        ,BILLADDR2
        ,USR1POS3A
        ,CHGOFFBALN
        ,ACCLATECAN
        ,LATECFN
        ,GRACEDAYS
        ,LCCODE
        ,PHONE
        ,PHONE2
        ,EMAILF
        ,PROCSC
        ,DAIND
        ,CSBORCBC
        ,CSBORCBST
        ,FIRSTFF1N
        ,ASSUMDATE
        ,VACDATE
        ,LNMODDATE
        ,USR20POS1A
        ,RECOVECABN
        ,NONRECCABN
        ,THIRDPRCBN
        ,PENDPIAMTN
        ,ADLCBN1
        ,ADLCSTN1
        ,ADLCBS
        ,ADLCBC
        ,ADLCBST
        ,ADLCBZC
        ,ADLCBPN
        ,LASTFPAYDT
        ,YTDINTAMTN
        ,YTDPPAMTN
        ,YTDTAXAMTN
        ,YTDHAZAMTN
        ,USR1PO4A
        ,DAYDELIQU
        ,ENTERNONAC
        ,LEAVENONAC
        ,APPRAIDATE
        ,LNMOAPPDAT
        ,LNMOAPPAM
        ,CHAROFFDAT
        ,DRROUTRNU
        ,FIORCOSAM
        ,FIORFEEAM
        ,NextDueDate
        ,OriginalLoanDate
        ,MaturityDate
        ,FirstDueDate
        ,AsOfDate
		,CONVERT(INT, CONVERT(nvarchar(6), AsOfDate, 112)) AS YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE AsOfDate > COALESCE((SELECT MAX(AsOfDate) FROM "DQP_BRONZE"."dbo"."bronze_jh_dmilay"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data