-- NAME: BRONZE_JH_BFWT0085
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: MONTHLY - 4TH BUSINESS DAY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



with landing_data as (
    SELECT
         WTACT
        ,WTAMOUNT
        ,WTFEE
        ,WTCOUNT
        ,WTFEEACT
        ,WTRANDATE
        ,NULL AS YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_BFWT0085"
),

bronze_data AS (
    SELECT
        CAST(NULLIF(WTACT, '') AS INTEGER) AS WTACT,
        CAST(NULLIF(WTAMOUNT, '') AS NUMERIC(15, 2)) AS WTAMOUNT,
        CAST(NULLIF(WTFEE, '') AS NUMERIC(15, 2)) AS WTFEE,
        CAST(NULLIF(WTCOUNT, '') AS INTEGER) AS WTCOUNT,
        CAST(NULLIF(WTFEEACT, '') AS NUMERIC(15, 2)) AS WTFEEACT,
        CAST(NULLIF(WTRANDATE, '') AS INTEGER) AS WTRANDATE,
        CONVERT(INT, CONCAT('20',LEFT(WTRANDATE,4))) AS YEARMONTH,
        GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM "DQP_BRONZE"."dbo"."bronze_jh_bfwt0085"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data