-- NAME: BRONZE_SBLC_LCMASTER
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: November 27, 2025



WITH landing_data AS (
    SELECT
     LCMBRN
     ,LCMCCY
     ,LCMGLN
     ,LCMCCN
     ,LCMPRC
     ,LCMACN
     ,LCMFCY
     ,LCMSTS
     ,LCMTYP
     ,LCMORF
     ,LCMRTY
     ,LCMOFX
     ,LCMCNF
     ,LCMTRF
     ,LCMTNR
     ,LCMOFI
     ,LCMGCD
     ,LCMGRC
     ,LCMOAM
     ,LCMAMN
     ,LCMCOM
     ,LCMEXP
     ,LCMMEB
     ,LCMCFK
     ,LCMODM
     ,LCMODD
     ,LCMODY
     ,LCMOPJ
     ,LCMLAM
     ,LCMLAD
     ,LCMLAY
     ,LCMLAJ
     ,LCMEXM
     ,LCMEXD
     ,LCMEXY
     ,LCMEXJ
     ,LCMCLM
     ,LCMCLD
     ,LCMCLY
     ,LCMCLJ
     ,LCMIB1
     ,LCMIB2
     ,LCMIB3
     ,LCMIBA
     ,LCMBN1
     ,LCMBN2
     ,LCMBN3
     ,LCMACC
     ,DATE_OF_DATA
     ,NULL AS YEARMONTH
     ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."SBLC_LCMASTER"
),

bronze_data AS (
    SELECT
        CAST(LCMBRN AS DECIMAL(3,0)) AS LCMBRN
        ,CAST(NULLIF(LCMCCY, '') AS VARCHAR(3)) AS LCMCCY
        ,CAST(LCMGLN AS DECIMAL(7,0)) AS LCMGLN
        ,CAST(LCMCCN AS DECIMAL(4,0)) AS LCMCCN
        ,CAST(LCMPRC AS DECIMAL(3,0)) AS LCMPRC
        ,CAST(LCMACN AS DECIMAL(16,0)) AS LCMACN
        ,CAST(NULLIF(LCMFCY, '') AS VARCHAR(3)) AS LCMFCY
        ,CAST(NULLIF(LCMSTS, '') AS VARCHAR(1)) AS LCMSTS
        ,CAST(NULLIF(LCMTYP, '') AS VARCHAR(1)) AS LCMTYP
        ,CAST(NULLIF(LCMORF, '') AS VARCHAR(16)) AS LCMORF
        ,CAST(NULLIF(LCMRTY, '') AS VARCHAR(1)) AS LCMRTY
        ,CAST(LCMOFX AS DECIMAL(17,6)) AS LCMOFX
        ,CAST(NULLIF(LCMCNF, '') AS VARCHAR(1)) AS LCMCNF
        ,CAST(NULLIF(LCMTRF, '') AS VARCHAR(16)) AS LCMTRF
        ,CAST(NULLIF(LCMTNR, '') AS VARCHAR(1)) AS LCMTNR
        ,CAST(NULLIF(LCMOFI, '') AS VARCHAR(6)) AS LCMOFI
        ,CAST(NULLIF(LCMGCD, '') AS VARCHAR(3)) AS LCMGCD
        ,CAST(NULLIF(LCMGRC, '') AS VARCHAR(3)) AS LCMGRC
        ,CAST(LCMOAM AS DECIMAL(17,2)) AS LCMOAM
        ,CAST(LCMAMN AS DECIMAL(17,2)) AS LCMAMN
        ,CAST(LCMCOM AS DECIMAL(17,2)) AS LCMCOM
        ,CAST(LCMEXP AS DECIMAL(17,2)) AS LCMEXP
        ,CAST(LCMMEB AS DECIMAL(17,2)) AS LCMMEB
        ,CAST(LCMCFK AS VARCHAR(7)) AS LCMCFK
        ,CAST(LCMODM AS DECIMAL(2,0)) AS LCMODM
        ,CAST(LCMODD AS DECIMAL(2,0)) AS LCMODD
        ,CAST(LCMODY AS DECIMAL(2,0)) AS LCMODY
        ,CAST(LCMOPJ AS DECIMAL(7,0)) AS LCMOPJ
        ,CAST(LCMLAM AS DECIMAL(2,0)) AS LCMLAM
        ,CAST(LCMLAD AS DECIMAL(2,0)) AS LCMLAD
        ,CAST(LCMLAY AS DECIMAL(2,0)) AS LCMLAY
        ,CAST(LCMLAJ AS DECIMAL(7,0)) AS LCMLAJ
        ,CAST(LCMEXM AS DECIMAL(2,0)) AS LCMEXM
        ,CAST(LCMEXD AS DECIMAL(2,0)) AS LCMEXD
        ,CAST(LCMEXY AS DECIMAL(2,0)) AS LCMEXY
        ,CAST(LCMEXJ AS DECIMAL(7,0)) AS LCMEXJ
        ,CAST(LCMCLM AS DECIMAL(2,0)) AS LCMCLM
        ,CAST(LCMCLD AS DECIMAL(2,0)) AS LCMCLD
        ,CAST(LCMCLY AS DECIMAL(2,0)) AS LCMCLY
        ,CAST(LCMCLJ AS DECIMAL(7,0)) AS LCMCLJ
        ,CAST(NULLIF(LCMIB1, '') AS VARCHAR(35)) AS LCMIB1
        ,CAST(NULLIF(LCMIB2, '') AS VARCHAR(35)) AS LCMIB2
        ,CAST(NULLIF(LCMIB3, '') AS VARCHAR(60)) AS LCMIB3
        ,CAST(LCMIBA AS DECIMAL(16,0)) AS LCMIBA
        ,CAST(NULLIF(LCMBN1, '') AS VARCHAR(35)) AS LCMBN1
        ,CAST(NULLIF(LCMBN2, '') AS VARCHAR(35)) AS LCMBN2
        ,CAST(NULLIF(LCMBN3, '') AS VARCHAR(60)) AS LCMBN3
        ,CAST(LCMACC AS DECIMAL(9,0)) AS LCMACC
        ,DATE_OF_DATA
        ,CONVERT(INT, CONVERT(nvarchar(6),DATE_OF_DATA, 112)) AS YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM "DQP_BRONZE"."dbo"."bronze_sblc_lcmaster"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data


-- NAME: BRONZE_SBLC_LCTRANX
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: November 27, 2025



with landing_data as (
    SELECT
        CAST(NULLIF(TRBR, '') AS INTEGER) AS TRBR
        ,CAST(NULLIF(TRCOST, '') AS INTEGER) AS TRCOST
        ,CAST(NULLIF(TRPROD, '') AS INTEGER) AS TRPROD
        ,CAST(NULLIF(TRAGLN, '') AS INTEGER) AS TRAGLN
        ,TRACCN
        ,CAST(NULLIF(LCMACC, '') AS INTEGER) AS LCMACC
        ,CAST(NULLIF(TRCODE, '') AS INTEGER) AS TRCODE
        ,CAST(NULLIF(TRATYP, '') AS VARCHAR(16)) AS TRATYP
        ,DESCRI
        ,CAST(NULLIF(TRDORC, '') AS VARCHAR(1)) AS TRDORC
        ,CAST(NULLIF(AMOUNT, '') AS DECIMAL(20,2)) AS AMOUNT
        ,FORMAT(
            TRY_CONVERT(DATE,
            STUFF(STUFF(NULLIF(TRIM(TREFF6), ''), 5, 0, '/'), 3, 0, '/'),
            1),
            'dd-MM-yyyy') AS TREFF6
        ,DDMUID
        ,DATE_OF_DATA
        ,CONVERT(INT, CONVERT(nvarchar(6),DATE_OF_DATA, 112)) AS YEARMONTH
    FROM
        "DQP_LANDING"."dbo"."SBLC_LCTRANX"
    
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM "DQP_BRONZE"."dbo"."bronze_sblc_lctranx")
    
)





SELECT *,GETUTCDATE() AS LOADED_AT FROM landing_data



