-- NAME: BRONZE_JH_ACSRET
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



WITH landing_data AS (
    SELECT
         ACRTYP
        ,AC1TYP
        ,AC1PCD
        ,AC1RP1
        ,AC1RPI
        ,AC1RPC
        ,AC1SP1
        ,AC1SPI
        ,AC1SPC
        ,AC1DT
        ,AC1TIM
        ,AC1MOD
        ,AC1REC
        ,AC1BLK
        ,AC1FC
        ,AC1DES
        ,AC1ORG
        ,AC1REF
        ,AC5CLA
        ,AC5COM
        ,AC5CDD
        ,AC5CID
        ,AC5SEC
        ,AC5CED
        ,AC5CDT
        ,AC5EED
        ,AC5SET
        ,AC5OSI
        ,AC5ODF
        ,AC5BAT
        ,AC5IATIND
        ,AC5IATFEI
        ,AC5IATFERI
        ,AC5IATFER
        ,AC5IATDCC
        ,AC5IATOCCD
        ,AC5IATDCCD
        ,AC5BRFEI
        ,AC5BRFERI
        ,AC5BRFER
        ,AC5BRDCC
        ,AC5BROCC
        ,AC5BRDCRC
        ,AC6TYP
        ,AC6TC
        ,AC6RTR
        ,AC6RCK
        ,AC6ACT
        ,AC6AMT
        ,AC6IIN
        ,AC6CKN
        ,AC6CTY
        ,AC6STA
        ,AC6INM
        ,AC6IINCIE
        ,AC6INMCIE
        ,AC6DD
        ,AC6ARI
        ,AC6TRC
        ,AC6BRRCVCO
        ,AC6CED
        ,AC6DFN
        ,AC6CAN
        ,AC6CTT
        ,AC6NIP
        ,AC6RCN
        ,AC6FIL
        ,AC6INOADDN
        ,AC6IACCTNO
        ,AC6IGOOSI1
        ,AC6IGOOSI2
        ,AC7TYP
        ,AC7ATC
        ,AC7RET
        ,AC7OTN
        ,AC7DOD
        ,AC7TR
        ,AC7AI
        ,AC7TRC
        ,AC7IOEPAMT
        ,AC7IRTNADD
        ,AC7ICORDTA
        ,AC7BRTRTYP
        ,AC7BRFRNID
        ,AC7BRFRNAM
        ,AC7BRFRNTR
        ,AC7BRFRNAC
        ,AC7BRRTID
        ,AC7BRRTAM
        ,AC7BRRTFAM
        ,AC7BRRTADN
        ,AC7BRRTTRC
        ,AC7TD
        ,AC7NIC
        ,AC7TIC
        ,AC7TSN
        ,AC7TDT
        ,AC7TTA
        ,AC7LOC
        ,AC7CIT
        ,AC7STA
        ,AC7PTC
        ,AC7RDC
        ,AC7RN
        ,AC7RID
        ,AC7DDA
        ,AC7TDA
        ,AC7ADJ
        ,AC7NET
        ,AC7AVI
        ,AC7SAN
        ,AC7FL2
        ,AC7ASN
        ,AC7DSN
        ,AC7F79
        ,AC7SSN
        ,AC7F80
        ,AC7SAS
        ,AC8EAC
        ,AC8HSH
        ,AC8DRA
        ,AC8CRA
        ,AC8CID
        ,AC8OTR
        ,AC8BAT
        ,AC9BAT
        ,AC9EAC
        ,AC9DRA
        ,AC9CRA
        ,AC8DRAADV
        ,AC8CRAADV
        ,AC8OPDADV
        ,AC9DRAADV
        ,AC9CRAADV
        ,AC9FILADV
        ,ACONUS
        ,ACONUSCRC
        ,ACONUSCRT
        ,ACONUSDRC
        ,ACONUSDRT
        ,ACNOTUSCRC
        ,ACNOTUSCRT
        ,ACNOTUSDRC
        ,ACNOTUSDRT
        ,ACRSKVIOL
        ,ACSUSPEND
        ,ACACCT
        ,ACATYP
        ,ACOSCD
        ,ACOSAT
        ,ACOBR
        ,ACMEMO
        ,ACEXDT
        ,ACFILK
        ,ACBATN
        ,ACSEQN
        ,ACORGFILK
        ,ACORGBATN
        ,ACORGSEQN
        ,ACENTB
        ,ACDEN7
        ,ACDEN6
        ,ACTENT
        ,ACENTV
        ,ACUPLDUID
        ,ACUPLDWID
        ,ACUSPNDUID
        ,ACUSPNDWID
        ,ACSPNDUID
        ,ACSPNDWID
        ,ACRETURNED
        ,ACRTNDTTM
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
            FROM dqp_landing.dbo.jh_ddpar1) as AsOfDate
        ,NULL AS YEARMONTH
        ,LOADED_AT
FROM
    "DQP_LANDING"."dbo"."JH_ACSRET"
),

bronze_data AS (
    SELECT
         ACRTYP
        ,AC1TYP
        ,AC1PCD
        ,AC1RP1
        ,AC1RPI
        ,AC1RPC
        ,AC1SP1
        ,AC1SPI
        ,AC1SPC
        ,AC1DT
        ,AC1TIM
        ,AC1MOD
        ,AC1REC
        ,AC1BLK
        ,AC1FC
        ,AC1DES
        ,AC1ORG
        ,AC1REF
        ,AC5CLA
        ,AC5COM
        ,AC5CDD
        ,AC5CID
        ,AC5SEC
        ,AC5CED
        ,AC5CDT
        ,AC5EED
        ,AC5SET
        ,AC5OSI
        ,AC5ODF
        ,AC5BAT
        ,AC5IATIND
        ,AC5IATFEI
        ,AC5IATFERI
        ,AC5IATFER
        ,AC5IATDCC
        ,AC5IATOCCD
        ,AC5IATDCCD
        ,AC5BRFEI
        ,AC5BRFERI
        ,AC5BRFER
        ,AC5BRDCC
        ,AC5BROCC
        ,AC5BRDCRC
        ,AC6TYP
        ,AC6TC
        ,AC6RTR
        ,AC6RCK
        ,AC6ACT
        ,AC6AMT
        ,AC6IIN
        ,AC6CKN
        ,AC6CTY
        ,AC6STA
        ,AC6INM
        ,AC6IINCIE
        ,AC6INMCIE
        ,AC6DD
        ,AC6ARI
        ,AC6TRC
        ,AC6BRRCVCO
        ,AC6CED
        ,AC6DFN
        ,AC6CAN
        ,AC6CTT
        ,AC6NIP
        ,AC6RCN
        ,AC6FIL
        ,AC6INOADDN
        ,AC6IACCTNO
        ,AC6IGOOSI1
        ,AC6IGOOSI2
        ,AC7TYP
        ,AC7ATC
        ,AC7RET
        ,AC7OTN
        ,AC7DOD
        ,AC7TR
        ,AC7AI
        ,AC7TRC
        ,AC7IOEPAMT
        ,AC7IRTNADD
        ,AC7ICORDTA
        ,AC7BRTRTYP
        ,AC7BRFRNID
        ,AC7BRFRNAM
        ,AC7BRFRNTR
        ,AC7BRFRNAC
        ,AC7BRRTID
        ,AC7BRRTAM
        ,AC7BRRTFAM
        ,AC7BRRTADN
        ,AC7BRRTTRC
        ,AC7TD
        ,AC7NIC
        ,AC7TIC
        ,AC7TSN
        ,AC7TDT
        ,AC7TTA
        ,AC7LOC
        ,AC7CIT
        ,AC7STA
        ,AC7PTC
        ,AC7RDC
        ,AC7RN
        ,AC7RID
        ,AC7DDA
        ,AC7TDA
        ,AC7ADJ
        ,AC7NET
        ,AC7AVI
        ,AC7SAN
        ,AC7FL2
        ,AC7ASN
        ,AC7DSN
        ,AC7F79
        ,AC7SSN
        ,AC7F80
        ,AC7SAS
        ,AC8EAC
        ,AC8HSH
        ,AC8DRA
        ,AC8CRA
        ,AC8CID
        ,AC8OTR
        ,AC8BAT
        ,AC9BAT
        ,AC9EAC
        ,AC9DRA
        ,AC9CRA
        ,AC8DRAADV
        ,AC8CRAADV
        ,AC8OPDADV
        ,AC9DRAADV
        ,AC9CRAADV
        ,AC9FILADV
        ,ACONUS
        ,ACONUSCRC
        ,ACONUSCRT
        ,ACONUSDRC
        ,ACONUSDRT
        ,ACNOTUSCRC
        ,ACNOTUSCRT
        ,ACNOTUSDRC
        ,ACNOTUSDRT
        ,ACRSKVIOL
        ,ACSUSPEND
        ,ACACCT
        ,ACATYP
        ,ACOSCD
        ,ACOSAT
        ,ACOBR
        ,ACMEMO
        ,ACEXDT
        ,ACFILK
        ,ACBATN
        ,ACSEQN
        ,ACORGFILK
        ,ACORGBATN
        ,ACORGSEQN
        ,ACENTB
        ,ACDEN7
        ,ACDEN6
        ,ACTENT
        ,ACENTV
        ,ACUPLDUID
        ,ACUPLDWID
        ,ACUSPNDUID
        ,ACUSPNDWID
        ,ACSPNDUID
        ,ACSPNDWID
        ,ACRETURNED
        ,ACRTNDTTM
        ,AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6), AsOfDate, 112)) AS YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE LOADED_AT > COALESCE((SELECT MAX(LOADED_AT) FROM "DQP_BRONZE"."dbo"."bronze_jh_acsret"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data