-- NAME: BRONZE_JH_GLMAST
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: March 27, 2025



WITH landing_data AS (
    SELECT
        BANKNO
        ,BRANCH
        ,ACCTNO
        ,CONACC
        ,CENTER
        ,PRDCOD
        ,[STATUS]
        ,POST
        ,TITLE
        ,ACTYPE
        ,REPTYP
        ,ACTSEQ
        ,[LEVEL]
        ,OFFICR
        ,BALCOD
        ,PSTFRQ
        ,TRNTYP
        ,MANDES
        ,MANOFF
        ,RISK
        ,CALRP1
        ,CALRP2
        ,CALRP3
        ,CALRP4
        ,COND1
        ,COND2
        ,COND3
        ,COND4
        ,COND5
        ,COND6
        ,COND7
        ,COND8
        ,COND9
        ,GLSIC1
        ,GLSIC2
        ,GLSIC3
        ,GLSIC4
        ,DATCV7
        ,DATCV6
        ,DLA7
        ,DLA6
        ,DATOP7
        ,DATOP6
        ,DATEN7
        ,DATEN6
        ,DLM7
        ,DLM6
        ,CURBAL
        ,NETCHG
        ,YESBAL
        ,BEGCYR
        ,BEGLYR
        ,BEGPYR
        ,MTDBAL
        ,QTDBAL
        ,YTDBAL
        ,MTDAVG
        ,QTDAVG
        ,YTDAVG
        ,YTDAVL
        ,YTDAVP
        ,MAGBAL
        ,QAGBAL
        ,YAGBAL
        ,GLPIC1
        ,GLPIC2
        ,GLPD71
        ,GLPD61
        ,GLPD72
        ,GLPD62
        ,GLPAM1
        ,GLPAM2
        ,GLPAM3
        ,GLPAM4
        ,CMEB1
        ,CMEB2
        ,CMEB3
        ,CMEB4
        ,CMEB5
        ,CMEB6
        ,CMEB7
        ,CMEB8
        ,CMEB9
        ,CMEB10
        ,CMEB11
        ,CMEB12
        ,LMEB1
        ,LMEB2
        ,LMEB3
        ,LMEB4
        ,LMEB5
        ,LMEB6
        ,LMEB7
        ,LMEB8
        ,LMEB9
        ,LMEB10
        ,LMEB11
        ,LMEB12
        ,PMEB1
        ,PMEB2
        ,PMEB3
        ,PMEB4
        ,PMEB5
        ,PMEB6
        ,PMEB7
        ,PMEB8
        ,PMEB9
        ,PMEB10
        ,PMEB11
        ,PMEB12
        ,CMTD1
        ,CMTD2
        ,CMTD3
        ,CMTD4
        ,CMTD5
        ,CMTD6
        ,CMTD7
        ,CMTD8
        ,CMTD9
        ,CMTD10
        ,CMTD11
        ,CMTD12
        ,LMTD1
        ,LMTD2
        ,LMTD3
        ,LMTD4
        ,LMTD5
        ,LMTD6
        ,LMTD7
        ,LMTD8
        ,LMTD9
        ,LMTD10
        ,LMTD11
        ,LMTD12
        ,PMTD1
        ,PMTD2
        ,PMTD3
        ,PMTD4
        ,PMTD5
        ,PMTD6
        ,PMTD7
        ,PMTD8
        ,PMTD9
        ,PMTD10
        ,PMTD11
        ,PMTD12
        ,CAGG1
        ,CAGG2
        ,CAGG3
        ,CAGG4
        ,CAGG5
        ,CAGG6
        ,CAGG7
        ,CAGG8
        ,CAGG9
        ,CAGG10
        ,CAGG11
        ,CAGG12
        ,LAGG1
        ,LAGG2
        ,LAGG3
        ,LAGG4
        ,LAGG5
        ,LAGG6
        ,LAGG7
        ,LAGG8
        ,LAGG9
        ,LAGG10
        ,LAGG11
        ,LAGG12
        ,PAGG1
        ,PAGG2
        ,PAGG3
        ,PAGG4
        ,PAGG5
        ,PAGG6
        ,PAGG7
        ,PAGG8
        ,PAGG9
        ,PAGG10
        ,PAGG11
        ,PAGG12
        ,CAVG1
        ,CAVG2
        ,CAVG3
        ,CAVG4
        ,CAVG5
        ,CAVG6
        ,CAVG7
        ,CAVG8
        ,CAVG9
        ,CAVG10
        ,CAVG11
        ,CAVG12
        ,LAVG1
        ,LAVG2
        ,LAVG3
        ,LAVG4
        ,LAVG5
        ,LAVG6
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
	        FROM dqp_landing.dbo.jh_ddpar1) as AsOfDate
        ,NULL as YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_GLMAST"
),

bronze_data AS (
    SELECT
        BANKNO
        ,BRANCH
        ,ACCTNO
        ,CONACC
        ,CENTER
        ,PRDCOD
        ,[STATUS]
        ,POST
        ,TITLE
        ,ACTYPE
        ,REPTYP
        ,ACTSEQ
        ,[LEVEL]
        ,OFFICR
        ,BALCOD
        ,PSTFRQ
        ,TRNTYP
        ,MANDES
        ,MANOFF
        ,RISK
        ,CALRP1
        ,CALRP2
        ,CALRP3
        ,CALRP4
        ,COND1
        ,COND2
        ,COND3
        ,COND4
        ,COND5
        ,COND6
        ,COND7
        ,COND8
        ,COND9
        ,GLSIC1
        ,GLSIC2
        ,GLSIC3
        ,GLSIC4
        ,DATCV7
        ,DATCV6
        ,DLA7
        ,DLA6
        ,DATOP7
        ,DATOP6
        ,DATEN7
        ,DATEN6
        ,DLM7
        ,DLM6
        ,CURBAL
        ,NETCHG
        ,YESBAL
        ,BEGCYR
        ,BEGLYR
        ,BEGPYR
        ,MTDBAL
        ,QTDBAL
        ,YTDBAL
        ,MTDAVG
        ,QTDAVG
        ,YTDAVG
        ,YTDAVL
        ,YTDAVP
        ,MAGBAL
        ,QAGBAL
        ,YAGBAL
        ,GLPIC1
        ,GLPIC2
        ,GLPD71
        ,GLPD61
        ,GLPD72
        ,GLPD62
        ,GLPAM1
        ,GLPAM2
        ,GLPAM3
        ,GLPAM4
        ,CMEB1
        ,CMEB2
        ,CMEB3
        ,CMEB4
        ,CMEB5
        ,CMEB6
        ,CMEB7
        ,CMEB8
        ,CMEB9
        ,CMEB10
        ,CMEB11
        ,CMEB12
        ,LMEB1
        ,LMEB2
        ,LMEB3
        ,LMEB4
        ,LMEB5
        ,LMEB6
        ,LMEB7
        ,LMEB8
        ,LMEB9
        ,LMEB10
        ,LMEB11
        ,LMEB12
        ,PMEB1
        ,PMEB2
        ,PMEB3
        ,PMEB4
        ,PMEB5
        ,PMEB6
        ,PMEB7
        ,PMEB8
        ,PMEB9
        ,PMEB10
        ,PMEB11
        ,PMEB12
        ,CMTD1
        ,CMTD2
        ,CMTD3
        ,CMTD4
        ,CMTD5
        ,CMTD6
        ,CMTD7
        ,CMTD8
        ,CMTD9
        ,CMTD10
        ,CMTD11
        ,CMTD12
        ,LMTD1
        ,LMTD2
        ,LMTD3
        ,LMTD4
        ,LMTD5
        ,LMTD6
        ,LMTD7
        ,LMTD8
        ,LMTD9
        ,LMTD10
        ,LMTD11
        ,LMTD12
        ,PMTD1
        ,PMTD2
        ,PMTD3
        ,PMTD4
        ,PMTD5
        ,PMTD6
        ,PMTD7
        ,PMTD8
        ,PMTD9
        ,PMTD10
        ,PMTD11
        ,PMTD12
        ,CAGG1
        ,CAGG2
        ,CAGG3
        ,CAGG4
        ,CAGG5
        ,CAGG6
        ,CAGG7
        ,CAGG8
        ,CAGG9
        ,CAGG10
        ,CAGG11
        ,CAGG12
        ,LAGG1
        ,LAGG2
        ,LAGG3
        ,LAGG4
        ,LAGG5
        ,LAGG6
        ,LAGG7
        ,LAGG8
        ,LAGG9
        ,LAGG10
        ,LAGG11
        ,LAGG12
        ,PAGG1
        ,PAGG2
        ,PAGG3
        ,PAGG4
        ,PAGG5
        ,PAGG6
        ,PAGG7
        ,PAGG8
        ,PAGG9
        ,PAGG10
        ,PAGG11
        ,PAGG12
        ,CAVG1
        ,CAVG2
        ,CAVG3
        ,CAVG4
        ,CAVG5
        ,CAVG6
        ,CAVG7
        ,CAVG8
        ,CAVG9
        ,CAVG10
        ,CAVG11
        ,CAVG12
        ,LAVG1
        ,LAVG2
        ,LAVG3
        ,LAVG4
        ,LAVG5
        ,LAVG6
        ,AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6),AsOfDate, 112)) AS YEARMONTH--YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE AsOfDate > COALESCE((SELECT MAX(AsOfDate) FROM "DQP_BRONZE"."dbo"."bronze_jh_glmast"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data