-- NAME: BRONZE_JH_LNMAST
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



WITH landing_data AS (
    SELECT
        BR__CS
        ,ACCTNO
        ,ACTYPE
        ,SNAME
        ,CIFNO
        ,ALTADD
        ,ADDNAM
        ,ALTNAM
        ,OFFCR
        ,COFFCR
        ,[STATUS]
        ,PRVSTS
        ,CLASS
        ,[TYPE]
        ,ORGAMT
        ,CBAL
        ,ACBAL
        ,QRYBAL
        ,SLDBAL
        ,ACCINT
        ,ACCIN2
        ,DLRACC
        ,PDIEM
        ,BKDISC
        ,DLRDSC
        ,OTHCHG
        ,ASSLC
        ,PAIDLC
        ,MINCG
        ,CURPO
        ,NXTPO
        ,INTREB
        ,DLRREB
        ,PMTAMT
        ,PIAMT
        ,LSTPMT
        ,PRTPMT
        ,BILPRN
        ,BILINT
        ,BILESC
        ,BILLC
        ,BILOC
        ,BILCL
        ,BILAH
        ,BILUN
        ,EOLDPM
        ,OLDPI
        ,OLDEPM
        ,NEWPMT
        ,NEWPI
        ,AMRSUS
        ,SUBAMT
        ,SUBREM
        ,AMRINT
        ,APRAMT
        ,ANINCM
        ,PREACC
        ,PREDSC
        ,YSCBAL
        ,YSACCI
        ,YSIREB
        ,YSDREB
        ,YSOTHC
        ,INTODY
        ,STMBAL
        ,RENBAL
        ,BALLON
        ,PACBAL
        ,CHGOFF
        ,PNTPD
        ,LSTADV
        ,CURTMN
        ,ACCURT
        ,SHCOPR
        ,SHCOIN
        ,SHIAP
        ,SHGLPR
        ,SHACCI
        ,SHCINT
        ,SHCSTS
        ,YRLFEE
        ,MINADV
        ,LNUCHG
        ,POAMNT
        ,ORGADV
        ,MTDADV
        ,MTDCURT
        ,MTDPRIN
        ,MTDCAPDR
        ,MTDCAPCR
        ,ORGDT6
        ,MATDT6
        ,DATOP6
        ,NREVD6
        ,COEXD6
        ,UCEXD6
        ,NSPDT6
        ,FPDT6
        ,LPDT6
        ,NPDT6
        ,NPDAY
        ,THRUD6
        ,PDTOD6
        ,CURED6
        ,CURBD6
        ,RENDT6
        ,RENPD6
        ,EXTDT6
        ,EXTPD6
        ,EXAMD6
        ,LFMDT6
        ,ORGMD6
        ,NWPMD6
        ,NWESD6
        ,NWEAD6
        ,NEAND6
        ,PREVD6
        ,STMDT6
        ,CPNDT6
        ,NACDT6
        ,CHGDT6
        ,WCHDT6
        ,PRVDAY
        ,APPDT6
        ,AMRDT6
        ,LSTAD6
        ,LSTCP6
        ,ECRDT6
        ,ECRDAY
        ,ENWRD6
        ,CVEXP6
        ,ACTIV6
        ,FRCLD6
        ,REAMD6
        ,REAMDAY
        ,DTPDO6
        ,CNVDT6
        ,PERMFD6
        ,HECNV6
        ,STEPRD6
        ,ORGADVD6
        ,REPRICD6
        ,ORGDT
        ,MATDT
        ,DATOPN
        ,NREVDT
        ,COEXDT
        ,UCEXDT
        ,NSPDT
        ,FPDT
        ,LPDT
        ,NPDT
        ,THRUDT
        ,PDTODT
        ,CUREDT
        ,CURBDT
        ,RENDT
        ,RENPDT
        ,EXTDT
        ,EXTPDT
        ,EXAMDT
        ,LFMDT
        ,ORGMDT
        ,NWPMDT
        ,NWESDT
        ,NWEADT
        ,NEANDT
        ,PREVDT
        ,STMDT
        ,CPNDT
        ,NACDT
        ,CHGDT
        ,WCHDT
        ,APPDT7
        ,AMRDT7
        ,LSTAD7
        ,LSTCP7
        ,ECRDT
        ,ENWRDT
        ,CVEXP7
        ,ACTIV7
        ,FRCLD7
        ,REAMD7
        ,DTPDO7
        ,CNVDT7
        ,PERMFD7
        ,HECNV7
        ,STEPRDT
        ,ORGADVD7
        ,RATE
        ,DLQRATE
        ,DLRATE
        ,DLRUPC
        ,DLRRPC
        ,DLRDYS
        ,DLRPMT
        ,DLRFOR
        ,DLRBOD
        ,DLRRSV
        ,DLRBRS
        ,DLRERN
        ,DLRBER
        ,DLRUER
        ,DLRFER
        ,TTLINT
        ,MATRAT
        ,PRATE__CS
        ,DLQRATE__CS
        ,PVARI
        ,PVCODE
        ,DLQVARI
        ,DLQVCODE
        ,DLQRTDYS
        ,PFLOOR
        ,PCEIL
        ,PRTERM
        ,PRCODE
        ,ECAPUP
        ,ECAPDN
        ,ECRTRM
        ,ECRTCD
        ,ECRYOV
        ,ECRYOS
        ,ECRNOV
        ,ECRNOS
        ,ECRPOV
        ,ECRPOS
        ,ECRYOU
        ,ERMETH
        ,ERAMT
        ,ECPRT
        ,EPRVRT
        ,ENWRT
        ,EPMCAP
        ,ENPDYS
        ,ORGIDX
        ,CURIDX
        ,PRVIDX
        ,FUTIDX
        ,CVRTAB
        ,CINDX__CS
        ,CVVARI
        ,CVVARC
        ,TERM
        ,TMCODE
        ,FREQ
        ,FRCODE
        ,SEMDY1
        ,SEMDY2
        ,IBASE
        ,PMTCOD
        ,ALTSCH
        ,REAMOR
        ,BILNDY
        ,REAMTRM
        ,REAMTMCD
        ,PFLC
        ,PFEXTF
        ,PFBAL
        ,PFEARN
        ,PFDAYS
        ,CPD10
        ,CPD30
        ,CPD60
        ,CPD90
        ,EXTFEE
        ,ORGFEE
        ,YTDINT
        ,YTDPRN
        ,YTDLC
        ,EXTYTD
        ,RTCYTD
        ,RENYTD
        ,YTDADV
        ,YTDCURT
        ,YTDPRIN
        ,YTDCAPDR
        ,YTDCAPCR
        ,PPD10
        ,PPD30
        ,PPD60
        ,PPD90
        ,INTPRE
        ,LCPRE
        ,IRSPRE
        ,EXTPRE
        ,ORGPRE
        ,RENPRE
        ,LPD10
        ,LPD30
        ,LPD60
        ,LPD90
        ,INTLTD
        ,EXTLTD
        ,RTCLTD
        ,EXTMTH
        ,EXTFEL
        ,RENLTD
        ,IRSLTD
        ,ORGLTD
        ,NEXLTD
        ,DELIN4
        ,DELIN3
        ,DELIN2
        ,DELIN1
        ,QAGQRYBAL
        ,PARTID
        ,CLCODE
        ,DEPTCD
        ,SHADOW
        ,SHACCF
        ,SHRPCO
        ,GROUP__CS
        ,GLCOST
        ,GLPROD
        ,CALREP
        ,COLCOD
        ,PURCOD
        ,DLRNO
        ,HMAIL
        ,INCLUD
        ,DEMSTU
        ,INDCOD
        ,NAICSC
        ,ESCPSQ
        ,INTPSQ
        ,LTCPSQ
        ,OTHPSQ
        ,PRNPSQ
        ,INSPSQ
        ,USEBIL
        ,SENDCD
        ,SENDMT
        ,TITLE
        ,PNFLAG
        ,PHFLAG
        ,SENDPD
        ,PDCODE
        ,LCTYPE
        ,IGNLCP
        ,TYPCLS
        ,RATCOD
        ,CENSUS
        ,SMSA
        ,CRALOC
        ,[STATE]
        ,CRASTA
        ,COUNTY
        ,VIN__CS
        ,MSG
        ,RENEXT
        ,USER1
        ,USER2
        ,ESCROW
        ,CLSZRO
        ,COUPON
        ,CPNTRM
        ,HASARM
        ,ALMTYP
        ,PRTPCT
        ,PRPRPC
        ,PRINPC
        ,PRTSQ__CS
        ,PRTPMS
        ,PRT1PM
        ,FNDSQ__CS
        ,FNDLMT
        ,FNDPCT
        ,PCACC__CS
        ,PCACTP
        ,CLACC__CS
        ,TAXREF
        ,RLACC__
        ,RLACTP
        ,HDACC__CS
        ,HDACTP
        ,REWLN__CS
        ,RQ1098
        ,STMPAS
        ,MATGRC
        ,WCHCOD
        ,PPPCOD
        ,FLINRQ
        ,BRWPD
        ,RSTRUC
        ,SECURE
        ,LNPIC1
        ,LNPIC2
        ,LNPIC3
        ,LNPIC4
        ,LNPIC5
        ,LNPIC6
        ,LNPIC7
        ,LNPDT1
        ,LNPD61
        ,LNPDT2
        ,LNPD62
        ,LNPAM1
        ,LNPAM2
        ,LNPAM3
        ,LNPAM4
        ,LNPAM5
        ,LNPAM6
        ,LNPAM7
        ,LNANIC
        ,LTVRAT
        ,CLTVRT
        ,SLOUTS
        ,OLDMNY
        ,NEWMNY
        ,DWNPMT
        ,XCLSTT
        ,POPEND
        ,UNPADV
        ,REMTRM
        ,CRAMIL
        ,SCRACOD
        ,SCRABDATE
        ,SCRABDAT6
        ,SCRAEDATE
        ,SCRAEDAT6
        ,LNSPCC
        ,CBC10
        ,CBC30
        ,CBC60
        ,CBC90
        ,STM__AC
        ,RSTADV
        ,RSTPMT
        ,LNMCHK
        ,LNREGH
        ,LNSENL
        ,BADCK__CS
        ,HIRISK
        ,LNREGP
        ,RECEIT
        ,DLORAT
        ,NEGPCT
        ,NSFFEE
        ,MADVFE
        ,DEFINT
        ,PTDINT
        ,USRSTS
        ,STPADV
        ,STPAD6
        ,STPAD7
        ,STPPMT
        ,STPPM6
        ,STPPM7
        ,STPTAX
        ,STPTX6
        ,STPTX7
        ,STPHZD
        ,STPHZ6
        ,STPHZ7
        ,STPOPT
        ,STPOP6
        ,STPOP7
        ,STPLNS
        ,STPLS6
        ,STPLS7
        ,STPNOT
        ,STPNT6
        ,STPNT7
        ,STPCRP
        ,STPCR6
        ,STPCR7
        ,STPPRP
        ,STPPR6
        ,STPPR7
        ,STPACR
        ,STPAC6
        ,STPAC7
        ,STPCOR
        ,STPCO6
        ,STPCO7
        ,STPIRS
        ,STPIR6
        ,STPIR7
        ,STPSTM
        ,STPST6
        ,STPST7
        ,STPCOU
        ,STPCP6
        ,STPCP7
        ,STPESD
        ,STPED6
        ,STPED7
        ,STPESA
        ,STPEA6
        ,STPEA7
        ,STPPDP
        ,STPPD6
        ,STPPD7
        ,PSTSHR
        ,USEUNA
        ,HOWUNA
        ,DLRLOC
        ,DLRTYP
        ,DLRFDP
        ,DLRFDPC
        ,CDLRFOR
        ,CDLRDYS
        ,CDLRPMT
        ,CDLRPDD
        ,RECRSCD
        ,RECRSPC
        ,RECRSTM
        ,RECRSTC
        ,RECDAYP
        ,RECINT
        ,PARTID__CS
        ,PNFLAGS
        ,PAYEX6
        ,PAYEX7
        ,CPD120
        ,CPD150
        ,CPD180
        ,PPD120
        ,PPD150
        ,PPD180
        ,LPD120
        ,LPD150
        ,LPD180
        ,PCTREA
        ,PARTPC
        ,BILOLA
        ,YTDPEN
        ,PREPEN
        ,LTDPEN
        ,SUBPRM
        ,OVLFEE
        ,CLCIF__CS
        ,ADOTNB
        ,UNTPDLRFP
        ,MINUNTADV
        ,SYNDAGTNBR
        ,SYNDMBRNBR
        ,SHRNTLCRD
        ,CORRESBANK
        ,CRCYTYPE
        ,FRDALRT
        ,ARGPRDCOD
        ,CONSTR
        ,RGRISK
        ,TEASER
        ,CSPLTV
        ,EXSLTV
        ,EXRELP
        ,LNATMCRD
        ,HMDA
        ,SALESAC
        ,RTCCTR
        ,AFFILIATE
        ,MINBIL
        ,INTFIR
        ,STEPRT
        ,LNLANG
        ,APPDLNS
        ,NBRPDPMT
        ,APPPDLNS
        ,NPDAPPLT
        ,NPDPPLTR
        ,POSTEXPC
        ,SHDOW6
        ,SHDOW7
        ,RSHTPC6
        ,ODIBAS
        ,MTDADV__CS
        ,YRLCALC
        ,LOCCALC
        ,LOCFREQ
        ,LOCFRCD
        ,LOCFDT6
        ,LOCFDT7
        ,LOCFDY
        ,UNUCALC
        ,UNUFREQ
        ,UNUFRCD
        ,UNUFDT6
        ,UNUFDT7
        ,UNUFDY
        ,DYSZROCUR
        ,DYSZRO01
        ,DYSZRO02
        ,DYSZRO03
        ,DYSZRO04
        ,DYSZRO05
        ,DYSZRO06
        ,DYSZRO07
        ,DYSZRO08
        ,DYSZRO09
        ,DYSZRO10
        ,DYSZRO11
        ,DYSZRO12
        ,LPTYPE
        ,CPASSLN
        ,RPASSLN
        ,RPASSPCT
        ,PPSDT6
        ,PPSDT7
        ,PPSFRQ
        ,PPSCOD
        ,PPDBAL
        ,PPCURT
        ,PPEXP6
        ,PPEXP7
        ,CURNTC6
        ,CURNTC7
        ,CUREXP6
        ,CUREXP7
        ,CURALL6
        ,CURALL7
        ,INVALL6
        ,INVALL7
        ,RECOUPASD
        ,RECOUPYTD
        ,RECOUPPRE
        ,NSFNTCYTD
        ,NSFNTCPRE
        ,PAYCURT
        ,PAYCOUP
        ,RECPRNDT6
        ,RECPRNDT7
        ,CURTAMT1
        ,CURTAMT2
        ,DATEPEN16
        ,DATEPEN17
        ,DATEPEN26
        ,DATEPEN27
        ,LNTIER
        ,LQBL__2
        ,LQRT__2
        ,LQBL__3
        ,LQRT__3
        ,LQBL__4
        ,LQRT__4
        ,LQBL__5
        ,LQRT__5
        ,LQBL__6
        ,LQRT__6
        ,LQBL__7
        ,LQRT__7
        ,LQBL__8
        ,LQRT__8
        ,LQBL__9
        ,LQRT__9
        ,LQBL__10
        ,LQRT__10
        ,LSPLIT
        ,LIENPOSN
        ,ODPUSEHOLD
        ,PENRAT__CS
        ,PENNEWRT
        ,PENRATE
        ,PENPDAYS
        ,PENAFTNT
        ,PENRVTM
        ,PENRVTMC
        ,PENNOTD6
        ,PENNOTD7
        ,PENSTDT6
        ,PENSTDT7
        ,PENRVDT6
        ,PENRVDT7
        ,PENRATYN
        ,PENLNRATE
        ,PPVARI
        ,PPVCODE
        ,SPECLEN
        ,TSAMT1
        ,TSAMT2
        ,TSDATE1
        ,TSDATE2
        ,TS1CHAR1
        ,TS1CHAR2
        ,TS2CHAR3
        ,TS2CHAR4
        ,PRMRSKRAT
        ,RSKRATDT6
        ,RSKRATDT7
        ,SPLRSKRAT1
        ,SPLRSKAMT1
        ,SPLRSKRAT2
        ,SPLRSKPCT2
        ,SPLRSKAMT2
        ,SPLRSKRAT3
        ,SPLRSKPCT3
        ,SPLRSKAMT3
        ,SPLRSKCA1
        ,NGAMORG__CS
        ,AUTOBIL
        ,YTDESC
        ,PRVESC
        ,YTDFEE
        ,PRVFEE
        ,PRVPRN
        ,PRIDWE
        ,ARMNTC
        ,INARMD
        ,ARMSNT
        ,EINDT6
        ,EINDT7
        ,dbo.ConvertJhDateJulianToDatetime(DATOPN) as LoanSetupDate
        ,dbo.ConvertJhDateJulianToDatetime(ORGDT) as OriginalLoanDate
        ,dbo.ConvertJhDateJulianToDatetime(MATDT) as MaturityDate
        ,dbo.ConvertJhDateJulianToDatetime(NREVDT) as NextReviewDate
        ,dbo.ConvertJhDateJulianToDatetime(FPDT) as FirstPaymentDate
        ,dbo.ConvertJhDateJulianToDatetime(LPDT) as LastPaymentDate
        ,dbo.ConvertJhDateJulianToDatetime(NPDT) as NextPaymentDueDate
        ,dbo.ConvertJhDateJulianToDatetime(RENDT) as DateLastRenewed
        ,dbo.ConvertJhDateJulianToDatetime(ORGMDT) as OriginalMaturityDate
        ,dbo.ConvertJhDateJulianToDatetime(PRVDAY) as RateReviewDate
        ,dbo.ConvertJhDateJulianToDatetime(NACDT) as NonAccrualDate
        ,dbo.ConvertJhDateJulianToDatetime(CHGDT) as ChargeOffDate
        ,dbo.ConvertJhDateJulianToDatetime(ACTIV7) as LastActivityDate
        ,dbo.ConvertJhDateJulianToDatetime(FRCLD7) as ForeclosureDate
        ,dbo.ConvertJhDateJulianToDatetime(DTPDO7) as DatePaidOff
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
	        FROM dqp_landing.dbo.jh_ddpar1) as AsOfDate
        ,NULL as YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_LNMAST"
),

bronze_data AS (
    SELECT
        BR__CS
        ,ACCTNO
        ,ACTYPE
        ,SNAME
        ,CIFNO
        ,ALTADD
        ,ADDNAM
        ,ALTNAM
        ,OFFCR
        ,COFFCR
        ,[STATUS]
        ,PRVSTS
        ,CLASS
        ,[TYPE]
        ,ORGAMT
        ,CBAL
        ,ACBAL
        ,QRYBAL
        ,SLDBAL
        ,ACCINT
        ,ACCIN2
        ,DLRACC
        ,PDIEM
        ,BKDISC
        ,DLRDSC
        ,OTHCHG
        ,ASSLC
        ,PAIDLC
        ,MINCG
        ,CURPO
        ,NXTPO
        ,INTREB
        ,DLRREB
        ,PMTAMT
        ,PIAMT
        ,LSTPMT
        ,PRTPMT
        ,BILPRN
        ,BILINT
        ,BILESC
        ,BILLC
        ,BILOC
        ,BILCL
        ,BILAH
        ,BILUN
        ,EOLDPM
        ,OLDPI
        ,OLDEPM
        ,NEWPMT
        ,NEWPI
        ,AMRSUS
        ,SUBAMT
        ,SUBREM
        ,AMRINT
        ,APRAMT
        ,ANINCM
        ,PREACC
        ,PREDSC
        ,YSCBAL
        ,YSACCI
        ,YSIREB
        ,YSDREB
        ,YSOTHC
        ,INTODY
        ,STMBAL
        ,RENBAL
        ,BALLON
        ,PACBAL
        ,CHGOFF
        ,PNTPD
        ,LSTADV
        ,CURTMN
        ,ACCURT
        ,SHCOPR
        ,SHCOIN
        ,SHIAP
        ,SHGLPR
        ,SHACCI
        ,SHCINT
        ,SHCSTS
        ,YRLFEE
        ,MINADV
        ,LNUCHG
        ,POAMNT
        ,ORGADV
        ,MTDADV
        ,MTDCURT
        ,MTDPRIN
        ,MTDCAPDR
        ,MTDCAPCR
        ,ORGDT6
        ,MATDT6
        ,DATOP6
        ,NREVD6
        ,COEXD6
        ,UCEXD6
        ,NSPDT6
        ,FPDT6
        ,LPDT6
        ,NPDT6
        ,NPDAY
        ,THRUD6
        ,PDTOD6
        ,CURED6
        ,CURBD6
        ,RENDT6
        ,RENPD6
        ,EXTDT6
        ,EXTPD6
        ,EXAMD6
        ,LFMDT6
        ,ORGMD6
        ,NWPMD6
        ,NWESD6
        ,NWEAD6
        ,NEAND6
        ,PREVD6
        ,STMDT6
        ,CPNDT6
        ,NACDT6
        ,CHGDT6
        ,WCHDT6
        ,PRVDAY
        ,APPDT6
        ,AMRDT6
        ,LSTAD6
        ,LSTCP6
        ,ECRDT6
        ,ECRDAY
        ,ENWRD6
        ,CVEXP6
        ,ACTIV6
        ,FRCLD6
        ,REAMD6
        ,REAMDAY
        ,DTPDO6
        ,CNVDT6
        ,PERMFD6
        ,HECNV6
        ,STEPRD6
        ,ORGADVD6
        ,REPRICD6
        ,ORGDT
        ,MATDT
        ,DATOPN
        ,NREVDT
        ,COEXDT
        ,UCEXDT
        ,NSPDT
        ,FPDT
        ,LPDT
        ,NPDT
        ,THRUDT
        ,PDTODT
        ,CUREDT
        ,CURBDT
        ,RENDT
        ,RENPDT
        ,EXTDT
        ,EXTPDT
        ,EXAMDT
        ,LFMDT
        ,ORGMDT
        ,NWPMDT
        ,NWESDT
        ,NWEADT
        ,NEANDT
        ,PREVDT
        ,STMDT
        ,CPNDT
        ,NACDT
        ,CHGDT
        ,WCHDT
        ,APPDT7
        ,AMRDT7
        ,LSTAD7
        ,LSTCP7
        ,ECRDT
        ,ENWRDT
        ,CVEXP7
        ,ACTIV7
        ,FRCLD7
        ,REAMD7
        ,DTPDO7
        ,CNVDT7
        ,PERMFD7
        ,HECNV7
        ,STEPRDT
        ,ORGADVD7
        ,RATE
        ,DLQRATE
        ,DLRATE
        ,DLRUPC
        ,DLRRPC
        ,DLRDYS
        ,DLRPMT
        ,DLRFOR
        ,DLRBOD
        ,DLRRSV
        ,DLRBRS
        ,DLRERN
        ,DLRBER
        ,DLRUER
        ,DLRFER
        ,TTLINT
        ,MATRAT
        ,PRATE__CS
        ,DLQRATE__CS
        ,PVARI
        ,PVCODE
        ,DLQVARI
        ,DLQVCODE
        ,DLQRTDYS
        ,PFLOOR
        ,PCEIL
        ,PRTERM
        ,PRCODE
        ,ECAPUP
        ,ECAPDN
        ,ECRTRM
        ,ECRTCD
        ,ECRYOV
        ,ECRYOS
        ,ECRNOV
        ,ECRNOS
        ,ECRPOV
        ,ECRPOS
        ,ECRYOU
        ,ERMETH
        ,ERAMT
        ,ECPRT
        ,EPRVRT
        ,ENWRT
        ,EPMCAP
        ,ENPDYS
        ,ORGIDX
        ,CURIDX
        ,PRVIDX
        ,FUTIDX
        ,CVRTAB
        ,CINDX__CS
        ,CVVARI
        ,CVVARC
        ,TERM
        ,TMCODE
        ,FREQ
        ,FRCODE
        ,SEMDY1
        ,SEMDY2
        ,IBASE
        ,PMTCOD
        ,ALTSCH
        ,REAMOR
        ,BILNDY
        ,REAMTRM
        ,REAMTMCD
        ,PFLC
        ,PFEXTF
        ,PFBAL
        ,PFEARN
        ,PFDAYS
        ,CPD10
        ,CPD30
        ,CPD60
        ,CPD90
        ,EXTFEE
        ,ORGFEE
        ,YTDINT
        ,YTDPRN
        ,YTDLC
        ,EXTYTD
        ,RTCYTD
        ,RENYTD
        ,YTDADV
        ,YTDCURT
        ,YTDPRIN
        ,YTDCAPDR
        ,YTDCAPCR
        ,PPD10
        ,PPD30
        ,PPD60
        ,PPD90
        ,INTPRE
        ,LCPRE
        ,IRSPRE
        ,EXTPRE
        ,ORGPRE
        ,RENPRE
        ,LPD10
        ,LPD30
        ,LPD60
        ,LPD90
        ,INTLTD
        ,EXTLTD
        ,RTCLTD
        ,EXTMTH
        ,EXTFEL
        ,RENLTD
        ,IRSLTD
        ,ORGLTD
        ,NEXLTD
        ,DELIN4
        ,DELIN3
        ,DELIN2
        ,DELIN1
        ,QAGQRYBAL
        ,PARTID
        ,CLCODE
        ,DEPTCD
        ,SHADOW
        ,SHACCF
        ,SHRPCO
        ,GROUP__CS
        ,GLCOST
        ,GLPROD
        ,CALREP
        ,COLCOD
        ,PURCOD
        ,DLRNO
        ,HMAIL
        ,INCLUD
        ,DEMSTU
        ,INDCOD
        ,NAICSC
        ,ESCPSQ
        ,INTPSQ
        ,LTCPSQ
        ,OTHPSQ
        ,PRNPSQ
        ,INSPSQ
        ,USEBIL
        ,SENDCD
        ,SENDMT
        ,TITLE
        ,PNFLAG
        ,PHFLAG
        ,SENDPD
        ,PDCODE
        ,LCTYPE
        ,IGNLCP
        ,TYPCLS
        ,RATCOD
        ,CENSUS
        ,SMSA
        ,CRALOC
        ,[STATE]
        ,CRASTA
        ,COUNTY
        ,VIN__CS
        ,MSG
        ,RENEXT
        ,USER1
        ,USER2
        ,ESCROW
        ,CLSZRO
        ,COUPON
        ,CPNTRM
        ,HASARM
        ,ALMTYP
        ,PRTPCT
        ,PRPRPC
        ,PRINPC
        ,PRTSQ__CS
        ,PRTPMS
        ,PRT1PM
        ,FNDSQ__CS
        ,FNDLMT
        ,FNDPCT
        ,PCACC__CS
        ,PCACTP
        ,CLACC__CS
        ,TAXREF
        ,RLACC__
        ,RLACTP
        ,HDACC__CS
        ,HDACTP
        ,REWLN__CS
        ,RQ1098
        ,STMPAS
        ,MATGRC
        ,WCHCOD
        ,PPPCOD
        ,FLINRQ
        ,BRWPD
        ,RSTRUC
        ,SECURE
        ,LNPIC1
        ,LNPIC2
        ,LNPIC3
        ,LNPIC4
        ,LNPIC5
        ,LNPIC6
        ,LNPIC7
        ,LNPDT1
        ,LNPD61
        ,LNPDT2
        ,LNPD62
        ,LNPAM1
        ,LNPAM2
        ,LNPAM3
        ,LNPAM4
        ,LNPAM5
        ,LNPAM6
        ,LNPAM7
        ,LNANIC
        ,LTVRAT
        ,CLTVRT
        ,SLOUTS
        ,OLDMNY
        ,NEWMNY
        ,DWNPMT
        ,XCLSTT
        ,POPEND
        ,UNPADV
        ,REMTRM
        ,CRAMIL
        ,SCRACOD
        ,SCRABDATE
        ,SCRABDAT6
        ,SCRAEDATE
        ,SCRAEDAT6
        ,LNSPCC
        ,CBC10
        ,CBC30
        ,CBC60
        ,CBC90
        ,STM__AC
        ,RSTADV
        ,RSTPMT
        ,LNMCHK
        ,LNREGH
        ,LNSENL
        ,BADCK__CS
        ,HIRISK
        ,LNREGP
        ,RECEIT
        ,DLORAT
        ,NEGPCT
        ,NSFFEE
        ,MADVFE
        ,DEFINT
        ,PTDINT
        ,USRSTS
        ,STPADV
        ,STPAD6
        ,STPAD7
        ,STPPMT
        ,STPPM6
        ,STPPM7
        ,STPTAX
        ,STPTX6
        ,STPTX7
        ,STPHZD
        ,STPHZ6
        ,STPHZ7
        ,STPOPT
        ,STPOP6
        ,STPOP7
        ,STPLNS
        ,STPLS6
        ,STPLS7
        ,STPNOT
        ,STPNT6
        ,STPNT7
        ,STPCRP
        ,STPCR6
        ,STPCR7
        ,STPPRP
        ,STPPR6
        ,STPPR7
        ,STPACR
        ,STPAC6
        ,STPAC7
        ,STPCOR
        ,STPCO6
        ,STPCO7
        ,STPIRS
        ,STPIR6
        ,STPIR7
        ,STPSTM
        ,STPST6
        ,STPST7
        ,STPCOU
        ,STPCP6
        ,STPCP7
        ,STPESD
        ,STPED6
        ,STPED7
        ,STPESA
        ,STPEA6
        ,STPEA7
        ,STPPDP
        ,STPPD6
        ,STPPD7
        ,PSTSHR
        ,USEUNA
        ,HOWUNA
        ,DLRLOC
        ,DLRTYP
        ,DLRFDP
        ,DLRFDPC
        ,CDLRFOR
        ,CDLRDYS
        ,CDLRPMT
        ,CDLRPDD
        ,RECRSCD
        ,RECRSPC
        ,RECRSTM
        ,RECRSTC
        ,RECDAYP
        ,RECINT
        ,PARTID__CS
        ,PNFLAGS
        ,PAYEX6
        ,PAYEX7
        ,CPD120
        ,CPD150
        ,CPD180
        ,PPD120
        ,PPD150
        ,PPD180
        ,LPD120
        ,LPD150
        ,LPD180
        ,PCTREA
        ,PARTPC
        ,BILOLA
        ,YTDPEN
        ,PREPEN
        ,LTDPEN
        ,SUBPRM
        ,OVLFEE
        ,CLCIF__CS
        ,ADOTNB
        ,UNTPDLRFP
        ,MINUNTADV
        ,SYNDAGTNBR
        ,SYNDMBRNBR
        ,SHRNTLCRD
        ,CORRESBANK
        ,CRCYTYPE
        ,FRDALRT
        ,ARGPRDCOD
        ,CONSTR
        ,RGRISK
        ,TEASER
        ,CSPLTV
        ,EXSLTV
        ,EXRELP
        ,LNATMCRD
        ,HMDA
        ,SALESAC
        ,RTCCTR
        ,AFFILIATE
        ,MINBIL
        ,INTFIR
        ,STEPRT
        ,LNLANG
        ,APPDLNS
        ,NBRPDPMT
        ,APPPDLNS
        ,NPDAPPLT
        ,NPDPPLTR
        ,POSTEXPC
        ,SHDOW6
        ,SHDOW7
        ,RSHTPC6
        ,ODIBAS
        ,MTDADV__CS
        ,YRLCALC
        ,LOCCALC
        ,LOCFREQ
        ,LOCFRCD
        ,LOCFDT6
        ,LOCFDT7
        ,LOCFDY
        ,UNUCALC
        ,UNUFREQ
        ,UNUFRCD
        ,UNUFDT6
        ,UNUFDT7
        ,UNUFDY
        ,DYSZROCUR
        ,DYSZRO01
        ,DYSZRO02
        ,DYSZRO03
        ,DYSZRO04
        ,DYSZRO05
        ,DYSZRO06
        ,DYSZRO07
        ,DYSZRO08
        ,DYSZRO09
        ,DYSZRO10
        ,DYSZRO11
        ,DYSZRO12
        ,LPTYPE
        ,CPASSLN
        ,RPASSLN
        ,RPASSPCT
        ,PPSDT6
        ,PPSDT7
        ,PPSFRQ
        ,PPSCOD
        ,PPDBAL
        ,PPCURT
        ,PPEXP6
        ,PPEXP7
        ,CURNTC6
        ,CURNTC7
        ,CUREXP6
        ,CUREXP7
        ,CURALL6
        ,CURALL7
        ,INVALL6
        ,INVALL7
        ,RECOUPASD
        ,RECOUPYTD
        ,RECOUPPRE
        ,NSFNTCYTD
        ,NSFNTCPRE
        ,PAYCURT
        ,PAYCOUP
        ,RECPRNDT6
        ,RECPRNDT7
        ,CURTAMT1
        ,CURTAMT2
        ,DATEPEN16
        ,DATEPEN17
        ,DATEPEN26
        ,DATEPEN27
        ,LNTIER
        ,LQBL__2
        ,LQRT__2
        ,LQBL__3
        ,LQRT__3
        ,LQBL__4
        ,LQRT__4
        ,LQBL__5
        ,LQRT__5
        ,LQBL__6
        ,LQRT__6
        ,LQBL__7
        ,LQRT__7
        ,LQBL__8
        ,LQRT__8
        ,LQBL__9
        ,LQRT__9
        ,LQBL__10
        ,LQRT__10
        ,LSPLIT
        ,LIENPOSN
        ,ODPUSEHOLD
        ,PENRAT__CS
        ,PENNEWRT
        ,PENRATE
        ,PENPDAYS
        ,PENAFTNT
        ,PENRVTM
        ,PENRVTMC
        ,PENNOTD6
        ,PENNOTD7
        ,PENSTDT6
        ,PENSTDT7
        ,PENRVDT6
        ,PENRVDT7
        ,PENRATYN
        ,PENLNRATE
        ,PPVARI
        ,PPVCODE
        ,SPECLEN
        ,TSAMT1
        ,TSAMT2
        ,TSDATE1
        ,TSDATE2
        ,TS1CHAR1
        ,TS1CHAR2
        ,TS2CHAR3
        ,TS2CHAR4
        ,PRMRSKRAT
        ,RSKRATDT6
        ,RSKRATDT7
        ,SPLRSKRAT1
        ,SPLRSKAMT1
        ,SPLRSKRAT2
        ,SPLRSKPCT2
        ,SPLRSKAMT2
        ,SPLRSKRAT3
        ,SPLRSKPCT3
        ,SPLRSKAMT3
        ,SPLRSKCA1
        ,NGAMORG__CS
        ,AUTOBIL
        ,YTDESC
        ,PRVESC
        ,YTDFEE
        ,PRVFEE
        ,PRVPRN
        ,PRIDWE
        ,ARMNTC
        ,INARMD
        ,ARMSNT
        ,EINDT6
        ,EINDT7
        ,LoanSetupDate
        ,OriginalLoanDate
        ,MaturityDate
        ,NextReviewDate
        ,FirstPaymentDate
        ,LastPaymentDate
        ,NextPaymentDueDate
        ,DateLastRenewed
        ,OriginalMaturityDate
        ,RateReviewDate
        ,NonAccrualDate
        ,ChargeOffDate
        ,LastActivityDate
        ,ForeclosureDate
        ,DatePaidOff
        ,AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6), AsofDate, 112)) AS YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE AsofDate > COALESCE((SELECT MAX(AsofDate) FROM "DQP_BRONZE"."dbo"."bronze_jh_lnmast"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data