-- NAME: BRONZE_JH_DDMAST
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: June 28, 2024



WITH landing_data AS (
    SELECT
        RECID
        ,BRANCH
        ,ACCTNO
        ,ACTYPE
        ,ARGPRDCOD
        ,SNAME
        ,CIFNO
        ,ALTADD
        ,ADDNAM
        ,ALTNAM
        ,GROUP__CS
        ,GLCOST
        ,GLPROD
        ,OFFICR
        ,COFFCR
        ,[STATUS]
        ,NOCLOS
        ,ALWROP
        ,EXCLUD
        ,CLASS
        ,SPCODE
        ,HDCODE
        ,ATCODE
        ,SICODE
        ,PCHECK
        ,PCHACT
        ,PCHATY
        ,DATOP7
        ,DATEN7
        ,DTOD7
        ,DLA7
        ,DLC7
        ,DLINP7
        ,DLSTM7
        ,DLFLM7
        ,DTLDP7
        ,DTSC7
        ,DTCLS7
        ,DTDOR7
        ,DTESC7
        ,DTCHO7
        ,CONVDT7
        ,CLSPND7
        ,DLSVCHG7
        ,DATOP6
        ,DATEN6
        ,DTOD6
        ,DLA6
        ,DLC6
        ,DLINP6
        ,DLSTM6
        ,DLFLM6
        ,DTLDP6
        ,DTSC6
        ,DTCLS6
        ,DTDOR6
        ,DTESC6
        ,DTCHO6
        ,CONVDT6
        ,CLSPND6
        ,DLSVCHG6
        ,AMTDP
        ,AMTLWD
        ,HOLD
        ,CBAL
        ,YBAL
        ,STMBAL
        ,MINBAL
        ,HGHBAL
        ,COLECT
        ,YESCOL
        ,ABAL
        ,AGGDAY
        ,AGGAMT
        ,AGGCOL
        ,AGGDAN
        ,AGGCON
        ,AGGAMN
        ,AGCODN
        ,AGGDAS
        ,AGGAMS
        ,AGGCOS
        ,MINBAI
        ,HGHBAI
        ,AGGDAI
        ,AGGAMI
        ,AGGCOI
        ,ACCRUE
        ,YSTACC
        ,ALTACR
        ,ODINT
        ,YTDINT
        ,YTDSC
        ,YTDODF
        ,YTDNSF
        ,RTCKCY
        ,RTCKWY
        ,ODWVEY
        ,ATCRNY
        ,ATDRNY
        ,YTDSCW
        ,FEEYTD
        ,NOCRL
        ,AMTCRL
        ,NODRL
        ,AMTDRL
        ,RTCKCL
        ,RTCKWL
        ,ODWVEL
        ,ATCRNL
        ,ATDRNL
        ,LYSCW
        ,FEELY
        ,LYTDIN
        ,LYTDSC
        ,LYTDOF
        ,LYTDNF
        ,LINTPD
        ,LSCAMT
        ,STCYC
        ,STCODE
        ,INTCYC
        ,SCCYC
        ,SCCODE
        ,SCTYPE
        ,DDUSER
        ,NXSTM6
        ,NXSTM7
        ,STMDAY
        ,STMFRC
        ,STMFRQ
        ,STMPR
        ,STMSC
        ,STMIN
        ,NODR
        ,AMTDR
        ,NOCR
        ,AMTCR
        ,SCDR
        ,SCDRA
        ,SCCR
        ,SCCRA
        ,NODRM
        ,AMTDRM
        ,NOCRM
        ,AMTCRM
        ,NODRC
        ,AMTDRC
        ,NOCRC
        ,AMTCRC
        ,NOCRY
        ,AMTCRY
        ,NODRY
        ,AMTDRY
        ,SCDRC
        ,SCDRAC
        ,SCCRC
        ,SCCRAC
        ,NODRP
        ,AMTDRP
        ,NOCRP
        ,AMTCRP
        ,ONSCKP
        ,FORCKP
        ,LOCLCKP
        ,AGGDYP
        ,AGGAMP
        ,AGGCOP
        ,DDAGDP
        ,DDAGBP
        ,MINBALP
        ,CBALP
        ,SCDRCP
        ,SCCRCP
        ,ATCRNO
        ,ATCRAO
        ,ATDRNO
        ,ATDRAO
        ,ATTFNO
        ,ATTFAO
        ,ATIQNO
        ,ATCRNF
        ,ATCRAF
        ,ATDRNF
        ,ATDRAF
        ,ATTFNF
        ,ATTFAF
        ,ATIQNF
        ,ATISD6
        ,ATISD7
        ,AMTNSF
        ,ODLMT
        ,ODMCDE
        ,SGCODE
        ,CHKGTY
        ,ATMCRD
        ,COMBIN
        ,MALHLD
        ,AUTNSF
        ,CODCHG
        ,CODFEE
        ,CODFMX
        ,CODFPC
        ,CODFDY
        ,CODFBL
        ,HIVOL
        ,TIMOD
        ,TIMOD1
        ,TIMOD2
        ,TIMOD3
        ,TIMOD4
        ,TIMOD5
        ,ODLSYR
        ,ODLTD
        ,ITMOD
        ,ITMOD1
        ,ITMOD2
        ,ITMOD3
        ,ITMOD4
        ,ITMOD5
        ,ITODLY
        ,ITODLT
        ,DYSOD
        ,DYSOD1
        ,DYSOD2
        ,DYSOD3
        ,DYSOD4
        ,DYSOD5
        ,DYODLY
        ,DYODLT
        ,CDYOD
        ,RELACT
        ,RACTTP
        ,ONUSCK
        ,FORNCK
        ,LOCLCK
        ,LSTPST
        ,RATE
        ,RATE__CS
        ,PVAR
        ,PVAR1
        ,PFLOOR
        ,PCEIL
        ,REVDT7
        ,REVDT6
        ,TERM
        ,TERMCD
        ,DR3
        ,DR6
        ,DR3LTD
        ,DR6LTD
        ,DR3EXC
        ,DR6EXC
        ,DR3EXCY
        ,DR6EXCY
        ,DR3EXCL
        ,DR6EXCL
        ,DR3EXC01
        ,DR3EXC02
        ,DR3EXC03
        ,DR3EXC04
        ,DR3EXC05
        ,DR3EXC06
        ,DR3EXC07
        ,DR3EXC08
        ,DR3EXC09
        ,DR3EXC10
        ,DR3EXC11
        ,DR3EXC12
        ,DR6EXC01
        ,DR6EXC02
        ,DR6EXC03
        ,DR6EXC04
        ,DR6EXC05
        ,DR6EXC06
        ,DR6EXC07
        ,DR6EXC08
        ,DR6EXC09
        ,DR6EXC10
        ,DR6EXC11
        ,DR6EXC12
        ,DR301
        ,DR302
        ,DR303
        ,DR304
        ,DR305
        ,DR306
        ,DR307
        ,DR308
        ,DR309
        ,DR310
        ,DR311
        ,DR312
        ,DR601
        ,DR602
        ,DR603
        ,DR604
        ,DR605
        ,DR606
        ,DR607
        ,DR608
        ,DR609
        ,DR610
        ,DR611
        ,DR612
        ,CASHDP
        ,FEECTD
        ,CASHPO
        ,QAGDAY
        ,QAGBAL
        ,QAGCOL
        ,ALEDQ1
        ,ALEDQ2
        ,ALEDQ3
        ,ALEDQ4
        ,ACOLQ1
        ,ACOLQ2
        ,ACOLQ3
        ,ACOLQ4
        ,DDAGGD
        ,DDAGGB
        ,DDINTE
        ,DDSIC1
        ,DDSIC2
        ,DDSIC3
        ,DDSIC4
        ,SPMESG
        ,XMASPL
        ,TIMRT
        ,TIMRT1
        ,TIMRT2
        ,TIMRT3
        ,TIMRT4
        ,TIMRT5
        ,RTLSYR
        ,RTLTD
        ,ITMRT
        ,ITMRT1
        ,ITMRT2
        ,ITMRT3
        ,ITMRT4
        ,ITMRT5
        ,ITRTLY
        ,ITRTLT
        ,DYSRT
        ,DYSRT1
        ,DYSRT2
        ,DYSRT3
        ,DYSRT4
        ,DYSRT5
        ,DYRTLY
        ,DYRTLT
        ,CDYRT
        ,TMNSF
        ,TMNFQ1
        ,TMNFQ2
        ,TMNFQ3
        ,TMNFQ4
        ,TMNFQ5
        ,TMNFLY
        ,TNFLTD
        ,ITMNSF
        ,ITMFQ1
        ,ITMFQ2
        ,ITMFQ3
        ,ITMFQ4
        ,ITMFQ5
        ,ITMFLY
        ,ITMFLT
        ,DYSNSF
        ,DYSFQ1
        ,DYSFQ2
        ,DYSFQ3
        ,DYSFQ4
        ,DYSFQ5
        ,DYSFLY
        ,DYSFLT
        ,CDYNSF
        ,TTFLOT
        ,TTFLAV
        ,TTFLCA
        ,NOENCL
        ,EFTFLG
        ,MINCHG
        ,NSFMAX
        ,ODIMAX
        ,FLUC__M
        ,FLUC__Y
        ,KITE__CS
        ,DKITE__CS
        ,DKITYR
        ,SMSA
        ,CRALOC
        ,ZIPCOD
        ,INDCOD
        ,CENSUS
        ,WHCODE
        ,WHSCOD
        ,[STATE]
        ,CRASTA
        ,COUNTY
        ,WDATE6
        ,WDATE7
        ,WALTAC
        ,WALTTP
        ,WALTRT
        ,WALTSR
        ,WHMTD
        ,WHQTD
        ,WHYTD
        ,WHSMTD
        ,WHSQTD
        ,WHSYTD
        ,WHLYR
        ,WHSLYR
        ,NFCODE
        ,AFCODE
        ,AACODE
        ,MAILCD
        ,STMPAS
        ,TLRINQ
        ,PRTCKO
        ,TRUNC
        ,IPERPG
        ,IFROBK
        ,ICKORD
        ,ICREDS
        ,RPBLK__CS
        ,MTDSC
        ,MTDINT
        ,MTDAGB
        ,MTDCOL
        ,MTDAGD
        ,RTCKCM
        ,RTCKWM
        ,ODCHGM
        ,ODWVEM
        ,RETCKM
        ,TIMODM
        ,TIMNFM
        ,MINBLM
        ,HGHBLM
        ,MTDSCW
        ,FEEMTD
        ,CGOAMT
        ,SECURE
        ,PRTMMDC
        ,PRTMMDD6
        ,PRTMMDD7
        ,DT6NOT__1
        ,DT7NOT__1
        ,DT6NOT__2
        ,DT7NOT__2
        ,DT6NOT__3
        ,DT7NOT__3
        ,DT6NOT__4
        ,DT7NOT__4
        ,DT6NOT__5
        ,DT7NOT__5
        ,DDPIC1
        ,DDPIC2
        ,DDPDT1
        ,DDPD61
        ,DDPDT2
        ,DDPD62
        ,DDPAM1
        ,DDPAM2
        ,USAGB1
        ,USAGB2
        ,USAGD1
        ,USAGD2
        ,US1DT6
        ,US1DT7
        ,US2DT6
        ,US2DT7
        ,USALF1
        ,USALF2
        ,USNUM1
        ,USNUM2
        ,CGIBKC
        ,CGIBKM
        ,CGIBK1
        ,CGIBK2
        ,CGIBK3
        ,CGIBK4
        ,CGIBK5
        ,CGILYR
        ,CGILTD
        ,CGTBKC
        ,CGTBKM
        ,CGTBK1
        ,CGTBK2
        ,CGTBK3
        ,CGTBK4
        ,CGTBK5
        ,CGTLYR
        ,CGTLTD
        ,DDREGP
        ,CALLREP
        ,INTCALYR
        ,OAKBIFAMT
        ,OAKBIFDT6
        ,OAKBIFDT7
        ,OAKSAIFAMT
        ,OAKSAIFDT6
        ,OAKSAIFDT7
        ,OAKARSOLD
        ,OAKARSOLD6
        ,OAKARSOLD7
        ,FDICINSURD
        ,BIFMEMBER
        ,SAIFMEMBER
        ,DDCYCPERD__CS
        ,DDSTMPERD__CS
        ,DDSTCYRSFQ
        ,DDSTCYCGFQ
        ,DDCYCCHG__CS
        ,DDSTMCHG__CS
        ,DDSTMFMTCD
        ,DDCTDWAIVE
        ,DDMTDWAIVE
        ,DDQTDWAIVE
        ,DDYTDWAIVE
        ,DDLTDWAIVE
        ,DDCLOSEDRS
        ,DDPYINTEOM
        ,AGGDAINP
        ,AGGAMINP
        ,AGGCOINP
        ,DDAGGDNP
        ,DDAGGBNP
        ,DDINTENP
        ,DDODNOTDY1
        ,DDODNOTDY2
        ,DDODNOTDY3
        ,DDODNOTDY4
        ,DDODNOTDY5
        ,DDODNOTDY6
        ,DDODNOTDT6
        ,DDODNOTDT7
        ,DDODNOTSNT
        ,PSTAFTNSF
        ,LTDSCW
        ,DKITE__01
        ,DKITE__02
        ,DKITE__03
        ,DKITE__04
        ,DKITE__05
        ,DKITE__06
        ,DKITE__07
        ,DKITE__08
        ,DKITE__09
        ,DKITE__10
        ,DKITE__11
        ,DKITE__12
        ,DKITE__ST
        ,DKITE__ST01
        ,DKITE__ST02
        ,DKITE__ST03
        ,DKITE__ST04
        ,DKITE__ST05
        ,DKITE__ST06
        ,DKITE__ST07
        ,DKITE__ST08
        ,DKITE__ST09
        ,DKITE__ST10
        ,DKITE__ST11
        ,DKITE__ST12
        ,DKITE__Q
        ,DKITE__Q01
        ,DKITE__Q02
        ,DKITE__Q03
        ,DKITE__Q04
        ,DKITE__LTD
        ,DKITEPYR
        ,FLUC__M01
        ,FLUC__M02
        ,FLUC__M03
        ,FLUC__M04
        ,FLUC__M05
        ,FLUC__M06
        ,FLUC__M07
        ,FLUC__M08
        ,FLUC__M09
        ,FLUC__M10
        ,FLUC__M11
        ,FLUC__M12
        ,FLUC__ST
        ,FLUC__ST01
        ,FLUC__ST02
        ,FLUC__ST03
        ,FLUC__ST04
        ,FLUC__ST05
        ,FLUC__ST06
        ,FLUC__ST07
        ,FLUC__ST08
        ,FLUC__ST09
        ,FLUC__ST10
        ,FLUC__ST11
        ,FLUC__ST12
        ,FLUC__Q
        ,FLUC__Q01
        ,FLUC__Q02
        ,FLUC__Q03
        ,FLUC__Q04
        ,FLUC__LTD
        ,FLUC__PYR
        ,FRDALRT
        ,CHALTACCT
        ,CHALTACTY
        ,ALLREDEP
        ,NOREDEP
        ,SNDREDPNO
        ,RDITCY
        ,RDITMO
        ,RDITQ1
        ,RDITQ2
        ,RDITQ3
        ,RDITQ4
        ,RDITQ5
        ,RDILYR
        ,RDILTD
        ,RDTMCY
        ,RDTMMO
        ,RDTMQ1
        ,RDTMQ2
        ,RDTMQ3
        ,RDTMQ4
        ,RDTMQ5
        ,RDTLYR
        ,RDTLTD
        ,DDJHA1
        ,DDJHA2
        ,DDJHA3
        ,DDJHA4
        ,DDJHA11
        ,DDJHA12
        ,DDJHA13
        ,DDJHA14
        ,DDJHA61
        ,DDJHA71
        ,DDCTDREVOP
        ,DDMTDREVOP
        ,DDQTDREVOP
        ,DDYTDREVOP
        ,DDLTDREVOP
        ,DDMTDSCREV
        ,DDYTDSCREV
        ,DDLTDSCREV
        ,DDPYRSCREV
        ,DDCTDFEECG
        ,DDMTDFEECG
        ,DDQTDFEECG
        ,DDYTDFEECG
        ,DDLTDFEECG
        ,DDYTDFEESC
        ,DDLTDFEESC
        ,DDPYRFEESC
        ,DDCTDLOSOP
        ,DDMTDLOSOP
        ,DDQTDLOSOP
        ,DDYTDLOSOP
        ,DDLTDLOSOP
        ,DDMTDLOSCG
        ,DDYTDLOSCG
        ,DDLTDLOSCG
        ,DDPYRLOSCG
        ,DDCTDREFND
        ,DDMTDREFND
        ,DDQTDREFND
        ,DDYTDREFND
        ,DDLTDREFND
        ,UCFMAX
        ,TMUCF
        ,TMNUCFQ1
        ,TMNUCFQ2
        ,TMNUCFQ3
        ,TMNUCFQ4
        ,TMNUCFQ5
        ,TMNUCFLY
        ,TNUCFLTD
        ,ITMUCF
        ,ITMUCFQ1
        ,ITMUCFQ2
        ,ITMUCFQ3
        ,ITMUCFQ4
        ,ITMUCFQ5
        ,ITMUCFLY
        ,ITMUCFLT
        ,DYSUCF
        ,DYSUCFQ1
        ,DYSUCFQ2
        ,DYSUCFQ3
        ,DYSUCFQ4
        ,DYSUCFQ5
        ,DYSUCFLY
        ,DYSUCFLT
        ,CDYUCF
        ,YTDUCF
        ,LYTDUCF
        ,AMTUCF
        ,TIMUCFM
        ,SALESAC
        ,ODRGRPT
        ,ODUNLIMIT
        ,ODCRLIMIT
        ,ODUSLIMIT
        ,ODRPTTYPE
        ,HSATYPE
        ,STDNSFP
        ,STDNSFR
        ,STDODAC
        ,YTDNSFP
        ,YTDNSFR
        ,YTDODAC
        ,TDYNSFC
        ,CODDAY
        ,BYRACR
        ,CODDAYCN
        ,CDYODBUS
        ,ACHCR__CSD
        ,ACHCR__CS
        ,ACHDR__CSD
        ,ACHDR__CS
        ,MSAVLTAB1
        ,MSAVLTAB2
        ,REGAGG
        ,PYTDPDOD
        ,PYTDRTIT
        ,DDLANG
        ,DDPSCOD
        ,DDPSFECODE
        ,REGCCNEW
        ,DDIMGACTFE
        ,WRWVCODE
        ,CRDOPT
        ,CRDOPTB
        ,CRDOPTE
        ,CRDOPTDT6
        ,CRDOPTDT7
        ,CRDODAMT
        ,CRDODAMTC
        ,CRDODCTD
        ,CRDODQTD
        ,CRDODYTD
        ,CRDODPYTD
        ,CDYODCHGA
        ,CDYODCHGB
        ,STMTDM
        ,DDITEMSBAL
        ,DDNSFFEBAL
        ,DDODCHGBAL
        ,DDSCBAL
        ,DDUCFBAL
        ,DDYITEMBAL
        ,DDYNSFFBAL
        ,DDYODCGBAL
        ,DDYSCBAL
        ,DDYUCFBAL
        ,DDAUTOCG
        ,DDDATECOL6
        ,DDDATECOL7
        ,PROMOCODE
        ,PROMOEXP6
        ,PROMOEXP7
        ,PROMOVAR
        ,PROMOVARC
        ,DDMTSA1
        ,DDMTSA2
        ,DDMTSA3
        ,DDMTSA4
        ,DDMTSN1
        ,DDMTSN2
        ,EXODCUR
        ,EXOD01
        ,EXOD02
        ,EXOD03
        ,EXOD04
        ,EXOD05
        ,EXOD06
        ,EXOD07
        ,EXOD08
        ,EXOD09
        ,EXOD10
        ,EXOD11
        ,EXOD12
        ,EXODLTD
        ,EXODACDT6
        ,EXODACDT7
        ,EXODLRDT6
        ,EXODLRDT7
        ,EXODRESET
        ,EXODREVOK
        ,EXODRPT
        ,EXODGCDT6
        ,EXODGCDT7
        ,EXODSMDT6
        ,EXODSMDT7
        ,DDHIGHOD
        ,DDPRNTADND
        ,DDADNDCNT
        ,DDCHGBFEE
        ,DDPSAUTCOD
        ,MTDINTACC
        ,dbo.ConvertJhDateJulianToDatetime(DATOP7) as DateOpened
        ,dbo.ConvertJhDateJulianToDatetime(DATEN7) as DateEntered
        ,dbo.ConvertJhDateJulianToDatetime(DTCLS7) as DateClosed
        ,dbo.ConvertJhDateJulianToDatetime(DDDATECOL7) as DateLastChargedOff
        ,dbo.ConvertJhDateJulianToDatetime(DLA7) as DateLastActive
        ,(SELECT CONVERT(DATE,dqp_landing.dbo.ConvertJhDateJulianToDatetime(POSTD7))
	        FROM dqp_landing.dbo.jh_ddpar1) as AsOfDate
        ,NULL as YEARMONTH
        ,LOADED_AT
    FROM
        "DQP_LANDING"."dbo"."JH_DDMAST"
),

bronze_data AS (
    SELECT
        RECID
        ,BRANCH
        ,ACCTNO
        ,ACTYPE
        ,ARGPRDCOD
        ,SNAME
        ,CIFNO
        ,ALTADD
        ,ADDNAM
        ,ALTNAM
        ,GROUP__CS
        ,GLCOST
        ,GLPROD
        ,OFFICR
        ,COFFCR
        ,[STATUS]
        ,NOCLOS
        ,ALWROP
        ,EXCLUD
        ,CLASS
        ,SPCODE
        ,HDCODE
        ,ATCODE
        ,SICODE
        ,PCHECK
        ,PCHACT
        ,PCHATY
        ,DATOP7
        ,DATEN7
        ,DTOD7
        ,DLA7
        ,DLC7
        ,DLINP7
        ,DLSTM7
        ,DLFLM7
        ,DTLDP7
        ,DTSC7
        ,DTCLS7
        ,DTDOR7
        ,DTESC7
        ,DTCHO7
        ,CONVDT7
        ,CLSPND7
        ,DLSVCHG7
        ,DATOP6
        ,DATEN6
        ,DTOD6
        ,DLA6
        ,DLC6
        ,DLINP6
        ,DLSTM6
        ,DLFLM6
        ,DTLDP6
        ,DTSC6
        ,DTCLS6
        ,DTDOR6
        ,DTESC6
        ,DTCHO6
        ,CONVDT6
        ,CLSPND6
        ,DLSVCHG6
        ,AMTDP
        ,AMTLWD
        ,HOLD
        ,CBAL
        ,YBAL
        ,STMBAL
        ,MINBAL
        ,HGHBAL
        ,COLECT
        ,YESCOL
        ,ABAL
        ,AGGDAY
        ,AGGAMT
        ,AGGCOL
        ,AGGDAN
        ,AGGCON
        ,AGGAMN
        ,AGCODN
        ,AGGDAS
        ,AGGAMS
        ,AGGCOS
        ,MINBAI
        ,HGHBAI
        ,AGGDAI
        ,AGGAMI
        ,AGGCOI
        ,ACCRUE
        ,YSTACC
        ,ALTACR
        ,ODINT
        ,YTDINT
        ,YTDSC
        ,YTDODF
        ,YTDNSF
        ,RTCKCY
        ,RTCKWY
        ,ODWVEY
        ,ATCRNY
        ,ATDRNY
        ,YTDSCW
        ,FEEYTD
        ,NOCRL
        ,AMTCRL
        ,NODRL
        ,AMTDRL
        ,RTCKCL
        ,RTCKWL
        ,ODWVEL
        ,ATCRNL
        ,ATDRNL
        ,LYSCW
        ,FEELY
        ,LYTDIN
        ,LYTDSC
        ,LYTDOF
        ,LYTDNF
        ,LINTPD
        ,LSCAMT
        ,STCYC
        ,STCODE
        ,INTCYC
        ,SCCYC
        ,SCCODE
        ,SCTYPE
        ,DDUSER
        ,NXSTM6
        ,NXSTM7
        ,STMDAY
        ,STMFRC
        ,STMFRQ
        ,STMPR
        ,STMSC
        ,STMIN
        ,NODR
        ,AMTDR
        ,NOCR
        ,AMTCR
        ,SCDR
        ,SCDRA
        ,SCCR
        ,SCCRA
        ,NODRM
        ,AMTDRM
        ,NOCRM
        ,AMTCRM
        ,NODRC
        ,AMTDRC
        ,NOCRC
        ,AMTCRC
        ,NOCRY
        ,AMTCRY
        ,NODRY
        ,AMTDRY
        ,SCDRC
        ,SCDRAC
        ,SCCRC
        ,SCCRAC
        ,NODRP
        ,AMTDRP
        ,NOCRP
        ,AMTCRP
        ,ONSCKP
        ,FORCKP
        ,LOCLCKP
        ,AGGDYP
        ,AGGAMP
        ,AGGCOP
        ,DDAGDP
        ,DDAGBP
        ,MINBALP
        ,CBALP
        ,SCDRCP
        ,SCCRCP
        ,ATCRNO
        ,ATCRAO
        ,ATDRNO
        ,ATDRAO
        ,ATTFNO
        ,ATTFAO
        ,ATIQNO
        ,ATCRNF
        ,ATCRAF
        ,ATDRNF
        ,ATDRAF
        ,ATTFNF
        ,ATTFAF
        ,ATIQNF
        ,ATISD6
        ,ATISD7
        ,AMTNSF
        ,ODLMT
        ,ODMCDE
        ,SGCODE
        ,CHKGTY
        ,ATMCRD
        ,COMBIN
        ,MALHLD
        ,AUTNSF
        ,CODCHG
        ,CODFEE
        ,CODFMX
        ,CODFPC
        ,CODFDY
        ,CODFBL
        ,HIVOL
        ,TIMOD
        ,TIMOD1
        ,TIMOD2
        ,TIMOD3
        ,TIMOD4
        ,TIMOD5
        ,ODLSYR
        ,ODLTD
        ,ITMOD
        ,ITMOD1
        ,ITMOD2
        ,ITMOD3
        ,ITMOD4
        ,ITMOD5
        ,ITODLY
        ,ITODLT
        ,DYSOD
        ,DYSOD1
        ,DYSOD2
        ,DYSOD3
        ,DYSOD4
        ,DYSOD5
        ,DYODLY
        ,DYODLT
        ,CDYOD
        ,RELACT
        ,RACTTP
        ,ONUSCK
        ,FORNCK
        ,LOCLCK
        ,LSTPST
        ,RATE
        ,RATE__CS
        ,PVAR
        ,PVAR1
        ,PFLOOR
        ,PCEIL
        ,REVDT7
        ,REVDT6
        ,TERM
        ,TERMCD
        ,DR3
        ,DR6
        ,DR3LTD
        ,DR6LTD
        ,DR3EXC
        ,DR6EXC
        ,DR3EXCY
        ,DR6EXCY
        ,DR3EXCL
        ,DR6EXCL
        ,DR3EXC01
        ,DR3EXC02
        ,DR3EXC03
        ,DR3EXC04
        ,DR3EXC05
        ,DR3EXC06
        ,DR3EXC07
        ,DR3EXC08
        ,DR3EXC09
        ,DR3EXC10
        ,DR3EXC11
        ,DR3EXC12
        ,DR6EXC01
        ,DR6EXC02
        ,DR6EXC03
        ,DR6EXC04
        ,DR6EXC05
        ,DR6EXC06
        ,DR6EXC07
        ,DR6EXC08
        ,DR6EXC09
        ,DR6EXC10
        ,DR6EXC11
        ,DR6EXC12
        ,DR301
        ,DR302
        ,DR303
        ,DR304
        ,DR305
        ,DR306
        ,DR307
        ,DR308
        ,DR309
        ,DR310
        ,DR311
        ,DR312
        ,DR601
        ,DR602
        ,DR603
        ,DR604
        ,DR605
        ,DR606
        ,DR607
        ,DR608
        ,DR609
        ,DR610
        ,DR611
        ,DR612
        ,CASHDP
        ,FEECTD
        ,CASHPO
        ,QAGDAY
        ,QAGBAL
        ,QAGCOL
        ,ALEDQ1
        ,ALEDQ2
        ,ALEDQ3
        ,ALEDQ4
        ,ACOLQ1
        ,ACOLQ2
        ,ACOLQ3
        ,ACOLQ4
        ,DDAGGD
        ,DDAGGB
        ,DDINTE
        ,DDSIC1
        ,DDSIC2
        ,DDSIC3
        ,DDSIC4
        ,SPMESG
        ,XMASPL
        ,TIMRT
        ,TIMRT1
        ,TIMRT2
        ,TIMRT3
        ,TIMRT4
        ,TIMRT5
        ,RTLSYR
        ,RTLTD
        ,ITMRT
        ,ITMRT1
        ,ITMRT2
        ,ITMRT3
        ,ITMRT4
        ,ITMRT5
        ,ITRTLY
        ,ITRTLT
        ,DYSRT
        ,DYSRT1
        ,DYSRT2
        ,DYSRT3
        ,DYSRT4
        ,DYSRT5
        ,DYRTLY
        ,DYRTLT
        ,CDYRT
        ,TMNSF
        ,TMNFQ1
        ,TMNFQ2
        ,TMNFQ3
        ,TMNFQ4
        ,TMNFQ5
        ,TMNFLY
        ,TNFLTD
        ,ITMNSF
        ,ITMFQ1
        ,ITMFQ2
        ,ITMFQ3
        ,ITMFQ4
        ,ITMFQ5
        ,ITMFLY
        ,ITMFLT
        ,DYSNSF
        ,DYSFQ1
        ,DYSFQ2
        ,DYSFQ3
        ,DYSFQ4
        ,DYSFQ5
        ,DYSFLY
        ,DYSFLT
        ,CDYNSF
        ,TTFLOT
        ,TTFLAV
        ,TTFLCA
        ,NOENCL
        ,EFTFLG
        ,MINCHG
        ,NSFMAX
        ,ODIMAX
        ,FLUC__M
        ,FLUC__Y
        ,KITE__CS
        ,DKITE__CS
        ,DKITYR
        ,SMSA
        ,CRALOC
        ,ZIPCOD
        ,INDCOD
        ,CENSUS
        ,WHCODE
        ,WHSCOD
        ,[STATE]
        ,CRASTA
        ,COUNTY
        ,WDATE6
        ,WDATE7
        ,WALTAC
        ,WALTTP
        ,WALTRT
        ,WALTSR
        ,WHMTD
        ,WHQTD
        ,WHYTD
        ,WHSMTD
        ,WHSQTD
        ,WHSYTD
        ,WHLYR
        ,WHSLYR
        ,NFCODE
        ,AFCODE
        ,AACODE
        ,MAILCD
        ,STMPAS
        ,TLRINQ
        ,PRTCKO
        ,TRUNC
        ,IPERPG
        ,IFROBK
        ,ICKORD
        ,ICREDS
        ,RPBLK__CS
        ,MTDSC
        ,MTDINT
        ,MTDAGB
        ,MTDCOL
        ,MTDAGD
        ,RTCKCM
        ,RTCKWM
        ,ODCHGM
        ,ODWVEM
        ,RETCKM
        ,TIMODM
        ,TIMNFM
        ,MINBLM
        ,HGHBLM
        ,MTDSCW
        ,FEEMTD
        ,CGOAMT
        ,SECURE
        ,PRTMMDC
        ,PRTMMDD6
        ,PRTMMDD7
        ,DT6NOT__1
        ,DT7NOT__1
        ,DT6NOT__2
        ,DT7NOT__2
        ,DT6NOT__3
        ,DT7NOT__3
        ,DT6NOT__4
        ,DT7NOT__4
        ,DT6NOT__5
        ,DT7NOT__5
        ,DDPIC1
        ,DDPIC2
        ,DDPDT1
        ,DDPD61
        ,DDPDT2
        ,DDPD62
        ,DDPAM1
        ,DDPAM2
        ,USAGB1
        ,USAGB2
        ,USAGD1
        ,USAGD2
        ,US1DT6
        ,US1DT7
        ,US2DT6
        ,US2DT7
        ,USALF1
        ,USALF2
        ,USNUM1
        ,USNUM2
        ,CGIBKC
        ,CGIBKM
        ,CGIBK1
        ,CGIBK2
        ,CGIBK3
        ,CGIBK4
        ,CGIBK5
        ,CGILYR
        ,CGILTD
        ,CGTBKC
        ,CGTBKM
        ,CGTBK1
        ,CGTBK2
        ,CGTBK3
        ,CGTBK4
        ,CGTBK5
        ,CGTLYR
        ,CGTLTD
        ,DDREGP
        ,CALLREP
        ,INTCALYR
        ,OAKBIFAMT
        ,OAKBIFDT6
        ,OAKBIFDT7
        ,OAKSAIFAMT
        ,OAKSAIFDT6
        ,OAKSAIFDT7
        ,OAKARSOLD
        ,OAKARSOLD6
        ,OAKARSOLD7
        ,FDICINSURD
        ,BIFMEMBER
        ,SAIFMEMBER
        ,DDCYCPERD__CS
        ,DDSTMPERD__CS
        ,DDSTCYRSFQ
        ,DDSTCYCGFQ
        ,DDCYCCHG__CS
        ,DDSTMCHG__CS
        ,DDSTMFMTCD
        ,DDCTDWAIVE
        ,DDMTDWAIVE
        ,DDQTDWAIVE
        ,DDYTDWAIVE
        ,DDLTDWAIVE
        ,DDCLOSEDRS
        ,DDPYINTEOM
        ,AGGDAINP
        ,AGGAMINP
        ,AGGCOINP
        ,DDAGGDNP
        ,DDAGGBNP
        ,DDINTENP
        ,DDODNOTDY1
        ,DDODNOTDY2
        ,DDODNOTDY3
        ,DDODNOTDY4
        ,DDODNOTDY5
        ,DDODNOTDY6
        ,DDODNOTDT6
        ,DDODNOTDT7
        ,DDODNOTSNT
        ,PSTAFTNSF
        ,LTDSCW
        ,DKITE__01
        ,DKITE__02
        ,DKITE__03
        ,DKITE__04
        ,DKITE__05
        ,DKITE__06
        ,DKITE__07
        ,DKITE__08
        ,DKITE__09
        ,DKITE__10
        ,DKITE__11
        ,DKITE__12
        ,DKITE__ST
        ,DKITE__ST01
        ,DKITE__ST02
        ,DKITE__ST03
        ,DKITE__ST04
        ,DKITE__ST05
        ,DKITE__ST06
        ,DKITE__ST07
        ,DKITE__ST08
        ,DKITE__ST09
        ,DKITE__ST10
        ,DKITE__ST11
        ,DKITE__ST12
        ,DKITE__Q
        ,DKITE__Q01
        ,DKITE__Q02
        ,DKITE__Q03
        ,DKITE__Q04
        ,DKITE__LTD
        ,DKITEPYR
        ,FLUC__M01
        ,FLUC__M02
        ,FLUC__M03
        ,FLUC__M04
        ,FLUC__M05
        ,FLUC__M06
        ,FLUC__M07
        ,FLUC__M08
        ,FLUC__M09
        ,FLUC__M10
        ,FLUC__M11
        ,FLUC__M12
        ,FLUC__ST
        ,FLUC__ST01
        ,FLUC__ST02
        ,FLUC__ST03
        ,FLUC__ST04
        ,FLUC__ST05
        ,FLUC__ST06
        ,FLUC__ST07
        ,FLUC__ST08
        ,FLUC__ST09
        ,FLUC__ST10
        ,FLUC__ST11
        ,FLUC__ST12
        ,FLUC__Q
        ,FLUC__Q01
        ,FLUC__Q02
        ,FLUC__Q03
        ,FLUC__Q04
        ,FLUC__LTD
        ,FLUC__PYR
        ,FRDALRT
        ,CHALTACCT
        ,CHALTACTY
        ,ALLREDEP
        ,NOREDEP
        ,SNDREDPNO
        ,RDITCY
        ,RDITMO
        ,RDITQ1
        ,RDITQ2
        ,RDITQ3
        ,RDITQ4
        ,RDITQ5
        ,RDILYR
        ,RDILTD
        ,RDTMCY
        ,RDTMMO
        ,RDTMQ1
        ,RDTMQ2
        ,RDTMQ3
        ,RDTMQ4
        ,RDTMQ5
        ,RDTLYR
        ,RDTLTD
        ,DDJHA1
        ,DDJHA2
        ,DDJHA3
        ,DDJHA4
        ,DDJHA11
        ,DDJHA12
        ,DDJHA13
        ,DDJHA14
        ,DDJHA61
        ,DDJHA71
        ,DDCTDREVOP
        ,DDMTDREVOP
        ,DDQTDREVOP
        ,DDYTDREVOP
        ,DDLTDREVOP
        ,DDMTDSCREV
        ,DDYTDSCREV
        ,DDLTDSCREV
        ,DDPYRSCREV
        ,DDCTDFEECG
        ,DDMTDFEECG
        ,DDQTDFEECG
        ,DDYTDFEECG
        ,DDLTDFEECG
        ,DDYTDFEESC
        ,DDLTDFEESC
        ,DDPYRFEESC
        ,DDCTDLOSOP
        ,DDMTDLOSOP
        ,DDQTDLOSOP
        ,DDYTDLOSOP
        ,DDLTDLOSOP
        ,DDMTDLOSCG
        ,DDYTDLOSCG
        ,DDLTDLOSCG
        ,DDPYRLOSCG
        ,DDCTDREFND
        ,DDMTDREFND
        ,DDQTDREFND
        ,DDYTDREFND
        ,DDLTDREFND
        ,UCFMAX
        ,TMUCF
        ,TMNUCFQ1
        ,TMNUCFQ2
        ,TMNUCFQ3
        ,TMNUCFQ4
        ,TMNUCFQ5
        ,TMNUCFLY
        ,TNUCFLTD
        ,ITMUCF
        ,ITMUCFQ1
        ,ITMUCFQ2
        ,ITMUCFQ3
        ,ITMUCFQ4
        ,ITMUCFQ5
        ,ITMUCFLY
        ,ITMUCFLT
        ,DYSUCF
        ,DYSUCFQ1
        ,DYSUCFQ2
        ,DYSUCFQ3
        ,DYSUCFQ4
        ,DYSUCFQ5
        ,DYSUCFLY
        ,DYSUCFLT
        ,CDYUCF
        ,YTDUCF
        ,LYTDUCF
        ,AMTUCF
        ,TIMUCFM
        ,SALESAC
        ,ODRGRPT
        ,ODUNLIMIT
        ,ODCRLIMIT
        ,ODUSLIMIT
        ,ODRPTTYPE
        ,HSATYPE
        ,STDNSFP
        ,STDNSFR
        ,STDODAC
        ,YTDNSFP
        ,YTDNSFR
        ,YTDODAC
        ,TDYNSFC
        ,CODDAY
        ,BYRACR
        ,CODDAYCN
        ,CDYODBUS
        ,ACHCR__CSD
        ,ACHCR__CS
        ,ACHDR__CSD
        ,ACHDR__CS
        ,MSAVLTAB1
        ,MSAVLTAB2
        ,REGAGG
        ,PYTDPDOD
        ,PYTDRTIT
        ,DDLANG
        ,DDPSCOD
        ,DDPSFECODE
        ,REGCCNEW
        ,DDIMGACTFE
        ,WRWVCODE
        ,CRDOPT
        ,CRDOPTB
        ,CRDOPTE
        ,CRDOPTDT6
        ,CRDOPTDT7
        ,CRDODAMT
        ,CRDODAMTC
        ,CRDODCTD
        ,CRDODQTD
        ,CRDODYTD
        ,CRDODPYTD
        ,CDYODCHGA
        ,CDYODCHGB
        ,STMTDM
        ,DDITEMSBAL
        ,DDNSFFEBAL
        ,DDODCHGBAL
        ,DDSCBAL
        ,DDUCFBAL
        ,DDYITEMBAL
        ,DDYNSFFBAL
        ,DDYODCGBAL
        ,DDYSCBAL
        ,DDYUCFBAL
        ,DDAUTOCG
        ,DDDATECOL6
        ,DDDATECOL7
        ,PROMOCODE
        ,PROMOEXP6
        ,PROMOEXP7
        ,PROMOVAR
        ,PROMOVARC
        ,DDMTSA1
        ,DDMTSA2
        ,DDMTSA3
        ,DDMTSA4
        ,DDMTSN1
        ,DDMTSN2
        ,EXODCUR
        ,EXOD01
        ,EXOD02
        ,EXOD03
        ,EXOD04
        ,EXOD05
        ,EXOD06
        ,EXOD07
        ,EXOD08
        ,EXOD09
        ,EXOD10
        ,EXOD11
        ,EXOD12
        ,EXODLTD
        ,EXODACDT6
        ,EXODACDT7
        ,EXODLRDT6
        ,EXODLRDT7
        ,EXODRESET
        ,EXODREVOK
        ,EXODRPT
        ,EXODGCDT6
        ,EXODGCDT7
        ,EXODSMDT6
        ,EXODSMDT7
        ,DDHIGHOD
        ,DDPRNTADND
        ,DDADNDCNT
        ,DDCHGBFEE
        ,DDPSAUTCOD
        ,MTDINTACC
        ,DateOpened
        ,DateEntered
        ,DateClosed
        ,DateLastChargedOff
        ,DateLastActive
        ,AsOfDate
        ,CONVERT(INT, CONVERT(nvarchar(6),AsOfDate, 112)) AS YEARMONTH--YEARMONTH
        ,GETUTCDATE() AS LOADED_AT
    FROM landing_data
    
        WHERE AsOfDate > COALESCE((SELECT MAX(AsOfDate) FROM "DQP_BRONZE"."dbo"."bronze_jh_ddmast"),'1970-01-01 00:00:00.000')
    
)





SELECT * FROM bronze_data