-- NAME: BRONZE_PERSHING_CKFF_REC_B
-- CATEGORY: MODEL
-- MATURITY LEVEL: 0
-- LAYER: BRONZE
-- FREQUENCY: DAILY
-- LOAD TYPE: INCREMENTAL
-- TYPE: REPLICATION
-- DATE: February 12, 2025

{{
   config(
          materialized='incremental',
          incremental_strategy='append',
          tags=["pershing_standard"]
        )
}}

WITH landing_data AS
(
    SELECT DISTINCT
        TRANSACTION_CODE
        ,RECORD_TYPE
        ,RECORD_ID_SEQUENCE_NUMBER
        ,ACCOUNT_NUMBER
        ,CONVERT(DECIMAL(18,2), TRANSACTION_AMOUNT) AS TRANSACTION_AMOUNT
        ,LEGACY_INVESTMENT_PROFESSIONAL_IP_NUMBER
        ,PAYEE_INFORMATION_LINE_1
        ,PAYEE_INFORMATION_LINE_2
        ,PAYEE_INFORMATION_LINE_3
        ,CHECK_NUMBER_OR_CHECK_DIS_ADD_INFO_LINE_1
        ,CHECK_DIS_ADD_INFO_LINE_2
        ,CHECK_DIS_ADD_INFO_LINE_3
        ,CHECK_DIS_ADD_INFO_LINE_4
        ,CHECK_DIS_ADD_INFO_LINE_5
        ,CHECK_DIS_ADD_INFO_LINE_6
        ,CHECK_DIS_ADD_INFO_LINE_7
        ,CHECK_DIS_ADD_INFO_LINE_8
        ,CHECK_DIS_ADD_INFO_LINE_9
        ,THIRD_PARTY_INDICATOR
        ,EXPANDED_INVESTMENT_PROFESSIONAL_IP_NUMBER
        ,SUBSTRING(ACCOUNT_NUMBER, 1, 3) AS ACCOUNT_NUMBER_OFFICE
        ,SUBSTRING(ACCOUNT_NUMBER, 4, 6) AS ACCOUNT_NUMBER_BASE
        ,SUBSTRING(ACCOUNT_NUMBER, 10, 1) AS ACCOUNT_NUMBER_TYPE
        ,DATE_OF_DATA
        ,YEARMONTH
    FROM {{ source("pershing", "PERSHING_CKFF_B") }}
    {% if is_incremental() %}
        WHERE DATE_OF_DATA NOT IN (SELECT DISTINCT DATE_OF_DATA FROM {{ this }})
    {% endif %}
)

{% if execute %}
{{
    log("Running incrementally: " ~ is_incremental(), info=True)
}}
{% endif %}

SELECT *, GETUTCDATE() AS LOADED_AT FROM landing_data